// shots_corn.mjs — Levi Lapp Jardín (EN) · "How to Pick the Sweetest Corn... The Old Amish Way"
// Shotlist DENSO CLIPS-FIRST (estilo barcos/replantar): queries LIMPIAS, visuales, con MOVIMIENTO
// (manos sobre el choclo, chala, seda, granos, campo al amanecer, mercado, cocina, parrilla),
// NO la palabra literal del narrador, NO tutoriales con texto quemado. Lo consume build_corn.mjs.
// ~240 conceptos. Secciones ancladas a los timestamps reales del avatar (1125s).
export const SHOTS = {
  // ░░ HOOK1 (0-52s) — promesa: elegir el choclo más dulce en 10s, sin pelar — RÁFAGA ~1s ░░
  hook1: [
    ["corn_h1_bin_pile_store", ["pile of fresh sweet corn in a grocery store bin", "bin of corn cobs at a supermarket"], "el cajón de choclos en el súper"],
    ["corn_h1_hand_grab_ear", ["hand reaching for an ear of corn at a market", "picking up a corn cob from a stand"], "una mano agarrando un choclo"],
    ["corn_h1_peel_husk_store", ["hands peeling back a corn husk at a store", "pulling back green husk from corn cob"], "pelando la chala en la tienda"],
    ["corn_h1_torn_husks_pile", ["pile of torn corn husks left on a table", "discarded corn husks heap close up"], "chalas rotas amontonadas"],
    ["corn_h1_roadside_stand", ["roadside farm stand selling fresh corn", "wooden produce stand with corn cobs"], "un puesto al costado del camino"],
    ["corn_h1_market_corn_crates", ["crates of sweet corn at a farmers market", "fresh corn stacked in wooden crates"], "cajones de choclo en el mercado"],
    ["corn_h1_hands_feel_ear", ["hands feeling an ear of corn through the husk", "fingers running along a corn cob"], "manos palpando el choclo"],
    ["corn_h1_silk_golden_macro", ["golden corn silk close up macro", "corn tassel silk at the tip of a cob"], "la seda dorada del choclo"],
    ["corn_h1_kernels_rows_macro", ["rows of plump yellow corn kernels macro", "close up of a corn cob kernels"], "los granos en hileras"],
    ["corn_h1_boiling_pot", ["sweet corn cobs boiling in a pot of water", "corn cobs in boiling water close up"], "choclos hirviendo en la olla"],
    ["corn_h1_butter_corn", ["butter melting on a hot corn cob", "spreading butter over corn on the cob"], "manteca derritiéndose sobre el choclo"],
    ["corn_h1_eating_corn", ["person biting into corn on the cob", "eating buttered corn on the cob"], "alguien comiendo choclo"],
    ["corn_h1_field_dawn", ["sweet corn field at sunrise golden light", "rows of corn stalks at dawn"], "el maizal al amanecer"],
    ["corn_h1_pull_ear_stalk", ["hand snapping an ear of corn off the stalk", "picking corn from the stalk in a field"], "arrancando un choclo de la planta"],
    ["corn_h1_husk_green_tight", ["bright green corn husk wrapped tight close up", "fresh green husk on a corn cob"], "chala verde brillante y apretada"],
    ["corn_h1_husk_pale_dry", ["dried pale yellow corn husk close up", "papery old corn husk close up"], "chala pálida y reseca"],
    ["corn_h1_basket_corn_field", ["wicker basket full of freshly picked corn", "basket of corn cobs in a field"], "una canasta de choclo recién cortado"],
    ["corn_h1_weigh_two_ears", ["holding two ears of corn one in each hand", "weighing corn cobs in both hands"], "sopesando dos choclos"],
    ["corn_h1_stem_cut_macro", ["cut stem end of a corn cob close up", "base of a corn cob where it was snapped"], "el corte del tallo del choclo"],
    ["corn_h1_amish_farmer_field", ["Amish farmer walking through a corn field", "man in straw hat in a corn field"], "un granjero entre el maíz"],
    ["corn_h1_grandfather_hands", ["weathered old hands holding an ear of corn", "elderly farmer hands with corn cob"], "manos viejas y curtidas con un choclo"],
    ["corn_h1_husk_peel_reveal", ["peeling a corn husk to reveal yellow kernels", "opening corn husk showing the cob"], "abriendo la chala y mostrando los granos"],
    ["corn_h1_corn_on_table", ["several ears of sweet corn on a rustic table", "fresh corn cobs on wooden table"], "choclos sobre la mesa de madera"],
    ["corn_h1_market_shopper", ["shopper choosing produce at a market stall", "person selecting vegetables at a market"], "alguien eligiendo en el mercado"],
    ["corn_h1_corn_husk_wind", ["corn stalks swaying in the wind close up", "green corn leaves moving in the breeze"], "el maíz meciéndose con el viento"],
    ["corn_h1_dew_corn_leaf", ["dew drops on a green corn leaf macro", "morning dew on corn plant close up"], "rocío sobre la hoja de maíz"],
    ["corn_h1_hands_husk_open", ["hands opening a corn husk gently", "carefully unwrapping a corn cob"], "manos abriendo la chala con cuidado"],
    ["corn_h1_kernels_tip_gap", ["corn cob with missing kernels at the tip", "bald patch at the tip of a corn cob"], "choclo con granos faltantes en la punta"],
    ["corn_h1_grill_corn", ["corn on the cob roasting on a grill", "charred corn cobs on a barbecue"], "choclo asándose en la parrilla"],
    ["corn_h1_corn_truck_load", ["truck loaded with crates of corn", "produce truck hauling sweet corn"], "un camión cargado de choclo"],
    ["corn_h1_thumb_kernel", ["thumbnail pressing into a corn kernel", "pressing a corn kernel showing milky juice"], "el pulgar apretando un grano"],
    ["corn_h1_corn_pyramid_market", ["pyramid of corn cobs stacked at a market", "neatly stacked sweet corn at a stand"], "una pila de choclos en el puesto"],
    ["corn_h1_hand_point_corn", ["finger pointing at an ear of corn", "hand indicating a corn cob close up"], "un dedo señalando un choclo"],
    ["corn_h1_corn_close_spin", ["single ear of sweet corn rotating close up", "corn cob turning slowly on display"], "un choclo girando en primer plano"],
    ["corn_h1_husk_papery_edge", ["yellowing dry edges on a corn husk close up", "brown edge of an old corn husk"], "bordes amarillos y secos de la chala"],
    ["corn_h1_basket_market_corn", ["fresh corn for sale at an outdoor market", "corn cobs piled at a green grocer"], "choclo a la venta al aire libre"],
  ],
  // ░░ HOOK2 (52-109s) — dolor (chewy/cardboard) + abuelo elige sin pelar — medio ~2s ░░
  hook2: [
    ["corn_h2_peel_check_store", ["customer peeling back husk to inspect corn", "shopper opening corn husks at a store"], "un cliente pelando para revisar"],
    ["corn_h2_mess_husks_counter", ["torn husks left messy on a store counter", "pile of stripped husks at a produce stand"], "el lío de chalas en el mostrador"],
    ["corn_h2_chewy_corn_plate", ["overcooked corn on the cob on a plate", "plain boiled corn looking dull on a plate"], "choclo soso en el plato"],
    ["corn_h2_butter_disappoint", ["butter on a bland ear of corn close up", "buttered corn on the cob on a table"], "manteca sobre un choclo sin gracia"],
    ["corn_h2_grandfather_walk_stand", ["old farmer walking along a corn stand", "elderly man inspecting corn at a market"], "el abuelo recorriendo el puesto"],
    ["corn_h2_hand_glide_ears", ["hand gliding over a row of corn cobs", "fingers brushing across ears of corn"], "la mano deslizándose sobre los choclos"],
    ["corn_h2_grandfather_choose", ["old hands selecting the best ear of corn", "farmer picking a corn cob confidently"], "el abuelo eligiendo el mejor"],
    ["corn_h2_amish_stand_lane", ["Amish produce stand at the end of a lane", "rustic farm stand with vegetables"], "un puesto amish al final del camino"],
    ["corn_h2_six_ears_lineup", ["six ears of corn lined up on a table", "row of corn cobs arranged on wood"], "seis choclos alineados"],
    ["corn_h2_hands_two_ears", ["comparing two ears of corn side by side", "holding two corn cobs to compare"], "comparando dos choclos"],
    ["corn_h2_grandfather_portrait", ["portrait of an old Amish farmer in a straw hat", "weathered farmer face in the field"], "el rostro del abuelo amish"],
    ["corn_h2_field_rows_walk", ["walking between tall rows of corn stalks", "person strolling through a corn field"], "caminando entre las hileras de maíz"],
    ["corn_h2_kitchen_corn_pot", ["pot of water coming to a boil on a stove", "steam rising from a pot on the stove"], "la olla a punto de hervir"],
    ["corn_h2_corn_basket_porch", ["basket of corn on a farmhouse porch", "fresh corn cobs by a rustic doorway"], "una canasta de choclo en el porche"],
  ],
  // ░░ LEVI (109-130s) — intro personal: Lancaster, el puesto, vender a vecinos (AV_FULL, poco broll) ░░
  levi: [
    ["corn_lv_lancaster_farm", ["aerial of an Amish farm in Lancaster County", "rolling Amish farmland with barn"], "una granja en Lancaster County"],
    ["corn_lv_stand_lane_end", ["small produce stand at the end of a farm lane", "roadside Amish vegetable stand"], "el puesto al final del camino"],
    ["corn_lv_neighbors_buy", ["customer buying corn from a farm stand", "handing corn cobs to a buyer"], "vendiéndole choclo a un vecino"],
    ["corn_lv_amish_buggy_road", ["Amish horse and buggy on a country road", "horse-drawn buggy passing farmland"], "un carruaje amish en el camino"],
    ["corn_lv_corn_cash_box", ["money box at a roadside honor stand", "cash and coins at a farm stand"], "la caja del puesto"],
    ["corn_lv_church_sunday", ["plain country church on a Sunday morning", "Amish meeting house in the countryside"], "la iglesia un domingo"],
  ],
  // ░░ VILLANO 1 (143-218s) — el azúcar se vuelve almidón + cadena (camión/depósito/góndola) ░░
  villain: [
    ["corn_vl_sugar_starch_macro", ["extreme macro of a corn kernel cross section", "inside of a corn kernel close up"], "el grano por dentro"],
    ["corn_vl_pick_stalk_snap", ["snapping a fresh ear off a corn stalk", "harvesting corn by hand in a field"], "arrancando el choclo de la planta"],
    ["corn_vl_clock_ticking", ["old clock ticking close up", "vintage clock hands moving"], "un reloj corriendo"],
    ["corn_vl_field_to_kitchen", ["carrying a basket of corn from field to house", "farmer walking corn back to the farmhouse"], "del campo a la cocina"],
    ["corn_vl_pot_boiling_ready", ["large pot of water boiling on a wood stove", "rolling boil in a kitchen pot"], "la olla hirviendo lista"],
    ["corn_vl_corn_on_truck", ["corn crates loaded onto a delivery truck", "truck hauling produce on a highway"], "choclo cargado en el camión"],
    ["corn_vl_warehouse_pallets", ["produce stacked on pallets in a warehouse", "boxes of vegetables in a cold warehouse"], "el depósito lleno de cajas"],
    ["corn_vl_grocery_shelf_corn", ["corn cobs sitting on a grocery store shelf", "packaged corn on a supermarket shelf"], "el choclo en la góndola"],
    ["corn_vl_days_calendar", ["calendar pages turning days passing", "time passing calendar timelapse"], "los días pasando"],
    ["corn_vl_old_corn_dull", ["dull dried out ear of corn close up", "old corn cob with shriveled kernels"], "un choclo viejo y opaco"],
    ["corn_vl_fresh_vs_old", ["comparing a fresh corn cob to an old one", "two ears of corn fresh and stale"], "fresco contra viejo"],
    ["corn_vl_kernel_drop_juice", ["milky juice from a fresh corn kernel macro", "fresh corn kernel bursting with juice"], "el jugo lechoso del grano fresco"],
    ["corn_vl_supermarket_aisle", ["wide shot of a supermarket produce aisle", "grocery store vegetable section"], "el pasillo de verduras del súper"],
    ["corn_vl_corn_stalks_wide", ["wide field of green corn stalks in summer", "tall corn rows under a blue sky"], "un campo de maíz en verano"],
  ],
  // ░░ HEIRLOOM (218-297s) — criado para viajar no para sabor + Golden Bantam / guardar semilla ░░
  heirloom: [
    ["corn_hr_machine_harvest", ["large combine harvester cutting a corn field", "industrial corn harvester at work"], "una cosechadora arrasando el maizal"],
    ["corn_hr_uniform_corn_crates", ["identical corn cobs packed in crates", "uniform sweet corn stacked for shipping"], "choclos idénticos listos para enviar"],
    ["corn_hr_pretty_husk_shelf", ["neat green husked corn on a store display", "tidy corn cobs in a supermarket"], "choclo prolijo en la góndola"],
    ["corn_hr_golden_bantam", ["heirloom golden yellow corn cob close up", "old variety yellow sweet corn"], "el Golden Bantam amarillo"],
    ["corn_hr_white_corn", ["tall white sweet corn cob close up", "heirloom white corn on a table"], "el choclo blanco antiguo"],
    ["corn_hr_save_seed", ["hands saving dried corn seed kernels", "drying corn cobs for seed in a barn"], "guardando semilla de maíz"],
    ["corn_hr_dried_seed_corn", ["dried corn cobs hanging to cure", "seed corn drying in a rustic barn"], "choclos secándose para semilla"],
    ["corn_hr_grandfather_field", ["old farmer inspecting his corn in the field", "Amish man among corn stalks"], "el abuelo revisando su maíz"],
    ["corn_hr_perfect_ear", ["one perfect fresh ear of sweet corn close up", "ideal corn cob held up to the light"], "el choclo perfecto"],
    ["corn_hr_open_pollinated", ["corn tassels releasing pollen in the wind", "pollen drifting over a corn field"], "el maíz polinizando al viento"],
    ["corn_hr_heirloom_basket", ["basket of colorful heirloom corn varieties", "assorted heirloom corn cobs in a basket"], "una canasta de maíces antiguos"],
    ["corn_hr_hands_shell_corn", ["hands shelling dried corn kernels off a cob", "removing seed kernels from dried corn"], "desgranando maíz seco a mano"],
  ],
  // ░░ SEÑAL 1 — LA CHALA / HUSK (297-366s) ░░
  s1: [
    ["corn_s1_husk_bright_green", ["bright green corn husk wrapped tight macro", "vivid green husk on a fresh cob"], "chala verde brillante y apretada"],
    ["corn_s1_husk_hold_light", ["holding a green husked corn to the sunlight", "fresh corn cob backlit by sun"], "un choclo verde a contraluz"],
    ["corn_s1_husk_pale_paper", ["pale papery dried corn husk close up", "yellowed brittle husk on old corn"], "chala pálida como papel"],
    ["corn_s1_husk_brown_edge", ["brown dried edges of a corn husk macro", "wilted brown husk tips close up"], "bordes marrones de la chala"],
    ["corn_s1_squeeze_husk", ["hand gently squeezing a corn husk", "fingers pressing a fresh corn cob"], "apretando la chala con la mano"],
    ["corn_s1_husk_damp_fresh", ["dewy fresh green corn husk macro", "moist green husk glistening close up"], "chala fresca y húmeda"],
    ["corn_s1_dry_kernels", ["dried shriveled corn kernels close up", "starchy dry corn kernels macro"], "granos secos y arrugados"],
    ["corn_s1_corn_pile_store", ["pile of husked corn in a store bin", "sweet corn stacked at a grocery"], "la pila de choclo en la tienda"],
    ["corn_s1_hand_select_husk", ["choosing a green ear of corn from a pile", "hand picking the greenest corn cob"], "eligiendo el choclo más verde"],
    ["corn_s1_husk_layers_macro", ["layers of a corn husk peeled back macro", "tight wrapped husk leaves close up"], "las capas de la chala"],
    ["corn_s1_corn_field_green", ["lush green corn field in full summer", "healthy green corn stalks wide"], "el maizal verde en verano"],
    ["corn_s1_two_husks_compare", ["fresh green husk next to a dry pale husk", "comparing good and bad corn husks"], "chala buena vs chala mala"],
  ],
  // ░░ ANÉCDOTA 1 (366-424s) — el hombre apurado que agarra de arriba; el abuelo busca en la sombra ░░
  anec1: [
    ["corn_a1_hurried_man_stand", ["man in a hurry grabbing corn at a stand", "busy shopper quickly picking produce"], "un hombre apurado en el puesto"],
    ["corn_a1_top_pile_sun", ["corn on top of a pile in direct sunlight", "sun beating on stacked corn cobs"], "el choclo de arriba al sol"],
    ["corn_a1_pale_husk_top", ["pale sun-faded husks on top of a corn pile", "dried husks on exposed corn cobs"], "chalas pálidas arriba de la pila"],
    ["corn_a1_grandfather_watch", ["old farmer quietly watching a customer", "elderly man observing at a stand"], "el abuelo mirando en silencio"],
    ["corn_a1_reach_under_pile", ["hand reaching underneath a pile of corn", "pulling corn from the cool bottom of a stack"], "metiendo la mano debajo de la pila"],
    ["corn_a1_green_ears_handover", ["handing over fresh green ears of corn", "giving corn cobs to a customer"], "entregando choclos verdes"],
    ["corn_a1_shade_cool_corn", ["corn cobs resting in cool shade", "fresh corn in the shade of a stand"], "choclo fresco en la sombra"],
    ["corn_a1_amish_stand_morning", ["Amish farm stand in the early morning", "rustic produce stand at dawn"], "el puesto amish de mañana"],
    ["corn_a1_glowing_green_husk", ["vivid glowing green corn husks close up", "extra fresh green corn cobs"], "chalas verdes que brillan"],
    ["corn_a1_boy_helping_stand", ["a boy helping at a farm produce stand", "child at an Amish vegetable stand"], "un chico ayudando en el puesto"],
  ],
  // ░░ SEÑAL 2 — LA SEDA / SILK (424-495s) ░░
  s2: [
    ["corn_s2_silk_tip_macro", ["corn silk sticking out of the top of a cob", "bundle of silk threads on corn macro"], "la seda saliendo de la punta"],
    ["corn_s2_silk_golden", ["golden brown corn silk close up", "ripe golden silk on a corn cob"], "seda dorada"],
    ["corn_s2_silk_soft_sticky", ["fresh sticky corn silk macro", "moist corn silk threads close up"], "seda suave y pegajosa"],
    ["corn_s2_silk_black_slimy", ["dark slimy old corn silk close up", "blackened wet corn silk macro"], "seda negra y babosa"],
    ["corn_s2_silk_green_stiff", ["bright green stiff corn silk close up", "unripe green silk on a young cob"], "seda verde y tiesa"],
    ["corn_s2_roll_silk_fingers", ["rolling corn silk between two fingers", "feeling corn silk with fingertips"], "frotando la seda entre los dedos"],
    ["corn_s2_silk_breeze", ["corn silk fluttering in a light breeze", "tassel silk moving in the wind macro"], "la seda moviéndose con la brisa"],
    ["corn_s2_cob_top_silk", ["top of a corn cob with full silk tuft", "corn ear silk bunch in sunlight"], "el penacho de seda del choclo"],
    ["corn_s2_silk_drying_gold", ["corn silk turning from green to gold", "silk drying to golden brown macro"], "la seda secándose a dorado"],
    ["corn_s2_tassel_field", ["corn tassels swaying at the top of stalks", "golden corn tassels in a field"], "las espigas del maizal"],
    ["corn_s2_hand_inspect_silk", ["hand inspecting corn silk without peeling", "examining the silk on an ear of corn"], "revisando la seda sin pelar"],
  ],
  // ░░ SEÑAL 3 — SENTIR LOS GRANOS / FEEL (495-584s) — el método sin pelar; la punta ░░
  s3: [
    ["corn_s3_fingers_down_cob", ["running fingers down a corn cob over the husk", "feeling an ear of corn through the husk"], "los dedos recorriendo el choclo"],
    ["corn_s3_feel_plump_even", ["pressing a plump even corn cob gently", "checking a full firm ear of corn"], "palpando un choclo lleno y parejo"],
    ["corn_s3_tip_full_round", ["full rounded tip of a corn cob close up", "well filled corn cob tip macro"], "la punta llena y redondeada"],
    ["corn_s3_tip_thin_pinch", ["thin pinched tapering tip of a corn cob", "underfilled corn cob tip close up"], "la punta fina y pellizcada"],
    ["corn_s3_bald_patch_tip", ["bald patch with missing kernels at the tip", "gaps in corn kernels at the cob tip"], "el claro sin granos en la punta"],
    ["corn_s3_kernels_pearls", ["plump rows of corn kernels like pearls macro", "even tight rows of corn kernels"], "granos como perlas en hileras"],
    ["corn_s3_press_kernel_give", ["pressing a corn kernel that gives slightly", "fingertip on a firm corn kernel macro"], "apretando un grano que cede"],
    ["corn_s3_rock_hard_kernels", ["hard dried corn kernels macro", "rock hard old corn kernels close up"], "granos duros como piedra"],
    ["corn_s3_pollination_cob", ["corn cob with full pollinated kernels", "perfectly pollinated ear of corn"], "un choclo bien polinizado"],
    ["corn_s3_hand_feel_market", ["shopper feeling corn cobs at a market", "customer squeezing corn at a stand"], "palpando choclo en el mercado"],
    ["corn_s3_husk_unpeeled", ["whole unpeeled green corn cob in hand", "intact husked corn held in palm"], "el choclo entero sin pelar"],
    ["corn_s3_corn_rows_macro", ["macro pan across rows of corn kernels", "close up traveling along a corn cob"], "recorrido macro por los granos"],
  ],
  // ░░ ANÉCDOTA 2 (584-665s) — la prueba del pulgar / etapa de leche (milk stage) ░░
  anec2: [
    ["corn_a2_thumbnail_kernel", ["thumbnail pressing into a single corn kernel", "fingernail bursting a corn kernel"], "la uña apretando un grano"],
    ["corn_a2_milky_juice", ["milky white juice from a corn kernel macro", "creamy liquid from fresh corn kernel"], "el jugo lechoso del grano"],
    ["corn_a2_clear_watery", ["clear watery juice from an unripe kernel", "thin liquid from a young corn kernel"], "jugo aguado del grano verde"],
    ["corn_a2_doughy_kernel", ["thick pasty starchy corn kernel close up", "overripe doughy corn kernel macro"], "grano pastoso y pasado"],
    ["corn_a2_peel_corner_check", ["peeling back a small corner of corn husk", "checking corn by opening a corner"], "abriendo una esquinita para revisar"],
    ["corn_a2_field_ready_pick", ["farmer checking if corn is ready to pick", "inspecting corn ripeness in the field"], "viendo si el maíz está a punto"],
    ["corn_a2_grandfather_test", ["old farmer testing a corn kernel in the field", "Amish man checking corn in a field"], "el abuelo probando el grano"],
    ["corn_a2_kernel_macro_burst", ["extreme macro of a corn kernel bursting", "juicy corn kernel splitting close up"], "el grano reventando en macro"],
    ["corn_a2_corn_stalk_close", ["close up of an ear of corn on the stalk", "ripe corn cob hanging on the plant"], "un choclo en la planta"],
    ["corn_a2_fingertips_feel", ["fingertips feeling a corn cob carefully", "sensitive touch on an ear of corn"], "las yemas de los dedos sintiendo"],
  ],
  // ░░ SEÑAL 4 — EL PESO / WEIGHT (665-718s) ░░
  s4: [
    ["corn_s4_lift_ear_hand", ["lifting a single ear of corn in one hand", "weighing a corn cob in the palm"], "levantando un choclo en la mano"],
    ["corn_s4_heavy_ear", ["holding a heavy plump ear of sweet corn", "a dense heavy corn cob close up"], "un choclo pesado y lleno"],
    ["corn_s4_two_ears_balance", ["balancing two ears of corn one per hand", "comparing the weight of two corn cobs"], "balanceando dos choclos"],
    ["corn_s4_light_dry_ear", ["lightweight dried out ear of corn", "airy old corn cob in hand"], "un choclo liviano y seco"],
    ["corn_s4_bounce_ear", ["bouncing an ear of corn in the hand to feel weight", "tossing a corn cob lightly to gauge weight"], "haciendo saltar el choclo en la mano"],
    ["corn_s4_moisture_kernels", ["moist juicy corn kernels macro", "water rich fresh corn kernels"], "granos jugosos y húmedos"],
    ["corn_s4_pick_from_bin", ["choosing the heaviest corn from a bin", "selecting a dense ear of corn at a store"], "eligiendo el más pesado del cajón"],
    ["corn_s4_old_timer_pick", ["old farmer weighing corn in both hands", "experienced hands judging corn weight"], "un veterano sopesando el choclo"],
    ["corn_s4_corn_set_back", ["setting a light ear of corn back on the pile", "returning a corn cob to the stand"], "devolviendo el choclo liviano"],
  ],
  // ░░ SEÑAL 5 — EL TALLO / STEM END (718-788s) ░░
  s5: [
    ["corn_s5_stem_end_macro", ["cut stem end of a corn cob extreme close up", "base of a corn cob macro"], "el corte del tallo en macro"],
    ["corn_s5_stem_pale_moist", ["pale moist creamy cut end of fresh corn", "fresh light colored corn stem base"], "el corte pálido y húmedo"],
    ["corn_s5_stem_brown_dry", ["brown dried shriveled corn stem end", "dark twiggy old corn cob base"], "el corte marrón y reseco"],
    ["corn_s5_flip_corn_over", ["flipping a corn cob over to check the base", "turning an ear of corn to see the stem"], "dando vuelta el choclo para ver la base"],
    ["corn_s5_snap_off_stalk", ["snapping a fresh ear off the corn stalk", "breaking corn from the plant close up"], "quebrando el choclo de la planta"],
    ["corn_s5_inspect_base_store", ["checking the cut end of corn at a store", "examining a corn cob base at a market"], "revisando la base en la tienda"],
    ["corn_s5_tree_rings", ["close up of tree rings on a cut log", "growth rings on cut wood macro"], "los anillos de un tronco cortado"],
    ["corn_s5_corn_basket_base", ["ears of corn showing their cut bases in a basket", "stem ends of corn cobs in a crate"], "las bases de los choclos en la canasta"],
    ["corn_s5_old_twig_compare", ["dried twig next to an old corn stem", "shriveled dry plant stem close up"], "una rama seca de comparación"],
  ],
  // ░░ ANÉCDOTA 3 (788-863s) — cosechar al amanecer; preguntar cuándo se cortó ░░
  anec3: [
    ["corn_a3_dawn_field", ["corn field at first light with mist", "sunrise over rows of corn stalks"], "el maizal a primera luz"],
    ["corn_a3_dew_everywhere", ["heavy dew on corn leaves at dawn macro", "morning dew dripping off corn plant"], "el rocío sobre todo el maíz"],
    ["corn_a3_harvest_morning", ["farmer harvesting corn early in the morning", "picking corn at dawn with a basket"], "cosechando temprano a la mañana"],
    ["corn_a3_sun_rising_corn", ["sun rising over a corn field golden light", "early sunrays through corn stalks"], "el sol saliendo sobre el maíz"],
    ["corn_a3_basket_dawn", ["basket filling with fresh corn at dawn", "morning harvest basket of corn"], "la canasta llenándose al alba"],
    ["corn_a3_hot_sun_field", ["hot midday sun over a corn field", "harsh sunlight on corn stalks"], "el sol fuerte del mediodía"],
    ["corn_a3_ask_grower_stand", ["customer talking to a farmer at a stand", "buyer asking a grower about produce"], "preguntándole al productor"],
    ["corn_a3_fresh_picked_morning", ["this morning's freshly picked corn on a stand", "just harvested corn cobs at a market"], "choclo recién cortado esta mañana"],
    ["corn_a3_stove_water_ready", ["pot of water already on the stove", "kitchen stove with a pot ready"], "la olla ya en la cocina"],
    ["corn_a3_farmers_market_wide", ["busy farmers market on a summer morning", "outdoor market stalls with produce"], "el mercado de productores de mañana"],
  ],
  // ░░ SEÑAL 6 — NO PELAR / NEVER PEEL (863-942s) — el revés que sorprende ░░
  s6: [
    ["corn_s6_hands_off_husk", ["intact green corn cob held without peeling", "whole sealed ear of corn in hands"], "el choclo entero, sin pelar"],
    ["corn_s6_pull_husk_back", ["pulling a corn husk back at a store", "opening corn husk to inspect"], "tirando de la chala hacia atrás"],
    ["corn_s6_moisture_escaping", ["dry corn cob losing moisture close up", "exposed corn kernels drying out"], "la humedad escapándose"],
    ["corn_s6_husk_packaging", ["tightly wrapped green husk like packaging", "natural husk sealing a corn cob"], "la chala como envoltorio natural"],
    ["corn_s6_clock_fast", ["clock hands spinning fast close up", "time speeding up clock macro"], "el reloj acelerándose"],
    ["corn_s6_man_tearing_corn", ["man tearing open multiple corn husks", "shopper ripping husks at a stand"], "el hombre rompiendo chalas"],
    ["corn_s6_corn_sealed_home", ["carrying unpeeled corn home in a bag", "bag of husked corn on a counter"], "llevando el choclo cerrado a casa"],
    ["corn_s6_peel_at_pot", ["peeling corn husk right before boiling", "shucking corn next to a boiling pot"], "pelando justo antes de hervir"],
    ["corn_s6_hot_water_drop", ["dropping corn into a pot of boiling water", "corn cobs going into boiling water"], "tirando el choclo al agua hirviendo"],
    ["corn_s6_six_signs_montage", ["close up montage of inspecting corn outside", "examining a sealed corn cob in hand"], "leyendo el choclo por fuera"],
    ["corn_s6_husk_tight_wrap", ["fresh corn husk wrapped tight macro", "sealed green husk on a corn cob"], "la chala bien cerrada"],
  ],
  // ░░ ROAST (942-965s) — asar en la chala ░░
  roast: [
    ["corn_rt_grill_husk", ["corn roasting in the husk on a grill", "whole husked corn on a barbecue"], "choclo asándose en la chala"],
    ["corn_rt_oven_corn", ["corn in husk roasting in an oven", "husked corn on a baking tray"], "choclo en el horno con chala"],
    ["corn_rt_steam_husk", ["steam rising off a hot husked corn cob", "peeling back a roasted corn husk"], "el vapor saliendo de la chala"],
    ["corn_rt_family_table", ["family gathering with corn on the table", "rustic outdoor meal with corn"], "una mesa familiar con choclo"],
    ["corn_rt_juicy_corn", ["juicy roasted corn on the cob close up", "perfectly cooked sweet corn"], "choclo jugoso y bien cocido"],
  ],
  // ░░ RECAP (965-1027s) — las 6 señales en 10 segundos ░░
  recap: [
    ["corn_rc_husk_green_recap", ["bright green tight corn husk close up", "fresh green husk macro"], "chala verde y apretada"],
    ["corn_rc_silk_recap", ["golden soft corn silk close up", "ripe silk on a corn cob"], "seda dorada"],
    ["corn_rc_feel_tip_recap", ["feeling a corn cob to the tip through husk", "fingers checking the tip of an ear"], "palpando hasta la punta"],
    ["corn_rc_weight_recap", ["lifting a heavy ear of corn in hand", "weighing a corn cob"], "sopesando el choclo"],
    ["corn_rc_stem_recap", ["flipping corn to check the pale stem end", "inspecting the base of a corn cob"], "revisando la base"],
    ["corn_rc_no_peel_recap", ["intact unpeeled corn cob held up", "sealed green corn cob in hand"], "el choclo sin pelar"],
    ["corn_rc_corn_bin_choose", ["choosing the best ear from a corn bin", "confident hand picking sweet corn"], "eligiendo el mejor del cajón"],
    ["corn_rc_sweet_corn_pile", ["pile of perfect fresh sweet corn", "stack of green husked corn cobs"], "una pila de choclo perfecto"],
  ],
  // ░░ EMOCIONAL (1027-1080s) — filosofía amish: no desperdiciar, no dejarse engañar ░░
  emotional: [
    ["corn_em_amish_table", ["simple Amish family dinner table", "plain wholesome meal on a wooden table"], "la mesa sencilla amish"],
    ["corn_em_grandfather_teach", ["old farmer teaching a child about corn", "elder showing a kid an ear of corn"], "el abuelo enseñando a un nieto"],
    ["corn_em_hands_corn_warm", ["weathered hands cradling an ear of corn", "old hands holding corn warmly"], "manos curtidas sosteniendo el choclo"],
    ["corn_em_amish_farm_evening", ["Amish farm at golden hour", "peaceful farmland in evening light"], "la granja amish al atardecer"],
    ["corn_em_full_table_food", ["a humble table full of good simple food", "abundant farm meal on rustic wood"], "una mesa humilde llena de comida"],
    ["corn_em_corn_field_sunset", ["corn field silhouetted at sunset", "golden corn stalks at dusk"], "el maizal contra el atardecer"],
    ["corn_em_passing_down", ["grandfather and grandchild walking a farm", "elder and child in a garden"], "transmitiéndolo de generación"],
  ],
  // ░░ CTA (1080-1125s) — probalo esta semana + teaser tomate (AV_FULL cierre) ░░
  cta: [
    ["corn_ct_pick_corn_market", ["shopper happily picking corn at a market", "person choosing sweet corn confidently"], "eligiendo choclo en el mercado"],
    ["corn_ct_taste_corn", ["person tasting fresh corn on the cob smiling", "enjoying a bite of sweet corn"], "probando el choclo, feliz"],
    ["corn_ct_tomato_store", ["ripe red tomatoes at a grocery store", "fresh tomatoes on a market shelf"], "tomates en la tienda (teaser)"],
    ["corn_ct_tomato_slice", ["slicing a ripe juicy tomato close up", "cutting into a red tomato macro"], "cortando un tomate jugoso"],
    ["corn_ct_corn_basket_close", ["basket of fresh sweet corn close up", "wicker basket of corn cobs"], "una canasta de choclo fresco"],
    ["corn_ct_farm_goodbye", ["Amish farmer waving in a field at dusk", "friendly farmer in a corn field evening"], "el granjero despidiéndose"],
  ],
};
