// shots_abono.mjs — Levi Lapp Jardín (ES) · "7 Basuras de Cocina Que Son Abono GRATIS (Deja de Tirarlas)"
// Shotlist DENSO CLIPS-FIRST (estilo corn/replantar/barcos): queries LIMPIAS, visuales, con MOVIMIENTO
// (manos sobre la tierra, restos de cocina cayendo, lombrices, brotes, compost, té de cáscaras, huerta),
// NO la palabra literal del narrador, NO tutoriales con texto quemado. Lo consume build_abono.mjs.
// ~270 conceptos. Secciones ancladas a los timestamps reales del avatar (1745s, captions_abono_aligned.json).
export const SHOTS = {
  // ░░ HOOK (0-95s) — promesa value-first + open loops (#4 y el secreto del abuelo) — ráfaga ~1-1.5s ░░
  hook: [
    ["abono_hk_kitchen_scraps_bowl", ["bowl of kitchen vegetable scraps on a counter", "food scraps collected in a kitchen bowl"], "restos de cocina en un bol"],
    ["abono_hk_scraps_into_soil", ["hand dropping kitchen scraps onto dark soil", "tossing vegetable peels onto garden bed"], "echando restos a la tierra"],
    ["abono_hk_trash_bin_food", ["food waste being thrown into a trash bin", "scraping leftovers into a garbage can"], "tirando comida a la basura"],
    ["abono_hk_rich_black_soil", ["hands lifting rich black crumbly soil", "dark compost soil running through fingers"], "tierra negra entre los dedos"],
    ["abono_hk_tomato_plant_thrive", ["healthy tomato plant heavy with fruit", "ripe tomatoes on a thriving vine"], "tomatera cargada y sana"],
    ["abono_hk_eggshells_crushed", ["crushing eggshells over soil close up", "broken eggshells sprinkled on dirt"], "cáscaras de huevo trituradas"],
    ["abono_hk_coffee_grounds_pour", ["used coffee grounds poured onto soil", "spent coffee grounds in a hand over plants"], "borra de café sobre la tierra"],
    ["abono_hk_banana_peel_soil", ["chopped banana peel buried in garden soil", "banana peel pieces on dark earth"], "cáscara de banana en la tierra"],
    ["abono_hk_worms_compost", ["earthworms wriggling in dark compost", "worms moving through rich soil close up"], "lombrices en el compost"],
    ["abono_hk_watering_can_garden", ["watering a vegetable garden with a can", "pouring water over leafy garden plants"], "regando la huerta"],
    ["abono_hk_garden_store_bag", ["bags of fertilizer stacked at a garden store", "commercial soil bags on a shelf"], "bolsas de abono en el vivero"],
    ["abono_hk_money_wallet", ["taking cash out of a wallet to pay", "counting money at a store checkout"], "sacando plata para pagar"],
    ["abono_hk_compost_pile_turn", ["turning a steaming compost pile with a fork", "garden fork lifting compost"], "removiendo la pila de compost"],
    ["abono_hk_hands_dirt_work", ["weathered hands working dark garden soil", "old hands digging into the earth"], "manos curtidas en la tierra"],
    ["abono_hk_veg_garden_wide", ["lush backyard vegetable garden in summer", "rows of healthy vegetables growing"], "una huerta frondosa"],
    ["abono_hk_seedling_sprout", ["tiny green seedling sprouting from soil", "young plant pushing up through dirt"], "un brote saliendo de la tierra"],
    ["abono_hk_potato_peels_falling", ["potato peelings falling onto a cutting board", "vegetable peels dropping in slow motion"], "cáscaras de papa cayendo"],
    ["abono_hk_onion_skins_hand", ["dry onion skins held in a hand", "papery onion peels close up"], "cáscaras secas de cebolla"],
    ["abono_hk_pour_veg_water", ["pouring cloudy vegetable cooking water", "draining pot water from boiled vegetables"], "volcando agua de cocción"],
    ["abono_hk_tea_bag_used", ["used tea bag held over a cup", "wet tea leaves spilling from a tea bag"], "una bolsita de té usada"],
    ["abono_hk_amish_garden_morning", ["Amish vegetable garden in morning light", "plain rustic homestead garden at dawn"], "una huerta amish al amanecer"],
    ["abono_hk_grandfather_garden", ["old farmer kneeling in a vegetable garden", "elder tending plants with bare hands"], "el abuelo en la huerta"],
    ["abono_hk_trench_dig_garden", ["digging a narrow trench in a garden bed", "spade opening a furrow in dark soil"], "cavando una zanja en la huerta"],
    ["abono_hk_bury_scraps_trench", ["burying food scraps in a garden trench", "covering kitchen waste with soil by hand"], "enterrando restos en la zanja"],
    ["abono_hk_basket_harvest", ["basket overflowing with fresh garden vegetables", "harvest basket full of tomatoes and greens"], "una canasta de cosecha"],
    ["abono_hk_hand_drop_eggshell", ["dropping a cracked eggshell into a jar", "saving eggshells in a kitchen jar"], "guardando cáscaras en un tarro"],
  ],
  // ░░ INTRO (95-200s) — por qué la basura vale: vivero caro vs calcio/potasio/nitrógeno gratis + abuelo ░░
  intro: [
    ["abono_in_fertilizer_shelf", ["rows of fertilizer products on a store shelf", "garden center shelves full of plant food"], "estantería de abonos del vivero"],
    ["abono_in_price_tag_bag", ["price tag on a bag of garden fertilizer", "scanning a fertilizer bag at checkout"], "el precio de la bolsa de abono"],
    ["abono_in_pour_fertilizer_granules", ["pouring fertilizer granules from a bag", "synthetic plant food pellets in a hand"], "gránulos de abono cayendo"],
    ["abono_in_lab_bag_label", ["close up of a fertilizer bag nutrient label", "NPK numbers on a plant food package"], "la etiqueta de nutrientes"],
    ["abono_in_rotting_matter_soil", ["organic matter decomposing in soil", "decaying leaves breaking down on the ground"], "materia pudriéndose en la tierra"],
    ["abono_in_full_trash_bin", ["overflowing kitchen trash bin with food", "garbage bag full of food waste"], "el cubo de basura lleno"],
    ["abono_in_scraps_pile_counter", ["pile of vegetable scraps on a kitchen counter", "peels and cores heaped on a board"], "montón de restos en la mesada"],
    ["abono_in_eggshell_macro", ["macro of a cracked white eggshell", "eggshell texture extreme close up"], "cáscara de huevo en macro"],
    ["abono_in_banana_potassium", ["yellow banana peel curling close up", "banana skin texture macro"], "cáscara de banana en primer plano"],
    ["abono_in_coffee_nitrogen", ["dark wet coffee grounds in a filter", "spent espresso puck close up"], "borra de café húmeda"],
    ["abono_in_grandfather_hands_soil", ["old farmer's hands cupping dark soil", "elder holding a handful of rich earth"], "el abuelo sosteniendo tierra"],
    ["abono_in_old_homestead_garden", ["old fashioned homestead vegetable plot", "traditional kitchen garden with no machines"], "huerta de antaño"],
    ["abono_in_horse_barn_manure", ["wheelbarrow of manure by a barn", "shoveling compost near a stable"], "carretilla junto al granero"],
    ["abono_in_feeding_soil_handful", ["sprinkling organic matter over a garden bed", "feeding the soil by hand with scraps"], "alimentando la tierra a mano"],
    ["abono_in_tomato_fist_size", ["very large ripe tomato held in a hand", "huge heirloom tomato on the vine"], "un tomate enorme en la mano"],
    ["abono_in_cucumber_abundance", ["pile of fresh cucumbers from a garden", "basket of homegrown cucumbers"], "pepinos en abundancia"],
    ["abono_in_empty_wallet_store", ["empty wallet at a store counter", "hand hesitating over an expensive product"], "billetera vacía en la tienda"],
    ["abono_in_soil_crumble_closeup", ["dark crumbly compost falling slowly", "rich soil breaking apart in slow motion"], "tierra desmenuzándose"],
    ["abono_in_amish_farmer_portrait", ["portrait of an old Amish farmer outdoors", "weathered plain-dressed farmer face"], "el rostro del abuelo amish"],
    ["abono_in_garden_gate_morning", ["wooden garden gate in morning light", "entering a fenced vegetable garden"], "el portón de la huerta"],
  ],
  // ░░ EGG (200-300s) — #1 cáscara de huevo: calcio, podredumbre apical, triturar, anti-babosas ░░
  egg: [
    ["abono_eg_collect_jar", ["collecting eggshells in a jar by the sink", "saving eggshells in a kitchen container"], "juntando cáscaras en un tarro"],
    ["abono_eg_crack_egg", ["cracking an egg into a bowl close up", "breaking an eggshell in the kitchen"], "rompiendo un huevo"],
    ["abono_eg_dry_shells_sun", ["eggshells drying on a windowsill", "shells laid out to dry in the sun"], "cáscaras secándose al sol"],
    ["abono_eg_crush_mortar", ["crushing eggshells with a mortar and pestle", "grinding shells into powder by hand"], "moliendo cáscaras en mortero"],
    ["abono_eg_powder_close", ["fine eggshell powder in a palm", "ground white shell dust close up"], "polvo fino de cáscara"],
    ["abono_eg_sprinkle_plant", ["sprinkling eggshell powder around a plant base", "dusting soil with crushed shells"], "espolvoreando alrededor de la planta"],
    ["abono_eg_hole_planting", ["adding amendment into a planting hole", "preparing a hole for a tomato seedling"], "el hoyo antes de plantar"],
    ["abono_eg_tomato_blossom_rot", ["tomato with dark rot spot on the bottom", "blossom end rot on a ripening tomato"], "tomate con la punta podrida"],
    ["abono_eg_healthy_tomato_bottom", ["smooth healthy bottom of a ripe tomato", "perfect underside of a garden tomato"], "tomate sano por debajo"],
    ["abono_eg_pepper_plant", ["green bell pepper growing on a plant", "young pepper fruit on the stem"], "un pimiento en la planta"],
    ["abono_eg_boot_crush_furrow", ["boot stepping on eggshells in a garden row", "pressing shells into soil with a shoe"], "la bota pisando cáscaras"],
    ["abono_eg_slug_leaf", ["slug crawling on a garden leaf at night", "garden snail on a lettuce leaf"], "una babosa sobre la hoja"],
    ["abono_eg_lettuce_seedling", ["tender young lettuce seedlings in a bed", "small lettuce plants in dark soil"], "plantines de lechuga"],
    ["abono_eg_shell_ring_plant", ["ring of crushed shells around a seedling", "barrier of eggshell pieces on soil"], "anillo de cáscara alrededor"],
    ["abono_eg_bottle_smash", ["smashing eggshells inside a bag", "rolling a bottle over dried shells"], "machacando cáscaras con una botella"],
    ["abono_eg_water_in_shells", ["watering soil after adding shell powder", "watering can over a freshly amended bed"], "regando para que baje"],
    ["abono_eg_basket_eggs_farm", ["basket of fresh farm eggs", "collecting eggs from a coop"], "una canasta de huevos de granja"],
    ["abono_eg_hands_full_shells", ["a handful of broken eggshells", "cupped hands full of shell pieces"], "puñado de cáscaras rotas"],
    ["abono_eg_snail_close_macro", ["macro of a snail moving slowly", "garden snail antennae close up"], "un caracol en macro"],
  ],
  // ░░ COFFEE (300-430s) — #2 borra de café: nitrógeno, error de amontonar, lombrices, balde invierno ░░
  coffee: [
    ["abono_cf_filter_grounds", ["used coffee grounds in a paper filter", "wet spent grounds in a coffee maker"], "borra en el filtro"],
    ["abono_cf_tap_out_grounds", ["tapping coffee grounds out of a portafilter", "emptying a coffee filter into a bowl"], "vaciando la borra"],
    ["abono_cf_grounds_macro", ["macro of dark wet coffee grounds", "texture of spent coffee close up"], "borra de café en macro"],
    ["abono_cf_sprinkle_thin_soil", ["thinly sprinkling coffee grounds on soil", "dusting a garden bed with grounds"], "espolvoreando una capa fina"],
    ["abono_cf_rake_into_soil", ["raking grounds into the top of the soil", "mixing amendment into garden dirt by hand"], "rascando para mezclar"],
    ["abono_cf_clumped_mold", ["moldy clumped organic matter on soil", "wet caked material on a garden bed"], "borra apelmazada con moho"],
    ["abono_cf_leafy_greens_green", ["lush green spinach growing in a bed", "vibrant leafy greens in a garden"], "verdura de hoja bien verde"],
    ["abono_cf_pale_yellow_leaf", ["pale yellowing plant leaves", "nitrogen-deficient yellow foliage"], "hoja pálida y amarillenta"],
    ["abono_cf_worms_in_grounds", ["earthworms in coffee-rich dark soil", "worms feeding in compost close up"], "lombrices en la borra"],
    ["abono_cf_worm_tunnels", ["worm tunnels in a cross section of soil", "aerated soil with worm channels"], "túneles de lombriz en la tierra"],
    ["abono_cf_worm_castings", ["dark worm castings in a hand", "vermicompost granules close up"], "humus de lombriz"],
    ["abono_cf_bucket_lid_barn", ["a lidded bucket in a barn corner", "old pail with a lid in a shed"], "un balde con tapa en el granero"],
    ["abono_cf_winter_storage", ["frosty barn yard in winter", "snow on a homestead in winter light"], "el granero en invierno"],
    ["abono_cf_scatter_like_seed", ["scattering dark compost by hand across a bed", "broadcasting material over the garden"], "repartiendo como semilla"],
    ["abono_cf_coffee_cup_morning", ["pouring a morning cup of black coffee", "steam rising from a coffee cup"], "el café de la mañana"],
    ["abono_cf_spoon_grounds_plant", ["adding a scoop of grounds near a plant", "spooning coffee grounds at a stem base"], "una cucharada de borra"],
    ["abono_cf_compost_add_grounds", ["adding coffee grounds to a compost bin", "dumping grounds onto a compost heap"], "borra al montón de compost"],
    ["abono_cf_earthworm_macro", ["single earthworm macro on dark soil", "close up of a worm in the dirt"], "una lombriz en macro"],
    ["abono_cf_night_garden", ["quiet vegetable garden at night", "moonlit garden bed in the dark"], "la huerta de noche"],
  ],
  // ░░ BANANA (430-560s) — #3 cáscara de banana: potasio, flor y fruto, enterrar o té, nunca al aire ░░
  banana: [
    ["abono_bn_peel_banana", ["peeling a ripe banana close up", "hands opening a banana skin"], "pelando una banana"],
    ["abono_bn_peel_macro", ["yellow banana peel inner side macro", "ripe banana skin texture close up"], "la cáscara de banana en macro"],
    ["abono_bn_cut_peel_scissors", ["cutting banana peel into pieces with scissors", "snipping a banana skin into a bowl"], "cortando la cáscara con tijera"],
    ["abono_bn_bury_peel_soil", ["burying banana peel pieces next to a plant", "covering peel chunks with garden soil"], "enterrando la cáscara junto a la planta"],
    ["abono_bn_tomato_flower", ["yellow tomato flowers on the vine", "blossoms forming on a tomato plant"], "flores de tomate"],
    ["abono_bn_pepper_blossom", ["white pepper flower close up", "blossom on a chili plant"], "flor de pimiento"],
    ["abono_bn_cucumber_flower", ["yellow cucumber flower in the garden", "blossom on a cucumber vine"], "flor de pepino"],
    ["abono_bn_peels_jar_water", ["banana peels soaking in a jar of water", "peel tea steeping in a glass jar"], "cáscaras en remojo en un frasco"],
    ["abono_bn_dark_tea_water", ["dark steeped water poured from a jar", "straining a brown plant tea"], "el té oscuro colado"],
    ["abono_bn_water_plant_tea", ["watering a flowering plant with liquid feed", "pouring homemade plant tea at the base"], "regando con el té de banana"],
    ["abono_bn_flowers_to_fruit", ["tiny green tomato forming from a flower", "fruit setting on a tomato plant"], "la flor volviéndose fruto"],
    ["abono_bn_fruit_flies_warning", ["fruit flies around exposed food scraps", "flies over rotting peel on a surface"], "moscas sobre restos al aire"],
    ["abono_bn_peel_on_soil_bad", ["banana peel left exposed on top of soil", "uncovered peel drying on a garden bed"], "cáscara dejada al aire (mal)"],
    ["abono_bn_spade_dig_side", ["digging a small hole beside a plant with a trowel", "trowel opening soil next to a stem"], "haciendo un pozo al costado"],
    ["abono_bn_ripe_bananas_bunch", ["bunch of ripe bananas on a table", "yellow bananas in a fruit bowl"], "un racimo de bananas maduras"],
    ["abono_bn_potted_plant_balcony", ["potted flowering plant on a balcony", "container plant being watered"], "una planta en maceta"],
    ["abono_bn_jar_shade_lid", ["covered jar steeping in the shade", "lidded glass jar on a shaded shelf"], "el frasco tapado a la sombra"],
    ["abono_bn_green_tomatoes_vine", ["clusters of green tomatoes on a vine", "unripe tomatoes hanging in the garden"], "tomates verdes en la planta"],
    ["abono_bn_hand_mix_water", ["stirring liquid plant feed in a bucket", "mixing diluted plant tea with water"], "mezclando el té con agua"],
  ],
  // ░░ WATER (560-680s) — #4 agua de cocción: caldo invisible, enfriar, sin sal, macetas reverdecen ░░
  water: [
    ["abono_wt_boil_vegetables", ["vegetables boiling in a pot of water", "broccoli and carrots cooking in a pot"], "verduras hirviendo en la olla"],
    ["abono_wt_colored_water", ["cloudy colored water in a cooking pot", "tinted vegetable broth close up"], "el agua teñida de la cocción"],
    ["abono_wt_drain_colander", ["draining boiled potatoes in a colander", "pouring vegetables into a strainer"], "colando las papas"],
    ["abono_wt_pour_down_drain", ["pouring water down a kitchen sink drain", "wasting cooking water in the sink"], "tirando el agua por la pileta"],
    ["abono_wt_save_water_jug", ["pouring saved cooking water into a jug", "keeping vegetable water in a container"], "guardando el caldo en una jarra"],
    ["abono_wt_cool_water_counter", ["jug of water cooling on a counter", "water sitting to reach room temperature"], "el agua enfriándose"],
    ["abono_wt_water_potted_plant", ["watering a houseplant with a jug", "pouring water onto a potted plant"], "regando una maceta"],
    ["abono_wt_salt_shaker", ["salt being added from a shaker", "salting food on a plate close up"], "salando en el plato"],
    ["abono_wt_yellowing_houseplant", ["yellowing leaves on a potted plant", "pale struggling houseplant on a sill"], "maceta amarillenta"],
    ["abono_wt_green_houseplant", ["glossy deep green potted plant", "vibrant healthy houseplant by a window"], "maceta de verde lustroso"],
    ["abono_wt_broccoli_pot", ["broccoli florets boiling in water", "green vegetables in a steaming pot"], "brócoli en la olla"],
    ["abono_wt_carrot_pot", ["carrots simmering in a pot of water", "orange carrots boiling close up"], "zanahorias hirviendo"],
    ["abono_wt_steam_pot_stove", ["steam rising from a pot on a stove", "boiling water steaming on a burner"], "vapor saliendo de la olla"],
    ["abono_wt_windowsill_plants", ["potted plants lined up on a windowsill", "herbs growing in pots by a window"], "macetas en el alféizar"],
    ["abono_wt_pouring_clear_water", ["pouring clear water slowly over soil", "stream of water onto a plant base"], "el chorro de agua sobre la tierra"],
    ["abono_wt_thermometer_cool", ["touching water to check temperature", "hand testing cooled water in a jug"], "probando que esté fría"],
    ["abono_wt_potato_peeling_pot", ["potatoes being prepared for boiling", "peeled potatoes going into a pot"], "papas para hervir"],
    ["abono_wt_green_recovery_plant", ["wilted plant reviving with green leaves", "houseplant perking up after watering"], "la planta recuperándose"],
    ["abono_wt_kitchen_cooking_wide", ["cooking vegetables on a rustic stove", "home kitchen with pots on the stove"], "cocinando en la cocina"],
  ],
  // ░░ PAUSE (680-740s) — pattern interrupt "PARA, empezá por UNO" — ritmo lento, íntimo ░░
  pause: [
    ["abono_ps_one_eggshell_hand", ["a single eggshell held up in a hand", "one shell between fingers close up"], "una sola cáscara en la mano"],
    ["abono_ps_coffee_one_cup", ["one cup of coffee on a wooden table", "single mug of coffee in morning light"], "una taza de café"],
    ["abono_ps_one_seedling_care", ["carefully tending a single seedling", "hands cupping one small plant"], "cuidando un solo plantín"],
    ["abono_ps_calendar_routine", ["marking days on a wall calendar", "weekly routine notes by a window"], "la rutina semanal"],
    ["abono_ps_sweeping_barn", ["sweeping the floor of an old barn", "broom on weathered wooden boards"], "barriendo el granero"],
    ["abono_ps_grandfather_thoughtful", ["thoughtful old farmer resting in a garden", "elder pausing among the plants"], "el abuelo pensativo"],
    ["abono_ps_calm_garden_breeze", ["calm vegetable garden swaying gently", "peaceful garden in soft afternoon light"], "la huerta tranquila"],
    ["abono_ps_hands_rest_soil", ["hands resting on dark garden soil", "open palms over a garden bed"], "manos en reposo sobre la tierra"],
    ["abono_ps_single_step_path", ["a single footstep on a garden path", "boots walking slowly down a garden row"], "un paso por el sendero"],
    ["abono_ps_small_start_pot", ["planting one seed into a small pot", "starting one plant on a windowsill"], "empezar con una sola maceta"],
    ["abono_ps_quiet_kitchen_window", ["quiet kitchen window with soft light", "still life of a calm farmhouse kitchen"], "la cocina en calma"],
    ["abono_ps_returning_daily", ["farmer walking back to the garden each day", "returning to tend plants at sunrise"], "volviendo cada día"],
  ],
  // ░░ ONION (740-870s) — #5 cebolla y ajo: potasio+azufre, té dorado, repele pulgón, rociar al atardecer ░░
  onion: [
    ["abono_on_peel_onion", ["peeling dry papery skin off an onion", "removing onion skins in the kitchen"], "pelando la cebolla"],
    ["abono_on_garlic_skins", ["papery garlic skins on a cutting board", "peeling cloves of garlic close up"], "pelando ajo"],
    ["abono_on_skins_handful", ["a handful of onion and garlic skins", "dry vegetable peels gathered in hand"], "puñado de cáscaras"],
    ["abono_on_skins_jar_water", ["onion skins steeping in a jar of water", "garlic peels soaking in water"], "cáscaras en remojo"],
    ["abono_on_golden_tea", ["golden-brown steeped liquid in a jar", "amber plant tea poured out"], "el té dorado"],
    ["abono_on_strain_tea", ["straining liquid through a sieve into a bottle", "pouring tea through a strainer"], "colando el té"],
    ["abono_on_spray_bottle_fill", ["filling a garden spray bottle with liquid", "pouring solution into a sprayer"], "llenando el rociador"],
    ["abono_on_spray_leaves", ["spraying the undersides of plant leaves", "misting garden foliage with a sprayer"], "rociando las hojas por abajo"],
    ["abono_on_aphids_leaf", ["aphids clustered under a green leaf", "tiny green aphids on a plant stem"], "pulgones bajo la hoja"],
    ["abono_on_cabbage_clean", ["healthy cabbage head with no pests", "pristine green cabbage in a garden"], "un repollo sin bichos"],
    ["abono_on_kale_plant", ["curly kale growing in a garden bed", "leafy kale plant close up"], "una planta de col rizada"],
    ["abono_on_sunset_garden_spray", ["spraying plants in golden evening light", "misting a garden at dusk"], "rociando al atardecer"],
    ["abono_on_jar_under_eaves", ["a jar fermenting on a shaded shelf", "covered jar under a barn eave"], "el frasco bajo el alero"],
    ["abono_on_onion_skin_macro", ["macro of dry onion skin layers", "papery onion peel texture close up"], "capas de cebolla en macro"],
    ["abono_on_garlic_bulb_macro", ["close up of a garlic bulb and skins", "peeling a garlic clove macro"], "un diente de ajo en macro"],
    ["abono_on_rain_washing_leaves", ["rain washing over garden leaves", "water dripping off plant foliage"], "la lluvia lavando las hojas"],
    ["abono_on_chopping_onion", ["chopping an onion on a board", "slicing onion in the kitchen"], "picando cebolla"],
    ["abono_on_pest_fly_off", ["small insect flying off a plant leaf", "bug leaving a garden plant"], "el bicho yéndose de la planta"],
  ],
  // ░░ TEA (870-960s) — #6 bolsita de té: nitrógeno, trampa del plástico, solo las hojas, lo chico repetido ░░
  tea: [
    ["abono_te_used_teabag_plate", ["used tea bag resting on a small plate", "soaked tea bag after brewing"], "la bolsita usada en el plato"],
    ["abono_te_pour_tea_cup", ["pouring brewed tea into a cup", "steam over a fresh cup of tea"], "sirviendo el té"],
    ["abono_te_open_teabag", ["tearing open a tea bag over soil", "emptying loose tea leaves from a bag"], "abriendo la bolsita"],
    ["abono_te_wet_leaves_hand", ["wet tea leaves in the palm of a hand", "spent tea leaves close up"], "las hojas de té mojadas"],
    ["abono_te_plastic_teabag", ["pyramid mesh tea bag close up", "shiny synthetic tea bag held up"], "bolsita con plástico"],
    ["abono_te_paper_teabag", ["plain paper tea bag close up", "simple unbleached tea bag"], "bolsita de papel puro"],
    ["abono_te_leaves_on_soil", ["scattering tea leaves over garden soil", "spreading loose leaves on a bed"], "hojas de té sobre la tierra"],
    ["abono_te_cover_with_soil", ["covering amendment with a thin layer of soil", "raking soil over scattered leaves"], "tapando con tierra"],
    ["abono_te_leaves_compost", ["adding tea leaves to a compost bin", "tossing leaves onto a compost heap"], "hojas al compost"],
    ["abono_te_microplastic_warn", ["tiny plastic fragments in soil", "microplastic pieces close up on dirt"], "microplástico en la tierra"],
    ["abono_te_handful_leaves_month", ["a generous handful of dried tea leaves", "accumulated tea leaves in a jar"], "un puñado de hojas juntadas"],
    ["abono_te_morning_tea_ritual", ["pouring hot water over a tea bag", "preparing a morning cup of tea"], "el té de la mañana"],
    ["abono_te_loose_leaf_macro", ["macro of moist black tea leaves", "close up of steeped tea leaves"], "hojas de té en macro"],
    ["abono_te_jar_collecting", ["collecting tea leaves in a small jar", "saving spent leaves over time"], "juntando hojas en un tarro"],
    ["abono_te_small_things_soil", ["small amounts of organic matter on soil", "adding a little amendment to a bed"], "lo poco que se suma a la tierra"],
  ],
  // ░░ SCRAPS (960-1080s) — #7 recortes de verdura: base, tierra negra, pozo entre plantas (puerta al secreto) ░░
  scraps: [
    ["abono_sc_carrot_tops_board", ["carrot tops and peels on a cutting board", "trimming carrot ends in the kitchen"], "puntas de zanahoria en la tabla"],
    ["abono_sc_potato_peels", ["potato peelings piling up on a board", "peeling potatoes over a bowl"], "cáscaras de papa"],
    ["abono_sc_broccoli_stalk", ["chopping a thick broccoli stalk", "broccoli stem trimmings close up"], "el tronco del brócoli"],
    ["abono_sc_lettuce_outer_leaves", ["removing outer leaves from a lettuce", "discarded cabbage leaves on a board"], "hojas feas de la lechuga"],
    ["abono_sc_scraps_bowl_full", ["a bowl filling with mixed vegetable scraps", "kitchen scraps collected during cooking"], "el bol llenándose de recortes"],
    ["abono_sc_carry_bowl_garden", ["carrying a bowl of scraps out to the garden", "walking compost scraps to a garden bed"], "llevando el bol a la huerta"],
    ["abono_sc_dig_hole_between", ["digging a hole between two plants", "trowel opening soil in a garden row"], "haciendo un pozo entre plantas"],
    ["abono_sc_dump_scraps_hole", ["emptying vegetable scraps into a garden hole", "tipping a bowl of scraps into soil"], "echando los recortes al pozo"],
    ["abono_sc_cover_soil_hand", ["covering buried scraps with soil by hand", "patting earth over a filled hole"], "tapando con la misma tierra"],
    ["abono_sc_black_soil_result", ["dark spongy compost-rich soil close up", "fluffy black earth in a garden bed"], "tierra negra y esponjosa"],
    ["abono_sc_soil_smell_handful", ["smelling a handful of rich dark soil", "holding fragrant compost close up"], "oliendo la tierra rica"],
    ["abono_sc_no_bin_needed", ["simple garden composting with no equipment", "burying scraps directly in the ground"], "compost sin compostera"],
    ["abono_sc_empty_bed_resting", ["a bare garden bed resting between seasons", "empty soil plot ready for planting"], "un cantero descansando"],
    ["abono_sc_tomato_cores", ["tomato cores and trimmings on a board", "scraps from chopping tomatoes"], "cabos de tomate"],
    ["abono_sc_cucumber_ends", ["cucumber ends being trimmed off", "chopping cucumber tips in the kitchen"], "extremos de pepino"],
    ["abono_sc_mixed_peels_macro", ["macro of colorful mixed vegetable peels", "close up of assorted kitchen scraps"], "recortes mezclados en macro"],
    ["abono_sc_garden_fork_soil", ["loosening dark soil with a garden fork", "turning rich earth in a bed"], "aflojando la tierra negra"],
  ],
  // ░░ TRENCH (1080-1300s) — EL SECRETO: la zanja del abuelo, todo junto, invierno, tomates legendarios ░░
  trench: [
    ["abono_tr_dig_long_trench", ["digging a long narrow trench with a spade", "opening a furrow along a garden bed"], "cavando la zanja larga"],
    ["abono_tr_spade_deep_soil", ["spade turning deep dark soil", "shovel lifting earth from a trench"], "la pala en la tierra honda"],
    ["abono_tr_bucket_kitchen_door", ["a kitchen scrap bucket by the back door", "compost pail at the door of a house"], "el balde junto a la puerta"],
    ["abono_tr_dump_bucket_trench", ["emptying a bucket of scraps into a trench", "tipping kitchen waste into a furrow"], "volcando el balde en la zanja"],
    ["abono_tr_cover_shovel_soil", ["covering scraps with a shovel of soil", "burying waste in a trench with earth"], "tapando con una palada"],
    ["abono_tr_all_scraps_mixed", ["mixed eggshells coffee and peels together", "assorted kitchen waste in dark soil"], "todo junto sin separar"],
    ["abono_tr_winter_field_snow", ["snowy garden plot in winter", "frosted vegetable beds in cold light"], "la huerta nevada en invierno"],
    ["abono_tr_worms_underground", ["earthworms working in underground soil", "worms in a cross section of dark earth"], "lombrices trabajando abajo"],
    ["abono_tr_fungi_decompose", ["white fungal threads in decomposing matter", "mycelium breaking down organic waste"], "hongos descomponiendo"],
    ["abono_tr_richest_black_soil", ["the richest darkest soil in a garden", "deep black living compost soil"], "la tierra más negra de la huerta"],
    ["abono_tr_plant_tomato_spring", ["planting a tomato seedling in spring soil", "setting a young plant into rich earth"], "plantando tomate en primavera"],
    ["abono_tr_legendary_tomatoes", ["heavy clusters of huge ripe tomatoes", "an abundant tomato harvest in baskets"], "tomates legendarios"],
    ["abono_tr_neighbors_admire", ["neighbors admiring a thriving garden", "people looking at big garden vegetables"], "los vecinos admirando"],
    ["abono_tr_give_away_basket", ["giving away a basket of vegetables", "sharing garden produce with others"], "regalando una canasta"],
    ["abono_tr_spade_rest_ground", ["a spade stuck upright in garden soil", "shovel resting in a finished trench"], "la pala clavada en la tierra"],
    ["abono_tr_pail_lid_simple", ["a simple lidded pail of kitchen scraps", "covered compost bucket close up"], "un balde con tapa sencillo"],
    ["abono_tr_no_smell_buried", ["smooth covered garden soil with no waste visible", "tidy buried compost trench"], "sin olor, todo enterrado"],
    ["abono_tr_seasons_passing", ["a garden bed changing through the seasons", "soil transforming over time"], "el paso de las estaciones"],
    ["abono_tr_grandfather_smile_garden", ["old farmer smiling proudly in his garden", "content elder among healthy plants"], "el abuelo sonriendo orgulloso"],
    ["abono_tr_strip_planting_tomatoes", ["a row of tomato plants in a rich strip of soil", "tomatoes planted over a buried trench"], "la franja plantada con tomate"],
  ],
  // ░░ RECAP (1300-1500s) — repaso de los 7 + "empezá por uno" + lo que NUNCA enterrar ░░
  recap: [
    ["abono_rc_eggshell_recap", ["crushed eggshells on dark soil", "shell powder sprinkled on a bed"], "cáscara de huevo"],
    ["abono_rc_coffee_recap", ["coffee grounds spread thinly on soil", "dark grounds on a garden bed"], "borra de café"],
    ["abono_rc_banana_recap", ["banana peel buried beside a plant", "peel pieces in dark soil"], "cáscara de banana"],
    ["abono_rc_water_recap", ["pouring cooled vegetable water on a plant", "watering with saved cooking water"], "agua de cocción"],
    ["abono_rc_onion_recap", ["spraying onion-garlic tea on leaves", "misting plants with golden tea"], "té de cebolla y ajo"],
    ["abono_rc_tea_recap", ["tea leaves scattered on garden soil", "loose leaves on a bed close up"], "hojas de té"],
    ["abono_rc_scraps_recap", ["vegetable scraps buried in a garden hole", "covering scraps with soil"], "recortes de verdura"],
    ["abono_rc_trench_recap", ["a full kitchen-waste trench being covered", "the buried trench at a glance"], "la zanja del abuelo"],
    ["abono_rc_start_one_thing", ["starting with one simple garden habit", "one jar of scraps by the sink"], "empezar por una sola cosa"],
    ["abono_rc_no_meat_bones", ["raw meat and bones crossed out concept", "meat scraps set aside from compost"], "nunca carne ni huesos"],
    ["abono_rc_no_dairy_oil", ["dairy and cooking oil not for compost", "cheese and grease separated out"], "nada de lácteos ni aceite"],
    ["abono_rc_rats_warning", ["a rat near garbage as a warning", "pest by an open bin"], "el aviso de las ratas"],
    ["abono_rc_grew_from_earth", ["plant-based scraps returning to the soil", "vegetable peels going back to earth"], "lo que creció de la tierra vuelve"],
    ["abono_rc_seven_scraps_layout", ["seven kinds of kitchen scraps laid out", "assorted compost materials arranged"], "los siete restos juntos"],
  ],
  // ░░ CLOSING (1500-1745s) — cierre + teaser Video 3 (plagas sin veneno) — AV_FULL cierre ░░
  closing: [
    ["abono_cl_thriving_garden_wide", ["a full thriving vegetable garden in summer", "lush productive backyard garden"], "la huerta floreciente"],
    ["abono_cl_feeding_soil_done", ["satisfied gardener looking at rich soil", "hands patting a well-fed garden bed"], "la tierra ya alimentada"],
    ["abono_cl_pest_eating_leaf", ["a caterpillar eating a garden leaf", "insect damage on a vegetable plant"], "un bicho comiendo la hoja"],
    ["abono_cl_pantry_kitchen_items", ["common pantry items on a kitchen shelf", "household kitchen staples close up"], "cosas de la alacena"],
    ["abono_cl_spray_protect_plant", ["spraying a homemade solution on plants", "protecting garden plants naturally"], "protegiendo la planta"],
    ["abono_cl_no_poison_garden", ["natural pest-free vegetable garden", "chemical-free healthy garden plants"], "una huerta sin veneno"],
    ["abono_cl_strong_plants_row", ["a row of strong healthy garden plants", "vigorous vegetables growing in line"], "plantas fuertes en hilera"],
    ["abono_cl_harvest_reward", ["harvesting ripe vegetables into a basket", "picking a full garden harvest"], "la cosecha como recompensa"],
    ["abono_cl_grandfather_garden_dusk", ["old farmer in his garden at dusk", "elder among plants in evening light"], "el abuelo en la huerta al atardecer"],
    ["abono_cl_hands_soil_goodbye", ["weathered hands in dark soil at sunset", "farmer's hands resting on the earth"], "manos en la tierra al final"],
    ["abono_cl_next_video_pests", ["close up of garden pests on leaves", "aphids and beetles on a plant"], "plagas de la huerta (teaser)"],
    ["abono_cl_kitchen_to_garden", ["walking from kitchen door to garden", "carrying kitchen items to the plants"], "de la cocina a la huerta"],
    ["abono_cl_calm_garden_evening", ["peaceful vegetable garden in evening light", "still garden rows at golden hour"], "la huerta en calma al anochecer"],
    ["abono_cl_basket_full_goodbye", ["holding up a full basket of vegetables", "proud gardener with a harvest basket"], "mostrando la canasta llena"],
  ],
};

// ── SUPLEMENTO: más conceptos por sección (más variedad de footage real) ──
export const SHOTS_EXTRA = {
  hook: [
    ["abono_hk_compost_handful2", ["hands holding dark crumbly compost outdoors", "rich soil falling from hands close up"], "compost en las manos"],
    ["abono_hk_kitchen_chopping2", ["chopping vegetables on a wooden board overhead", "knife cutting vegetables in a home kitchen"], "picando verdura"],
    ["abono_hk_garden_rows2", ["green vegetable garden rows from above", "tidy raised beds of vegetables"], "hileras de la huerta"],
  ],
  intro: [
    ["abono_in_store_aisle2", ["garden center aisle with plant products", "person walking a nursery store aisle"], "pasillo del vivero"],
    ["abono_in_hand_soil_pour2", ["dark soil pouring between two hands slowly", "loose earth sifting through fingers"], "tierra cayendo entre las manos"],
    ["abono_in_compost_bin2", ["open compost bin full of kitchen waste", "backyard compost heap close up"], "el cajón de compost"],
  ],
  egg: [
    ["abono_eg_eggshell_grind2", ["grinding eggshells into white powder mortar", "crushed eggshell powder on a spoon"], "moliendo cáscara"],
    ["abono_eg_eggs_carton2", ["brown eggs in a carton on a table", "fresh eggs cracked into a bowl"], "huevos en la mesa"],
    ["abono_eg_seedling_plant2", ["planting a tomato seedling into dark soil", "hands firming soil around a young plant"], "plantando el plantín"],
  ],
  coffee: [
    ["abono_cf_pour_grounds2", ["dumping wet coffee grounds onto soil", "spent coffee grounds tipped from a scoop"], "volcando la borra"],
    ["abono_cf_espresso_puck2", ["knocking an espresso puck out of a portafilter", "wet coffee puck close up"], "el café usado"],
    ["abono_cf_worm_soil2", ["earthworm burrowing into dark rich soil", "worms in compost macro"], "lombriz en la tierra"],
  ],
  banana: [
    ["abono_bn_chop_peel2", ["chopping a banana peel into small pieces", "scissors cutting banana skin into a jar"], "cortando la cáscara"],
    ["abono_bn_jar_steep2", ["jar of peels steeping in water on a shelf", "amber liquid in a glass jar by a window"], "el frasco en remojo"],
    ["abono_bn_flower_macro2", ["yellow tomato flower macro in the garden", "blossom opening on a vegetable plant"], "flor en macro"],
  ],
  water: [
    ["abono_wt_boil_pot2", ["vegetables boiling in a steaming pot on a stove", "green water boiling with broccoli"], "olla hirviendo"],
    ["abono_wt_pour_plant2", ["pouring water from a jug onto a potted plant", "watering a green plant indoors"], "regando la maceta"],
    ["abono_wt_green_leaves2", ["glossy deep green plant leaves close up", "healthy vibrant foliage macro"], "hojas verdes sanas"],
  ],
  onion: [
    ["abono_on_peel_onion2", ["peeling papery skin off an onion close up", "dry onion skins falling onto a board"], "pelando cebolla"],
    ["abono_on_spray_plant2", ["spraying a garden plant with a mist bottle", "misting leaves at dusk in a garden"], "rociando la planta"],
    ["abono_on_aphids_macro2", ["green aphids on a plant stem macro", "cluster of aphids under a leaf"], "pulgones en macro"],
  ],
  tea: [
    ["abono_te_teabag_cup2", ["tea bag steeping in a cup of hot water", "lifting a wet tea bag from a mug"], "la bolsita en la taza"],
    ["abono_te_leaves_soil2", ["loose tea leaves scattered on garden soil", "emptying tea leaves onto a bed"], "hojas de té en la tierra"],
  ],
  scraps: [
    ["abono_sc_peel_potato2", ["peeling potatoes over a bowl of scraps", "potato peelings curling off a peeler"], "pelando papas"],
    ["abono_sc_bowl_scraps2", ["bowl of mixed vegetable kitchen scraps", "colorful peels and ends in a bowl"], "bol de recortes"],
    ["abono_sc_bury_hole2", ["burying scraps in a hole in a garden bed", "covering food waste with soil by hand"], "enterrando en el pozo"],
  ],
  trench: [
    ["abono_tr_spade_dig2", ["digging soil with a spade in a garden", "shovel turning over dark earth"], "cavando con la pala"],
    ["abono_tr_bucket_scraps2", ["a bucket of kitchen scraps by a garden", "compost pail full of food waste"], "el balde de restos"],
    ["abono_tr_tomatoes_harvest2", ["harvesting ripe red tomatoes into a basket", "hands picking tomatoes off the vine"], "cosechando tomates"],
  ],
  closing: [
    ["abono_cl_garden_evening2", ["vegetable garden glowing in evening light", "rows of plants at golden hour"], "huerta al atardecer"],
    ["abono_cl_harvest_basket2", ["basket full of fresh garden vegetables", "holding a harvest of tomatoes and greens"], "canasta de cosecha"],
  ],
};
