// cues_choclo.gen.tsx — GENERADO por beatsheet.mjs desde choclo.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/choclo.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { HalfShot } from "./scenes/HalfShot";
import { MistakeCard } from "./scenes/MistakeCard";
import { LieList } from "./scenes/LieList";
import { NumberCard } from "./scenes/NumberCard";
import { GridReveal } from "./scenes/GridReveal";
import { GrowthTimeline } from "./scenes/GrowthTimeline";
import { KineticLine } from "./scenes/KineticLine";
import { BlurReveal } from "./scenes/BlurReveal";
import { LoupeInspect } from "./setpieces/LoupeInspect";
import { FocusCard } from "./setpieces/FocusCard";
import { SplitExplain } from "./setpieces/SplitExplain";

const D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "bh1_corn_h1_bin_pile_store", start: 2.05, dur: 2.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_bin_pile_store.mp4" darken={0} /> },
  { key: "bh2_corn_h1_bin_pile_store", start: 4.26, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_bin_pile_store.mp4" darken={0} /> },
  { key: "bh3_corn_h1_peel_husk_store", start: 6.52, dur: 2.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_peel_husk_store.mp4" darken={0} /> },
  { key: "bh4_corn_h1_roadside_stand", start: 8.83, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_roadside_stand.mp4" darken={0} /> },
  { key: "bh5_corn_h1_roadside_stand", start: 10.79, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_roadside_stand.mp4" darken={0} /> },
  { key: "bh6_corn_h1_corn_close_spin", start: 14.81, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_corn_close_spin.mp4" darken={0} /> },
  { key: "bh7_corn_h1_hands_feel_ear", start: 17.13, dur: 1.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_hands_feel_ear.mp4" darken={0} /> },
  { key: "bh8_corn_h1_husk_green_tight", start: 18.57, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_husk_green_tight.mp4" darken={0} /> },
  { key: "bh9_corn_h1_husk_green_tight", start: 20.53, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_husk_green_tight.mp4" darken={0} /> },
  { key: "bh10_corn_h1_torn_husks_pile", start: 22.55, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_torn_husks_pile.mp4" darken={0} /> },
  { key: "bh11_corn_h1_grandfather_hands", start: 24.61, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_grandfather_hands.mp4" darken={0} /> },
  { key: "bh12_corn_h1_grandfather_hands", start: 26.51, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_grandfather_hands.mp4" darken={0} /> },
  { key: "bh13_corn_h1_market_corn_crates", start: 28.45, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_market_corn_crates.mp4" darken={0} /> },
  { key: "bh14_corn_h1_husk_pale_dry", start: 30.45, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_husk_pale_dry.mp4" darken={0} /> },
  { key: "bh15_corn_h1_husk_pale_dry", start: 34.5, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_husk_pale_dry.mp4" darken={0} /> },
  { key: "cmp_split_notools", start: 38.6, dur: 4.2, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Sin trucos, sin aparatos" items={["Sin herramientas","Nada que memorizar","Sin pelar"]} accent={D} cross /> },
  { key: "bf_corn_h1_bin_pile_store_428", start: 42.8, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_bin_pile_store.mp4" darken={0} /> },
  { key: "bh18_corn_h1_torn_husks_pile", start: 46.85, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_torn_husks_pile.mp4" darken={0} /> },
  { key: "bh19_corn_h1_peel_husk_store", start: 49.27, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_peel_husk_store.mp4" darken={0} /> },
  { key: "bh20_corn_h1_peel_husk_store", start: 52.23, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_peel_husk_store.mp4" darken={0} /> },
  { key: "bh21_corn_h1_boiling_pot", start: 55.23, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_boiling_pot.mp4" darken={0} /> },
  { key: "cmp_loop", start: 58.23, dur: 4.2, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="!" title="El error que arruina tu choclo" desc="Casi todos lo hacen en el súper — y les cuesta el dulzor." eyebrow="EN ESTE VIDEO" image="img/cmp_loop_bg.png" /> },
  { key: "bf_corn_h1_eating_corn_624", start: 62.43, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h1_eating_corn.mp4" darken={0} /> },
  { key: "b1_corn_h2_peel_check_store", start: 65.82, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_peel_check_store_1.jpg" darken={0} /> },
  { key: "b2_corn_h2_mess_husks_counter", start: 67.64, dur: 2.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_mess_husks_counter_1.jpg" darken={0} /> },
  { key: "b3_corn_h2_chewy_corn_plate", start: 69.46, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_chewy_corn_plate_1.jpg" darken={0} /> },
  { key: "b4_corn_h2_butter_disappoint", start: 72.18, dur: 1.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_butter_disappoint_1.jpg" darken={0} /> },
  { key: "b5_corn_h2_grandfather_walk_stand", start: 73.7, dur: 1.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_grandfather_walk_stand_1.jpg" darken={0} /> },
  { key: "b6_corn_h2_hand_glide_ears", start: 75.28, dur: 2.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_hand_glide_ears_1.jpg" darken={0} /> },
  { key: "b7_corn_h2_grandfather_choose", start: 77.14, dur: 1.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_grandfather_choose_1.jpg" darken={0} /> },
  { key: "b8_corn_h2_amish_stand_lane", start: 78.58, dur: 1.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_amish_stand_lane_1.jpg" darken={0} /> },
  { key: "b9_corn_h2_six_ears_lineup", start: 79.98, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_six_ears_lineup_1.jpg" darken={0} /> },
  { key: "b10_corn_h2_hands_two_ears", start: 81.82, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_hands_two_ears_1.jpg" darken={0} /> },
  { key: "b11_corn_h2_grandfather_portrait", start: 83.62, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_grandfather_portrait_1.jpg" darken={0} /> },
  { key: "b12_corn_h2_field_rows_walk", start: 85.88, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_h2_field_rows_walk.mp4" darken={0} /> },
  { key: "b13_corn_h2_kitchen_corn_pot", start: 87.86, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_kitchen_corn_pot_1.jpg" darken={0} /> },
  { key: "b14_corn_h2_corn_basket_porch", start: 91.16, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_corn_basket_porch_1.jpg" darken={0} /> },
  { key: "b15_corn_h2_peel_check_store", start: 94, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_peel_check_store_1.jpg" darken={0} /> },
  { key: "b16_corn_h2_mess_husks_counter", start: 96.48, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_pick_stand.png" darken={0} /> },
  { key: "b17_corn_h2_chewy_corn_plate", start: 98.9, dur: 1.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_chewy_corn_plate_1.jpg" darken={0} /> },
  { key: "b18_corn_h2_butter_disappoint", start: 100.28, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_butter_disappoint_1.jpg" darken={0} /> },
  { key: "b19_corn_h2_grandfather_walk_stand", start: 102.56, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_grandfather_walk_stand_1.jpg" darken={0} /> },
  { key: "b20_corn_h2_hand_glide_ears", start: 104.7, dur: 1.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_hand_glide_ears_1.jpg" darken={0} /> },
  { key: "cmp_checklist", start: 105.7, dur: 10.74, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="El método entero" items={[{"text":"Hojas verdes y ajustadas","state":"done"},{"text":"Pelos dorados y pegajosos","state":"done"},{"text":"Granos llenos hasta la punta","state":"done"},{"text":"Pesada para su tamaño","state":"done"},{"text":"Corte pálido y húmedo","state":"done"},{"text":"Dejale las hojas puestas","state":"done"}]} eyebrow="Frente al maíz" accent="good" hue="amber" image="img/cmp_checklist_bg.png" /> },
  { key: "b24_corn_h2_hands_two_ears", start: 116.44, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_hands_two_ears_1.jpg" darken={0} /> },
  { key: "b25_corn_h2_grandfather_portrait", start: 120.78, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_h2_grandfather_portrait_1.jpg" darken={0} /> },
  { key: "cmp_proc_read", start: 124.5, dur: 3.52, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Mirá las hojas y los pelos"},{"title":"Palpá los granos hasta la punta"},{"title":"Sopesá y mirá el corte del tallo"}]} eyebrow="Sin abrir nada" title="Cómo leer el maíz" accent="good" hue="amber" /> },
  { key: "b27_corn_vl_sugar_starch_macro", start: 169.4, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_sugar_starch_macro_1.jpg" darken={0} /> },
  { key: "b28_corn_vl_pick_stalk_snap", start: 172.02, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_pick_stalk_snap_1.jpg" darken={0} /> },
  { key: "b29_corn_vl_clock_ticking", start: 173.82, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_clock_ticking_1.jpg" darken={0} /> },
  { key: "cmp_sugar", start: 176.8, dur: 6.16, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="50%" eyebrow="Azúcar perdido en un día" caption="desde que sale de la caña" accent="danger" hue="amber" /> },
  { key: "b32_corn_vl_corn_on_truck", start: 182.96, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_corn_on_truck_1.jpg" darken={0} /> },
  { key: "b33_corn_vl_warehouse_pallets", start: 186.12, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_warehouse_pallets_1.jpg" darken={0} /> },
  { key: "cmp_clock", start: 188.46, dur: 6.66, kind: "growthtimeline", el: (d) => <GrowthTimeline durationInFrames={d} stages={[{"label":"Recién cortada","sub":"100% dulce"},{"label":"1 hora"},{"label":"1 día","sub":"mitad"},{"label":"En la góndola","sub":"harinosa"}]} title="El azúcar se vuelve almidón — rápido" bg="broll/corn_vl_field_to_kitchen.mp4" /> },
  { key: "b37_corn_vl_fresh_vs_old", start: 195.12, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_fresh_vs_old_1.jpg" darken={0} /> },
  { key: "cmp_quote_water", start: 198, dur: 9.88, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_water_bg.png" words={parseQuote("Tené el agua *hirviendo* antes de cortar el maíz.")} accent="amber" hue="amber" fontSize={84} /> },
  { key: "b41_corn_vl_sugar_starch_macro", start: 207.88, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_sugar_starch_macro_1.jpg" darken={0} /> },
  { key: "cmp_bars_days", start: 210.56, dur: 8.8, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Del puesto, esta mañana","value":0,"display":"0 días","winner":true},{"label":"Del supermercado","value":5,"display":"3–5 días","tone":"danger"}]} eyebrow="Puesto vs súper" title="Días desde que se cortó" unit="dias" accent="good" hue="amber" /> },
  { key: "b45_corn_vl_pot_boiling_ready", start: 219.36, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_pot_boiling_ready_1.jpg" darken={0} /> },
  { key: "cmp_bars_sugar", start: 221.4, dur: 9.04, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Cortado esta mañana","value":100,"display":"100%","winner":true},{"label":"De un día","value":50,"display":"~50%","tone":"danger"},{"label":"Días en la góndola","value":20,"display":"~20%","tone":"danger"}]} eyebrow="¿Qué tan fresco está?" title="Azúcar que queda en el grano" unit="%" accent="good" hue="amber" /> },
  { key: "cmp_oldcorn", start: 230.44, dur: 8.44, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_oldcorn_bg.png" impact="Es maíz VIEJO." setup="¿Soso, duro, a cartón?" impactAccent="danger" hitAt={1.1} boom={0} darken={0.45} /> },
  { key: "b51_corn_vl_fresh_vs_old", start: 238.88, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_fresh_vs_old_1.jpg" darken={0} /> },
  { key: "b52_corn_vl_kernel_drop_juice", start: 241.64, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_kernel_drop_juice_1.jpg" darken={0} /> },
  { key: "b53_corn_vl_supermarket_aisle", start: 244.98, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_supermarket_aisle_1.webp" darken={0} /> },
  { key: "b54_corn_vl_corn_stalks_wide", start: 248.04, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_corn_stalks_wide_1.jpg" darken={0} /> },
  { key: "b55_corn_vl_sugar_starch_macro", start: 250.48, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_sugar_starch_macro_1.jpg" darken={0} /> },
  { key: "b56_corn_vl_pick_stalk_snap", start: 252.58, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_pick_stalk_snap_1.jpg" darken={0} /> },
  { key: "b57_corn_vl_clock_ticking", start: 256.34, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_vl_clock_ticking_1.jpg" darken={0} /> },
  { key: "b58_corn_hr_machine_harvest", start: 260.08, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_machine_harvest_1.jpg" darken={0} /> },
  { key: "b59_corn_hr_uniform_corn_crates", start: 262.8, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_uniform_corn_crates_1.jpg" darken={0} /> },
  { key: "b60_corn_hr_pretty_husk_shelf", start: 266.14, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_pretty_husk_shelf_1.jpg" darken={0} /> },
  { key: "cmp_ship", start: 268.66, dur: 11.62, kind: "lielist", el: (d) => <LieList durationInFrames={d} title="Criado para la góndola, no para vos" items={["Madura todo junto para las máquinas","Se ve lindo una semana","El sabor es lo último"]} image="img/cmp_ship_bg.png" accent="danger" /> },
  { key: "b64_corn_hr_dried_seed_corn", start: 280.28, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_dried_seed_corn_1.jpg" darken={0} /> },
  { key: "b65_corn_hr_grandfather_field", start: 282, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_hr_grandfather_field.mp4" darken={0} /> },
  { key: "b66_corn_hr_perfect_ear", start: 284, dur: 4.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_perfect_ear_1.jpg" darken={0} /> },
  { key: "b67_corn_hr_machine_harvest", start: 287.64, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_machine_harvest_1.jpg" darken={0} /> },
  { key: "b68_corn_hr_uniform_corn_crates", start: 291.02, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_uniform_corn_crates_1.jpg" darken={0} /> },
  { key: "b69_corn_hr_pretty_husk_shelf", start: 292.94, dur: 5.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_seed_save.png" darken={0} /> },
  { key: "cmp_heirloom", start: 297.62, dur: 9.12, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} image="img/cmp_heirloom_bg.png" title="Las variedades de antes" chips={["Golden Bantam","Stowell's Evergreen","Polinización abierta"]} hue="amber" /> },
  { key: "b73_corn_hr_dried_seed_corn", start: 306.74, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_dried_seed_corn_1.jpg" darken={0} /> },
  { key: "b74_corn_hr_grandfather_field", start: 310.5, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_hr_grandfather_field.mp4" darken={0} /> },
  { key: "b75_corn_hr_perfect_ear", start: 314.26, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_perfect_ear_1.jpg" darken={0} /> },
  { key: "cmp_focus_heirloom", start: 316.06, dur: 9.42, kind: "focuscard", el: (d) => <FocusCard durationInFrames={d} bg="real/corn_hr_heirloom_basket_1.jpg" image="real/corn_hr_golden_bantam_1.jpg" title="Un día perfecto" desc="Demasiado tierno para viajar — pero nada sabe como él." eyebrow="Maíz de antes" imageSide="left" accent="amber" /> },
  { key: "b80_corn_hr_uniform_corn_crates", start: 325.48, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_uniform_corn_crates_1.jpg" darken={0} /> },
  { key: "b81_corn_hr_pretty_husk_shelf", start: 328.6, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_pretty_husk_shelf_1.jpg" darken={0} /> },
  { key: "b82_corn_hr_golden_bantam", start: 333.22, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_golden_bantam_1.jpg" darken={0} /> },
  { key: "b83_corn_hr_white_corn", start: 336, dur: 6.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_white_corn_1.jpg" darken={0} /> },
  { key: "cmp_split_myth", start: 341.58, dur: 12.48, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Lo que el súper no te dice" items={["Lo cortaron hace días","Viajó y esperó en góndola","Criado para viajar, no para vos"]} accent={D} cross /> },
  { key: "b87_corn_hr_perfect_ear", start: 354.06, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_perfect_ear_1.jpg" darken={0} /> },
  { key: "b88_corn_hr_open_pollinated", start: 356.6, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_open_pollinated_1.jpg" darken={0} /> },
  { key: "b89_corn_hr_heirloom_basket", start: 359.22, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_hr_heirloom_basket_1.jpg" darken={0} /> },
  { key: "cmp_sign_1", start: 361.4, dur: 3.86, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="1" name="Las hojas" bg="broll/corn_s1_husk_hold_light.mp4" eyebrow="Leéla desde afuera" total="6" accent="amber" /> },
  { key: "b91_corn_s1_husk_hold_light", start: 365.26, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s1_husk_hold_light.mp4" darken={0} /> },
  { key: "cmp_half_husk", start: 367.4, dur: 7.5, kind: "half", el: (d) => <HalfShot durationInFrames={d} src="real/corn_s1_husk_bright_green_1.jpg" side="right" kicker="Verde brillante,\nbien ajustadas\n= fresco" hue="amber" /> },
  { key: "b96_corn_s1_dry_kernels", start: 374.9, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_dry_kernels_1.webp" darken={0} /> },
  { key: "b97_corn_s1_corn_pile_store", start: 376.86, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s1_corn_pile_store.mp4" darken={0} /> },
  { key: "b98_corn_s1_hand_select_husk", start: 378.78, dur: 7.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_hand_select_husk_1.jpg" darken={0} /> },
  { key: "b99_corn_s1_husk_layers_macro", start: 385.7, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_husk_layers_macro_1.jpg" darken={0} /> },
  { key: "b100_corn_s1_corn_field_green", start: 388.86, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_corn_field_green_1.jpg" darken={0} /> },
  { key: "b101_corn_s1_two_husks_compare", start: 390.94, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_two_husks_compare_1.jpg" darken={0} /> },
  { key: "b102_corn_s1_husk_bright_green", start: 393.72, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_husk_bright_green_1.jpg" darken={0} /> },
  { key: "b103_corn_s1_husk_hold_light", start: 397.12, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s1_husk_hold_light.mp4" darken={0} /> },
  { key: "cmp_anno_husk", start: 401.12, dur: 4.38, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_husk_bg.png" annotations={[{"kind":"circle","x":0.38,"y":0.45,"w":0.2,"label":"Verde brillante = fresco","color":"good"},{"kind":"arrow","x":0.7,"y":0.5,"fromX":0.9,"fromY":0.2,"label":"Pálidas = viejo","color":"danger"}]} eyebrow="Leé las hojas" hue="amber" /> },
  { key: "cmp_bars_kernels", start: 405.5, dur: 10.04, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Grano fresco, jugoso","value":100,"display":"Dulce","winner":true},{"label":"Grano seco","value":30,"display":"Harinoso","tone":"danger"}]} eyebrow="Fresco vs reseco" title="Humedad en el grano" unit="%" accent="good" hue="amber" /> },
  { key: "b108_corn_s1_dry_kernels", start: 415.54, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_dry_kernels_1.webp" darken={0} /> },
  { key: "b109_corn_s1_corn_pile_store", start: 419.26, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s1_corn_pile_store.mp4" darken={0} /> },
  { key: "b110_corn_s1_hand_select_husk", start: 421.96, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_hand_select_husk_1.jpg" darken={0} /> },
  { key: "b111_corn_s1_husk_layers_macro", start: 425.1, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_husk_layers_macro_1.jpg" darken={0} /> },
  { key: "b112_corn_s1_corn_field_green", start: 427.54, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_corn_field_green_1.jpg" darken={0} /> },
  { key: "b113_corn_s1_two_husks_compare", start: 429.3, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_two_husks_compare_1.jpg" darken={0} /> },
  { key: "b114_corn_s1_husk_bright_green", start: 431.5, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_husk_bright_green_1.jpg" darken={0} /> },
  { key: "b115_corn_s1_husk_hold_light", start: 433.42, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s1_husk_hold_light.mp4" darken={0} /> },
  { key: "b116_corn_s1_husk_pale_paper", start: 435.58, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_husk_pale_paper_1.jpg" darken={0} /> },
  { key: "b117_corn_s1_husk_brown_edge", start: 437.9, dur: 5.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s1_husk_brown_edge_1.png" darken={0} /> },
  { key: "b118_corn_a1_hurried_man_stand", start: 443.36, dur: 5.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_hurried_man_stand_1.jpg" darken={0} /> },
  { key: "b119_corn_a1_top_pile_sun", start: 448.14, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_top_pile_sun_1.jpg" darken={0} /> },
  { key: "b120_corn_a1_pale_husk_top", start: 449.86, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_pale_husk_top_1.jpg" darken={0} /> },
  { key: "b121_corn_a1_grandfather_watch", start: 453.64, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_grandfather_watch_1.jpg" darken={0} /> },
  { key: "b122_corn_a1_reach_under_pile", start: 456.92, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_hurried_man.png" darken={0} /> },
  { key: "b123_corn_a1_green_ears_handover", start: 460.5, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a1_green_ears_handover.mp4" darken={0} /> },
  { key: "b124_corn_a1_shade_cool_corn", start: 463.44, dur: 2.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_shade_cool_corn_1.jpg" darken={0} /> },
  { key: "b125_corn_a1_amish_stand_morning", start: 465.66, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_amish_stand_morning_1.jpg" darken={0} /> },
  { key: "b126_corn_a1_glowing_green_husk", start: 469.38, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_glowing_green_husk_1.jpg" darken={0} /> },
  { key: "b127_corn_a1_boy_helping_stand", start: 472.36, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a1_boy_helping_stand.mp4" darken={0} /> },
  { key: "b128_corn_a1_hurried_man_stand", start: 476.78, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_hurried_man_stand_1.jpg" darken={0} /> },
  { key: "b129_corn_a1_top_pile_sun", start: 481.44, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_reach_shade.png" darken={0} /> },
  { key: "b130_corn_a1_pale_husk_top", start: 484.98, dur: 2.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_pale_husk_top_1.jpg" darken={0} /> },
  { key: "b131_corn_a1_grandfather_watch", start: 486.68, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_hand_over.png" darken={0} /> },
  { key: "b132_corn_a1_reach_under_pile", start: 491.04, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_reach_under_pile_1.jpg" darken={0} /> },
  { key: "b133_corn_a1_green_ears_handover", start: 494.02, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a1_green_ears_handover.mp4" darken={0} /> },
  { key: "b134_corn_a1_shade_cool_corn", start: 497.58, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a1_shade_cool_corn_1.jpg" darken={0} /> },
  { key: "cmp_sign_2", start: 503.08, dur: 3.06, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="2" name="Los pelos" bg="broll/corn_s2_silk_black_slimy.mp4" eyebrow="Leéla desde afuera" total="6" accent="amber" /> },
  { key: "cmp_half_shade", start: 506.14, dur: 6.88, kind: "half", el: (d) => <HalfShot durationInFrames={d} src="real/corn_a1_shade_cool_corn_1.jpg" side="left" kicker="Las buenas se\nesconden donde\nestá fresco" hue="amber" /> },
  { key: "b138_corn_s2_silk_golden", start: 513.02, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_golden_1.jpg" darken={0} /> },
  { key: "b139_corn_s2_silk_soft_sticky", start: 517.32, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_soft_sticky_1.jpg" darken={0} /> },
  { key: "b140_corn_s2_silk_black_slimy", start: 519.42, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s2_silk_black_slimy.mp4" darken={0} /> },
  { key: "cmp_anno_silk", start: 521.84, dur: 9.48, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_silk_bg.png" annotations={[{"kind":"circle","x":0.5,"y":0.28,"w":0.22,"label":"Dorados, blandos, pegajosos","color":"good"},{"kind":"arrow","x":0.5,"y":0.6,"fromX":0.82,"fromY":0.85,"label":"No negros, no verdes","color":"amber"}]} eyebrow="Leé los pelos" hue="amber" /> },
  { key: "cmp_loupe_silk", start: 531.32, dur: 2.8, kind: "loupe", el: (d) => <LoupeInspect durationInFrames={d} image="real/corn_s2_silk_golden_1.jpg" focusX={0.5} focusY={0.28} zoom={1.7} label="Dorados, blandos, pegajosos" accent="amber" /> },
  { key: "cmp_proc_silk", start: 534.12, dur: 13.62, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Dorados y blandos = madura"},{"title":"Apenas pegajosos = fresca"},{"title":"Negros o verdes = descartar"}]} eyebrow="Sin abrir la hoja" title="Qué dicen los pelos" accent="good" hue="amber" /> },
  { key: "b148_corn_s2_silk_tip_macro", start: 547.74, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_tip_macro_1.jpg" darken={0} /> },
  { key: "cmp_split_silk", start: 551.34, dur: 6.28, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Pelos para evitar" items={["Negros, babosos, blandos","Verdes y tiesos","Secos y polvorientos"]} accent={D} cross /> },
  { key: "b152_corn_s2_silk_green_stiff", start: 557.62, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_green_stiff_1.jpg" darken={0} /> },
  { key: "b153_corn_s2_roll_silk_fingers", start: 559.44, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_roll_silk_fingers_1.jpg" darken={0} /> },
  { key: "b154_corn_s2_silk_breeze", start: 562.12, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_breeze_1.jpg" darken={0} /> },
  { key: "b155_corn_s2_cob_top_silk", start: 566.34, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_cob_top_silk_1.jpg" darken={0} /> },
  { key: "b156_corn_s2_silk_drying_gold", start: 568.98, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s2_silk_drying_gold.mp4" darken={0} /> },
  { key: "b157_corn_s2_tassel_field", start: 571.02, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s2_tassel_field.mp4" darken={0} /> },
  { key: "b158_corn_s2_hand_inspect_silk", start: 575.56, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_hand_inspect_silk_1.webp" darken={0} /> },
  { key: "b159_corn_s2_silk_tip_macro", start: 577.6, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_tip_macro_1.jpg" darken={0} /> },
  { key: "b160_corn_s2_silk_golden", start: 580.54, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_golden_1.jpg" darken={0} /> },
  { key: "b161_corn_s2_silk_soft_sticky", start: 582.52, dur: 5.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_roll_silk.png" darken={0} /> },
  { key: "b162_corn_s2_silk_black_slimy", start: 587.34, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s2_silk_black_slimy.mp4" darken={0} /> },
  { key: "b163_corn_s2_silk_green_stiff", start: 591.06, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_green_stiff_1.jpg" darken={0} /> },
  { key: "b164_corn_s2_roll_silk_fingers", start: 593.3, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_roll_silk_fingers_1.jpg" darken={0} /> },
  { key: "b165_corn_s2_silk_breeze", start: 595.1, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_silk_breeze_1.jpg" darken={0} /> },
  { key: "b166_corn_s2_cob_top_silk", start: 597.66, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s2_cob_top_silk_1.jpg" darken={0} /> },
  { key: "b167_corn_s2_silk_drying_gold", start: 601.36, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s2_silk_drying_gold.mp4" darken={0} /> },
  { key: "cmp_sign_3", start: 604.84, dur: 5.1, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="3" name="Palpá los granos" bg="broll/corn_s3_fingers_down_cob.mp4" eyebrow="Leéla desde afuera" total="6" accent="amber" /> },
  { key: "b170_corn_s3_tip_full_round", start: 609.94, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_tip_full_round_1.jpg" darken={0} /> },
  { key: "b171_corn_s3_tip_thin_pinch", start: 612.68, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_tip_thin_pinch_1.jpg" darken={0} /> },
  { key: "b172_corn_s3_bald_patch_tip", start: 615.12, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_bald_patch_tip_1.jpg" darken={0} /> },
  { key: "b173_corn_s3_kernels_pearls", start: 618.26, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_kernels_pearls_1.jpg" darken={0} /> },
  { key: "b174_corn_s3_press_kernel_give", start: 621.12, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_press_kernel_give_1.jpg" darken={0} /> },
  { key: "cmp_loupe_tip", start: 623, dur: 3.28, kind: "loupe", el: (d) => <LoupeInspect durationInFrames={d} image="real/corn_s3_tip_full_round_1.jpg" focusX={0.8} focusY={0.5} zoom={1.8} label="Llena hasta la punta" accent="good" /> },
  { key: "cmp_split_fooled", start: 626.28, dur: 8.62, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Donde se engaña la gente" items={["Palpan solo el medio","Confían en un centro gordo","Se saltean la punta"]} accent={D} cross /> },
  { key: "cmp_anno_tip", start: 634.9, dur: 7.12, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_tip_bg.png" annotations={[{"kind":"circle","x":0.78,"y":0.5,"w":0.18,"label":"Punta llena = repleta","color":"good"},{"kind":"arrow","x":0.78,"y":0.5,"fromX":0.95,"fromY":0.85,"label":"Punta fina = huecos","color":"danger"}]} eyebrow="Palpá la PUNTA" hue="amber" /> },
  { key: "b182_corn_s3_tip_full_round", start: 642.02, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_tip_full_round_1.jpg" darken={0} /> },
  { key: "b183_corn_s3_tip_thin_pinch", start: 644.98, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_tip_thin_pinch_1.jpg" darken={0} /> },
  { key: "b184_corn_s3_bald_patch_tip", start: 646.88, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_bald_patch_tip_1.jpg" darken={0} /> },
  { key: "b185_corn_s3_kernels_pearls", start: 650.2, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_kernels_pearls_1.jpg" darken={0} /> },
  { key: "b186_corn_s3_press_kernel_give", start: 652.98, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_press_kernel_give_1.jpg" darken={0} /> },
  { key: "b187_corn_s3_rock_hard_kernels", start: 655.44, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s3_rock_hard_kernels.mp4" darken={0} /> },
  { key: "b188_corn_s3_pollination_cob", start: 657.92, dur: 7.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_pollination_cob_1.jpg" darken={0} /> },
  { key: "b189_corn_s3_hand_feel_market", start: 664.54, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s3_hand_feel_market.mp4" darken={0} /> },
  { key: "cmp_split_kernels", start: 666.36, dur: 6.76, kind: "splitexplain", el: (d) => <SplitExplain durationInFrames={d} bg="real/corn_s3_kernels_pearls_1.jpg" image="real/corn_s3_kernels_pearls_1.jpg" title="Como hileras de perlas" points={["Gorditos y parejos","Firmes pero ceden un poco","Hasta la punta misma"]} eyebrow="Palpá los granos" accent="good" /> },
  { key: "b191_corn_s3_corn_rows_macro", start: 673.12, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_corn_rows_macro_1.jpg" darken={0} /> },
  { key: "b192_corn_s3_fingers_down_cob", start: 675.88, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s3_fingers_down_cob.mp4" darken={0} /> },
  { key: "b193_corn_s3_feel_plump_even", start: 679.32, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_feel_plump_even_1.jpg" darken={0} /> },
  { key: "b194_corn_s3_tip_full_round", start: 682.52, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_tip_full_round_1.jpg" darken={0} /> },
  { key: "b195_corn_s3_tip_thin_pinch", start: 686.34, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_tip_thin_pinch_1.jpg" darken={0} /> },
  { key: "b196_corn_s3_bald_patch_tip", start: 688.78, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_bald_patch_tip_1.jpg" darken={0} /> },
  { key: "b197_corn_s3_kernels_pearls", start: 690.68, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_kernels_pearls_1.jpg" darken={0} /> },
  { key: "b198_corn_s3_press_kernel_give", start: 693.46, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_press_kernel_give_1.jpg" darken={0} /> },
  { key: "b199_corn_s3_rock_hard_kernels", start: 695.24, dur: 6.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s3_rock_hard_kernels.mp4" darken={0} /> },
  { key: "b200_corn_s3_pollination_cob", start: 701.08, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_pollination_cob_1.jpg" darken={0} /> },
  { key: "b201_corn_s3_hand_feel_market", start: 705.7, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s3_hand_feel_market.mp4" darken={0} /> },
  { key: "b202_corn_s3_husk_unpeeled", start: 708.2, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s3_husk_unpeeled.mp4" darken={0} /> },
  { key: "b203_corn_s3_corn_rows_macro", start: 712.26, dur: 1.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s3_corn_rows_macro_1.jpg" darken={0} /> },
  { key: "b204_corn_a2_thumbnail_kernel", start: 713.48, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a2_thumbnail_kernel_1.jpg" darken={0} /> },
  { key: "b205_corn_a2_milky_juice", start: 718.24, dur: 7.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_thumbnail.png" darken={0} /> },
  { key: "b206_corn_a2_clear_watery", start: 725.52, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_clear_watery.mp4" darken={0} /> },
  { key: "b207_corn_a2_doughy_kernel", start: 728.54, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a2_doughy_kernel_1.png" darken={0} /> },
  { key: "b208_corn_a2_peel_corner_check", start: 731.12, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_peel_corner_check.mp4" darken={0} /> },
  { key: "b209_corn_a2_field_ready_pick", start: 733.48, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_check_field.png" darken={0} /> },
  { key: "b210_corn_a2_grandfather_test", start: 737.26, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_grandfather_test.mp4" darken={0} /> },
  { key: "b211_corn_a2_kernel_macro_burst", start: 741.46, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_kernel_macro_burst.mp4" darken={0} /> },
  { key: "b212_corn_a2_corn_stalk_close", start: 744, dur: 5.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_corn_stalk_close.mp4" darken={0} /> },
  { key: "b213_corn_a2_fingertips_feel", start: 749.24, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a2_fingertips_feel_1.jpg" darken={0} /> },
  { key: "cmp_milk", start: 752.48, dur: 3.48, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Leche" eyebrow="Pico de dulzor" caption="gordito, elástico, lleno — eso buscan tus dedos" accent="good" hue="amber" /> },
  { key: "cmp_focus_milk", start: 755.96, dur: 9.52, kind: "focuscard", el: (d) => <FocusCard durationInFrames={d} bg="real/corn_s3_kernels_pearls_1.jpg" image="real/corn_a2_thumbnail_kernel_1.jpg" title="Lechoso = pico de dulzor" desc="Gordito, elástico, lleno — justo lo que buscan tus dedos." eyebrow="La etapa de leche" imageSide="right" accent="good" /> },
  { key: "b218_corn_a2_peel_corner_check", start: 765.48, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_peel_corner_check.mp4" darken={0} /> },
  { key: "b219_corn_a2_field_ready_pick", start: 768.32, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_field_ready_pick.mp4" darken={0} /> },
  { key: "b220_corn_a2_grandfather_test", start: 770.84, dur: 7.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_grandfather_test.mp4" darken={0} /> },
  { key: "b221_corn_a2_kernel_macro_burst", start: 777.44, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_kernel_macro_burst.mp4" darken={0} /> },
  { key: "b222_corn_a2_corn_stalk_close", start: 780.6, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_corn_stalk_close.mp4" darken={0} /> },
  { key: "b223_corn_a2_fingertips_feel", start: 782.58, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a2_fingertips_feel_1.jpg" darken={0} /> },
  { key: "b224_corn_a2_thumbnail_kernel", start: 785.3, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a2_thumbnail_kernel_1.jpg" darken={0} /> },
  { key: "b225_corn_a2_milky_juice", start: 789.66, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_milky_juice.mp4" darken={0} /> },
  { key: "b226_corn_a2_clear_watery", start: 792.32, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_clear_watery.mp4" darken={0} /> },
  { key: "b227_corn_a2_doughy_kernel", start: 794.12, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a2_doughy_kernel_1.png" darken={0} /> },
  { key: "b228_corn_a2_peel_corner_check", start: 798.72, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_peel_corner_check.mp4" darken={0} /> },
  { key: "b229_corn_a2_field_ready_pick", start: 801.22, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a2_field_ready_pick.mp4" darken={0} /> },
  { key: "cmp_sign_4", start: 804.94, dur: 3.54, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="4" name="El peso" bg="broll/corn_s4_two_ears_balance.mp4" eyebrow="Leéla desde afuera" total="6" accent="amber" /> },
  { key: "b231_corn_s4_heavy_ear", start: 808.48, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_heavy_ear_1.jpg" darken={0} /> },
  { key: "b232_corn_s4_two_ears_balance", start: 810.98, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_two_ears_balance.mp4" darken={0} /> },
  { key: "b233_corn_s4_light_dry_ear", start: 813.1, dur: 6.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_light_dry_ear_1.jpg" darken={0} /> },
  { key: "b234_corn_s4_bounce_ear", start: 818.86, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_bounce_ear_1.jpg" darken={0} /> },
  { key: "b235_corn_s4_moisture_kernels", start: 820.74, dur: 2.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_moisture_kernels.mp4" darken={0} /> },
  { key: "b236_corn_s4_pick_from_bin", start: 822.4, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_pick_from_bin.mp4" darken={0} /> },
  { key: "b237_corn_s4_old_timer_pick", start: 825.24, dur: 5.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_old_timer_pick.mp4" darken={0} /> },
  { key: "b238_corn_s4_corn_set_back", start: 829.76, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_corn_set_back.mp4" darken={0} /> },
  { key: "b239_corn_s4_lift_ear_hand", start: 831.9, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_lift_ear_hand_1.png" darken={0} /> },
  { key: "b240_corn_s4_heavy_ear", start: 834.06, dur: 2.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_heavy_ear_1.jpg" darken={0} /> },
  { key: "b241_corn_s4_two_ears_balance", start: 835.8, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_two_ears_balance.mp4" darken={0} /> },
  { key: "b242_corn_s4_light_dry_ear", start: 837.86, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_light_dry_ear_1.jpg" darken={0} /> },
  { key: "b243_corn_s4_bounce_ear", start: 840.04, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_bounce_ear_1.jpg" darken={0} /> },
  { key: "b244_corn_s4_moisture_kernels", start: 842.38, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_moisture_kernels.mp4" darken={0} /> },
  { key: "b245_corn_s4_pick_from_bin", start: 845.68, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_pick_from_bin.mp4" darken={0} /> },
  { key: "b246_corn_s4_old_timer_pick", start: 849.8, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_old_timer_pick.mp4" darken={0} /> },
  { key: "b247_corn_s4_corn_set_back", start: 852.88, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_corn_set_back.mp4" darken={0} /> },
  { key: "b248_corn_s4_lift_ear_hand", start: 854.86, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_weigh_two.png" darken={0} /> },
  { key: "b249_corn_s4_heavy_ear", start: 858.08, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s4_heavy_ear_1.jpg" darken={0} /> },
  { key: "b250_corn_s4_two_ears_balance", start: 860.74, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s4_two_ears_balance.mp4" darken={0} /> },
  { key: "cmp_sign_5", start: 863.74, dur: 3.04, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="5" name="El corte del tallo" bg="broll/corn_s5_stem_pale_moist.mp4" eyebrow="Leéla desde afuera" total="6" accent="amber" /> },
  { key: "cmp_weight_half", start: 866.78, dur: 6.6, kind: "half", el: (d) => <HalfShot durationInFrames={d} src="broll/corn_s4_two_ears_balance.mp4" side="right" kicker="Pesada = fresca\nLiviana = vieja" hue="amber" /> },
  { key: "b254_corn_s5_stem_end_macro", start: 873.38, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_stem_end_macro_1.jpg" darken={0} /> },
  { key: "b255_corn_s5_stem_pale_moist", start: 874.98, dur: 4.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_pale_moist.mp4" darken={0} /> },
  { key: "b256_corn_s5_stem_brown_dry", start: 879.42, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_brown_dry.mp4" darken={0} /> },
  { key: "b257_corn_s5_flip_corn_over", start: 881.68, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_flip_corn_over_1.jpg" darken={0} /> },
  { key: "b258_corn_s5_snap_off_stalk", start: 883.78, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_snap_off_stalk.mp4" darken={0} /> },
  { key: "b259_corn_s5_inspect_base_store", start: 887.24, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_inspect_base_store_1.jpg" darken={0} /> },
  { key: "cmp_split_stem", start: 888.84, dur: 6.86, kind: "splitexplain", el: (d) => <SplitExplain durationInFrames={d} bg="real/corn_s5_stem_end_macro_1.jpg" image="real/corn_s5_stem_end_macro_1.jpg" title="Leé el corte del tallo" points={["Pálido y húmedo = nuevo","Marrón y seco = viejo","El corte no miente"]} eyebrow="Dala vuelta" accent="amber" /> },
  { key: "b263_corn_s5_stem_end_macro", start: 895.7, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_stem_end_macro_1.jpg" darken={0} /> },
  { key: "b264_corn_s5_stem_pale_moist", start: 897.64, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_pale_moist.mp4" darken={0} /> },
  { key: "b265_corn_s5_stem_brown_dry", start: 900.6, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_brown_dry.mp4" darken={0} /> },
  { key: "b266_corn_s5_flip_corn_over", start: 903.4, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_flip_corn_over_1.jpg" darken={0} /> },
  { key: "b267_corn_s5_snap_off_stalk", start: 905.44, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_snap_off_stalk.mp4" darken={0} /> },
  { key: "b268_corn_s5_inspect_base_store", start: 909.04, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_inspect_base_store_1.jpg" darken={0} /> },
  { key: "b269_corn_s5_tree_rings", start: 912.58, dur: 2.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_tree_rings_1.jpg" darken={0} /> },
  { key: "b270_corn_s5_corn_basket_base", start: 914.28, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_corn_basket_base.mp4" darken={0} /> },
  { key: "b271_corn_s5_old_twig_compare", start: 917.18, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_old_twig_compare.mp4" darken={0} /> },
  { key: "b272_corn_s5_stem_end_macro", start: 920.84, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_stem_end_macro_1.jpg" darken={0} /> },
  { key: "b273_corn_s5_stem_pale_moist", start: 922.44, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_pale_moist.mp4" darken={0} /> },
  { key: "b274_corn_s5_stem_brown_dry", start: 925.94, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_brown_dry.mp4" darken={0} /> },
  { key: "cmp_anno_stem", start: 928.34, dur: 6.24, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_stem_bg.png" annotations={[{"kind":"circle","x":0.42,"y":0.55,"w":0.18,"label":"Pálido y húmedo = nuevo","color":"good"},{"kind":"arrow","x":0.66,"y":0.55,"fromX":0.9,"fromY":0.85,"label":"Marrón y seco = viejo","color":"danger"}]} eyebrow="Dala vuelta" hue="amber" /> },
  { key: "b278_corn_s5_tree_rings", start: 934.58, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_tree_rings_1.jpg" darken={0} /> },
  { key: "b279_corn_s5_corn_basket_base", start: 937.52, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_corn_basket_base.mp4" darken={0} /> },
  { key: "b280_corn_s5_old_twig_compare", start: 940.34, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_old_twig_compare.mp4" darken={0} /> },
  { key: "b281_corn_s5_stem_end_macro", start: 942.58, dur: 2.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s5_stem_end_macro_1.jpg" darken={0} /> },
  { key: "b282_corn_s5_stem_pale_moist", start: 944.32, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_pale_moist.mp4" darken={0} /> },
  { key: "b283_corn_s5_stem_brown_dry", start: 946.18, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s5_stem_brown_dry.mp4" darken={0} /> },
  { key: "b284_corn_a3_dawn_field", start: 948.96, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_dawn_field.mp4" darken={0} /> },
  { key: "b285_corn_a3_dew_everywhere", start: 952.08, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_dew_everywhere.mp4" darken={0} /> },
  { key: "b286_corn_a3_harvest_morning", start: 953.84, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_harvest_morning.mp4" darken={0} /> },
  { key: "b287_corn_a3_sun_rising_corn", start: 956.42, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_sun_rising_corn.mp4" darken={0} /> },
  { key: "b288_corn_a3_basket_dawn", start: 958.58, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a3_basket_dawn_1.jpg" darken={0} /> },
  { key: "b289_corn_a3_hot_sun_field", start: 963.78, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_hot_sun_field.mp4" darken={0} /> },
  { key: "b290_corn_a3_ask_grower_stand", start: 965.84, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_ask_grower_stand.mp4" darken={0} /> },
  { key: "b291_corn_a3_fresh_picked_morning", start: 968.1, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a3_fresh_picked_morning_1.jpg" darken={0} /> },
  { key: "b292_corn_a3_stove_water_ready", start: 970.28, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_stove_water_ready.mp4" darken={0} /> },
  { key: "b293_corn_a3_farmers_market_wide", start: 972.06, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_farmers_market_wide.mp4" darken={0} /> },
  { key: "cmp_dawn", start: 974.44, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Amanecer" eyebrow="Más dulce a primera luz" caption="comprá temprano: día, semana, temporada" accent="good" hue="amber" /> },
  { key: "b296_corn_a3_harvest_morning", start: 980.94, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_harvest_morning.mp4" darken={0} /> },
  { key: "b297_corn_a3_sun_rising_corn", start: 983.74, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_sun_rising_corn.mp4" darken={0} /> },
  { key: "cmp_bars_dawn", start: 985.9, dur: 7.36, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Cortado al amanecer","value":100,"display":"El más dulce","winner":true},{"label":"Bajo el sol fuerte","value":70,"display":"Menos dulce","tone":"danger"}]} eyebrow="Por qué importa el amanecer" title="Dulzor según la hora" unit="%" accent="good" hue="amber" /> },
  { key: "b300_corn_a3_ask_grower_stand", start: 993.26, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_dawn_harvest.png" darken={0} /> },
  { key: "b301_corn_a3_fresh_picked_morning", start: 995.52, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a3_fresh_picked_morning_1.jpg" darken={0} /> },
  { key: "b302_corn_a3_stove_water_ready", start: 997.32, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_stove_water_ready.mp4" darken={0} /> },
  { key: "b303_corn_a3_farmers_market_wide", start: 1000.62, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_farmers_market_wide.mp4" darken={0} /> },
  { key: "b304_corn_a3_dawn_field", start: 1003.46, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_dawn_field.mp4" darken={0} /> },
  { key: "b305_corn_a3_dew_everywhere", start: 1006.02, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_dew_everywhere.mp4" darken={0} /> },
  { key: "b306_corn_a3_harvest_morning", start: 1009.68, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_harvest_morning.mp4" darken={0} /> },
  { key: "b307_corn_a3_sun_rising_corn", start: 1011.44, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_sun_rising_corn.mp4" darken={0} /> },
  { key: "b308_corn_a3_basket_dawn", start: 1013.48, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a3_basket_dawn_1.jpg" darken={0} /> },
  { key: "b309_corn_a3_hot_sun_field", start: 1015.56, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_hot_sun_field.mp4" darken={0} /> },
  { key: "b310_corn_a3_ask_grower_stand", start: 1018.6, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_ask_grower_stand.mp4" darken={0} /> },
  { key: "b311_corn_a3_fresh_picked_morning", start: 1022.82, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a3_fresh_picked_morning_1.jpg" darken={0} /> },
  { key: "b312_corn_a3_stove_water_ready", start: 1026.28, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_stove_water_ready.mp4" darken={0} /> },
  { key: "b313_corn_a3_farmers_market_wide", start: 1029.04, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_a3_farmers_market_wide.mp4" darken={0} /> },
  { key: "cmp_proc_early", start: 1030.84, dur: 9.08, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Temprano en el día"},{"title":"Temprano en la semana"},{"title":"Temprano en la temporada"}]} eyebrow="El maíz más fresco" title="Compralo temprano" accent="good" hue="amber" /> },
  { key: "b318_corn_a3_basket_dawn", start: 1039.92, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_a3_basket_dawn_1.jpg" darken={0} /> },
  { key: "cmp_sign_6", start: 1041.78, dur: 3.86, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="6" name="No la peles" bg="broll/corn_s6_pull_husk_back.mp4" eyebrow="La que nadie hace" total="6" accent="good" /> },
  { key: "b320_corn_s6_hands_off_husk", start: 1045.64, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_hands_off_husk_1.png" darken={0} /> },
  { key: "b321_corn_s6_pull_husk_back", start: 1048.74, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_pull_husk_back.mp4" darken={0} /> },
  { key: "b322_corn_s6_moisture_escaping", start: 1050.82, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_moisture_escaping.mp4" darken={0} /> },
  { key: "b323_corn_s6_husk_packaging", start: 1052.94, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_husk_packaging.mp4" darken={0} /> },
  { key: "b324_corn_s6_clock_fast", start: 1055.78, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_clock_fast.mp4" darken={0} /> },
  { key: "b325_corn_s6_man_tearing_corn", start: 1058.46, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_man_tearing_corn.mp4" darken={0} /> },
  { key: "b326_corn_s6_corn_sealed_home", start: 1060.52, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_corn_sealed_home.mp4" darken={0} /> },
  { key: "cmp_nopeel", start: 1062.86, dur: 7.84, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_nopeel_bg.png" impact="NO la peles." setup="Todos hacen esto..." impactAccent="danger" hitAt={1.1} boom={0} darken={0.5} /> },
  { key: "b329_corn_s6_six_signs_montage", start: 1070.7, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_six_signs_montage.mp4" darken={0} /> },
  { key: "b330_corn_s6_husk_tight_wrap", start: 1073.48, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_husk_tight_wrap_1.jpg" darken={0} /> },
  { key: "b331_corn_s6_hands_off_husk", start: 1076.58, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_hands_off_husk_1.png" darken={0} /> },
  { key: "b332_corn_s6_pull_husk_back", start: 1078.54, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_pull_husk_back.mp4" darken={0} /> },
  { key: "b333_corn_s6_moisture_escaping", start: 1081.6, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_moisture_escaping.mp4" darken={0} /> },
  { key: "b334_corn_s6_husk_packaging", start: 1085.14, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_husk_packaging.mp4" darken={0} /> },
  { key: "b335_corn_s6_clock_fast", start: 1087.84, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_clock_fast.mp4" darken={0} /> },
  { key: "b336_corn_s6_man_tearing_corn", start: 1091.3, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_man_tearing_corn.mp4" darken={0} /> },
  { key: "b337_corn_s6_corn_sealed_home", start: 1094.52, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_corn_sealed_home.mp4" darken={0} /> },
  { key: "b338_corn_s6_peel_at_pot", start: 1096.2, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_peel_at_pot_1.jpg" darken={0} /> },
  { key: "cmp_proc_peel", start: 1097.92, dur: 8.22, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Se escapa la humedad"},{"title":"Entra el aire"},{"title":"El azúcar se vuelve almidón — al doble"}]} eyebrow="Acelerás el reloj" title="Qué hace pelarla" accent="danger" hue="amber" /> },
  { key: "b342_corn_s6_hands_off_husk", start: 1106.14, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_hands_off_husk_1.png" darken={0} /> },
  { key: "b343_corn_s6_pull_husk_back", start: 1110.02, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_pull_husk_back.mp4" darken={0} /> },
  { key: "b344_corn_s6_moisture_escaping", start: 1112.18, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_moisture_escaping.mp4" darken={0} /> },
  { key: "b345_corn_s6_husk_packaging", start: 1115.8, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_husk_packaging.mp4" darken={0} /> },
  { key: "cmp_proc_husk", start: 1119, dur: 9.02, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Leé la mazorca desde afuera"},{"title":"Dejale las hojas puestas"},{"title":"Pelala recién con el agua hirviendo"}]} eyebrow="Sellá el dulzor" title="La regla de las hojas" accent="good" hue="amber" /> },
  { key: "b349_corn_s6_peel_at_pot", start: 1128.02, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_peel_at_pot_1.jpg" darken={0} /> },
  { key: "b350_corn_s6_hot_water_drop", start: 1129.94, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_hot_water_drop.mp4" darken={0} /> },
  { key: "b351_corn_s6_six_signs_montage", start: 1132.92, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_six_signs_montage.mp4" darken={0} /> },
  { key: "b352_corn_s6_husk_tight_wrap", start: 1134.68, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_husk_tight_wrap_1.jpg" darken={0} /> },
  { key: "b353_corn_s6_hands_off_husk", start: 1136.48, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_s6_hands_off_husk_1.png" darken={0} /> },
  { key: "b354_corn_s6_pull_husk_back", start: 1139, dur: 2.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_s6_pull_husk_back.mp4" darken={0} /> },
  { key: "b355_corn_rt_grill_husk", start: 1140.98, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rt_grill_husk.mp4" darken={0} /> },
  { key: "b356_corn_rt_oven_corn", start: 1143.22, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rt_oven_corn.mp4" darken={0} /> },
  { key: "b357_corn_rt_steam_husk", start: 1145.32, dur: 4.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rt_steam_husk_1.jpg" darken={0} /> },
  { key: "b358_corn_rt_family_table", start: 1149, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rt_family_table.mp4" darken={0} /> },
  { key: "b359_corn_rt_juicy_corn", start: 1153.66, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rt_juicy_corn.mp4" darken={0} /> },
  { key: "b360_corn_rt_grill_husk", start: 1156.24, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rt_grill_husk.mp4" darken={0} /> },
  { key: "b361_corn_rt_oven_corn", start: 1159.72, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rt_oven_corn.mp4" darken={0} /> },
  { key: "b362_corn_rt_steam_husk", start: 1162.06, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rt_steam_husk_1.jpg" darken={0} /> },
  { key: "cmp_grid", start: 1163.34, dur: 8.32, kind: "gridreveal", el: (d) => <GridReveal durationInFrames={d} tiles={[{"number":"1","name":"Las hojas"},{"number":"2","name":"Los pelos"},{"number":"3","name":"Palpá los granos"},{"number":"4","name":"El peso"},{"number":"5","name":"El corte del tallo"},{"number":"6","name":"No la peles"}]} title="6 señales · 10 segundos · sin pelar" subtitle="Como los viejos" /> },
  { key: "b366_corn_rc_weight_recap", start: 1171.66, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_weight_recap.mp4" darken={0} /> },
  { key: "b367_corn_rc_stem_recap", start: 1174.08, dur: 2.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_stem_recap_1.jpg" darken={0} /> },
  { key: "b368_corn_rc_no_peel_recap", start: 1175.74, dur: 1.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_no_peel_recap_1.jpg" darken={0} /> },
  { key: "b369_corn_rc_corn_bin_choose", start: 1177.08, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_corn_bin_choose.mp4" darken={0} /> },
  { key: "b370_corn_rc_sweet_corn_pile", start: 1179.22, dur: 2.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_sweet_corn_pile_1.jpg" darken={0} /> },
  { key: "b371_corn_rc_husk_green_recap", start: 1180.96, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_husk_green_recap.mp4" darken={0} /> },
  { key: "b372_corn_rc_silk_recap", start: 1183.12, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_silk_recap.mp4" darken={0} /> },
  { key: "b373_corn_rc_feel_tip_recap", start: 1185.22, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_feel_tip_recap_1.jpg" darken={0} /> },
  { key: "b374_corn_rc_weight_recap", start: 1187.52, dur: 2.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_weight_recap.mp4" darken={0} /> },
  { key: "b375_corn_rc_stem_recap", start: 1189.18, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_stem_recap_1.jpg" darken={0} /> },
  { key: "b376_corn_rc_no_peel_recap", start: 1191.12, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_no_peel_recap_1.jpg" darken={0} /> },
  { key: "b377_corn_rc_corn_bin_choose", start: 1193.78, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_corn_bin_choose.mp4" darken={0} /> },
  { key: "b378_corn_rc_sweet_corn_pile", start: 1196.1, dur: 1.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_sweet_corn_pile_1.jpg" darken={0} /> },
  { key: "b379_corn_rc_husk_green_recap", start: 1197.66, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_husk_green_recap.mp4" darken={0} /> },
  { key: "b380_corn_rc_silk_recap", start: 1200.06, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_silk_recap.mp4" darken={0} /> },
  { key: "b381_corn_rc_feel_tip_recap", start: 1202.8, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_feel_tip_recap_1.jpg" darken={0} /> },
  { key: "b382_corn_rc_weight_recap", start: 1204.86, dur: 2.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_weight_recap.mp4" darken={0} /> },
  { key: "b383_corn_rc_stem_recap", start: 1206.72, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_stem_recap_1.jpg" darken={0} /> },
  { key: "b384_corn_rc_no_peel_recap", start: 1209.62, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_no_peel_recap_1.jpg" darken={0} /> },
  { key: "b385_corn_rc_corn_bin_choose", start: 1211.78, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_corn_bin_choose.mp4" darken={0} /> },
  { key: "b386_corn_rc_sweet_corn_pile", start: 1213.8, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_sweet_corn_pile_1.jpg" darken={0} /> },
  { key: "b387_corn_rc_husk_green_recap", start: 1215.96, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_husk_green_recap.mp4" darken={0} /> },
  { key: "cmp_proc_bin", start: 1219.76, dur: 9.06, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Mirá: hojas verdes, pelos dorados"},{"title":"Palpá: lleno hasta la punta, pesada"},{"title":"Dala vuelta: corte pálido — y dejala sellada"}]} eyebrow="Diez segundos, sin pelar" title="Frente al maíz" accent="good" hue="amber" /> },
  { key: "b390_corn_rc_weight_recap", start: 1228.82, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_rc_weight_recap.mp4" darken={0} /> },
  { key: "b391_corn_rc_stem_recap", start: 1231.56, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_stem_recap_1.jpg" darken={0} /> },
  { key: "b392_corn_rc_no_peel_recap", start: 1233.32, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_no_peel_recap_1.jpg" darken={0} /> },
  { key: "b393_corn_rc_corn_bin_choose", start: 1236.08, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_hands_golden.png" darken={0} /> },
  { key: "b394_corn_rc_sweet_corn_pile", start: 1238.36, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_rc_sweet_corn_pile_1.jpg" darken={0} /> },
  { key: "b395_corn_em_amish_table", start: 1240.48, dur: 5.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_amish_table.mp4" darken={0} /> },
  { key: "b396_corn_em_grandfather_teach", start: 1245.6, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_grandfather_teach.mp4" darken={0} /> },
  { key: "b397_corn_em_hands_corn_warm", start: 1247.62, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_em_hands_corn_warm_1.jpg" darken={0} /> },
  { key: "cmp_quote_amish", start: 1250.32, dur: 8.34, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_amish_bg.png" words={parseQuote("Es no ser *derrochadores*, y no dejarse *engañar*.")} accent="amber" hue="amber" fontSize={80} /> },
  { key: "b401_corn_em_passing_down", start: 1258.66, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_passing_down.mp4" darken={0} /> },
  { key: "b402_corn_em_amish_table", start: 1261.88, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_amish_table.mp4" darken={0} /> },
  { key: "b403_corn_em_grandfather_teach", start: 1264.52, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_grandfather_teach.mp4" darken={0} /> },
  { key: "b404_corn_em_hands_corn_warm", start: 1269.02, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/corn_em_hands_corn_warm_1.jpg" darken={0} /> },
  { key: "b405_corn_em_amish_farm_evening", start: 1271.32, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_amish_farm_evening.mp4" darken={0} /> },
  { key: "b406_corn_em_full_table_food", start: 1273.84, dur: 4.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_full_table_food.mp4" darken={0} /> },
  { key: "b407_corn_em_corn_field_sunset", start: 1278.28, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_corn_field_sunset.mp4" darken={0} /> },
  { key: "b408_corn_em_passing_down", start: 1281.68, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_passing_down.mp4" darken={0} /> },
  { key: "b409_corn_em_amish_table", start: 1284.9, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_amish_table.mp4" darken={0} /> },
  { key: "b410_corn_em_grandfather_teach", start: 1289.04, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_grandfather_teach.mp4" darken={0} /> },
  { key: "b411_corn_em_hands_corn_warm", start: 1291.68, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/corn_gf_table_food.png" darken={0} /> },
  { key: "b412_corn_em_amish_farm_evening", start: 1295.62, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/corn_em_amish_farm_evening.mp4" darken={0} /> },
  { key: "cmp_free", start: 1297.66, dur: 7.4, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Gratis" eyebrow="Un saber heredado" caption="y ahora es tuyo" accent="good" hue="amber" /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "kl1", start: 18.52, dur: 2.72, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"sin","at":0},{"t":"pelar","at":0.2},{"t":"una","at":0.54},{"t":"sola","at":0.8},{"t":"hoja,","at":1.02,"hl":true}]} accent="amber" /> },
  { key: "kl2", start: 30.4, dur: 4.76, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"nunca","at":0,"hl":true},{"t":"más","at":0.4},{"t":"vas","at":0.96},{"t":"a","at":1.24},{"t":"llevarte","at":1.44},{"t":"a","at":1.74},{"t":"casa","at":1.92},{"t":"una","at":2.18},{"t":"mazorca","at":2.46},{"t":"mala","at":3.06}]} accent="amber" /> },
  { key: "cmp_blur_husk", start: 1089.28, dur: 3, kind: "blurreveal", el: (d) => <BlurReveal durationInFrames={d} title="Las hojas son su envase natural" eyebrow="Dejale las hojas" accent="good" /> },
];
