// cues_jabon.gen.tsx — GENERADO por beatsheet.mjs desde jabon.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/jabon.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { JourneyCanvas } from "./scenes/JourneyCanvas";
import { FloatingInsert } from "./scenes/FloatingInsert";
import { KineticHeadline } from "./scenes/KineticHeadline";
import { AgedDoc } from "./scenes/AgedDoc";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { AnnotatedImage } from "./scenes/AnnotatedImage";

const A = COLORS.accent, D = COLORS.danger, G = COLORS.good;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "intro_0", start: 0.1, dur: 9.58, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/jb_barra_mano.png" impact="Y NO VAS A CREER DE QUÉ ESTÁ HECHA" setup="Esta barra no la compré en ningún lado" impactAccent="danger" hitAt={1.3} /> },
  { key: "intro_1", start: 9.68, dur: 7.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_jabon_mano2.png" hue="amber" kicker="No la compré en ningún lado" /> },
  { key: "intro_2", start: 17.52, dur: 6.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_jabon_tabla.png" hue="amber" /> },
  { key: "intro_3", start: 24.06, dur: 4.79, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="img/jb_ceniza_fogon.png" side="right" kicker="Ceniza del fogón" hue="amber" /> },
  { key: "intro_4", start: 28.85, dur: 6.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_lard_fat.mp4" hue="amber" kicker="Grasa que iba a la basura" /> },
  { key: "intro_5", start: 35.38, dur: 1.1, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_lavar_manos.png" words={parseQuote("Más suave con su piel que los jabones de colores del *supermercado*.")} hue="amber" /> },
  { key: "intro_6", start: 36.48, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_soap_lather.mp4" hue="amber" /> },
  { key: "intro_7", start: 39.16, dur: 0.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_wash_laundry.mp4" hue="amber" /> },
  { key: "intro_8", start: 40.1, dur: 6.85, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_monedas.png" words={parseQuote("No es solo que sea barato. Es que *dura* años.")} hue="amber" /> },
  { key: "intro_9", start: 46.95, dur: 16.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_supermarket_soap.mp4" hue="amber" kicker="Mes a mes, toda la vida" /> },
  { key: "intro_10", start: 63.59, dur: 6.53, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Nunca"},{"t":"más"},{"t":"compres"},{"t":"jabón","hl":true}]} eyebrow="Lo que tu bisabuela sabía" hue="amber" bg="image" image="img/jb_pila_curado.png" /> },
  { key: "tomas_0", start: 70.12, dur: 7.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_casa_campo.mp4" hue="blue" kicker="Hace veinte años dejé la ciudad" /> },
  { key: "tomas_1", start: 77.14, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_old_kitchen.mp4" hue="blue" /> },
  { key: "tomas_2", start: 79.62, dur: 7.27, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_manos_viejas.png" words={parseQuote("La primera tanda me salió mal, se lo confieso. Y la segunda *también*.")} hue="blue" /> },
  { key: "tomas_3", start: 86.89, dur: 6.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_jabon_feo.png" hue="blue" /> },
  { key: "tomas_4", start: 93.12, dur: 8.31, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Lo que le voy a enseñar" lines={[{"text":"Sacar la lejía de la ceniza."},{"text":"Limpiar la grasa."},{"text":"Cocinar, cortar y curar el jabón."}]} image="img/jb_pasos_mesa.png" hue="blue" /> },
  { key: "tomas_5", start: 101.43, dur: 7.61, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="img/jb_barra_sol.png" side="left" kicker="Una cosa menos que comprar" hue="blue" /> },
  { key: "tomas_6", start: 109.04, dur: 6.93, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={20} suffix=" años" label="haciendo mi propio jabón" eyebrow="Sin comprar una barra" hue="blue" /> },
  { key: "tomas_7", start: 115.97, dur: 17.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_hombre_campo.mp4" hue="blue" /> },
  { key: "quees_0", start: 133.62, dur: 3.13, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"¿Qué"},{"t":"es"},{"t":"el"},{"t":"jabón","hl":true},{"t":"?"}]} eyebrow="Entendé esto y nunca le temés" hue="amber" bg="image" image="img/jb_barra_corte.png" /> },
  { key: "quees_1", start: 136.75, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_grasa_cuchara.png" hue="amber" kicker="Una grasa" /> },
  { key: "quees_2", start: 139.33, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_ceniza_mano.mp4" hue="amber" kicker="Un álcali" /> },
  { key: "quees_3", start: 141.91, dur: 6.24, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_olla_mezcla.png" words={parseQuote("Es lo que pasa cuando uno junta una grasa con un *álcali* fuerte.")} hue="amber" /> },
  { key: "quees_4", start: 148.15, dur: 21.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/dg_saponificacion.png" hue="amber" kicker="Saponificación" zoom={[1,1.05]} /> },
  { key: "quees_5", start: 169.36, dur: 6.54, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="El jabón sale de dos cosas" items={["Una grasa","Un álcali (lejía)"]} accent={A} /> },
  { key: "quees_6", start: 175.9, dur: 6.77, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_fuego_noche.png" words={parseQuote("No hay magia. Es química vieja, de hace cinco *mil* años.")} hue="amber" /> },
  { key: "quees_7", start: 182.67, dur: 6.44, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={5000} suffix=" años" label="limpiándose así" eyebrow="La humanidad" accent="amber" hue="amber" /> },
  { key: "dos_0", start: 189.11, dur: 15.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/dg_dos_mitades.png" hue="blue" kicker="Dos mitades que se unen" zoom={[1,1.05]} /> },
  { key: "dos_1", start: 204.84, dur: 7.9, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_fogon_brasas.png" words={parseQuote("El álcali salió de un solo lugar, gratis: del fondo del *fogón*.")} hue="blue" /> },
  { key: "dos_2", start: 212.74, dur: 19.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_fire_wood.mp4" hue="blue" /> },
  { key: "dos_3", start: 231.92, dur: 11.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_ash_bucket.mp4" hue="blue" kicker="La ceniza guarda el álcali" /> },
  { key: "dos_4", start: 243.2, dur: 7.53, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} bg="image" image="img/jb_roble_lena.png" title="La mejor ceniza" chips={["madera dura","roble, fresno","frutales"]} hue="amber" /> },
  { key: "dos_5", start: 250.73, dur: 8.27, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Ceniza que SÍ y que NO" items={["Madera limpia natural","Nunca pintada ni tratada","Nunca carbón con químicos"]} accent={D} cross /> },
  { key: "dos_6", start: 259, dur: 5.9, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_ceniza_fina.png" words={parseQuote("Madera limpia, ceniza limpia. Eso es *ley*.")} hue="blue" /> },
  { key: "lejia_0", start: 264.9, dur: 4.48, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Sacar"},{"t":"la"},{"t":"lejía","hl":true}]} eyebrow="El agua fuerte de los antiguos" hue="amber" bg="image" image="img/jb_barril_ceniza.png" /> },
  { key: "lejia_1", start: 269.38, dur: 4.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_balde_paja.png" hue="amber" kicker="Un balde o un barril" /> },
  { key: "lejia_2", start: 273.41, dur: 11.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/dg_lixiviado.png" hue="amber" kicker="Cómo gotea la lejía" zoom={[1,1.05]} /> },
  { key: "lejia_3", start: 284.84, dur: 11.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_pour_water.mp4" hue="amber" kicker="Agua de lluvia tibia" /> },
  { key: "lejia_4", start: 296.27, dur: 17.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_lye_leach.mp4" hue="amber" kicker="Sale oscura y resbalosa" /> },
  { key: "lejia_5", start: 313.4, dur: 6.73, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Paja en el fondo","image":"img/jb_paja_fondo.png"},{"title":"Ceniza encima","image":"img/jb_ceniza_encima.png"},{"title":"Echar agua","image":"img/jb_echar_agua.png"},{"title":"Gotea la lejía","image":"img/jb_gota_lejia.png"}]} title="Sacar la lejía" hue="amber" /> },
  { key: "lejia_6", start: 320.13, dur: 4.7, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_lejia_frasco.png" words={parseQuote("Ese líquido jabonoso entre los dedos, *es* la lejía.")} hue="amber" /> },
  { key: "prueba_0", start: 324.83, dur: 0.87, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"¿Está"},{"t":"en"},{"t":"su"},{"t":"punto","hl":true},{"t":"?"}]} eyebrow="Sin instrumentos, como los viejos" hue="blue" bg="image" image="img/jb_huevo_lejia.png" /> },
  { key: "prueba_1", start: 325.7, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_egg_float.mp4" hue="blue" kicker="La prueba del huevo" /> },
  { key: "prueba_2", start: 327.92, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/dg_huevo.png" hue="blue" kicker="Floja, en punto o fuerte" zoom={[1,1.05]} /> },
  { key: "prueba_3", start: 330.14, dur: 15.34, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_huevo_flota.png" words={parseQuote("El huevo flota y asoma un pedacito del tamaño de una *moneda*.")} hue="blue" /> },
  { key: "prueba_4", start: 345.48, dur: 21.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_feather.mp4" hue="blue" kicker="La pluma se empieza a deshacer" /> },
  { key: "prueba_5", start: 367.38, dur: 19.72, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/jb_guantes_lejia.png" annotations={[{"kind":"circle","x":30,"y":45,"label":"Guantes"},{"kind":"circle","x":66,"y":35,"label":"Proteja los ojos"},{"kind":"circle","x":50,"y":78,"label":"Lugar ventilado"}]} caption="La lejía quema: respeto, no pánico" hue="blue" /> },
  { key: "prueba_6", start: 387.1, dur: 17.18, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_cuchillo_filo.png" words={parseQuote("No le tenga pánico. Téngale *respeto*. Como al fuego.")} hue="blue" /> },
  { key: "prueba_7", start: 404.28, dur: 14.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_balde_tapado.png" hue="blue" /> },
  { key: "injerto1_0", start: 419, dur: 7.98, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Uno de 35 sistemas" lines={[{"text":"Las proporciones exactas, las pasadas de ceniza,"},{"text":"cómo concentrar una lejía floja…"},{"text":"todo medido y probado en mi cocina."}]} image="img/jb_cuaderno.png" hue="amber" /> },
  { key: "injerto1_1", start: 426.98, dur: 7.32, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="img/jb_manual_jabon.png" side="right" kicker="Todo junto en el manual" hue="amber" /> },
  { key: "injerto1_2", start: 434.3, dur: 6.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_estante_frascos.png" hue="amber" /> },
  { key: "injerto1_3", start: 441.28, dur: 13.72, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_olla_humea.png" words={parseQuote("Ahora viene la grasa, y no le voy a esconder ni un solo *paso*.")} hue="amber" /> },
  { key: "grasa_0", start: 455, dur: 8.25, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"La"},{"t":"otra"},{"t":"mitad"},{"t":":"},{"t":"grasa","hl":true}]} eyebrow="Lo que también se tira" hue="red" bg="image" image="img/jb_sebo_bowl.png" /> },
  { key: "grasa_1", start: 463.25, dur: 7.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_fat_trim.mp4" hue="red" kicker="Grasa que le saca a la carne" /> },
  { key: "grasa_2", start: 470.67, dur: 21.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_manteca_cerdo.png" hue="red" /> },
  { key: "grasa_3", start: 491.7, dur: 8.24, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} bg="image" image="img/jb_grasas_varias.png" title="Cualquier grasa sirve" chips={["sebo de vaca","manteca de cerdo","o aceite vegetal"]} hue="red" /> },
  { key: "grasa_4", start: 499.94, dur: 21.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_melt_fat.mp4" hue="red" kicker="Se derrite en agua" /> },
  { key: "grasa_5", start: 520.97, dur: 12.37, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Grasa + agua al fuego","image":"img/jb_grasa_agua.png"},{"title":"Enfriar toda la noche","image":"img/jb_olla_reposa.png"},{"title":"Sube y se solidifica","image":"img/jb_capa_grasa.png"},{"title":"Raspar lo sucio","image":"img/jb_raspar_grasa.png"}]} title="Limpiar la grasa" hue="red" /> },
  { key: "grasa_6", start: 533.34, dur: 8.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_grasa_limpia.png" hue="red" /> },
  { key: "grasa_7", start: 542, dur: 3, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_grasa_brillo.png" words={parseQuote("La grasa más limpia da el jabón más blanco y más *suave*.")} hue="red" /> },
  { key: "coccion_0", start: 545, dur: 3.38, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_olla_revolver.png" words={parseQuote("Esta es la parte donde se hace el jabón de *verdad*.")} hue="amber" /> },
  { key: "coccion_1", start: 548.38, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_melt_fat.mp4" hue="amber" kicker="Grasa tibia, no hirviendo" /> },
  { key: "coccion_2", start: 551.28, dur: 11.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_verter_lejia.mp4" hue="amber" kicker="La lejía de a poco, revolviendo" /> },
  { key: "coccion_3", start: 562.79, dur: 8.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/dg_proceso.png" hue="amber" kicker="Los cuatro pasos" zoom={[1,1.05]} /> },
  { key: "coccion_4", start: 571, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_mezcla_espesa.mp4" hue="amber" kicker="Se pone cremosa, espesa" /> },
  { key: "coccion_5", start: 575.84, dur: 4.35, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/jb_rastro_cuchara.png" annotations={[{"kind":"circle","x":50,"y":45,"label":"La gota deja una marca"},{"kind":"circle","x":50,"y":78,"label":"= llegó al punto"}]} caption="La prueba del rastro" hue="amber" /> },
  { key: "coccion_6", start: 580.19, dur: 4.03, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Si quiere, al final" items={[{"text":"Un puñado de sal: más dura","state":"done"},{"text":"Aromas: lavanda, romero","state":"done"},{"text":"Avena: más suave","state":"done"}]} hue="amber" /> },
  { key: "coccion_7", start: 584.22, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_salt_add.mp4" hue="amber" /> },
  { key: "coccion_8", start: 586.63, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_lavender.mp4" hue="amber" /> },
  { key: "coccion_9", start: 589.05, dur: 54.05, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_brazo_revuelve.png" words={parseQuote("El mismo movimiento del brazo que hicieron millones de manos antes que la *suya*.")} hue="amber" /> },
  { key: "curar_0", start: 643.1, dur: 23.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_soap_pour.mp4" hue="blue" kicker="Verter en moldes" /> },
  { key: "curar_1", start: 666.13, dur: 13.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_soap_cut.mp4" hue="blue" kicker="Cortar en barras" /> },
  { key: "curar_2", start: 679.68, dur: 8.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_barras_frescas.mp4" hue="blue" /> },
  { key: "curar_3", start: 687.81, dur: 11.29, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Mínimo","value":4},{"label":"Ideal","value":8}]} title="Tiempo de curado" unit="semanas" hue="blue" /> },
  { key: "curar_4", start: 699.1, dur: 4.93, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_curado_estante.png" words={parseQuote("El jabón curado, viejo, es el *mejor* jabón.")} hue="blue" /> },
  { key: "curar_5", start: 704.03, dur: 7.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_soap_cure.mp4" hue="blue" kicker="Secar al aire, separadas" /> },
  { key: "curar_6", start: 711.07, dur: 4.93, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_jabon_viejo.png" words={parseQuote("La prisa es la enemiga del *buen* jabón.")} hue="blue" /> },
  { key: "injerto2_0", start: 716, dur: 4.96, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"¿Por"},{"t":"qué"},{"t":"nadie"},{"t":"te"},{"t":"lo"},{"t":"enseñó","hl":true},{"t":"?"}]} eyebrow="La parte incómoda" hue="red" bg="image" image="img/jb_gondola2.png" /> },
  { key: "injerto2_1", start: 720.96, dur: 12.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_jabon_marca.png" hue="red" kicker="Un producto con marca y publicidad" /> },
  { key: "injerto2_2", start: 733.6, dur: 5.2, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_caja_registr.png" words={parseQuote("Con algo gratis que sale de la ceniza, nadie gana *dinero*.")} hue="red" /> },
  { key: "injerto2_3", start: 738.8, dur: 6.2, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Jabón casero","value":1},{"label":"Toda una vida comprando","value":12}]} title="Lo que entrega gota a gota" hue="red" /> },
  { key: "injerto2_4", start: 745, dur: 11.78, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_abuela_ensena.png" words={parseQuote("Alcanza con que deje de enseñarse una sola *generación*.")} hue="red" /> },
  { key: "injerto2_5", start: 756.78, dur: 10.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_manos_jabon_viejo.png" hue="red" /> },
  { key: "injerto2_6", start: 766.88, dur: 13.46, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Por eso junté todo" lines={[{"text":"Treinta y cinco sistemas, ordenados y probados."},{"text":"Para devolverle el saber que le sacaron."}]} image="img/jb_cuaderno2.png" hue="red" /> },
  { key: "preguntas_0", start: 780.34, dur: 18.77, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="¿Y si es peligroso por la lejía?" items={["Empiece por el jabón","Después saque su lejía","Vaya a su ritmo"]} accent={G} /> },
  { key: "preguntas_1", start: 799.11, dur: 15.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_principiante.png" hue="amber" /> },
  { key: "preguntas_2", start: 814.46, dur: 11.58, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_tanda_fallida.png" words={parseQuote("Le va a salir mal alguna vez, y no pasa nada. Cada error le *enseña*.")} hue="amber" /> },
  { key: "preguntas_3", start: 826.04, dur: 9.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_jabon_usos.mp4" hue="amber" /> },
  { key: "preguntas_4", start: 835.97, dur: 11.03, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} bg="image" image="img/jb_jabon_rallado.png" title="Una sola receta sirve para" chips={["manos y cuerpo","lavar la ropa","los platos","la casa"]} hue="blue" /> },
  { key: "preguntas_5", start: 847, dur: 1.87, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_lavar_platos.png" words={parseQuote("Una sola receta le resuelve la limpieza entera de su *hogar*.")} hue="amber" /> },
  { key: "preguntas_6", start: 848.87, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_wash_dishes.mp4" hue="amber" /> },
  { key: "preguntas_7", start: 850.47, dur: 4.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_ropa_tendida.mp4" hue="amber" /> },
  { key: "panorama_0", start: 855, dur: 9, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_pan_casero.png" words={parseQuote("El jabón, el pan, conservar la comida… dejamos de *enseñarlas*.")} hue="blue" /> },
  { key: "panorama_1", start: 864, dur: 21.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_mujer_amasa.mp4" hue="blue" /> },
  { key: "panorama_2", start: 885.86, dur: 9.43, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="No tenés que hacer todo" items={["Tené la opción","Sepé hacerlo","No dependas de nadie"]} accent={A} /> },
  { key: "panorama_3", start: 895.29, dur: 7.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_despensa_llena.mp4" hue="blue" /> },
  { key: "panorama_4", start: 903, dur: 1.32, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_hombre_ventana.png" words={parseQuote("Esa tranquilidad de saber que podría hacerlo… no la compra el *dinero*.")} hue="blue" /> },
  { key: "panorama_5", start: 904.32, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_campo_atardecer.mp4" hue="blue" /> },
  { key: "accion_0", start: 907.53, dur: 10.27, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Este fin de semana" items={[{"text":"Junte grasa de cocinar","state":"done"},{"text":"Guarde ceniza de madera limpia","state":"done"},{"text":"Guantes y algo para los ojos","state":"done"},{"text":"Una tanda chica, sin apuro","state":"done"}]} hue="amber" /> },
  { key: "accion_1", start: 917.8, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_frasco_grasa.png" hue="amber" /> },
  { key: "accion_2", start: 923.96, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_ash_bucket.mp4" hue="amber" /> },
  { key: "accion_3", start: 930.12, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/jb_guantes_mesa.png" hue="amber" /> },
  { key: "accion_4", start: 936.28, dur: 19.72, kind: "journey", el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="Su primera barra" title="Paso a paso, sin miedo" waypoints={[{"x":0,"y":0,"z":0,"image":"img/jb_jrn_ceniza.png","label":"Ceniza","num":"1","dwell":2.4,"travel":1.5},{"x":1.2,"y":-0.3,"z":0.3,"image":"img/jb_jrn_lejia.png","label":"Lejía","num":"2","dwell":2.4,"travel":1.5},{"x":2.4,"y":0.2,"z":-0.2,"image":"img/jb_jrn_cocina.png","label":"Cocinar","num":"3","dwell":2.4,"travel":1.5},{"x":3.6,"y":-0.2,"z":0.2,"image":"img/jb_jrn_curar.png","label":"Curar","num":"4","dwell":2.6,"travel":1.4}]} /> },
  { key: "accion_5", start: 956, dur: 2, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_primera_barra.png" words={parseQuote("Es una sensación que no se *compra*.")} hue="amber" /> },
  { key: "injerto3_0", start: 958, dur: 8.64, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Todo en el manual" lines={[{"text":"Proporciones, tiempos de curado,"},{"text":"jabón de ropa y jabón de bebé,"},{"text":"y cómo arreglar una tanda que salió mal."}]} image="img/jb_manual_abierto.png" hue="red" /> },
  { key: "injerto3_1", start: 966.64, dur: 18.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_soap_stack.mp4" hue="red" /> },
  { key: "injerto3_2", start: 985, dur: 9, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Por separado","value":158},{"label":"Hoy","value":27}]} title="El precio de hoy" hue="red" /> },
  { key: "injerto3_3", start: 994, dur: 9.65, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_jabon_regalo.png" words={parseQuote("Si no es para usted, le devuelvo cada centavo. Todo el riesgo lo pongo *yo*.")} hue="red" /> },
  { key: "injerto3_4", start: 1003.65, dur: 10.1, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="img/jb_pocas_copias.png" side="left" kicker="Quedan pocas copias" hue="red" /> },
  { key: "cierre_0", start: 1013.75, dur: 9.98, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_abuela_jabon.png" words={parseQuote("Cuénteme si su abuela lo hacía. Esas historias me *encantan*.")} hue="blue" /> },
  { key: "cierre_1", start: 1023.73, dur: 8.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_manos_arrugadas.mp4" hue="blue" /> },
  { key: "cierre_2", start: 1032.28, dur: 9.5, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"No"},{"t":"tire"},{"t":"más"},{"t":"la"},{"t":"ceniza","hl":true}]} eyebrow="La próxima vez" hue="blue" bg="image" image="img/jb_ceniza_tacho.png" /> },
  { key: "cierre_3", start: 1041.78, dur: 24.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jb_rain_barrel.mp4" hue="blue" kicker="Fertilizante, limpieza, plagas" /> },
  { key: "cierre_4", start: 1066, dur: 0.84, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/jb_oficio_manos.png" words={parseQuote("No es magia. Es *oficio*. Y todavía se puede aprender.")} hue="blue" /> },
  { key: "cierre_5", start: 1066.84, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/jb_barra_final.mp4" hue="blue" /> },
];

export const REFRAME: { start: number; end: number }[] = [];
