// cues_replantar.gen.tsx — GENERADO por beatsheet.mjs desde replantar.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/replantar.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { MistakeCard } from "./scenes/MistakeCard";
import { RegrowSplit } from "./scenes/RegrowSplit";
import { LieList } from "./scenes/LieList";
import { NumberCard } from "./scenes/NumberCard";
import { GridReveal } from "./scenes/GridReveal";
import { GrowthTimeline } from "./scenes/GrowthTimeline";
import { KineticLine } from "./scenes/KineticLine";

const D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "b1_rpl_h1_green_onion_roots_macro", start: 2.04, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "b2_rpl_h1_pineapple_crown_top", start: 2.99, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "b3_rpl_h1_roots_growing_water_macro", start: 3.94, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_roots_growing_water_macro.mp4" darken={0} /> },
  { key: "b4_rpl_h1_sprout_timelapse_soil", start: 4.89, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_sprout_timelapse_soil.mp4" darken={0} /> },
  { key: "b5_rpl_h1_hands_planting_soil", start: 5.84, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "b6_rpl_h1_kitchen_scraps_board", start: 6.79, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_kitchen_scraps_board.mp4" darken={0} /> },
  { key: "b7_rpl_h1_harvest_hands_tomatoes", start: 7.74, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_harvest_hands_tomatoes.mp4" darken={0} /> },
  { key: "b8_rpl_h1_fresh_veg_spread_table", start: 8.69, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "b9_rpl_h1_green_onion_roots_macro", start: 9.64, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "b10_rpl_h1_pineapple_crown_top", start: 10.59, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "b11_rpl_h1_roots_growing_water_macro", start: 11.54, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_roots_growing_water_macro.mp4" darken={0} /> },
  { key: "b12_rpl_h1_sprout_timelapse_soil", start: 12.49, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_sprout_timelapse_soil.mp4" darken={0} /> },
  { key: "b13_rpl_h1_hands_planting_soil", start: 13.44, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "b14_rpl_h1_kitchen_scraps_board", start: 14.39, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_kitchen_scraps_board.mp4" darken={0} /> },
  { key: "b15_rpl_h1_harvest_hands_tomatoes", start: 15.34, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_harvest_hands_tomatoes.mp4" darken={0} /> },
  { key: "b16_rpl_h1_fresh_veg_spread_table", start: 16.29, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "b17_rpl_h1_green_onion_roots_macro", start: 17.24, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "b18_rpl_h1_pineapple_crown_top", start: 18.19, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "b19_rpl_h1_roots_growing_water_macro", start: 19.14, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_roots_growing_water_macro.mp4" darken={0} /> },
  { key: "b20_rpl_h1_sprout_timelapse_soil", start: 20.09, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_sprout_timelapse_soil.mp4" darken={0} /> },
  { key: "b21_rpl_h1_hands_planting_soil", start: 21.04, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "cmp_alive", start: 21.99, dur: 6.65, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_alive_bg.png" impact="sigue VIVA." setup="Eso que llamas basura..." impactAccent="good" hitAt={1.2} boom={0} darken={0.4} /> },
  { key: "b29_rpl_h1_hands_planting_soil", start: 28.64, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "b30_rpl_h1_kitchen_scraps_board", start: 29.59, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_kitchen_scraps_board.mp4" darken={0} /> },
  { key: "b31_rpl_h1_harvest_hands_tomatoes", start: 30.54, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_harvest_hands_tomatoes.mp4" darken={0} /> },
  { key: "b32_rpl_h1_fresh_veg_spread_table", start: 31.49, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "cmp_business", start: 32.44, dur: 6.65, kind: "lielist", el: (d) => <LieList durationInFrames={d} title="Por qué te lo vende suelto" items={["Para que vuelvas cada semana","Lo usás una vez y lo tirás","El negocio es la dependencia"]} image="img/cmp_business_bg.png" accent="danger" /> },
  { key: "b40_rpl_h1_fresh_veg_spread_table", start: 39.09, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "b41_rpl_h1_green_onion_roots_macro", start: 40.04, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "b42_rpl_h1_pineapple_crown_top", start: 40.99, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "b43_rpl_h1_roots_growing_water_macro", start: 41.94, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_roots_growing_water_macro.mp4" darken={0} /> },
  { key: "b44_rpl_h1_sprout_timelapse_soil", start: 42.89, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_sprout_timelapse_soil.mp4" darken={0} /> },
  { key: "b45_rpl_h1_hands_planting_soil", start: 43.84, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "b46_rpl_h1_kitchen_scraps_board", start: 44.79, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_kitchen_scraps_board.mp4" darken={0} /> },
  { key: "b47_rpl_h1_harvest_hands_tomatoes", start: 45.74, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_harvest_hands_tomatoes.mp4" darken={0} /> },
  { key: "b48_rpl_h1_fresh_veg_spread_table", start: 46.69, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "b49_rpl_h1_green_onion_roots_macro", start: 47.64, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "b50_rpl_h1_pineapple_crown_top", start: 48.59, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "cmp_tally", start: 49.54, dur: 6.65, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={16} suffix=" plantas · 0€" label="comida nueva, gratis, desde tu basura" eyebrow="Lo que vas a sacar hoy" accent="good" hue="amber" /> },
  { key: "b58_rpl_h1_pineapple_crown_top", start: 56.19, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "b59_rpl_h1_roots_growing_water_macro", start: 57.14, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_roots_growing_water_macro.mp4" darken={0} /> },
  { key: "b60_rpl_h1_sprout_timelapse_soil", start: 58.09, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_sprout_timelapse_soil.mp4" darken={0} /> },
  { key: "b61_rpl_h1_hands_planting_soil", start: 59.04, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "b62_rpl_h1_kitchen_scraps_board", start: 59.99, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_kitchen_scraps_board.mp4" darken={0} /> },
  { key: "b63_rpl_h1_harvest_hands_tomatoes", start: 60.94, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_harvest_hands_tomatoes.mp4" darken={0} /> },
  { key: "b64_rpl_h1_fresh_veg_spread_table", start: 61.89, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "b65_rpl_h1_green_onion_roots_macro", start: 62.84, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "b66_rpl_h1_pineapple_crown_top", start: 63.79, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "b67_rpl_h1_roots_growing_water_macro", start: 64.74, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_roots_growing_water_macro.mp4" darken={0} /> },
  { key: "b68_rpl_h1_sprout_timelapse_soil", start: 65.69, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_sprout_timelapse_soil.mp4" darken={0} /> },
  { key: "b69_rpl_h1_hands_planting_soil", start: 66.64, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "b70_rpl_h1_kitchen_scraps_board", start: 67.59, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_kitchen_scraps_board.mp4" darken={0} /> },
  { key: "b71_rpl_h1_harvest_hands_tomatoes", start: 68.54, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_harvest_hands_tomatoes.mp4" darken={0} /> },
  { key: "b72_rpl_h1_fresh_veg_spread_table", start: 69.49, dur: 1.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "b73_rpl_h1_green_onion_roots_macro", start: 70.44, dur: 1.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "b74_rpl_h2_wilting_plant_cloudy", start: 71.41, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b75_rpl_h2_pepper_seedlings", start: 73.02, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "b76_rpl_h2_seedling_emerging", start: 74.62, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b77_rpl_h2_pepper_plant_fruit", start: 76.22, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "cmp_teaser11", start: 77.83, dur: 6.41, kind: "regrow", el: (d) => <RegrowSplit durationInFrames={d} leftImage="img/cmp_teaser11_l.png" rightImage="img/cmp_teaser11_r.png" number="11" title="Una sola te da una bolsa de comida" leftLabel="Basura" rightLabel="Cosecha" hue="amber" /> },
  { key: "b82_rpl_h2_wilting_plant_cloudy", start: 84.24, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b83_rpl_h2_pepper_seedlings", start: 85.84, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "b84_rpl_h2_seedling_emerging", start: 87.44, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b85_rpl_h2_pepper_plant_fruit", start: 89.05, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b86_rpl_h2_wilting_plant_cloudy", start: 90.65, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b87_rpl_h2_pepper_seedlings", start: 92.25, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "cmp_loop_error", start: 93.85, dur: 6.41, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="!" title="El error que mata la mitad de tus plantas" desc="Casi todos lo cometen, y creen que no funcionó." eyebrow="EN ESTE VIDEO" image="img/cmp_loop_error_bg.png" /> },
  { key: "b92_rpl_h2_seedling_emerging", start: 100.26, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b93_rpl_h2_pepper_plant_fruit", start: 101.87, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b94_rpl_h2_wilting_plant_cloudy", start: 103.47, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b95_rpl_h2_pepper_seedlings", start: 105.07, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "b96_rpl_h2_seedling_emerging", start: 106.68, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b97_rpl_h2_pepper_plant_fruit", start: 108.28, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b98_rpl_h2_wilting_plant_cloudy", start: 109.88, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b99_rpl_h2_pepper_seedlings", start: 111.48, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "b100_rpl_h2_seedling_emerging", start: 113.09, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b101_rpl_h2_pepper_plant_fruit", start: 114.69, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b102_rpl_h2_wilting_plant_cloudy", start: 116.29, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b103_rpl_h2_pepper_seedlings", start: 117.9, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "b104_rpl_h2_seedling_emerging", start: 119.5, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b105_rpl_h2_pepper_plant_fruit", start: 121.1, dur: 1.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b106_rpl_tr_greenhouse_interior", start: 154.62, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_greenhouse_interior.mp4" darken={0} /> },
  { key: "b107_rpl_tr_sun_kitchen_window", start: 157.67, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_sun_kitchen_window.mp4" darken={0} /> },
  { key: "cmp_savings_bars", start: 160.73, dur: 3.05, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Comprándolas todo el año","value":160,"display":"~160€","tone":"danger"},{"label":"Replantando los restos","value":0,"display":"0€","winner":true}]} eyebrow="Lo que se va al año" title="Hierbas y verduras de hoja" unit="EUR" accent="good" hue="amber" /> },
  { key: "cmp_growth", start: 163.78, dur: 9.16, kind: "growthtimeline", el: (d) => <GrowthTimeline durationInFrames={d} stages={[{"label":"Un resto"},{"label":"En agua","sub":"días"},{"label":"Raíces"},{"label":"A la tierra"},{"label":"Cosecha"}]} title="De un resto a una planta" bg="broll/rpl_err_pale_wilting_cutting.mp4" /> },
  { key: "b112_rpl_tr_sun_kitchen_window", start: 172.94, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_sun_kitchen_window.mp4" darken={0} /> },
  { key: "b113_rpl_tr_scraps_lined_up", start: 175.99, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_scraps_lined_up.mp4" darken={0} /> },
  { key: "b114_rpl_tr_roots_timelapse", start: 179.04, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_roots_timelapse.mp4" darken={0} /> },
  { key: "cmp_nonecesitas", start: 182.1, dur: 6.1, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="No necesitas nada de esto" items={["Semillas caras","Luces de cultivo","Invernadero"]} accent={D} cross /> },
  { key: "b117_rpl_tr_sun_kitchen_window", start: 188.2, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_sun_kitchen_window.mp4" darken={0} /> },
  { key: "cmp_solo", start: 191.25, dur: 6.11, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Solo necesitas" items={[{"text":"Un vaso de agua","state":"done"},{"text":"Un puñado de tierra","state":"done"},{"text":"Una ventana con luz","state":"done"}]} eyebrow="En tu cocina" accent="good" hue="amber" image="img/cmp_solo_bg.png" /> },
  { key: "b120_rpl_tr_money_saved_jar", start: 197.36, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_money_saved_jar.mp4" darken={0} /> },
  { key: "b121_rpl_tr_greenhouse_interior", start: 200.41, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_greenhouse_interior.mp4" darken={0} /> },
  { key: "b122_rpl_tr_sun_kitchen_window", start: 203.46, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_sun_kitchen_window.mp4" darken={0} /> },
  { key: "cmp_num_1", start: 206.52, dur: 3.05, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="1" name="Cebolla de verdeo" bg="broll/rpl_i1_scallion_root_ends.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_cebolla", start: 209.57, dur: 6.38, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_cebolla_bg.png" annotations={[{"kind":"circle","x":0.5,"y":0.78,"w":0.18,"label":"Raíces al agua","color":"good"},{"kind":"arrow","x":0.5,"y":0.32,"fromX":0.78,"fromY":0.12,"label":"Dejá 3 dedos de tallo","color":"amber"},{"kind":"circle","x":0.5,"y":0.9,"w":0.4,"label":"1 dedo de agua","color":"accent"}]} eyebrow="Cómo se hace" hue="amber" /> },
  { key: "b126_rpl_i1_scallion_regrow_timelapse", start: 215.95, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "b127_rpl_i1_snipping_scissors", start: 219.26, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_snipping_scissors.mp4" darken={0} /> },
  { key: "b128_rpl_i1_chopped_over_food", start: 222.58, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_chopped_over_food.mp4" darken={0} /> },
  { key: "b129_rpl_i1_slicing_scallions_macro", start: 225.9, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_slicing_scallions_macro.mp4" darken={0} /> },
  { key: "b130_rpl_i1_scallion_root_ends", start: 229.21, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_root_ends.mp4" darken={0} /> },
  { key: "b131_rpl_i1_scallion_regrow_timelapse", start: 232.53, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "b132_rpl_i1_snipping_scissors", start: 235.84, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_snipping_scissors.mp4" darken={0} /> },
  { key: "b133_rpl_i1_chopped_over_food", start: 239.16, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_chopped_over_food.mp4" darken={0} /> },
  { key: "b134_rpl_i1_slicing_scallions_macro", start: 242.47, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_slicing_scallions_macro.mp4" darken={0} /> },
  { key: "b135_rpl_i1_scallion_root_ends", start: 245.79, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_root_ends.mp4" darken={0} /> },
  { key: "b136_rpl_i1_scallion_regrow_timelapse", start: 249.11, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "b137_rpl_i1_snipping_scissors", start: 252.42, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_snipping_scissors.mp4" darken={0} /> },
  { key: "b138_rpl_i1_chopped_over_food", start: 255.74, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_chopped_over_food.mp4" darken={0} /> },
  { key: "b139_rpl_i1_slicing_scallions_macro", start: 259.05, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_slicing_scallions_macro.mp4" darken={0} /> },
  { key: "b140_rpl_i1_scallion_root_ends", start: 262.37, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_root_ends.mp4" darken={0} /> },
  { key: "b141_rpl_i1_scallion_regrow_timelapse", start: 265.69, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "b142_rpl_i1_snipping_scissors", start: 269, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_snipping_scissors.mp4" darken={0} /> },
  { key: "cmp_num_2", start: 272.32, dur: 3.32, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="2" name="Lechuga" bg="broll/rpl_i2_lettuce_dish_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b144_rpl_i2_lettuce_dish_water", start: 275.64, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b145_rpl_i2_lettuce_water_window", start: 279.01, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "b146_rpl_i2_harvest_lettuce_hand", start: 282.39, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_harvest_lettuce_hand.mp4" darken={0} /> },
  { key: "b147_rpl_i2_chopping_lettuce_board", start: 285.76, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b148_rpl_i2_lettuce_dish_water", start: 289.14, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b149_rpl_i2_lettuce_water_window", start: 292.51, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "b150_rpl_i2_harvest_lettuce_hand", start: 295.89, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_harvest_lettuce_hand.mp4" darken={0} /> },
  { key: "b151_rpl_i2_chopping_lettuce_board", start: 299.27, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b152_rpl_i2_lettuce_dish_water", start: 302.64, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b153_rpl_i2_lettuce_water_window", start: 306.02, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "b154_rpl_i2_harvest_lettuce_hand", start: 309.39, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_harvest_lettuce_hand.mp4" darken={0} /> },
  { key: "b155_rpl_i2_chopping_lettuce_board", start: 312.77, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b156_rpl_i2_lettuce_dish_water", start: 316.14, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b157_rpl_i2_lettuce_water_window", start: 319.52, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "b158_rpl_i2_harvest_lettuce_hand", start: 322.9, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_harvest_lettuce_hand.mp4" darken={0} /> },
  { key: "b159_rpl_i2_chopping_lettuce_board", start: 326.27, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b160_rpl_i2_lettuce_dish_water", start: 329.65, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b161_rpl_i2_lettuce_water_window", start: 333.02, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "cmp_num_3", start: 336.4, dur: 3.37, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="3" name="Apio" bg="broll/rpl_i3_celery_base_glass.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b163_rpl_i3_celery_base_glass", start: 339.77, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "b164_rpl_i3_celery_regrow_timelapse", start: 342.98, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_regrow_timelapse.mp4" darken={0} /> },
  { key: "b165_rpl_i3_celery_water_window", start: 346.2, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_water_window.mp4" darken={0} /> },
  { key: "b166_rpl_i3_celery_base_glass", start: 349.41, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "b167_rpl_i3_celery_regrow_timelapse", start: 352.63, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_regrow_timelapse.mp4" darken={0} /> },
  { key: "b168_rpl_i3_celery_water_window", start: 355.84, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_water_window.mp4" darken={0} /> },
  { key: "b169_rpl_i3_celery_base_glass", start: 359.05, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "b170_rpl_i3_celery_regrow_timelapse", start: 362.27, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_regrow_timelapse.mp4" darken={0} /> },
  { key: "b171_rpl_i3_celery_water_window", start: 365.48, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_water_window.mp4" darken={0} /> },
  { key: "b172_rpl_i3_celery_base_glass", start: 368.7, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "b173_rpl_i3_celery_regrow_timelapse", start: 371.91, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_regrow_timelapse.mp4" darken={0} /> },
  { key: "b174_rpl_i3_celery_water_window", start: 375.13, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_water_window.mp4" darken={0} /> },
  { key: "b175_rpl_i3_celery_base_glass", start: 378.34, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "cmp_num_4", start: 381.55, dur: 3.21, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="4" name="Bok choy" bg="broll/rpl_i4_bokchoy_base_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b177_rpl_i4_bokchoy_base_water", start: 384.76, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_base_water.mp4" darken={0} /> },
  { key: "b178_rpl_i4_asian_leafy_greens", start: 387.75, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_asian_leafy_greens.mp4" darken={0} /> },
  { key: "b179_rpl_i4_bokchoy_window_jar", start: 390.73, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_window_jar.mp4" darken={0} /> },
  { key: "b180_rpl_i4_bokchoy_base_water", start: 393.72, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_base_water.mp4" darken={0} /> },
  { key: "b181_rpl_i4_asian_leafy_greens", start: 396.7, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_asian_leafy_greens.mp4" darken={0} /> },
  { key: "b182_rpl_i4_bokchoy_window_jar", start: 399.69, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_window_jar.mp4" darken={0} /> },
  { key: "b183_rpl_i4_bokchoy_base_water", start: 402.68, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_base_water.mp4" darken={0} /> },
  { key: "b184_rpl_i4_asian_leafy_greens", start: 405.66, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_asian_leafy_greens.mp4" darken={0} /> },
  { key: "b185_rpl_i4_bokchoy_window_jar", start: 408.65, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_window_jar.mp4" darken={0} /> },
  { key: "cmp_num_5", start: 411.63, dur: 3.01, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="5" name="Puerro" bg="broll/rpl_i5_leek_regrow_upward.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b187_rpl_i5_leek_regrow_upward", start: 414.64, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leek_regrow_upward.mp4" darken={0} /> },
  { key: "b188_rpl_i5_leeks_rustic_kitchen", start: 418.11, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leeks_rustic_kitchen.mp4" darken={0} /> },
  { key: "b189_rpl_i5_leek_root_macro", start: 421.59, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leek_root_macro.mp4" darken={0} /> },
  { key: "b190_rpl_i5_chopping_leek_macro", start: 425.06, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_chopping_leek_macro.mp4" darken={0} /> },
  { key: "b191_rpl_i5_leek_soup_pot", start: 428.53, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leek_soup_pot.mp4" darken={0} /> },
  { key: "b192_rpl_i5_washing_leek_water", start: 432.01, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_washing_leek_water.mp4" darken={0} /> },
  { key: "b193_rpl_i5_leek_regrow_upward", start: 435.48, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leek_regrow_upward.mp4" darken={0} /> },
  { key: "b194_rpl_i5_leeks_rustic_kitchen", start: 438.95, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leeks_rustic_kitchen.mp4" darken={0} /> },
  { key: "b195_rpl_i5_leek_root_macro", start: 442.43, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leek_root_macro.mp4" darken={0} /> },
  { key: "cmp_herbs", start: 445.9, dur: 6.95, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} image="img/cmp_herbs_bg.png" title="Las hierbas: donde más ahorrás" chips={["Albahaca","Menta","Cilantro"]} hue="amber" /> },
  { key: "cmp_num_6", start: 452.85, dur: 3.47, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="6" name="Albahaca" bg="broll/rpl_i6_basil_cuttings_glass.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_basil_bars", start: 456.32, dur: 6.94, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Comprada cada semana","value":60,"display":"60€/año","tone":"danger"},{"label":"De 1 manojo replantado","value":0,"display":"0€","winner":true}]} eyebrow="Comprarla vs replantarla" title="Albahaca fresca" unit="EUR" accent="good" hue="amber" /> },
  { key: "b201_rpl_i6_basil_cuttings_glass", start: 463.26, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_cuttings_glass.mp4" darken={0} /> },
  { key: "b202_rpl_i6_basil_windowsill_plants", start: 466.52, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_windowsill_plants.mp4" darken={0} /> },
  { key: "b203_rpl_i6_picking_basil_hand", start: 469.78, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_picking_basil_hand.mp4" darken={0} /> },
  { key: "b204_rpl_i6_basil_timelapse_root", start: 473.04, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_timelapse_root.mp4" darken={0} /> },
  { key: "b205_rpl_i6_basil_cuttings_glass", start: 476.3, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_cuttings_glass.mp4" darken={0} /> },
  { key: "b206_rpl_i6_basil_windowsill_plants", start: 479.56, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_windowsill_plants.mp4" darken={0} /> },
  { key: "b207_rpl_i6_picking_basil_hand", start: 482.82, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_picking_basil_hand.mp4" darken={0} /> },
  { key: "b208_rpl_i6_basil_timelapse_root", start: 486.07, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_timelapse_root.mp4" darken={0} /> },
  { key: "b209_rpl_i6_basil_cuttings_glass", start: 489.33, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_cuttings_glass.mp4" darken={0} /> },
  { key: "b210_rpl_i6_basil_windowsill_plants", start: 492.59, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_windowsill_plants.mp4" darken={0} /> },
  { key: "b211_rpl_i6_picking_basil_hand", start: 495.85, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_picking_basil_hand.mp4" darken={0} /> },
  { key: "b212_rpl_i6_basil_timelapse_root", start: 499.11, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_timelapse_root.mp4" darken={0} /> },
  { key: "cmp_num_7", start: 502.37, dur: 3.26, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="7" name="Menta" bg="broll/rpl_i7_mint_cuttings_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b214_rpl_i7_mint_cuttings_water", start: 505.63, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b215_rpl_i7_mint_roots_macro", start: 508.91, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b216_rpl_i7_mint_timelapse_grow", start: 512.19, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b217_rpl_i7_mint_cuttings_water", start: 515.47, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b218_rpl_i7_mint_roots_macro", start: 518.74, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b219_rpl_i7_mint_timelapse_grow", start: 522.02, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b220_rpl_i7_mint_cuttings_water", start: 525.3, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b221_rpl_i7_mint_roots_macro", start: 528.58, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b222_rpl_i7_mint_timelapse_grow", start: 531.86, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b223_rpl_i7_mint_cuttings_water", start: 535.13, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b224_rpl_i7_mint_roots_macro", start: 538.41, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b225_rpl_i7_mint_timelapse_grow", start: 541.69, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b226_rpl_i7_mint_cuttings_water", start: 544.97, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b227_rpl_i7_mint_roots_macro", start: 548.25, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b228_rpl_i7_mint_timelapse_grow", start: 551.52, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b229_rpl_err_pale_wilting_cutting", start: 554.8, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b230_rpl_err_cloudy_stagnant_water", start: 557.96, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b231_rpl_err_slimy_rotting_roots", start: 561.13, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b232_rpl_err_pouring_old_water", start: 564.29, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b233_rpl_err_transplant_rich_soil", start: 567.46, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b234_rpl_err_pale_wilting_cutting", start: 570.62, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b235_rpl_err_cloudy_stagnant_water", start: 573.79, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b236_rpl_err_slimy_rotting_roots", start: 576.96, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b237_rpl_err_pouring_old_water", start: 580.12, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b238_rpl_err_transplant_rich_soil", start: 583.29, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b239_rpl_err_pale_wilting_cutting", start: 586.45, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b240_rpl_err_cloudy_stagnant_water", start: 589.62, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b241_rpl_err_slimy_rotting_roots", start: 592.78, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b242_rpl_err_pouring_old_water", start: 595.95, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b243_rpl_err_transplant_rich_soil", start: 599.12, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b244_rpl_err_pale_wilting_cutting", start: 602.28, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "cmp_error_fix", start: 605.45, dur: 6.33, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Cambia el agua cada 2-3 días"},{"title":"En cuanto veas raíces, pásala a la tierra"}]} eyebrow="Las 2 reglas" title="Cómo evitar que mueran" accent="good" hue="amber" /> },
  { key: "b247_rpl_err_pouring_old_water", start: 611.78, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b248_rpl_err_transplant_rich_soil", start: 614.94, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b249_rpl_err_pale_wilting_cutting", start: 618.11, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b250_rpl_err_cloudy_stagnant_water", start: 621.28, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b251_rpl_err_slimy_rotting_roots", start: 624.44, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b252_rpl_err_pouring_old_water", start: 627.61, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b253_rpl_err_transplant_rich_soil", start: 630.77, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b254_rpl_err_pale_wilting_cutting", start: 633.94, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b255_rpl_err_cloudy_stagnant_water", start: 637.1, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "cmp_water_crew", start: 640.27, dur: 6.33, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Solo agua y ventana" items={[{"text":"Cebolla de verdeo","state":"done"},{"text":"Lechuga","state":"done"},{"text":"Apio","state":"done"},{"text":"Bok choy","state":"done"},{"text":"Puerro","state":"done"}]} eyebrow="Los 5 más fáciles" accent="good" hue="amber" image="img/cmp_water_crew_bg.png" /> },
  { key: "cmp_num_8", start: 646.6, dur: 3.17, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="8" name="Cilantro" bg="broll/rpl_i8_cilantro_stems_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b259_rpl_i8_cilantro_stems_water", start: 649.77, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_stems_water.mp4" darken={0} /> },
  { key: "b260_rpl_i8_cilantro_regrow_fresh", start: 653.04, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_regrow_fresh.mp4" darken={0} /> },
  { key: "b261_rpl_i8_cilantro_flowering", start: 656.3, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_flowering.mp4" darken={0} /> },
  { key: "b262_rpl_i8_coriander_seeds_macro", start: 659.57, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_coriander_seeds_macro.mp4" darken={0} /> },
  { key: "b263_rpl_i8_chopping_cilantro", start: 662.84, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_chopping_cilantro.mp4" darken={0} /> },
  { key: "b264_rpl_i8_cilantro_window_jar", start: 666.1, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_window_jar.mp4" darken={0} /> },
  { key: "b265_rpl_i8_cilantro_roots_macro", start: 669.37, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_roots_macro.mp4" darken={0} /> },
  { key: "b266_rpl_i8_cilantro_garden_bed", start: 672.64, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_garden_bed.mp4" darken={0} /> },
  { key: "b267_rpl_i8_cilantro_stems_water", start: 675.9, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_stems_water.mp4" darken={0} /> },
  { key: "b268_rpl_i8_cilantro_regrow_fresh", start: 679.17, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_regrow_fresh.mp4" darken={0} /> },
  { key: "b269_rpl_i8_cilantro_flowering", start: 682.44, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_flowering.mp4" darken={0} /> },
  { key: "b270_rpl_i8_coriander_seeds_macro", start: 685.7, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_coriander_seeds_macro.mp4" darken={0} /> },
  { key: "b271_rpl_i8_chopping_cilantro", start: 688.97, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_chopping_cilantro.mp4" darken={0} /> },
  { key: "b272_rpl_i8_cilantro_window_jar", start: 692.24, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_window_jar.mp4" darken={0} /> },
  { key: "cmp_num_9", start: 695.5, dur: 3.27, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="9" name="Ajo" bg="broll/rpl_i9_planting_clove_soil.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b274_rpl_i9_planting_clove_soil", start: 698.77, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b275_rpl_i9_garlic_rows_field", start: 702.02, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b276_rpl_i9_planting_clove_soil", start: 705.27, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b277_rpl_i9_garlic_rows_field", start: 708.52, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b278_rpl_i9_planting_clove_soil", start: 711.77, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b279_rpl_i9_garlic_rows_field", start: 715.02, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b280_rpl_i9_planting_clove_soil", start: 718.27, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b281_rpl_i9_garlic_rows_field", start: 721.52, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b282_rpl_i9_planting_clove_soil", start: 724.77, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b283_rpl_i9_garlic_rows_field", start: 728.02, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b284_rpl_i9_planting_clove_soil", start: 731.27, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b285_rpl_i9_garlic_rows_field", start: 734.52, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b286_rpl_i9_planting_clove_soil", start: 737.77, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b287_rpl_i9_garlic_rows_field", start: 741.02, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "cmp_num_10", start: 744.27, dur: 3.25, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="10" name="Jengibre" bg="broll/rpl_i10_ginger_buds_macro.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_jengibre", start: 747.52, dur: 6.44, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_jengibre_bg.png" annotations={[{"kind":"circle","x":0.42,"y":0.4,"w":0.16,"label":"Yema (como un ojo)","color":"good"},{"kind":"arrow","x":0.6,"y":0.6,"fromX":0.85,"fromY":0.85,"label":"Cortá con una yema","color":"amber"}]} eyebrow="Buscá la yema" hue="amber" /> },
  { key: "b291_rpl_i10_planting_ginger_soil", start: 753.96, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_planting_ginger_soil.mp4" darken={0} /> },
  { key: "b292_rpl_i10_ginger_shoot_green", start: 757.15, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_shoot_green.mp4" darken={0} /> },
  { key: "b293_rpl_i10_turmeric_root_orange", start: 760.34, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_turmeric_root_orange.mp4" darken={0} /> },
  { key: "b294_rpl_i10_ginger_pot_plant", start: 763.53, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_pot_plant.mp4" darken={0} /> },
  { key: "b295_rpl_i10_ginger_tea_water", start: 766.72, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_tea_water.mp4" darken={0} /> },
  { key: "b296_rpl_i10_ginger_market_pile", start: 769.91, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_market_pile.mp4" darken={0} /> },
  { key: "b297_rpl_i10_ginger_buds_macro", start: 773.1, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_buds_macro.mp4" darken={0} /> },
  { key: "b298_rpl_i10_planting_ginger_soil", start: 776.29, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_planting_ginger_soil.mp4" darken={0} /> },
  { key: "b299_rpl_i10_ginger_shoot_green", start: 779.48, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_shoot_green.mp4" darken={0} /> },
  { key: "b300_rpl_i10_turmeric_root_orange", start: 782.67, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_turmeric_root_orange.mp4" darken={0} /> },
  { key: "b301_rpl_i10_ginger_pot_plant", start: 785.86, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_pot_plant.mp4" darken={0} /> },
  { key: "b302_rpl_i10_ginger_tea_water", start: 789.05, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_tea_water.mp4" darken={0} /> },
  { key: "b303_rpl_i10_ginger_market_pile", start: 792.24, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_market_pile.mp4" darken={0} /> },
  { key: "b304_rpl_i10_ginger_buds_macro", start: 795.43, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_buds_macro.mp4" darken={0} /> },
  { key: "b305_rpl_i10_planting_ginger_soil", start: 798.62, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_planting_ginger_soil.mp4" darken={0} /> },
  { key: "b306_rpl_i10_ginger_shoot_green", start: 801.81, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_shoot_green.mp4" darken={0} /> },
  { key: "b307_rpl_i10_turmeric_root_orange", start: 805, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_turmeric_root_orange.mp4" darken={0} /> },
  { key: "cmp_num_11", start: 808.19, dur: 3.19, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="11" name="Papa" bg="broll/rpl_i11_sprouting_potato_pantry.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_papa", start: 811.38, dur: 6.54, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_papa_bg.png" annotations={[{"kind":"circle","x":0.35,"y":0.4,"w":0.14,"label":"Los ojos / brotes","color":"good"},{"kind":"circle","x":0.66,"y":0.55,"w":0.14,"label":"","color":"good"},{"kind":"arrow","x":0.5,"y":0.82,"fromX":0.8,"fromY":0.95,"label":"Cortá en trozos y dejá secar","color":"amber"}]} eyebrow="Cada trozo, un ojo" hue="amber" /> },
  { key: "b311_rpl_i11_cutting_potato_pieces", start: 817.92, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_cutting_potato_pieces.mp4" darken={0} /> },
  { key: "b312_rpl_i11_potato_pieces_drying", start: 821.26, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_pieces_drying.mp4" darken={0} /> },
  { key: "b313_rpl_i11_planting_trench_soil", start: 824.61, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_planting_trench_soil.mp4" darken={0} /> },
  { key: "b314_rpl_i11_potato_plants_rows", start: 827.95, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plants_rows.mp4" darken={0} /> },
  { key: "b315_rpl_i11_potato_sprout_macro", start: 831.29, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_sprout_macro.mp4" darken={0} /> },
  { key: "b316_rpl_i11_potato_plant_timelapse", start: 834.64, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plant_timelapse.mp4" darken={0} /> },
  { key: "b317_rpl_i11_washing_potatoes_water", start: 837.98, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_washing_potatoes_water.mp4" darken={0} /> },
  { key: "b318_rpl_i11_sprouting_potato_pantry", start: 841.33, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_sprouting_potato_pantry.mp4" darken={0} /> },
  { key: "b319_rpl_i11_cutting_potato_pieces", start: 844.67, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_cutting_potato_pieces.mp4" darken={0} /> },
  { key: "b320_rpl_i11_potato_pieces_drying", start: 848.01, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_pieces_drying.mp4" darken={0} /> },
  { key: "b321_rpl_i11_planting_trench_soil", start: 851.36, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_planting_trench_soil.mp4" darken={0} /> },
  { key: "b322_rpl_i11_potato_plants_rows", start: 854.7, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plants_rows.mp4" darken={0} /> },
  { key: "b323_rpl_i11_potato_sprout_macro", start: 858.04, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_sprout_macro.mp4" darken={0} /> },
  { key: "b324_rpl_i11_potato_plant_timelapse", start: 861.39, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plant_timelapse.mp4" darken={0} /> },
  { key: "b325_rpl_i11_washing_potatoes_water", start: 864.73, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_washing_potatoes_water.mp4" darken={0} /> },
  { key: "cmp_potato_yield", start: 868.08, dur: 6.68, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="10–15" eyebrow="De una sola papa" caption="papas nuevas, de una que ibas a tirar" accent="good" hue="amber" /> },
  { key: "b328_rpl_i11_potato_pieces_drying", start: 874.76, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_pieces_drying.mp4" darken={0} /> },
  { key: "b329_rpl_i11_planting_trench_soil", start: 878.11, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_planting_trench_soil.mp4" darken={0} /> },
  { key: "b330_rpl_i11_potato_plants_rows", start: 881.45, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plants_rows.mp4" darken={0} /> },
  { key: "cmp_num_12", start: 884.8, dur: 3.34, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="12" name="Batata" bg="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_batata", start: 888.14, dur: 6.78, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_batata_bg.png" annotations={[{"kind":"arrow","x":0.5,"y":0.45,"fromX":0.8,"fromY":0.2,"label":"Palillos: mitad en agua","color":"amber"},{"kind":"circle","x":0.5,"y":0.2,"w":0.3,"label":"Salen los esquejes","color":"good"}]} eyebrow="El truco de los palillos" hue="amber" /> },
  { key: "b334_rpl_i12_pulling_a_slip", start: 894.92, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_pulling_a_slip.mp4" darken={0} /> },
  { key: "b335_rpl_i12_rooting_slips_water", start: 898.34, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_rooting_slips_water.mp4" darken={0} /> },
  { key: "b336_rpl_i12_slips_macro_roots", start: 901.77, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_slips_macro_roots.mp4" darken={0} /> },
  { key: "b337_rpl_i12_sweetpotato_toothpicks_glass", start: 905.2, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" darken={0} /> },
  { key: "b338_rpl_i12_pulling_a_slip", start: 908.63, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_pulling_a_slip.mp4" darken={0} /> },
  { key: "b339_rpl_i12_rooting_slips_water", start: 912.06, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_rooting_slips_water.mp4" darken={0} /> },
  { key: "b340_rpl_i12_slips_macro_roots", start: 915.49, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_slips_macro_roots.mp4" darken={0} /> },
  { key: "b341_rpl_i12_sweetpotato_toothpicks_glass", start: 918.92, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" darken={0} /> },
  { key: "b342_rpl_i12_pulling_a_slip", start: 922.35, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_pulling_a_slip.mp4" darken={0} /> },
  { key: "b343_rpl_i12_rooting_slips_water", start: 925.78, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_rooting_slips_water.mp4" darken={0} /> },
  { key: "b344_rpl_i12_slips_macro_roots", start: 929.2, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_slips_macro_roots.mp4" darken={0} /> },
  { key: "b345_rpl_i12_sweetpotato_toothpicks_glass", start: 932.63, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" darken={0} /> },
  { key: "b346_rpl_i12_pulling_a_slip", start: 936.06, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_pulling_a_slip.mp4" darken={0} /> },
  { key: "b347_rpl_i12_rooting_slips_water", start: 939.49, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_rooting_slips_water.mp4" darken={0} /> },
  { key: "b348_rpl_i12_slips_macro_roots", start: 942.92, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_slips_macro_roots.mp4" darken={0} /> },
  { key: "cmp_num_13", start: 946.35, dur: 3.42, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="13" name="Zanahoria" bg="broll/rpl_i13_cutting_carrot_tops.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b350_rpl_i13_cutting_carrot_tops", start: 949.77, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_cutting_carrot_tops.mp4" darken={0} /> },
  { key: "b351_rpl_i13_carrot_tops_dish_water", start: 953.11, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_tops_dish_water.mp4" darken={0} /> },
  { key: "b352_rpl_i13_carrot_seeds_hand", start: 956.44, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seeds_hand.mp4" darken={0} /> },
  { key: "b353_rpl_i13_pulling_carrots_soil", start: 959.77, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_pulling_carrots_soil.mp4" darken={0} /> },
  { key: "b354_rpl_i13_washing_carrots_water", start: 963.11, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_washing_carrots_water.mp4" darken={0} /> },
  { key: "b355_rpl_i13_carrots_market_bunch", start: 966.44, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrots_market_bunch.mp4" darken={0} /> },
  { key: "b356_rpl_i13_carrot_seedling_soil", start: 969.77, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seedling_soil.mp4" darken={0} /> },
  { key: "b357_rpl_i13_cutting_carrot_tops", start: 973.11, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_cutting_carrot_tops.mp4" darken={0} /> },
  { key: "b358_rpl_i13_carrot_tops_dish_water", start: 976.44, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_tops_dish_water.mp4" darken={0} /> },
  { key: "b359_rpl_i13_carrot_seeds_hand", start: 979.77, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seeds_hand.mp4" darken={0} /> },
  { key: "b360_rpl_i13_pulling_carrots_soil", start: 983.11, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_pulling_carrots_soil.mp4" darken={0} /> },
  { key: "b361_rpl_i13_washing_carrots_water", start: 986.44, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_washing_carrots_water.mp4" darken={0} /> },
  { key: "b362_rpl_i13_carrots_market_bunch", start: 989.77, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrots_market_bunch.mp4" darken={0} /> },
  { key: "b363_rpl_i13_carrot_seedling_soil", start: 993.11, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seedling_soil.mp4" darken={0} /> },
  { key: "b364_rpl_i13_cutting_carrot_tops", start: 996.44, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_cutting_carrot_tops.mp4" darken={0} /> },
  { key: "b365_rpl_i13_carrot_tops_dish_water", start: 999.77, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_tops_dish_water.mp4" darken={0} /> },
  { key: "b366_rpl_i13_carrot_seeds_hand", start: 1003.11, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seeds_hand.mp4" darken={0} /> },
  { key: "b367_rpl_i13_pulling_carrots_soil", start: 1006.44, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_pulling_carrots_soil.mp4" darken={0} /> },
  { key: "b368_rpl_i13_washing_carrots_water", start: 1009.77, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_washing_carrots_water.mp4" darken={0} /> },
  { key: "b369_rpl_i13_carrots_market_bunch", start: 1013.11, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrots_market_bunch.mp4" darken={0} /> },
  { key: "cmp_num_14", start: 1016.44, dur: 3.33, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="14" name="Tomate" bg="broll/rpl_i14_slicing_tomato_rounds.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b371_rpl_i14_slicing_tomato_rounds", start: 1019.77, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_slicing_tomato_rounds.mp4" darken={0} /> },
  { key: "b372_rpl_i14_covering_slices_soil", start: 1023, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_covering_slices_soil.mp4" darken={0} /> },
  { key: "b373_rpl_i14_tomato_seedlings_row", start: 1026.22, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seedlings_row.mp4" darken={0} /> },
  { key: "b374_rpl_i14_seedlings_tray_dozens", start: 1029.45, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_seedlings_tray_dozens.mp4" darken={0} /> },
  { key: "b375_rpl_i14_tomato_seeds_macro", start: 1032.68, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seeds_macro.mp4" darken={0} /> },
  { key: "b376_rpl_i14_tomato_timelapse_grow", start: 1035.9, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_timelapse_grow.mp4" darken={0} /> },
  { key: "b377_rpl_i14_slicing_tomato_rounds", start: 1039.13, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_slicing_tomato_rounds.mp4" darken={0} /> },
  { key: "b378_rpl_i14_covering_slices_soil", start: 1042.35, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_covering_slices_soil.mp4" darken={0} /> },
  { key: "b379_rpl_i14_tomato_seedlings_row", start: 1045.58, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seedlings_row.mp4" darken={0} /> },
  { key: "b380_rpl_i14_seedlings_tray_dozens", start: 1048.81, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_seedlings_tray_dozens.mp4" darken={0} /> },
  { key: "b381_rpl_i14_tomato_seeds_macro", start: 1052.03, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seeds_macro.mp4" darken={0} /> },
  { key: "b382_rpl_i14_tomato_timelapse_grow", start: 1055.26, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_timelapse_grow.mp4" darken={0} /> },
  { key: "b383_rpl_i14_slicing_tomato_rounds", start: 1058.49, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_slicing_tomato_rounds.mp4" darken={0} /> },
  { key: "b384_rpl_i14_covering_slices_soil", start: 1061.71, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_covering_slices_soil.mp4" darken={0} /> },
  { key: "b385_rpl_i14_tomato_seedlings_row", start: 1064.94, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seedlings_row.mp4" darken={0} /> },
  { key: "b386_rpl_i14_seedlings_tray_dozens", start: 1068.17, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_seedlings_tray_dozens.mp4" darken={0} /> },
  { key: "b387_rpl_i14_tomato_seeds_macro", start: 1071.39, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seeds_macro.mp4" darken={0} /> },
  { key: "b388_rpl_i14_tomato_timelapse_grow", start: 1074.62, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_timelapse_grow.mp4" darken={0} /> },
  { key: "cmp_num_15", start: 1077.85, dur: 3.22, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="15" name="Piña" bg="broll/rpl_i15_pineapple_crown_leafy.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_pina", start: 1081.07, dur: 6.61, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_pina_bg.png" annotations={[{"kind":"arrow","x":0.5,"y":0.7,"fromX":0.82,"fromY":0.9,"label":"Sacá las hojas de abajo","color":"amber"},{"kind":"circle","x":0.5,"y":0.66,"w":0.16,"label":"Raíces dormidas","color":"good"}]} eyebrow="La corona = una planta" hue="amber" /> },
  { key: "b392_rpl_i15_stripping_lower_leaves", start: 1087.68, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_stripping_lower_leaves.mp4" darken={0} /> },
  { key: "b393_rpl_i15_pineapple_crown_drying", start: 1091.06, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_crown_drying.mp4" darken={0} /> },
  { key: "b394_rpl_i15_crown_rooting_water", start: 1094.44, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_crown_rooting_water.mp4" darken={0} /> },
  { key: "b395_rpl_i15_mature_pineapple_fruit", start: 1097.82, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_mature_pineapple_fruit.mp4" darken={0} /> },
  { key: "b396_rpl_i15_pineapple_root_bumps_macro", start: 1101.2, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_root_bumps_macro.mp4" darken={0} /> },
  { key: "b397_rpl_i15_pineapple_field_rows", start: 1104.58, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_field_rows.mp4" darken={0} /> },
  { key: "b398_rpl_i15_planting_crown_soil", start: 1107.96, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_planting_crown_soil.mp4" darken={0} /> },
  { key: "b399_rpl_i15_pineapple_crown_window", start: 1111.33, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_crown_window.mp4" darken={0} /> },
  { key: "b400_rpl_i15_pineapple_leaves_macro", start: 1114.71, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_leaves_macro.mp4" darken={0} /> },
  { key: "b401_rpl_i15_cutting_pineapple_top", start: 1118.09, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_cutting_pineapple_top.mp4" darken={0} /> },
  { key: "b402_rpl_i15_pineapple_timelapse_root", start: 1121.47, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_timelapse_root.mp4" darken={0} /> },
  { key: "b403_rpl_i15_pineapple_crown_leafy", start: 1124.85, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_crown_leafy.mp4" darken={0} /> },
  { key: "b404_rpl_i15_stripping_lower_leaves", start: 1128.23, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_stripping_lower_leaves.mp4" darken={0} /> },
  { key: "b405_rpl_i15_pineapple_crown_drying", start: 1131.61, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_crown_drying.mp4" darken={0} /> },
  { key: "b406_rpl_i15_crown_rooting_water", start: 1134.98, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_crown_rooting_water.mp4" darken={0} /> },
  { key: "b407_rpl_i15_mature_pineapple_fruit", start: 1138.36, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_mature_pineapple_fruit.mp4" darken={0} /> },
  { key: "b408_rpl_i15_pineapple_root_bumps_macro", start: 1141.74, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_root_bumps_macro.mp4" darken={0} /> },
  { key: "b409_rpl_i15_pineapple_field_rows", start: 1145.12, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_field_rows.mp4" darken={0} /> },
  { key: "cmp_num_16", start: 1148.5, dur: 3.38, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="16" name="Pimiento" bg="broll/rpl_i16_cutting_open_pepper.mp4" eyebrow="Bonus de regalo" accent="good" /> },
  { key: "cmp_quote", start: 1151.88, dur: 6.75, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_bg.png" words={parseQuote("La naturaleza no conoce la palabra *basura*.")} accent="amber" hue="amber" fontSize={96} /> },
  { key: "b413_rpl_i16_cutting_open_pepper", start: 1158.63, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_cutting_open_pepper.mp4" darken={0} /> },
  { key: "b414_rpl_i16_pressing_seeds_soil", start: 1161.91, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pressing_seeds_soil.mp4" darken={0} /> },
  { key: "b415_rpl_i16_pepper_seedlings_germinate", start: 1165.18, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedlings_germinate.mp4" darken={0} /> },
  { key: "b416_rpl_i16_colorful_peppers_market", start: 1168.46, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_colorful_peppers_market.mp4" darken={0} /> },
  { key: "b417_rpl_i16_pepper_seedling_macro", start: 1171.74, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedling_macro.mp4" darken={0} /> },
  { key: "b418_rpl_i16_watering_pepper_pot", start: 1175.01, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_watering_pepper_pot.mp4" darken={0} /> },
  { key: "b419_rpl_i16_picking_pepper_plant", start: 1178.29, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_picking_pepper_plant.mp4" darken={0} /> },
  { key: "b420_rpl_i16_cutting_open_pepper", start: 1181.56, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_cutting_open_pepper.mp4" darken={0} /> },
  { key: "b421_rpl_i16_pressing_seeds_soil", start: 1184.84, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pressing_seeds_soil.mp4" darken={0} /> },
  { key: "b422_rpl_i16_pepper_seedlings_germinate", start: 1188.12, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedlings_germinate.mp4" darken={0} /> },
  { key: "b423_rpl_i16_colorful_peppers_market", start: 1191.39, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_colorful_peppers_market.mp4" darken={0} /> },
  { key: "b424_rpl_i16_pepper_seedling_macro", start: 1194.67, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedling_macro.mp4" darken={0} /> },
  { key: "b425_rpl_i16_watering_pepper_pot", start: 1197.94, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_watering_pepper_pot.mp4" darken={0} /> },
  { key: "b426_rpl_i16_picking_pepper_plant", start: 1201.22, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_picking_pepper_plant.mp4" darken={0} /> },
  { key: "cmp_grid", start: 1204.5, dur: 9.2, kind: "gridreveal", el: (d) => <GridReveal durationInFrames={d} tiles={[{"number":"1","name":"Cebolla de verdeo"},{"number":"2","name":"Lechuga"},{"number":"3","name":"Apio"},{"number":"4","name":"Bok choy"},{"number":"5","name":"Puerro"},{"number":"6","name":"Albahaca"},{"number":"7","name":"Menta"},{"number":"8","name":"Cilantro"},{"number":"9","name":"Ajo"},{"number":"10","name":"Jengibre"},{"number":"11","name":"Papa"},{"number":"12","name":"Batata"},{"number":"13","name":"Zanahoria"},{"number":"14","name":"Tomate"},{"number":"15","name":"Piña"},{"number":"16","name":"Pimiento"}]} title="16 restos = 16 plantas" subtitle="Gratis · desde tu basura" /> },
  { key: "cmp_zero", start: 1213.7, dur: 8.91, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="0€" eyebrow="16 plantas" caption="comida que se siembra a sí misma, desde tu basura" accent="good" hue="amber" /> },
  { key: "b433_rpl_cl_scraps_returned_soil", start: 1222.61, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_scraps_returned_soil.mp4" darken={0} /> },
  { key: "b434_rpl_cl_child_hands_seedling", start: 1225.58, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_child_hands_seedling.mp4" darken={0} /> },
  { key: "b435_rpl_cl_seedlings_windowsill_row", start: 1228.55, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_seedlings_windowsill_row.mp4" darken={0} /> },
  { key: "b436_rpl_cl_farmer_teaching_child", start: 1231.52, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_farmer_teaching_child.mp4" darken={0} /> },
  { key: "b437_rpl_cl_scraps_returned_soil", start: 1234.5, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_scraps_returned_soil.mp4" darken={0} /> },
  { key: "b438_rpl_cl_child_hands_seedling", start: 1237.47, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_child_hands_seedling.mp4" darken={0} /> },
  { key: "b439_rpl_cl_seedlings_windowsill_row", start: 1240.44, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_seedlings_windowsill_row.mp4" darken={0} /> },
  { key: "b440_rpl_cl_farmer_teaching_child", start: 1243.41, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_farmer_teaching_child.mp4" darken={0} /> },
  { key: "b441_rpl_cl_scraps_returned_soil", start: 1246.38, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_scraps_returned_soil.mp4" darken={0} /> },
  { key: "b442_rpl_ac_scallion_into_glass", start: 1249.35, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
  { key: "b443_rpl_ac_writing_garden_journal", start: 1252.29, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_writing_garden_journal.mp4" darken={0} /> },
  { key: "b444_rpl_ac_fresh_start_seedlings", start: 1255.24, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_fresh_start_seedlings.mp4" darken={0} /> },
  { key: "b445_rpl_ac_scallion_into_glass", start: 1258.18, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
  { key: "b446_rpl_ac_writing_garden_journal", start: 1261.12, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_writing_garden_journal.mp4" darken={0} /> },
  { key: "b447_rpl_ac_fresh_start_seedlings", start: 1264.07, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_fresh_start_seedlings.mp4" darken={0} /> },
  { key: "b448_rpl_ac_scallion_into_glass", start: 1267.01, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
  { key: "b449_rpl_ac_writing_garden_journal", start: 1269.95, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_writing_garden_journal.mp4" darken={0} /> },
  { key: "b450_rpl_ac_fresh_start_seedlings", start: 1272.9, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_fresh_start_seedlings.mp4" darken={0} /> },
  { key: "b451_rpl_ac_scallion_into_glass", start: 1275.84, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
  { key: "b452_rpl_ac_writing_garden_journal", start: 1278.79, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_writing_garden_journal.mp4" darken={0} /> },
  { key: "b453_rpl_ac_fresh_start_seedlings", start: 1281.73, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_fresh_start_seedlings.mp4" darken={0} /> },
  { key: "b454_rpl_ac_scallion_into_glass", start: 1284.67, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "kl1", start: 43.5, dur: 4.84, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" Esa","at":0},{"t":" parte","at":0.22},{"t":" que","at":0.6},{"t":" tú","at":0.83},{"t":" llamas","at":1.06},{"t":" basura","at":1.51},{"t":" todavía","at":2},{"t":" está","at":2.72},{"t":" viva.","at":3.14,"hl":true}]} accent="amber" /> },
  { key: "kl2", start: 50.29, dur: 3.05, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" vuelve","at":0},{"t":" a","at":0.53},{"t":" crecer.","at":0.62},{"t":" Gratis.","at":1.35,"hl":true}]} accent="amber" /> },
  { key: "kl3", start: 1214.1, dur: 2.56, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" cero","at":0,"hl":true},{"t":" euros","at":0.33,"hl":true},{"t":" gastados.","at":0.86}]} accent="amber" /> },
  { key: "kl4", start: 593.18, dur: 2.09, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" para","at":0},{"t":" siempre","at":0.39,"hl":true}]} accent="amber" /> },
  { key: "kl5", start: 1323.93, dur: 3.43, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" tires","at":0},{"t":" lo","at":0.44},{"t":" que","at":0.48},{"t":" todavía","at":0.71},{"t":" está","at":1.33},{"t":" vivo.","at":1.73,"hl":true}]} accent="amber" /> },
];
