// cues_rampump.gen.tsx — GENERADO por beatsheet.mjs desde rampump.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/rampump.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { StatTag } from "./scenes/StatTag";
import { PhraseTag } from "./scenes/PhraseTag";
import { SagaTimeline } from "./scenes/SagaTimeline";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { RamPumpCycle } from "./scenes/RamPumpCycle";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { NextVideoEndcard } from "./scenes/NextVideoEndcard";
import { DocLabel } from "./overlays/DocLabel";
import { DateStamp } from "./overlays/DateStamp";

const B = COLORS.cold;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "rp_pump_mud", start: 2.2, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pump_mud.mp4" darken={0} /> },
  { key: "rp_spring", start: 5.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_spring.mp4" darken={0} /> },
  { key: "rp_pump_close", start: 9, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pump_close.mp4" darken={0} /> },
  { key: "rp_pasture_spring", start: 13, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pasture_spring.mp4" darken={0} /> },
  { key: "rp_grandfather", start: 17.4, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_grandfather.mp4" darken={0} /> },
  { key: "rp_pipe_valves", start: 21.8, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pipe_valves.mp4" darken={0} /> },
  { key: "rp_inner_tube", start: 25.7, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_inner_tube.mp4" darken={0} /> },
  { key: "rp_open_valve", start: 29.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_open_valve.mp4" darken={0} /> },
  { key: "rp_winter_farm", start: 33.5, dur: 9.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_winter_farm.mp4" darken={0} /> },
  { key: "rp_pump_running", start: 42.1, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pump_running.mp4" darken={0} /> },
  { key: "rp_water_climb", start: 50.1, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_water_climb.mp4" darken={0} /> },
  { key: "rp_tank_hill", start: 54.4, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_tank_hill.mp4" darken={0} /> },
  { key: "rp_trough", start: 58.3, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_trough.mp4" darken={0} /> },
  { key: "rp_uphill_pipe", start: 62.6, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_uphill_pipe.mp4" darken={0} /> },
  { key: "rp_water_weight", start: 71.1, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_water_weight.mp4" darken={0} /> },
  { key: "cmp_hook", start: 75.2, dur: 8.3, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_hook_bg.png" impact="Water going uphill. With no power." setup="Watch closely:" impactAccent="cold" hitAt={1.5} boom={0} darken={0.42} /> },
  { key: "rp_uphill_magic", start: 83.5, dur: 8.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_uphill_magic.mp4" darken={0} /> },
  { key: "rp_water_bill2", start: 91.8, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_water_bill2.mp4" darken={0} /> },
  { key: "rp_diagram_hand", start: 95.8, dur: 8.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_diagram_hand.mp4" darken={0} /> },
  { key: "rp_cool_pipe", start: 124.7, dur: 8.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_cool_pipe.png" darken={0} /> },
  { key: "rp_stream_wide", start: 132.5, dur: 9.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_stream_wide.mp4" darken={0} /> },
  { key: "rp_spring_low", start: 141.4, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_spring_low.mp4" darken={0} /> },
  { key: "rp_house_high", start: 145.6, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_house_high.mp4" darken={0} /> },
  { key: "rp_animals_drink", start: 149.3, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_animals_drink.mp4" darken={0} /> },
  { key: "rp_electric_pump", start: 153.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_electric_pump.mp4" darken={0} /> },
  { key: "rp_pump_broken", start: 158, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pump_broken.mp4" darken={0} /> },
  { key: "rp_pump_knock", start: 162.1, dur: 11.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_pump_knock.png" darken={0} /> },
  { key: "rp_gallon", start: 173.4, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_gallon.mp4" darken={0} /> },
  { key: "rp_lift_water", start: 181.4, dur: 8.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_lift_water.mp4" darken={0} /> },
  { key: "rp_energy", start: 189.3, dur: 12.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_energy.mp4" darken={0} /> },
  { key: "rp_plug_pump", start: 201.5, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_plug_pump.mp4" darken={0} /> },
  { key: "rp_meter_spin", start: 205.6, dur: 8.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_meter_spin.mp4" darken={0} /> },
  { key: "rp_power_out", start: 213.4, dur: 9.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_power_out.mp4" darken={0} /> },
  { key: "rp_water_energy2", start: 222.2, dur: 13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_water_energy2.mp4" darken={0} /> },
  { key: "rp_flowing", start: 234.7, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_flowing.mp4" darken={0} /> },
  { key: "rp_mill_wheel", start: 242.9, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_mill_wheel.mp4" darken={0} /> },
  { key: "rp_dam", start: 246.6, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_dam.mp4" darken={0} /> },
  { key: "rp_big_small", start: 254.8, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_big_small.mp4" darken={0} /> },
  { key: "rp_push_up", start: 258.6, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_push_up.mp4" darken={0} /> },
  { key: "cmp_cycle", start: 266.6, dur: 17.2, kind: "rampump", el: (d) => <RamPumpCycle durationInFrames={d} eyebrow="How it works" title="One knock at a time" driveTag={{"text":"Drive pipe","sub":"water falls & speeds up"}} wasteTag={{"text":"Waste valve","sub":"slams shut → hammer"}} airTag={{"text":"Air chamber","sub":"cushions the blow"}} tankTag={{"text":"Up the hill","sub":"to your tank"}} ratioTag="10 fall · 1 climbs" /> },
  { key: "rp_drive_pipe", start: 283.8, dur: 13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_drive_pipe.mp4" darken={0} /> },
  { key: "rp_waste_valve", start: 296.3, dur: 12.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_waste_valve.mp4" darken={0} /> },
  { key: "rp_water_rush", start: 308.3, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_water_rush.png" darken={0} /> },
  { key: "rp_valve_slam", start: 320.7, dur: 16.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_valve_slam.mp4" darken={0} /> },
  { key: "rp_pressure", start: 336.4, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pressure.mp4" darken={0} /> },
  { key: "rp_faucet_bang", start: 344.4, dur: 12.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_faucet_bang.mp4" darken={0} /> },
  { key: "rp_hammer", start: 356.4, dur: 8.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_hammer.mp4" darken={0} /> },
  { key: "rp_delivery_valve", start: 364.8, dur: 12.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_delivery_valve.png" darken={0} /> },
  { key: "rp_slug_up", start: 377.1, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_slug_up.mp4" darken={0} /> },
  { key: "rp_valve_reset", start: 385.1, dur: 13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_valve_reset.png" darken={0} /> },
  { key: "rp_tick", start: 397.6, dur: 13.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_tick.png" darken={0} /> },
  { key: "rp_air_chamber", start: 410.9, dur: 16.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_air_chamber.mp4" darken={0} /> },
  { key: "rp_air_squeeze", start: 427.2, dur: 12.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_air_squeeze.mp4" darken={0} /> },
  { key: "cmp_anatomy", start: 439.1, dur: 16.7, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anatomy_bg.png" annotations={[{"kind":"circle","x":0.28,"y":0.4,"w":0.14,"label":"Drive pipe","color":"accent"},{"kind":"circle","x":0.52,"y":0.78,"w":0.12,"label":"Waste valve","color":"danger"},{"kind":"arrow","x":0.62,"y":0.3,"fromX":0.8,"fromY":0.12,"label":"Air chamber","color":"cold"}]} eyebrow="The five parts" hue="cold" /> },
  { key: "cmp_parts", start: 455.8, dur: 20.6, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="The whole device" items={[{"text":"Drive pipe","state":"done"},{"text":"Waste valve","state":"done"},{"text":"Delivery valve","state":"done"},{"text":"Air chamber","state":"done"},{"text":"Delivery pipe","state":"done"}]} eyebrow="5 parts · 2 are just flaps" accent="good" hue="cold" image="img/cmp_parts_bg.png" /> },
  { key: "rp_no_motor", start: 476.4, dur: 13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_no_motor.mp4" darken={0} /> },
  { key: "cmp_ratio", start: 488.9, dur: 20.2, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Back to the stream","value":9,"display":"9 gal","tone":"amber"},{"label":"Up the hill","value":1,"display":"1 gal","winner":true}]} eyebrow="Out of every 10" title="Where the water goes" unit="gal" accent="good" hue="cold" /> },
  { key: "rp_waste_back", start: 509.1, dur: 9.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_waste_back.mp4" darken={0} /> },
  { key: "rp_free_water", start: 517.7, dur: 16.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_free_water.mp4" darken={0} /> },
  { key: "cmp_lift", start: 533.6, dur: 16.3, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={10} suffix="×" label="higher than the distance the water falls" eyebrow="The lift" accent="good" hue="cold" /> },
  { key: "rp_fall_three", start: 549.9, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_fall_three.mp4" darken={0} /> },
  { key: "rp_fall_six", start: 558, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_fall_six.mp4" darken={0} /> },
  { key: "cmp_perday", start: 566.1, dur: 12.3, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={1000} prefix="+" suffix=" gal/day" label="from a machine that costs a few dollars and runs on falling water" eyebrow="All day, all night" accent="good" hue="amber" /> },
  { key: "rp_house_garden", start: 578.4, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_house_garden.mp4" darken={0} /> },
  { key: "rp_cheap_machine", start: 586, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_cheap_machine.png" darken={0} /> },
  { key: "rp_buckets", start: 593.6, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_buckets.png" darken={0} /> },
  { key: "rp_hard_chore", start: 606, dur: 15.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_hard_chore.mp4" darken={0} /> },
  { key: "rp_old_book", start: 621.2, dur: 8.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_old_book.mp4" darken={0} /> },
  { key: "rp_cut_pipe", start: 629.5, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_cut_pipe.mp4" darken={0} /> },
  { key: "rp_set_in_mud", start: 637.7, dur: 8.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_set_in_mud.mp4" darken={0} /> },
  { key: "rp_water_boots", start: 646, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_water_boots.mp4" darken={0} /> },
  { key: "rp_men_watching", start: 654.1, dur: 13.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_men_watching.mp4" darken={0} /> },
  { key: "rp_water_walk", start: 687.4, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_water_walk.png" darken={0} /> },
  { key: "cmp_history", start: 691.4, dur: 20.6, kind: "timeline", el: (d) => <SagaTimeline durationInFrames={d} events={[{"year":"1796","label":"perfected in France","accent":"amber"},{"year":"1800s","label":"farms & villages everywhere","accent":"amber"},{"year":"1900s","label":"the grid buried it","accent":"danger"}]} eyebrow="It is not new" title="Why you never heard of it" /> },
  { key: "rp_old_estate", start: 712, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_old_estate.mp4" darken={0} /> },
  { key: "rp_rooftop_tank", start: 720.2, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_rooftop_tank.mp4" darken={0} /> },
  { key: "rp_village", start: 724.4, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_village.mp4" darken={0} /> },
  { key: "rp_grid_came", start: 728.4, dur: 8.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_grid_came.mp4" darken={0} /> },
  { key: "rp_forgotten", start: 736.3, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_forgotten.mp4" darken={0} /> },
  { key: "rp_no_money", start: 743.8, dur: 9.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_no_money.mp4" darken={0} /> },
  { key: "rp_catalog", start: 752.5, dur: 16.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_catalog.png" darken={0} /> },
  { key: "rp_offgrid_folks", start: 768.9, dur: 16.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_offgrid_folks.mp4" darken={0} /> },
  { key: "cmp_materials", start: 784.7, dur: 12.7, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="What to buy" items={[{"text":"Falling water source (3+ ft drop)","state":"done"},{"text":"Rigid drive pipe","state":"done"},{"text":"Two check valves","state":"done"},{"text":"Air chamber + delivery pipe","state":"done"}]} eyebrow="Any hardware store" accent="good" hue="amber" image="img/cmp_materials_bg.png" /> },
  { key: "rp_solid_pipe", start: 797.4, dur: 12.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_solid_pipe.mp4" darken={0} /> },
  { key: "rp_pump_body", start: 809.3, dur: 12.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_pump_body.mp4" darken={0} /> },
  { key: "rp_check_valve", start: 821.1, dur: 13.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_check_valve.png" darken={0} /> },
  { key: "rp_capped_pipe", start: 833.7, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_capped_pipe.mp4" darken={0} /> },
  { key: "rp_delivery_line", start: 841.9, dur: 8.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_delivery_line.mp4" darken={0} /> },
  { key: "rp_few_fittings", start: 849.7, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_few_fittings.mp4" darken={0} /> },
  { key: "cmp_sizing", start: 857.8, dur: 27.7, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Getting it right" items={[{"text":"Drive pipe = 5–10× the fall","state":"done"},{"text":"Fat pipe down, thin pipe up","state":"done"},{"text":"Big air chamber = smooth knock","state":"done"}]} eyebrow="Roughly, then tune by ear" accent="good" hue="cold" image="img/cmp_sizing_bg.png" /> },
  { key: "rp_drive_long", start: 885.5, dur: 17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_drive_long.mp4" darken={0} /> },
  { key: "rp_fat_thin", start: 902, dur: 21.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_fat_thin.mp4" darken={0} /> },
  { key: "rp_air_volume", start: 922.6, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_air_volume.mp4" darken={0} /> },
  { key: "rp_tune_knock", start: 935, dur: 16.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_tune_knock.mp4" darken={0} /> },
  { key: "rp_scrap_pump", start: 950.6, dur: 13.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_scrap_pump.mp4" darken={0} /> },
  { key: "rp_install_pump", start: 963.9, dur: 12.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_install_pump.mp4" darken={0} /> },
  { key: "rp_meter_daily", start: 975.6, dur: 8.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_meter_daily.mp4" darken={0} /> },
  { key: "rp_motor_burn", start: 983.9, dur: 13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_motor_burn.png" darken={0} /> },
  { key: "cmp_cost", start: 996.4, dur: 20.2, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Electric pump","value":80,"display":"$1000s","sub":"install + power + replace","tone":"danger"},{"label":"Ram pump","value":1,"display":"a few $","sub":"once, runs free","winner":true}]} eyebrow="Moving water uphill" title="Cost over 30 years" unit="USD" accent="good" hue="amber" /> },
  { key: "cmp_where", start: 1016.6, dur: 8.4, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Where it works" items={["Needs falling water (3+ ft drop)","Spring, stream, pond above a field","A small dam makes the drop"]} accent={B} /> },
  { key: "cmp_runfree", start: 1025, dur: 20.4, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$0 / year" image="img/cmp_runfree_bg.png" eyebrow="To run — forever" caption="no electricity, no fuel, no bill; the only part that wears is a rubber washer" accent="good" hue="cold" /> },
  { key: "rp_falling_water", start: 1045.4, dur: 12.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_falling_water.mp4" darken={0} /> },
  { key: "rp_higher_source", start: 1057.6, dur: 12.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_higher_source.mp4" darken={0} /> },
  { key: "rp_flat_pond", start: 1069.6, dur: 12.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_flat_pond.mp4" darken={0} /> },
  { key: "rp_small_drop", start: 1081.4, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_small_drop.mp4" darken={0} /> },
  { key: "rp_creek_dam", start: 1085.5, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_creek_dam.mp4" darken={0} /> },
  { key: "rp_hillside_spring", start: 1089.2, dur: 8.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_hillside_spring.mp4" darken={0} /> },
  { key: "cmp_mistakes", start: 1097.1, dur: 20.5, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Two mistakes to avoid" items={[{"text":"Never use flexible/soft drive pipe","state":"done"},{"text":"Tune the waste valve to a steady knock","state":"done"}]} eyebrow="Then it runs day one" accent="danger" hue="amber" image="img/cmp_mistakes_bg.png" /> },
  { key: "rp_garden_hose", start: 1117.6, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_garden_hose.mp4" darken={0} /> },
  { key: "rp_rigid_pipe", start: 1125.6, dur: 13.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_rigid_pipe.png" darken={0} /> },
  { key: "rp_hose_flex", start: 1138.2, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_hose_flex.png" darken={0} /> },
  { key: "rp_waste_tune", start: 1150.6, dur: 16.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_waste_tune.mp4" darken={0} /> },
  { key: "rp_valve_weight", start: 1166.6, dur: 20.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_valve_weight.png" darken={0} /> },
  { key: "rp_steady_knock", start: 1186.3, dur: 13.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_steady_knock.mp4" darken={0} /> },
  { key: "rp_tuned_once", start: 1199.3, dur: 12.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_tuned_once.png" darken={0} /> },
  { key: "rp_tap_well", start: 1211.2, dur: 12.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_tap_well.mp4" darken={0} /> },
  { key: "rp_town_water", start: 1223, dur: 12.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_town_water.mp4" darken={0} /> },
  { key: "rp_blackout_water", start: 1235.2, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_blackout_water.mp4" darken={0} /> },
  { key: "rp_dependence", start: 1243.2, dur: 13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_dependence.mp4" darken={0} /> },
  { key: "cmp_quote", start: 1255.7, dur: 3.9, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_bg.png" words={parseQuote("Nothing burned. Nothing bought. *Nothing to break*.")} accent="cold" hue="cold" fontSize={90} /> },
  { key: "cmp_weekend", start: 1284.3, dur: 12.2, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Find falling water"},{"title":"Sketch source → pump → tank"},{"title":"Build it & tune the knock"}]} eyebrow="Build a small one first" title="Your weekend" accent="good" hue="amber" /> },
  { key: "rp_creek_ditch", start: 1296.5, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_creek_ditch.mp4" darken={0} /> },
  { key: "rp_picture_pump", start: 1304.7, dur: 12.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_picture_pump.mp4" darken={0} /> },
  { key: "rp_buy_valves", start: 1316.7, dur: 8.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_buy_valves.mp4" darken={0} /> },
  { key: "rp_build_set", start: 1325.1, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_build_set.mp4" darken={0} /> },
  { key: "rp_boy_watching", start: 1333.3, dur: 12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rp_boy_watching.png" darken={0} /> },
  { key: "rp_laugh", start: 1344.8, dur: 8.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_laugh.mp4" darken={0} /> },
  { key: "cmp_next", start: 1380.8, dur: 8.3, kind: "nextvideo", el: (d) => <NextVideoEndcard durationInFrames={d} title="Light a whole room with one small flame" kicker="Next time" sub="No grid, no batteries — a forgotten trick that makes one candle shine like ten." /> },
  { key: "rp_candle_jar", start: 1389.1, dur: 12.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_candle_jar.mp4" darken={0} /> },
  { key: "rp_warm_home", start: 1401.3, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_warm_home.mp4" darken={0} /> },
  { key: "rp_community", start: 1405.9, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rp_community.mp4" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_34", start: 34, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} value={79} suffix=" yrs" label="still knocking" corner="TL" accent="cold" /> },
  { key: "ov_59", start: 59, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} value={30} suffix=" ft" label="straight up" corner="TR" accent="cold" /> },
  { key: "ovp_80", start: 80, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Water uphill — on its own" accent="cold" pos="bottom" /> },
  { key: "ov_86", start: 86, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} value={200} suffix=" yrs" label="old physics" corner="TL" accent="cold" /> },
  { key: "ovp_67", start: 67, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="No power · no fuel · no battery" accent="amber" pos="top" /> },
  { key: "ovp_189", start: 189, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Lifting water takes energy" accent="cold" pos="bottom" /> },
  { key: "ovd_284", start: 284, dur: 3.4, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Drive pipe" sub="water falls & speeds up" accent="cold" corner="BL" /> },
  { key: "ovd_297", start: 297, dur: 3.4, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Waste valve" sub="open at rest" accent="cold" corner="BL" /> },
  { key: "ovp_325", start: 325, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="It slams shut" accent="danger" pos="bottom" /> },
  { key: "ovp_349", start: 349, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Water hammer" accent="danger" pos="bottom" /> },
  { key: "ovd_365", start: 365, dur: 3.4, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Delivery valve" sub="one-way, up only" accent="cold" corner="BL" /> },
  { key: "ovd_420", start: 420, dur: 3.4, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Air chamber" sub="cushions every blow" accent="cold" corner="BL" /> },
  { key: "ov_503", start: 503, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} text="10 : 1" label="fall vs lift" corner="TR" accent="amber" /> },
  { key: "ov_548", start: 548, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} value={10} suffix="×" label="the lift" corner="TL" accent="cold" /> },
  { key: "ovy_597", start: 597, dur: 3.6, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="1947" label="still running" accent="amber" corner="TR" /> },
  { key: "ov_556", start: 556, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} value={3} suffix=" ft" label="drop is plenty" corner="TR" accent="cold" /> },
  { key: "ovy_705", start: 705, dur: 3.6, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="1796" label="perfected in France" accent="amber" corner="TR" /> },
  { key: "ovp_744", start: 744, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="No money in a pump that lasts 100 years" accent="amber" pos="bottom" /> },
  { key: "ov_796", start: 796, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} text="3 ft" label="minimum drop" corner="TR" accent="amber" /> },
  { key: "ov_880", start: 880, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} text="5–10×" label="drive pipe vs fall" corner="TL" accent="amber" /> },
  { key: "ov_971", start: 971, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} text="$1000+" label="just to install electric" corner="TR" accent="amber" /> },
  { key: "ovp_1146", start: 1146, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Rigid drive pipe — always" accent="danger" pos="bottom" /> },
  { key: "ovp_1186", start: 1186, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="A steady knock, once a second" accent="cold" pos="bottom" /> },
  { key: "ovp_1239", start: 1239, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Power out = water out" accent="danger" pos="top" /> },
  { key: "ovp_1316", start: 1316, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Build it once. Free forever." accent="cold" pos="bottom" /> },
];
