// cues_aceite.gen.tsx — GENERADO por beatsheet.mjs desde aceite.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/aceite.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { PremiumOverlay } from "./scenes/PremiumOverlay";
import { BigStatReveal, BeforeAfter, MythTruth, PullQuote, ChecklistReveal, HighlightSweep, VsDuel, CtaCard, NumberedSteps, THEME_EARTH } from "./kit/premium";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "ace_s_001", start: 0.14, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_001.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_001_b", start: 2.77, dur: 4.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_001_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_002", start: 7.22, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_002.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_002_b", start: 9.88, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_002_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_003", start: 13.78, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_003.png" hue="amber" darken={0} /> },
  { key: "ace_s_003_b", start: 16.65, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_003_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_004", start: 19.48, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_004.png" hue="amber" darken={0} /> },
  { key: "ace_s_004_b", start: 22.23, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_004_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_005", start: 26.52, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_005.mp4" hue="amber" darken={0} clipDur={8.03} /> },
  { key: "ace_s_005_b", start: 29.17, dur: 4.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_005_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_006", start: 33.22, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_006.png" hue="amber" darken={0} /> },
  { key: "ace_s_006_b", start: 36.1, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_006_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_007", start: 40.32, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_007.png" hue="amber" darken={0} /> },
  { key: "ace_s_007_b", start: 42.94, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_007_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_008", start: 47.2, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_008.png" hue="amber" darken={0} /> },
  { key: "ace_s_008_b", start: 50.15, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_008_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_009", start: 53.62, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_009.mp4" hue="amber" darken={0} clipDur={8} /> },
  { key: "ace_s_009_b", start: 56.52, dur: 4.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_009_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_010", start: 60.67, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_010.mp4" hue="amber" darken={0} clipDur={5.1} /> },
  { key: "ace_s_010_b", start: 63.46, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_010_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_010_c", start: 66.3, dur: 2.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_010_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_011", start: 68.18, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_011.mp4" hue="amber" darken={0} clipDur={7.57} /> },
  { key: "ace_s_011_b", start: 71.16, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_011_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_012", start: 74.64, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_012.png" hue="amber" darken={0} /> },
  { key: "ace_s_012_b", start: 77.34, dur: 4.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_012_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_013", start: 81.15, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_013.png" hue="amber" darken={0} /> },
  { key: "ace_s_013_b", start: 83.86, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_013_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_014", start: 88.15, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_014.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_014_b", start: 90.82, dur: 2.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_014_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_015", start: 93.24, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_015.png" hue="amber" darken={0} /> },
  { key: "ace_s_015_b", start: 96.19, dur: 2.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_015_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_016", start: 98.52, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_016.png" hue="amber" darken={0} /> },
  { key: "ace_s_016_b", start: 101.66, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_016_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_017", start: 104.66, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_017.png" hue="amber" darken={0} /> },
  { key: "ace_s_017_b", start: 107.46, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_017_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_018", start: 109.76, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_018.png" hue="amber" darken={0} /> },
  { key: "ace_s_018_b", start: 112.44, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_018_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_019", start: 115.94, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_019.png" hue="amber" darken={0} /> },
  { key: "ace_s_019_b", start: 118.58, dur: 4.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_019_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_020", start: 122.95, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_020.mp4" hue="amber" darken={0} clipDur={6.5} /> },
  { key: "ace_s_020_b", start: 125.62, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_020_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_020_c", start: 128.52, dur: 2.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_020_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_021", start: 130.45, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_021.mp4" hue="amber" darken={0} clipDur={8} /> },
  { key: "ace_s_021_b", start: 133.52, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_021_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_022", start: 135.62, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_022.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_022_b", start: 138.25, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_022_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_023", start: 141.84, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_023.png" hue="amber" darken={0} /> },
  { key: "ace_s_023_b", start: 145.15, dur: 2.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_023_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_024", start: 147.6, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_024.mp4" hue="amber" darken={0} clipDur={8} /> },
  { key: "ace_s_024_b", start: 150.27, dur: 4.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_024_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_025", start: 154.6, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_025.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_025_b", start: 157.66, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_025_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_026", start: 161.72, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_026.png" hue="amber" darken={0} /> },
  { key: "ace_s_026_b", start: 164.44, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_026_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_027", start: 167.98, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_027.png" hue="amber" darken={0} /> },
  { key: "ace_s_027_b", start: 170.78, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_027_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_028", start: 174.36, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_028.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_028_b", start: 177.12, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_028_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_029", start: 181.56, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_029.mp4" hue="amber" darken={0} clipDur={8.03} /> },
  { key: "ace_s_029_b", start: 184.31, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_029_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_030", start: 187.44, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_030.png" hue="amber" darken={0} /> },
  { key: "ace_s_030_b", start: 190.11, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_030_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_031", start: 194.36, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_031.mp4" hue="amber" darken={0} clipDur={5.2} /> },
  { key: "ace_s_031_b", start: 196.99, dur: 4.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_031_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_032", start: 201.38, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_032.mp4" hue="amber" darken={0} clipDur={3.87} /> },
  { key: "ace_s_032_b", start: 204.25, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_032_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_033", start: 207.4, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_033.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_033_b", start: 210.32, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_033_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_034", start: 212.47, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_034.mp4" hue="amber" darken={0} clipDur={8} /> },
  { key: "ace_s_034_b", start: 215.08, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_034_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_035", start: 219.52, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_035.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_035_b", start: 222.7, dur: 4.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_035_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_036", start: 226.71, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_036.png" hue="amber" darken={0} /> },
  { key: "ace_s_036_b", start: 229.4, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_036_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_037", start: 232.4, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_037.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_037_b", start: 235.15, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_037_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_037_c", start: 237.84, dur: 2.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_037_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_038", start: 240.29, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_038.png" hue="amber" darken={0} /> },
  { key: "ace_s_038_b", start: 242.94, dur: 4.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_038_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_039", start: 246.97, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_039.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_039_b", start: 250.24, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_039_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_040", start: 253.67, dur: 3.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_040.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_040_b", start: 256.96, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_040_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_041", start: 260.98, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_041.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_041_b", start: 263.98, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_041_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_042", start: 266.96, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_042.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_042_b", start: 269.6, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_042_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_042_c", start: 272.44, dur: 2.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_042_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_043", start: 274.21, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_043.png" hue="amber" darken={0} /> },
  { key: "ace_s_043_b", start: 277.76, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_043_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_044", start: 280.72, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_044.mp4" hue="amber" darken={0} clipDur={6.27} /> },
  { key: "ace_s_044_b", start: 283.61, dur: 4.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_044_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_045", start: 288.24, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_045.png" hue="amber" darken={0} /> },
  { key: "ace_s_045_b", start: 291.01, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_045_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_046", start: 293.79, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_046.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_046_b", start: 296.48, dur: 4.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_046_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_047", start: 300.27, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_047.png" hue="amber" darken={0} /> },
  { key: "ace_s_047_b", start: 303.27, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_047_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_048", start: 307.37, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_048.mp4" hue="amber" darken={0} clipDur={4.9} /> },
  { key: "ace_s_048_b", start: 310.12, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_048_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_049", start: 314.66, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_049.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_049_b", start: 318.08, dur: 2.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_049_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_050", start: 319.96, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_050.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_050_b", start: 322.85, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_050_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_051", start: 325.09, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_051.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_051_b", start: 327.75, dur: 4.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_051_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_052", start: 332.16, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_052.mp4" hue="amber" darken={0} clipDur={6.37} /> },
  { key: "ace_s_052_b", start: 335.1, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_052_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_053", start: 339.2, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_053.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_053_b", start: 341.88, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_053_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_054", start: 344.22, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_054.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_054_b", start: 346.85, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_054_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_055", start: 349.68, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_055.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_055_b", start: 352.45, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_055_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_056", start: 355.8, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_056.mp4" hue="amber" darken={0} clipDur={7.6} /> },
  { key: "ace_s_056_b", start: 358.56, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_056_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_057", start: 362.85, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_057.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_057_b", start: 365.47, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_057_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_058", start: 370.05, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_058.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_058_b", start: 372.88, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_058_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_059", start: 377.05, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_059.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_059_b", start: 379.8, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_059_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_060", start: 383.28, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_060.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_060_b", start: 386.56, dur: 4.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_060_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_061", start: 390.79, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_061.png" hue="amber" darken={0} /> },
  { key: "ace_s_061_b", start: 393.56, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_061_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_062", start: 397.86, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_062.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_062_b", start: 400.52, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_062_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_063", start: 403.22, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_063.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_063_b", start: 405.88, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_063_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_063_c", start: 408.68, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_063_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_064", start: 411, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_064.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_064_b", start: 414.1, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_064_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_065", start: 416.4, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_065.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_065_b", start: 419, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_065_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_066", start: 422.63, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_066.mp4" hue="amber" darken={0} clipDur={7.4} /> },
  { key: "ace_s_066_b", start: 425.27, dur: 4.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_066_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_067", start: 429.8, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_067.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_067_b", start: 432.55, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_067_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_068", start: 435.4, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_068.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_068_b", start: 438.08, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_068_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_069", start: 440.77, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_069.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_069_b", start: 443.63, dur: 4.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_069_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_070", start: 448.12, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_070.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_070_b", start: 451.04, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_070_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_071", start: 455.16, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_071.png" hue="amber" darken={0} /> },
  { key: "ace_s_071_b", start: 457.83, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_071_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_071_c", start: 460.62, dur: 2.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_071_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_072", start: 462.71, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_072.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_072_b", start: 465.4, dur: 4.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_072_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_073", start: 470.09, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_073.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_073_b", start: 472.79, dur: 4.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_073_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_074", start: 477.2, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_074.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_074_b", start: 479.98, dur: 2.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_074_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_075", start: 482.53, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_075.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_075_b", start: 485.31, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_075_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_076", start: 489.53, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_076.mp4" hue="amber" darken={0} clipDur={5.47} /> },
  { key: "ace_s_076_b", start: 492.32, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_076_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_077", start: 496.68, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_077.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_077_b", start: 499.56, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_077_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_078", start: 503.74, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_078.png" hue="amber" darken={0} /> },
  { key: "ace_s_078_b", start: 506.68, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_078_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_079", start: 510.53, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_079.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_079_b", start: 513.22, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_079_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_080", start: 516.62, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_080.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_080_b", start: 519.4, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_080_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_080_c", start: 522.04, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_080_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_081", start: 524.14, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_081.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_081_b", start: 527.38, dur: 4.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_081_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_082", start: 531.17, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_082.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_082_b", start: 533.84, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_082_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_083", start: 536.88, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_083.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_083_b", start: 539.48, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_083_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_083_c", start: 542.33, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_083_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_084", start: 544.12, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_084.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_084_b", start: 546.92, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_084_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_085", start: 551.38, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_085.png" hue="amber" darken={0} /> },
  { key: "ace_s_085_b", start: 554.18, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_085_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_086", start: 558.47, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_086.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_086_b", start: 561.51, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_086_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_086_c", start: 564.31, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_086_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_087", start: 566.16, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_087.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_087_b", start: 568.85, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_087_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_088", start: 572.05, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_088.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_088_b", start: 575.04, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_088_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_089", start: 578.41, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_089.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_089_b", start: 581.35, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_089_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_089_c", start: 584.06, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_089_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_090", start: 585.8, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_090.mp4" hue="amber" darken={0} clipDur={6.93} /> },
  { key: "ace_s_090_b", start: 588.46, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_090_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_090_c", start: 591.18, dur: 2.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_090_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_091", start: 593.07, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_091.png" hue="amber" darken={0} /> },
  { key: "ace_s_091_b", start: 596.21, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_091_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_092", start: 598.36, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_092.png" hue="amber" darken={0} /> },
  { key: "ace_s_092_b", start: 601.05, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_092_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_092_c", start: 603.89, dur: 2.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_092_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_093", start: 605.64, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_093.png" hue="amber" darken={0} /> },
  { key: "ace_s_093_b", start: 608.28, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_093_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_093_c", start: 610.96, dur: 2.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_093_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_094", start: 612.8, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_094.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_094_b", start: 615.47, dur: 4.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_094_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_095", start: 619.88, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_095.png" hue="amber" darken={0} /> },
  { key: "ace_s_095_b", start: 622.52, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_095_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_096", start: 624.88, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_096.png" hue="amber" darken={0} /> },
  { key: "ace_s_096_b", start: 627.62, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_096_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_097", start: 632.02, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_097.png" hue="amber" darken={0} /> },
  { key: "ace_s_097_b", start: 634.77, dur: 4.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_097_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_098", start: 639.04, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_098.png" hue="amber" darken={0} /> },
  { key: "ace_s_098_b", start: 641.82, dur: 4.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_098_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_099", start: 646.09, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_099.png" hue="amber" darken={0} /> },
  { key: "ace_s_099_b", start: 648.76, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_099_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_099_c", start: 651.79, dur: 2.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_099_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_100", start: 653.66, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_100.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_100_b", start: 656.37, dur: 2.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_100_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_101", start: 658.8, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_101.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_101_b", start: 661.4, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_101_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_102", start: 664.28, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_102.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_102_b", start: 666.98, dur: 4.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_102_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_103", start: 671.29, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_103.mp4" hue="amber" darken={0} clipDur={7} /> },
  { key: "ace_s_103_b", start: 674.16, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_103_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_103_c", start: 677.22, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_103_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_104", start: 679.2, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_104.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_104_b", start: 682.15, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_104_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_104_c", start: 684.79, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_104_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_105", start: 686.58, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_105.png" hue="amber" darken={0} /> },
  { key: "ace_s_105_b", start: 689.18, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_105_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_105_c", start: 691.93, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_105_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_106", start: 693.95, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_106.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_106_b", start: 696.74, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_106_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_107", start: 700.86, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_107.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_107_b", start: 703.81, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_107_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_108", start: 708.03, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_108.png" hue="amber" darken={0} /> },
  { key: "ace_s_108_b", start: 711.1, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_108_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_108_c", start: 713.8, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_108_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_109", start: 716.04, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_109.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_109_b", start: 718.68, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_109_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_110", start: 721.02, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_110.mp4" hue="amber" darken={0} clipDur={3.03} /> },
  { key: "ace_s_110_b", start: 723.9, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_110_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_111", start: 728.4, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_111.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_111_b", start: 731.42, dur: 4.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_111_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_112", start: 735.46, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_112.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_112_b", start: 738.28, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_112_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_112_c", start: 740.92, dur: 2.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_112_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_113", start: 742.86, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_113.png" hue="amber" darken={0} /> },
  { key: "ace_s_113_b", start: 745.5, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_113_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_113_c", start: 748.33, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_113_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_114", start: 750.07, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_114.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_114_b", start: 752.88, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_114_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_115", start: 757.13, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_115.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_115_b", start: 759.86, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_115_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_116", start: 764.42, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_116.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_116_b", start: 767.25, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_116_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_117", start: 770.46, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_117.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_117_b", start: 773.4, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_117_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_118", start: 776.48, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_118.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_118_b", start: 779.26, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_118_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_119", start: 783.6, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_119.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_119_b", start: 786.64, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_119_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_120", start: 790.84, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_120.png" hue="amber" darken={0} /> },
  { key: "ace_s_120_b", start: 793.49, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_120_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_120_c", start: 796.16, dur: 2.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_120_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_121", start: 797.98, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_121.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_121_b", start: 800.82, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_121_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_122", start: 804.58, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_122.png" hue="amber" darken={0} /> },
  { key: "ace_s_122_b", start: 807.5, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_122_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_123", start: 811.82, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_123.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_123_b", start: 814.46, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_123_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_123_c", start: 817.28, dur: 2.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_123_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_124", start: 819.21, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_124.mp4" hue="amber" darken={0} clipDur={6.77} /> },
  { key: "ace_s_124_b", start: 822.05, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_124_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_125", start: 824.7, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_125.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_125_b", start: 827.6, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_125_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_126", start: 831.7, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_126.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_126_b", start: 834.46, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_126_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_127", start: 838.84, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_127.png" hue="amber" darken={0} /> },
  { key: "ace_s_127_b", start: 841.77, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_127_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_128", start: 843.95, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_128.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_128_b", start: 846.75, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_128_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_128_c", start: 849.51, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_128_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_129", start: 851.31, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_129.png" hue="amber" darken={0} /> },
  { key: "ace_s_129_b", start: 853.93, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_129_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_130", start: 856.56, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_130.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_130_b", start: 859.42, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_130_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_131", start: 863.56, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_131.png" hue="amber" darken={0} /> },
  { key: "ace_s_131_b", start: 866.18, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_131_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_131_c", start: 868.85, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_131_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_132", start: 870.59, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_132.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_132_b", start: 873.54, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_132_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_133", start: 875.98, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_133.png" hue="amber" darken={0} /> },
  { key: "ace_s_133_b", start: 878.62, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_133_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_134", start: 882.18, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_134.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_134_b", start: 884.78, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_134_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_134_c", start: 887.5, dur: 2.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_134_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_135", start: 889.43, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_135.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_135_b", start: 892.29, dur: 2.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_135_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_136", start: 894.35, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_136.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_136_b", start: 897, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_136_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_136_c", start: 899.68, dur: 2.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_136_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_137", start: 901.54, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_137.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_137_b", start: 904.25, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_137_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_137_c", start: 906.88, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_137_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_138", start: 909.42, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_138.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_138_b", start: 912.17, dur: 4.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_138_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_139", start: 916.44, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_139.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_139_b", start: 919.42, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_139_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_140", start: 921.66, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_140.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_140_b", start: 924.26, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_140_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_141", start: 928.18, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_141.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_141_b", start: 930.98, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_141_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_141_c", start: 933.71, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_141_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_142", start: 935.41, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_142.png" hue="amber" darken={0} /> },
  { key: "ace_s_142_b", start: 938.07, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_142_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_142_c", start: 940.79, dur: 2.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_142_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_143", start: 942.56, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_143.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_143_b", start: 945.24, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_143_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_144", start: 948.29, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_144.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_144_b", start: 951, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_144_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_145", start: 955.3, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_145.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_145_b", start: 958.21, dur: 4.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_145_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_146", start: 962.18, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_146.mp4" hue="amber" darken={0} clipDur={8} /> },
  { key: "ace_s_146_b", start: 965.06, dur: 4.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_146_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_147", start: 969.43, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_147.mp4" hue="amber" darken={0} clipDur={7.93} /> },
  { key: "ace_s_147_b", start: 972.75, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_147_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_148", start: 976.61, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_148.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_148_b", start: 979.28, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_148_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_148_c", start: 981.91, dur: 2.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_148_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_149", start: 983.69, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_149.png" hue="amber" darken={0} /> },
  { key: "ace_s_149_b", start: 986.41, dur: 2.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_149_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_150", start: 988.92, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_150.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_150_b", start: 992.64, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_150_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_151", start: 995.96, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_151.png" hue="amber" darken={0} /> },
  { key: "ace_s_151_b", start: 998.56, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_151_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_151_c", start: 1001.32, dur: 2.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_151_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_152", start: 1003.14, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_152.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_152_b", start: 1005.82, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_152_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_152_c", start: 1008.57, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_152_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_153", start: 1010.52, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_153.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_153_b", start: 1013.28, dur: 3.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_153_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_154", start: 1016.89, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_154.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_154_b", start: 1019.91, dur: 3.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_154_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_155", start: 1022.88, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_155.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_155_b", start: 1025.63, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_155_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_156", start: 1029.99, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_156.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_156_b", start: 1032.74, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_156_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_157", start: 1036.5, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_157.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_157_b", start: 1039.12, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_157_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_157_c", start: 1041.73, dur: 2.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_157_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_158", start: 1043.98, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_158.mp4" hue="amber" darken={0} clipDur={7} /> },
  { key: "ace_s_158_b", start: 1047.09, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_158_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_159", start: 1051.17, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_159.mp4" hue="amber" darken={0} clipDur={5} /> },
  { key: "ace_s_159_b", start: 1054.04, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_159_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_159_c", start: 1056.66, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_159_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_160", start: 1058.51, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_160.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_160_b", start: 1061.22, dur: 4.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_160_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_161", start: 1065.41, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_161.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_161_b", start: 1068.35, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_161_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_162", start: 1072.53, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_162.png" hue="amber" darken={0} /> },
  { key: "ace_s_162_b", start: 1075.4, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_162_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_163", start: 1079.66, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_163.png" hue="amber" darken={0} /> },
  { key: "ace_s_163_b", start: 1083.07, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_163_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_164", start: 1086.24, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_164.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_164_b", start: 1089.19, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_164_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_165", start: 1092.85, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_165.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_165_b", start: 1095.71, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_165_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_166", start: 1098.27, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_166.png" hue="amber" darken={0} /> },
  { key: "ace_s_166_b", start: 1100.99, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_166_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_166_c", start: 1103.73, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_166_c.png" hue="amber" darken={0} /> },
  { key: "ace_s_167", start: 1105.75, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_167.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_167_b", start: 1108.95, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_167_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_168", start: 1112.58, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_168.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_168_b", start: 1115.52, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_168_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_169", start: 1118.68, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_169.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_169_b", start: 1121.62, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_169_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_170", start: 1125.06, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_170.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_170_b", start: 1128.36, dur: 2.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_170_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_171", start: 1130.45, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_171.mp4" hue="amber" darken={0} clipDur={8} /> },
  { key: "ace_s_171_b", start: 1133.58, dur: 4.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_171_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_172", start: 1137.63, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_172.mp4" hue="amber" darken={0} clipDur={8.03} /> },
  { key: "ace_s_172_b", start: 1140.56, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_172_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_173", start: 1143.98, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_173.png" hue="amber" darken={0} /> },
  { key: "ace_s_173_b", start: 1146.79, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_173_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_174", start: 1150.02, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_174.png" hue="amber" darken={0} /> },
  { key: "ace_s_174_b", start: 1152.72, dur: 4.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_174_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_175", start: 1157.09, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_175.png" hue="amber" darken={0} /> },
  { key: "ace_s_175_b", start: 1160.6, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_175_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_176", start: 1164.11, dur: 3.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_176.png" hue="amber" darken={0} /> },
  { key: "ace_s_176_b", start: 1167.2, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_176_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_177", start: 1170.72, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_177.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_177_b", start: 1173.6, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_177_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_178", start: 1176.84, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_178.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_178_b", start: 1179.72, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_178_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_179", start: 1182.51, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ace_s_179.mp4" hue="amber" darken={0} clipDur={8.07} /> },
  { key: "ace_s_179_b", start: 1185.2, dur: 4.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_179_b.png" hue="amber" darken={0} /> },
  { key: "ace_s_180", start: 1189.69, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_180.png" hue="amber" darken={0} /> },
  { key: "ace_s_180_b", start: 1192.36, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ace_s_180_b.png" hue="amber" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_bigstatreveal_14", start: 13.78, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El carpintero de la historia","value":74,"prefix":"","suffix":" años","support":"Don Ernesto — 40 años de oficio, un galpón que él mismo levantó tabla por tabla"} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_61", start: 60.67, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El engaño de la humedad","beforeLabel":"Por fuera: sano","afterLabel":"Por dentro: podrido y negro","caption":"trabaja callada, adentro, donde no la ves"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_82", start: 82.37, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Esta madera ya no tiene arreglo, hay que demoler y hacer todo nuevo","truth":"Con un tarro de aceite y una tarde, esa madera queda más sana que la nueva"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_107", start: 107.12, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Esta madera la levantó mi viejo con las manos. La humedad no me la va a ganar a mí."} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_174", start: 174.36, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El secreto que salvó el galpón","value":100,"prefix":"","suffix":" años","support":"un líquido que cuesta casi nada y hace durar la madera un siglo"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_210", start: 210.32, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"La madera se pudre porque es vieja / por el paso del tiempo","truth":"La edad no la pudre: la pudren el agua, los hongos y los insectos"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_216", start: 215.8, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La madera no muere por vieja","value":800,"prefix":"","suffix":" años","support":"iglesias de madera en Noruega, intactas — la edad no pudre la madera"} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_229", start: 229.4, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Lo único que pudre la madera","items":["El agua (la madre de todas)","Los hongos","Los insectos / termitas"],"stamp":"SACÁ ESAS 3 = MADERA ETERNA"} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_240", start: 240.34, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"De los tres enemigos, la madre de todas es","highlight":"el agua","post":" — es la que llama a los hongos y los insectos.","note":"sacá el agua y la madera es casi eterna"} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_247", start: 246.97, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"La madera es","highlight":"una esponja llena de tubitos","post":" que antes llevaban la savia; el agua entra por ahí.","note":"por eso hay que taparlos"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_328", start: 328.41, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"El sellador de película pone una capa impermeable que protege","truth":"Se agrieta, el agua entra y queda atrapada abajo — pudre más rápido"} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_337", start: 336.64, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El sellador de película, afuera","beforeLabel":"Recién puesto","afterLabel":"Agrietado, atrapa el agua","caption":"el sol lo castiga y la madera se mueve"} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_367", start: 366.84, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Dos filosofías opuestas","title":"Tapar vs. alimentar","left":{"label":"Sellador (película)","sub":"capa de plástico arriba; se agrieta y atrapa el agua","good":false},"right":{"label":"Aceite (penetrante)","sub":"se mete adentro, flexible, no se pela","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_383", start: 383.28, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"La protección de la madera","highlight":"no se pone encima, se mete adentro","post":".","note":"el corazón de todo"} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_430", start: 429.8, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El líquido: dos versiones","title":"Motor usado vs. linaza noble","left":{"label":"Aceite de motor usado","sub":"gratis e imbatible, pero sucio/tóxico — solo enterrado","good":false},"right":{"label":"Mezcla de linaza","sub":"no tóxica, huele bien, protege igual — para todo","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_459", start: 459.2, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"El aceite de motor usado penetra profundo y","highlight":"repele el agua como pocas cosas","post":" — y es gratis.","note":"solo para lo enterrado"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_471", start: 470.64, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Un poste enterrado, con aceite de motor","value":100,"prefix":"","suffix":" años","support":"gratis, porque es un desecho — por eso ningún corralón te lo recomienda"} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_568", start: 568.33, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"La mezcla noble (la fórmula)","items":["Aceite de linaza (el alma, penetra y alimenta)","Un solvente (aguarrás/trementina, lleva el aceite al fondo)","Un refuerzo (brea de pino o cera de abeja)"],"stamp":"PROPORCIONES EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_630", start: 629.59, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"40 arreglos y secretos de los viejos","title":"Manual del Constructor Libre","bullet":"madera, óxido, humedad, plagas, caños — con medidas exactas","price":0,"cta":"LINK EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_770", start: 770.46, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Paso 1 de 4","title":"Cómo aplicarlo (lo que casi nadie hace)","steps":[{"title":"Madera bien seca","sub":"sobre húmeda sellás el agua adentro — el error #1"}]} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_773", start: 773.4, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Apurar y aplicar el aceite sobre madera húmeda o recién lavada","truth":"Sobre húmeda sellás el agua adentro y la condenás: seca, siempre"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_819", start: 819.21, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Paso 2 de 4","title":"Cómo aplicarlo (lo que casi nadie hace)","steps":[{"title":"Madera bien seca","sub":"sobre húmeda sellás el agua adentro — el error #1"},{"title":"Limpia y sin capa gris","sub":"sacá la fibra muerta o el aceite no penetra"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_855", start: 855.14, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Paso 3 de 4","title":"Cómo aplicarlo (lo que casi nadie hace)","steps":[{"title":"Madera bien seca","sub":"sobre húmeda sellás el agua adentro — el error #1"},{"title":"Limpia y sin capa gris","sub":"sacá la fibra muerta o el aceite no penetra"},{"title":"Aceite generoso, saturando","sub":"2-3 manos en el sentido de la veta, hasta que no absorba"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_895", start: 895.49, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Paso 4 de 4","title":"Cómo aplicarlo (lo que casi nadie hace)","steps":[{"title":"Madera bien seca","sub":"sobre húmeda sellás el agua adentro — el error #1"},{"title":"Limpia y sin capa gris","sub":"sacá la fibra muerta o el aceite no penetra"},{"title":"Aceite generoso, saturando","sub":"2-3 manos en el sentido de la veta, hasta que no absorba"},{"title":"Sacá el excedente","sub":"a los 10-15 min pasá un trapo; después, secar"}]} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_950", start: 950.06, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El mantenimiento del aceite","value":10,"prefix":"","suffix":" min","support":"una manito cada tanto, sin lijar — contra el infierno de lijar y repintar cada 2 años"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_957", start: 957.34, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Los viejos no eran atrasados. Eran más inteligentes que nosotros."} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_962", start: 962.18, dur: 7.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Todo lo que podés salvar","items":["Postes y bases enterradas (motor usado)","Deck, galería y pérgola (linaza)","Muebles de interior y exterior (linaza + cera)","Mangos de herramientas (hacha, pala, martillo)"],"stamp":"MISMO PRINCIPIO"} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_1011", start: 1011.37, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El deck con la mezcla de linaza","beforeLabel":"Gris y áspero","afterLabel":"Con color, repele el agua","caption":"el agua hace perlitas arriba de la madera"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_1078", start: 1078.32, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Cuesta menos que una visita al corralón","title":"Manual de Reparaciones Caseras","bullet":"40 soluciones caseras, con medidas y pasos, para cuando las necesites","price":0,"cta":"LINK ARRIBA DE TODO"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_1084", start: 1083.98, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Manual de reparaciones caseras","value":40,"prefix":"","suffix":"","support":"arreglos como este, con medidas y pasos, para cuando los necesites"} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_1093", start: 1092.85, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Lo que cubre el manual completo","items":["Madera","Óxido","Humedad y goteras","Plagas","Caños","Hasta cosas del auto"],"stamp":"40 ARREGLOS"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_1113", start: 1113.09, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Para llevarte lo importante","title":"El resumen","steps":[{"title":"No se pudre por vieja, se pudre por el agua"},{"title":"La protección se mete adentro, no encima"},{"title":"El error que mata: aplicarla húmeda"},{"title":"El mejor protector es el más barato: aceite"}]} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_1150", start: 1150.02, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Empezá por el enlace de arriba","title":"Manual del Constructor Libre","bullet":"los 40 arreglos completos + la fórmula de hoy, numerada","price":0,"cta":"LINK EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_1171", start: 1170.72, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"En el próximo video:","highlight":"quemar la madera para que dure 80 años","post":", sin pintura ni un solo químico.","note":"shou sugi ban — no te lo pierdas"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_1188", start: 1187.66, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"No dejes que nadie te haga tirar lo que todavía tiene vida."} as any)} /></PremiumOverlay> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":13.78,"role":"popUp","vol":0.32},{"at":60.67,"role":"popUp","vol":0.32},{"at":82.37,"role":"popUp","vol":0.32},{"at":107.12,"role":"popUp","vol":0.32},{"at":174.36,"role":"popUp","vol":0.32},{"at":210.32,"role":"popUp","vol":0.32},{"at":215.8,"role":"popUp","vol":0.32},{"at":229.4,"role":"popUp","vol":0.32},{"at":240.34,"role":"popUp","vol":0.32},{"at":246.97,"role":"popUp","vol":0.32},{"at":328.41,"role":"popUp","vol":0.32},{"at":336.64,"role":"popUp","vol":0.32},{"at":366.84,"role":"popUp","vol":0.32},{"at":383.28,"role":"popUp","vol":0.32},{"at":429.8,"role":"popUp","vol":0.32},{"at":459.2,"role":"popUp","vol":0.32},{"at":470.64,"role":"popUp","vol":0.32},{"at":568.33,"role":"popUp","vol":0.32},{"at":629.59,"role":"popUp","vol":0.32},{"at":770.46,"role":"popUp","vol":0.32},{"at":773.4,"role":"popUp","vol":0.32},{"at":819.21,"role":"popUp","vol":0.32},{"at":855.14,"role":"popUp","vol":0.32},{"at":895.49,"role":"popUp","vol":0.32},{"at":950.06,"role":"popUp","vol":0.32},{"at":957.34,"role":"popUp","vol":0.32},{"at":962.18,"role":"popUp","vol":0.32},{"at":1011.37,"role":"popUp","vol":0.32},{"at":1078.32,"role":"popUp","vol":0.32},{"at":1083.98,"role":"popUp","vol":0.32},{"at":1092.85,"role":"popUp","vol":0.32},{"at":1113.09,"role":"popUp","vol":0.32},{"at":1150.02,"role":"popUp","vol":0.32},{"at":1170.72,"role":"popUp","vol":0.32},{"at":1187.66,"role":"popUp","vol":0.32}];
