// cues_ciudades.gen.tsx — GENERADO por beatsheet.mjs desde ciudades.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/ciudades.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { StatBig } from "./scenes/StatBig";
import { SagaTimeline } from "./scenes/SagaTimeline";
import { KineticHeadline } from "./scenes/KineticHeadline";
import { RuleNumberScene } from "./scenes/RuleNumberScene";
import { ScaleColossus } from "./setpieces/ScaleColossus";
import { DocLabel } from "./overlays/DocLabel";
import { DateStamp } from "./overlays/DateStamp";
import { CountRail } from "./overlays/CountRail";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "c001", start: 0, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_ciudades.mp4" hue="cold" /> },
  { key: "c002", start: 3.61, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_mercados.mp4" hue="cold" /> },
  { key: "c003", start: 7.22, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_hundieron.mp4" hue="cold" /> },
  { key: "c004", start: 10.83, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_bajando.mp4" hue="cold" /> },
  { key: "c005", start: 14.44, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_fondo.mp4" hue="cold" /> },
  { key: "c006", start: 18.05, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_leyendas.mp4" hue="cold" /> },
  { key: "c007", start: 21.66, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_buzos.mp4" hue="cold" /> },
  { key: "c008", start: 25.27, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_calles_lodo.mp4" hue="cold" /> },
  { key: "c009", start: 28.88, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_pregunta.mp4" hue="cold" /> },
  { key: "c010", start: 32.49, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_como_posible.mp4" hue="cold" /> },
  { key: "c011", start: 36.1, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_bajar.mp4" hue="cold" /> },
  { key: "c012", start: 39.71, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_siete.mp4" hue="cold" /> },
  { key: "c013", start: 43.33, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_planeta.mp4" hue="cold" /> },
  { key: "c014", start: 46.94, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_guia.mp4" hue="cold" /> },
  { key: "c015", start: 50.55, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_final_teaser.mp4" hue="cold" /> },
  { key: "c016", start: 54.16, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_estructura.mp4" hue="cold" /> },
  { key: "c017", start: 57.77, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_respira.mp4" hue="cold" /> },
  { key: "c018", start: 61.38, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_nivel_mar.mp4" hue="cold" /> },
  { key: "c019", start: 64.99, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_no_siempre.mp4" hue="cold" /> },
  { key: "c020", start: 68.6, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_edad_hielo.mp4" hue="cold" /> },
  { key: "c021", start: 72.21, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_cien_metros.mp4" hue="cold" /> },
  { key: "c022", start: 75.82, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_regiones.mp4" hue="cold" /> },
  { key: "c023", start: 79.43, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_llanuras.mp4" hue="cold" /> },
  { key: "c024", start: 83.04, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_derritio.mp4" hue="cold" /> },
  { key: "headline025", start: 86.65, dur: 6, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"7","hl":true},{"t":"ciudades"},{"t":"sumergidas"},{"t":"que"},{"t":"la"},{"t":"ciencia"},{"t":"no"},{"t":"puede"},{"t":"explicar","hl":true}]} hue="blue" size={88} bg="image" image="real/ciud_hero.jpg" /> },
  { key: "c026", start: 92.65, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_ciudades.mp4" hue="cold" /> },
  { key: "c027", start: 96.3, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_mercados.mp4" hue="cold" /> },
  { key: "c028", start: 99.95, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_hundieron.mp4" hue="cold" /> },
  { key: "c029", start: 103.61, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_bajando.mp4" hue="cold" /> },
  { key: "c030", start: 107.26, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_fondo.mp4" hue="cold" /> },
  { key: "c031", start: 110.91, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_leyendas.mp4" hue="cold" /> },
  { key: "c032", start: 114.56, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_buzos.mp4" hue="cold" /> },
  { key: "c033", start: 118.22, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_calles_lodo.mp4" hue="cold" /> },
  { key: "c034", start: 121.87, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_pregunta.mp4" hue="cold" /> },
  { key: "c035", start: 125.52, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_como_posible.mp4" hue="cold" /> },
  { key: "c036", start: 129.17, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_bajar.mp4" hue="cold" /> },
  { key: "c037", start: 132.82, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_siete.mp4" hue="cold" /> },
  { key: "c038", start: 136.48, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_planeta.mp4" hue="cold" /> },
  { key: "c039", start: 140.13, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_guia.mp4" hue="cold" /> },
  { key: "c040", start: 143.78, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_final_teaser.mp4" hue="cold" /> },
  { key: "c041", start: 147.43, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_estructura.mp4" hue="cold" /> },
  { key: "c042", start: 151.08, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_respira.mp4" hue="cold" /> },
  { key: "c043", start: 154.74, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_nivel_mar.mp4" hue="cold" /> },
  { key: "c044", start: 158.39, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_no_siempre.mp4" hue="cold" /> },
  { key: "c045", start: 162.04, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_edad_hielo.mp4" hue="cold" /> },
  { key: "c046", start: 165.69, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_cien_metros.mp4" hue="cold" /> },
  { key: "c047", start: 169.35, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_regiones.mp4" hue="cold" /> },
  { key: "c048", start: 173, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_llanuras.mp4" hue="cold" /> },
  { key: "rule049", start: 176.65, dur: 4.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="07" title="Pavlopetri" label="Laconia, Grecia" hue="blue" /> },
  { key: "c052", start: 180.85, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_intro.mp4" hue="blue" /> },
  { key: "c053", start: 184.28, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_profundidad.mp4" hue="blue" /> },
  { key: "c054", start: 187.72, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_nombre.mp4" hue="blue" /> },
  { key: "c055", start: 191.15, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_no_piedras.mp4" hue="blue" /> },
  { key: "c056", start: 194.58, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_trazado.mp4" hue="blue" /> },
  { key: "c057", start: 198.02, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_calles.mp4" hue="blue" /> },
  { key: "c058", start: 201.45, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_plano.mp4" hue="blue" /> },
  { key: "c059", start: 204.89, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_edad.mp4" hue="blue" /> },
  { key: "c060", start: 208.32, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_cinco_mil.mp4" hue="blue" /> },
  { key: "scalecolossus061", start: 211.75, dur: 6, kind: "scalecolossus", el: (d) => <ScaleColossus durationInFrames={d} image="real/pv_layout.jpg" meters={4} unit="m" label="de profundidad · ciudad entera intacta" eyebrow="Pavlopetri" accent="blue" /> },
  { key: "c063", start: 217.75, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_intro.mp4" hue="blue" /> },
  { key: "c064", start: 221.31, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_profundidad.mp4" hue="blue" /> },
  { key: "c065", start: 224.87, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_nombre.mp4" hue="blue" /> },
  { key: "c066", start: 228.43, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_no_piedras.mp4" hue="blue" /> },
  { key: "c067", start: 231.98, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_trazado.mp4" hue="blue" /> },
  { key: "c068", start: 235.54, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_calles.mp4" hue="blue" /> },
  { key: "c069", start: 239.1, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_plano.mp4" hue="blue" /> },
  { key: "stat070", start: 242.66, dur: 5.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={5000} suffix=" años" label="habitada antes de las grandes pirámides" eyebrow="Edad de Bronce" accent="accent" hue="blue" /> },
  { key: "c071", start: 247.86, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_intro.mp4" hue="blue" /> },
  { key: "c072", start: 251.53, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_profundidad.mp4" hue="blue" /> },
  { key: "c073", start: 255.2, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_nombre.mp4" hue="blue" /> },
  { key: "c074", start: 258.87, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_no_piedras.mp4" hue="blue" /> },
  { key: "c075", start: 262.54, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_trazado.mp4" hue="blue" /> },
  { key: "c076", start: 266.22, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_calles.mp4" hue="blue" /> },
  { key: "c077", start: 269.89, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pv_plano.mp4" hue="blue" /> },
  { key: "rule078", start: 273.56, dur: 4.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="06" title="Port Royal" label="Jamaica, Caribe" hue="red" /> },
  { key: "c081", start: 277.76, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_intro.mp4" hue="red" /> },
  { key: "c082", start: 281.46, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_jamaica.mp4" hue="red" /> },
  { key: "c083", start: 285.16, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_nombre.mp4" hue="red" /> },
  { key: "c084", start: 288.86, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_puerto.mp4" hue="red" /> },
  { key: "c085", start: 292.57, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_malvada.mp4" hue="red" /> },
  { key: "c086", start: 296.27, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_fecha.mp4" hue="red" /> },
  { key: "c087", start: 299.97, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_rugio.mp4" hue="red" /> },
  { key: "c088", start: 303.67, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_terremoto.mp4" hue="red" /> },
  { key: "c089", start: 307.37, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_arena.mp4" hue="red" /> },
  { key: "c090", start: 311.07, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_liquido.mp4" hue="red" /> },
  { key: "scalecolossus091", start: 314.77, dur: 6, kind: "scalecolossus", el: (d) => <ScaleColossus durationInFrames={d} image="real/pr_town.jpg" meters={12} unit="m" label="bajo el agua · tragada en minutos" eyebrow="Port Royal" accent="red" /> },
  { key: "c093", start: 320.77, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_intro.mp4" hue="red" /> },
  { key: "c094", start: 324.22, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_jamaica.mp4" hue="red" /> },
  { key: "c095", start: 327.67, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_nombre.mp4" hue="red" /> },
  { key: "c096", start: 331.11, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_puerto.mp4" hue="red" /> },
  { key: "c097", start: 334.56, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_malvada.mp4" hue="red" /> },
  { key: "c098", start: 338, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_fecha.mp4" hue="red" /> },
  { key: "c099", start: 341.45, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_rugio.mp4" hue="red" /> },
  { key: "c100", start: 344.89, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_terremoto.mp4" hue="red" /> },
  { key: "c101", start: 348.34, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_arena.mp4" hue="red" /> },
  { key: "stat102", start: 351.79, dur: 5.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={2000} suffix=" muertos" label="el suelo se volvió líquido y los tragó" eyebrow="Licuefacción del terreno" accent="accent" hue="red" /> },
  { key: "c103", start: 356.99, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_intro.mp4" hue="red" /> },
  { key: "c104", start: 360.52, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_jamaica.mp4" hue="red" /> },
  { key: "c105", start: 364.06, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_nombre.mp4" hue="red" /> },
  { key: "c106", start: 367.59, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_puerto.mp4" hue="red" /> },
  { key: "c107", start: 371.13, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_malvada.mp4" hue="red" /> },
  { key: "c108", start: 374.66, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_fecha.mp4" hue="red" /> },
  { key: "c109", start: 378.2, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_rugio.mp4" hue="red" /> },
  { key: "c110", start: 381.73, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_terremoto.mp4" hue="red" /> },
  { key: "c111", start: 385.27, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pr_arena.mp4" hue="red" /> },
  { key: "rule112", start: 388.8, dur: 4.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="05" title="Baiae" label="Bahía de Nápoles, Italia" hue="blue" /> },
  { key: "c115", start: 393, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_intro.mp4" hue="blue" /> },
  { key: "c116", start: 396.82, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_lujo.mp4" hue="blue" /> },
  { key: "c117", start: 400.64, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_nombre.mp4" hue="blue" /> },
  { key: "c118", start: 404.45, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_vegas.mp4" hue="blue" /> },
  { key: "c119", start: 408.27, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_poderosos.mp4" hue="blue" /> },
  { key: "c120", start: 412.09, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_villas.mp4" hue="blue" /> },
  { key: "c121", start: 415.91, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_pecar.mp4" hue="blue" /> },
  { key: "c122", start: 419.73, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_problema.mp4" hue="blue" /> },
  { key: "scalecolossus123", start: 423.54, dur: 6, kind: "scalecolossus", el: (d) => <ScaleColossus durationInFrames={d} image="real/ba_villa.jpg" meters={6} unit="m" label="bajo el agua · villas imperiales" eyebrow="Baiae" accent="blue" /> },
  { key: "c125", start: 429.54, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_intro.mp4" hue="blue" /> },
  { key: "c126", start: 433.05, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_lujo.mp4" hue="blue" /> },
  { key: "c127", start: 436.56, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_nombre.mp4" hue="blue" /> },
  { key: "c128", start: 440.06, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_vegas.mp4" hue="blue" /> },
  { key: "c129", start: 443.57, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_poderosos.mp4" hue="blue" /> },
  { key: "c130", start: 447.07, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_villas.mp4" hue="blue" /> },
  { key: "c131", start: 450.58, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_pecar.mp4" hue="blue" /> },
  { key: "stat132", start: 454.09, dur: 5.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={0} prefix="≈" suffix=" refugio" label="ni el imperio más rico pudo salvarla" eyebrow="Hundida por el bradisismo" accent="accent" hue="blue" /> },
  { key: "c133", start: 459.29, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_intro.mp4" hue="blue" /> },
  { key: "c134", start: 462.91, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_lujo.mp4" hue="blue" /> },
  { key: "c135", start: 466.53, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_nombre.mp4" hue="blue" /> },
  { key: "c136", start: 470.15, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_vegas.mp4" hue="blue" /> },
  { key: "c137", start: 473.77, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_poderosos.mp4" hue="blue" /> },
  { key: "c138", start: 477.39, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_villas.mp4" hue="blue" /> },
  { key: "c139", start: 481.01, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ba_pecar.mp4" hue="blue" /> },
  { key: "rule140", start: 484.63, dur: 4.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="04" title="Dwarka" label="Golfo de Cambay, India" hue="amber" /> },
  { key: "c143", start: 488.83, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_intro.mp4" hue="amber" /> },
  { key: "c144", start: 492.38, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_textos.mp4" hue="amber" /> },
  { key: "c145", start: 495.93, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_nombre.mp4" hue="amber" /> },
  { key: "c146", start: 499.48, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_urbe.mp4" hue="amber" /> },
  { key: "c147", start: 503.04, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_tragada.mp4" hue="amber" /> },
  { key: "c148", start: 506.59, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_mitologia.mp4" hue="amber" /> },
  { key: "c149", start: 510.14, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_buceo.mp4" hue="amber" /> },
  { key: "c150", start: 513.69, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_encontraron.mp4" hue="amber" /> },
  { key: "c151", start: 517.24, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_estructuras.mp4" hue="amber" /> },
  { key: "scalecolossus152", start: 520.79, dur: 6, kind: "scalecolossus", el: (d) => <ScaleColossus durationInFrames={d} image="real/dw_city.jpg" meters={20} unit="m" label="bajo el agua · la ciudad de un dios" eyebrow="Dwarka" accent="amber" /> },
  { key: "c154", start: 526.79, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_intro.mp4" hue="amber" /> },
  { key: "c155", start: 530.5, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_textos.mp4" hue="amber" /> },
  { key: "c156", start: 534.21, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_nombre.mp4" hue="amber" /> },
  { key: "c157", start: 537.92, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_urbe.mp4" hue="amber" /> },
  { key: "c158", start: 541.63, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_tragada.mp4" hue="amber" /> },
  { key: "c159", start: 545.34, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_mitologia.mp4" hue="amber" /> },
  { key: "c160", start: 549.05, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_buceo.mp4" hue="amber" /> },
  { key: "stat161", start: 552.76, dur: 5.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={9000} prefix="¿" suffix=" años?" label="algunos restos llevan la zona mucho más atrás" eyebrow="La leyenda de Krishna" accent="accent" hue="amber" /> },
  { key: "c162", start: 557.96, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_intro.mp4" hue="amber" /> },
  { key: "c163", start: 561.78, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_textos.mp4" hue="amber" /> },
  { key: "c164", start: 565.6, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_nombre.mp4" hue="amber" /> },
  { key: "c165", start: 569.43, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_urbe.mp4" hue="amber" /> },
  { key: "c166", start: 573.25, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_tragada.mp4" hue="amber" /> },
  { key: "c167", start: 577.07, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_mitologia.mp4" hue="amber" /> },
  { key: "c168", start: 580.9, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/dw_buceo.mp4" hue="amber" /> },
  { key: "rule169", start: 584.72, dur: 4.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="03" title="Thonis-Heracleion" label="Bahía de Abukir, Egipto" hue="amber" /> },
  { key: "c172", start: 588.92, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_intro.mp4" hue="amber" /> },
  { key: "c173", start: 592.58, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_griegos.mp4" hue="amber" /> },
  { key: "c174", start: 596.24, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_nilo.mp4" hue="amber" /> },
  { key: "c175", start: 599.91, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_templos.mp4" hue="amber" /> },
  { key: "c176", start: 603.57, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_nombres.mp4" hue="amber" /> },
  { key: "c177", start: 607.23, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_desaparecio.mp4" hue="amber" /> },
  { key: "c178", start: 610.89, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_sombra.mp4" hue="amber" /> },
  { key: "c179", start: 614.55, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_dudaban.mp4" hue="amber" /> },
  { key: "c180", start: 618.21, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_dos_mil.mp4" hue="amber" /> },
  { key: "c181", start: 621.88, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_perdida.mp4" hue="amber" /> },
  { key: "scalecolossus182", start: 625.54, dur: 6, kind: "scalecolossus", el: (d) => <ScaleColossus durationInFrames={d} image="real/he_statue.jpg" meters={5} unit="m" label="de estatuas colosales en el fondo" eyebrow="Thonis-Heracleion" accent="amber" /> },
  { key: "c184", start: 631.54, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_intro.mp4" hue="amber" /> },
  { key: "c185", start: 634.94, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_griegos.mp4" hue="amber" /> },
  { key: "c186", start: 638.34, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_nilo.mp4" hue="amber" /> },
  { key: "c187", start: 641.74, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_templos.mp4" hue="amber" /> },
  { key: "c188", start: 645.14, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_nombres.mp4" hue="amber" /> },
  { key: "c189", start: 648.55, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_desaparecio.mp4" hue="amber" /> },
  { key: "c190", start: 651.95, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_sombra.mp4" hue="amber" /> },
  { key: "c191", start: 655.35, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_dudaban.mp4" hue="amber" /> },
  { key: "c192", start: 658.75, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_dos_mil.mp4" hue="amber" /> },
  { key: "stat193", start: 662.15, dur: 5.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={64} suffix=" barcos" label="hundidos junto a la ciudad que se creía un mito" eyebrow="Una metrópolis entera" accent="danger" hue="amber" /> },
  { key: "c194", start: 667.35, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_intro.mp4" hue="amber" /> },
  { key: "c195", start: 670.84, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_griegos.mp4" hue="amber" /> },
  { key: "c196", start: 674.33, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_nilo.mp4" hue="amber" /> },
  { key: "c197", start: 677.83, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_templos.mp4" hue="amber" /> },
  { key: "c198", start: 681.32, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_nombres.mp4" hue="amber" /> },
  { key: "c199", start: 684.81, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_desaparecio.mp4" hue="amber" /> },
  { key: "c200", start: 688.3, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_sombra.mp4" hue="amber" /> },
  { key: "c201", start: 691.79, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_dudaban.mp4" hue="amber" /> },
  { key: "c202", start: 695.28, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/he_dos_mil.mp4" hue="amber" /> },
  { key: "rule203", start: 698.77, dur: 4.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="02" title="Monumento de Yonaguni" label="Okinawa, Japón" hue="blue" /> },
  { key: "c206", start: 702.97, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_intro.mp4" hue="blue" /> },
  { key: "c207", start: 706.7, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_japon.mp4" hue="blue" /> },
  { key: "c208", start: 710.43, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_buzo.mp4" hue="blue" /> },
  { key: "c209", start: 714.16, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_encontro.mp4" hue="blue" /> },
  { key: "c210", start: 717.89, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_estructura.mp4" hue="blue" /> },
  { key: "c211", start: 721.62, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_terrazas.mp4" hue="blue" /> },
  { key: "c212", start: 725.35, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_geometria.mp4" hue="blue" /> },
  { key: "c213", start: 729.08, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_monumento.mp4" hue="blue" /> },
  { key: "c214", start: 732.81, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_artificial.mp4" hue="blue" /> },
  { key: "c215", start: 736.54, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_tierra_seca.mp4" hue="blue" /> },
  { key: "c216", start: 740.27, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_diez_mil.mp4" hue="blue" /> },
  { key: "scalecolossus217", start: 744, dur: 6, kind: "scalecolossus", el: (d) => <ScaleColossus durationInFrames={d} image="real/yo_monument.jpg" meters={27} unit="m" label="de altura · terrazas y ángulos rectos" eyebrow="Monumento de Yonaguni" accent="blue" /> },
  { key: "c219", start: 750, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_intro.mp4" hue="blue" /> },
  { key: "c220", start: 753.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_japon.mp4" hue="blue" /> },
  { key: "c221", start: 757.01, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_buzo.mp4" hue="blue" /> },
  { key: "c222", start: 760.51, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_encontro.mp4" hue="blue" /> },
  { key: "c223", start: 764.01, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_estructura.mp4" hue="blue" /> },
  { key: "c224", start: 767.51, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_terrazas.mp4" hue="blue" /> },
  { key: "c225", start: 771.02, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_geometria.mp4" hue="blue" /> },
  { key: "c226", start: 774.52, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_monumento.mp4" hue="blue" /> },
  { key: "c227", start: 778.02, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_artificial.mp4" hue="blue" /> },
  { key: "c228", start: 781.53, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_tierra_seca.mp4" hue="blue" /> },
  { key: "stat229", start: 785.03, dur: 5.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={10000} prefix="¿" suffix=" años?" label="si es artificial, nadie debería haberlo construido" eyebrow="¿Natural o humano?" accent="danger" hue="blue" /> },
  { key: "c230", start: 790.23, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_intro.mp4" hue="blue" /> },
  { key: "c231", start: 793.81, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_japon.mp4" hue="blue" /> },
  { key: "c232", start: 797.4, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_buzo.mp4" hue="blue" /> },
  { key: "c233", start: 800.98, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_encontro.mp4" hue="blue" /> },
  { key: "c234", start: 804.56, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_estructura.mp4" hue="blue" /> },
  { key: "c235", start: 808.14, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_terrazas.mp4" hue="blue" /> },
  { key: "c236", start: 811.73, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_geometria.mp4" hue="blue" /> },
  { key: "c237", start: 815.31, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_monumento.mp4" hue="blue" /> },
  { key: "c238", start: 818.89, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_artificial.mp4" hue="blue" /> },
  { key: "c239", start: 822.48, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/yo_tierra_seca.mp4" hue="blue" /> },
  { key: "rule240", start: 826.06, dur: 4.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="01" title="Estructura sumergida de Cuba" label="Cabo de San Antonio, Cuba" hue="red" /> },
  { key: "c243", start: 830.26, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_intro.mp4" hue="red" /> },
  { key: "c244", start: 833.82, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_no_encaja.mp4" hue="red" /> },
  { key: "c245", start: 837.38, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_caribe.mp4" hue="red" /> },
  { key: "c246", start: 840.94, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_sonar.mp4" hue="red" /> },
  { key: "c247", start: 844.5, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_galeones.mp4" hue="red" /> },
  { key: "c248", start: 848.06, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_pantallas.mp4" hue="red" /> },
  { key: "c249", start: 851.61, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_profundidad.mp4" hue="red" /> },
  { key: "c250", start: 855.17, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_formas.mp4" hue="red" /> },
  { key: "c251", start: 858.73, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_eran_estructuras.mp4" hue="red" /> },
  { key: "c252", start: 862.29, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_bloques.mp4" hue="red" /> },
  { key: "c253", start: 865.85, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_piramides.mp4" hue="red" /> },
  { key: "c254", start: 869.41, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_complejo.mp4" hue="red" /> },
  { key: "c255", start: 872.97, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_problema.mp4" hue="red" /> },
  { key: "c256", start: 876.53, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_tierra_seca.mp4" hue="red" /> },
  { key: "c257", start: 880.09, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_mucho_bajo.mp4" hue="red" /> },
  { key: "scalecolossus258", start: 883.65, dur: 6, kind: "scalecolossus", el: (d) => <ScaleColossus durationInFrames={d} image="real/cu_structure.jpg" meters={700} unit="m" label="de profundidad · imposible para la cronología" eyebrow="Estructura sumergida de Cuba" accent="red" /> },
  { key: "c260", start: 889.65, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_intro.mp4" hue="red" /> },
  { key: "c261", start: 893.29, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_no_encaja.mp4" hue="red" /> },
  { key: "c262", start: 896.94, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_caribe.mp4" hue="red" /> },
  { key: "c263", start: 900.58, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_sonar.mp4" hue="red" /> },
  { key: "c264", start: 904.23, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_galeones.mp4" hue="red" /> },
  { key: "c265", start: 907.87, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_pantallas.mp4" hue="red" /> },
  { key: "c266", start: 911.52, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_profundidad.mp4" hue="red" /> },
  { key: "c267", start: 915.16, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_formas.mp4" hue="red" /> },
  { key: "c268", start: 918.81, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_eran_estructuras.mp4" hue="red" /> },
  { key: "c269", start: 922.45, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_bloques.mp4" hue="red" /> },
  { key: "c270", start: 926.1, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_piramides.mp4" hue="red" /> },
  { key: "c271", start: 929.74, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_complejo.mp4" hue="red" /> },
  { key: "c272", start: 933.39, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_problema.mp4" hue="red" /> },
  { key: "stat273", start: 937.03, dur: 5.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={700} suffix=" metros" label="demasiado profundo para cualquier ciudad conocida" eyebrow="Detectada por sonar en 2001" accent="danger" hue="red" /> },
  { key: "c274", start: 942.23, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_intro.mp4" hue="red" /> },
  { key: "c275", start: 945.94, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_no_encaja.mp4" hue="red" /> },
  { key: "c276", start: 949.65, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_caribe.mp4" hue="red" /> },
  { key: "c277", start: 953.35, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_sonar.mp4" hue="red" /> },
  { key: "c278", start: 957.06, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_galeones.mp4" hue="red" /> },
  { key: "c279", start: 960.77, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_pantallas.mp4" hue="red" /> },
  { key: "c280", start: 964.47, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_profundidad.mp4" hue="red" /> },
  { key: "c281", start: 968.18, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_formas.mp4" hue="red" /> },
  { key: "c282", start: 971.89, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_eran_estructuras.mp4" hue="red" /> },
  { key: "c283", start: 975.59, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_bloques.mp4" hue="red" /> },
  { key: "c284", start: 979.3, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_piramides.mp4" hue="red" /> },
  { key: "c285", start: 983.01, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_complejo.mp4" hue="red" /> },
  { key: "c286", start: 986.71, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cu_problema.mp4" hue="red" /> },
  { key: "c287", start: 990.42, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_ventanas.mp4" hue="blue" /> },
  { key: "c288", start: 994.15, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_pavlopetri.mp4" hue="blue" /> },
  { key: "c289", start: 997.88, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_port_royal.mp4" hue="blue" /> },
  { key: "c290", start: 1001.61, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_baiae.mp4" hue="blue" /> },
  { key: "c291", start: 1005.34, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_dwarka.mp4" hue="blue" /> },
  { key: "c292", start: 1009.07, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_heracleion.mp4" hue="blue" /> },
  { key: "c293", start: 1012.8, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_yonaguni.mp4" hue="blue" /> },
  { key: "c294", start: 1016.53, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_cuba.mp4" hue="blue" /> },
  { key: "c295", start: 1020.26, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_doce_mil.mp4" hue="blue" /> },
  { key: "c296", start: 1023.99, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_museos.mp4" hue="blue" /> },
  { key: "c297", start: 1027.72, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_bajo_agua.mp4" hue="blue" /> },
  { key: "timeline298", start: 1031.45, dur: 8.5, kind: "timeline", el: (d) => <SagaTimeline durationInFrames={d} events={[{"year":"¿remoto?","label":"Cuba"},{"year":"¿+10.000 a.C.?","label":"Yonaguni"},{"year":"3.000 a.C.","label":"Pavlopetri"},{"year":"s. II a.C.","label":"Heracleion"},{"year":"1692","label":"Port Royal"}]} eyebrow="Repartidas por el planeta y los milenios" title="El mar guardó lo que la tierra perdió" /> },
  { key: "c299", start: 1039.95, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_ventanas.mp4" hue="blue" /> },
  { key: "c300", start: 1043.64, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_pavlopetri.mp4" hue="blue" /> },
  { key: "c301", start: 1047.34, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_port_royal.mp4" hue="blue" /> },
  { key: "c302", start: 1051.03, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_baiae.mp4" hue="blue" /> },
  { key: "c303", start: 1054.72, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_dwarka.mp4" hue="blue" /> },
  { key: "c304", start: 1058.41, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_heracleion.mp4" hue="blue" /> },
  { key: "c305", start: 1062.11, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_yonaguni.mp4" hue="blue" /> },
  { key: "c306", start: 1065.8, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_cuba.mp4" hue="blue" /> },
  { key: "c307", start: 1069.49, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_doce_mil.mp4" hue="blue" /> },
  { key: "c308", start: 1073.18, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_museos.mp4" hue="blue" /> },
  { key: "c309", start: 1076.88, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_bajo_agua.mp4" hue="blue" /> },
  { key: "c310", start: 1080.57, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_tierra_seca.mp4" hue="blue" /> },
  { key: "headline311", start: 1084.26, dur: 6, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"¿Y"},{"t":"si"},{"t":"lo"},{"t":"imposible"},{"t":"duerme"},{"t":"bajo"},{"t":"el"},{"t":"hielo?","hl":true}]} hue="blue" size={84} bg="image" image="real/ciud_ice.jpg" /> },
  { key: "c312", start: 1090.26, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_ventanas.mp4" hue="blue" /> },
  { key: "c313", start: 1093.67, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_pavlopetri.mp4" hue="blue" /> },
  { key: "c314", start: 1097.08, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_port_royal.mp4" hue="blue" /> },
  { key: "c315", start: 1100.5, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_baiae.mp4" hue="blue" /> },
  { key: "c316", start: 1103.91, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_dwarka.mp4" hue="blue" /> },
  { key: "c317", start: 1107.32, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_heracleion.mp4" hue="blue" /> },
  { key: "c318", start: 1110.73, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_yonaguni.mp4" hue="blue" /> },
  { key: "c319", start: 1114.15, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_cuba.mp4" hue="blue" /> },
  { key: "c320", start: 1117.56, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cl_doce_mil.mp4" hue="blue" /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "o050", start: 180.85, dur: 6, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Pavlopetri" sub="Laconia, Grecia" accent="blue" /> },
  { key: "o051", start: 180.85, dur: 92.51, kind: "countrail", el: (d) => <CountRail durationInFrames={d} rank={1} total={7} name="Pavlopetri" accent="blue" /> },
  { key: "o062", start: 211.95, dur: 5, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="≈ 3.000 a.C." label="Pavlopetri" accent="blue" /> },
  { key: "o079", start: 277.76, dur: 6, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Port Royal" sub="Jamaica, Caribe" accent="red" /> },
  { key: "o080", start: 277.76, dur: 110.84, kind: "countrail", el: (d) => <CountRail durationInFrames={d} rank={2} total={7} name="Port Royal" accent="red" /> },
  { key: "o092", start: 314.97, dur: 5, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="7 jun. 1692" label="Port Royal" accent="red" /> },
  { key: "o113", start: 393, dur: 6, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Baiae" sub="Bahía de Nápoles, Italia" accent="blue" /> },
  { key: "o114", start: 393, dur: 91.43, kind: "countrail", el: (d) => <CountRail durationInFrames={d} rank={3} total={7} name="Baiae" accent="blue" /> },
  { key: "o124", start: 423.74, dur: 5, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="Imperio Romano" label="Baiae" accent="blue" /> },
  { key: "o141", start: 488.83, dur: 6, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Dwarka" sub="Golfo de Cambay, India" accent="amber" /> },
  { key: "o142", start: 488.83, dur: 95.69, kind: "countrail", el: (d) => <CountRail durationInFrames={d} rank={4} total={7} name="Dwarka" accent="amber" /> },
  { key: "o153", start: 520.99, dur: 5, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="Mito → piedra" label="Dwarka" accent="amber" /> },
  { key: "o170", start: 588.92, dur: 6, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Thonis-Heracleion" sub="Bahía de Abukir, Egipto" accent="amber" /> },
  { key: "o171", start: 588.92, dur: 109.65, kind: "countrail", el: (d) => <CountRail durationInFrames={d} rank={5} total={7} name="Thonis-Heracleion" accent="amber" /> },
  { key: "o183", start: 625.74, dur: 5, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="Hallada en 2000" label="Thonis-Heracleion" accent="amber" /> },
  { key: "o204", start: 702.97, dur: 6, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Monumento de Yonaguni" sub="Okinawa, Japón" accent="blue" /> },
  { key: "o205", start: 702.97, dur: 122.89, kind: "countrail", el: (d) => <CountRail durationInFrames={d} rank={6} total={7} name="Monumento de Yonaguni" accent="blue" /> },
  { key: "o218", start: 744.2, dur: 5, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="¿+10.000 años?" label="Monumento de Yonaguni" accent="blue" /> },
  { key: "o241", start: 830.26, dur: 6, kind: "doclabel", el: (d) => <DocLabel durationInFrames={d} label="Estructura sumergida de Cuba" sub="Cabo de San Antonio, Cuba" accent="red" /> },
  { key: "o242", start: 830.26, dur: 159.96, kind: "countrail", el: (d) => <CountRail durationInFrames={d} rank={7} total={7} name="Estructura sumergida de Cuba" accent="red" /> },
  { key: "o259", start: 883.85, dur: 5, kind: "datestamp", el: (d) => <DateStamp durationInFrames={d} value="Sonar, 2001" label="Estructura sumergida de Cuba" accent="red" /> },
];
