// cues_semillas.gen.tsx — GENERADO por beatsheet.mjs desde semillas.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/semillas.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { BreakingReveal } from "./scenes/BreakingReveal";
import { PresenterTag } from "./scenes/PresenterTag";
import { VerifiedStamp } from "./scenes/VerifiedStamp";
import { StepTracker } from "./scenes/StepTracker";
import { AlertWipe } from "./scenes/AlertWipe";
import { KineticLine } from "./scenes/KineticLine";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "s_01", start: 0.78, dur: 5.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra10_a.png" darken={0} /> },
  { key: "s_02", start: 6.16, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra11_a.png" darken={0} /> },
  { key: "s_03", start: 11.34, dur: 6.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra12_a.png" darken={0} /> },
  { key: "s_04", start: 17.58, dur: 6.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_04.mp4" darken={0} clipDur={8.4} /> },
  { key: "s_05_0", start: 24.02, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_05_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_05_1", start: 25.65, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_05_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_05_2", start: 27.28, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_05_c.jpg" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_06", start: 28.4, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra13_a.png" darken={0} /> },
  { key: "s_07_0", start: 31.38, dur: 2.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_07_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_07_1", start: 33.97, dur: 2.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_07_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_08", start: 36.06, dur: 5.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra14_a.png" darken={0} /> },
  { key: "s_09", start: 40.98, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra1_a.png" darken={0} /> },
  { key: "s_10", start: 45.3, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra2_a.png" darken={0} /> },
  { key: "s_11", start: 49.12, dur: 5.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra3_a.png" darken={0} /> },
  { key: "s_12", start: 54.34, dur: 5.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra4_a.png" darken={0} /> },
  { key: "s_13", start: 58.92, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra5_a.png" darken={0} /> },
  { key: "s_14", start: 63.72, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra6_a.png" darken={0} /> },
  { key: "s_15", start: 69.12, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra7_a.png" darken={0} /> },
  { key: "s_16", start: 72.58, dur: 5.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_16_a.png" darken={0} /> },
  { key: "s_17", start: 78.06, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_17_a.png" darken={0} /> },
  { key: "s_18", start: 86.16, dur: 5.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra8_a.png" darken={0} /> },
  { key: "s_19", start: 91.64, dur: 6.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_19_a.png" darken={0} /> },
  { key: "s_20", start: 97.84, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_extra9_a.png" darken={0} /> },
  { key: "s_21", start: 103.34, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_21_a.jpg" darken={0} /> },
  { key: "s_22", start: 107.68, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_22.png" darken={0} /> },
  { key: "s_23", start: 112.62, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_23.png" darken={0} /> },
  { key: "s_24", start: 117.82, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_24.png" darken={0} /> },
  { key: "s_25", start: 122.36, dur: 5.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_25.png" darken={0} /> },
  { key: "s_26", start: 127.74, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_26.png" darken={0} /> },
  { key: "s_27", start: 132.5, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_27_a.png" darken={0} /> },
  { key: "s_28", start: 136.26, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_28.png" darken={0} /> },
  { key: "s_29", start: 142.76, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_29.png" darken={0} /> },
  { key: "s_30", start: 147.66, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_30.png" darken={0} /> },
  { key: "s_31", start: 152.84, dur: 6.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_31.png" darken={0} /> },
  { key: "s_32", start: 158.76, dur: 5.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_32.png" darken={0} /> },
  { key: "s_33", start: 163.68, dur: 6.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_33.png" darken={0} /> },
  { key: "s_34", start: 169.64, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_34_a.png" darken={0} /> },
  { key: "s_35", start: 175.16, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_35.png" darken={0} /> },
  { key: "s_36", start: 177.82, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_36.png" darken={0} /> },
  { key: "s_37_0", start: 182.48, dur: 2.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_37_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_37_1", start: 184.75, dur: 2.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_37_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_38", start: 186.52, dur: 5.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_38_a.png" darken={0} /> },
  { key: "s_39", start: 191.9, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_39_a.png" darken={0} /> },
  { key: "s_40", start: 195.18, dur: 6.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_40.png" darken={0} /> },
  { key: "s_41", start: 201.23, dur: 5.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_41.png" darken={0} /> },
  { key: "s_42", start: 205.96, dur: 5.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_42_a.png" darken={0} /> },
  { key: "s_43", start: 210.7, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_43.png" darken={0} /> },
  { key: "s_44_0", start: 216.78, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_44_a.png" darken={0} kbPhase={0} /> },
  { key: "s_44_1", start: 219.15, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_44_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_45_0", start: 221.02, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_45_a.png" darken={0} kbPhase={0} /> },
  { key: "s_45_1", start: 222.65, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_45_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_45_2", start: 224.28, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_45_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_46_0", start: 225.4, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_46_a.png" darken={0} kbPhase={0} /> },
  { key: "s_46_1", start: 228.65, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_46_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_47_0", start: 231.4, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_47_a.png" darken={0} kbPhase={0} /> },
  { key: "s_47_1", start: 234.55, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_47_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_48_0", start: 237.2, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_48_a.png" darken={0} kbPhase={0} /> },
  { key: "s_48_1", start: 239.35, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_48_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_48_2", start: 241.5, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_48_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_49_0", start: 243.14, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_49_a.png" darken={0} kbPhase={0} /> },
  { key: "s_49_1", start: 246.18, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_49_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_50_0", start: 248.72, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_50_a.png" darken={0} kbPhase={0} /> },
  { key: "s_50_1", start: 250.76, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_50_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_51", start: 252.3, dur: 7.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_51.png" darken={0} /> },
  { key: "s_52_0", start: 259.14, dur: 2.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_52_a.png" darken={0} kbPhase={0} /> },
  { key: "s_52_1", start: 261.93, dur: 2.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_52_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_52_2", start: 264.72, dur: 2.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_52_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_53_0", start: 267, dur: 2.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_53_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_53_1", start: 269.49, dur: 2.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_53_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_53_2", start: 271.98, dur: 2.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_53_c.jpg" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_54_0", start: 273.96, dur: 2.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_54_a.png" darken={0} kbPhase={0} /> },
  { key: "s_54_1", start: 276.53, dur: 2.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_54_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_54_2", start: 279.1, dur: 2.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_54_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_55", start: 281.16, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_55.png" darken={0} /> },
  { key: "s_56", start: 286.1, dur: 5.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_56.png" darken={0} /> },
  { key: "s_57_0", start: 290.62, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_57_a.png" darken={0} kbPhase={0} /> },
  { key: "s_57_1", start: 293.69, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_57_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_58_0", start: 296.26, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_58_a.png" darken={0} kbPhase={0} /> },
  { key: "s_58_1", start: 299.17, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_58_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_59_0", start: 301.58, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_59_a.png" darken={0} kbPhase={0} /> },
  { key: "s_59_1", start: 303.59, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_59_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_60_0", start: 305.1, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_60_a.png" darken={0} kbPhase={0} /> },
  { key: "s_60_1", start: 308.67, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_60_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_61_0", start: 311.74, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_61_a.png" darken={0} kbPhase={0} /> },
  { key: "s_61_1", start: 314.4, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_61_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_62", start: 316.56, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_62.png" darken={0} /> },
  { key: "s_63_0", start: 322.56, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_63_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_63_1", start: 325.47, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_63_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_64", start: 327.88, dur: 5.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_64.png" darken={0} /> },
  { key: "s_65_0", start: 332.86, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_65_a.png" darken={0} kbPhase={0} /> },
  { key: "s_65_1", start: 335.64, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_65_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_66", start: 337.92, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_66_a.png" darken={0} /> },
  { key: "s_67", start: 340.84, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_67.png" darken={0} /> },
  { key: "s_68_0", start: 344.92, dur: 2.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_68_a.png" darken={0} kbPhase={0} /> },
  { key: "s_68_1", start: 347.11, dur: 2.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_68_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_69", start: 348.8, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_69.png" darken={0} /> },
  { key: "s_70_0", start: 352.2, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_70_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_70_1", start: 354.55, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_70_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_70_2", start: 356.9, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_70_c.jpg" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_71", start: 358.76, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_71.png" darken={0} /> },
  { key: "s_72", start: 363.16, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_72.png" darken={0} /> },
  { key: "s_73", start: 366.6, dur: 5.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_73.png" darken={0} /> },
  { key: "s_74", start: 372.08, dur: 6.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_74_a.png" darken={0} /> },
  { key: "s_75", start: 377.82, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_75.png" darken={0} /> },
  { key: "s_76", start: 383.08, dur: 7.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_76_a.png" darken={0} /> },
  { key: "s_77", start: 390.54, dur: 5.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_77.png" darken={0} /> },
  { key: "s_78", start: 395.6, dur: 6.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_78.png" darken={0} /> },
  { key: "s_79", start: 401.22, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_79.png" darken={0} /> },
  { key: "s_80", start: 406.62, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_80.mp4" darken={0} clipDur={7.01} /> },
  { key: "s_81", start: 411.62, dur: 7.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_81.png" darken={0} /> },
  { key: "s_82", start: 418.44, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_82.png" darken={0} /> },
  { key: "s_83", start: 422.24, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_83.png" darken={0} /> },
  { key: "s_84_0", start: 425.6, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_84_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_84_1", start: 428.11, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_84_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_84_2", start: 430.62, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_84_c.jpg" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_85", start: 432.62, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_85.png" darken={0} /> },
  { key: "s_86", start: 437.56, dur: 5.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_86.mp4" darken={0} clipDur={7.01} /> },
  { key: "s_87", start: 442.54, dur: 6.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_87.png" darken={0} /> },
  { key: "s_88", start: 448.72, dur: 8.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_88.png" darken={0} /> },
  { key: "s_89_0", start: 456.36, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_89_a.png" darken={0} kbPhase={0} /> },
  { key: "s_89_1", start: 458.71, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_89_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_89_2", start: 461.06, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_89_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_90", start: 462.92, dur: 5.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_90.png" darken={0} /> },
  { key: "s_91", start: 467.74, dur: 6.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_91.png" darken={0} /> },
  { key: "s_92", start: 474.12, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_92_a.jpg" darken={0} /> },
  { key: "s_93", start: 479.16, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_93.png" darken={0} /> },
  { key: "s_94", start: 483.38, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_94.png" darken={0} /> },
  { key: "s_95", start: 488.28, dur: 6.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_95.png" darken={0} /> },
  { key: "s_96", start: 493.92, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_96.png" darken={0} /> },
  { key: "s_97", start: 499.92, dur: 6.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_97.png" darken={0} /> },
  { key: "s_98", start: 506.34, dur: 7.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_98.png" darken={0} /> },
  { key: "s_99", start: 513.4, dur: 6.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_99.png" darken={0} /> },
  { key: "s_100", start: 519.74, dur: 5.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_100.png" darken={0} /> },
  { key: "s_101", start: 524.26, dur: 6.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_101.mp4" darken={0} clipDur={7.71} /> },
  { key: "s_102_0", start: 529.96, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_102_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_102_1", start: 533.18, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_102_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_103", start: 535.9, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_103.png" darken={0} /> },
  { key: "s_104", start: 540.9, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_104.png" darken={0} /> },
  { key: "s_105", start: 546.22, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_105.png" darken={0} /> },
  { key: "s_106", start: 550.64, dur: 5.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_106.png" darken={0} /> },
  { key: "s_107", start: 555.46, dur: 5.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_107.png" darken={0} /> },
  { key: "s_108", start: 560.44, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_108.png" darken={0} /> },
  { key: "s_109_0", start: 565.48, dur: 2.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_109_a.png" darken={0} kbPhase={0} /> },
  { key: "s_109_1", start: 567.77, dur: 2.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_109_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_109_2", start: 570.06, dur: 2.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_109_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_110", start: 571.86, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_110.png" darken={0} /> },
  { key: "s_111_0", start: 575.4, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_111_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_111_1", start: 577.77, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_111_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_111_2", start: 580.14, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_111_c.jpg" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_112_0", start: 582, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_112_a.png" darken={0} kbPhase={0} /> },
  { key: "s_112_1", start: 584.88, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_112_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_113_0", start: 587.26, dur: 6.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_113_a.png" darken={0} kbPhase={0} /> },
  { key: "s_113_1", start: 593.49, dur: 6.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_113_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_113_2", start: 599.72, dur: 6.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_113_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_114", start: 605.44, dur: 6.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_114.png" darken={0} /> },
  { key: "s_115", start: 611.48, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_115.png" darken={0} /> },
  { key: "s_116", start: 615.58, dur: 7.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_116_a.png" darken={0} /> },
  { key: "s_117_0", start: 622.34, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_117_a.png" darken={0} kbPhase={0} /> },
  { key: "s_117_1", start: 625.77, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_117_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_118", start: 628.7, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_118.png" darken={0} /> },
  { key: "s_119", start: 632.42, dur: 6.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_119.png" darken={0} /> },
  { key: "s_120", start: 637.96, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_120.png" darken={0} /> },
  { key: "s_121", start: 642.36, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_121_a.jpg" darken={0} /> },
  { key: "s_122", start: 647.76, dur: 5.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_122.png" darken={0} /> },
  { key: "s_123_0", start: 652.64, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_123_a.png" darken={0} kbPhase={0} /> },
  { key: "s_123_1", start: 656.08, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_123_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_124_0", start: 659.02, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_124_a.png" darken={0} kbPhase={0} /> },
  { key: "s_124_1", start: 662.52, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_124_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_125_0", start: 665.52, dur: 4.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_125_a.png" darken={0} kbPhase={0} /> },
  { key: "s_125_1", start: 669.75, dur: 4.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_125_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_126", start: 673.48, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_126.mp4" darken={0} clipDur={5} /> },
  { key: "s_127_0", start: 676.51, dur: 1.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_127_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_127_1", start: 678.42, dur: 1.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_127_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_128", start: 679.82, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_128.png" darken={0} /> },
  { key: "s_129_0", start: 683.82, dur: 2.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_129_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_129_1", start: 685.93, dur: 2.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_129_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_130_0", start: 687.54, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_130_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_130_1", start: 690.22, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_130_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_131", start: 692.4, dur: 7.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_131.png" darken={0} /> },
  { key: "s_132", start: 699.42, dur: 4.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_132_a.png" darken={0} /> },
  { key: "s_133", start: 703.06, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_133.png" darken={0} /> },
  { key: "s_134", start: 707.1, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_134.png" darken={0} /> },
  { key: "s_135_0", start: 710.24, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_135_a.png" darken={0} kbPhase={0} /> },
  { key: "s_135_1", start: 713.64, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_135_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_136", start: 716.54, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_136_a.png" darken={0} /> },
  { key: "s_137", start: 721.14, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_137_a.jpg" darken={0} /> },
  { key: "s_138_0", start: 724.86, dur: 1.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_138_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_138_1", start: 726.4, dur: 1.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_138_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_138_2", start: 727.94, dur: 1.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_138_c.jpg" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_139_0", start: 728.98, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_139_a.png" darken={0} kbPhase={0} /> },
  { key: "s_139_1", start: 731.93, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_139_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_140", start: 734.38, dur: 8.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_140.png" darken={0} /> },
  { key: "s_141", start: 742.1, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_141_a.png" darken={0} /> },
  { key: "s_142", start: 745.52, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_142_a.png" darken={0} /> },
  { key: "s_143_0", start: 750.7, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_143_a.png" darken={0} kbPhase={0} /> },
  { key: "s_143_1", start: 754.52, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_143_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_144", start: 757.84, dur: 6.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_144.png" darken={0} /> },
  { key: "s_145", start: 763.72, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_145.png" darken={0} /> },
  { key: "s_146", start: 767.28, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_146_a.jpg" darken={0} /> },
  { key: "s_147", start: 772.46, dur: 5.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_147.png" darken={0} /> },
  { key: "s_148", start: 777.48, dur: 6.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_148.png" darken={0} /> },
  { key: "s_149", start: 783.04, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_149.png" darken={0} /> },
  { key: "s_150", start: 786.56, dur: 5.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_150.png" darken={0} /> },
  { key: "s_151", start: 792.04, dur: 5.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_151.png" darken={0} /> },
  { key: "s_152", start: 797.46, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_152.png" darken={0} /> },
  { key: "s_153_0", start: 800.46, dur: 1.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_153_a.png" darken={0} kbPhase={0} /> },
  { key: "s_153_1", start: 802.3, dur: 1.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_153_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_154_0", start: 803.64, dur: 2.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_154_a.jpg" darken={0} kbPhase={0} /> },
  { key: "s_154_1", start: 805.69, dur: 2.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_154_b.jpg" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_155_0", start: 807.24, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_155_a.png" darken={0} kbPhase={0} /> },
  { key: "s_155_1", start: 810.5, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_155_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_156_0", start: 813.26, dur: 2.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_156_a.png" darken={0} kbPhase={0} /> },
  { key: "s_156_1", start: 815.95, dur: 2.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_156_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_157_0", start: 818.14, dur: 1.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_157_a.png" darken={0} kbPhase={0} /> },
  { key: "s_157_1", start: 820, dur: 1.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_157_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_157_2", start: 821.86, dur: 1.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_157_c.png" darken={0} trans={7} kbPhase={2} /> },
  { key: "s_158_0", start: 823.22, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_158_a.png" darken={0} kbPhase={0} /> },
  { key: "s_158_1", start: 826.17, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_158_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_159", start: 828.62, dur: 8.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_159_a.jpg" darken={0} /> },
  { key: "s_160", start: 836.2, dur: 5.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_160_a.jpg" darken={0} /> },
  { key: "s_161", start: 841.62, dur: 6.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_161_a.jpg" darken={0} /> },
  { key: "s_162", start: 847.66, dur: 6.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_162.png" darken={0} /> },
  { key: "s_163", start: 854.06, dur: 4.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_163.png" darken={0} /> },
  { key: "s_164", start: 858.39, dur: 6.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_164_a.jpg" darken={0} /> },
  { key: "s_165", start: 864.82, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_165.png" darken={0} /> },
  { key: "s_166_0", start: 869.42, dur: 2.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_166_a.png" darken={0} kbPhase={0} /> },
  { key: "s_166_1", start: 872.07, dur: 2.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_166_b.png" darken={0} trans={7} kbPhase={1} /> },
  { key: "s_167", start: 874.22, dur: 1.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_167_a.jpg" darken={0} /> },
  { key: "s_168", start: 881.9, dur: 0.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/semillas_s_168_a.jpg" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "cmp_pres", start: 4.91, dur: 4.5, kind: "presenter", el: (d) => <PresenterTag durationInFrames={d} name="LEVI LAPP" subtitle="Huerta a la vieja usanza · 3ª generación" accent="amber" /> },
  { key: "kl1", start: 11.34, dur: 2.54, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"No","at":0},{"t":"muerta.","at":0.06},{"t":"Dormida.","at":0.84,"hl":true}]} accent="amber" /> },
  { key: "kl2", start: 15.96, dur: 2.78, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"una","at":0},{"t":"botellita","at":0.2},{"t":"de","at":0.66},{"t":"dos","at":0.86,"hl":true},{"t":"pesos,","at":1.08}]} accent="amber" /> },
  { key: "cmp_alert", start: 50.18, dur: 1.1, kind: "alertwipe", el: (d) => <AlertWipe durationInFrames={d} text="ATENCIÓN" accent="danger" /> },
  { key: "cmp_break3", start: 54.44, dur: 4, kind: "breaking", el: (d) => <BreakingReveal durationInFrames={d} headline="Un error de tiempo la MATA" label="CUIDADO" badge="OJO" ticker="Un rato de más y en vez de despertarla, la quemás" accent="danger" /> },
  { key: "cmp_break1", start: 82.54, dur: 4.2, kind: "breaking", el: (d) => <BreakingReveal durationInFrames={d} headline="No están muertas — están dormidas" label="AL DESCUBIERTO" badge="DATO" ticker="Dos candados que el oxígeno abre de golpe" accent="amber" /> },
  { key: "cmp_step1", start: 327.88, dur: 6, kind: "steptrack", el: (d) => <StepTracker durationInFrames={d} step={1} total={3} label="PASO" accent="amber" /> },
  { key: "cmp_step2", start: 352.2, dur: 6, kind: "steptrack", el: (d) => <StepTracker durationInFrames={d} step={2} total={3} label="PASO" accent="amber" /> },
  { key: "cmp_verif", start: 362.04, dur: 3.2, kind: "verified", el: (d) => <VerifiedStamp durationInFrames={d} text="30 MINUTOS · NI UNO MÁS" accent="good" /> },
  { key: "cmp_step3", start: 395.6, dur: 6, kind: "steptrack", el: (d) => <StepTracker durationInFrames={d} step={3} total={3} label="PASO" accent="amber" /> },
  { key: "cmp_break2", start: 490.28, dur: 4.2, kind: "breaking", el: (d) => <BreakingReveal durationInFrames={d} headline="Sabé qué semilla vive antes de sembrar" label="LA PRUEBA" badge="10 SEG" ticker="La que se hunde está viva; la que flota, no" accent="good" /> },
  { key: "kl3", start: 878, dur: 3.12, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"lo","at":0},{"t":"que","at":0.14},{"t":"parece","at":0.3},{"t":"muerto","at":0.5,"hl":true},{"t":"solo","at":0.92},{"t":"estaba","at":1.18},{"t":"esperando","at":1.42}]} accent="amber" /> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":4.91,"role":"popUp","vol":0.32},{"at":11.34,"role":"popUp","vol":0.32},{"at":15.96,"role":"popUp","vol":0.32},{"at":25.65,"role":"transition","vol":0.3},{"at":33.97,"role":"transition","vol":0.3},{"at":50.18,"role":"popUp","vol":0.32},{"at":54.44,"role":"popUp","vol":0.32},{"at":82.54,"role":"popUp","vol":0.32},{"at":184.75,"role":"transition","vol":0.3},{"at":219.15,"role":"transition","vol":0.3},{"at":222.65,"role":"transition","vol":0.3},{"at":228.65,"role":"transition","vol":0.3},{"at":234.55,"role":"transition","vol":0.3},{"at":239.35,"role":"transition","vol":0.3},{"at":241.5,"role":"transition","vol":0.3},{"at":246.18,"role":"transition","vol":0.3},{"at":250.76,"role":"transition","vol":0.3},{"at":261.93,"role":"transition","vol":0.3},{"at":264.72,"role":"transition","vol":0.3},{"at":269.49,"role":"transition","vol":0.3},{"at":271.98,"role":"transition","vol":0.3},{"at":276.53,"role":"transition","vol":0.3},{"at":279.1,"role":"transition","vol":0.3},{"at":293.69,"role":"transition","vol":0.3},{"at":299.17,"role":"transition","vol":0.3},{"at":303.59,"role":"transition","vol":0.3},{"at":308.67,"role":"transition","vol":0.3},{"at":314.4,"role":"transition","vol":0.3},{"at":325.47,"role":"transition","vol":0.3},{"at":327.88,"role":"popUp","vol":0.32},{"at":335.64,"role":"transition","vol":0.3},{"at":347.11,"role":"transition","vol":0.3},{"at":352.2,"role":"popUp","vol":0.32},{"at":354.55,"role":"transition","vol":0.3},{"at":356.9,"role":"transition","vol":0.3},{"at":362.04,"role":"popUp","vol":0.32},{"at":395.6,"role":"popUp","vol":0.32},{"at":428.11,"role":"transition","vol":0.3},{"at":430.62,"role":"transition","vol":0.3},{"at":458.71,"role":"transition","vol":0.3},{"at":461.06,"role":"transition","vol":0.3},{"at":490.28,"role":"popUp","vol":0.32},{"at":533.18,"role":"transition","vol":0.3},{"at":567.77,"role":"transition","vol":0.3},{"at":570.06,"role":"transition","vol":0.3},{"at":577.77,"role":"transition","vol":0.3},{"at":580.14,"role":"transition","vol":0.3},{"at":584.88,"role":"transition","vol":0.3},{"at":593.49,"role":"transition","vol":0.3},{"at":599.72,"role":"transition","vol":0.3},{"at":625.77,"role":"transition","vol":0.3},{"at":656.08,"role":"transition","vol":0.3},{"at":662.52,"role":"transition","vol":0.3},{"at":669.75,"role":"transition","vol":0.3},{"at":678.42,"role":"transition","vol":0.3},{"at":685.93,"role":"transition","vol":0.3},{"at":690.22,"role":"transition","vol":0.3},{"at":713.64,"role":"transition","vol":0.3},{"at":726.4,"role":"transition","vol":0.3},{"at":731.93,"role":"transition","vol":0.3},{"at":754.52,"role":"transition","vol":0.3},{"at":802.3,"role":"transition","vol":0.3},{"at":805.69,"role":"transition","vol":0.3},{"at":810.5,"role":"transition","vol":0.3},{"at":815.95,"role":"transition","vol":0.3},{"at":820,"role":"transition","vol":0.3},{"at":826.17,"role":"transition","vol":0.3},{"at":872.07,"role":"transition","vol":0.3},{"at":878,"role":"popUp","vol":0.32}];
