// cues_revivir.gen.tsx — GENERADO por beatsheet.mjs desde revivir.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/revivir.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { BreakingReveal } from "./scenes/BreakingReveal";
import { PresenterTag } from "./scenes/PresenterTag";
import { NewsTicker } from "./scenes/NewsTicker";
import { VerifiedStamp } from "./scenes/VerifiedStamp";
import { StepTracker } from "./scenes/StepTracker";
import { AlertWipe } from "./scenes/AlertWipe";
import { KineticLine } from "./scenes/KineticLine";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "s_01", start: 0.6, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_001.mp4" darken={0} clipDur={3} /> },
  { key: "s_02", start: 6.1, dur: 5.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_02.png" darken={0} /> },
  { key: "s_03", start: 10.82, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_03.png" darken={0} /> },
  { key: "s_04", start: 14.34, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_002.mp4" darken={0} clipDur={3} /> },
  { key: "s_05", start: 18.26, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_05.png" darken={0} /> },
  { key: "s_06", start: 24.16, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_06.png" darken={0} /> },
  { key: "s_07", start: 27.52, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_003.mp4" darken={0} clipDur={3} /> },
  { key: "s_08", start: 33.12, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_08.png" darken={0} /> },
  { key: "s_09", start: 37.32, dur: 6.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_09.png" darken={0} /> },
  { key: "s_10", start: 43.52, dur: 5.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_10.mp4" darken={0} clipDur={7} /> },
  { key: "s_11", start: 48.48, dur: 5.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_11.png" darken={0} /> },
  { key: "s_12", start: 53.96, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_12.png" darken={0} /> },
  { key: "s_13", start: 57.4, dur: 5.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_004.mp4" darken={0} clipDur={3} /> },
  { key: "s_14", start: 62.42, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_14.png" darken={0} /> },
  { key: "s_15", start: 65.86, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_15.png" darken={0} /> },
  { key: "s_16", start: 70.7, dur: 6.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_005.mp4" darken={0} clipDur={3} /> },
  { key: "s_17", start: 76.98, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_17.png" darken={0} /> },
  { key: "s_18", start: 80.92, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_18.png" darken={0} /> },
  { key: "s_19", start: 84.44, dur: 7.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_006.mp4" darken={0} clipDur={3} /> },
  { key: "s_20", start: 91.76, dur: 6.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_20.png" darken={0} /> },
  { key: "s_21", start: 97.32, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_21.png" darken={0} /> },
  { key: "s_22", start: 101.92, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_007.mp4" darken={0} clipDur={3} /> },
  { key: "s_23", start: 105.44, dur: 6.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_23.png" darken={0} /> },
  { key: "s_24", start: 111.72, dur: 13.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_24.png" darken={0} /> },
  { key: "s_25", start: 124.28, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_008.mp4" darken={0} clipDur={3} /> },
  { key: "s_26", start: 128.7, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_26.png" darken={0} /> },
  { key: "s_27", start: 132.72, dur: 8.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_27.png" darken={0} /> },
  { key: "s_28", start: 140.48, dur: 4.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_28.mp4" darken={0} clipDur={5.81} /> },
  { key: "s_29", start: 144.32, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_29.png" darken={0} /> },
  { key: "s_30", start: 149.12, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_30.png" darken={0} /> },
  { key: "s_31", start: 154.52, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_009.mp4" darken={0} clipDur={3} /> },
  { key: "s_32", start: 158, dur: 7.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_32.png" darken={0} /> },
  { key: "s_33", start: 164.58, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_33.png" darken={0} /> },
  { key: "s_34", start: 169.84, dur: 5.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_010.mp4" darken={0} clipDur={3} /> },
  { key: "s_35", start: 175.2, dur: 5.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_35.png" darken={0} /> },
  { key: "s_36", start: 180.48, dur: 7.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_36.png" darken={0} /> },
  { key: "s_37", start: 187.3, dur: 6.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_011.mp4" darken={0} clipDur={3} /> },
  { key: "s_38", start: 193.56, dur: 7.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_38.mp4" darken={0} clipDur={9.31} /> },
  { key: "s_39", start: 200.88, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_39.png" darken={0} /> },
  { key: "s_40", start: 204.2, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_012.mp4" darken={0} clipDur={3} /> },
  { key: "s_41", start: 207.94, dur: 7.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_41.png" darken={0} /> },
  { key: "s_42", start: 214.56, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_42.mp4" darken={0} clipDur={3} /> },
  { key: "s_43", start: 217.88, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_013.mp4" darken={0} clipDur={3} /> },
  { key: "s_44", start: 223.04, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_44.png" darken={0} /> },
  { key: "s_45", start: 226.22, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_45.png" darken={0} /> },
  { key: "s_46", start: 229.24, dur: 6.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_014.mp4" darken={0} clipDur={3} /> },
  { key: "s_47", start: 234.8, dur: 5.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_47.png" darken={0} /> },
  { key: "s_48", start: 239.58, dur: 7.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_48.png" darken={0} /> },
  { key: "s_49", start: 246.54, dur: 5.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_49.mp4" darken={0} clipDur={3} /> },
  { key: "s_50", start: 251.4, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_50.png" darken={0} /> },
  { key: "s_51", start: 254.46, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_51.png" darken={0} /> },
  { key: "s_52", start: 259.62, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_015.mp4" darken={0} clipDur={3} /> },
  { key: "s_53", start: 264.82, dur: 7.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_53.png" darken={0} /> },
  { key: "s_54", start: 271.34, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_54.png" darken={0} /> },
  { key: "s_55", start: 274.36, dur: 5.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_016.mp4" darken={0} clipDur={3} /> },
  { key: "s_56", start: 279.66, dur: 7.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_56.mp4" darken={0} clipDur={3} /> },
  { key: "s_57", start: 286.18, dur: 6.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_57.png" darken={0} /> },
  { key: "s_58", start: 292.62, dur: 5.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_58.mp4" darken={0} clipDur={7.2} /> },
  { key: "s_59", start: 297.86, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_59.mp4" darken={0} clipDur={6.4} /> },
  { key: "s_60", start: 302.22, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_60.png" darken={0} /> },
  { key: "s_61", start: 307.06, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_017.mp4" darken={0} clipDur={3} /> },
  { key: "s_62", start: 312.32, dur: 6.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_62.png" darken={0} /> },
  { key: "s_63", start: 318.08, dur: 6.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_63.png" darken={0} /> },
  { key: "s_64", start: 323.9, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_018.mp4" darken={0} clipDur={3} /> },
  { key: "s_65", start: 329.1, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_65.png" darken={0} /> },
  { key: "s_66", start: 334.1, dur: 5.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_66.png" darken={0} /> },
  { key: "s_67", start: 339.56, dur: 6.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_019.mp4" darken={0} clipDur={3} /> },
  { key: "s_68", start: 345.76, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_68.png" darken={0} /> },
  { key: "s_69", start: 350.92, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_69.png" darken={0} /> },
  { key: "s_70", start: 354.24, dur: 7.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_020.mp4" darken={0} clipDur={3} /> },
  { key: "s_71", start: 361.02, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_71.png" darken={0} /> },
  { key: "s_72", start: 364.06, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_72.png" darken={0} /> },
  { key: "s_73", start: 369.1, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_021.mp4" darken={0} clipDur={3} /> },
  { key: "s_74", start: 374.42, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_74.png" darken={0} /> },
  { key: "s_75", start: 380.08, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_75.png" darken={0} /> },
  { key: "s_76", start: 383.24, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_022.mp4" darken={0} clipDur={3} /> },
  { key: "s_77", start: 387.58, dur: 6.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_77.png" darken={0} /> },
  { key: "s_78", start: 393.16, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_78.png" darken={0} /> },
  { key: "s_79", start: 397.32, dur: 7.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_023.mp4" darken={0} clipDur={3} /> },
  { key: "s_80", start: 404.66, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_80.png" darken={0} /> },
  { key: "s_81", start: 410.32, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_81.mp4" darken={0} clipDur={7.12} /> },
  { key: "s_82", start: 415.46, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_024.mp4" darken={0} clipDur={3} /> },
  { key: "s_83", start: 421.36, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_83.png" darken={0} /> },
  { key: "s_84", start: 424.9, dur: 5.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_84.png" darken={0} /> },
  { key: "s_85", start: 430.34, dur: 7.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_025.mp4" darken={0} clipDur={3} /> },
  { key: "s_86", start: 437.66, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_86.png" darken={0} /> },
  { key: "s_87", start: 441.78, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_87.png" darken={0} /> },
  { key: "s_88", start: 446.72, dur: 5.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_026.mp4" darken={0} clipDur={3} /> },
  { key: "s_89", start: 451.44, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_89.png" darken={0} /> },
  { key: "s_90", start: 455.94, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_90.png" darken={0} /> },
  { key: "s_91", start: 461.12, dur: 6.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_027.mp4" darken={0} clipDur={3} /> },
  { key: "s_92", start: 467.46, dur: 5.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_92.png" darken={0} /> },
  { key: "s_93", start: 471.98, dur: 19.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_93.png" darken={0} /> },
  { key: "s_94", start: 490.58, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_028.mp4" darken={0} clipDur={3} /> },
  { key: "s_95", start: 494.4, dur: 5.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_95.mp4" darken={0} clipDur={7.4} /> },
  { key: "s_96", start: 499.76, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_96.png" darken={0} /> },
  { key: "s_97", start: 505.76, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_029.mp4" darken={0} clipDur={3} /> },
  { key: "s_98", start: 509.9, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_98.png" darken={0} /> },
  { key: "s_99", start: 514.94, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_99.png" darken={0} /> },
  { key: "s_100", start: 519.24, dur: 6.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_030.mp4" darken={0} clipDur={3} /> },
  { key: "s_101", start: 525.28, dur: 7.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_101.png" darken={0} /> },
  { key: "s_102", start: 532.44, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_102.png" darken={0} /> },
  { key: "s_103", start: 535.6, dur: 6.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_031.mp4" darken={0} clipDur={3} /> },
  { key: "s_104", start: 541.86, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_104.png" darken={0} /> },
  { key: "s_105", start: 546.48, dur: 5.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_105.png" darken={0} /> },
  { key: "s_106", start: 551.5, dur: 6.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_032.mp4" darken={0} clipDur={3} /> },
  { key: "s_107", start: 557.04, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_107.png" darken={0} /> },
  { key: "s_108", start: 560.26, dur: 6.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_108.mp4" darken={0} clipDur={7.6} /> },
  { key: "s_109", start: 565.88, dur: 5.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_033.mp4" darken={0} clipDur={3} /> },
  { key: "s_110", start: 570.98, dur: 7.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_110.png" darken={0} /> },
  { key: "s_111", start: 577.52, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_111.mp4" darken={0} clipDur={5.52} /> },
  { key: "s_112", start: 580.98, dur: 6.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_034.mp4" darken={0} clipDur={3} /> },
  { key: "s_113", start: 586.74, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_113.mp4" darken={0} clipDur={3} /> },
  { key: "s_114", start: 590.16, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_114.png" darken={0} /> },
  { key: "s_115", start: 593.14, dur: 5.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_035.mp4" darken={0} clipDur={3} /> },
  { key: "s_116", start: 598.06, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_116.png" darken={0} /> },
  { key: "s_117", start: 601.34, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_117.png" darken={0} /> },
  { key: "s_118", start: 606.6, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_036.mp4" darken={0} clipDur={3} /> },
  { key: "s_119", start: 611.92, dur: 6.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_119.png" darken={0} /> },
  { key: "s_120", start: 617.74, dur: 6.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_120.png" darken={0} /> },
  { key: "s_121", start: 623.58, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_037.mp4" darken={0} clipDur={3} /> },
  { key: "s_122", start: 626.98, dur: 7.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_122.png" darken={0} /> },
  { key: "s_123", start: 633.62, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_123.png" darken={0} /> },
  { key: "s_124", start: 637.4, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_038.mp4" darken={0} clipDur={3} /> },
  { key: "s_125", start: 642.58, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_125.png" darken={0} /> },
  { key: "s_126", start: 646.62, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_126.mp4" darken={0} clipDur={3} /> },
  { key: "s_127", start: 653.12, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_039.mp4" darken={0} clipDur={3} /> },
  { key: "s_128", start: 658.78, dur: 4.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_128.png" darken={0} /> },
  { key: "s_129", start: 663.24, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_129.mp4" darken={0} clipDur={3} /> },
  { key: "s_130", start: 666.78, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_130.mp4" darken={0} clipDur={3} /> },
  { key: "s_131", start: 670.44, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_131.png" darken={0} /> },
  { key: "s_132", start: 674.84, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_132.png" darken={0} /> },
  { key: "s_133", start: 679.46, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_040.mp4" darken={0} clipDur={3} /> },
  { key: "s_134", start: 682.58, dur: 6.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_134.mp4" darken={0} clipDur={7.5} /> },
  { key: "s_135", start: 688.12, dur: 7.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_135.png" darken={0} /> },
  { key: "s_136", start: 694.64, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_041.mp4" darken={0} clipDur={3} /> },
  { key: "s_137", start: 700.14, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_137.mp4" darken={0} clipDur={3} /> },
  { key: "s_138", start: 704.68, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_138.png" darken={0} /> },
  { key: "s_139", start: 708.3, dur: 7.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_042.mp4" darken={0} clipDur={3} /> },
  { key: "s_140", start: 715.04, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_140.png" darken={0} /> },
  { key: "s_141", start: 719.8, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_141.png" darken={0} /> },
  { key: "s_142", start: 723.96, dur: 6.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_043.mp4" darken={0} clipDur={3} /> },
  { key: "s_143", start: 730.38, dur: 6.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_143.png" darken={0} /> },
  { key: "s_144", start: 736.2, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_144.png" darken={0} /> },
  { key: "s_145", start: 741.72, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_044.mp4" darken={0} clipDur={3} /> },
  { key: "s_146", start: 744.62, dur: 5.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_146.png" darken={0} /> },
  { key: "s_147", start: 749.98, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_147.mp4" darken={0} clipDur={3} /> },
  { key: "s_148", start: 753.02, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_148.mp4" darken={0} clipDur={3} /> },
  { key: "s_149", start: 757.36, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_149.mp4" darken={0} clipDur={3} /> },
  { key: "s_150", start: 761.86, dur: 6.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_150.mp4" darken={0} clipDur={8} /> },
  { key: "s_151", start: 767.84, dur: 6.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_151.mp4" darken={0} clipDur={8} /> },
  { key: "s_152", start: 773.86, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_152.png" darken={0} /> },
  { key: "s_153", start: 779.12, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_153.png" darken={0} /> },
  { key: "s_154", start: 784.44, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_045.mp4" darken={0} clipDur={3} /> },
  { key: "s_155", start: 789.96, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_155.png" darken={0} /> },
  { key: "s_156", start: 792.5, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_156.png" darken={0} /> },
  { key: "s_157", start: 797.64, dur: 5.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_046.mp4" darken={0} clipDur={3} /> },
  { key: "s_158", start: 802.5, dur: 7.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_158.png" darken={0} /> },
  { key: "s_159", start: 809.28, dur: 5.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_159.png" darken={0} /> },
  { key: "s_160", start: 813.96, dur: 6.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_047.mp4" darken={0} clipDur={3} /> },
  { key: "s_161", start: 820.08, dur: 7.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_161.png" darken={0} /> },
  { key: "s_162", start: 826.68, dur: 6.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_162.png" darken={0} /> },
  { key: "s_163", start: 832.52, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_048.mp4" darken={0} clipDur={3} /> },
  { key: "s_164", start: 836.68, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_164.png" darken={0} /> },
  { key: "s_165", start: 840, dur: 6.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_165.png" darken={0} /> },
  { key: "s_166", start: 845.56, dur: 5.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_049.mp4" darken={0} clipDur={3} /> },
  { key: "s_167", start: 850.54, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_167.png" darken={0} /> },
  { key: "s_168", start: 854, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_168.mp4" darken={0} clipDur={5.5} /> },
  { key: "s_169", start: 857.48, dur: 6.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_169.mp4" darken={0} clipDur={8.2} /> },
  { key: "s_170", start: 863.66, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_170.png" darken={0} /> },
  { key: "s_171", start: 871.26, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_171.mp4" darken={0} clipDur={3} /> },
  { key: "s_172", start: 874.66, dur: 7.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_050.mp4" darken={0} clipDur={3} /> },
  { key: "s_173", start: 881.2, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_173.png" darken={0} /> },
  { key: "s_174", start: 886.88, dur: 6.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/s_174.mp4" darken={0} clipDur={8.2} /> },
  { key: "s_175", start: 893.06, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_051.mp4" darken={0} clipDur={3} /> },
  { key: "s_176", start: 896.86, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_176.png" darken={0} /> },
  { key: "s_177", start: 902.02, dur: 5.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_177.png" darken={0} /> },
  { key: "s_178", start: 906.84, dur: 6.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_052.mp4" darken={0} clipDur={3} /> },
  { key: "s_179", start: 912.78, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_179.mp4" darken={0} clipDur={3} /> },
  { key: "s_180", start: 917.54, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_180.png" darken={0} /> },
  { key: "s_181", start: 921.32, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_053.mp4" darken={0} clipDur={3} /> },
  { key: "s_182", start: 925.82, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_182.png" darken={0} /> },
  { key: "s_183", start: 930.48, dur: 5.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_183.png" darken={0} /> },
  { key: "s_184", start: 935.94, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_054.mp4" darken={0} clipDur={3} /> },
  { key: "s_185", start: 941.08, dur: 5.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_185.png" darken={0} /> },
  { key: "s_186", start: 945.94, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_186.png" darken={0} /> },
  { key: "s_187", start: 949.84, dur: 5.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_055.mp4" darken={0} clipDur={3} /> },
  { key: "s_188", start: 955.12, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_188.mp4" darken={0} clipDur={3} /> },
  { key: "s_189", start: 961.62, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_189.png" darken={0} /> },
  { key: "s_190", start: 966.42, dur: 7.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_056.mp4" darken={0} clipDur={3} /> },
  { key: "s_191", start: 972.98, dur: 6.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_191.png" darken={0} /> },
  { key: "s_192", start: 978.52, dur: 6.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_192.png" darken={0} /> },
  { key: "s_193", start: 984.24, dur: 6.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_057.mp4" darken={0} clipDur={3} /> },
  { key: "s_194", start: 989.86, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_194.png" darken={0} /> },
  { key: "s_195", start: 994.62, dur: 6.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_195.png" darken={0} /> },
  { key: "s_196", start: 1000.56, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_058.mp4" darken={0} clipDur={3} /> },
  { key: "s_197", start: 1005.4, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_197.png" darken={0} /> },
  { key: "s_198", start: 1008.76, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_198.png" darken={0} /> },
  { key: "s_199", start: 1013.94, dur: 5.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_059.mp4" darken={0} clipDur={3} /> },
  { key: "s_200", start: 1018.72, dur: 5.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_200.png" darken={0} /> },
  { key: "s_201", start: 1024.18, dur: 6.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_201.mp4" darken={0} clipDur={3} /> },
  { key: "s_202", start: 1030.34, dur: 7.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_202.mp4" darken={0} clipDur={3} /> },
  { key: "s_203", start: 1037.82, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_203.mp4" darken={0} clipDur={3} /> },
  { key: "s_204", start: 1041.18, dur: 8.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_204.png" darken={0} /> },
  { key: "s_205", start: 1049.34, dur: 6.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_060.mp4" darken={0} clipDur={3} /> },
  { key: "s_206", start: 1055.04, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_206.mp4" darken={0} clipDur={3} /> },
  { key: "s_207", start: 1059.8, dur: 5.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_207.mp4" darken={0} clipDur={3} /> },
  { key: "s_208", start: 1064.92, dur: 6.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_levi_061.mp4" darken={0} clipDur={3} /> },
  { key: "s_209", start: 1070.56, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/revivir_s_209.png" darken={0} /> },
  { key: "s_210", start: 1073.76, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_210.mp4" darken={0} clipDur={3} /> },
  { key: "s_211", start: 1081.76, dur: 1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="vid/revivir_s_211.mp4" darken={0} clipDur={3} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "cmp_pres", start: 3.36, dur: 4.5, kind: "presenter", el: (d) => <PresenterTag durationInFrames={d} name="LEVI LAPP" subtitle="Huerta a la vieja usanza · 3ª generación" accent="amber" /> },
  { key: "cmp_ticker", start: 52, dur: 7, kind: "ticker", el: (d) => <NewsTicker durationInFrames={d} items={["Agua oxigenada al 3% — cuesta monedas","1½ cucharada por litro para el rescate","Se degrada con la luz: guardala en botella oscura","Nunca al sol fuerte del mediodía"]} label="DATO" accent="danger" /> },
  { key: "cmp_alert", start: 111.72, dur: 1.1, kind: "alertwipe", el: (d) => <AlertWipe durationInFrames={d} text="ATENCIÓN" accent="danger" /> },
  { key: "cmp_break1", start: 241.04, dur: 4, kind: "breaking", el: (d) => <BreakingReveal durationInFrames={d} headline="Estás ahogando tu planta con agua" label="AL DESCUBIERTO" badge="AHORA" ticker="El error que comete casi todo el mundo" accent="danger" /> },
  { key: "cmp_step1", start: 254.46, dur: 6, kind: "steptrack", el: (d) => <StepTracker durationInFrames={d} step={1} total={3} label="PASO" accent="amber" /> },
  { key: "cmp_step2", start: 393.16, dur: 6, kind: "steptrack", el: (d) => <StepTracker durationInFrames={d} step={2} total={3} label="PASO" accent="amber" /> },
  { key: "cmp_verif", start: 465.6, dur: 3.2, kind: "verified", el: (d) => <VerifiedStamp durationInFrames={d} text="LA DOSIS JUSTA" accent="good" /> },
  { key: "cmp_step3", start: 491.34, dur: 6, kind: "steptrack", el: (d) => <StepTracker durationInFrames={d} step={3} total={3} label="PASO" accent="amber" /> },
  { key: "cmp_break2", start: 616.34, dur: 4.2, kind: "breaking", el: (d) => <BreakingReveal durationInFrames={d} headline="Una hoja nueva = va a vivir" label="LA SEÑAL" badge="GANASTE" ticker="La señal de que la raíz ya se recuperó" accent="good" /> },
  { key: "kl1", start: 694.64, dur: 2.68, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"la","at":0},{"t":"tierra","at":0.06},{"t":"también","at":0.52},{"t":"se","at":0.74},{"t":"enferma.","at":0.98,"hl":true}]} accent="amber" /> },
  { key: "cmp_verif2", start: 1008.76, dur: 3, kind: "verified", el: (d) => <VerifiedStamp durationInFrames={d} text="GRATIS" accent="good" /> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":3.36,"role":"popUp","vol":0.32},{"at":52,"role":"popUp","vol":0.32},{"at":111.72,"role":"popUp","vol":0.32},{"at":241.04,"role":"popUp","vol":0.32},{"at":254.46,"role":"popUp","vol":0.32},{"at":393.16,"role":"popUp","vol":0.32},{"at":465.6,"role":"popUp","vol":0.32},{"at":491.34,"role":"popUp","vol":0.32},{"at":616.34,"role":"popUp","vol":0.32},{"at":694.64,"role":"popUp","vol":0.32},{"at":1008.76,"role":"popUp","vol":0.32}];
