// cues_peroxido.gen.tsx — GENERADO por beatsheet.mjs desde peroxido.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/peroxido.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { SplitList } from "./scenes/SplitList";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { HalfShot } from "./scenes/HalfShot";
import { MistakeCard } from "./scenes/MistakeCard";
import { LieList } from "./scenes/LieList";
import { KineticLine } from "./scenes/KineticLine";
import { PeroxidoDiagram } from "./scenes/PeroxidoDiagram";
import { FocusCard } from "./setpieces/FocusCard";

const D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "bh1_px_h_pour_soil", start: 2.05, dur: 5.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h_pour_soil.mp4" darken={0} /> },
  { key: "bh2_px_h_wilting_plant", start: 7.5, dur: 6.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h_wilting_plant.mp4" darken={0} /> },
  { key: "bh3_px_h2_fizz_hand", start: 13.01, dur: 6.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h2_fizz_hand.mp4" darken={0} /> },
  { key: "bh4_px_t1_compacted_soil", start: 18.52, dur: 6.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "bh5_px_t3_new_leaf", start: 24.07, dur: 1.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t3_new_leaf.mp4" darken={0} /> },
  { key: "bh6_px_t4_powdery", start: 25.53, dur: 1.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t4_powdery.mp4" darken={0} /> },
  { key: "bh7_px_h_wilting_plant", start: 27.09, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h_wilting_plant.mp4" darken={0} /> },
  { key: "bh8_px_t7_stale_water", start: 29.02, dur: 2.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t7_stale_water.mp4" darken={0} /> },
  { key: "bh9_px_h_wilting_plant", start: 30.99, dur: 2.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h_wilting_plant.mp4" darken={0} /> },
  { key: "bh10_px_y_birdbath", start: 32.96, dur: 2.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_y_birdbath.mp4" darken={0} /> },
  { key: "b1_px_h2_fizz_hand", start: 34.94, dur: 0.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h2_fizz_hand.mp4" darken={0} /> },
  { key: "bh11_px_h_pour_soil", start: 34.99, dur: 1.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h_pour_soil.mp4" darken={0} /> },
  { key: "b2_px_h2_question_garden", start: 36.16, dur: 0.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_h2_question_garden.png" darken={0} /> },
  { key: "bh12_px_p_houseplants", start: 36.94, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_p_houseplants.mp4" darken={0} /> },
  { key: "b3_px_h2_fizz_hand", start: 40.86, dur: 1.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h2_fizz_hand.mp4" darken={0} /> },
  { key: "cmp_loop", start: 41.94, dur: 8.58, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="!" title="El error que quema las plantas" desc="Casi todos lo cometen creyendo que ayudan. Mirá hasta el final." eyebrow="EN ESTE VIDEO" image="img/cmp_loop_bg.png" /> },
  { key: "b6_px_h2_question_garden", start: 50.52, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_h2_question_garden.png" darken={0} /> },
  { key: "b7_px_h2_fizz_hand", start: 54.18, dur: 1.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h2_fizz_hand.mp4" darken={0} /> },
  { key: "b8_px_h2_question_garden", start: 55.64, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_h2_question_garden.png" darken={0} /> },
  { key: "b9_px_h2_fizz_hand", start: 58.1, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_h2_fizz_hand.mp4" darken={0} /> },
  { key: "b10_px_h2_question_garden", start: 60.76, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/px_gf_amos_tomatoes.png" darken={0} /> },
  { key: "b11_px_v_store_shelf", start: 101.36, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/px_gf_neighbor_store.png" darken={0} /> },
  { key: "b12_px_v_dead_garden", start: 103.36, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_dead_garden.png" darken={0} /> },
  { key: "b13_px_v_money_waste", start: 105.54, dur: 2.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_money_waste.png" darken={0} /> },
  { key: "b14_px_v_store_shelf", start: 107.28, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_store_shelf.png" darken={0} /> },
  { key: "b15_px_v_dead_garden", start: 110.08, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_dead_garden.png" darken={0} /> },
  { key: "b16_px_v_money_waste", start: 112.76, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_money_waste.png" darken={0} /> },
  { key: "b17_px_v_store_shelf", start: 114.8, dur: 15.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_store_shelf.png" darken={0} /> },
  { key: "cmp_half_neighbor", start: 130.1, dur: 6.84, kind: "half", el: (d) => <HalfShot durationInFrames={d} src="real/px_v_dead_garden.png" side="left" kicker="El vecino compró\ntodo — y su huerta\nera un desastre" hue="amber" /> },
  { key: "cmp_cost_bars", start: 136.94, dur: 8.36, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Vivero: un frasco caro por problema","value":100,"display":"Camioneta llena","tone":"danger"},{"label":"Una botellita de agua oxigenada","value":4,"display":"$2, resuelve 7 cosas","winner":true}]} eyebrow="La diferencia no era la plata" title="El vecino vs el abuelo" accent="good" hue="amber" /> },
  { key: "b24_px_v_dead_garden", start: 145.3, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_dead_garden.png" darken={0} /> },
  { key: "b25_px_v_money_waste", start: 149.46, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_money_waste.png" darken={0} /> },
  { key: "b26_px_v_store_shelf", start: 151.56, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_v_store_shelf.png" darken={0} /> },
  { key: "b27_px_sc_water_glass", start: 153.9, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b28_px_sc_bubbles_o2", start: 155.7, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b29_px_sc_pharmacy", start: 157.58, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b30_px_sc_water_glass", start: 160.44, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "cmp_molecule", start: 162.92, dur: 9.12, kind: "perox", el: (d) => <PeroxidoDiagram durationInFrames={d} mode="molecule" title="Por qué funciona: un oxígeno de más" /> },
  { key: "b35_px_sc_pharmacy", start: 172.04, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b36_px_sc_water_glass", start: 174.12, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b37_px_sc_bubbles_o2", start: 175.96, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b38_px_sc_pharmacy", start: 178.34, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "cmp_fizz", start: 181.18, dur: 6.16, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="O₂" eyebrow="La espuma que ves" caption="es oxígeno puro liberándose, justo donde hace falta" accent="good" hue="amber" /> },
  { key: "b41_px_sc_pharmacy", start: 187.34, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b42_px_sc_water_glass", start: 190.84, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b43_px_sc_bubbles_o2", start: 192.56, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b44_px_sc_pharmacy", start: 195.54, dur: 2.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b45_px_sc_water_glass", start: 197.2, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b46_px_sc_bubbles_o2", start: 199.58, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b47_px_sc_pharmacy", start: 201.26, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b48_px_sc_water_glass", start: 205.44, dur: 2.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b49_px_sc_bubbles_o2", start: 207.08, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b50_px_sc_pharmacy", start: 209.32, dur: 2.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b51_px_sc_water_glass", start: 210.94, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b52_px_sc_bubbles_o2", start: 214.06, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b53_px_sc_pharmacy", start: 217.12, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b54_px_sc_water_glass", start: 220.22, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b55_px_sc_bubbles_o2", start: 222.88, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b56_px_sc_pharmacy", start: 225.68, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_pharmacy.png" darken={0} /> },
  { key: "b57_px_sc_water_glass", start: 228.76, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_water_glass.png" darken={0} /> },
  { key: "b58_px_sc_bubbles_o2", start: 230.92, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_sc_bubbles_o2.png" darken={0} /> },
  { key: "b59_px_t1_compacted_soil", start: 235.24, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b60_px_t1_roots_soil", start: 237.14, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_roots_soil.png" darken={0} /> },
  { key: "b61_px_t1_watering_can", start: 240.66, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "cmp_perox_roots", start: 242.6, dur: 8.1, kind: "perox", el: (d) => <PeroxidoDiagram durationInFrames={d} mode="roots" title="Las raíces respiran" /> },
  { key: "b65_px_t1_watering_can", start: 250.7, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b66_px_t1_seedling_perk", start: 254.06, dur: 5.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "cmp_ahogada", start: 259.44, dur: 7.06, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Ahogada se ve igual que con sed" items={["Hojas caídas y mustias","Le echás más agua","Y la terminás de hundir"]} accent={D} cross /> },
  { key: "b69_px_t1_watering_can", start: 266.5, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b70_px_t1_seedling_perk", start: 268.38, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b71_px_t1_compacted_soil", start: 271.68, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "cmp_dose1", start: 274.82, dur: 7.76, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="1 cda / 1 L" eyebrow="Truco 1 · oxigenar la tierra" caption="regás como siempre, cada 1 o 2 semanas" accent="good" hue="amber" /> },
  { key: "b73_px_t1_watering_can", start: 282.58, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b74_px_t1_seedling_perk", start: 286.94, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b75_px_t1_compacted_soil", start: 288.9, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b76_px_t1_roots_soil", start: 292.92, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_roots_soil.png" darken={0} /> },
  { key: "b77_px_t1_watering_can", start: 296.46, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b78_px_t1_seedling_perk", start: 299.06, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b79_px_t1_compacted_soil", start: 303.24, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b80_px_t2_seeds_hand", start: 307.34, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_seeds_hand.png" darken={0} /> },
  { key: "b81_px_t2_soak_bowl", start: 310.16, dur: 5.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_soak_bowl.png" darken={0} /> },
  { key: "b82_px_t2_sowing", start: 315.26, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_sowing.png" darken={0} /> },
  { key: "b83_px_t2_sprout_row", start: 318.22, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_sprout_row.png" darken={0} /> },
  { key: "b84_px_t2_seeds_hand", start: 321.76, dur: 7.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_seeds_hand.png" darken={0} /> },
  { key: "b85_px_t2_soak_bowl", start: 328.88, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_soak_bowl.png" darken={0} /> },
  { key: "cmp_seeds_two", start: 331.86, dur: 10.2, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Ablanda la cáscara dura"},{"title":"Mata los hongos que trae pegados"},{"title":"Brotan parejas y días antes"}]} eyebrow="Por qué germinan mejor" title="Dos cosas a la vez" accent="good" hue="amber" /> },
  { key: "cmp_dose2", start: 342.06, dur: 10.28, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="30 min" eyebrow="Truco 2 · despertar semillas" caption="remojo en pura, del 3%, y ni un minuto más" accent="good" hue="amber" /> },
  { key: "b91_px_t2_sprout_row", start: 352.34, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_sprout_row.png" darken={0} /> },
  { key: "b92_px_t2_seeds_hand", start: 357.94, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_seeds_hand.png" darken={0} /> },
  { key: "b93_px_t2_soak_bowl", start: 360.18, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_soak_bowl.png" darken={0} /> },
  { key: "b94_px_t2_sowing", start: 365.22, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_sowing.png" darken={0} /> },
  { key: "b95_px_t2_sprout_row", start: 368.48, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_sprout_row.png" darken={0} /> },
  { key: "b96_px_t2_seeds_hand", start: 370.68, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t2_seeds_hand.png" darken={0} /> },
  { key: "b97_px_t3_rootrot", start: 374.4, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_rootrot.png" darken={0} /> },
  { key: "b98_px_t3_overwater", start: 377.22, dur: 6.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_overwater.png" darken={0} /> },
  { key: "b99_px_t3_drench_soil", start: 383.08, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_drench_soil.png" darken={0} /> },
  { key: "b100_px_t3_new_leaf", start: 385.36, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t3_new_leaf.mp4" darken={0} /> },
  { key: "b101_px_t3_rootrot", start: 388.18, dur: 5.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_rootrot.png" darken={0} /> },
  { key: "b102_px_t3_overwater", start: 393.64, dur: 4.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_overwater.png" darken={0} /> },
  { key: "b103_px_t3_drench_soil", start: 398.1, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_drench_soil.png" darken={0} /> },
  { key: "b104_px_t3_new_leaf", start: 401.7, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t3_new_leaf.mp4" darken={0} /> },
  { key: "cmp_dose3", start: 403.98, dur: 10.58, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="1½ cda / 1 L" eyebrow="Truco 3 · raíz podrida" caption="empapá la tierra alrededor del tallo y dejá de regar" accent="danger" hue="amber" /> },
  { key: "b107_px_t3_drench_soil", start: 414.56, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_drench_soil.png" darken={0} /> },
  { key: "b108_px_t3_new_leaf", start: 416.64, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t3_new_leaf.mp4" darken={0} /> },
  { key: "b109_px_t3_rootrot", start: 419.76, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_rootrot.png" darken={0} /> },
  { key: "b110_px_t3_overwater", start: 422.14, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_overwater.png" darken={0} /> },
  { key: "b111_px_t3_drench_soil", start: 425.44, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_drench_soil.png" darken={0} /> },
  { key: "b112_px_t3_new_leaf", start: 428.72, dur: 5.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t3_new_leaf.mp4" darken={0} /> },
  { key: "b113_px_t3_rootrot", start: 433.68, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_rootrot.png" darken={0} /> },
  { key: "cmp_rescue_check", start: 436.08, dur: 8.26, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="¿Se salvó?" items={[{"text":"Día 1-3: sigue caída, es normal","state":"done"},{"text":"A la semana: frena la caída","state":"done"},{"text":"Aparece una hoja nueva = ganaste","state":"done"},{"text":"Ahora regá menos y mejor","state":"done"}]} eyebrow="Qué mirar" accent="good" hue="amber" /> },
  { key: "b116_px_t3_new_leaf", start: 444.34, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t3_new_leaf.mp4" darken={0} /> },
  { key: "b117_px_t3_rootrot", start: 447.84, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_rootrot.png" darken={0} /> },
  { key: "b118_px_t3_overwater", start: 451.04, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_overwater.png" darken={0} /> },
  { key: "b119_px_t3_drench_soil", start: 453.4, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_drench_soil.png" darken={0} /> },
  { key: "b120_px_t3_new_leaf", start: 455.46, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t3_new_leaf.mp4" darken={0} /> },
  { key: "b121_px_t3_rootrot", start: 458.32, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t3_rootrot.png" darken={0} /> },
  { key: "b122_px_t4_powdery", start: 460.6, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t4_powdery.mp4" darken={0} /> },
  { key: "b123_px_t4_spots", start: 463.42, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_spots.png" darken={0} /> },
  { key: "b124_px_t4_spray_bottle", start: 466.74, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_spray_bottle.png" darken={0} /> },
  { key: "b125_px_t4_morning_garden", start: 470.84, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_morning_garden.png" darken={0} /> },
  { key: "b126_px_t4_powdery", start: 474.14, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t4_powdery.mp4" darken={0} /> },
  { key: "cmp_dose4", start: 476.94, dur: 6.6, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="1 cda / 1 L" eyebrow="Truco 4 · hongos en hojas" caption="en rociador, arriba y abajo de la hoja" accent="good" hue="amber" /> },
  { key: "b129_px_t4_morning_garden", start: 483.54, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_morning_garden.png" darken={0} /> },
  { key: "b130_px_t4_powdery", start: 488.3, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t4_powdery.mp4" darken={0} /> },
  { key: "b131_px_t4_spots", start: 490.02, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_spots.png" darken={0} /> },
  { key: "cmp_sun_warn", start: 493.5, dur: 4.74, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_sun_warn_bg.png" impact="El sol lo vuelve veneno. Quema la hoja." setup="¿Rociás al mediodía?" impactAccent="danger" hitAt={1.1} boom={0} darken={0.5} /> },
  { key: "b134_px_t4_powdery", start: 498.24, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t4_powdery.mp4" darken={0} /> },
  { key: "b135_px_t4_spots", start: 501.24, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_spots.png" darken={0} /> },
  { key: "b136_px_t4_spray_bottle", start: 503.04, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_spray_bottle.png" darken={0} /> },
  { key: "b137_px_t4_morning_garden", start: 506.02, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t4_morning_garden.png" darken={0} /> },
  { key: "b138_px_t4_powdery", start: 511.7, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t4_powdery.mp4" darken={0} /> },
  { key: "b139_px_t5_pruning", start: 517.22, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_pruning.png" darken={0} /> },
  { key: "b140_px_t5_wipe_blade", start: 520.56, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_wipe_blade.png" darken={0} /> },
  { key: "b141_px_t5_dirty_pots", start: 524.12, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_dirty_pots.png" darken={0} /> },
  { key: "b142_px_t5_clean_pots", start: 526.16, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_clean_pots.png" darken={0} /> },
  { key: "cmp_tools_impact", start: 530.2, dur: 5.3, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_tools_impact_bg.png" impact="Vos mismo contagiás la huerta." setup="Podás enferma y después sana..." impactAccent="danger" hitAt={1.1} boom={0} darken={0.45} /> },
  { key: "b145_px_t5_dirty_pots", start: 535.5, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_dirty_pots.png" darken={0} /> },
  { key: "b146_px_t5_clean_pots", start: 537.76, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_clean_pots.png" darken={0} /> },
  { key: "b147_px_t5_pruning", start: 541.52, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_pruning.png" darken={0} /> },
  { key: "b148_px_t5_wipe_blade", start: 543.4, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_wipe_blade.png" darken={0} /> },
  { key: "cmp_tools_how", start: 547.16, dur: 9.28, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Desinfectar en 2 segundos" items={[{"text":"Trapito con pura en la tijera","state":"done"},{"text":"Entre planta y planta","state":"done"},{"text":"Macetas viejas en remojo","state":"done"},{"text":"Cepillás y enjuagás","state":"done"}]} eyebrow="Truco 5 · con pura" accent="good" hue="amber" /> },
  { key: "b152_px_t5_wipe_blade", start: 556.44, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_wipe_blade.png" darken={0} /> },
  { key: "b153_px_t5_dirty_pots", start: 560.32, dur: 9.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_dirty_pots.png" darken={0} /> },
  { key: "b154_px_t5_clean_pots", start: 569.02, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_clean_pots.png" darken={0} /> },
  { key: "b155_px_t5_pruning", start: 571.12, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t5_pruning.png" darken={0} /> },
  { key: "b156_px_t6_gnats", start: 575.62, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_gnats.png" darken={0} /> },
  { key: "b157_px_t6_soil_larvae", start: 577.58, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_soil_larvae.png" darken={0} /> },
  { key: "b158_px_t6_drench_pot", start: 579.64, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_drench_pot.png" darken={0} /> },
  { key: "cmp_gnats_split", start: 583.12, dur: 7.72, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Por qué no se terminan nunca" items={["Matás los que vuelan","Abajo nacen las larvas","Que se comen las raíces finas"]} accent={D} cross /> },
  { key: "b162_px_t6_gnats", start: 590.84, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_gnats.png" darken={0} /> },
  { key: "b163_px_t6_soil_larvae", start: 594.4, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_soil_larvae.png" darken={0} /> },
  { key: "b164_px_t6_drench_pot", start: 596.66, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_drench_pot.png" darken={0} /> },
  { key: "b165_px_t6_gnats", start: 598.48, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_gnats.png" darken={0} /> },
  { key: "b166_px_t6_soil_larvae", start: 600.92, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_soil_larvae.png" darken={0} /> },
  { key: "cmp_dose6", start: 602.96, dur: 8.58, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="1 cda / 1 L" eyebrow="Truco 6 · mosca del sustrato" caption="empapás la tierra, repetís 1-2 semanas, se corta de raíz" accent="good" hue="amber" /> },
  { key: "b169_px_t6_soil_larvae", start: 611.54, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_soil_larvae.png" darken={0} /> },
  { key: "b170_px_t6_drench_pot", start: 614.5, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_drench_pot.png" darken={0} /> },
  { key: "b171_px_t6_gnats", start: 616.56, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_gnats.png" darken={0} /> },
  { key: "b172_px_t6_soil_larvae", start: 618.96, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_soil_larvae.png" darken={0} /> },
  { key: "b173_px_t6_drench_pot", start: 620.72, dur: 5.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t6_drench_pot.png" darken={0} /> },
  { key: "b174_px_t7_stale_water", start: 625.5, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t7_stale_water.mp4" darken={0} /> },
  { key: "b175_px_t7_rain_barrel", start: 627.46, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t7_rain_barrel.png" darken={0} /> },
  { key: "b176_px_t7_fresh_stream", start: 631.4, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t7_fresh_stream.png" darken={0} /> },
  { key: "b177_px_t7_strong_roots", start: 633.2, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t7_strong_roots.png" darken={0} /> },
  { key: "b178_px_t7_stale_water", start: 635.74, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t7_stale_water.mp4" darken={0} /> },
  { key: "cmp_dose7", start: 638.54, dur: 6.42, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="1 cda / 4 L" eyebrow="Truco 7 · agua de riego viva" caption="un chorrito siempre: reoxigena el agua estancada" accent="good" hue="amber" /> },
  { key: "b182_px_t7_stale_water", start: 644.96, dur: 5.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t7_stale_water.mp4" darken={0} /> },
  { key: "b183_px_t7_rain_barrel", start: 650.08, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t7_rain_barrel.png" darken={0} /> },
  { key: "cmp_water_bars", start: 652.84, dur: 8.38, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Agua estancada del balde","value":100,"display":"Raíces débiles","tone":"danger"},{"label":"Agua reoxigenada","value":100,"display":"Raíces fuertes y blancas","winner":true}]} eyebrow="Lo que cambia en la raíz" title="Agua muerta vs agua viva" accent="good" hue="amber" /> },
  { key: "b188_px_t7_fresh_stream", start: 661.22, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t7_fresh_stream.png" darken={0} /> },
  { key: "b189_px_t7_strong_roots", start: 663.38, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t7_strong_roots.png" darken={0} /> },
  { key: "b190_px_t7_stale_water", start: 667.92, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t7_stale_water.mp4" darken={0} /> },
  { key: "b191_px_t7_rain_barrel", start: 669.98, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t7_rain_barrel.png" darken={0} /> },
  { key: "b192_px_y_flowers_vase", start: 673.3, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_y_flowers_vase.png" darken={0} /> },
  { key: "b193_px_y_birdbath", start: 675.86, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_y_birdbath.mp4" darken={0} /> },
  { key: "b194_px_y_flowers_vase", start: 678.68, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_y_flowers_vase.png" darken={0} /> },
  { key: "b195_px_y_birdbath", start: 683.84, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_y_birdbath.mp4" darken={0} /> },
  { key: "b196_px_y_flowers_vase", start: 685.8, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_y_flowers_vase.png" darken={0} /> },
  { key: "b197_px_y_birdbath", start: 690.18, dur: 5.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_y_birdbath.mp4" darken={0} /> },
  { key: "b198_px_y_flowers_vase", start: 695.52, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_y_flowers_vase.png" darken={0} /> },
  { key: "b199_px_y_birdbath", start: 698.56, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_y_birdbath.mp4" darken={0} /> },
  { key: "b200_px_y_flowers_vase", start: 701.56, dur: 13.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_y_flowers_vase.png" darken={0} /> },
  { key: "b201_px_y_birdbath", start: 714.9, dur: 1.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_y_birdbath.mp4" darken={0} /> },
  { key: "b202_px_p_tomatoes", start: 716.06, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_p_tomatoes.png" darken={0} /> },
  { key: "b203_px_p_houseplants", start: 719.66, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_p_houseplants.mp4" darken={0} /> },
  { key: "b204_px_p_lettuce", start: 723.48, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_p_lettuce.mp4" darken={0} /> },
  { key: "b205_px_p_tomatoes", start: 727.46, dur: 6.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_p_tomatoes.png" darken={0} /> },
  { key: "b206_px_p_houseplants", start: 733.1, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_p_houseplants.mp4" darken={0} /> },
  { key: "b207_px_p_lettuce", start: 735.86, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_p_lettuce.mp4" darken={0} /> },
  { key: "b208_px_p_tomatoes", start: 738.7, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_p_tomatoes.png" darken={0} /> },
  { key: "b209_px_p_houseplants", start: 741.68, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_p_houseplants.mp4" darken={0} /> },
  { key: "b210_px_p_lettuce", start: 743.86, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_p_lettuce.mp4" darken={0} /> },
  { key: "cmp_focus_saved", start: 747.74, dur: 2, kind: "focuscard", el: (d) => <FocusCard durationInFrames={d} bg="img/px_gf_tomato_saved.png" image="img/px_gf_tomato_saved.png" title="Volvió a los 4 días" desc="No tenía sed: se estaba ahogando. La tierra también se cura." eyebrow="Mi primer tomate salvado" imageSide="right" accent="good" /> },
  { key: "cmp_anno_finger", start: 749.74, dur: 1.92, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/px_gf_amos_finger_soil.png" annotations={[{"kind":"circle","x":0.5,"y":0.55,"w":0.26,"label":"Meté el dedo hasta abajo","color":"amber"},{"kind":"arrow","x":0.5,"y":0.6,"fromX":0.82,"fromY":0.12,"label":"Si está mojada, no tiene sed: se ahoga","color":"good"}]} eyebrow="La prueba del abuelo" hue="amber" /> },
  { key: "b213_px_e_measuring", start: 797.68, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "b214_px_e_burnt_leaf", start: 799.48, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_burnt_leaf.png" darken={0} /> },
  { key: "b215_px_e_hot_sun", start: 801.74, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_hot_sun.png" darken={0} /> },
  { key: "b216_px_e_measuring", start: 804.88, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "b217_px_e_burnt_leaf", start: 807.98, dur: 2.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_burnt_leaf.png" darken={0} /> },
  { key: "b218_px_e_hot_sun", start: 809.64, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_hot_sun.png" darken={0} /> },
  { key: "b219_px_e_measuring", start: 812.28, dur: 2.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "b220_px_e_burnt_leaf", start: 813.9, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_burnt_leaf.png" darken={0} /> },
  { key: "cmp_error_impact", start: 816, dur: 4.78, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_error_impact_bg.png" impact="De más, quema los pelitos de la raíz." setup="¿Más es mejor?" impactAccent="danger" hitAt={1.1} boom={0} darken={0.5} /> },
  { key: "b222_px_e_measuring", start: 820.78, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "b223_px_e_burnt_leaf", start: 822.8, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_burnt_leaf.png" darken={0} /> },
  { key: "b224_px_e_hot_sun", start: 825.38, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_hot_sun.png" darken={0} /> },
  { key: "b225_px_e_measuring", start: 827.8, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "cmp_dose_rule", start: 830.22, dur: 6.02, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="1 cda / 1 L" eyebrow="La regla de oro" caption="las dosis son bajas a propósito: es una medicina, respetá la dosis" accent="danger" hue="amber" /> },
  { key: "b228_px_e_measuring", start: 836.24, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "b229_px_e_burnt_leaf", start: 837.84, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_burnt_leaf.png" darken={0} /> },
  { key: "b230_px_e_hot_sun", start: 840.32, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_hot_sun.png" darken={0} /> },
  { key: "b231_px_e_measuring", start: 843.68, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "b232_px_e_burnt_leaf", start: 846.62, dur: 5.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_burnt_leaf.png" darken={0} /> },
  { key: "b233_px_e_hot_sun", start: 851.68, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_hot_sun.png" darken={0} /> },
  { key: "b234_px_e_measuring", start: 853.82, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "b235_px_e_burnt_leaf", start: 857.6, dur: 2.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_burnt_leaf.png" darken={0} /> },
  { key: "b236_px_e_hot_sun", start: 859.46, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_hot_sun.png" darken={0} /> },
  { key: "b237_px_e_measuring", start: 862.26, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_e_measuring.png" darken={0} /> },
  { key: "cmp_myths", start: 865.12, dur: 7.68, kind: "lielist", el: (d) => <LieList durationInFrames={d} title="3 mitos del agua oxigenada" items={["No es un fertilizante (es el botiquín)","No sirve la industrial fuerte","No dura para siempre: se degrada con la luz"]} accent="danger" /> },
  { key: "b241_px_m_pantry", start: 872.8, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b242_px_m_dark_bottle", start: 875.46, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b243_px_m_fizz_test", start: 877.62, dur: 2.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b244_px_m_pantry", start: 879.4, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b245_px_m_dark_bottle", start: 881.52, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b246_px_m_fizz_test", start: 883.82, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "cmp_fizztest", start: 886.58, dur: 6.68, kind: "focuscard", el: (d) => <FocusCard durationInFrames={d} bg="img/cmp_fizztest_bg.png" image="img/cmp_fizztest_bg.png" title="La prueba del burbujeo" desc="Un chorrito en la bacha: si burbujea, está viva; si queda quieta, está muerta." eyebrow="¿Todavía sirve?" imageSide="right" accent="good" /> },
  { key: "b250_px_m_pantry", start: 893.26, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b251_px_m_dark_bottle", start: 896.06, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b252_px_m_fizz_test", start: 899.1, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b253_px_m_pantry", start: 901.46, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b254_px_m_dark_bottle", start: 904.96, dur: 2.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b255_px_m_fizz_test", start: 906.7, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b256_px_m_pantry", start: 909.7, dur: 5.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b257_px_m_dark_bottle", start: 914.94, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b258_px_m_fizz_test", start: 917.06, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b259_px_m_pantry", start: 921.14, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b260_px_m_dark_bottle", start: 923.7, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b261_px_m_fizz_test", start: 926.5, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b262_px_m_pantry", start: 931.34, dur: 2.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b263_px_m_dark_bottle", start: 933.2, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b264_px_m_fizz_test", start: 936.54, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b265_px_m_pantry", start: 938.6, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b266_px_m_dark_bottle", start: 941.72, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b267_px_m_fizz_test", start: 943.6, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b268_px_m_pantry", start: 945.64, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b269_px_m_dark_bottle", start: 949.76, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b270_px_m_fizz_test", start: 951.86, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b271_px_m_pantry", start: 956.24, dur: 2.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b272_px_m_dark_bottle", start: 958.1, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "cmp_free", start: 961.04, dur: 9.8, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$2" eyebrow="Todo esto salió de" caption="una botellita que ya tenías tirada en el baño — cero vivero" accent="good" hue="amber" /> },
  { key: "b275_px_m_dark_bottle", start: 970.84, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b276_px_m_fizz_test", start: 973.26, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "b277_px_m_pantry", start: 977.06, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_pantry.png" darken={0} /> },
  { key: "b278_px_m_dark_bottle", start: 979.92, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_dark_bottle.png" darken={0} /> },
  { key: "b279_px_m_fizz_test", start: 983.44, dur: 1.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_m_fizz_test.png" darken={0} /> },
  { key: "cmp_recap", start: 984.76, dur: 9.86, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Los 7, redonditos" items={[{"text":"1 · Oxigenar la tierra encharcada","state":"done"},{"text":"2 · Despertar semillas (remojo 30 min)","state":"done"},{"text":"3 · Salvar la raíz podrida","state":"done"},{"text":"4 · Hongos en hojas (jamás al sol)","state":"done"},{"text":"5 · Desinfectar tijeras y macetas","state":"done"},{"text":"6 · Larvas de mosquitos del sustrato","state":"done"},{"text":"7 · Agua de riego más viva","state":"done"}]} eyebrow="Guardá el video" accent="good" hue="amber" /> },
  { key: "b283_px_t1_seedling_perk", start: 994.62, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b284_px_t1_compacted_soil", start: 996.64, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b285_px_t1_roots_soil", start: 999.04, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_roots_soil.png" darken={0} /> },
  { key: "b286_px_t1_watering_can", start: 1003.04, dur: 2.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b287_px_t1_seedling_perk", start: 1004.98, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b288_px_t1_compacted_soil", start: 1009.18, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b289_px_t1_roots_soil", start: 1011.5, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_roots_soil.png" darken={0} /> },
  { key: "b290_px_t1_watering_can", start: 1013.64, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b291_px_t1_seedling_perk", start: 1016.84, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b292_px_t1_compacted_soil", start: 1019.38, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b293_px_t1_roots_soil", start: 1022.48, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_roots_soil.png" darken={0} /> },
  { key: "b294_px_t1_watering_can", start: 1025.44, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b295_px_t1_seedling_perk", start: 1029.18, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b296_px_t1_compacted_soil", start: 1032.02, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b297_px_t1_roots_soil", start: 1036.56, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_roots_soil.png" darken={0} /> },
  { key: "b298_px_t1_watering_can", start: 1038.44, dur: 4.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
  { key: "b299_px_t1_seedling_perk", start: 1042.08, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_seedling_perk.png" darken={0} /> },
  { key: "b300_px_t1_compacted_soil", start: 1044.28, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/px_t1_compacted_soil.mp4" darken={0} /> },
  { key: "b301_px_t1_roots_soil", start: 1047.36, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_roots_soil.png" darken={0} /> },
  { key: "b302_px_t1_watering_can", start: 1051.6, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/px_t1_watering_can.png" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "kl3", start: 807.98, dur: 2.06, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"más","at":0},{"t":"es","at":0.16},{"t":"mejor.","at":0.36,"hl":true}]} accent="amber" /> },
];
