// cues_jardin.gen.tsx — GENERADO por beatsheet.mjs desde jardin.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/jardin.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { PremiumOverlay } from "./scenes/PremiumOverlay";
import { VsDuel, BigStatReveal, PullQuote, MythTruth, FlowSteps, FramedPhoto, HighlightSweep, ChecklistReveal, NumberedSteps, BulletCascade, CtaCard, SplitPanel, BeforeAfter, THEME_EARTH } from "./kit/premium";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "jd_s_001", start: 0.13, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_001.mp4" hue="amber" darken={0} clipDur={20.48} /> },
  { key: "jd_s_001_b", start: 3.38, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_001_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_002", start: 6.14, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_002.mp4" hue="amber" darken={0} clipDur={35.29} /> },
  { key: "jd_s_002_b", start: 8.8, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_002_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_002_c", start: 11.75, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_002_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_003", start: 13.46, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_003.png" hue="amber" darken={0} /> },
  { key: "jd_s_003_b", start: 16.44, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_003_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_003_c", start: 19.24, dur: 2.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_003_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_004", start: 21.2, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_004.mp4" hue="amber" darken={0} clipDur={48.55} /> },
  { key: "jd_s_004_b", start: 23.94, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_004_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_005", start: 28.28, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_005.png" hue="amber" darken={0} /> },
  { key: "jd_s_005_b", start: 31.66, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_005_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_006", start: 34.12, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_006.mp4" hue="amber" darken={0} clipDur={8.2} /> },
  { key: "jd_s_006_b", start: 37.4, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_006_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_006_c", start: 40.07, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_006_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_007", start: 41.78, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_007.png" hue="amber" darken={0} /> },
  { key: "jd_s_007_b", start: 44.38, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_007_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_007_c", start: 47.43, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_007_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_008", start: 49.69, dur: 4.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_008.mp4" hue="amber" darken={0} clipDur={46.01} /> },
  { key: "jd_s_008_b", start: 53.64, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_008_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_009", start: 56.44, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_009.png" hue="amber" darken={0} /> },
  { key: "jd_s_009_b", start: 59.74, dur: 2.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_009_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_010", start: 61.88, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_010.png" hue="amber" darken={0} /> },
  { key: "jd_s_010_b", start: 64.49, dur: 5.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_010_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_011", start: 69.26, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_011.png" hue="amber" darken={0} /> },
  { key: "jd_s_011_b", start: 72.06, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_011_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_011_c", start: 74.92, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_011_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_012", start: 76.9, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_012.png" hue="amber" darken={0} /> },
  { key: "jd_s_012_b", start: 79.71, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_012_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_012_c", start: 82.48, dur: 2.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_012_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_013", start: 84.9, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_013.png" hue="amber" darken={0} /> },
  { key: "jd_s_013_b", start: 87.8, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_013_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_013_c", start: 90.44, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_013_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_014", start: 93.83, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_014.png" hue="amber" darken={0} /> },
  { key: "jd_s_014_b", start: 96.45, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_014_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_015", start: 99.33, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_015.png" hue="amber" darken={0} /> },
  { key: "jd_s_015_b", start: 101.97, dur: 2.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_015_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_016", start: 103.96, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_016.png" hue="amber" darken={0} /> },
  { key: "jd_s_016_b", start: 106.79, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_016_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_017", start: 109.72, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_017.mp4" hue="amber" darken={0} clipDur={51.25} /> },
  { key: "jd_s_017_b", start: 112.6, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_017_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_018", start: 114.39, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_018.mp4" hue="amber" darken={0} clipDur={35.58} /> },
  { key: "jd_s_018_b", start: 117.02, dur: 2.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_018_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_019", start: 119.16, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_019.png" hue="amber" darken={0} /> },
  { key: "jd_s_019_b", start: 122.08, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_019_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_020", start: 126.6, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_020.mp4" hue="amber" darken={0} clipDur={54.04} /> },
  { key: "jd_s_020_b", start: 129.47, dur: 4.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_020_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_021", start: 133.48, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_021.png" hue="amber" darken={0} /> },
  { key: "jd_s_021_b", start: 136.52, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_021_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_022", start: 139.3, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_022.mp4" hue="amber" darken={0} clipDur={20.72} /> },
  { key: "jd_s_022_b", start: 142.46, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_022_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_023", start: 144.36, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_023.png" hue="amber" darken={0} /> },
  { key: "jd_s_023_b", start: 147.27, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_023_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_024", start: 150.52, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_024.png" hue="amber" darken={0} /> },
  { key: "jd_s_024_b", start: 153.28, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_024_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_025", start: 156.71, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_025.mp4" hue="amber" darken={0} clipDur={12.51} /> },
  { key: "jd_s_025_b", start: 159.31, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_025_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_025_c", start: 161.94, dur: 2.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_025_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_026", start: 164.21, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_026.mp4" hue="amber" darken={0} clipDur={9.24} /> },
  { key: "jd_s_026_b", start: 166.89, dur: 2.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_026_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_027", start: 169.14, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_027.png" hue="amber" darken={0} /> },
  { key: "jd_s_027_b", start: 171.85, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_027_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_028", start: 173.97, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_028.png" hue="amber" darken={0} /> },
  { key: "jd_s_028_b", start: 177.22, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_028_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_029", start: 180.4, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_029.png" hue="amber" darken={0} /> },
  { key: "jd_s_029_b", start: 183.23, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_029_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_030", start: 187.45, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_030.png" hue="amber" darken={0} /> },
  { key: "jd_s_030_b", start: 190.3, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_030_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_031", start: 194.36, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_031.png" hue="amber" darken={0} /> },
  { key: "jd_s_031_b", start: 197.4, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_031_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_031_c", start: 200.04, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_031_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_032", start: 202.28, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_032.png" hue="amber" darken={0} /> },
  { key: "jd_s_032_b", start: 205.04, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_032_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_033", start: 207.64, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_033.png" hue="amber" darken={0} /> },
  { key: "jd_s_033_b", start: 210.25, dur: 2.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_033_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_034", start: 212.48, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_034.png" hue="amber" darken={0} /> },
  { key: "jd_s_034_b", start: 215.36, dur: 3.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_034_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_035", start: 218.65, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_035.mp4" hue="amber" darken={0} clipDur={5.51} /> },
  { key: "jd_s_035_b", start: 222, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_035_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_035_c", start: 224.65, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_035_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_036", start: 226.55, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_036.mp4" hue="amber" darken={0} clipDur={14.37} /> },
  { key: "jd_s_036_b", start: 229.21, dur: 4.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_036_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_037", start: 233.22, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_037.mp4" hue="amber" darken={0} clipDur={20.02} /> },
  { key: "jd_s_037_b", start: 236.29, dur: 3.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_037_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_038", start: 239.9, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_038.png" hue="amber" darken={0} /> },
  { key: "jd_s_038_b", start: 242.53, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_038_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_039", start: 246.03, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_039.png" hue="amber" darken={0} /> },
  { key: "jd_s_039_b", start: 249.04, dur: 4.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_039_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_040", start: 252.77, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_040.png" hue="amber" darken={0} /> },
  { key: "jd_s_040_b", start: 256.16, dur: 2.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_040_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_041", start: 258.45, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_041.mp4" hue="amber" darken={0} clipDur={9.16} /> },
  { key: "jd_s_041_b", start: 261.27, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_041_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_042", start: 263.38, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_042.png" hue="amber" darken={0} /> },
  { key: "jd_s_042_b", start: 266.03, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_042_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_043", start: 268.74, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_043.png" hue="amber" darken={0} /> },
  { key: "jd_s_043_b", start: 271.68, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_043_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_044", start: 275.36, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_044.mp4" hue="amber" darken={0} clipDur={13.85} /> },
  { key: "jd_s_044_b", start: 278.04, dur: 4.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_044_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_045", start: 282.08, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_045.png" hue="amber" darken={0} /> },
  { key: "jd_s_045_b", start: 285.04, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_045_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_046", start: 289.32, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_046.png" hue="amber" darken={0} /> },
  { key: "jd_s_046_b", start: 291.94, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_046_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_046_c", start: 294.83, dur: 2.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_046_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_047", start: 297.08, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_047.png" hue="amber" darken={0} /> },
  { key: "jd_s_047_b", start: 300.09, dur: 2.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_047_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_048", start: 301.92, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_048.mp4" hue="amber" darken={0} clipDur={20} /> },
  { key: "jd_s_048_b", start: 304.61, dur: 2.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_048_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_049", start: 306.77, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_049.png" hue="amber" darken={0} /> },
  { key: "jd_s_049_b", start: 309.6, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_049_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_050", start: 313.52, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_050.mp4" hue="amber" darken={0} clipDur={7.64} /> },
  { key: "jd_s_050_b", start: 316.44, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_050_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_051", start: 319.75, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_051.png" hue="amber" darken={0} /> },
  { key: "jd_s_051_b", start: 322.49, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_051_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_052", start: 326.66, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_052.mp4" hue="amber" darken={0} clipDur={18.89} /> },
  { key: "jd_s_052_b", start: 329.91, dur: 2.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_052_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_053", start: 332.16, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_053.png" hue="amber" darken={0} /> },
  { key: "jd_s_053_b", start: 335.03, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_053_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_054", start: 339.28, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_054.png" hue="amber" darken={0} /> },
  { key: "jd_s_054_b", start: 341.95, dur: 2.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_054_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_055", start: 344.36, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_055.png" hue="amber" darken={0} /> },
  { key: "jd_s_055_b", start: 347.55, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_055_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_056", start: 350.23, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_056.png" hue="amber" darken={0} /> },
  { key: "jd_s_056_b", start: 352.92, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_056_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_057", start: 354.92, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_057.png" hue="amber" darken={0} /> },
  { key: "jd_s_057_b", start: 357.56, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_057_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_058", start: 361.82, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_058.mp4" hue="amber" darken={0} clipDur={6.12} /> },
  { key: "jd_s_058_b", start: 364.61, dur: 2.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_058_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_059", start: 366.39, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_059.png" hue="amber" darken={0} /> },
  { key: "jd_s_059_b", start: 369.17, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_059_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_060", start: 373.19, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_060.png" hue="amber" darken={0} /> },
  { key: "jd_s_060_b", start: 376.11, dur: 3.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_060_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_061", start: 379.8, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_061.png" hue="amber" darken={0} /> },
  { key: "jd_s_061_b", start: 382.59, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_061_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_062", start: 386.71, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_062.png" hue="amber" darken={0} /> },
  { key: "jd_s_062_b", start: 389.39, dur: 4.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_062_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_063", start: 393.52, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_063.png" hue="amber" darken={0} /> },
  { key: "jd_s_063_b", start: 396.3, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_063_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_064", start: 398.45, dur: 4.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_064.mp4" hue="amber" darken={0} clipDur={9.53} /> },
  { key: "jd_s_065", start: 403, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_065.png" hue="amber" darken={0} /> },
  { key: "jd_s_065_b", start: 405.72, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_065_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_066", start: 409.27, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_066.mp4" hue="amber" darken={0} clipDur={21.65} /> },
  { key: "jd_s_066_b", start: 412.22, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_066_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_066_c", start: 415.02, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_066_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_067", start: 416.81, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_067.png" hue="amber" darken={0} /> },
  { key: "jd_s_067_b", start: 419.62, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_067_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_068", start: 424, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_068.png" hue="amber" darken={0} /> },
  { key: "jd_s_068_b", start: 426.63, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_068_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_069", start: 429.41, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_069.png" hue="amber" darken={0} /> },
  { key: "jd_s_069_b", start: 432.55, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_069_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_070", start: 435.2, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_070.png" hue="amber" darken={0} /> },
  { key: "jd_s_070_b", start: 438.01, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_070_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_071", start: 441.37, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_071.png" hue="amber" darken={0} /> },
  { key: "jd_s_071_b", start: 444.21, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_071_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_071_c", start: 446.86, dur: 2.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_071_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_072", start: 448.77, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_072.mp4" hue="amber" darken={0} clipDur={9.32} /> },
  { key: "jd_s_072_b", start: 451.4, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_072_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_072_c", start: 454.18, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_072_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_073", start: 456.86, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_073.png" hue="amber" darken={0} /> },
  { key: "jd_s_073_b", start: 459.49, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_073_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_074", start: 462.36, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_074.png" hue="amber" darken={0} /> },
  { key: "jd_s_074_b", start: 465.13, dur: 4.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_074_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_075", start: 468.86, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_075.png" hue="amber" darken={0} /> },
  { key: "jd_s_075_b", start: 471.52, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_075_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_076", start: 474.76, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_076.mp4" hue="amber" darken={0} clipDur={28.92} /> },
  { key: "jd_s_076_b", start: 477.43, dur: 2.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_076_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_077", start: 479.47, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_077.png" hue="amber" darken={0} /> },
  { key: "jd_s_077_b", start: 482.36, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_077_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_077_c", start: 485.06, dur: 2.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_077_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_078", start: 487.48, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_078.png" hue="amber" darken={0} /> },
  { key: "jd_s_078_b", start: 490.14, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_078_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_079", start: 493.08, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_079.png" hue="amber" darken={0} /> },
  { key: "jd_s_079_b", start: 495.71, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_079_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_079_c", start: 498.39, dur: 2.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_079_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_080", start: 500.35, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_080.png" hue="amber" darken={0} /> },
  { key: "jd_s_080_b", start: 503.33, dur: 3.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_080_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_081", start: 506.62, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_081.png" hue="amber" darken={0} /> },
  { key: "jd_s_081_b", start: 509.38, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_081_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_081_c", start: 512.01, dur: 2.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_081_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_082", start: 514.05, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_082.png" hue="amber" darken={0} /> },
  { key: "jd_s_082_b", start: 517.04, dur: 4.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_082_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_083", start: 521.19, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_083.png" hue="amber" darken={0} /> },
  { key: "jd_s_083_b", start: 524.12, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_083_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_084", start: 527.63, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_084.mp4" hue="amber" darken={0} clipDur={11.72} /> },
  { key: "jd_s_084_b", start: 530.49, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_084_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_085", start: 534.16, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_085.mp4" hue="amber" darken={0} clipDur={16.72} /> },
  { key: "jd_s_085_b", start: 536.77, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_085_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_085_c", start: 539.75, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_085_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_086", start: 542.6, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_086.mp4" hue="amber" darken={0} clipDur={10.67} /> },
  { key: "jd_s_086_b", start: 545.2, dur: 3.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_086_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_087", start: 548.69, dur: 3.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_087.mp4" hue="amber" darken={0} clipDur={7.76} /> },
  { key: "jd_s_087_b", start: 551.98, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_087_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_088", start: 553.72, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_088.png" hue="amber" darken={0} /> },
  { key: "jd_s_088_b", start: 556.49, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_088_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_089", start: 559.75, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_089.png" hue="amber" darken={0} /> },
  { key: "jd_s_089_b", start: 562.58, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_089_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_090", start: 565.08, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_090.mp4" hue="amber" darken={0} clipDur={21.58} /> },
  { key: "jd_s_090_b", start: 567.96, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_090_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_090_c", start: 571.34, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_090_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_091", start: 574.37, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_091.png" hue="amber" darken={0} /> },
  { key: "jd_s_091_b", start: 577.3, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_091_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_091_c", start: 579.91, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_091_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_092", start: 584.03, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_092.png" hue="amber" darken={0} /> },
  { key: "jd_s_092_b", start: 586.78, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_092_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_092_c", start: 589.41, dur: 2.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_092_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_093", start: 591.28, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_093.png" hue="amber" darken={0} /> },
  { key: "jd_s_093_b", start: 593.95, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_093_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_093_c", start: 596.67, dur: 2.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_093_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_094", start: 599.18, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_094.png" hue="amber" darken={0} /> },
  { key: "jd_s_094_b", start: 601.8, dur: 4.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_094_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_095", start: 606.29, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_095.png" hue="amber" darken={0} /> },
  { key: "jd_s_095_b", start: 608.95, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_095_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_096", start: 613.09, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_096.mp4" hue="amber" darken={0} clipDur={55.26} /> },
  { key: "jd_s_096_b", start: 615.93, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_096_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_097", start: 618.6, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_097.mp4" hue="amber" darken={0} clipDur={17.33} /> },
  { key: "jd_s_097_b", start: 621.76, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_097_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_097_c", start: 624.4, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_097_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_098", start: 627.45, dur: 3.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_098.mp4" hue="amber" darken={0} clipDur={6.88} /> },
  { key: "jd_s_098_b", start: 630.54, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_098_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_098_c", start: 633.19, dur: 2.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_098_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_099", start: 635.15, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_099.png" hue="amber" darken={0} /> },
  { key: "jd_s_099_b", start: 637.76, dur: 4.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_099_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_100", start: 642.29, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_100.mp4" hue="amber" darken={0} clipDur={14.6} /> },
  { key: "jd_s_100_b", start: 644.97, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_100_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_101", start: 649.39, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_101.png" hue="amber" darken={0} /> },
  { key: "jd_s_101_b", start: 652.01, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_101_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_102", start: 656.51, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_102.png" hue="amber" darken={0} /> },
  { key: "jd_s_102_b", start: 659.23, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_102_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_102_c", start: 661.87, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_102_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_103", start: 664.95, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_103.png" hue="amber" darken={0} /> },
  { key: "jd_s_103_b", start: 667.68, dur: 4.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_103_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_104", start: 671.59, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_104.png" hue="amber" darken={0} /> },
  { key: "jd_s_104_b", start: 674.28, dur: 4.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_104_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_105", start: 678.07, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_105.png" hue="amber" darken={0} /> },
  { key: "jd_s_105_b", start: 680.72, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_105_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_106", start: 684.64, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_106.png" hue="amber" darken={0} /> },
  { key: "jd_s_106_b", start: 687.6, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_106_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_106_c", start: 690.23, dur: 2.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_106_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_107", start: 692.16, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_107.png" hue="amber" darken={0} /> },
  { key: "jd_s_107_b", start: 694.77, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_107_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_107_c", start: 697.38, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_107_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_108", start: 700.24, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_108.png" hue="amber" darken={0} /> },
  { key: "jd_s_108_b", start: 703.01, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_108_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_109", start: 704.86, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_109.mp4" hue="amber" darken={0} clipDur={11.96} /> },
  { key: "jd_s_109_b", start: 707.54, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_109_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_110", start: 710.84, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_110.png" hue="amber" darken={0} /> },
  { key: "jd_s_110_b", start: 713.52, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_110_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_111", start: 717.68, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_111.png" hue="amber" darken={0} /> },
  { key: "jd_s_111_b", start: 720.28, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_111_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_112", start: 722.92, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_112.png" hue="amber" darken={0} /> },
  { key: "jd_s_112_b", start: 725.64, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_112_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_112_c", start: 728.28, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_112_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_113", start: 731.32, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_113.png" hue="amber" darken={0} /> },
  { key: "jd_s_113_b", start: 734.08, dur: 2.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_113_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_114", start: 736.12, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_114.png" hue="amber" darken={0} /> },
  { key: "jd_s_114_b", start: 738.87, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_114_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_115", start: 743.12, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_115.png" hue="amber" darken={0} /> },
  { key: "jd_s_115_b", start: 745.85, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_115_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_115_c", start: 748.73, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_115_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_115_d", start: 751.49, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_115_d.png" hue="amber" darken={0} /> },
  { key: "jd_s_116", start: 753.85, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_116.mp4" hue="amber" darken={0} clipDur={50.88} /> },
  { key: "jd_s_116_b", start: 756.55, dur: 4.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_116_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_117", start: 761.08, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_117.mp4" hue="amber" darken={0} clipDur={30.83} /> },
  { key: "jd_s_117_b", start: 763.89, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_117_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_118", start: 766.64, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_118.mp4" hue="amber" darken={0} clipDur={11.22} /> },
  { key: "jd_s_118_b", start: 770.08, dur: 4.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_118_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_119", start: 774.11, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_119.png" hue="amber" darken={0} /> },
  { key: "jd_s_119_b", start: 776.8, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_119_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_120", start: 779.93, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_120.png" hue="amber" darken={0} /> },
  { key: "jd_s_120_b", start: 782.81, dur: 2.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_120_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_121", start: 785.12, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_121.mp4" hue="amber" darken={0} clipDur={17.28} /> },
  { key: "jd_s_121_b", start: 787.84, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_121_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_121_c", start: 790.46, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_121_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_122", start: 793.29, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_122.mp4" hue="amber" darken={0} clipDur={17.02} /> },
  { key: "jd_s_122_b", start: 795.93, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_122_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_123", start: 798.37, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_123.mp4" hue="amber" darken={0} clipDur={6.85} /> },
  { key: "jd_s_123_b", start: 801.42, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_123_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_124", start: 804.56, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_124.mp4" hue="amber" darken={0} clipDur={10.44} /> },
  { key: "jd_s_124_b", start: 807.33, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_124_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_124_c", start: 810.12, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_124_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_125", start: 814.29, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_125.mp4" hue="amber" darken={0} clipDur={20.45} /> },
  { key: "jd_s_125_b", start: 817.04, dur: 2.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_125_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_126", start: 819.49, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_126.mp4" hue="amber" darken={0} clipDur={12.8} /> },
  { key: "jd_s_126_b", start: 822.1, dur: 4.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_126_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_127", start: 826.59, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_127.mp4" hue="amber" darken={0} clipDur={21.97} /> },
  { key: "jd_s_127_b", start: 829.5, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_127_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_128", start: 832.35, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_128.png" hue="amber" darken={0} /> },
  { key: "jd_s_128_b", start: 834.98, dur: 2.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_128_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_129", start: 837.49, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_129.mp4" hue="amber" darken={0} clipDur={3.92} /> },
  { key: "jd_s_129_b", start: 840.13, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_129_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_130", start: 842.21, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_130.mp4" hue="amber" darken={0} clipDur={7.34} /> },
  { key: "jd_s_130_b", start: 844.92, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_130_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_131", start: 847.84, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_131.mp4" hue="amber" darken={0} clipDur={34.92} /> },
  { key: "jd_s_131_b", start: 850.49, dur: 3.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_131_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_132", start: 853.58, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_132.mp4" hue="amber" darken={0} clipDur={17.54} /> },
  { key: "jd_s_132_b", start: 856.28, dur: 2.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_132_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_133", start: 858.75, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_133.mp4" hue="amber" darken={0} clipDur={19.94} /> },
  { key: "jd_s_133_b", start: 861.8, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_133_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_134", start: 865.8, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_134.png" hue="amber" darken={0} /> },
  { key: "jd_s_134_b", start: 868.6, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_134_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_135", start: 871.04, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_135.mp4" hue="amber" darken={0} clipDur={16.02} /> },
  { key: "jd_s_135_b", start: 873.74, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_135_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_136", start: 875.94, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_136.mp4" hue="amber" darken={0} clipDur={20.02} /> },
  { key: "jd_s_136_b", start: 878.74, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_136_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_137", start: 882.94, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_137.mp4" hue="amber" darken={0} clipDur={25.58} /> },
  { key: "jd_s_137_b", start: 885.76, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_137_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_137_c", start: 888.53, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_137_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_138", start: 890.79, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_138.mp4" hue="amber" darken={0} clipDur={22.31} /> },
  { key: "jd_s_138_b", start: 893.43, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_138_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_138_c", start: 896.11, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_138_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_138_d", start: 898.94, dur: 2.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_138_d.png" hue="amber" darken={0} /> },
  { key: "jd_s_139", start: 901.21, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_139.png" hue="amber" darken={0} /> },
  { key: "jd_s_139_b", start: 903.96, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_139_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_140", start: 906.8, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_140.mp4" hue="amber" darken={0} clipDur={13} /> },
  { key: "jd_s_140_b", start: 909.55, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_140_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_141", start: 911.73, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_141.mp4" hue="amber" darken={0} clipDur={35.58} /> },
  { key: "jd_s_141_b", start: 914.56, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_141_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_142", start: 918.77, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_142.mp4" hue="amber" darken={0} clipDur={37.07} /> },
  { key: "jd_s_142_b", start: 921.62, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_142_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_142_c", start: 924.26, dur: 2.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_142_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_143", start: 926.13, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_143.png" hue="amber" darken={0} /> },
  { key: "jd_s_143_b", start: 929.28, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_143_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_144", start: 933.1, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_144.mp4" hue="amber" darken={0} clipDur={18.27} /> },
  { key: "jd_s_144_b", start: 936.4, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_144_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_144_c", start: 939.41, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_144_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_145", start: 942.07, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_145.png" hue="amber" darken={0} /> },
  { key: "jd_s_145_b", start: 944.84, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_145_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_146", start: 947.64, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_146.png" hue="amber" darken={0} /> },
  { key: "jd_s_146_b", start: 950.53, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_146_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_146_c", start: 953.7, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_146_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_147", start: 957.28, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_147.png" hue="amber" darken={0} /> },
  { key: "jd_s_147_b", start: 960.67, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_147_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_147_c", start: 963.69, dur: 2.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_147_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_148", start: 966.11, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_148.png" hue="amber" darken={0} /> },
  { key: "jd_s_148_b", start: 968.8, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_148_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_149", start: 970.98, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_149.png" hue="amber" darken={0} /> },
  { key: "jd_s_149_b", start: 973.65, dur: 2.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_149_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_150", start: 975.88, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_150.png" hue="amber" darken={0} /> },
  { key: "jd_s_150_b", start: 978.64, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_150_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_150_c", start: 981.3, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_150_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_151", start: 983.28, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_151.png" hue="amber" darken={0} /> },
  { key: "jd_s_151_b", start: 985.88, dur: 4.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_151_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_152", start: 990.35, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_152.png" hue="amber" darken={0} /> },
  { key: "jd_s_152_b", start: 992.97, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_152_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_152_c", start: 995.58, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_152_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_153", start: 997.32, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_153.png" hue="amber" darken={0} /> },
  { key: "jd_s_153_b", start: 1000.45, dur: 4.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_153_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_154", start: 1004.56, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_154.png" hue="amber" darken={0} /> },
  { key: "jd_s_154_b", start: 1007.23, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_154_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_155", start: 1010.17, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_155.mp4" hue="amber" darken={0} clipDur={8.01} /> },
  { key: "jd_s_155_b", start: 1012.78, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_155_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_156", start: 1016.09, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_156.mp4" hue="amber" darken={0} clipDur={10} /> },
  { key: "jd_s_156_b", start: 1018.86, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_156_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_157", start: 1022.32, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_157.png" hue="amber" darken={0} /> },
  { key: "jd_s_157_b", start: 1024.97, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_157_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_157_c", start: 1027.9, dur: 4.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_157_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_158", start: 1032.03, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_158.png" hue="amber" darken={0} /> },
  { key: "jd_s_158_b", start: 1034.7, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_158_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_158_c", start: 1037.36, dur: 2.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_158_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_159", start: 1039.32, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_159.png" hue="amber" darken={0} /> },
  { key: "jd_s_159_b", start: 1041.92, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_159_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_160", start: 1046.42, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_160.png" hue="amber" darken={0} /> },
  { key: "jd_s_160_b", start: 1049.05, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_160_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_161", start: 1051.53, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_161.mp4" hue="amber" darken={0} clipDur={6.16} /> },
  { key: "jd_s_161_b", start: 1054.13, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_161_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_162", start: 1056.92, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_162.mp4" hue="amber" darken={0} clipDur={8.48} /> },
  { key: "jd_s_162_b", start: 1059.67, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_162_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_162_c", start: 1062.33, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_162_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_163", start: 1065, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_163.png" hue="amber" darken={0} /> },
  { key: "jd_s_163_b", start: 1067.8, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_163_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_163_c", start: 1070.99, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_163_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_164", start: 1073.77, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_164.png" hue="amber" darken={0} /> },
  { key: "jd_s_164_b", start: 1076.43, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_164_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_164_c", start: 1079.03, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_164_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_165", start: 1081.08, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_165.mp4" hue="amber" darken={0} clipDur={37.8} /> },
  { key: "jd_s_165_b", start: 1083.81, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_165_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_166", start: 1085.73, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_166.mp4" hue="amber" darken={0} clipDur={18.96} /> },
  { key: "jd_s_166_b", start: 1088.55, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_166_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_166_c", start: 1091.22, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_166_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_167", start: 1093.33, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_167.png" hue="amber" darken={0} /> },
  { key: "jd_s_167_b", start: 1096.08, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_167_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_168", start: 1098.08, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_168.mp4" hue="amber" darken={0} clipDur={19.63} /> },
  { key: "jd_s_168_b", start: 1100.85, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_168_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_168_c", start: 1103.51, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_168_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_169", start: 1107.36, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_169.png" hue="amber" darken={0} /> },
  { key: "jd_s_169_b", start: 1109.97, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_169_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_169_c", start: 1112.6, dur: 2.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_169_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_170", start: 1114.33, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_170.png" hue="amber" darken={0} /> },
  { key: "jd_s_170_b", start: 1117.1, dur: 4.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_170_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_171", start: 1121.05, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_171.mp4" hue="amber" darken={0} clipDur={31.78} /> },
  { key: "jd_s_171_b", start: 1123.96, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_171_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_171_c", start: 1126.73, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_171_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_171_d", start: 1129.44, dur: 2.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_171_d.png" hue="amber" darken={0} /> },
  { key: "jd_s_172", start: 1131.5, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_172.png" hue="amber" darken={0} /> },
  { key: "jd_s_172_b", start: 1134.36, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_172_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_172_c", start: 1136.99, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_172_c.png" hue="amber" darken={0} /> },
  { key: "jd_s_173", start: 1140.45, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_173.png" hue="amber" darken={0} /> },
  { key: "jd_s_173_b", start: 1143.15, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_173_b.png" hue="amber" darken={0} /> },
  { key: "jd_s_174", start: 1145.2, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/jd_s_174.mp4" hue="amber" darken={0} clipDur={18.1} /> },
  { key: "jd_s_174_b", start: 1148.11, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/jd_s_174_b.png" hue="amber" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_vsduel_14", start: 13.7, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Apretá un puñado de tu tierra","title":"Tierra muerta vs. tierra viva","left":{"label":"Muerta","sub":"terrón gris, duro como cemento, no crece nada","good":false},"right":{"label":"Viva","sub":"oscura, esponjosa, se desarma, con lombrices","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_35", start: 35.35, dur: 5.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La mezcla que lo cambia todo","value":4,"prefix":"$","suffix":"","support":"cuatro dólares de cosas que ya tenés en casa — y resucita la tierra para siempre"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_42", start: 41.78, dur: 5.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"No la alimenta: la vuelve VIVA. Para siempre."} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_45", start: 45.07, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"El fertilizante caro es lo que tu jardín necesita","truth":"Una tierra viva se alimenta sola: por eso es un pésimo cliente para ellos"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_100", start: 100.22, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Sin fertilizante las plantas no crecen fuertes","truth":"Nadie fertiliza un bosque y es lo más fértil del planeta: la vida alimenta a la vida"} as any)} /></PremiumOverlay> },
  { key: "ov_flowsteps_127", start: 126.6, dur: 6.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><FlowSteps durationInFrames={d} theme={THEME_EARTH} {...({"title":"El círculo que rompimos","nodes":[{"label":"La hoja cae","sub":""},{"label":"Se pudre","sub":"alimenta el suelo"},{"label":"El suelo","sub":"alimenta el árbol"},{"label":"El árbol","sub":"tira otra hoja"}]} as any)} /></PremiumOverlay> },
  { key: "ov_framedphoto_153", start: 153.28, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><FramedPhoto durationInFrames={d} theme={THEME_EARTH} {...({"image":"real/jardin_c1.png","caption":"Doña Carmen","sub":"78 años, toda la vida la mejor huerta del barrio"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_198", start: 198.43, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"El fertilizante nutre la planta","truth":"Es un chute de azúcar: se ve linda arriba dos semanas, mientras mata la vida abajo"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_224", start: 223.53, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"En un solo puñado de tierra viva","value":7000,"prefix":"+","suffix":" millones","support":"más seres vivos que personas en todo el planeta — la fábrica que alimenta tus plantas"} as any)} /></PremiumOverlay> },
  { key: "ov_flowsteps_272", start: 271.68, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><FlowSteps durationInFrames={d} theme={THEME_EARTH} {...({"title":"El negocio perfecto","nodes":[{"label":"Te venden fertilizante","sub":""},{"label":"Mata la vida del suelo","sub":""},{"label":"La tierra queda muerta","sub":""},{"label":"Necesitás más","sub":"para siempre"}]} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_304", start: 303.83, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Por qué el químico mata","title":"La sal deshidrata","left":{"label":"Sal a una babosa","sub":"le chupa el agua, se muere","good":false},"right":{"label":"Sal (químico) al suelo","sub":"seca millones de bacterias y hongos","good":false}} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_348", start: 347.55, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"Una tierra viva no solo alimenta: ","highlight":"DEFIENDE","post":" — los microbios buenos forman un escudo en las raíces.","note":"la planta se enferma mucho menos"} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_395", start: 395.32, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"El caldo vivo: 4 ingredientes","items":["Melaza — despierta las bacterias","Compost / humus — trae la vida","Sal de Epsom — el verde","Ceniza — el fruto"],"stamp":"$4 EN TOTAL"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_398", start: 398.45, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Ingrediente 1 de 4","title":"El caldo vivo","steps":[{"title":"Melaza (2 cdas)","sub":"comida de las bacterias — las despierta"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_429", start: 429.41, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Ingrediente 2 de 4","title":"El caldo vivo","steps":[{"title":"Melaza (2 cdas)","sub":"comida de las bacterias — las despierta"},{"title":"Compost / humus (un puñado)","sub":"la vida que la melaza multiplica"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_469", start: 468.86, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Ingrediente 3 de 4","title":"El caldo vivo","steps":[{"title":"Melaza (2 cdas)","sub":"comida de las bacterias — las despierta"},{"title":"Compost / humus (un puñado)","sub":"la vida que la melaza multiplica"},{"title":"Sal de Epsom (1 cda)","sub":"magnesio — el verde de las hojas"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_500", start: 500.35, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Ingrediente 4 de 4","title":"El caldo vivo","steps":[{"title":"Melaza (2 cdas)","sub":"comida de las bacterias — las despierta"},{"title":"Compost / humus (un puñado)","sub":"la vida que la melaza multiplica"},{"title":"Sal de Epsom (1 cda)","sub":"magnesio — el verde de las hojas"},{"title":"Ceniza de madera (1 taza)","sub":"potasio — flores y frutos"}]} as any)} /></PremiumOverlay> },
  { key: "ov_bulletcascade_514", start: 514.05, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BulletCascade durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Los 4 roles, en una frase","bullets":[{"pre":"Melaza para ","key":"despertar la vida","post":""},{"pre":"Compost para ","key":"traerla","post":""},{"pre":"Epsom para ","key":"el verde","post":", ceniza para el fruto"}]} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_526", start: 526.2, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El mismo alimento, otro precio","title":"Caldo casero vs. bolsa de marca","left":{"label":"Caldo vivo","sub":"cosas de tu casa, alimenta el suelo","good":true},"right":{"label":"Bolsa de marca","sub":"$30, quema la vida del suelo","good":false}} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_540", start: 539.75, dur: 6.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La receta, en el balde","title":"10 L de agua (mejor de lluvia)","steps":[{"title":"2 cdas de melaza","sub":""},{"title":"1 puñado de compost / humus","sub":""},{"title":"1 cda de sal de Epsom","sub":""},{"title":"1 taza de ceniza","sub":"revolvé y dejá 24 h"}]} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_569", start: 569.23, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"A las 24 horas","value":24,"prefix":"","suffix":" h","support":"un puñado de compost se vuelve un caldo vivo, burbujeante, con billones de microorganismos"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_587", start: 587.44, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Con la tierra sana, frená las plagas","title":"Manual de Reparaciones Caseras","bullet":"el módulo de plagas: hormigas y bichos con bórax, sin veneno que mate el suelo","price":0,"cta":"LINK EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_splitpanel_620", start: 619.58, dur: 6.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><SplitPanel durationInFrames={d} theme={THEME_EARTH} {...({"image":"real/jardin_c2.png","eyebrow":"Dos formas, y las dos suman","title":"Regar la tierra + pulverizar las hojas","bullets":["Regá la base: coloniza el suelo","Pulverizá las hojas al atardecer","Alimenta directo y protege del hongo","Nunca con sol fuerte"]} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_681", start: 680.72, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Cuanto más fermente el caldo, mejor","truth":"A las 24-48 h está en su punto; días de más se pudre y trae los hongos que querés evitar"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_739", start: 739.01, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Una huerta sana empieza por un entorno sano","title":"Manual de Reparaciones Caseras","bullet":"el módulo de humedad y moho: cortar la humedad y el moho de raíz, por centavos","price":0,"cta":"LINK ARRIBA DE TODO"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_763", start: 763.02, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La frecuencia","value":15,"prefix":"cada ","suffix":" días","support":"un balde cada dos semanas en temporada — sin esclavitud, y el jardín se transforma"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_808", start: 808.37, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Qué esperar","title":"Semana a semana","steps":[{"title":"Semana 1: nada arriba","sub":"toda la acción está abajo"},{"title":"Semana 2-3: hojas más verdes","sub":""},{"title":"Mes 1: el cambio ya es claro","sub":""},{"title":"Mes 2: tierra oscura + lombrices","sub":""}]} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_867", start: 866.76, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Donde hay lombrices, hay vida. Donde no hay ni una, la tierra está muerta."} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_903", start: 902.69, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"El caldo es el empujón; ","highlight":"el mantillo es la despensa","post":" que mantiene la vida alimentada todo el año.","note":"menos riego, menos yuyos, menos plagas"} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_929", start: 929.28, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La huerta de Doña Carmen","beforeLabel":"Antes: amarilla, tomates chiquitos","afterLabel":"Después: verde, tomates rojos pesados","caption":"y dejó de comprar fertilizante para siempre"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_952", start: 951.77, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Estuve 30 años pagándole a una empresa para que me matara la tierra despacito."} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_988", start: 988.28, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Cuesta menos que una bolsa de fertilizante","title":"Manual de Reparaciones Caseras","bullet":"40 arreglos con el material exacto, las cantidades y el error que arruina a la mayoría","price":0,"cta":"PRIMER LINK DE LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_1058", start: 1058.29, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"La vida no se compra en el vivero. Se cultiva, se cuida, se multiplica."} as any)} /></PremiumOverlay> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":13.7,"role":"popUp","vol":0.32},{"at":35.35,"role":"popUp","vol":0.32},{"at":41.78,"role":"popUp","vol":0.32},{"at":45.07,"role":"popUp","vol":0.32},{"at":100.22,"role":"popUp","vol":0.32},{"at":126.6,"role":"popUp","vol":0.32},{"at":153.28,"role":"popUp","vol":0.32},{"at":198.43,"role":"popUp","vol":0.32},{"at":223.53,"role":"popUp","vol":0.32},{"at":271.68,"role":"popUp","vol":0.32},{"at":303.83,"role":"popUp","vol":0.32},{"at":347.55,"role":"popUp","vol":0.32},{"at":395.32,"role":"popUp","vol":0.32},{"at":398.45,"role":"popUp","vol":0.32},{"at":429.41,"role":"popUp","vol":0.32},{"at":468.86,"role":"popUp","vol":0.32},{"at":500.35,"role":"popUp","vol":0.32},{"at":514.05,"role":"popUp","vol":0.32},{"at":526.2,"role":"popUp","vol":0.32},{"at":539.75,"role":"popUp","vol":0.32},{"at":569.23,"role":"popUp","vol":0.32},{"at":587.44,"role":"popUp","vol":0.32},{"at":619.58,"role":"popUp","vol":0.32},{"at":680.72,"role":"popUp","vol":0.32},{"at":739.01,"role":"popUp","vol":0.32},{"at":763.02,"role":"popUp","vol":0.32},{"at":808.37,"role":"popUp","vol":0.32},{"at":866.76,"role":"popUp","vol":0.32},{"at":902.69,"role":"popUp","vol":0.32},{"at":929.28,"role":"popUp","vol":0.32},{"at":951.77,"role":"popUp","vol":0.32},{"at":988.28,"role":"popUp","vol":0.32},{"at":1058.29,"role":"popUp","vol":0.32}];
