// cues_impuestos.gen.tsx — GENERADO por beatsheet.mjs desde impuestos.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/impuestos.json
import { ReactNode } from "react";
import { sec, COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { DiagramBoard } from "./scenes/DiagramBoard";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { JourneyCanvas } from "./scenes/JourneyCanvas";
import { KineticHeadline } from "./scenes/KineticHeadline";
import { AgedDoc } from "./scenes/AgedDoc";
import { BarCompare } from "./scenes/BarCompare";
import { Checklist } from "./scenes/Checklist";
import { RuleNumberScene } from "./scenes/RuleNumberScene";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";

const D = COLORS.danger, B = COLORS.cold, G = COLORS.good;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "i001", start: 1.6, dur: 5, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/hk_bill.png" impact="el impuesto predial?" setup="¿Cuántos años llevás pagando" impactAccent="danger" hitAt={2.6} boom={2} /> },
  { key: "r002", start: 6.97, dur: 2.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_calendar10.png" hue="red" kicker="Diez años" /> },
  { key: "r003", start: 9.37, dur: 2.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_calendar30.png" hue="red" kicker="Treinta años" /> },
  { key: "r004", start: 11.87, dur: 2.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_mailbox.png" hue="red" kicker="Cada año, esa cuenta" /> },
  { key: "r005", start: 14.87, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_paying.png" hue="red" /> },
  { key: "h006", start: 17.9, dur: 4, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Porque "},{"t":"es la ley","danger":true},{"t":"."},{"t":" Porque nadie te dijo"},{"t":" que había otra opción","hl":true}]} eyebrow="Lo que nunca te contaron" hue="red" bg="black" /> },
  { key: "q007", start: 23.9, dur: 4.5, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/hk_paying.png" eyebrow="Un descubrimiento" words={parseQuote("Esto me enteré hace *dos años* y todavía me cuesta procesar")} accent="amber" hue="amber" fontSize={88} /> },
  { key: "s008", start: 28.6, dur: 4.2, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={48} label="estados con exención legal para adultos mayores" eyebrow="Impuesto predial" accent="good" hue="amber" /> },
  { key: "j009", start: 33, dur: 9, kind: "journey", el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="48 de 50 estados" title="La exención existe casi en todo el país" worldImage="img/map_usa.png" accent="good" waypoints={[{"x":0.32,"y":0.46,"z":1,"num":"48","label":"48 estados con exención","sub":"para mayores de 65","dwell":2.7,"travel":1.5},{"x":0.7,"y":0.4,"z":1,"num":"2","label":"Solo 2 quedan afuera","dwell":2.7}]} /> },
  { key: "h010", start: 42.5, dur: 4.4, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"La mayoría que califica"},{"t":" nunca la reclamó","danger":true}]} eyebrow="Y sin embargo…" hue="red" bg="image" image="img/hk_calendar30.png" /> },
  { key: "sl011", start: 47, dur: 5.5, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Nadie te avisa" items={["El condado no te llama","El municipio no te manda carta","El estado no manda a nadie"]} accent={D} cross /> },
  { key: "r012", start: 52.77, dur: 2.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_office_closed.png" hue="cold" /> },
  { key: "q013", start: 55.5, dur: 4, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/hk_office_closed.png" eyebrow="Cómo funciona" words={parseQuote("El sistema *espera*. Y mientras espera, vos seguís *pagando*")} accent="danger" hue="cold" fontSize={82} /> },
  { key: "r014", start: 59.77, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_house.png" hue="amber" kicker="Tu casa" /> },
  { key: "r015", start: 63.87, dur: 2.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_waiting.png" hue="cold" kicker="El sistema espera" /> },
  { key: "r016", start: 66.57, dur: 2.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_man57.png" hue="amber" kicker="Soy un hombre de 57" /> },
  { key: "r017", start: 69.67, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/hk_decades.png" hue="amber" kicker="Dos décadas, misma casa" /> },
  { key: "r018", start: 73.17, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rb_paying.png" hue="amber" kicker="Pagué puntualmente" /> },
  { key: "cm019", start: 79.5, dur: 5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="68" image="img/ch_roberto.png" eyebrow="Roberto · Georgia" caption="Jubilado · 31 años en su casa" accent="amber" hue="amber" /> },
  { key: "r020", start: 84.77, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rb_house_ga.png" hue="amber" /> },
  { key: "s021", start: 90.8, dur: 4.5, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={3400} prefix="$" label="que Roberto pagaba cada año" eyebrow="Impuesto predial anual" accent="danger" hue="amber" /> },
  { key: "c022", start: 95.3, dur: 3.5, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="Como casi todo el mundo" chips={["Como yo","Como vos","Todos los años"]} hue="amber" /> },
  { key: "r023", start: 101.57, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rb_daughter.png" hue="cold" /> },
  { key: "q024", start: 108.3, dur: 4.8, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/rb_daughter.png" eyebrow="La pregunta de su hija" words={parseQuote("Papá, ¿alguna vez pediste la *exención para adultos mayores*?")} accent="good" hue="cold" fontSize={70} /> },
  { key: "r025", start: 115.57, dur: 2.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rb_confused.png" hue="amber" kicker="¿La exención para qué?" /> },
  { key: "q026", start: 118.8, dur: 2.2, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} words={parseQuote("Esa conversación le *cambió la vida financiera*")} accent="amber" hue="amber" fontSize={60} /> },
  { key: "r027", start: 124.57, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rb_assessor.png" hue="cold" kicker="Oficina del tasador" /> },
  { key: "ck028", start: 128.1, dur: 9, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Lo que Roberto llevó" items={[{"text":"Su identificación con foto","state":"done"},{"text":"Prueba de su edad","state":"done"},{"text":"Boleta de servicios (residencia)","state":"done"}]} eyebrow="Solo 3 cosas" accent="good" hue="amber" /> },
  { key: "s029", start: 138, dur: 2.6, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={20} suffix=" min" label="duró todo el trámite" eyebrow="El trámite" accent="good" hue="amber" /> },
  { key: "b030", start: 140.6, dur: 5.6, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Antes","value":3400,"display":"$3,400","tone":"danger"},{"label":"Después","value":900,"display":"$900","tone":"good","winner":true}]} eyebrow="El impuesto de Roberto" title="Antes y después de la exención" unit="$/año" accent="good" hue="amber" /> },
  { key: "s031", start: 146.5, dur: 3.4, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={1800} prefix="$" label="le devolvieron del año anterior" eyebrow="Reembolso retroactivo" accent="good" hue="amber" /> },
  { key: "s032", start: 149.9, dur: 5, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={2500} prefix="$" suffix="+" label="que ahorra CADA año desde entonces" eyebrow="Ahorro anual" accent="good" hue="amber" /> },
  { key: "a033", start: 157.3, dur: 7.5, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Lo que Roberto me dijo" lines={[{"text":"Pasé 15 años manejando","mark":false},{"text":"frente a ese edificio.","mark":true},{"text":"Tenía dinero esperándome adentro","mark":true},{"text":"y nunca lo supe.","mark":false}]} eyebrow="Sus palabras" image="img/rb_assessor.png" accent="amber" hue="amber" /> },
  { key: "r034", start: 165.47, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/rb_building_drive.png" hue="cold" /> },
  { key: "r035", start: 170.77, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/wy_records.png" hue="cold" /> },
  { key: "h036", start: 184.9, dur: 4.6, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"El impuesto predial es la fuente de ingresos"},{"t":" más estable del gobierno local","hl":true}]} eyebrow="Por qué no llega solo" hue="blue" bg="image" image="img/wy_records.png" /> },
  { key: "c037", start: 190.3, dur: 3, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="Para el condado es…" chips={["Predecible","Automático","Todos los años"]} hue="blue" /> },
  { key: "q038", start: 193.5, dur: 5, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/wy_records.png" eyebrow="El conflicto" words={parseQuote("Los condados no tienen *ningún incentivo* para recordarte que podés pagar menos")} accent="danger" hue="cold" fontSize={70} /> },
  { key: "h039", start: 201.2, dur: 1.7, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Cero","danger":true},{"t":" incentivo"}]} hue="red" bg="black" /> },
  { key: "sl040", start: 203, dur: 5.2, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="La trampa legal" items={["Tienen obligación de aceptar tu solicitud","Pero nadie te obliga a presentarla","Si no la presentás, te cobran todo"]} accent={B} /> },
  { key: "c041", start: 214.4, dur: 4.4, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="El sistema es…" chips={["Completamente legal","Completamente injusto","Completamente evitable"]} hue="red" /> },
  { key: "q042", start: 220.9, dur: 5, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/hk_office_closed.png" eyebrow="La verdad incómoda" words={parseQuote("No es un error del sistema. Es el sistema funcionando *como fue diseñado*")} accent="danger" hue="cold" fontSize={72} /> },
  { key: "sl043", start: 227.3, dur: 5, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Solo hay dos grupos" items={["Los que pagan sin preguntar","Los que preguntaron"]} accent={G} /> },
  { key: "rn044", start: 234.1, dur: 3, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="01" title="3 tipos de exención" label="Vamos a lo concreto" hue="amber" /> },
  { key: "h045", start: 247.8, dur: 4, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Tres tipos principales","hl":true},{"t":" — cuál aplica donde vivís"}]} eyebrow="Lo que tenés que saber" hue="amber" bg="grid" /> },
  { key: "rn046", start: 252.8, dur: 2.7, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="01" title="Valor tasado congelado" label="Tipo 1" hue="blue" /> },
  { key: "d047", start: 255.7, dur: 8.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} avatar="impuestos_opt.mp4" avatarFrom={sec(255.7)} pages={[{"image":"img/dg_freeze.png","eyebrow":"Al cumplir 65, tu valor tasado se congela"}]} /> },
  { key: "b048", start: 264.1, dur: 7, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Tu vecino","value":100,"display":"↑ sube","tone":"danger"},{"label":"Vos (congelado)","value":55,"display":"= fijo","tone":"good","winner":true}]} eyebrow="Mientras el mercado sube…" title="Tu vecino vs vos (a 65)" orientation="vertical" unit="valor" accent="cold" hue="blue" /> },
  { key: "r049", start: 275.07, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ty_house_frozen.png" hue="blue" kicker="Fijo, para siempre" /> },
  { key: "rn050", start: 280, dur: 3, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="02" title="Reducción directa" label="Tipo 2" hue="amber" /> },
  { key: "r051", start: 285.27, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ty_form.png" hue="amber" /> },
  { key: "s052", start: 291.7, dur: 4.4, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={50000} prefix="$" label="Florida quita del valor tasado (bajos ingresos)" eyebrow="Florida" accent="good" hue="amber" /> },
  { key: "b053", start: 300.6, dur: 8, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Florida","value":50000,"display":"$50,000","tone":"good","winner":true},{"label":"Texas (estatal)","value":10000,"display":"$10,000","sub":"+ distrito escolar","tone":"accent"}]} eyebrow="Reducción directa por estado" title="Cuánto te sacan del valor tasado" orientation="horizontal" unit="USD" accent="good" hue="amber" /> },
  { key: "rn054", start: 312.4, dur: 3, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="03" title="Circuit Breaker" label="Tipo 3 · El más poderoso" hue="red" /> },
  { key: "s055", start: 315.6, dur: 3.6, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={30} suffix="+" label="estados tienen Circuit Breaker" eyebrow="Poco conocido" accent="danger" hue="red" /> },
  { key: "d056", start: 321.7, dur: 7.4, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} avatar="impuestos_opt.mp4" avatarFrom={sec(321.7)} pages={[{"image":"img/dg_cb1.png","eyebrow":"Si tu impuesto supera un % de tus ingresos…"},{"image":"img/dg_cb2.png","eyebrow":"…el estado te reembolsa la diferencia"}]} /> },
  { key: "r057", start: 329.67, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ty_check.png" hue="amber" kicker="Cheque o crédito" /> },
  { key: "q058", start: 336, dur: 6, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ty_check.png" eyebrow="La idea del Circuit Breaker" words={parseQuote("Ningún adulto mayor debería pagar más de *X%* de sus ingresos en impuesto predial")} accent="good" hue="red" fontSize={70} /> },
  { key: "h059", start: 349.2, dur: 3.4, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Casi nadie","danger":true},{"t":" lo reclama"}]} hue="red" bg="black" /> },
  { key: "q060", start: 356.5, dur: 4.6, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/hk_man57.png" eyebrow="El error más caro" words={parseQuote("Yo gano demasiado para calificar")} accent="danger" hue="cold" fontSize={92} /> },
  { key: "c061", start: 361.5, dur: 4, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="Pienso que tengo…" chips={["Casa pagada","Mis ahorros","Seguro social"]} hue="blue" /> },
  { key: "h062", start: 365.9, dur: 5, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Ese pensamiento te cuesta"},{"t":" miles de dólares al año","danger":true}]} eyebrow="El mito que cuesta caro" hue="red" bg="grid" /> },
  { key: "a063", start: 379.6, dur: 6, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="El dato clave" lines={[{"text":"Muchas exenciones NO son","mark":false},{"text":"solo para bajos ingresos.","mark":true},{"text":"Cualquiera mayor de 65","mark":true},{"text":"con residencia principal.","mark":false}]} eyebrow="Desmontando el mito" accent="good" hue="cold" /> },
  { key: "j064", start: 391.1, dur: 26, kind: "journey", el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="Sin límite de ingresos" title="No asumas que no calificás" worldImage="img/map_usa2.png" accent="good" waypoints={[{"x":0.55,"y":0.4,"z":1,"num":"IL","label":"Illinois","sub":"Senior Homestead · sin límite de ingresos","dwell":3,"travel":7.4},{"x":0.74,"y":0.36,"z":1,"num":"PA","label":"Pensilvania","sub":"umbral más alto de lo que creés","dwell":3,"travel":7.4},{"x":0.12,"y":0.5,"z":1,"num":"CA","label":"California","sub":"Proposition 19 · protege tu residencia","dwell":3}]} /> },
  { key: "h065", start: 421.3, dur: 3.4, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"No asumas. "},{"t":"Verificá","good":true}]} hue="amber" bg="black" /> },
  { key: "r066", start: 425.57, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ty_laptop.png" hue="cold" kicker="5 minutos online" /> },
  { key: "cm067", start: 430.9, dur: 4.4, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="71" image="img/ch_marta.png" eyebrow="Marta · Arizona" caption="Maestra retirada · 22 años en su casa" accent="amber" hue="amber" /> },
  { key: "r068", start: 435.57, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/mt_house_az.png" hue="amber" /> },
  { key: "s069", start: 443.7, dur: 4, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={4200} prefix="$" label="que Marta pagaba al año" eyebrow="Impuesto predial anual" accent="danger" hue="amber" /> },
  { key: "c070", start: 447.8, dur: 3, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="Sus ingresos" chips={["Pensión modesta","Seguro social"]} hue="amber" /> },
  { key: "q071", start: 450.9, dur: 4.4, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ch_marta.png" eyebrow="Su error" words={parseQuote("Nunca me consideré de *bajos ingresos*, así que nunca pregunté")} accent="danger" hue="cold" fontSize={74} /> },
  { key: "sl072", start: 456.3, dur: 6, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Marta calificaba para DOS programas" items={["Senior Property Valuation Protection","Property Tax Refund Credit estatal"]} accent={G} /> },
  { key: "b073", start: 467.6, dur: 6.8, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Antes","value":4200,"display":"$4,200","tone":"danger"},{"label":"Después","value":1100,"display":"$1,100","sub":"+$3,100/año a su bolsillo","tone":"good","winner":true}]} eyebrow="La cuenta de Marta" title="Combinando los dos programas" unit="$/año" accent="good" hue="amber" /> },
  { key: "q074", start: 474.8, dur: 5, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ch_marta.png" eyebrow="Marta" words={parseQuote("Pensé que eso era para gente que *no tenía nada*. No me di cuenta de que era para *mí*")} accent="amber" hue="amber" fontSize={66} /> },
  { key: "rn075", start: 485.2, dur: 3.5, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="01" title="Esta semana" label="No la semana que viene" hue="amber" /> },
  { key: "rn076", start: 491, dur: 3.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="01" title="Buscá en Google" label="Paso 1" hue="amber" /> },
  { key: "an077", start: 494.2, dur: 6, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/st_google.png" annotations={[{"kind":"underline","x":0.5,"y":0.42,"w":0.6,"label":"Tu condado + estas palabras"}]} eyebrow="Paso 1" caption="«[tu condado] Senior Homestead Exemption»" hue="amber" /> },
  { key: "r078", start: 506.87, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/st_requirements.png" hue="amber" kicker="Requisitos de tu zona" /> },
  { key: "rn079", start: 515.4, dur: 3.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="02" title="Llamá al tasador del condado" label="Paso 2" hue="amber" /> },
  { key: "r080", start: 518.87, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/st_phone.png" hue="amber" kicker="County Assessor" /> },
  { key: "q081", start: 530.2, dur: 7, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/st_phone.png" eyebrow="Decí exactamente esto" words={parseQuote("Tengo más de 65, esta es mi residencia principal: ¿califico para alguna *exención*?")} accent="good" hue="amber" fontSize={62} /> },
  { key: "h082", start: 543, dur: 3.4, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Esa pregunta sola"},{"t":" puede ahorrarte miles","good":true}]} hue="amber" bg="black" /> },
  { key: "rn083", start: 546.4, dur: 3.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="03" title="Llevá tus documentos" label="Paso 3" hue="amber" /> },
  { key: "ck084", start: 549.6, dur: 9, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Los 3 documentos que necesitás" items={[{"text":"Identificación con foto","state":"todo"},{"text":"Prueba de edad (pasaporte / acta)","state":"todo"},{"text":"Prueba de residencia principal","state":"todo","note":"boleta, licencia o declaración"}]} eyebrow="Paso 3" accent="good" hue="amber" /> },
  { key: "rn085", start: 570.8, dur: 3.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="04" title="Reclamá años anteriores" label="Paso 4 · Importante" hue="amber" /> },
  { key: "s086", start: 576.9, dur: 5, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={3} label="años hacia atrás podés recuperar (según el estado)" eyebrow="Reembolso retroactivo" accent="good" hue="amber" /> },
  { key: "cm087", start: 586.3, dur: 4, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$1,800" image="img/st_refund.png" eyebrow="Roberto recuperó" caption="del año anterior" accent="good" hue="amber" /> },
  { key: "rn088", start: 594.4, dur: 3.2, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="05" title="Si te niegan, apelá" label="Paso 5" hue="amber" /> },
  { key: "ck089", start: 598, dur: 9, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Tenés derechos en el sistema" items={[{"text":"Impugnar la tasación","state":"doing"},{"text":"Pedir una revisión","state":"doing"},{"text":"No necesitás abogado (primera instancia)","state":"done"}]} eyebrow="Paso 5" accent="good" hue="amber" /> },
  { key: "cm090", start: 617.4, dur: 5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="74" image="img/ch_domingo.png" eyebrow="Domingo · Texas" caption="Jubilado de la construcción · 26 años" accent="amber" hue="amber" /> },
  { key: "r091", start: 624.77, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/dm_house_tx.png" hue="amber" /> },
  { key: "q092", start: 634.2, dur: 5.2, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ch_domingo.png" eyebrow="Domingo" words={parseQuote("Yo pensé que el gobierno sabía lo que me tenía que cobrar")} accent="danger" hue="cold" fontSize={72} /> },
  { key: "q093", start: 644.2, dur: 4.2, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ch_domingo.png" eyebrow="Y tiene razón" words={parseQuote("¿Para qué me van a cobrar de más si hay una ley que dice que no deben?")} accent="amber" hue="cold" fontSize={60} /> },
  { key: "a094", start: 651.8, dur: 6, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Debería funcionar así" lines={[{"text":"Pagaste impuestos 40 años.","mark":false},{"text":"Si te pueden cobrar menos,","mark":true},{"text":"deberían cobrarte menos.","mark":true},{"text":"Pero no es lo que pasa.","mark":false}]} eyebrow="En un sistema justo" accent="amber" hue="cold" /> },
  { key: "h095", start: 665.1, dur: 6, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"La exención existe. La ley existe. "},{"t":"El dinero existe","good":true},{"t":". Pero es "},{"t":"pasivo","danger":true}]} eyebrow="El punto central" hue="amber" bg="image" image="img/ty_check.png" /> },
  { key: "i096", start: 676.1, dur: 5, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cl_county.png" impact="el condado se lo queda" setup="Si nadie lo reclama," impactAccent="danger" hitAt={2.2} boom={2} /> },
  { key: "s097", start: 681.1, dur: 4, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={26} suffix=" años" label="Domingo nunca lo reclamó — calificaba hace más de una década" eyebrow="El costo de no preguntar" accent="danger" hue="amber" /> },
  { key: "q098", start: 692, dur: 8, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ty_laptop.png" eyebrow="Si te llevás una sola cosa" words={parseQuote("La exención *no viene a buscarte*. Vos tenés que ir a buscarla")} accent="good" hue="amber" fontSize={76} /> },
  { key: "j099", start: 700.7, dur: 15.5, kind: "journey", el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="El costo vs el premio" title="Una visita lo cambia todo" accent="good" waypoints={[{"x":0.22,"y":0.4,"z":1,"image":"img/rb_assessor.png","num":"1","label":"Una visita","sub":"a la oficina del tasador","dwell":3,"travel":1.7},{"x":0.52,"y":0.58,"z":1,"image":"img/st_refund.png","num":"2","label":"20 minutos","sub":"tres documentos","dwell":3,"travel":1.7},{"x":0.8,"y":0.42,"z":1,"image":"img/ty_check.png","num":"3","label":"Miles al año","sub":"por el resto de tu vida","dwell":3.2}]} /> },
  { key: "r100", start: 716.67, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/cl_share.png" hue="amber" kicker="Pensá en alguien" /> },
  { key: "c101", start: 725.4, dur: 4.5, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="Mandáselo a quien…" chips={["Tenga más de 65","Sea dueño de su casa","Pague sin preguntar"]} hue="amber" /> },
  { key: "h102", start: 737.8, dur: 6.5, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Quizás esté pagando una cuenta"},{"t":" que no le corresponde","danger":true},{"t":". Y vos podés cambiar eso."}]} eyebrow="Antes de cerrar" hue="amber" bg="image" image="img/cl_share.png" /> },
];

export const REFRAME: { start: number; end: number }[] = [];
