// cues_shou.gen.tsx — GENERADO por beatsheet.mjs desde shou.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/shou.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { PremiumOverlay } from "./scenes/PremiumOverlay";
import { BigStatReveal, PullQuote, VsDuel, BeforeAfter, MythTruth, HighlightSweep, ChecklistReveal, NumberedSteps, CtaCard, THEME_EARTH } from "./kit/premium";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "shou_s_001", start: 0.16, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_001.png" hue="amber" darken={0} /> },
  { key: "shou_s_001_b", start: 2.87, dur: 4.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_001_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_002", start: 7.22, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_002.png" hue="amber" darken={0} /> },
  { key: "shou_s_002_b", start: 9.87, dur: 4.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_002_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_003", start: 14.28, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_003.png" hue="amber" darken={0} /> },
  { key: "shou_s_003_b", start: 17.48, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_003_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_004", start: 21.69, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_004.png" hue="amber" darken={0} /> },
  { key: "shou_s_004_b", start: 24.59, dur: 4.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_004_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_005", start: 28.63, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_005.png" hue="amber" darken={0} /> },
  { key: "shou_s_005_b", start: 31.48, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_005_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_006", start: 35.82, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_006.png" hue="amber" darken={0} /> },
  { key: "shou_s_006_b", start: 38.7, dur: 4.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_006_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_007", start: 43.01, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_007.png" hue="amber" darken={0} /> },
  { key: "shou_s_007_b", start: 45.8, dur: 4.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_007_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_008", start: 49.68, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_008.png" hue="amber" darken={0} /> },
  { key: "shou_s_008_b", start: 52.44, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_008_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_008_c", start: 55.18, dur: 2.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_008_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_009", start: 56.94, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_009.png" hue="amber" darken={0} /> },
  { key: "shou_s_009_b", start: 59.64, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_009_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_009_c", start: 62.42, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_009_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_010", start: 64.27, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_010.png" hue="amber" darken={0} /> },
  { key: "shou_s_010_b", start: 66.94, dur: 4.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_010_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_011", start: 71.33, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_011.png" hue="amber" darken={0} /> },
  { key: "shou_s_011_b", start: 74.06, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_011_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_012", start: 76.6, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_012.png" hue="amber" darken={0} /> },
  { key: "shou_s_012_b", start: 80, dur: 4.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_012_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_013", start: 83.73, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_013.png" hue="amber" darken={0} /> },
  { key: "shou_s_013_b", start: 86.46, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_013_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_014", start: 89.08, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_014.png" hue="amber" darken={0} /> },
  { key: "shou_s_014_b", start: 92, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_014_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_015", start: 96.4, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_015.png" hue="amber" darken={0} /> },
  { key: "shou_s_015_b", start: 99.41, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_015_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_015_c", start: 102.05, dur: 2.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_015_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_016", start: 103.87, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_016.png" hue="amber" darken={0} /> },
  { key: "shou_s_016_b", start: 106.8, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_016_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_017", start: 111.06, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_017.png" hue="amber" darken={0} /> },
  { key: "shou_s_017_b", start: 114.22, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_017_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_018", start: 118.4, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_018.png" hue="amber" darken={0} /> },
  { key: "shou_s_018_b", start: 121.68, dur: 2.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_018_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_019", start: 123.52, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_019.png" hue="amber" darken={0} /> },
  { key: "shou_s_019_b", start: 126.32, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_019_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_020", start: 130.53, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_020.png" hue="amber" darken={0} /> },
  { key: "shou_s_020_b", start: 133.15, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_020_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_020_c", start: 135.84, dur: 2.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_020_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_021", start: 137.66, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_021.png" hue="amber" darken={0} /> },
  { key: "shou_s_021_b", start: 140.47, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_021_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_022", start: 144.76, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_022.png" hue="amber" darken={0} /> },
  { key: "shou_s_022_b", start: 147.71, dur: 3.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_022_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_023", start: 151.04, dur: 7.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_023.png" hue="amber" darken={0} /> },
  { key: "shou_s_024", start: 158.04, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_024.png" hue="amber" darken={0} /> },
  { key: "shou_s_024_b", start: 160.68, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_024_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_024_c", start: 163.34, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_024_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_025", start: 165.32, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_025.png" hue="amber" darken={0} /> },
  { key: "shou_s_025_b", start: 168.2, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_025_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_026", start: 171.18, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_026.png" hue="amber" darken={0} /> },
  { key: "shou_s_026_b", start: 173.81, dur: 4.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_026_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_027", start: 178.46, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_027.png" hue="amber" darken={0} /> },
  { key: "shou_s_027_b", start: 181.37, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_027_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_027_c", start: 184.14, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_027_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_028", start: 185.88, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_028.png" hue="amber" darken={0} /> },
  { key: "shou_s_028_b", start: 188.51, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_028_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_029", start: 192.68, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_029.png" hue="amber" darken={0} /> },
  { key: "shou_s_029_b", start: 195.33, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_029_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_030", start: 198.76, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_030.png" hue="amber" darken={0} /> },
  { key: "shou_s_030_b", start: 201.39, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_030_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_031", start: 204, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_031.png" hue="amber" darken={0} /> },
  { key: "shou_s_031_b", start: 206.76, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_031_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_032", start: 209.64, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_032.png" hue="amber" darken={0} /> },
  { key: "shou_s_032_b", start: 212.51, dur: 4.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_032_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_033", start: 216.74, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_033.png" hue="amber" darken={0} /> },
  { key: "shou_s_033_b", start: 219.35, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_033_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_033_c", start: 221.96, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_033_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_034", start: 224.48, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_034.png" hue="amber" darken={0} /> },
  { key: "shou_s_034_b", start: 227.41, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_034_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_035", start: 231.59, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_035.png" hue="amber" darken={0} /> },
  { key: "shou_s_035_b", start: 234.33, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_035_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_035_c", start: 237.35, dur: 2.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_035_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_036", start: 239.08, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_036.png" hue="amber" darken={0} /> },
  { key: "shou_s_036_b", start: 242, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_036_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_037", start: 245.08, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_037.png" hue="amber" darken={0} /> },
  { key: "shou_s_037_b", start: 248.25, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_037_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_038", start: 250.96, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_038.png" hue="amber" darken={0} /> },
  { key: "shou_s_038_b", start: 253.94, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_038_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_039", start: 257.04, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_039.png" hue="amber" darken={0} /> },
  { key: "shou_s_039_b", start: 259.92, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_039_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_039_c", start: 262.57, dur: 2.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_039_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_040", start: 264.35, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_040.png" hue="amber" darken={0} /> },
  { key: "shou_s_040_b", start: 267.18, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_040_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_041", start: 271.42, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_041.png" hue="amber" darken={0} /> },
  { key: "shou_s_041_b", start: 274.12, dur: 3.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_041_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_042", start: 277.69, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_042.png" hue="amber" darken={0} /> },
  { key: "shou_s_042_b", start: 280.43, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_042_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_043", start: 284.72, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_043.png" hue="amber" darken={0} /> },
  { key: "shou_s_043_b", start: 287.38, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_043_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_044", start: 290.32, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_044.png" hue="amber" darken={0} /> },
  { key: "shou_s_044_b", start: 293.08, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_044_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_045", start: 296.56, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_045.png" hue="amber" darken={0} /> },
  { key: "shou_s_045_b", start: 299.43, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_045_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_046", start: 302.36, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_046.png" hue="amber" darken={0} /> },
  { key: "shou_s_046_b", start: 305.13, dur: 4.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_046_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_047", start: 309.44, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_047.png" hue="amber" darken={0} /> },
  { key: "shou_s_047_b", start: 312.82, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_047_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_048", start: 316.48, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_048.png" hue="amber" darken={0} /> },
  { key: "shou_s_048_b", start: 319.15, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_048_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_048_c", start: 322.08, dur: 2.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_048_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_049", start: 323.97, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_049.png" hue="amber" darken={0} /> },
  { key: "shou_s_049_b", start: 326.89, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_049_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_049_c", start: 329.65, dur: 2.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_049_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_050", start: 331.36, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_050.png" hue="amber" darken={0} /> },
  { key: "shou_s_050_b", start: 333.98, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_050_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_051", start: 336.76, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_051.png" hue="amber" darken={0} /> },
  { key: "shou_s_051_b", start: 339.44, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_051_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_052", start: 341.68, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_052.png" hue="amber" darken={0} /> },
  { key: "shou_s_052_b", start: 344.34, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_052_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_053", start: 347.88, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_053.png" hue="amber" darken={0} /> },
  { key: "shou_s_053_b", start: 351.35, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_053_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_054", start: 354.9, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_054.png" hue="amber" darken={0} /> },
  { key: "shou_s_054_b", start: 358.32, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_054_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_055", start: 362.04, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_055.png" hue="amber" darken={0} /> },
  { key: "shou_s_055_b", start: 365.42, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_055_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_056", start: 369.32, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_056.png" hue="amber" darken={0} /> },
  { key: "shou_s_056_b", start: 372.18, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_056_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_057", start: 376.58, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_057.png" hue="amber" darken={0} /> },
  { key: "shou_s_057_b", start: 379.3, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_057_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_058", start: 383.54, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_058.png" hue="amber" darken={0} /> },
  { key: "shou_s_058_b", start: 386.34, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_058_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_059", start: 388.94, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_059.png" hue="amber" darken={0} /> },
  { key: "shou_s_059_b", start: 391.58, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_059_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_059_c", start: 394.2, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_059_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_060", start: 396.28, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_060.png" hue="amber" darken={0} /> },
  { key: "shou_s_060_b", start: 398.98, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_060_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_060_c", start: 401.76, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_060_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_061", start: 403.66, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_061.png" hue="amber" darken={0} /> },
  { key: "shou_s_061_b", start: 406.46, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_061_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_062", start: 409, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_062.png" hue="amber" darken={0} /> },
  { key: "shou_s_062_b", start: 411.84, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_062_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_063", start: 415.2, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_063.png" hue="amber" darken={0} /> },
  { key: "shou_s_063_b", start: 417.96, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_063_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_063_c", start: 420.58, dur: 2.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_063_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_064", start: 422.34, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_064.png" hue="amber" darken={0} /> },
  { key: "shou_s_064_b", start: 425.2, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_064_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_065", start: 429.38, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_065.png" hue="amber" darken={0} /> },
  { key: "shou_s_065_b", start: 432.14, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_065_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_066", start: 434.4, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_066.png" hue="amber" darken={0} /> },
  { key: "shou_s_066_b", start: 437.32, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_066_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_066_c", start: 439.92, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_066_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_067", start: 441.66, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_067.png" hue="amber" darken={0} /> },
  { key: "shou_s_067_b", start: 444.51, dur: 2.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_067_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_068", start: 446.76, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_068.png" hue="amber" darken={0} /> },
  { key: "shou_s_068_b", start: 449.58, dur: 4.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_068_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_069", start: 453.77, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_069.png" hue="amber" darken={0} /> },
  { key: "shou_s_069_b", start: 456.55, dur: 4.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_069_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_070", start: 461.2, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_070.png" hue="amber" darken={0} /> },
  { key: "shou_s_070_b", start: 464.34, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_070_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_071", start: 468.6, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_071.png" hue="amber" darken={0} /> },
  { key: "shou_s_071_b", start: 471.47, dur: 4.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_071_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_072", start: 475.6, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_072.png" hue="amber" darken={0} /> },
  { key: "shou_s_072_b", start: 478.27, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_072_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_073", start: 482.65, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_073.png" hue="amber" darken={0} /> },
  { key: "shou_s_073_b", start: 485.27, dur: 3.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_073_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_074", start: 488.56, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_074.png" hue="amber" darken={0} /> },
  { key: "shou_s_074_b", start: 491.26, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_074_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_075", start: 494.56, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_075.png" hue="amber" darken={0} /> },
  { key: "shou_s_075_b", start: 497.48, dur: 4.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_075_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_076", start: 501.89, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_076.png" hue="amber" darken={0} /> },
  { key: "shou_s_076_b", start: 504.72, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_076_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_077", start: 508.93, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_077.png" hue="amber" darken={0} /> },
  { key: "shou_s_077_b", start: 511.98, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_077_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_078", start: 516, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_078.png" hue="amber" darken={0} /> },
  { key: "shou_s_078_b", start: 518.68, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_078_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_078_c", start: 521.46, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_078_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_079", start: 523.31, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_079.png" hue="amber" darken={0} /> },
  { key: "shou_s_079_b", start: 526.3, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_079_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_080", start: 530.76, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_080.png" hue="amber" darken={0} /> },
  { key: "shou_s_080_b", start: 533.4, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_080_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_080_c", start: 536.17, dur: 2.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_080_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_081", start: 538.44, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_081.png" hue="amber" darken={0} /> },
  { key: "shou_s_081_b", start: 541.04, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_081_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_082", start: 544.24, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_082.png" hue="amber" darken={0} /> },
  { key: "shou_s_082_b", start: 547.27, dur: 4.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_082_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_083", start: 551.24, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_083.png" hue="amber" darken={0} /> },
  { key: "shou_s_083_b", start: 553.97, dur: 2.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_083_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_084", start: 556.48, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_084.png" hue="amber" darken={0} /> },
  { key: "shou_s_084_b", start: 559.68, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_084_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_085", start: 563.48, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_085.png" hue="amber" darken={0} /> },
  { key: "shou_s_085_b", start: 566.15, dur: 3.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_085_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_086", start: 569.64, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_086.png" hue="amber" darken={0} /> },
  { key: "shou_s_086_b", start: 572.38, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_086_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_087", start: 576.8, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_087.png" hue="amber" darken={0} /> },
  { key: "shou_s_087_b", start: 579.7, dur: 4.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_087_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_088", start: 584.17, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_088.png" hue="amber" darken={0} /> },
  { key: "shou_s_088_b", start: 587.41, dur: 4.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_088_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_089", start: 591.42, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_089.png" hue="amber" darken={0} /> },
  { key: "shou_s_089_b", start: 594.28, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_089_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_090", start: 598.46, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_090.png" hue="amber" darken={0} /> },
  { key: "shou_s_090_b", start: 601.13, dur: 2.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_090_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_091", start: 603.64, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_091.png" hue="amber" darken={0} /> },
  { key: "shou_s_091_b", start: 606.51, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_091_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_092", start: 609.36, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_092.png" hue="amber" darken={0} /> },
  { key: "shou_s_092_b", start: 612.23, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_092_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_092_c", start: 614.9, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_092_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_093", start: 616.69, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_093.png" hue="amber" darken={0} /> },
  { key: "shou_s_093_b", start: 619.56, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_093_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_094", start: 623.78, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_094.png" hue="amber" darken={0} /> },
  { key: "shou_s_094_b", start: 626.8, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_094_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_095", start: 631.01, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_095.png" hue="amber" darken={0} /> },
  { key: "shou_s_095_b", start: 634, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_095_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_096", start: 638, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_096.png" hue="amber" darken={0} /> },
  { key: "shou_s_096_b", start: 640.75, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_096_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_097", start: 645.03, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_097.png" hue="amber" darken={0} /> },
  { key: "shou_s_097_b", start: 647.89, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_097_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_097_c", start: 650.64, dur: 2.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_097_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_098", start: 652.36, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_098.png" hue="amber" darken={0} /> },
  { key: "shou_s_098_b", start: 655.3, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_098_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_099", start: 659.4, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_099.png" hue="amber" darken={0} /> },
  { key: "shou_s_099_b", start: 662.11, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_099_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_099_c", start: 664.8, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_099_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_100", start: 666.72, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_100.png" hue="amber" darken={0} /> },
  { key: "shou_s_100_b", start: 669.48, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_100_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_101", start: 672.75, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_101.png" hue="amber" darken={0} /> },
  { key: "shou_s_101_b", start: 675.38, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_101_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_102", start: 679.84, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_102.png" hue="amber" darken={0} /> },
  { key: "shou_s_102_b", start: 682.54, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_102_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_103", start: 685.44, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_103.png" hue="amber" darken={0} /> },
  { key: "shou_s_103_b", start: 688.31, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_103_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_104", start: 692.52, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_104.png" hue="amber" darken={0} /> },
  { key: "shou_s_104_b", start: 695.41, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_104_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_105", start: 699.15, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_105.png" hue="amber" darken={0} /> },
  { key: "shou_s_105_b", start: 702, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_105_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_106", start: 705.52, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_106.png" hue="amber" darken={0} /> },
  { key: "shou_s_106_b", start: 708.18, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_106_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_107", start: 712, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_107.png" hue="amber" darken={0} /> },
  { key: "shou_s_107_b", start: 715.4, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_107_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_108", start: 719.1, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_108.png" hue="amber" darken={0} /> },
  { key: "shou_s_108_b", start: 722.12, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_108_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_109", start: 725.24, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_109.png" hue="amber" darken={0} /> },
  { key: "shou_s_109_b", start: 728.2, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_109_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_110", start: 731.12, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_110.png" hue="amber" darken={0} /> },
  { key: "shou_s_110_b", start: 733.99, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_110_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_111", start: 738.27, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_111.png" hue="amber" darken={0} /> },
  { key: "shou_s_111_b", start: 741.32, dur: 4.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_111_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_112", start: 745.16, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_112.png" hue="amber" darken={0} /> },
  { key: "shou_s_112_b", start: 747.92, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_112_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_113", start: 752.26, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_113.png" hue="amber" darken={0} /> },
  { key: "shou_s_113_b", start: 755.17, dur: 4.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_113_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_114", start: 759.04, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_114.png" hue="amber" darken={0} /> },
  { key: "shou_s_114_b", start: 761.66, dur: 4.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_114_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_115", start: 766.05, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_115.png" hue="amber" darken={0} /> },
  { key: "shou_s_115_b", start: 768.65, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_115_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_116", start: 772.24, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_116.png" hue="amber" darken={0} /> },
  { key: "shou_s_116_b", start: 775.03, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_116_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_116_c", start: 777.74, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_116_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_117", start: 779.94, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_117.png" hue="amber" darken={0} /> },
  { key: "shou_s_117_b", start: 782.97, dur: 4.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_117_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_118", start: 787, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_118.png" hue="amber" darken={0} /> },
  { key: "shou_s_118_b", start: 789.62, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_118_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_119", start: 794.04, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_119.png" hue="amber" darken={0} /> },
  { key: "shou_s_119_b", start: 797, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_119_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_120", start: 801.06, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_120.png" hue="amber" darken={0} /> },
  { key: "shou_s_120_b", start: 803.77, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_120_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_120_c", start: 806.51, dur: 2.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_120_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_121", start: 808.42, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_121.png" hue="amber" darken={0} /> },
  { key: "shou_s_121_b", start: 811.5, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_121_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_121_c", start: 814.12, dur: 2.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_121_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_122", start: 816, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_122.png" hue="amber" darken={0} /> },
  { key: "shou_s_122_b", start: 819.06, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_122_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_123", start: 823.12, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_123.png" hue="amber" darken={0} /> },
  { key: "shou_s_123_b", start: 826.1, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_123_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_124", start: 830.27, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_124.png" hue="amber" darken={0} /> },
  { key: "shou_s_124_b", start: 833.16, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_124_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_125", start: 837.41, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_125.png" hue="amber" darken={0} /> },
  { key: "shou_s_125_b", start: 840.66, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_125_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_126", start: 844.44, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_126.png" hue="amber" darken={0} /> },
  { key: "shou_s_126_b", start: 847.22, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_126_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_127", start: 851.46, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_127.png" hue="amber" darken={0} /> },
  { key: "shou_s_127_b", start: 854.06, dur: 4.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_127_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_128", start: 858.51, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_128.png" hue="amber" darken={0} /> },
  { key: "shou_s_128_b", start: 861.2, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_128_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_129", start: 863.76, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_129.png" hue="amber" darken={0} /> },
  { key: "shou_s_129_b", start: 866.78, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_129_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_130", start: 869.6, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_130.png" hue="amber" darken={0} /> },
  { key: "shou_s_130_b", start: 872.36, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_130_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_131", start: 876.6, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_131.png" hue="amber" darken={0} /> },
  { key: "shou_s_131_b", start: 879.5, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_131_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_132", start: 883.6, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_132.png" hue="amber" darken={0} /> },
  { key: "shou_s_132_b", start: 886.26, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_132_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_133", start: 890.08, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_133.png" hue="amber" darken={0} /> },
  { key: "shou_s_133_b", start: 892.79, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_133_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_134", start: 897.08, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_134.png" hue="amber" darken={0} /> },
  { key: "shou_s_134_b", start: 899.84, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_134_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_135", start: 902.16, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_135.png" hue="amber" darken={0} /> },
  { key: "shou_s_135_b", start: 905.03, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_135_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_136", start: 908.4, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_136.png" hue="amber" darken={0} /> },
  { key: "shou_s_136_b", start: 911.5, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_136_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_137", start: 914.39, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_137.png" hue="amber" darken={0} /> },
  { key: "shou_s_137_b", start: 917.24, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_137_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_138", start: 921.53, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_138.png" hue="amber" darken={0} /> },
  { key: "shou_s_138_b", start: 924.17, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_138_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_138_c", start: 926.78, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_138_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_139", start: 929.16, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_139.png" hue="amber" darken={0} /> },
  { key: "shou_s_139_b", start: 931.88, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_139_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_139_c", start: 935.24, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_139_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_140", start: 937.16, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_140.png" hue="amber" darken={0} /> },
  { key: "shou_s_140_b", start: 939.92, dur: 4.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_140_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_141", start: 944.23, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_141.png" hue="amber" darken={0} /> },
  { key: "shou_s_141_b", start: 946.93, dur: 4.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_141_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_142", start: 950.72, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_142.png" hue="amber" darken={0} /> },
  { key: "shou_s_142_b", start: 953.5, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_142_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_143", start: 957.8, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_143.png" hue="amber" darken={0} /> },
  { key: "shou_s_143_b", start: 960.48, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_143_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_144", start: 963.4, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_144.png" hue="amber" darken={0} /> },
  { key: "shou_s_144_b", start: 966.8, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_144_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_145", start: 970.04, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_145.png" hue="amber" darken={0} /> },
  { key: "shou_s_145_b", start: 972.97, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_145_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_146", start: 976.08, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_146.png" hue="amber" darken={0} /> },
  { key: "shou_s_146_b", start: 978.86, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_146_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_147", start: 982.48, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_147.png" hue="amber" darken={0} /> },
  { key: "shou_s_147_b", start: 985.24, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_147_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_148", start: 989.48, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_148.png" hue="amber" darken={0} /> },
  { key: "shou_s_148_b", start: 992.09, dur: 4.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_148_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_149", start: 996.36, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_149.png" hue="amber" darken={0} /> },
  { key: "shou_s_149_b", start: 998.98, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_149_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_150", start: 1002.32, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_150.png" hue="amber" darken={0} /> },
  { key: "shou_s_150_b", start: 1005.09, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_150_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_151", start: 1008.08, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_151.png" hue="amber" darken={0} /> },
  { key: "shou_s_151_b", start: 1010.95, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_151_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_152", start: 1015.24, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_152.png" hue="amber" darken={0} /> },
  { key: "shou_s_152_b", start: 1017.86, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_152_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_153", start: 1021.16, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_153.png" hue="amber" darken={0} /> },
  { key: "shou_s_153_b", start: 1024.3, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_153_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_154", start: 1028.2, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_154.png" hue="amber" darken={0} /> },
  { key: "shou_s_154_b", start: 1030.86, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_154_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_155", start: 1034.76, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_155.png" hue="amber" darken={0} /> },
  { key: "shou_s_155_b", start: 1037.54, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_155_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_156", start: 1042.06, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_156.png" hue="amber" darken={0} /> },
  { key: "shou_s_156_b", start: 1044.99, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_156_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_157", start: 1049.16, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_157.png" hue="amber" darken={0} /> },
  { key: "shou_s_157_b", start: 1052.28, dur: 4.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_157_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_158", start: 1056.05, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_158.png" hue="amber" darken={0} /> },
  { key: "shou_s_158_b", start: 1058.83, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_158_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_158_c", start: 1061.51, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_158_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_159", start: 1063.72, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_159.png" hue="amber" darken={0} /> },
  { key: "shou_s_159_b", start: 1067.12, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_159_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_160", start: 1070.79, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_160.png" hue="amber" darken={0} /> },
  { key: "shou_s_160_b", start: 1073.44, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_160_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_160_c", start: 1076.05, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_160_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_161", start: 1077.84, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_161.png" hue="amber" darken={0} /> },
  { key: "shou_s_161_b", start: 1080.76, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_161_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_162", start: 1085.16, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_162.png" hue="amber" darken={0} /> },
  { key: "shou_s_162_b", start: 1087.85, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_162_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_163", start: 1091.04, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_163.png" hue="amber" darken={0} /> },
  { key: "shou_s_163_b", start: 1093.8, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_163_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_164", start: 1098.09, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_164.png" hue="amber" darken={0} /> },
  { key: "shou_s_164_b", start: 1101.2, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_164_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_165", start: 1105.26, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_165.png" hue="amber" darken={0} /> },
  { key: "shou_s_165_b", start: 1108.01, dur: 3.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_165_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_166", start: 1111.4, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_166.png" hue="amber" darken={0} /> },
  { key: "shou_s_166_b", start: 1114.16, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_166_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_167", start: 1117.04, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_167.png" hue="amber" darken={0} /> },
  { key: "shou_s_167_b", start: 1119.65, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_167_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_167_c", start: 1122.42, dur: 2.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_167_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_168", start: 1124.24, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_168.png" hue="amber" darken={0} /> },
  { key: "shou_s_168_b", start: 1127.04, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_168_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_168_c", start: 1129.66, dur: 2.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_168_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_169", start: 1131.38, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_169.png" hue="amber" darken={0} /> },
  { key: "shou_s_169_b", start: 1134.02, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_169_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_170", start: 1138.08, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_170.png" hue="amber" darken={0} /> },
  { key: "shou_s_170_b", start: 1141.01, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_170_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_171", start: 1144.53, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_171.png" hue="amber" darken={0} /> },
  { key: "shou_s_171_b", start: 1147.24, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_171_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_172", start: 1150.11, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_172.png" hue="amber" darken={0} /> },
  { key: "shou_s_172_b", start: 1152.89, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_172_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_173", start: 1155.79, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_173.png" hue="amber" darken={0} /> },
  { key: "shou_s_173_b", start: 1158.39, dur: 4.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_173_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_174", start: 1162.32, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_174.png" hue="amber" darken={0} /> },
  { key: "shou_s_174_b", start: 1165.06, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_174_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_174_c", start: 1167.72, dur: 2.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_174_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_175", start: 1169.56, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_175.png" hue="amber" darken={0} /> },
  { key: "shou_s_175_b", start: 1172.32, dur: 3.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_175_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_176", start: 1175.65, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_176.png" hue="amber" darken={0} /> },
  { key: "shou_s_176_b", start: 1178.34, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_176_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_176_c", start: 1180.97, dur: 2.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_176_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_177", start: 1182.8, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_177.png" hue="amber" darken={0} /> },
  { key: "shou_s_177_b", start: 1185.52, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_177_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_178", start: 1188.32, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_178.png" hue="amber" darken={0} /> },
  { key: "shou_s_178_b", start: 1191.32, dur: 4.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_178_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_179", start: 1195.39, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_179.png" hue="amber" darken={0} /> },
  { key: "shou_s_179_b", start: 1198.06, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_179_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_180", start: 1200.86, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_180.png" hue="amber" darken={0} /> },
  { key: "shou_s_180_b", start: 1203.64, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_180_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_181", start: 1206.82, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_181.png" hue="amber" darken={0} /> },
  { key: "shou_s_181_b", start: 1209.76, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_181_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_182", start: 1213.88, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_182.png" hue="amber" darken={0} /> },
  { key: "shou_s_182_b", start: 1216.96, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_182_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_182_c", start: 1219.66, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_182_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_183", start: 1221.45, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_183.png" hue="amber" darken={0} /> },
  { key: "shou_s_183_b", start: 1224.24, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_183_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_184", start: 1228.54, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_184.png" hue="amber" darken={0} /> },
  { key: "shou_s_184_b", start: 1231.27, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_184_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_185", start: 1234.06, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_185.png" hue="amber" darken={0} /> },
  { key: "shou_s_185_b", start: 1236.7, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_185_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_186", start: 1240.34, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_186.png" hue="amber" darken={0} /> },
  { key: "shou_s_186_b", start: 1243.03, dur: 4.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_186_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_187", start: 1247.48, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_187.png" hue="amber" darken={0} /> },
  { key: "shou_s_187_b", start: 1250.37, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_187_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_188", start: 1254.04, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_188.png" hue="amber" darken={0} /> },
  { key: "shou_s_188_b", start: 1256.86, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_188_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_189", start: 1261.1, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_189.png" hue="amber" darken={0} /> },
  { key: "shou_s_189_b", start: 1263.88, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_189_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_189_c", start: 1266.57, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_189_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_190", start: 1268.36, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_190.png" hue="amber" darken={0} /> },
  { key: "shou_s_190_b", start: 1271.19, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_190_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_191", start: 1275.43, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_191.png" hue="amber" darken={0} /> },
  { key: "shou_s_191_b", start: 1278.39, dur: 2.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_191_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_192", start: 1280.88, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_192.png" hue="amber" darken={0} /> },
  { key: "shou_s_192_b", start: 1283.51, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_192_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_193", start: 1287.89, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_193.png" hue="amber" darken={0} /> },
  { key: "shou_s_193_b", start: 1290.55, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_193_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_194", start: 1293.77, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_194.png" hue="amber" darken={0} /> },
  { key: "shou_s_194_b", start: 1296.42, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_194_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_195", start: 1298.92, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_195.png" hue="amber" darken={0} /> },
  { key: "shou_s_195_b", start: 1301.57, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_195_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_196", start: 1304.6, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_196.png" hue="amber" darken={0} /> },
  { key: "shou_s_196_b", start: 1307.36, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_196_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_197", start: 1311.76, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_197.png" hue="amber" darken={0} /> },
  { key: "shou_s_197_b", start: 1314.46, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_197_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_198", start: 1318.9, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_198.png" hue="amber" darken={0} /> },
  { key: "shou_s_198_b", start: 1321.8, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_198_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_199", start: 1326.05, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_199.png" hue="amber" darken={0} /> },
  { key: "shou_s_199_b", start: 1328.85, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_199_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_199_c", start: 1331.54, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_199_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_200", start: 1333.44, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_200.png" hue="amber" darken={0} /> },
  { key: "shou_s_200_b", start: 1336.31, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_200_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_201", start: 1339.15, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_201.png" hue="amber" darken={0} /> },
  { key: "shou_s_201_b", start: 1342.21, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_201_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_202", start: 1345.89, dur: 3.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_202.png" hue="amber" darken={0} /> },
  { key: "shou_s_202_b", start: 1349.04, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_202_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_203", start: 1351.44, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_203.png" hue="amber" darken={0} /> },
  { key: "shou_s_203_b", start: 1354.22, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_203_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_204", start: 1357.64, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_204.png" hue="amber" darken={0} /> },
  { key: "shou_s_204_b", start: 1360.62, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_204_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_205", start: 1363.2, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_205.png" hue="amber" darken={0} /> },
  { key: "shou_s_205_b", start: 1365.91, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_205_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_206", start: 1369.34, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_206.png" hue="amber" darken={0} /> },
  { key: "shou_s_206_b", start: 1372.34, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_206_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_207", start: 1375.52, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_207.png" hue="amber" darken={0} /> },
  { key: "shou_s_207_b", start: 1378.32, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_207_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_208", start: 1381.64, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_208.png" hue="amber" darken={0} /> },
  { key: "shou_s_208_b", start: 1384.25, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_208_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_208_c", start: 1386.97, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_208_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_209", start: 1389.07, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_209.png" hue="amber" darken={0} /> },
  { key: "shou_s_209_b", start: 1391.8, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_209_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_210", start: 1395.6, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_210.png" hue="amber" darken={0} /> },
  { key: "shou_s_210_b", start: 1398.35, dur: 3.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_210_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_211", start: 1401.44, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_211.png" hue="amber" darken={0} /> },
  { key: "shou_s_211_b", start: 1404.13, dur: 2.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_211_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_212", start: 1406.44, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_212.png" hue="amber" darken={0} /> },
  { key: "shou_s_212_b", start: 1409.18, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_212_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_213", start: 1412.94, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_213.png" hue="amber" darken={0} /> },
  { key: "shou_s_213_b", start: 1415.76, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_213_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_213_c", start: 1418.48, dur: 2.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_213_c.png" hue="amber" darken={0} /> },
  { key: "shou_s_214", start: 1420.2, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_214.png" hue="amber" darken={0} /> },
  { key: "shou_s_214_b", start: 1422.82, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_214_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_215", start: 1425.6, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_215.png" hue="amber" darken={0} /> },
  { key: "shou_s_215_b", start: 1428.28, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_215_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_216", start: 1430.8, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_216.png" hue="amber" darken={0} /> },
  { key: "shou_s_216_b", start: 1433.56, dur: 4.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_216_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_217", start: 1437.83, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_217.png" hue="amber" darken={0} /> },
  { key: "shou_s_217_b", start: 1440.56, dur: 4.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_217_b.png" hue="amber" darken={0} /> },
  { key: "shou_s_218", start: 1444.87, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_218.png" hue="amber" darken={0} /> },
  { key: "shou_s_218_b", start: 1447.68, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/shou_s_218_b.png" hue="amber" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_bigstatreveal_29", start: 28.63, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El japonés del cerco negro","value":82,"suffix":" años","support":"Don Ito — llegó tras la guerra con dos cajones de herramientas y un secreto"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_86", start: 85.86, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Ramírez, en mi pueblo hacemos esto desde hace mil años. Vení a verme en cuarenta."} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_93", start: 93.02, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"40 años después","title":"Poste tratado vs. poste quemado","left":{"label":"Postes tratados (Ramírez)","sub":"se pudrieron y hubo que cambiarlos 2-3 veces","good":false},"right":{"label":"Cerco quemado (Don Ito)","sub":"firme e intacto a los 50 años","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_101", start: 100.68, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Los años pasaron","beforeLabel":"Postes del pueblo: caídos","afterLabel":"Cerco de Don Ito: intacto","caption":"los mismos postes que quemó el primer día"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_108", start: 108, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El cerco que sobrevivió a todos","value":50,"suffix":" años","support":"más sano que muchos postes nuevos del corralón — los mismos que quemó el primer día"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_186", start: 185.88, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Si el fuego destruye todo, quemar la madera la arruina","truth":"Controlado, no la destruye: la transforma en carbón inerte que la protege"} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_272", start: 272.32, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"El carbón sella los tubitos: la superficie se vuelve","highlight":"hidrófoba","post":" — repele el agua, rebota y se va.","note":"sin agua, no hay pudrición"} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_297", start: 296.56, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"La capa de carbón","highlight":"absorbe y bloquea los rayos UV","post":" — un escudo contra el sol.","note":"por eso no se pone gris"} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_317", start: 317.32, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Lo que hace el fuego, en una pasada","items":["Sin comida para los hongos (carbón inerte)","Sin comida para los insectos","Puerta cerrada al agua (hidrófoba)","Escudo contra el sol (UV)"],"stamp":"LAS 4, DE UN GOLPE"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_325", start: 325.28, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Lo que logra el fuego en una pasada","value":4,"suffix":" enemigos","support":"hongos, insectos, agua y sol — neutralizados de un solo golpe, gratis"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_342", start: 341.68, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"No es moda: es antiquísima","value":1000,"suffix":" años","support":"en Japón revisten casas, templos y graneros con madera quemada (Yakisugi)"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_409", start: 409, dur: 6.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La técnica · 1","title":"Cómo se hace, paso a paso","steps":[{"title":"Madera seca (pino/cedro/ciprés)","sub":"si la quemás húmeda, el vapor revienta la superficie"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_447", start: 446.76, dur: 6.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La técnica · 2","title":"Cómo se hace, paso a paso","steps":[{"title":"Madera seca (pino/cedro/ciprés)","sub":"si la quemás húmeda, el vapor revienta la superficie"},{"title":"Un soplete de gas","sub":"control total y barato — la chimenea tradicional es para expertos"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_491", start: 491.26, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La técnica · 3","title":"Cómo se hace, paso a paso","steps":[{"title":"Madera seca (pino/cedro/ciprés)","sub":"si la quemás húmeda, el vapor revienta la superficie"},{"title":"Un soplete de gas","sub":"control total y barato — la chimenea tradicional es para expertos"},{"title":"Quemar hasta piel de cocodrilo","sub":"escamas negras brillantes: capa de carbón de 3-5 mm"}]} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_509", start: 508.73, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"El punto justo del quemado:","highlight":"piel de cocodrilo","post":" — escamas negras brillantes, 3-5 mm de carbón.","note":"ahí parás, ni más ni menos"} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_517", start: 516.55, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Cómo leer el quemado","beforeLabel":"Se dora y se pone marrón","afterLabel":"Se agrieta: piel de cocodrilo","caption":"ahí parás — capa de carbón de 3-5 mm"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_565", start: 564.84, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La técnica · 4","title":"Cómo se hace, paso a paso","steps":[{"title":"Madera seca (pino/cedro/ciprés)","sub":"si la quemás húmeda, el vapor revienta la superficie"},{"title":"Un soplete de gas","sub":"control total y barato — la chimenea tradicional es para expertos"},{"title":"Quemar hasta piel de cocodrilo","sub":"escamas negras brillantes: capa de carbón de 3-5 mm"},{"title":"Enfriar y cepillar (opcional)","sub":"aparece la veta con un brillo plateado precioso"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_600", start: 599.6, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La técnica · 5","title":"Cómo se hace, paso a paso","steps":[{"title":"Madera seca (pino/cedro/ciprés)","sub":"si la quemás húmeda, el vapor revienta la superficie"},{"title":"Un soplete de gas","sub":"control total y barato — la chimenea tradicional es para expertos"},{"title":"Quemar hasta piel de cocodrilo","sub":"escamas negras brillantes: capa de carbón de 3-5 mm"},{"title":"Enfriar y cepillar (opcional)","sub":"aparece la veta con un brillo plateado precioso"},{"title":"Aceite, siempre","sub":"fija el carbón, lo nutre y suma repelencia al agua"}]} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_627", start: 626.8, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"Madera quemada + aceite es","highlight":"la combinación más duradera sin química","post":".","note":"fuego y aceite: toda la receta"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_650", start: 650.44, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"40 arreglos y secretos de los viejos","title":"Manual del Constructor Libre","bullet":"madera, óxido, humedad, plagas, caños — con medidas exactas","price":0,"cta":"LINK EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_685", start: 685.44, dur: 7.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Todo lo que podés quemar","items":["Postes enterrados (la base + un poco más)","Revestimiento y fachadas (yakisugi)","Deck, galería y piso de exterior","Muebles rústicos","Macetas y canteros de la huerta"],"stamp":"MISMA TÉCNICA"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_725", start: 725.24, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Un poste con base quemada + aceite","value":80,"suffix":" años","support":"enterrado, como el cerco de Don Ito — la parte bajo tierra es la que más sufre"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_820", start: 820.02, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Cuesta menos que un poste tratado","title":"Manual de Reparaciones Caseras","bullet":"40 soluciones caseras, con medidas y pasos, para cuando las necesites","price":0,"cta":"LINK ARRIBA DE TODO"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_825", start: 825.44, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Manual de reparaciones caseras","value":40,"suffix":"","support":"arreglos como este, con medidas y pasos, para cuando los necesites"} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_840", start: 840, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Lo que cubre el manual completo","items":["Madera","Óxido","Humedad y goteras","Plagas","Caños","Hasta cosas del auto"],"stamp":"40 ARREGLOS"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_886", start: 886.26, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Error 1: quemar la madera húmeda","truth":"El agua hierve y el vapor revienta la superficie: capa débil e inútil. Seca siempre"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_914", start: 914.39, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Error 2: quemar de más (el fuego es adictivo)","truth":"Carbonizar profundo la vuelve frágil: solo la piel de cocodrilo, 3-5 mm"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_946", start: 945.58, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Error 3: no apagar bien las brasas","truth":"Sigue quemándose sola y es riesgo de incendio: enfriá con agua apenas llegás al punto"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_982", start: 982.48, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Error 4: saltarse el aceite","truth":"El aceite fija el carbón y multiplica la duración: es el paso que la hace eterna"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_1008", start: 1008.08, dur: 6.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Consejo 1 de 4","title":"Consejos de los que saben","steps":[{"title":"Un día sin viento","sub":"el viento quema disparejo y es peligroso"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_1021", start: 1021.16, dur: 6.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Consejo 2 de 4","title":"Consejos de los que saben","steps":[{"title":"Un día sin viento","sub":"el viento quema disparejo y es peligroso"},{"title":"Probá en un descarte","sub":"agarrале la mano al punto de cocodrilo"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_1040", start: 1039.56, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Consejo 3 de 4","title":"Consejos de los que saben","steps":[{"title":"Un día sin viento","sub":"el viento quema disparejo y es peligroso"},{"title":"Probá en un descarte","sub":"agarrале la mano al punto de cocodrilo"},{"title":"Seguridad: balde de agua a mano","sub":"lejos de todo lo que prenda; nunca dejes brasas"}]} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_1064", start: 1063.72, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Consejo 4 de 4","title":"Consejos de los que saben","steps":[{"title":"Un día sin viento","sub":"el viento quema disparejo y es peligroso"},{"title":"Probá en un descarte","sub":"agarrале la mano al punto de cocodrilo"},{"title":"Seguridad: balde de agua a mano","sub":"lejos de todo lo que prenda; nunca dejes brasas"},{"title":"Manito de aceite cada tanto","sub":"cada par de años, 10 min, sin lijar"}]} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_1099", start: 1098.68, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Elegís el acabado","beforeLabel":"Carbón grueso: negro aterciopelado","afterLabel":"Cepillado: veta plateada","caption":"y hasta podés sumarle un tinte"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_1159", start: 1158.92, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"A veces, para que algo dure, primero hay que pasarlo por el fuego."} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_1273", start: 1272.84, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"¿Por qué casi nadie la conoce?","highlight":"porque no se puede vender","post":" — el fuego es gratis.","note":"nadie hace publicidad de lo gratis"} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_1295", start: 1295.48, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Por qué casi nadie la conoce","title":"Lo que se vende vs. lo gratis","left":{"label":"El producto de la latita","sub":"dura 3 años y tenés que volver a comprar — deja ganancia","good":false},"right":{"label":"El fuego","sub":"gratis, tuyo apenas lo aprendés, para siempre","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_1323", start: 1323.12, dur: 7.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Para llevarte lo importante","items":["El fuego protege de las 4 cosas que matan la madera","El punto: piel de cocodrilo, 3-5 mm","La madera tiene que estar seca","Enfriar, cepillar (opcional) y aceitar siempre"],"stamp":"RESUMEN"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_1366", start: 1366.44, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Empezá por el enlace de arriba","title":"Manual del Constructor Libre","bullet":"los 40 arreglos completos + el paso a paso de hoy, numerado","price":0,"cta":"LINK EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_1443", start: 1443.18, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"No dejes que nadie te haga tirar lo que todavía tiene vida."} as any)} /></PremiumOverlay> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":28.63,"role":"popUp","vol":0.32},{"at":85.86,"role":"popUp","vol":0.32},{"at":93.02,"role":"popUp","vol":0.32},{"at":100.68,"role":"popUp","vol":0.32},{"at":108,"role":"popUp","vol":0.32},{"at":185.88,"role":"popUp","vol":0.32},{"at":272.32,"role":"popUp","vol":0.32},{"at":296.56,"role":"popUp","vol":0.32},{"at":317.32,"role":"popUp","vol":0.32},{"at":325.28,"role":"popUp","vol":0.32},{"at":341.68,"role":"popUp","vol":0.32},{"at":409,"role":"popUp","vol":0.32},{"at":446.76,"role":"popUp","vol":0.32},{"at":491.26,"role":"popUp","vol":0.32},{"at":508.73,"role":"popUp","vol":0.32},{"at":516.55,"role":"popUp","vol":0.32},{"at":564.84,"role":"popUp","vol":0.32},{"at":599.6,"role":"popUp","vol":0.32},{"at":626.8,"role":"popUp","vol":0.32},{"at":650.44,"role":"popUp","vol":0.32},{"at":685.44,"role":"popUp","vol":0.32},{"at":725.24,"role":"popUp","vol":0.32},{"at":820.02,"role":"popUp","vol":0.32},{"at":825.44,"role":"popUp","vol":0.32},{"at":840,"role":"popUp","vol":0.32},{"at":886.26,"role":"popUp","vol":0.32},{"at":914.39,"role":"popUp","vol":0.32},{"at":945.58,"role":"popUp","vol":0.32},{"at":982.48,"role":"popUp","vol":0.32},{"at":1008.08,"role":"popUp","vol":0.32},{"at":1021.16,"role":"popUp","vol":0.32},{"at":1039.56,"role":"popUp","vol":0.32},{"at":1063.72,"role":"popUp","vol":0.32},{"at":1098.68,"role":"popUp","vol":0.32},{"at":1158.92,"role":"popUp","vol":0.32},{"at":1272.84,"role":"popUp","vol":0.32},{"at":1295.48,"role":"popUp","vol":0.32},{"at":1323.12,"role":"popUp","vol":0.32},{"at":1366.44,"role":"popUp","vol":0.32},{"at":1443.18,"role":"popUp","vol":0.32}];
