// cues_molino.gen.tsx — GENERADO por beatsheet.mjs desde molino.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/molino.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { BarCompare } from "./scenes/BarCompare";
import { CrossSection } from "./scenes/CrossSection";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { WindmillDiagram } from "./scenes/WindmillDiagram";
import { CalloutMark } from "./scenes/CalloutMark";
import { NextVideoEndcard } from "./scenes/NextVideoEndcard";
import { KeyPhrase } from "./scenes/KeyPhrase";

const D = COLORS.danger, B = COLORS.cold, G = COLORS.good;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "m_h_raise", start: 1.8, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_raise.png" darken={0} /> },
  { key: "m_h_wheel_dusk", start: 5.4, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_wheel_dusk.png" darken={0} /> },
  { key: "m_h_impact1", start: 8.8, dur: 5, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/m_h_wheel_dusk.png" impact="Not one power bill." setup="80 years turning." impactAccent="amber" hitAt={2} boom={0} darken={0.46} /> },
  { key: "m_h_old_mill", start: 13.8, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_old_mill.png" darken={0} /> },
  { key: "m_h_keyphrase", start: 18, dur: 4.6, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="It runs on the wind." src="img/m_h_wind_grass.png" accent="cold" fontSize={100} /> },
  { key: "m_h_water_tank", start: 22.6, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_water_tank.png" darken={0} /> },
  { key: "m_h_cattle", start: 26.8, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_cattle.png" darken={0} /> },
  { key: "m_h_clank", start: 31, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_clank.png" darken={0} /> },
  { key: "m_h_impact2", start: 35, dur: 5, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/m_h_well.png" impact="Lifted by wind alone." setup="85 feet down." impactAccent="amber" hitAt={1.9} boom={0} darken={0.46} /> },
  { key: "m_h_well", start: 40, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_well.png" darken={0} /> },
  { key: "m_h_claudio_bench", start: 44, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_claudio_bench.png" darken={0} /> },
  { key: "m_h_grandfather", start: 48, dur: 7.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_h_grandfather.png" darken={0} /> },
  { key: "m_windmill_old_standing", start: 54.6, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_windmill_old_standing.png" darken={0} /> },
  { key: "m_homestead_trees", start: 60, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_homestead_trees.mp4" darken={0} /> },
  { key: "m_f_fallen_tree", start: 64, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_fallen_tree.mp4" darken={0} /> },
  { key: "m_drought_cracked", start: 70, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_drought_cracked.png" darken={0} /> },
  { key: "m_blizzard_fence", start: 76, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_blizzard_fence.mp4" darken={0} /> },
  { key: "m_summer_heat_field", start: 83, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_summer_heat_field.png" darken={0} /> },
  { key: "cmp_open", start: 88, dur: 9, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={80} suffix=" years" label="pulling water with no motor, no fuel, no bill — it runs on the wind" eyebrow="Still turning" accent="good" hue="good" /> },
  { key: "m_f_clear_water_hand", start: 97, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_clear_water_hand.png" darken={0} /> },
  { key: "m_wind_grass_plains", start: 104.6, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_wind_grass_plains.png" darken={0} /> },
  { key: "m_f_grass_wind_wave", start: 108, dur: 11.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_grass_wind_wave.mp4" darken={0} /> },
  { key: "m_cattle_trough", start: 130.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_cattle_trough.mp4" darken={0} /> },
  { key: "m_storage_tank_farm", start: 136, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_storage_tank_farm.mp4" darken={0} /> },
  { key: "m_windmill_dusk", start: 142, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_windmill_dusk.mp4" darken={0} /> },
  { key: "m_f_mill_evening", start: 146, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_mill_evening.png" darken={0} /> },
  { key: "m_sleeping_house", start: 150, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_sleeping_house.png" darken={0} /> },
  { key: "m_f_quiet_farmhouse", start: 154, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_quiet_farmhouse.png" darken={0} /> },
  { key: "m_old_workbench", start: 158, dur: 9.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_old_workbench.png" darken={0} /> },
  { key: "m_wheel_breeze", start: 167.2, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_wheel_breeze.mp4" darken={0} /> },
  { key: "m_f_wheel_spin_slow", start: 172, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_wheel_spin_slow.png" darken={0} /> },
  { key: "m_cottonwood_leaves", start: 178, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_cottonwood_leaves.mp4" darken={0} /> },
  { key: "m_windmill_clank_close", start: 184, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_windmill_clank_close.png" darken={0} /> },
  { key: "m_deep_well_dark", start: 190, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_deep_well_dark.mp4" darken={0} /> },
  { key: "m_f_well_shaft_dark", start: 195, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_well_shaft_dark.mp4" darken={0} /> },
  { key: "cmp_welldepth", start: 200, dur: 11, kind: "cross", el: (d) => <CrossSection durationInFrames={d} layers={[{"label":"Surface — the dry sod","color":"#c9a25c","weight":0.7},{"label":"Soil & clay","color":"#9c7b46","weight":1},{"label":"Limestone rock","color":"#8a8a8a","weight":1.2},{"label":"Water table — cold & clean","color":"#3a6ea5","weight":1}]} eyebrow="Straight down" title="85 feet to water" marker={{"label":"the pump","atDepth":0.85,"color":"cold"}} hue="cold" /> },
  { key: "m_water_up_pipe", start: 211, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_water_up_pipe.mp4" darken={0} /> },
  { key: "m_stone_tank_hill", start: 218, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_stone_tank_hill.png" darken={0} /> },
  { key: "m_f_stone_cistern2", start: 224, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_stone_cistern2.mp4" darken={0} /> },
  { key: "m_cattle_herd_drink", start: 230.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_cattle_herd_drink.mp4" darken={0} /> },
  { key: "m_f_black_cattle2", start: 235, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_black_cattle2.mp4" darken={0} /> },
  { key: "m_tomato_patch", start: 240, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_tomato_patch.mp4" darken={0} /> },
  { key: "m_kitchen_faucet", start: 246, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_kitchen_faucet.mp4" darken={0} /> },
  { key: "m_empty_hand_no_cost", start: 250, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_empty_hand_no_cost.png" darken={0} /> },
  { key: "m_f_mill_proud2", start: 258, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_mill_proud2.mp4" darken={0} /> },
  { key: "cmp_notturbine", start: 264, dur: 6.81, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Not the modern turbine" items={["Modern turbine: makes electricity","Wires, batteries, circuit boards","Old windmill: lifts water, mechanically","Five iron parts, lasts a century"]} accent={D} cross /> },
  { key: "m_windmill_classic", start: 286.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_windmill_classic.png" darken={0} /> },
  { key: "m_wind_turbines_highway", start: 292, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_wind_turbines_highway.mp4" darken={0} /> },
  { key: "m_f_turbine_row2", start: 298, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_turbine_row2.mp4" darken={0} /> },
  { key: "m_turbine_generator", start: 307, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_turbine_generator.mp4" darken={0} /> },
  { key: "m_circuit_boards", start: 315, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_circuit_boards.png" darken={0} /> },
  { key: "m_f_wires_tangle", start: 320, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_wires_tangle.mp4" darken={0} /> },
  { key: "m_lightning_storm", start: 325, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_lightning_storm.png" darken={0} /> },
  { key: "m_f_storm_field2", start: 332, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_storm_field2.png" darken={0} /> },
  { key: "m_steel_blades_wheel", start: 339.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_steel_blades_wheel.mp4" darken={0} /> },
  { key: "m_f_galv_blades", start: 346, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_galv_blades.png" darken={0} /> },
  { key: "m_windmills_horizon", start: 354, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_windmills_horizon.png" darken={0} /> },
  { key: "m_f_prairie_horizon", start: 358, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_prairie_horizon.png" darken={0} /> },
  { key: "m_dry_plains_settle", start: 362, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_dry_plains_settle.mp4" darken={0} /> },
  { key: "m_no_creek_dry_land", start: 370, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_no_creek_dry_land.mp4" darken={0} /> },
  { key: "m_f_dry_sod", start: 375, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_dry_sod.mp4" darken={0} /> },
  { key: "m_one_job_water", start: 382, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_one_job_water.png" darken={0} /> },
  { key: "m_f_water_gush_pipe", start: 388, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_water_gush_pipe.mp4" darken={0} /> },
  { key: "m_thirsty_livestock", start: 393.5, dur: 0.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_thirsty_livestock.png" darken={0} /> },
  { key: "m_tower_top_down", start: 413, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_tower_top_down.mp4" darken={0} /> },
  { key: "m_f_tower_legs", start: 420, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_tower_legs.mp4" darken={0} /> },
  { key: "m_wheel_eight_foot", start: 426, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_wheel_eight_foot.mp4" darken={0} /> },
  { key: "m_f_wheel_hub_close", start: 431, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_wheel_hub_close.png" darken={0} /> },
  { key: "m_small_wheel_shallow", start: 435, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_small_wheel_shallow.mp4" darken={0} /> },
  { key: "m_huge_wheel_deep", start: 442, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_huge_wheel_deep.mp4" darken={0} /> },
  { key: "cmp_wheelsizes", start: 449, dur: 11, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"6 ft (shallow)","value":1,"display":"~75 gal","tone":"amber"},{"label":"8 ft (common)","value":3,"display":"150–300 gal","winner":true},{"label":"12 ft (deep)","value":5,"display":"500+ gal"}]} eyebrow="In a steady breeze" title="Bigger wheel, more water" unit="gal/hr" accent="good" hue="amber" /> },
  { key: "m_f_wheel_against_sky", start: 460, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_wheel_against_sky.png" darken={0} /> },
  { key: "m_wind_push_blades", start: 467, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_wind_push_blades.mp4" darken={0} /> },
  { key: "m_blade_angle_hub", start: 475, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_blade_angle_hub.png" darken={0} /> },
  { key: "m_f_blade_curve_macro", start: 482, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_blade_curve_macro.png" darken={0} /> },
  { key: "m_wheel_light_draft", start: 489.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_wheel_light_draft.mp4" darken={0} /> },
  { key: "m_slow_heavy_turn", start: 495, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_slow_heavy_turn.png" darken={0} /> },
  { key: "m_f_ox_power", start: 500, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_ox_power.png" darken={0} /> },
  { key: "m_heavy_water_column", start: 505, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_heavy_water_column.mp4" darken={0} /> },
  { key: "m_f_water_weight_pour", start: 510, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_water_weight_pour.png" darken={0} /> },
  { key: "m_tail_fin", start: 518.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_tail_fin.png" darken={0} /> },
  { key: "m_f_tail_vane_close", start: 525, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_tail_vane_close.png" darken={0} /> },
  { key: "m_tail_aim_wind", start: 534, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_tail_aim_wind.mp4" darken={0} /> },
  { key: "m_f_wind_direction_clouds", start: 542, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_wind_direction_clouds.mp4" darken={0} /> },
  { key: "m_weather_shift_clouds", start: 548, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_weather_shift_clouds.png" darken={0} /> },
  { key: "m_mill_head_pivot", start: 556, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_mill_head_pivot.png" darken={0} /> },
  { key: "m_f_iron_head_mill", start: 560, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_iron_head_mill.png" darken={0} /> },
  { key: "m_wheel_face_wind", start: 566, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_wheel_face_wind.png" darken={0} /> },
  { key: "m_f_wheel_face_breeze", start: 575, dur: 12.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_wheel_face_breeze.png" darken={0} /> },
  { key: "m_sunflower_field", start: 587, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_sunflower_field.mp4" darken={0} /> },
  { key: "m_f_sunflower_track", start: 592, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_sunflower_track.mp4" darken={0} /> },
  { key: "m_old_engineering", start: 600, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_old_engineering.mp4" darken={0} /> },
  { key: "m_f_cast_iron_gears", start: 608, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_cast_iron_gears.mp4" darken={0} /> },
  { key: "m_wheel_spinning_useless", start: 616, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_wheel_spinning_useless.png" darken={0} /> },
  { key: "m_cow_corn_water", start: 624, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_cow_corn_water.png" darken={0} /> },
  { key: "m_f_corn_rows_water", start: 628, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_corn_rows_water.mp4" darken={0} /> },
  { key: "m_up_down_motion", start: 632, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_up_down_motion.mp4" darken={0} /> },
  { key: "m_gearbox_oil", start: 640, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_gearbox_oil.mp4" darken={0} /> },
  { key: "m_f_gear_oil_pour", start: 646, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_gear_oil_pour.mp4" darken={0} /> },
  { key: "m_pitman_arm", start: 653.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_pitman_arm.png" darken={0} /> },
  { key: "m_f_pitman_motion", start: 660, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_pitman_motion.png" darken={0} /> },
  { key: "m_steel_rod_long", start: 667, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_steel_rod_long.png" darken={0} /> },
  { key: "m_ash_wood_rod", start: 676, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_ash_wood_rod.mp4" darken={0} /> },
  { key: "m_rod_down_tower", start: 685.5, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_rod_down_tower.mp4" darken={0} /> },
  { key: "m_f_rod_in_tower", start: 695, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_rod_in_tower.mp4" darken={0} /> },
  { key: "m_well_casing_top", start: 700, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_well_casing_top.mp4" darken={0} /> },
  { key: "m_f_well_head_ground", start: 704, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_well_head_ground.png" darken={0} /> },
  { key: "m_rod_into_water", start: 708, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_rod_into_water.mp4" darken={0} /> },
  { key: "m_pump_cylinder_deep", start: 714, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_pump_cylinder_deep.mp4" darken={0} /> },
  { key: "m_f_brass_cylinder2", start: 718, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_brass_cylinder2.mp4" darken={0} /> },
  { key: "m_brass_cylinder", start: 724, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_brass_cylinder.mp4" darken={0} /> },
  { key: "m_leather_cups", start: 731, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_leather_cups.mp4" darken={0} /> },
  { key: "m_f_leather_seal", start: 736, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_leather_seal.png" darken={0} /> },
  { key: "m_oiled_leather", start: 742, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_oiled_leather.png" darken={0} /> },
  { key: "m_f_oil_soak_leather", start: 748, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_oil_soak_leather.mp4" darken={0} /> },
  { key: "m_pump_valves", start: 753.5, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_pump_valves.mp4" darken={0} /> },
  { key: "m_f_pump_valve_close", start: 762, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_pump_valve_close.mp4" darken={0} /> },
  { key: "m_old_hand_pump", start: 768, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_old_hand_pump.mp4" darken={0} /> },
  { key: "m_f_handpump_red", start: 775, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_handpump_red.mp4" darken={0} /> },
  { key: "m_pump_handle_bucket", start: 780, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_pump_handle_bucket.mp4" darken={0} /> },
  { key: "m_f_pump_bucket_fill", start: 787, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_pump_bucket_fill.png" darken={0} /> },
  { key: "m_physics_same", start: 796.5, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_physics_same.mp4" darken={0} /> },
  { key: "m_f_water_simple_flow", start: 805, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_water_simple_flow.png" darken={0} /> },
  { key: "m_wind_does_pumping", start: 811.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_wind_does_pumping.png" darken={0} /> },
  { key: "m_f_mill_tireless", start: 817, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_mill_tireless.mp4" darken={0} /> },
  { key: "m_strokes_minute", start: 822, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_strokes_minute.png" darken={0} /> },
  { key: "m_f_rod_fast_stroke", start: 827, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_rod_fast_stroke.png" darken={0} /> },
  { key: "m_rain_midnight_mill", start: 831, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_rain_midnight_mill.png" darken={0} /> },
  { key: "m_f_mill_rain_night", start: 840, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_mill_rain_night.png" darken={0} /> },
  { key: "m_cylinder_stroke", start: 846, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_cylinder_stroke.png" darken={0} /> },
  { key: "m_f_cylinder_inside2", start: 854, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_cylinder_inside2.mp4" darken={0} /> },
  { key: "cmp_stroke", start: 860, dur: 7, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Up — valve shuts, lifts the column"},{"title":"Vacuum pulls fresh water in"},{"title":"Down — foot valve traps it"},{"title":"Piston reloads, ready again"}]} eyebrow="Up, down, up, down" title="Each stroke of the pump" accent="cold" hue="cold" /> },
  { key: "m_f_rod_rise2", start: 867, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_rod_rise2.png" darken={0} /> },
  { key: "m_piston_valve_shut", start: 872, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_piston_valve_shut.mp4" darken={0} /> },
  { key: "m_f_water_lift_column", start: 880, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_water_lift_column.png" darken={0} /> },
  { key: "m_foot_valve_open", start: 887, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_foot_valve_open.png" darken={0} /> },
  { key: "m_f_fresh_water_draw", start: 892, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_fresh_water_draw.png" darken={0} /> },
  { key: "m_rod_down_stroke", start: 897, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_rod_down_stroke.mp4" darken={0} /> },
  { key: "m_water_trapped", start: 902, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_water_trapped.mp4" darken={0} /> },
  { key: "m_f_rod_descend", start: 908, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_rod_descend.png" darken={0} /> },
  { key: "m_piston_reload", start: 914.5, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_piston_reload.png" darken={0} /> },
  { key: "m_f_water_trapped2", start: 922, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_water_trapped2.png" darken={0} /> },
  { key: "m_water_climbs_pipe", start: 930, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_water_climbs_pipe.png" darken={0} /> },
  { key: "m_f_water_higher_pipe", start: 935, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_water_higher_pipe.png" darken={0} /> },
  { key: "cmp_fiveparts", start: 940, dur: 8, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Wheel — harvests the wind"},{"title":"Tail — steers it into the weather"},{"title":"Gearbox — spins into strokes"},{"title":"Rod — carries it down the tower"},{"title":"Pump — lifts the water"}]} eyebrow="Clouds to bedrock" title="The whole machine — 5 iron parts" accent="amber" hue="amber" /> },
  { key: "cmp_howitworks", start: 948, dur: 8.5, kind: "windmill", el: (d) => <WindmillDiagram durationInFrames={d} eyebrow="How it works" title="Wind in, water up, gravity out" wind={{"text":"Wind","sub":"turns the wheel"}} pump={{"text":"Pump 85 ft down","sub":"rod strokes up & down"}} tank={{"text":"Tank on the hill","sub":"fills when wind blows"}} out={{"text":"Gravity to the house","sub":"pressure, always"}} partsTag="5 iron parts" /> },
  { key: "m_full_mill_system", start: 956.5, dur: 12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_full_mill_system.mp4" darken={0} /> },
  { key: "m_f_simple_mill_parts", start: 968, dur: 11.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_simple_mill_parts.png" darken={0} /> },
  { key: "m_no_wires_simple", start: 979, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_no_wires_simple.mp4" darken={0} /> },
  { key: "cmp_lasts", start: 984, dur: 13, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Iron windmill","value":8,"display":"100+ yrs","winner":true},{"label":"Electric pump","value":1,"display":"~12 yrs","tone":"amber"}]} eyebrow="Same job: lift water" title="How long it lasts" unit="years" accent="good" hue="amber" /> },
  { key: "m_burnt_electric_pump", start: 997, dur: 8.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_burnt_electric_pump.mp4" darken={0} /> },
  { key: "m_real_secret_setup", start: 1004.7, dur: 7.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_real_secret_setup.png" darken={0} /> },
  { key: "m_f_mill_tank_pair", start: 1012, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_mill_tank_pair.mp4" darken={0} /> },
  { key: "m_sensible_farmer", start: 1017, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_sensible_farmer.png" darken={0} /> },
  { key: "m_f_farmer_squint", start: 1024, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_farmer_squint.png" darken={0} /> },
  { key: "cmp_calmday", start: 1029, dur: 9, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="What about a calm day?" items={[{"text":"The mill fills the tank when wind blows","state":"done"},{"text":"The tank holds 2–3 days of water","state":"done"},{"text":"Gravity feeds the house with no wind","state":"done"},{"text":"Build the tank bigger than you think","state":"done"}]} eyebrow="Why it never runs dry" accent="good" hue="cold" image="img/cmp_calmday_bg.png" /> },
  { key: "m_f_still_air_flag", start: 1038, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_still_air_flag.mp4" darken={0} /> },
  { key: "m_brilliant_part", start: 1045, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_brilliant_part.png" darken={0} /> },
  { key: "m_f_high_cistern", start: 1051, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_high_cistern.png" darken={0} /> },
  { key: "m_mill_is_engine", start: 1057, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_mill_is_engine.mp4" darken={0} /> },
  { key: "m_f_mill_engine_head", start: 1063, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_mill_engine_head.png" darken={0} /> },
  { key: "m_tank_behind_barn", start: 1068.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_tank_behind_barn.mp4" darken={0} /> },
  { key: "m_f_big_tank_barn", start: 1072, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_big_tank_barn.png" darken={0} /> },
  { key: "m_fieldstone_cistern", start: 1076, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_fieldstone_cistern.png" darken={0} /> },
  { key: "m_f_stone_mortar_tank", start: 1080, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_stone_mortar_tank.mp4" darken={0} /> },
  { key: "m_f_cedar_tank2", start: 1088, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_cedar_tank2.mp4" darken={0} /> },
  { key: "m_poly_tank", start: 1093, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_poly_tank.mp4" darken={0} /> },
  { key: "cmp_storewater", start: 1098, dur: 12.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Store water, not wind" image="img/cmp_storewater_bg.png" eyebrow="The secret" caption="no batteries to rot — the wind fills a high tank, and gravity feeds the house even on a dead-calm day" accent="good" hue="cold" /> },
  { key: "m_no_batteries", start: 1110.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_no_batteries.png" darken={0} /> },
  { key: "m_f_dead_batteries", start: 1115, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_dead_batteries.mp4" darken={0} /> },
  { key: "m_store_water", start: 1119.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_store_water.mp4" darken={0} /> },
  { key: "m_f_strong_wind_mill", start: 1126, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_strong_wind_mill.png" darken={0} /> },
  { key: "m_overflow_pipe", start: 1132.5, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_overflow_pipe.png" darken={0} /> },
  { key: "m_f_overflow_water", start: 1140, dur: 11.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_overflow_water.mp4" darken={0} /> },
  { key: "m_dead_still_august", start: 1150.9, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_dead_still_august.png" darken={0} /> },
  { key: "m_f_hot_still_day", start: 1155, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_hot_still_day.png" darken={0} /> },
  { key: "m_no_worry_water", start: 1160.5, dur: 6.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_no_worry_water.png" darken={0} /> },
  { key: "m_gravity_falling", start: 1166.9, dur: 11.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_gravity_falling.mp4" darken={0} /> },
  { key: "m_water_down_pipes", start: 1177.7, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_water_down_pipes.mp4" darken={0} /> },
  { key: "m_f_buried_pipe2", start: 1182, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_buried_pipe2.mp4" darken={0} /> },
  { key: "m_tap_full_pressure", start: 1190, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_tap_full_pressure.mp4" darken={0} /> },
  { key: "m_f_tap_pressure2", start: 1195, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_tap_pressure2.png" darken={0} /> },
  { key: "m_silent_water_battery", start: 1202, dur: 9.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_silent_water_battery.mp4" darken={0} /> },
  { key: "m_torn_down_mill", start: 1226, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_torn_down_mill.png" darken={0} /> },
  { key: "cmp_whystopped", start: 1232, dur: 6.6, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="A monthly bill" image="img/cmp_whystopped_bg.png" eyebrow="Why we tore them down" caption="the grid + cheap electric pumps traded a free 100-year machine for convenience — and a utility bill forever" accent="danger" hue="red" /> },
  { key: "m_convenience_switch", start: 1238.6, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_convenience_switch.png" darken={0} /> },
  { key: "m_f_switch_finger", start: 1244, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_switch_finger.png" darken={0} /> },
  { key: "m_old_power_poles", start: 1248.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_old_power_poles.png" darken={0} /> },
  { key: "m_f_power_poles2", start: 1254, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_power_poles2.png" darken={0} /> },
  { key: "cmp_history", start: 1259, dur: 10.6, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Subsidized power lines reach the farms"},{"title":"Cheap electric pumps arrive"},{"title":"Low upfront cost, instant water"},{"title":"Towers torn down for scrap"}]} eyebrow="1930s–1950s" title="How we lost them" accent="danger" hue="red" /> },
  { key: "m_submersible_pump", start: 1269.6, dur: 8.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_submersible_pump.mp4" darken={0} /> },
  { key: "m_f_submersible2", start: 1278, dur: 11.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_submersible2.mp4" darken={0} /> },
  { key: "m_cash_upfront", start: 1289, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_cash_upfront.png" darken={0} /> },
  { key: "m_f_cash_hand2", start: 1298, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_cash_hand2.png" darken={0} /> },
  { key: "m_switch_instant_water", start: 1305, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_switch_instant_water.mp4" darken={0} /> },
  { key: "m_f_water_blast_tap", start: 1310, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_water_blast_tap.png" darken={0} /> },
  { key: "m_pump_down_hole", start: 1318, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_pump_down_hole.png" darken={0} /> },
  { key: "m_f_hidden_pump_well", start: 1323, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_hidden_pump_well.mp4" darken={0} /> },
  { key: "m_no_tower_yard", start: 1330, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_no_tower_yard.png" darken={0} /> },
  { key: "cmp_grease", start: 1336, dur: 9.7, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="The only chore" items={[{"text":"Climb the tower on a calm day","state":"done"},{"text":"Fresh gear oil in the head","state":"done"},{"text":"Check the leathers","state":"done"},{"text":"Tighten loose bolts, climb down","state":"done"}]} eyebrow="Once a year" accent="good" hue="amber" image="img/cmp_grease_bg.png" /> },
  { key: "m_trade_deal", start: 1345.7, dur: 7.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_trade_deal.png" darken={0} /> },
  { key: "cmp_trade", start: 1353, dur: 7, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="The trade we didn't read" items={["Gave: generational durability","Got: effortless convenience","Gave: a machine that costs $0 to run","Got: a bill to a utility for life"]} accent={B} /> },
  { key: "cmp_paths", start: 1392.9, dur: 12.6, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Two ways to get one" items={["Restore an old mill from a pasture","Mostly a weekend of your own labor","Or buy new from a traditional maker","Built once, never pay for water again"]} accent={G} /> },
  { key: "m_back_roads_drive", start: 1405.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_back_roads_drive.png" darken={0} /> },
  { key: "m_f_backroad_drive2", start: 1410, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_backroad_drive2.mp4" darken={0} /> },
  { key: "m_abandoned_homestead", start: 1416, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_abandoned_homestead.png" darken={0} /> },
  { key: "m_f_mill_in_briars", start: 1422, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_mill_in_briars.png" darken={0} /> },
  { key: "m_mill_overgrown_vines", start: 1426, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_mill_overgrown_vines.png" darken={0} /> },
  { key: "m_landowner_deal", start: 1435, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_landowner_deal.png" darken={0} /> },
  { key: "m_f_handshake_field2", start: 1440, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_handshake_field2.png" darken={0} /> },
  { key: "m_old_casting_workshop", start: 1445, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_old_casting_workshop.png" darken={0} /> },
  { key: "m_f_old_head_shop", start: 1450, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_old_head_shop.png" darken={0} /> },
  { key: "cmp_restorecheck", start: 1455, dur: 10, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Restoring an old mill" items={[{"text":"Gears preserved in old oil — usually fine","state":"done"},{"text":"New leather cups — about $30","state":"done"},{"text":"Treat leathers with tallow/oil","state":"done"},{"text":"Fresh gasket, bolt it back up","state":"done"}]} eyebrow="What to check" accent="good" hue="amber" image="img/cmp_restorecheck_bg.png" /> },
  { key: "cmp_restore", start: 1465, dur: 8.4, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Find an old tower in a pasture"},{"title":"Scrape the grease, pull the head"},{"title":"Gears still pristine in oil"},{"title":"$30 leather cups, bolt it up"}]} eyebrow="Path 1 — for a weekend's labor" title="Restore an old mill" accent="amber" hue="amber" /> },
  { key: "m_aermotor_702", start: 1473.4, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_aermotor_702.png" darken={0} /> },
  { key: "m_f_antique_gears2", start: 1478, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_antique_gears2.png" darken={0} /> },
  { key: "m_new_leather_cups", start: 1484, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_new_leather_cups.png" darken={0} /> },
  { key: "m_f_new_leathers2", start: 1488, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_new_leathers2.png" darken={0} /> },
  { key: "m_beef_tallow_treat", start: 1492, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_beef_tallow_treat.mp4" darken={0} /> },
  { key: "m_rebuilt_head_run", start: 1500, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_rebuilt_head_run.png" darken={0} /> },
  { key: "m_new_windmill_factory", start: 1504.2, dur: 6.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_new_windmill_factory.png" darken={0} /> },
  { key: "m_f_foundry_pour", start: 1510, dur: 7.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_foundry_pour.mp4" darken={0} /> },
  { key: "m_new_replica_mill", start: 1517.4, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_new_replica_mill.mp4" darken={0} /> },
  { key: "m_f_new_mill_shiny", start: 1522, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_new_mill_shiny.png" darken={0} /> },
  { key: "m_galvanized_steel_mill", start: 1528, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_galvanized_steel_mill.mp4" darken={0} /> },
  { key: "m_f_galv_steel2", start: 1534, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_galv_steel2.mp4" darken={0} /> },
  { key: "cmp_buyonce", start: 1540, dur: 5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Buy it once" image="img/cmp_buyonce_bg.png" eyebrow="Path 2 — new, built to last" caption="more up front than a cheap pump — but you pour the footings once and never pay for water again" accent="good" hue="amber" /> },
  { key: "cmp_lifecost", start: 1545, dur: 12.3, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Iron windmill","value":1,"display":"Buy once","sub":"+ grease yearly","winner":true},{"label":"Electric pump","value":4,"display":"pump × 3 + power bills","tone":"amber"}]} eyebrow="Same job: lift water" title="Cost over a lifetime" unit="USD over 30 yrs" accent="good" hue="amber" /> },
  { key: "m_buy_once", start: 1557.3, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_buy_once.png" darken={0} /> },
  { key: "m_pour_footings", start: 1561, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_pour_footings.mp4" darken={0} /> },
  { key: "m_f_footing_concrete", start: 1565, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_f_footing_concrete.mp4" darken={0} /> },
  { key: "m_built_to_last", start: 1617, dur: 14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/m_built_to_last.mp4" darken={0} /> },
  { key: "m_asks_nothing", start: 1630.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_asks_nothing.png" darken={0} /> },
  { key: "m_cold_sweet_water", start: 1636, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_cold_sweet_water.png" darken={0} /> },
  { key: "m_f_cold_water_glass", start: 1640, dur: 13.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_cold_water_glass.png" darken={0} /> },
  { key: "m_find_old_mill_brush", start: 1653, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_find_old_mill_brush.png" darken={0} /> },
  { key: "m_f_mill_brush_hidden", start: 1658, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_mill_brush_hidden.png" darken={0} /> },
  { key: "cmp_next", start: 1664, dur: 14, kind: "nextvideo", el: (d) => <NextVideoEndcard durationInFrames={d} title="Running water in every room — no pump, no power" kicker="Next time" sub="The old gravity system, the tank on the hill, and the one trick of the land. Water that runs itself." /> },
  { key: "m_f_windmill_farewell", start: 1678, dur: 9.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/m_f_windmill_farewell.png" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [

];
