// cues_comidas.gen.tsx — GENERADO por beatsheet.mjs desde comidas.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/comidas.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { TopDulce } from "./components/DulcesCards";
import { DishGrid } from "./components/DishGrid";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "intro_0", start: 0.16, dur: 2.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_2.jpg" hue="amber" /> },
  { key: "intro_1", start: 2.4, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_manos_viejas_1.jpg" hue="amber" /> },
  { key: "intro_2", start: 4, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_1.jpg" hue="amber" /> },
  { key: "intro_3", start: 5.6, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_68.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.5} /> },
  { key: "intro_4", start: 8.5, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_1.jpg" hue="amber" /> },
  { key: "intro_5", start: 11.1, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_pan_mesa_2.jpg" hue="amber" /> },
  { key: "intro_6", start: 13.7, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_76.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.6} /> },
  { key: "intro_7", start: 15.9, dur: 1.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_3.jpg" hue="amber" /> },
  { key: "intro_8", start: 17.8, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_1.jpg" hue="amber" /> },
  { key: "intro_9", start: 20.5, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_mesa_humilde_1.jpg" hue="amber" /> },
  { key: "intro_10", start: 22.6, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_2.jpg" hue="amber" /> },
  { key: "intro_11", start: 24.9, dur: 1.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_73.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.4} /> },
  { key: "intro_12", start: 26.7, dur: 1.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_36.mp4" hue="amber" fit="blur" clipDur={7.1} /> },
  { key: "intro_13", start: 28.1, dur: 1.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_20.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={8.01} /> },
  { key: "intro_14", start: 29.4, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_22.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={6.32} /> },
  { key: "intro_15", start: 32, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_23.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7.01} /> },
  { key: "intro_16", start: 35.3, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_2.jpg" hue="amber" /> },
  { key: "intro_17", start: 38.3, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_4.jpg" hue="amber" /> },
  { key: "intro_18", start: 40.6, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_2.jpg" hue="amber" /> },
  { key: "intro_19", start: 43.3, dur: 1.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_53.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7} /> },
  { key: "intro_20", start: 45, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_1.jpg" hue="amber" /> },
  { key: "intro_21", start: 47.9, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_89.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.9} /> },
  { key: "intro_22", start: 52.4, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_105.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.1} /> },
  { key: "intro_23", start: 55.5, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_5.jpg" hue="amber" /> },
  { key: "co_13", start: 62.56, dur: 8.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_2.jpg" hue="amber" /> },
  { key: "co_14", start: 71.48, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_3.jpg" hue="amber" /> },
  { key: "co_15", start: 75.32, dur: 6.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_manos_viejas_1.jpg" hue="amber" /> },
  { key: "co_16", start: 81.59, dur: 5.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_20.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={8.01} /> },
  { key: "co_17", start: 87.24, dur: 7.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_22.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={6.32} /> },
  { key: "co_18", start: 94.4, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_mesa_humilde_1.jpg" hue="amber" /> },
  { key: "co_19", start: 98.8, dur: 7.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_pan_mesa_2.jpg" hue="amber" /> },
  { key: "co_20", start: 106.05, dur: 7.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_20.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={8.01} /> },
  { key: "co_21", start: 114.04, dur: 6.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_1.jpg" hue="amber" /> },
  { key: "co_22", start: 120.6, dur: 6.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_22.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={6.32} /> },
  { key: "co_23", start: 126.92, dur: 6.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_23.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7.01} /> },
  { key: "co_24", start: 133.91, dur: 7.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_23.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7.01} /> },
  { key: "co_25", start: 141.32, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_3.jpg" hue="amber" /> },
  { key: "co_26", start: 147.32, dur: 5.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_1.jpg" hue="amber" /> },
  { key: "co_27", start: 152.37, dur: 5.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_2.jpg" hue="amber" /> },
  { key: "co_28", start: 157.79, dur: 5.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_3.jpg" hue="amber" /> },
  { key: "co_29", start: 163.3, dur: 7.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_4.jpg" hue="amber" /> },
  { key: "co_30", start: 171.2, dur: 7.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_2.jpg" hue="amber" /> },
  { key: "co_31", start: 178.48, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_3.jpg" hue="amber" /> },
  { key: "co_32", start: 181.53, dur: 6.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_5.jpg" hue="amber" /> },
  { key: "co_33", start: 187.64, dur: 7.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_1.jpg" hue="amber" /> },
  { key: "co_34", start: 194.95, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_3.jpg" hue="amber" /> },
  { key: "co_35", start: 197.46, dur: 4.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_2.jpg" hue="amber" /> },
  { key: "co_36", start: 202.23, dur: 7.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_36.mp4" hue="amber" fit="blur" clipDur={7.1} /> },
  { key: "co_37", start: 209.3, dur: 6.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_37.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={6.7} /> },
  { key: "co_38", start: 216, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_36.mp4" hue="amber" fit="blur" clipDur={7.1} /> },
  { key: "co_39", start: 220.16, dur: 7.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_37.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={6.7} /> },
  { key: "co_40", start: 227.88, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_3.jpg" hue="amber" /> },
  { key: "co_41", start: 230.36, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_4.jpg" hue="amber" /> },
  { key: "co_42", start: 236, dur: 7.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_42.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7.4} /> },
  { key: "co_43", start: 243.37, dur: 4.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_42.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7.4} /> },
  { key: "co_44", start: 248.18, dur: 5.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_5.jpg" hue="amber" /> },
  { key: "co_45", start: 254.16, dur: 7.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_2.jpg" hue="amber" /> },
  { key: "co_46", start: 261.62, dur: 2.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_3.jpg" hue="amber" /> },
  { key: "co_47", start: 264.11, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_4.jpg" hue="amber" /> },
  { key: "co_48", start: 268.73, dur: 4.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_53.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7} /> },
  { key: "co_49", start: 273.16, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_1.jpg" hue="amber" /> },
  { key: "co_50", start: 278.98, dur: 5.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_2.jpg" hue="amber" /> },
  { key: "co_51", start: 284.43, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_4.jpg" hue="amber" /> },
  { key: "co_52", start: 288.28, dur: 7.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_6.jpg" hue="amber" /> },
  { key: "co_53", start: 295.89, dur: 6.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_53.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={7} /> },
  { key: "co_54", start: 302.85, dur: 4.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_3.jpg" hue="amber" /> },
  { key: "co_55", start: 307.8, dur: 6.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_4.jpg" hue="amber" /> },
  { key: "co_56", start: 314.48, dur: 5.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_5.jpg" hue="amber" /> },
  { key: "co_57", start: 320.39, dur: 4.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_2.jpg" hue="amber" /> },
  { key: "co_58", start: 324.42, dur: 5.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_3.jpg" hue="amber" /> },
  { key: "co_59", start: 329.6, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_5.jpg" hue="amber" /> },
  { key: "co_60", start: 333.4, dur: 5.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_2.jpg" hue="amber" /> },
  { key: "co_61", start: 338.99, dur: 5.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_3.jpg" hue="amber" /> },
  { key: "co_62", start: 344.44, dur: 5.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_manos_viejas_1.jpg" hue="amber" /> },
  { key: "co_63", start: 349.8, dur: 6.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_mesa_humilde_1.jpg" hue="amber" /> },
  { key: "co_64", start: 356.14, dur: 5.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_pan_mesa_2.jpg" hue="amber" /> },
  { key: "co_65", start: 362.08, dur: 8.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_1.jpg" hue="amber" /> },
  { key: "co_66", start: 370.09, dur: 5.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_3.jpg" hue="amber" /> },
  { key: "co_67", start: 376.01, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_68.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.5} /> },
  { key: "co_68", start: 381.31, dur: 5.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_68.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.5} /> },
  { key: "co_69", start: 386.82, dur: 7.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_73.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.4} /> },
  { key: "co_70", start: 394.15, dur: 5.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_68.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.5} /> },
  { key: "co_71", start: 399.99, dur: 6.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_73.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.4} /> },
  { key: "co_72", start: 406, dur: 6.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_1.jpg" hue="amber" /> },
  { key: "co_73", start: 412.67, dur: 5.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_73.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.4} /> },
  { key: "co_74", start: 418.08, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_76.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.6} /> },
  { key: "co_75", start: 422.58, dur: 4.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_76.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.6} /> },
  { key: "co_76", start: 427.51, dur: 5.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_76.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.6} /> },
  { key: "co_77", start: 433.1, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_2.jpg" hue="amber" /> },
  { key: "co_78", start: 436.4, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_3.jpg" hue="amber" /> },
  { key: "co_79", start: 441.44, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_4.jpg" hue="amber" /> },
  { key: "co_80", start: 447.46, dur: 5.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_2.jpg" hue="amber" /> },
  { key: "co_81", start: 453.09, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_3.jpg" hue="amber" /> },
  { key: "co_82", start: 459.25, dur: 5.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_5.jpg" hue="amber" /> },
  { key: "co_83", start: 464.58, dur: 5.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_1.jpg" hue="amber" /> },
  { key: "co_84", start: 470.04, dur: 5.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_3.jpg" hue="amber" /> },
  { key: "co_85", start: 475.28, dur: 7.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_2.jpg" hue="amber" /> },
  { key: "co_86", start: 482.5, dur: 6.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_3.jpg" hue="amber" /> },
  { key: "co_87", start: 489.21, dur: 6.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_89.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.9} /> },
  { key: "co_88", start: 495.96, dur: 7.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_89.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.9} /> },
  { key: "co_89", start: 503.26, dur: 4.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_89.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.9} /> },
  { key: "co_90", start: 508.19, dur: 7.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_4.jpg" hue="amber" /> },
  { key: "co_91", start: 515.6, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_5.jpg" hue="amber" /> },
  { key: "co_92", start: 519.64, dur: 5.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_2.jpg" hue="amber" /> },
  { key: "co_93", start: 524.88, dur: 7.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_97.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.41} /> },
  { key: "co_94", start: 532.33, dur: 7.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_97.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.41} /> },
  { key: "co_95", start: 539.96, dur: 5.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_3.jpg" hue="amber" /> },
  { key: "co_96", start: 545.49, dur: 6.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_4.jpg" hue="amber" /> },
  { key: "co_97", start: 551.84, dur: 5.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_97.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.41} /> },
  { key: "co_98", start: 557.25, dur: 4.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_1.jpg" hue="amber" /> },
  { key: "co_99", start: 561.78, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_2.jpg" hue="amber" /> },
  { key: "co_100", start: 566.78, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_4.jpg" hue="amber" /> },
  { key: "co_101", start: 569.32, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_6.jpg" hue="amber" /> },
  { key: "co_102", start: 575.72, dur: 5.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_3.jpg" hue="amber" /> },
  { key: "co_103", start: 581.28, dur: 6.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_4.jpg" hue="amber" /> },
  { key: "co_104", start: 587.95, dur: 6.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_5.jpg" hue="amber" /> },
  { key: "co_105", start: 594, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_105.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.1} /> },
  { key: "co_106", start: 599.12, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_105.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.1} /> },
  { key: "co_107", start: 602.14, dur: 5.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_105.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={5.1} /> },
  { key: "co_108", start: 608.06, dur: 6.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_2.jpg" hue="amber" /> },
  { key: "co_109", start: 615.03, dur: 6.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_3.jpg" hue="amber" /> },
  { key: "co_110", start: 622, dur: 5.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_5.jpg" hue="amber" /> },
  { key: "co_111", start: 627.09, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_2.jpg" hue="amber" /> },
  { key: "co_112", start: 631.97, dur: 6.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_3.jpg" hue="amber" /> },
  { key: "co_113", start: 638.59, dur: 7.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_manos_viejas_1.jpg" hue="amber" /> },
  { key: "co_114", start: 645.72, dur: 4.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_mesa_humilde_1.jpg" hue="amber" /> },
  { key: "co_115", start: 650.45, dur: 7.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_pan_mesa_2.jpg" hue="amber" /> },
  { key: "co_116", start: 658.12, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_1.jpg" hue="amber" /> },
  { key: "co_117", start: 662.62, dur: 7.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_3.jpg" hue="amber" /> },
  { key: "co_118", start: 670.59, dur: 6.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_1.jpg" hue="amber" /> },
  { key: "co_119", start: 677.38, dur: 7.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_2.jpg" hue="amber" /> },
  { key: "co_120", start: 684.8, dur: 6.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_3.jpg" hue="amber" /> },
  { key: "co_121", start: 691.1, dur: 4.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_4.jpg" hue="amber" /> },
  { key: "co_122", start: 696.03, dur: 5.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_2.jpg" hue="amber" /> },
  { key: "co_123", start: 701.95, dur: 6.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_3.jpg" hue="amber" /> },
  { key: "co_124", start: 708.84, dur: 7.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_5.jpg" hue="amber" /> },
  { key: "co_125", start: 716.21, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_1.jpg" hue="amber" /> },
  { key: "co_126", start: 720.81, dur: 8.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_3.jpg" hue="amber" /> },
  { key: "co_127", start: 729.46, dur: 5.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_2.jpg" hue="amber" /> },
  { key: "co_128", start: 735.07, dur: 5.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_3.jpg" hue="amber" /> },
  { key: "co_129", start: 741.02, dur: 5.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_133.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.5} /> },
  { key: "co_130", start: 746.17, dur: 6.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_133.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.5} /> },
  { key: "co_131", start: 752.87, dur: 7.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_133.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.5} /> },
  { key: "co_132", start: 760.46, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_4.jpg" hue="amber" /> },
  { key: "co_133", start: 764.2, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/co_133.mp4" hue="amber" zoom={[1.04,1.06]} clipDur={4.5} /> },
  { key: "co_134", start: 768.71, dur: 7.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_5.jpg" hue="amber" /> },
  { key: "co_135", start: 776.46, dur: 5.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_2.jpg" hue="amber" /> },
  { key: "co_136", start: 782.02, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_3.jpg" hue="amber" /> },
  { key: "co_137", start: 787.18, dur: 7.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_4.jpg" hue="amber" /> },
  { key: "co_138", start: 794.41, dur: 4.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_1.jpg" hue="amber" /> },
  { key: "co_139", start: 799.22, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_2.jpg" hue="amber" /> },
  { key: "co_140", start: 803.96, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_4.jpg" hue="amber" /> },
  { key: "co_141", start: 808.47, dur: 6.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_6.jpg" hue="amber" /> },
  { key: "co_142", start: 815.28, dur: 6.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_3.jpg" hue="amber" /> },
  { key: "co_143", start: 822.14, dur: 8.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_4.jpg" hue="amber" /> },
  { key: "co_144", start: 830.54, dur: 5.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_5.jpg" hue="amber" /> },
  { key: "co_145", start: 836.29, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_2.jpg" hue="amber" /> },
  { key: "co_146", start: 840.81, dur: 7.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_3.jpg" hue="amber" /> },
  { key: "co_147", start: 848.15, dur: 5.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mesa_5.jpg" hue="amber" /> },
  { key: "co_148", start: 854.11, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_2.jpg" hue="amber" /> },
  { key: "co_149", start: 857.37, dur: 7.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_cocina_vieja_3.jpg" hue="amber" /> },
  { key: "co_150", start: 864.63, dur: 7.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_manos_viejas_1.jpg" hue="amber" /> },
  { key: "co_151", start: 871.65, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_mesa_humilde_1.jpg" hue="amber" /> },
  { key: "co_152", start: 877.35, dur: 7.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_pan_mesa_2.jpg" hue="amber" /> },
  { key: "co_153", start: 884.83, dur: 7.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_1.jpg" hue="amber" /> },
  { key: "co_154", start: 892.5, dur: 7.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/nost_persona_sola_3.jpg" hue="amber" /> },
  { key: "co_155", start: 900.44, dur: 4.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_1.jpg" hue="amber" /> },
  { key: "co_156", start: 905.07, dur: 5.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_2.jpg" hue="amber" /> },
  { key: "co_157", start: 910.7, dur: 7.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_3.jpg" hue="amber" /> },
  { key: "co_158", start: 918.39, dur: 4.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_abuela_4.jpg" hue="amber" /> },
  { key: "co_159", start: 923.06, dur: 5.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_2.jpg" hue="amber" /> },
  { key: "co_160", start: 928.42, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_3.jpg" hue="amber" /> },
  { key: "co_161", start: 932, dur: 5.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_campo_5.jpg" hue="amber" /> },
  { key: "co_162", start: 937.25, dur: 4.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_1.jpg" hue="amber" /> },
  { key: "co_163", start: 942.06, dur: 5.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_cocina_3.jpg" hue="amber" /> },
  { key: "co_164", start: 947.91, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_2.jpg" hue="amber" /> },
  { key: "co_165", start: 952.06, dur: 7.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_3.jpg" hue="amber" /> },
  { key: "co_166", start: 959.45, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_4.jpg" hue="amber" /> },
  { key: "co_167", start: 963.97, dur: 5.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_estufa_5.jpg" hue="amber" /> },
  { key: "co_168", start: 969.32, dur: 6.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_2.jpg" hue="amber" /> },
  { key: "co_169", start: 975.55, dur: 2.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_3.jpg" hue="amber" /> },
  { key: "co_170", start: 978.18, dur: 6.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_familia_4.jpg" hue="amber" /> },
  { key: "co_171", start: 984.79, dur: 6.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_1.jpg" hue="amber" /> },
  { key: "co_172", start: 991.51, dur: 7.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_2.jpg" hue="amber" /> },
  { key: "co_173", start: 999.32, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_4.jpg" hue="amber" /> },
  { key: "co_174", start: 1005.02, dur: 7.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_manos_6.jpg" hue="amber" /> },
  { key: "co_175", start: 1012.74, dur: 6.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vin_mate_3.jpg" hue="amber" /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "dishgrid", start: 47.9, dur: 9.6, kind: "dishgrid", el: (d) => <DishGrid durationInFrames={d} images={["real/nost_cocina_vieja_2.jpg","real/nost_cocina_vieja_3.jpg","real/nost_manos_viejas_1.jpg","real/nost_mesa_humilde_1.jpg","real/nost_pan_mesa_2.jpg","real/vin_cocina_1.jpg","real/vin_cocina_3.jpg","real/vin_estufa_2.jpg","real/vin_estufa_3.jpg","real/vin_estufa_4.jpg","real/vin_estufa_5.jpg","real/vin_manos_1.jpg","real/vin_manos_2.jpg","real/vin_manos_4.jpg","real/vin_manos_6.jpg","real/vin_mesa_2.jpg","real/vin_mesa_3.jpg","real/vin_mesa_5.jpg","real/nost_persona_sola_1.jpg","real/nost_persona_sola_3.jpg","real/vin_abuela_1.jpg","real/vin_abuela_2.jpg","real/vin_abuela_3.jpg","real/vin_abuela_4.jpg","real/vin_campo_2.jpg"]} cols={5} title="25 comidas" eyebrow="de antes" /> },
  { key: "top_1", start: 79.05, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={1} title="Sopa de pan" total={25} image="broll/co_20.mp4" /> },
  { key: "top_2", start: 119.93, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={2} title="Guiso de lentejas" total={25} image="broll/co_23.mp4" /> },
  { key: "top_3", start: 162.3, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={3} title="Polenta" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_4", start: 199.6, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={4} title="Tortilla de papas" total={25} image="broll/co_36.mp4" /> },
  { key: "top_5", start: 235.23, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={5} title="Arroz con huevo" total={25} image="broll/co_42.mp4" /> },
  { key: "top_6", start: 267.83, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={6} title="Fideos con manteca" total={25} image="broll/co_53.mp4" /> },
  { key: "top_7", start: 302.04, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={7} title="Arroz guisado" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_8", start: 337.99, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={8} title="Zapallo" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_9", start: 375.01, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={9} title="Puchero" total={25} image="broll/co_68.mp4" /> },
  { key: "top_10", start: 412.15, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={10} title="Guiso de arroz" total={25} image="broll/co_76.mp4" /> },
  { key: "top_11", start: 452.44, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={11} title="Tortas fritas" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_12", start: 488.4, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={12} title="Buñuelos de acelga" total={25} image="broll/co_89.mp4" /> },
  { key: "top_13", start: 522.87, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={13} title="Pan con grasa" total={25} image="broll/co_97.mp4" /> },
  { key: "top_14", start: 556.39, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={14} title="Sopa de verduras" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_15", start: 591.25, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={15} title="Croquetas" total={25} image="broll/co_105.mp4" /> },
  { key: "top_16", start: 626.31, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={16} title="Pastel de papa" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_17", start: 661.62, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={17} title="Locro" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_18", start: 698.94, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={18} title="Revuelto de zapallitos" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_19", start: 734.39, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={19} title="Albóndigas" total={25} image="broll/co_133.mp4" /> },
  { key: "top_20", start: 767.94, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={20} title="Ensalada de lentejas" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_21", start: 803.12, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={21} title="Budín de pan" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_22", start: 835.35, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={22} title="Leche cocida con maicena" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_23", start: 870.96, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={23} title="Fideos guisados" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_24", start: 906.84, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={24} title="Mate cocido" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
  { key: "top_25", start: 947.15, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={25} title="Papa con manteca" total={25} image="real/nost_cocina_vieja_2.jpg" /> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":47.9,"role":"popUp","vol":0.32},{"at":79.05,"role":"popUp","vol":0.32},{"at":119.93,"role":"popUp","vol":0.32},{"at":162.3,"role":"popUp","vol":0.32},{"at":199.6,"role":"popUp","vol":0.32},{"at":235.23,"role":"popUp","vol":0.32},{"at":267.83,"role":"popUp","vol":0.32},{"at":302.04,"role":"popUp","vol":0.32},{"at":337.99,"role":"popUp","vol":0.32},{"at":375.01,"role":"popUp","vol":0.32},{"at":412.15,"role":"popUp","vol":0.32},{"at":452.44,"role":"popUp","vol":0.32},{"at":488.4,"role":"popUp","vol":0.32},{"at":522.87,"role":"popUp","vol":0.32},{"at":556.39,"role":"popUp","vol":0.32},{"at":591.25,"role":"popUp","vol":0.32},{"at":626.31,"role":"popUp","vol":0.32},{"at":661.62,"role":"popUp","vol":0.32},{"at":698.94,"role":"popUp","vol":0.32},{"at":734.39,"role":"popUp","vol":0.32},{"at":767.94,"role":"popUp","vol":0.32},{"at":803.12,"role":"popUp","vol":0.32},{"at":835.35,"role":"popUp","vol":0.32},{"at":870.96,"role":"popUp","vol":0.32},{"at":906.84,"role":"popUp","vol":0.32},{"at":947.15,"role":"popUp","vol":0.32}];
