// cues_ventilador.gen.tsx — GENERADO por beatsheet.mjs desde ventilador.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/ventilador.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { EyebrowKicker, FrictionCard, SecretSealCard, PromiseChecklist, FanFailProof, EvaporationPhysics, FanBottleAssembly, WrongVsRightPlacement, BottleSizeGauge, SaltPhysicsDiagram, StepByStepBuild, DripTrayCallout, RotationCycleDiagram, OldTimersStamp, MythBusterCard, DistanceLimitWarning, ThreeLegsDiagram, NightDayCycle, CostVsCard, RecapNumberedList, ManualCTACard, NextVideoTeaser } from "./overlays/VentiladorKit";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "vt_hot_night_sweating", start: 0.11, dur: 1.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_hot_night_sweating.png" hue="amber" darken={0} /> },
  { key: "vt_hot_night_no_sleep", start: 1.04, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_hot_night_no_sleep.mp4" hue="red" darken={0} /> },
  { key: "vt_fan_only_blows_hot_air", start: 4.18, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_fan_only_blows_hot_air.mp4" hue="blue" darken={0} /> },
  { key: "vt_fan_blowing_warm_air", start: 7.72, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_blowing_warm_air.png" hue="amber" darken={0} /> },
  { key: "vt_fan_only_moves_air", start: 10.52, dur: 8.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_only_moves_air.png" hue="red" darken={0} /> },
  { key: "vt_electricity_meter_running", start: 18.23, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_electricity_meter_running.png" hue="blue" darken={0} /> },
  { key: "vt_ac_unit_expensive", start: 21.7, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_ac_unit_expensive.png" hue="amber" darken={0} /> },
  { key: "vt_old_fan_running_full", start: 25.96, dur: 5.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_old_fan_running_full.png" hue="red" darken={0} /> },
  { key: "vt_bottles_each_side_axis", start: 30.88, dur: 7.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_bottles_each_side_axis.mp4" hue="blue" darken={0} /> },
  { key: "vt_no_electric_meter", start: 38.34, dur: 1.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_no_electric_meter.png" hue="amber" darken={0} /> },
  { key: "vt_person_feeling_cold_air", start: 39.4, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_person_feeling_cold_air.png" hue="red" darken={0} /> },
  { key: "vt_fan_trapped_hot_cold", start: 44, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_fan_trapped_hot_cold.mp4" hue="blue" darken={0} /> },
  { key: "vt_manual_constructor_libre", start: 45.92, dur: 11.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_manual_constructor_libre.png" hue="amber" darken={0} /> },
  { key: "vt_fan_doesnt_cool_moves_air", start: 57.06, dur: 2.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_fan_doesnt_cool_moves_air.mp4" hue="blue" darken={0} /> },
  { key: "vt_bottles_behind_fan", start: 59.61, dur: 1.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bottles_behind_fan.png" hue="amber" darken={0} /> },
  { key: "vt_salt_box_kitchen", start: 61.24, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_salt_box_kitchen.png" hue="red" darken={0} /> },
  { key: "vt_bottles_wrong_position", start: 63.95, dur: 9.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bottles_wrong_position.png" hue="blue" darken={0} /> },
  { key: "vt_fan_bedroom_corner", start: 73.34, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_bedroom_corner.png" hue="amber" darken={0} /> },
  { key: "vt_thermometer_outside_35C", start: 78.16, dur: 13.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_thermometer_outside_35C.png" hue="red" darken={0} /> },
  { key: "vt_fan_sitting_desk_office", start: 91.84, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_sitting_desk_office.png" hue="blue" darken={0} /> },
  { key: "vt_fan_cools_your_body_sweat", start: 97.2, dur: 7.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_fan_cools_your_body_sweat.mp4" hue="red" darken={0} /> },
  { key: "vt_breeze_cold_face", start: 104.2, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_breeze_cold_face.png" hue="blue" darken={0} /> },
  { key: "vt_thermometer_inside_cool", start: 107.04, dur: 6.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_thermometer_inside_cool.png" hue="amber" darken={0} /> },
  { key: "vt_humid_hot_day_fan_useless", start: 112.86, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_humid_hot_day_fan_useless.mp4" hue="red" darken={0} /> },
  { key: "vt_comparison_hot_humid_dry", start: 114.97, dur: 6.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_comparison_hot_humid_dry.png" hue="blue" darken={0} /> },
  { key: "vt_temperature_gradient_room", start: 121.06, dur: 16.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_temperature_gradient_room.png" hue="blue" darken={0} /> },
  { key: "vt_water_bottle_freezing", start: 136.9, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_water_bottle_freezing.png" hue="amber" darken={0} /> },
  { key: "vt_bottles_in_freezer", start: 139.72, dur: 1.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bottles_in_freezer.png" hue="red" darken={0} /> },
  { key: "vt_freezer_overnight", start: 141, dur: 15.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_freezer_overnight.mp4" hue="amber" darken={0} /> },
  { key: "vt_fan_back_showing_grille", start: 156.06, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_back_showing_grille.png" hue="red" darken={0} /> },
  { key: "vt_cold_air_before_fan_idea", start: 159.46, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_cold_air_before_fan_idea.mp4" hue="blue" darken={0} /> },
  { key: "vt_cold_fresh_air_flows", start: 162.24, dur: 6.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_cold_fresh_air_flows.mp4" hue="amber" darken={0} /> },
  { key: "vt_bottles_sweating_frost", start: 168.49, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bottles_sweating_frost.png" hue="red" darken={0} /> },
  { key: "vt_correct_back_position", start: 171.34, dur: 13.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_correct_back_position.mp4" hue="red" darken={0} /> },
  { key: "vt_bottles_behind_fan_back", start: 184.22, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_bottles_behind_fan_back.mp4" hue="blue" darken={0} /> },
  { key: "vt_tie_bottles_to_fan_back", start: 187.1, dur: 9.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_tie_bottles_to_fan_back.mp4" hue="amber" darken={0} /> },
  { key: "vt_empty_bottles_discard", start: 195.97, dur: 6.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_empty_bottles_discard.png" hue="red" darken={0} /> },
  { key: "vt_wrong_placement_front", start: 202.3, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_wrong_placement_front.mp4" hue="blue" darken={0} /> },
  { key: "vt_pure_water_not_salty", start: 205.21, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_pure_water_not_salty.png" hue="amber" darken={0} /> },
  { key: "vt_point_fan_at_you", start: 208.48, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_point_fan_at_you.mp4" hue="red" darken={0} /> },
  { key: "vt_bottles_fully_frozen", start: 210.92, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bottles_fully_frozen.png" hue="blue" darken={0} /> },
  { key: "vt_small_bottles_melt_fast", start: 214.32, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_small_bottles_melt_fast.mp4" hue="amber" darken={0} /> },
  { key: "vt_small_bottle_bad", start: 218.86, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_small_bottle_bad.png" hue="red" darken={0} /> },
  { key: "vt_large_bottles_last_longer", start: 222.48, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_large_bottles_last_longer.mp4" hue="blue" darken={0} /> },
  { key: "vt_large_bidons_ideal", start: 227.04, dur: 2.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_large_bidons_ideal.png" hue="amber" darken={0} /> },
  { key: "vt_two_three_hours_cold", start: 228.9, dur: 6.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_two_three_hours_cold.mp4" hue="red" darken={0} /> },
  { key: "vt_multiple_fans_house", start: 235.05, dur: 4.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_multiple_fans_house.png" hue="blue" darken={0} /> },
  { key: "vt_salt_makes_fresco_last_longer", start: 239.72, dur: 10.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_salt_makes_fresco_last_longer.mp4" hue="red" darken={0} /> },
  { key: "vt_salt_into_water", start: 249.88, dur: 5.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_salt_into_water.png" hue="blue" darken={0} /> },
  { key: "vt_shaking_salty_water", start: 254.96, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_shaking_salty_water.png" hue="amber" darken={0} /> },
  { key: "vt_frozen_pure_vs_salty", start: 257.58, dur: 12.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_frozen_pure_vs_salty.png" hue="red" darken={0} /> },
  { key: "vt_old_ice_cream_makers_salt", start: 269.52, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_old_ice_cream_makers_salt.mp4" hue="blue" darken={0} /> },
  { key: "vt_ice_cream_maker_salt", start: 272.88, dur: 7.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_ice_cream_maker_salt.png" hue="amber" darken={0} /> },
  { key: "vt_salt_crystals_visible", start: 280.01, dur: 5.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_salt_crystals_visible.png" hue="red" darken={0} /> },
  { key: "vt_no_wasted_bottles", start: 285.16, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_no_wasted_bottles.mp4" hue="blue" darken={0} /> },
  { key: "vt_net_bag_bottles", start: 288.6, dur: 13.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_net_bag_bottles.png" hue="amber" darken={0} /> },
  { key: "vt_expansion_space_top", start: 302.18, dur: 8.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_expansion_space_top.png" hue="red" darken={0} /> },
  { key: "vt_fill_bottle_leave_air", start: 310.62, dur: 2.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_fill_bottle_leave_air.mp4" hue="blue" darken={0} /> },
  { key: "vt_add_salt_shake_bottle", start: 312.66, dur: 6.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_add_salt_shake_bottle.mp4" hue="amber" darken={0} /> },
  { key: "vt_water_expands_freezing", start: 318.39, dur: 9.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_water_expands_freezing.mp4" hue="red" darken={0} /> },
  { key: "vt_rotate_frozen_pairs", start: 327.24, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_rotate_frozen_pairs.mp4" hue="blue" darken={0} /> },
  { key: "vt_rope_tying_bottles_fan", start: 328.56, dur: 1.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_rope_tying_bottles_fan.png" hue="amber" darken={0} /> },
  { key: "vt_tray_under_bottles", start: 329.4, dur: 10.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_tray_under_bottles.mp4" hue="red" darken={0} /> },
  { key: "vt_tray_protects_floor", start: 340.06, dur: 1.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_tray_protects_floor.mp4" hue="blue" darken={0} /> },
  { key: "vt_fan_speed_medium_dial", start: 341.74, dur: 6.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_speed_medium_dial.png" hue="amber" darken={0} /> },
  { key: "vt_fan_near_bed_pointing", start: 347.52, dur: 2.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_near_bed_pointing.png" hue="red" darken={0} /> },
  { key: "vt_second_pair_freezing", start: 349.48, dur: 6.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_second_pair_freezing.png" hue="amber" darken={0} /> },
  { key: "vt_first_bottles_defrosting", start: 355.66, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_first_bottles_defrosting.png" hue="red" darken={0} /> },
  { key: "vt_swapping_bottles_night", start: 359.25, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_swapping_bottles_night.png" hue="blue" darken={0} /> },
  { key: "vt_next_day_new_bottles", start: 364.21, dur: 7.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_next_day_new_bottles.png" hue="amber" darken={0} /> },
  { key: "vt_old_office_ice_block", start: 370.97, dur: 8.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_old_office_ice_block.mp4" hue="red" darken={0} /> },
  { key: "vt_old_ice_block_1900", start: 379.63, dur: 9.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_old_ice_block_1900.png" hue="blue" darken={0} /> },
  { key: "vt_desert_wet_cloth_window", start: 388.4, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_desert_wet_cloth_window.mp4" hue="amber" darken={0} /> },
  { key: "vt_wet_sheet_window", start: 393.54, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_wet_sheet_window.png" hue="red" darken={0} /> },
  { key: "vt_bedouin_wet_sheet_memory", start: 397.1, dur: 6.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bedouin_wet_sheet_memory.png" hue="blue" darken={0} /> },
  { key: "vt_floor_mopping_wet", start: 403.52, dur: 8.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_floor_mopping_wet.png" hue="amber" darken={0} /> },
  { key: "vt_evaporation_cooling_physics", start: 411.58, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_evaporation_cooling_physics.png" hue="red" darken={0} /> },
  { key: "vt_air_conditioner_expensive_bill", start: 415.82, dur: 4.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/vt_air_conditioner_expensive_bill.mp4" hue="blue" darken={0} /> },
  { key: "vt_ac_compressor_heavy_load", start: 420.49, dur: 7.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_ac_compressor_heavy_load.png" hue="amber" darken={0} /> },
  { key: "vt_cost_comparison_visual", start: 427.4, dur: 16.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_cost_comparison_visual.png" hue="red" darken={0} /> },
  { key: "vt_fan_near_close_effective", start: 443.12, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_near_close_effective.png" hue="blue" darken={0} /> },
  { key: "vt_bedroom_cool_comfortable", start: 450.32, dur: 8.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bedroom_cool_comfortable.png" hue="amber" darken={0} /> },
  { key: "vt_money_save_visualization", start: 458.34, dur: 13.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_money_save_visualization.png" hue="amber" darken={0} /> },
  { key: "vt_fan_far_room_useless", start: 471.26, dur: 16.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_far_room_useless.png" hue="red" darken={0} /> },
  { key: "vt_personal_bubble_cooling", start: 487.95, dur: 8.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_personal_bubble_cooling.png" hue="blue" darken={0} /> },
  { key: "vt_summer_heat_index", start: 496.1, dur: 18.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_summer_heat_index.png" hue="amber" darken={0} /> },
  { key: "vt_three_strategies_together", start: 513.9, dur: 11.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_three_strategies_together.png" hue="blue" darken={0} /> },
  { key: "vt_wet_towel_front_fan", start: 525.02, dur: 15.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_wet_towel_front_fan.png" hue="amber" darken={0} /> },
  { key: "vt_damp_towel_evaporation", start: 539.78, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_damp_towel_evaporation.png" hue="red" darken={0} /> },
  { key: "vt_humidity_high_wet_air", start: 544.3, dur: 8.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_humidity_high_wet_air.png" hue="blue" darken={0} /> },
  { key: "vt_dry_climate_evaporation", start: 552.29, dur: 23.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_dry_climate_evaporation.png" hue="amber" darken={0} /> },
  { key: "vt_nighttime_window_open", start: 575.82, dur: 15.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_nighttime_window_open.png" hue="red" darken={0} /> },
  { key: "vt_fan_window_pushing_heat_out", start: 591.26, dur: 6.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_fan_window_pushing_heat_out.png" hue="blue" darken={0} /> },
  { key: "vt_second_window_opposite_side", start: 597.31, dur: 33.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_second_window_opposite_side.png" hue="amber" darken={0} /> },
  { key: "vt_morning_sun_on_window", start: 630.1, dur: 6.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_morning_sun_on_window.png" hue="red" darken={0} /> },
  { key: "vt_sun_heat_through_glass", start: 636.22, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_sun_heat_through_glass.png" hue="blue" darken={0} /> },
  { key: "vt_closed_blinds_afternoon", start: 641.74, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_closed_blinds_afternoon.png" hue="amber" darken={0} /> },
  { key: "vt_dark_curtains_day", start: 645.09, dur: 16.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_dark_curtains_day.png" hue="red" darken={0} /> },
  { key: "vt_bottle_feet_bed", start: 660.98, dur: 11.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bottle_feet_bed.png" hue="blue" darken={0} /> },
  { key: "vt_morning_sleep_quality", start: 672.22, dur: 15.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_morning_sleep_quality.png" hue="amber" darken={0} /> },
  { key: "vt_next_video_heating_teaser", start: 687.3, dur: 15.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_next_video_heating_teaser.png" hue="amber" darken={0} /> },
  { key: "vt_drip_tray_metal", start: 702.06, dur: 18.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_drip_tray_metal.png" hue="red" darken={0} /> },
  { key: "vt_bottle_burst_overfilled", start: 720.46, dur: 37.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_bottle_burst_overfilled.png" hue="blue" darken={0} /> },
  { key: "vt_subscribe_channel", start: 757.72, dur: 11.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_subscribe_channel.png" hue="red" darken={0} /> },
  { key: "vt_water_dripping_tray", start: 769.32, dur: 9.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_water_dripping_tray.png" hue="blue" darken={0} /> },
  { key: "vt_freedom_construction", start: 778.46, dur: 43.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vt_freedom_construction.png" hue="amber" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_eyebrowkicker_0", start: 0.11, dur: 3.2, kind: "eyebrowkicker", el: (d) => <EyebrowKicker {...({ durationInFrames: d, ...{"hue":"amber","eyebrow":"EL CONSTRUCTOR LIBRE","text":"Ventilador viejo → aire frío"} } as any)} /> },
  { key: "ov_frictioncard_8", start: 7.72, dur: 5.4, kind: "frictioncard", el: (d) => <FrictionCard {...({ durationInFrames: d, ...{"hue":"amber","title":"Atrapado entre los dos","leftImage":"vt_fan_blowing_warm_air.png","rightImage":"vt_electricity_meter_running.png","leftLabel":"Aire caliente en la cara","rightLabel":"Factura que te funde"} } as any)} /> },
  { key: "ov_secretsealcard_31", start: 30.88, dur: 5.2, kind: "secretsealcard", el: (d) => <SecretSealCard {...({ durationInFrames: d, ...{"hue":"amber","label":"POR CENTAVOS","sub":"con dos botellas"} } as any)} /> },
  { key: "ov_promisechecklist_57", start: 57.06, dur: 9, kind: "promisechecklist", el: (d) => <PromiseChecklist {...({ durationInFrames: d, ...{"hue":"amber","heading":"Hoy te paso el truco completo"} } as any)} /> },
  { key: "ov_fanfailproof_85", start: 84.6, dur: 6.9, kind: "fanfailproof", el: (d) => <FanFailProof {...({ durationInFrames: d, ...{"hue":"amber","title":"La pieza no baja ni un grado","tempLabel":"35°C → 35°C"} } as any)} /> },
  { key: "ov_evaporationphysics_100", start: 100.39, dur: 9.9, kind: "evaporationphysics", el: (d) => <EvaporationPhysics {...({ durationInFrames: d, ...{"hue":"amber","title":"El aire te evapora el sudor. Eso te saca calor."} } as any)} /> },
  { key: "ov_fanbottleassembly_141", start: 141.49, dur: 24.3, kind: "fanbottleassembly", el: (d) => <FanBottleAssembly {...({ durationInFrames: d, ...{"hue":"amber","title":"El aire pasa por el hielo antes de tirártelo"} } as any)} /> },
  { key: "ov_wrongvsrightplacement_187", start: 187.1, dur: 24.1, kind: "wrongvsrightplacement", el: (d) => <WrongVsRightPlacement {...({ durationInFrames: d, ...{"hue":"amber","title":"Nunca adelante. Siempre detrás."} } as any)} /> },
  { key: "ov_bottlesizegauge_214", start: 214.32, dur: 21.7, kind: "bottlesizegauge", el: (d) => <BottleSizeGauge {...({ durationInFrames: d, ...{"hue":"amber","title":"El tamaño importa"} } as any)} /> },
  { key: "ov_saltphysicsdiagram_250", start: 249.88, dur: 21.2, kind: "saltphysicsdiagram", el: (d) => <SaltPhysicsDiagram {...({ durationInFrames: d, ...{"hue":"amber","title":"El agua con sal se pone más fría y dura más"} } as any)} /> },
  { key: "ov_stepbystepbuild_302", start: 302.18, dur: 15.4, kind: "stepbystepbuild", el: (d) => <StepByStepBuild {...({ durationInFrames: d, ...{"hue":"amber","heading":"Se hace en 2 minutos"} } as any)} /> },
  { key: "ov_driptraycallout_333", start: 333.14, dur: 4.8, kind: "driptraycallout", el: (d) => <DripTrayCallout {...({ durationInFrames: d, ...{"hue":"amber","text":"Las botellas transpiran y gotean: poné una bandeja"} } as any)} /> },
  { key: "ov_rotationcyclediagram_353", start: 352.64, dur: 12.2, kind: "rotationcyclediagram", el: (d) => <RotationCycleDiagram {...({ durationInFrames: d, ...{"hue":"amber","title":"Rotando dos pares, frío toda la noche"} } as any)} /> },
  { key: "ov_oldtimersstamp_373", start: 373.14, dur: 24.7, kind: "oldtimersstamp", el: (d) => <OldTimersStamp {...({ durationInFrames: d, ...{"hue":"amber","heading":"Esto no lo inventó nadie ayer"} } as any)} /> },
  { key: "ov_mythbustercard_423", start: 423.06, dur: 6.3, kind: "mythbustercard", el: (d) => <MythBusterCard {...({ durationInFrames: d, ...{"hue":"amber","myth":"“Baja la pieza de 38 a 17 grados”","truth":"Enfría el aire que te da a vos, cerca"} } as any)} /> },
  { key: "ov_costvscard_467", start: 467.26, dur: 4, kind: "costvscard", el: (d) => <CostVsCard {...({ durationInFrames: d, ...{"hue":"amber","title":"Centavos contra una fortuna"} } as any)} /> },
  { key: "ov_distancelimitwarning_479", start: 478.82, dur: 12.5, kind: "distancelimitwarning", el: (d) => <DistanceLimitWarning {...({ durationInFrames: d, ...{"hue":"amber","title":"El error de 30 segundos"} } as any)} /> },
  { key: "ov_threelegsdiagram_534", start: 533.57, dur: 8.5, kind: "threelegsdiagram", el: (d) => <ThreeLegsDiagram {...({ durationInFrames: d, ...{"hue":"amber","title":"Las tres patas del verano"} } as any)} /> },
  { key: "ov_nightdaycycle_591", start: 591.26, dur: 9.2, kind: "nightdaycycle", el: (d) => <NightDayCycle {...({ durationInFrames: d, ...{"hue":"amber","title":"De noche afuera, de día todo cerrado"} } as any)} /> },
  { key: "ov_recapnumberedlist_687", start: 687.3, dur: 42.5, kind: "recapnumberedlist", el: (d) => <RecapNumberedList {...({ durationInFrames: d, ...{"hue":"amber","heading":"Repaso rápido"} } as any)} /> },
  { key: "ov_manualctacard_767", start: 767.02, dur: 15.4, kind: "manualctacard", el: (d) => <ManualCTACard {...({ durationInFrames: d, ...{"hue":"amber","heading":"El manual del constructor libre"} } as any)} /> },
  { key: "ov_nextvideoteaser_792", start: 791.58, dur: 12.5, kind: "nextvideoteaser", el: (d) => <NextVideoTeaser {...({ durationInFrames: d, ...{"hue":"amber","title":"El próximo: calentar sin gas"} } as any)} /> },
];
