// cues_hipos.gen.tsx — GENERADO por beatsheet.mjs desde hipos.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/hipos.json
import { ReactNode } from "react";
import { sec } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { AvatarPresentation } from "./scenes/AvatarPresentation";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { JourneyCanvas } from "./scenes/JourneyCanvas";

export type Cue = { key: string; start: number; dur: number; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "hip_c001", start: 0, dur: 4.75, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c001.mp4" hue="cold" kicker="Río Magdalena, Colombia" /> },
  { key: "i002", start: 4.75, dur: 3.6, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_hook.png" impact="MÁS DE 200" setup="Pablo Escobar trajo 4. Hoy son" impactAccent="danger" hitAt={1.1} boom={2} /> },
  { key: "hip_p003", start: 8.35, dur: 3.35, el: (d) => <RawShot durationInFrames={d} src="img/hip_p003.png" hue="amber" /> },
  { key: "hip_p004", start: 11.7, dur: 3.35, el: (d) => <RawShot durationInFrames={d} src="img/hip_p004.png" hue="cold" /> },
  { key: "hip_c005", start: 15.05, dur: 4.47, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c005.mp4" hue="red" kicker="Atacan pescadores" /> },
  { key: "hip_p006", start: 19.52, dur: 3.08, el: (d) => <RawShot durationInFrames={d} src="img/hip_p006.png" hue="red" kicker="Contaminan el agua" /> },
  { key: "i007", start: 22.6, dur: 3.4, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_kill80.png" impact="MATAR A 80" setup="Y el gobierno acaba de decidir" impactAccent="danger" hitAt={1} boom={1} /> },
  { key: "hip_p008", start: 26, dur: 3.35, el: (d) => <RawShot durationInFrames={d} src="img/hip_p008.png" hue="red" /> },
  { key: "hip_p009", start: 29.35, dur: 3.63, el: (d) => <RawShot durationInFrames={d} src="img/hip_p009.png" hue="cold" kicker="La peor invasión de Sudamérica" /> },
  { key: "hip_p010", start: 33, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p010.png" hue="cold" kicker="1.500 km de río" /> },
  { key: "hip_c011", start: 40, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c011.mp4" hue="cold" /> },
  { key: "hip_p012", start: 47, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p012.png" hue="cold" kicker="El 2º río más importante" /> },
  { key: "s013", start: 54, dur: 4, el: (d) => <StatBig durationInFrames={d} value={200} prefix="+" label="hipopótamos salvajes en Colombia" eyebrow="Hoy, en 2026" accent="danger" hue="red" /> },
  { key: "hip_p014", start: 58, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p014.png" hue="amber" kicker="Hacienda Nápoles" /> },
  { key: "hip_p015", start: 65, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p015.png" hue="amber" kicker="3.000 hectáreas" /> },
  { key: "hip_c016", start: 72, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c016.mp4" hue="cold" /> },
  { key: "hip_p017", start: 79, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p017.png" hue="cold" /> },
  { key: "hip_p018", start: 86, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p018.png" hue="amber" /> },
  { key: "hip_p019", start: 93, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p019.png" hue="amber" /> },
  { key: "hip_p020", start: 100, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p020.png" hue="amber" /> },
  { key: "hip_c021", start: 107, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c021.mp4" hue="cold" /> },
  { key: "hip_p022", start: 114, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p022.png" hue="amber" /> },
  { key: "hip_p023", start: 146, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p023.png" hue="amber" kicker="El Cadillac a balazos" /> },
  { key: "hip_p024", start: 153, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p024.png" hue="amber" /> },
  { key: "hip_p025", start: 160, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p025.png" hue="amber" /> },
  { key: "hip_p026", start: 167, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p026.png" hue="amber" /> },
  { key: "hip_c027", start: 174, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c027.mp4" hue="amber" kicker="Aviones que volvían de Miami" /> },
  { key: "hip_p028", start: 181, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p028.png" hue="amber" kicker="Iban llenos de droga al norte" /> },
  { key: "hip_p029", start: 188, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p029.png" hue="amber" kicker="Y volvían llenos de animales" /> },
  { key: "hip_p030", start: 195, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p030.png" hue="amber" /> },
  { key: "hip_p031", start: 202, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p031.png" hue="amber" /> },
  { key: "s032", start: 209, dur: 4, el: (d) => <StatBig durationInFrames={d} value={100000} prefix="$" label="costaba cada hipopótamo en los 80" eyebrow="Una fortuna" accent="amber" hue="amber" /> },
  { key: "hip_c033", start: 213, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c033.mp4" hue="cold" kicker="Un macho, tres hembras" /> },
  { key: "hip_p034", start: 220, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p034.png" hue="amber" /> },
  { key: "hip_p035", start: 227, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p035.png" hue="cold" /> },
  { key: "hip_p036", start: 234, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p036.png" hue="amber" kicker="Para él, una propina" /> },
  { key: "i037", start: 272, dur: 3.4, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_death.png" impact="ESCOBAR MUERE" setup="2 de diciembre de 1993" impactAccent="danger" hitAt={1} boom={2} /> },
  { key: "hip_p038", start: 275.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p038.png" hue="amber" /> },
  { key: "hip_p039", start: 282.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p039.png" hue="amber" kicker="Confiscada y abandonada" /> },
  { key: "hip_p040", start: 289.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p040.png" hue="amber" /> },
  { key: "hip_p041", start: 296.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p041.png" hue="amber" kicker="Saqueada por bandas" /> },
  { key: "hip_c042", start: 303.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c042.mp4" hue="amber" /> },
  { key: "hip_p043", start: 310.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p043.png" hue="amber" kicker="Las jirafas no sobrevivieron" /> },
  { key: "hip_p044", start: 317.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p044.png" hue="amber" /> },
  { key: "hip_p045", start: 324.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p045.png" hue="cold" kicker="Los hipopótamos: otro problema" /> },
  { key: "s046", start: 331.4, dur: 3.8, el: (d) => <StatBig durationInFrames={d} value={3000} suffix=" kg" label="pesa un hipopótamo adulto" eyebrow="Imposible de mover" accent="amber" hue="amber" /> },
  { key: "hip_p047", start: 335.2, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p047.png" hue="amber" /> },
  { key: "hip_p048", start: 342.2, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p048.png" hue="amber" kicker="Las cercas cediendo" /> },
  { key: "hip_c049", start: 349.2, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c049.mp4" hue="cold" kicker="Caminaron hacia afuera" /> },
  { key: "hip_p050", start: 356.2, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p050.png" hue="cold" /> },
  { key: "hip_p051", start: 363.2, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p051.png" hue="amber" kicker="Una erosión lenta" /> },
  { key: "hip_c052", start: 370.2, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c052.mp4" hue="cold" /> },
  { key: "hip_p053", start: 454, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p053.png" hue="cold" kicker="El paraíso del hipopótamo" /> },
  { key: "hip_c054", start: 461, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c054.mp4" hue="cold" /> },
  { key: "d055", start: 468, dur: 9, el: (d) => <AvatarPresentation durationInFrames={d} eyebrow="Por qué explotó la población" hue="cold" accent="accent" avatar="hipos_opt.mp4" avatarFrom={sec(468)} slides={[{"image":"img/hip_dg_55_1.png","title":"En África: freno natural"},{"image":"img/hip_dg_55_2.png","title":"En Colombia: sin frenos"}]} /> },
  { key: "hip_p056", start: 477, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p056.png" hue="cold" kicker="Crías cada año, no cada 3" /> },
  { key: "hip_p057", start: 484, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p057.png" hue="amber" /> },
  { key: "j058", start: 491, dur: 18, el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="La invasión, año por año" title="De 4 a más de 200" worldImage="img/hip_jy_river_world.png" accent="#B0503C" waypoints={[{"x":500,"y":820,"z":0.7,"image":"img/hip_jy_2007.png","label":"2007 · ~20","num":"1","dwell":2.6,"travel":1.6},{"x":1550,"y":480,"z":0.45,"image":"img/hip_jy_2014.png","label":"2014 · ~40","num":"2","dwell":2.6,"travel":1.8},{"x":2650,"y":1020,"z":0.8,"image":"img/hip_jy_2020.png","label":"2020 · ~90","num":"3","dwell":2.6,"travel":1.8},{"x":3750,"y":520,"z":0.5,"image":"img/hip_jy_2026.png","label":"2026 · +200","num":"4","dwell":3,"travel":1.8}]} /> },
  { key: "s059", start: 509, dur: 4, el: (d) => <StatBig durationInFrames={d} value={3} suffix=" años" label="edad reproductiva en Colombia (en África: 7-9)" eyebrow="La mitad del tiempo" accent="danger" hue="red" /> },
  { key: "hip_c060", start: 513, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c060.mp4" hue="cold" /> },
  { key: "hip_p061", start: 520, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p061.png" hue="amber" /> },
  { key: "hip_p062", start: 527, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p062.png" hue="amber" kicker="Nocturnos, difíciles de contar" /> },
  { key: "hip_p063", start: 534, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p063.png" hue="red" /> },
  { key: "i064", start: 541, dur: 3.8, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_proj7000.png" impact="SERÁN 7.000" setup="Si nadie hace nada, para 2050" impactAccent="danger" hitAt={1.1} boom={2} /> },
  { key: "hip_p065", start: 544.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p065.png" hue="cold" kicker="Colonización de toda la cuenca" /> },
  { key: "hip_c066", start: 698, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c066.mp4" hue="cold" kicker="Parecen inofensivos" /> },
  { key: "hip_c067", start: 705, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c067.mp4" hue="amber" /> },
  { key: "s068", start: 712, dur: 3.8, el: (d) => <StatBig durationInFrames={d} value={40} suffix=" kg" label="de vegetación come por noche, cada uno" eyebrow="Una máquina de procesar" accent="amber" hue="amber" /> },
  { key: "d069", start: 715.8, dur: 10, el: (d) => <AvatarPresentation durationInFrames={d} eyebrow="Cómo envenena el río" hue="red" accent="danger" avatar="hipos_opt.mp4" avatarFrom={sec(715.8)} slides={[{"image":"img/hip_dg_69_1.png","title":"1. Come en la orilla"},{"image":"img/hip_dg_69_2.png","title":"2. Devuelve todo al agua"},{"image":"img/hip_dg_69_3.png","title":"3. Algas y cero oxígeno"}]} /> },
  { key: "hip_p070", start: 725.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p070.png" hue="red" kicker="Florecen las algas" /> },
  { key: "hip_p071", start: 732.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p071.png" hue="red" /> },
  { key: "hip_c072", start: 739.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c072.mp4" hue="cold" /> },
  { key: "hip_p073", start: 746.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p073.png" hue="amber" kicker="Antes 30 kg, hoy 2" /> },
  { key: "hip_p074", start: 753.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p074.png" hue="cold" /> },
  { key: "hip_p075", start: 760.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p075.png" hue="amber" kicker="Pueblos que viven del río" /> },
  { key: "hip_p076", start: 767.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p076.png" hue="cold" kicker="El manatí, en peligro crítico" /> },
  { key: "hip_p077", start: 774.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p077.png" hue="cold" /> },
  { key: "hip_p078", start: 781.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p078.png" hue="cold" /> },
  { key: "hip_c079", start: 788.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c079.mp4" hue="amber" kicker="Orillas pisoteadas" /> },
  { key: "hip_p080", start: 795.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p080.png" hue="amber" /> },
  { key: "hip_p081", start: 802.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p081.png" hue="cold" kicker="Plantas que solo existen acá" /> },
  { key: "i082", start: 935, dur: 3.8, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_deaths500.png" impact="500 MUERTES AL AÑO" setup="En África matan más que los leones" impactAccent="danger" hitAt={1.1} boom={2} /> },
  { key: "hip_c083", start: 938.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c083.mp4" hue="red" kicker="30 km/h en tierra" /> },
  { key: "s084", start: 945.8, dur: 3.6, el: (d) => <StatBig durationInFrames={d} value={30} suffix=" km/h" label="alcanza un hipopótamo en tierra" eyebrow="Y son impredecibles" accent="danger" hue="red" /> },
  { key: "hip_p085", start: 949.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p085.png" hue="red" /> },
  { key: "hip_p086", start: 956.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p086.png" hue="cold" kicker="Cruzan la carretera" /> },
  { key: "hip_p087", start: 963.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p087.png" hue="red" /> },
  { key: "hip_c088", start: 970.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c088.mp4" hue="amber" /> },
  { key: "hip_p089", start: 977.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p089.png" hue="amber" /> },
  { key: "hip_p090", start: 984.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p090.png" hue="red" kicker="Chicos que salen corriendo" /> },
  { key: "hip_p091", start: 991.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p091.png" hue="amber" kicker="Doradal · Puerto Triunfo" /> },
  { key: "hip_p092", start: 998.4, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p092.png" hue="cold" kicker="Ya es parte de la vida diaria" /> },
  { key: "hip_p093", start: 1110, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p093.png" hue="cold" kicker="Atracción turística" /> },
  { key: "hip_p094", start: 1117, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p094.png" hue="cold" /> },
  { key: "hip_p095", start: 1124, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p095.png" hue="cold" kicker="Para ellos, vecinos" /> },
  { key: "hip_p096", start: 1131, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p096.png" hue="cold" /> },
  { key: "d097", start: 1138, dur: 10, el: (d) => <AvatarPresentation durationInFrames={d} eyebrow="Las soluciones que probaron" hue="cold" accent="cold" avatar="hipos_opt.mp4" avatarFrom={sec(1138)} slides={[{"image":"img/hip_dg_97_1.png","title":"Esterilizar"},{"image":"img/hip_dg_97_2.png","title":"Anticonceptivos por dardo"},{"image":"img/hip_dg_97_3.png","title":"Trasladar al exterior"}]} /> },
  { key: "hip_c098", start: 1148, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c098.mp4" hue="amber" kicker="$20.000 por esterilización" /> },
  { key: "hip_p099", start: 1155, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p099.png" hue="amber" /> },
  { key: "hip_p100", start: 1162, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p100.png" hue="amber" kicker="$200.000 por traslado" /> },
  { key: "hip_p101", start: 1169, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p101.png" hue="cold" /> },
  { key: "hip_p102", start: 1176, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p102.png" hue="amber" kicker="Mientras tanto, se reproducían" /> },
  { key: "hip_p103", start: 1280, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p103.png" hue="amber" kicker="2022: especie invasora" /> },
  { key: "hip_p104", start: 1287, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p104.png" hue="amber" /> },
  { key: "i105", start: 1294, dur: 3.6, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_plan2026.png" impact="UN PLAN DE CONTROL" setup="Y para 2026, lo inevitable" impactAccent="amber" hitAt={1} boom={1} /> },
  { key: "i106", start: 1321, dur: 3.8, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_euthan.png" impact="EUTANASIA DE 80" setup="Por primera vez, sin eufemismos" impactAccent="danger" hitAt={1} boom={2} /> },
  { key: "hip_p107", start: 1324.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p107.png" hue="cold" kicker="La reacción: feroz" /> },
  { key: "hip_p108", start: 1331.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p108.png" hue="cold" /> },
  { key: "hip_p109", start: 1338.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p109.png" hue="cold" /> },
  { key: "hip_p110", start: 1345.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p110.png" hue="cold" kicker="Cartas de todo el mundo" /> },
  { key: "hip_p111", start: 1352.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p111.png" hue="amber" /> },
  { key: "hip_p112", start: 1359.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p112.png" hue="amber" kicker="La ciencia: datos contundentes" /> },
  { key: "s113", start: 1366.8, dur: 4, el: (d) => <StatBig durationInFrames={d} value={1500} prefix="+" label="ejemplares en menos de 2 décadas si no se actúa" eyebrow="La proyección" accent="danger" hue="red" /> },
  { key: "hip_p114", start: 1370.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p114.png" hue="amber" kicker="Los pescadores: acción urgente" /> },
  { key: "hip_c115", start: 1377.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c115.mp4" hue="cold" kicker="Indiferentes al debate" /> },
  { key: "hip_p116", start: 1384.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p116.png" hue="cold" kicker="Se expanden hacia el norte" /> },
  { key: "hip_p117", start: 1391.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p117.png" hue="amber" /> },
  { key: "j118", start: 1398.8, dur: 16, el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="Cómo un capricho se volvió crisis" title="1981 → hoy" worldImage="img/hip_jy_time_world.png" accent="#A9794A" waypoints={[{"x":500,"y":800,"z":0.65,"image":"img/hip_jy_t_import.png","label":"1981 · Llegan 4","num":"1","dwell":2.4,"travel":1.5},{"x":1500,"y":500,"z":0.45,"image":"img/hip_jy_t_death.png","label":"1993 · Muere Escobar","num":"2","dwell":2.4,"travel":1.6},{"x":2550,"y":1000,"z":0.8,"image":"img/hip_jy_t_escape.png","label":"~2000 · Escapan","num":"3","dwell":2.4,"travel":1.6},{"x":3600,"y":540,"z":0.5,"image":"img/hip_jy_t_today.png","label":"2026 · +200","num":"4","dwell":2.8,"travel":1.6}]} /> },
  { key: "hip_p119", start: 1414.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p119.png" hue="cold" kicker="Hoy: un parque temático" /> },
  { key: "hip_p120", start: 1421.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p120.png" hue="amber" kicker="Su legado más resistente" /> },
  { key: "i121", start: 1428.8, dur: 4, el: (d) => <ImpactReveal durationInFrames={d} image="img/hip_im_legacy4.png" impact="CUATRO HIPOPÓTAMOS" setup="No fue su fortuna ni su cartel. Fueron" impactAccent="amber" hitAt={1.2} boom={0} /> },
  { key: "hip_c122", start: 1432.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c122.mp4" hue="cold" kicker="Y nace otra cría" /> },
  { key: "hip_p123", start: 1439.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p123.png" hue="cold" /> },
  { key: "hip_p124", start: 1446.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p124.png" hue="cold" kicker="Mientras los humanos discuten" /> },
  { key: "hip_c125", start: 1453.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="vid/hip_c125.mp4" hue="amber" kicker="La invasión se acelera" /> },
  { key: "hip_p126", start: 1460.8, dur: 7, el: (d) => <RawShot durationInFrames={d} src="img/hip_p126.png" hue="amber" kicker="Un final sin escribir" /> },
];

export const REFRAME: { start: number; end: number }[] = [];
