// cues_techo5.gen.tsx — GENERADO por beatsheet.mjs desde techo5.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/techo5.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { PremiumOverlay } from "./scenes/PremiumOverlay";
import { BigStatReveal, MythTruth, PullQuote, FramedPhoto, VsDuel, FloatingCutout, HighlightSweep, CtaCard, BulletCascade, FlowSteps, ChecklistReveal, NumberedSteps, SplitPanel, CutawayCallouts, BeforeAfter, DuelColumns, THEME_EARTH } from "./kit/premium";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "t5_s_001", start: 0.16, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_001.png" hue="amber" darken={0} /> },
  { key: "t5_s_001_b", start: 3.59, dur: 5.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_001_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_002", start: 8.44, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_002.png" hue="amber" darken={0} /> },
  { key: "t5_s_002_b", start: 11.36, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_002_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_003", start: 15.92, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_003.mp4" hue="amber" darken={0} clipDur={28.29} /> },
  { key: "t5_s_003_b", start: 18.71, dur: 4.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_003_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_004", start: 22.48, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_004.png" hue="amber" darken={0} /> },
  { key: "t5_s_004_b", start: 25.28, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_004_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_004_c", start: 28.18, dur: 2.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_004_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_005", start: 30.12, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_005.png" hue="amber" darken={0} /> },
  { key: "t5_s_005_b", start: 32.73, dur: 3.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_005_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_005_c", start: 35.7, dur: 2.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_005_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_006", start: 37.56, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_006.png" hue="amber" darken={0} /> },
  { key: "t5_s_006_b", start: 40.18, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_006_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_007", start: 44.32, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_007.png" hue="amber" darken={0} /> },
  { key: "t5_s_007_b", start: 47.07, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_007_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_007_c", start: 49.78, dur: 2.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_007_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_008", start: 52.35, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_008.mp4" hue="amber" darken={0} clipDur={22.96} /> },
  { key: "t5_s_008_b", start: 55.06, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_008_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_009", start: 58.56, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_009.png" hue="amber" darken={0} /> },
  { key: "t5_s_009_b", start: 61.84, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_009_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_010", start: 64.16, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_010.mp4" hue="amber" darken={0} clipDur={15.88} /> },
  { key: "t5_s_010_b", start: 67.02, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_010_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_010_c", start: 69.68, dur: 2.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_010_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_011", start: 71.99, dur: 3.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_011.png" hue="amber" darken={0} /> },
  { key: "t5_s_011_b", start: 74.84, dur: 4.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_011_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_012", start: 79.03, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_012.png" hue="amber" darken={0} /> },
  { key: "t5_s_012_b", start: 81.79, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_012_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_013", start: 85.2, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_013.png" hue="amber" darken={0} /> },
  { key: "t5_s_013_b", start: 87.98, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_013_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_014", start: 92.28, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_014.png" hue="amber" darken={0} /> },
  { key: "t5_s_014_b", start: 95.02, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_014_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_015", start: 97.96, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_015.png" hue="amber" darken={0} /> },
  { key: "t5_s_015_b", start: 100.61, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_015_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_016", start: 104.83, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_016.mp4" hue="amber" darken={0} clipDur={21.02} /> },
  { key: "t5_s_016_b", start: 107.61, dur: 4.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_016_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_017", start: 112.22, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_017.png" hue="amber" darken={0} /> },
  { key: "t5_s_017_b", start: 115.36, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_017_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_018", start: 118, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_018.png" hue="amber" darken={0} /> },
  { key: "t5_s_018_b", start: 120.83, dur: 2.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_018_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_019", start: 123.32, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_019.png" hue="amber" darken={0} /> },
  { key: "t5_s_019_b", start: 126.07, dur: 4.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_019_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_020", start: 130.16, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_020.mp4" hue="amber" darken={0} clipDur={14.3} /> },
  { key: "t5_s_020_b", start: 132.88, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_020_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_020_c", start: 135.54, dur: 2.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_020_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_021", start: 137.3, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_021.mp4" hue="amber" darken={0} clipDur={5.83} /> },
  { key: "t5_s_021_b", start: 139.99, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_021_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_021_c", start: 142.82, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_021_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_022", start: 145.94, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_022.mp4" hue="amber" darken={0} clipDur={7.34} /> },
  { key: "t5_s_022_b", start: 148.57, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_022_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_023", start: 151.88, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_023.mp4" hue="amber" darken={0} clipDur={32.16} /> },
  { key: "t5_s_023_b", start: 154.72, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_023_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_023_c", start: 157.7, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_023_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_024", start: 160.43, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_024.png" hue="amber" darken={0} /> },
  { key: "t5_s_024_b", start: 163.27, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_024_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_024_c", start: 165.94, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_024_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_025", start: 168.16, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_025.png" hue="amber" darken={0} /> },
  { key: "t5_s_025_b", start: 170.94, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_025_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_026", start: 174.86, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_026.mp4" hue="amber" darken={0} clipDur={12.03} /> },
  { key: "t5_s_026_b", start: 177.66, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_026_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_027", start: 181.88, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_027.mp4" hue="amber" darken={0} clipDur={15.93} /> },
  { key: "t5_s_027_b", start: 184.51, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_027_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_028", start: 187.64, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_028.mp4" hue="amber" darken={0} clipDur={13.96} /> },
  { key: "t5_s_028_b", start: 190.24, dur: 4.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_028_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_029", start: 194.23, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_029.png" hue="amber" darken={0} /> },
  { key: "t5_s_029_b", start: 197.04, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_029_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_030", start: 201.4, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_030.png" hue="amber" darken={0} /> },
  { key: "t5_s_030_b", start: 204.04, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_030_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_030_c", start: 206.8, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_030_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_031", start: 208.82, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_031.png" hue="amber" darken={0} /> },
  { key: "t5_s_031_b", start: 211.86, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_031_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_032", start: 215.71, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_032.png" hue="amber" darken={0} /> },
  { key: "t5_s_032_b", start: 218.44, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_032_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_032_c", start: 221.32, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_032_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_033", start: 223.02, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_033.png" hue="amber" darken={0} /> },
  { key: "t5_s_033_b", start: 226.03, dur: 3.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_033_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_034", start: 229, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_034.png" hue="amber" darken={0} /> },
  { key: "t5_s_034_b", start: 231.68, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_034_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_035", start: 235.85, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_035.png" hue="amber" darken={0} /> },
  { key: "t5_s_035_b", start: 238.55, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_035_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_035_c", start: 241.75, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_035_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_036", start: 244.62, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_036.png" hue="amber" darken={0} /> },
  { key: "t5_s_036_b", start: 247.6, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_036_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_037", start: 250.36, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_037.png" hue="amber" darken={0} /> },
  { key: "t5_s_037_b", start: 253.28, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_037_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_038", start: 257.28, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_038.png" hue="amber" darken={0} /> },
  { key: "t5_s_038_b", start: 260.15, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_038_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_039", start: 263.36, dur: 3.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_039.png" hue="amber" darken={0} /> },
  { key: "t5_s_039_b", start: 266.33, dur: 5.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_039_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_040", start: 271.08, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_040.png" hue="amber" darken={0} /> },
  { key: "t5_s_040_b", start: 274.04, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_040_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_040_c", start: 276.91, dur: 2.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_040_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_041", start: 278.88, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_041.png" hue="amber" darken={0} /> },
  { key: "t5_s_041_b", start: 281.95, dur: 3.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_041_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_041_c", start: 284.88, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_041_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_042", start: 286.96, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_042.png" hue="amber" darken={0} /> },
  { key: "t5_s_042_b", start: 289.76, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_042_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_042_c", start: 292.57, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_042_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_043", start: 294.36, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_043.png" hue="amber" darken={0} /> },
  { key: "t5_s_043_b", start: 297.04, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_043_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_043_c", start: 299.74, dur: 2.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_043_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_044", start: 301.46, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_044.png" hue="amber" darken={0} /> },
  { key: "t5_s_044_b", start: 304.23, dur: 2.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_044_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_045", start: 306.14, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_045.png" hue="amber" darken={0} /> },
  { key: "t5_s_045_b", start: 308.75, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_045_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_045_c", start: 311.37, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_045_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_046", start: 313.32, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_046.png" hue="amber" darken={0} /> },
  { key: "t5_s_046_b", start: 316.22, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_046_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_047", start: 319.36, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_047.png" hue="amber" darken={0} /> },
  { key: "t5_s_047_b", start: 322.09, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_047_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_047_c", start: 324.73, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_047_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_047_d", start: 327.46, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_047_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_048", start: 329.82, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_048.png" hue="amber" darken={0} /> },
  { key: "t5_s_048_b", start: 332.42, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_048_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_048_c", start: 335.18, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_048_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_048_d", start: 338.4, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_048_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_049", start: 340.38, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_049.png" hue="amber" darken={0} /> },
  { key: "t5_s_049_b", start: 343.08, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_049_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_050", start: 345.32, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_050.png" hue="amber" darken={0} /> },
  { key: "t5_s_050_b", start: 348.05, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_050_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_050_c", start: 350.77, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_050_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_051", start: 354.12, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_051.png" hue="amber" darken={0} /> },
  { key: "t5_s_051_b", start: 356.83, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_051_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_051_c", start: 359.5, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_051_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_051_d", start: 362.31, dur: 2.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_051_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_052", start: 364.66, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_052.png" hue="amber" darken={0} /> },
  { key: "t5_s_052_b", start: 367.49, dur: 2.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_052_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_053", start: 369.96, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_053.png" hue="amber" darken={0} /> },
  { key: "t5_s_053_b", start: 372.96, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_053_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_054", start: 374.96, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_054.png" hue="amber" darken={0} /> },
  { key: "t5_s_054_b", start: 377.78, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_054_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_054_c", start: 380.47, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_054_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_055", start: 382.26, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_055.png" hue="amber" darken={0} /> },
  { key: "t5_s_055_b", start: 384.89, dur: 4.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_055_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_056", start: 389.28, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_056.png" hue="amber" darken={0} /> },
  { key: "t5_s_056_b", start: 392.01, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_056_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_057", start: 395.81, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_057.png" hue="amber" darken={0} /> },
  { key: "t5_s_057_b", start: 398.61, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_057_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_057_c", start: 401.31, dur: 2.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_057_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_058", start: 403.76, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_058.png" hue="amber" darken={0} /> },
  { key: "t5_s_058_b", start: 406.48, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_058_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_059", start: 409.92, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_059.png" hue="amber" darken={0} /> },
  { key: "t5_s_059_b", start: 412.69, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_059_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_060", start: 414.48, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_060.mp4" hue="amber" darken={0} clipDur={21.23} /> },
  { key: "t5_s_060_b", start: 417.55, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_060_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_060_c", start: 420.34, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_060_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_061", start: 423.41, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_061.mp4" hue="amber" darken={0} clipDur={6.72} /> },
  { key: "t5_s_061_b", start: 426.24, dur: 4.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_061_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_062", start: 430.37, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_062.png" hue="amber" darken={0} /> },
  { key: "t5_s_062_b", start: 433.56, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_062_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_062_c", start: 436.25, dur: 2.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_062_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_063", start: 437.98, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_063.mp4" hue="amber" darken={0} clipDur={23.17} /> },
  { key: "t5_s_063_b", start: 440.63, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_063_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_064", start: 444.08, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_064.png" hue="amber" darken={0} /> },
  { key: "t5_s_064_b", start: 447.06, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_064_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_065", start: 450.24, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_065.mp4" hue="amber" darken={0} clipDur={5.08} /> },
  { key: "t5_s_065_b", start: 452.84, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_065_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_065_c", start: 455.83, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_065_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_065_d", start: 458.5, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_065_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_066", start: 462.32, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_066.mp4" hue="amber" darken={0} clipDur={12.56} /> },
  { key: "t5_s_067", start: 462.32, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_067.mp4" hue="amber" darken={0} clipDur={10} /> },
  { key: "t5_s_066_b", start: 465.07, dur: 2.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_066_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_068", start: 466.96, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_068.png" hue="amber" darken={0} /> },
  { key: "t5_s_068_b", start: 469.58, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_068_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_069", start: 473.32, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_069.png" hue="amber" darken={0} /> },
  { key: "t5_s_069_b", start: 476.01, dur: 4.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_069_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_070", start: 480.12, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_070.png" hue="amber" darken={0} /> },
  { key: "t5_s_070_b", start: 483.07, dur: 3.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_070_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_071", start: 486.04, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_071.png" hue="amber" darken={0} /> },
  { key: "t5_s_071_b", start: 488.93, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_071_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_072", start: 491.04, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_072.png" hue="amber" darken={0} /> },
  { key: "t5_s_072_b", start: 494.24, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_072_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_073", start: 497.84, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_073.png" hue="amber" darken={0} /> },
  { key: "t5_s_073_b", start: 500.72, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_073_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_074", start: 504.36, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_074.png" hue="amber" darken={0} /> },
  { key: "t5_s_074_b", start: 506.98, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_074_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_074_c", start: 509.69, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_074_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_075", start: 511.74, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_075.png" hue="amber" darken={0} /> },
  { key: "t5_s_075_b", start: 514.56, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_075_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_076", start: 517.56, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_076.mp4" hue="amber" darken={0} clipDur={12.12} /> },
  { key: "t5_s_076_b", start: 520.48, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_076_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_077", start: 523.04, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_077.mp4" hue="amber" darken={0} clipDur={17.08} /> },
  { key: "t5_s_077_b", start: 525.67, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_077_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_078", start: 529.08, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_078.mp4" hue="amber" darken={0} clipDur={60.46} /> },
  { key: "t5_s_078_b", start: 531.98, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_078_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_079", start: 536.22, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_079.mp4" hue="amber" darken={0} clipDur={15} /> },
  { key: "t5_s_079_b", start: 538.93, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_079_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_079_c", start: 541.66, dur: 2.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_079_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_080", start: 543.52, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_080.png" hue="amber" darken={0} /> },
  { key: "t5_s_080_b", start: 546.51, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_080_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_081", start: 549.72, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_081.png" hue="amber" darken={0} /> },
  { key: "t5_s_081_b", start: 552.33, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_081_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_081_c", start: 555.2, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_081_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_081_d", start: 558.1, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_081_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_082", start: 560.28, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_082.mp4" hue="amber" darken={0} clipDur={16.73} /> },
  { key: "t5_s_082_b", start: 562.9, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_082_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_082_c", start: 565.67, dur: 2.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_082_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_083", start: 567.4, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_083.png" hue="amber" darken={0} /> },
  { key: "t5_s_083_b", start: 570.12, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_083_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_084", start: 572.8, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_084.png" hue="amber" darken={0} /> },
  { key: "t5_s_084_b", start: 577.16, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_084_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_085", start: 579.44, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_085.mp4" hue="amber" darken={0} clipDur={12.51} /> },
  { key: "t5_s_085_b", start: 582.06, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_085_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_085_c", start: 584.77, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_085_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_086", start: 587.93, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_086.mp4" hue="amber" darken={0} clipDur={12.21} /> },
  { key: "t5_s_086_b", start: 590.84, dur: 4.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_086_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_087", start: 594.75, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_087.mp4" hue="amber" darken={0} clipDur={24.1} /> },
  { key: "t5_s_087_b", start: 597.44, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_087_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_088", start: 601.52, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_088.mp4" hue="amber" darken={0} clipDur={29.04} /> },
  { key: "t5_s_088_b", start: 604.33, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_088_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_088_c", start: 606.94, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_088_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_089", start: 609.14, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_089.mp4" hue="amber" darken={0} clipDur={19.49} /> },
  { key: "t5_s_089_b", start: 611.78, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_089_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_090", start: 615.98, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_090.mp4" hue="amber" darken={0} clipDur={39.04} /> },
  { key: "t5_s_090_b", start: 619.08, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_090_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_091", start: 623.36, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_091.mp4" hue="amber" darken={0} clipDur={8.34} /> },
  { key: "t5_s_091_b", start: 625.97, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_091_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_091_c", start: 628.87, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_091_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_092", start: 630.95, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_092.png" hue="amber" darken={0} /> },
  { key: "t5_s_092_b", start: 633.76, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_092_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_092_c", start: 636.77, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_092_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_092_d", start: 639.64, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_092_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_093", start: 641.38, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_093.mp4" hue="amber" darken={0} clipDur={27.5} /> },
  { key: "t5_s_093_b", start: 644.06, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_093_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_094", start: 648.08, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_094.mp4" hue="amber" darken={0} clipDur={9.08} /> },
  { key: "t5_s_094_b", start: 650.74, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_094_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_095", start: 654.68, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_095.mp4" hue="amber" darken={0} clipDur={34} /> },
  { key: "t5_s_095_b", start: 657.34, dur: 2.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_095_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_096", start: 659.28, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_096.png" hue="amber" darken={0} /> },
  { key: "t5_s_096_b", start: 661.89, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_096_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_096_c", start: 664.62, dur: 2.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_096_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_097", start: 667.01, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_097.png" hue="amber" darken={0} /> },
  { key: "t5_s_097_b", start: 669.84, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_097_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_098", start: 672.64, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_098.mp4" hue="amber" darken={0} clipDur={18.08} /> },
  { key: "t5_s_098_b", start: 675.56, dur: 4.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_098_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_099", start: 679.33, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_099.png" hue="amber" darken={0} /> },
  { key: "t5_s_099_b", start: 682.1, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_099_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_100", start: 685.76, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_100.mp4" hue="amber" darken={0} clipDur={19.56} /> },
  { key: "t5_s_100_b", start: 688.43, dur: 4.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_100_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_101", start: 692.32, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_101.png" hue="amber" darken={0} /> },
  { key: "t5_s_101_b", start: 695.09, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_101_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_101_c", start: 698.3, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_101_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_102", start: 700, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_102.mp4" hue="amber" darken={0} clipDur={15.02} /> },
  { key: "t5_s_102_b", start: 702.7, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_102_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_102_c", start: 705.3, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_102_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_103", start: 708.18, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_103.png" hue="amber" darken={0} /> },
  { key: "t5_s_103_b", start: 710.98, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_103_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_103_c", start: 713.73, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_103_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_104", start: 716.59, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_104.png" hue="amber" darken={0} /> },
  { key: "t5_s_104_b", start: 719.31, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_104_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_104_c", start: 722.71, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_104_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_105", start: 725.45, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_105.mp4" hue="amber" darken={0} clipDur={10.88} /> },
  { key: "t5_s_105_b", start: 728.17, dur: 4.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_105_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_106", start: 732.04, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_106.mp4" hue="amber" darken={0} clipDur={32.67} /> },
  { key: "t5_s_106_b", start: 734.81, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_106_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_107", start: 738.04, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_107.png" hue="amber" darken={0} /> },
  { key: "t5_s_107_b", start: 740.68, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_107_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_107_c", start: 743.58, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_107_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_108", start: 746.24, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_108.mp4" hue="amber" darken={0} clipDur={12.52} /> },
  { key: "t5_s_108_b", start: 749.08, dur: 4.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_108_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_109", start: 753.43, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_109.png" hue="amber" darken={0} /> },
  { key: "t5_s_109_b", start: 756.17, dur: 4.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_109_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_110", start: 760.06, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_110.mp4" hue="amber" darken={0} clipDur={5.94} /> },
  { key: "t5_s_110_b", start: 762.8, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_110_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_110_c", start: 765.56, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_110_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_110_d", start: 768.76, dur: 2.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_110_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_111", start: 770.68, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_111.png" hue="amber" darken={0} /> },
  { key: "t5_s_111_b", start: 773.68, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_111_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_112", start: 776.76, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_112.mp4" hue="amber" darken={0} clipDur={35.54} /> },
  { key: "t5_s_112_b", start: 779.46, dur: 4.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_112_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_113", start: 783.83, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_113.png" hue="amber" darken={0} /> },
  { key: "t5_s_113_b", start: 786.6, dur: 4.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_113_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_114", start: 791.08, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_114.png" hue="amber" darken={0} /> },
  { key: "t5_s_114_b", start: 793.68, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_114_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_115", start: 796.82, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_115.mp4" hue="amber" darken={0} clipDur={8.68} /> },
  { key: "t5_s_115_b", start: 799.47, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_115_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_116", start: 803.72, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_116.png" hue="amber" darken={0} /> },
  { key: "t5_s_116_b", start: 806.47, dur: 3.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_116_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_116_c", start: 809.52, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_116_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_117", start: 813.08, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_117.mp4" hue="amber" darken={0} clipDur={11.92} /> },
  { key: "t5_s_117_b", start: 815.81, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_117_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_118", start: 819.67, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_118.mp4" hue="amber" darken={0} clipDur={16.22} /> },
  { key: "t5_s_118_b", start: 822.37, dur: 4.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_118_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_119", start: 826.64, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_119.png" hue="amber" darken={0} /> },
  { key: "t5_s_119_b", start: 829.25, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_119_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_119_c", start: 831.93, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_119_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_120", start: 834.64, dur: 2.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_120.mp4" hue="amber" darken={0} clipDur={20.24} /> },
  { key: "t5_s_120_b", start: 837.33, dur: 4.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_120_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_121", start: 841.66, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_121.mp4" hue="amber" darken={0} clipDur={20.27} /> },
  { key: "t5_s_121_b", start: 844.41, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_121_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_122", start: 846.52, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_122.mp4" hue="amber" darken={0} clipDur={9.66} /> },
  { key: "t5_s_122_b", start: 849.24, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_122_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_123", start: 853.6, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_123.mp4" hue="amber" darken={0} clipDur={18.24} /> },
  { key: "t5_s_123_b", start: 856.47, dur: 2.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_123_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_124", start: 858.6, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_124.mp4" hue="amber" darken={0} clipDur={34.12} /> },
  { key: "t5_s_124_b", start: 861.24, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_124_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_125", start: 865.41, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_125.mp4" hue="amber" darken={0} clipDur={24.92} /> },
  { key: "t5_s_125_b", start: 868.04, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_125_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_126", start: 872.64, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_126.mp4" hue="amber" darken={0} clipDur={15} /> },
  { key: "t5_s_126_b", start: 875.42, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_126_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_127", start: 878.64, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_127.mp4" hue="amber" darken={0} clipDur={56.86} /> },
  { key: "t5_s_127_b", start: 881.5, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_127_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_127_c", start: 884.14, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_127_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_128", start: 886.35, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_128.mp4" hue="amber" darken={0} clipDur={30} /> },
  { key: "t5_s_128_b", start: 889.46, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_128_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_129", start: 892.4, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_129.png" hue="amber" darken={0} /> },
  { key: "t5_s_129_b", start: 895.23, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_129_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_130", start: 898.04, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_130.mp4" hue="amber" darken={0} clipDur={34.13} /> },
  { key: "t5_s_130_b", start: 900.69, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_130_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_131", start: 904.54, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_131.mp4" hue="amber" darken={0} clipDur={14.12} /> },
  { key: "t5_s_131_b", start: 907.4, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_131_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_132", start: 911.6, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_132.png" hue="amber" darken={0} /> },
  { key: "t5_s_132_b", start: 914.48, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_132_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_133", start: 917.12, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_133.png" hue="amber" darken={0} /> },
  { key: "t5_s_133_b", start: 919.89, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_133_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_133_c", start: 922.67, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_133_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_134", start: 925.45, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_134.png" hue="amber" darken={0} /> },
  { key: "t5_s_134_b", start: 928.2, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_134_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_134_c", start: 931.16, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_134_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_135", start: 935.44, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_135.png" hue="amber" darken={0} /> },
  { key: "t5_s_135_b", start: 938.39, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_135_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_135_c", start: 940.99, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_135_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_135_d", start: 943.81, dur: 2.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_135_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_136", start: 945.94, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_136.mp4" hue="amber" darken={0} clipDur={13.92} /> },
  { key: "t5_s_136_b", start: 948.55, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_136_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_136_c", start: 951.55, dur: 4.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_136_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_137", start: 956, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_137.mp4" hue="amber" darken={0} clipDur={6.24} /> },
  { key: "t5_s_137_b", start: 958.82, dur: 4.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_137_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_138", start: 962.57, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_138.png" hue="amber" darken={0} /> },
  { key: "t5_s_138_b", start: 965.49, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_138_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_138_c", start: 968.14, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_138_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_139", start: 972.28, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_139.mp4" hue="amber" darken={0} clipDur={37.1} /> },
  { key: "t5_s_139_b", start: 974.88, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_139_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_139_c", start: 977.68, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_139_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_140", start: 981.4, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_140.png" hue="amber" darken={0} /> },
  { key: "t5_s_140_b", start: 984.34, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_140_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_141", start: 988.66, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_141.mp4" hue="amber" darken={0} clipDur={10} /> },
  { key: "t5_s_141_b", start: 991.58, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_141_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_142", start: 994.64, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_142.mp4" hue="amber" darken={0} clipDur={17.05} /> },
  { key: "t5_s_142_b", start: 997.94, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_142_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_143", start: 1001.54, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_143.png" hue="amber" darken={0} /> },
  { key: "t5_s_143_b", start: 1004.32, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_143_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_144", start: 1007.05, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_144.png" hue="amber" darken={0} /> },
  { key: "t5_s_144_b", start: 1009.95, dur: 4.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_144_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_145", start: 1013.84, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_145.png" hue="amber" darken={0} /> },
  { key: "t5_s_145_b", start: 1016.68, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_145_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_145_c", start: 1019.54, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_145_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_146", start: 1022.4, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_146.png" hue="amber" darken={0} /> },
  { key: "t5_s_146_b", start: 1025.04, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_146_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_147", start: 1028.48, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_147.png" hue="amber" darken={0} /> },
  { key: "t5_s_147_b", start: 1031.08, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_147_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_148", start: 1033.86, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_148.png" hue="amber" darken={0} /> },
  { key: "t5_s_148_b", start: 1036.51, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_148_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_148_c", start: 1039.15, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_148_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_149", start: 1041.37, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_149.png" hue="amber" darken={0} /> },
  { key: "t5_s_149_b", start: 1044.09, dur: 4.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_149_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_150", start: 1048.08, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_150.png" hue="amber" darken={0} /> },
  { key: "t5_s_150_b", start: 1050.96, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_150_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_150_c", start: 1053.56, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_150_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_151", start: 1056.32, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_151.png" hue="amber" darken={0} /> },
  { key: "t5_s_151_b", start: 1059, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_151_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_151_c", start: 1061.62, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_151_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_152", start: 1063.52, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_152.png" hue="amber" darken={0} /> },
  { key: "t5_s_152_b", start: 1066.12, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_152_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_153", start: 1069.3, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_153.png" hue="amber" darken={0} /> },
  { key: "t5_s_153_b", start: 1072.34, dur: 2.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_153_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_154", start: 1074.4, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_154.mp4" hue="amber" darken={0} clipDur={14.81} /> },
  { key: "t5_s_154_b", start: 1077.01, dur: 3.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_154_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_155", start: 1079.76, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_155.png" hue="amber" darken={0} /> },
  { key: "t5_s_155_b", start: 1082.42, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_155_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_156", start: 1086.74, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_156.mp4" hue="amber" darken={0} clipDur={6.97} /> },
  { key: "t5_s_156_b", start: 1089.74, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_156_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_157", start: 1094.2, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_157.png" hue="amber" darken={0} /> },
  { key: "t5_s_157_b", start: 1096.92, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_157_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_157_c", start: 1099.72, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_157_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_157_d", start: 1102.45, dur: 2.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_157_d.png" hue="amber" darken={0} /> },
  { key: "t5_s_158", start: 1105, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_158.png" hue="amber" darken={0} /> },
  { key: "t5_s_158_b", start: 1107.63, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_158_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_158_c", start: 1110.43, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_158_c.png" hue="amber" darken={0} /> },
  { key: "t5_s_159", start: 1113.1, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/t5_s_159.mp4" hue="amber" darken={0} clipDur={5.2} /> },
  { key: "t5_s_159_b", start: 1116.02, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_159_b.png" hue="amber" darken={0} /> },
  { key: "t5_s_160", start: 1119.42, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_160.png" hue="amber" darken={0} /> },
  { key: "t5_s_160_b", start: 1122.46, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/t5_s_160_b.png" hue="amber" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_bigstatreveal_1", start: 0.99, dur: 5.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El líquido del que nadie quiere hablar","value":5,"prefix":"$","suffix":"","support":"cinco dólares que impermeabilizan un techo entero — por eso incomoda tanto"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_11", start: 10.68, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Si algo se prohíbe o desaparece, es porque era malo o peligroso","truth":"A veces se restringe porque funcionaba demasiado bien y arruinaba un negocio"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_28", start: 28.18, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Debajo de toda la propaganda, hay una verdad bastante incómoda."} as any)} /></PremiumOverlay> },
  { key: "ov_framedphoto_44", start: 44.32, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><FramedPhoto durationInFrames={d} theme={THEME_EARTH} {...({"image":"img/techo5_c1.png","caption":"Esa gota, a las tres de la mañana","sub":"el balde, el trapo, y el 'mañana lo arreglo'"} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_87", start: 86.53, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Dos caminos para el mismo techo","title":"Membrana cara vs. líquido negro","left":{"label":"Membrana premium","sub":"una fortuna, y a los 3-5 años se cuartea y se pela","good":false},"right":{"label":"El asfáltico de $5","sub":"una fracción del precio, sella parejo y aguanta","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_103", start: 103.48, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Lo que dura la membrana cara","value":3,"prefix":"","suffix":" años","support":"3, 4, 5 si tenés suerte — y volvés a foja cero: a comprar, a gastar"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_115", start: 115.36, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Es un negocio redondo. Redondo para ellos, no para vos."} as any)} /></PremiumOverlay> },
  { key: "ov_floatingcutout_142", start: 141.64, dur: 5.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><FloatingCutout durationInFrames={d} theme={THEME_EARTH} {...({"image":"img/techo5_c5.png","label":"El líquido negro","sub":"oscuro, espeso — sella lo que toca, mejor que cualquier plástico moderno"} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_152", start: 151.88, dur: 5.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"Estoy hablando del ","highlight":"alquitrán, la brea","post":" — ese material negro y pegajoso.","note":"sellaba lo que ningún plástico moderno"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_156", start: 155.92, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El material que sellaba de verdad","value":100,"prefix":"","suffix":" años","support":"alquitrán y brea: techos, barcos, cañerías, vías del tren — más de un siglo"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_188", start: 187.64, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Lo aplicabas una sola vez","value":20,"prefix":"","suffix":" años","support":"una sola aplicación, penetrando cada poro del hormigón — y costaba centavos"} as any)} /></PremiumOverlay> },
  { key: "ov_framedphoto_204", start: 203.92, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><FramedPhoto durationInFrames={d} theme={THEME_EARTH} {...({"image":"img/techo5_c4.png","caption":"Mi abuelo, en el techo del barrio","sub":"un tacho abollado, un cepillo, y todo el tiempo del mundo"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_226", start: 226.03, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Esto lo hago yo ahora, y lo va a arreglar tu nieto."} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_263", start: 263.36, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"El alquitrán desapareció solo, porque ya no servía para nada","truth":"Lo restringieron tanto, en tantos países, que para vos es como si estuviera prohibido"} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_325", start: 324.56, dur: 6.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El riesgo real, en perspectiva","title":"El obrero de fábrica vs. vos","left":{"label":"Obrero, 8 h/día, 30 años","sub":"vapores concentrados del coal tar, sin protección","good":false},"right":{"label":"Vos, un domingo al aire libre","sub":"una capa, con guantes, y no lo tocás nunca más","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_350", start: 349.57, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Un producto que dura 20 años y cuesta $5… es un pésimo negocio para el que te vende membrana nueva."} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_387", start: 386.76, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"40 arreglos de los que sabían los viejos","title":"Manual de Reparaciones Caseras","bullet":"tapar una gotera para siempre, con el material exacto y las cantidades","price":0,"cta":"LINK EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_434", start: 433.56, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La solución que SÍ conseguís hoy","title":"Alquitrán viejo vs. emulsión asfáltica","left":{"label":"Alquitrán de hulla","sub":"sellaba genial, pero vapores fuertes — restringido","good":false},"right":{"label":"Emulsión asfáltica","sub":"primo hermano, sella igual, sin el problema, baratísima","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_bulletcascade_455", start: 454.84, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BulletCascade durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Las tres que vas a ver en la ferretería","bullets":[{"pre":"La ","key":"emulsión","post":" — en agua, sin olor, la más amigable"},{"pre":"La ","key":"pintura o membrana","post":" — más espesa, da cuerpo"},{"pre":"La ","key":"masilla","post":" — pastosa, para grietas y detalles"}]} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_477", start: 477.04, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El mejor consejo de compra","title":"Etiqueta cara vs. bidón feo","left":{"label":"Marca cara importada","sub":"packaging divino y publicidad — cuesta el triple","good":false},"right":{"label":"Bidón sencillo","sub":"misma base asfáltica, sella igual, un tercio del precio","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_494", start: 494.24, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"El caro es mejor: por algo cuesta el triple","truth":"Le das vuelta a los dos y adentro es lo mismo: base asfáltica. Pagás la etiqueta, nada más"} as any)} /></PremiumOverlay> },
  { key: "ov_flowsteps_506", start: 505.84, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><FlowSteps durationInFrames={d} theme={THEME_EARTH} {...({"title":"Cómo se hace bien, de una","nodes":[{"label":"Limpiar","sub":"barrer, raspar, secar"},{"label":"Tratar grietas","sub":"masilla + banda"},{"label":"Dos manos finas","sub":"cruzadas, dejando secar"},{"label":"Sellar detalles","sub":"caños, encuentros, clavos"}]} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_519", start: 519.35, dur: 7.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Antes de tocar el asfáltico","items":["Barré cada hoja y piedrita","Sacá la membrana vieja floja","Raspá el musgo y el verdín","Que quede como un plato limpio"],"stamp":"LIMPIA Y SECA, SIN EXCUSAS"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_526", start: 525.55, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El error que se lo come todo","value":90,"prefix":"","suffix":"%","support":"aplicar sobre polvo o humedad: pegás el sellador a la mugre, no al techo"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_588", start: 587.93, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Le paso el sellador por encima a la grieta y listo","truth":"El techo se mueve, se dilata y se contrae, y te rompe la capa fina: por eso siempre vuelve"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_605", start: 605.48, dur: 6.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"La grieta, en orden","title":"Domar una grieta antes de sellar","steps":[{"title":"Rellená la grieta gruesa","sub":"con masilla asfáltica, no con el líquido fino"},{"title":"Poné una banda de refuerzo","sub":"malla o tela embebida, que haga de puente"},{"title":"Recién ahí, la mano general","sub":"con las grietas domadas, sellás todo encima"}]} as any)} /></PremiumOverlay> },
  { key: "ov_vsduel_655", start: 654.68, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><VsDuel durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El consejo que vale oro","title":"Una mano gruesa vs. dos finas","left":{"label":"Una mano gruesa","sub":"piel seca afuera, blanda adentro — se agrieta","good":false},"right":{"label":"Dos manos finas cruzadas","sub":"película pareja, sin poros ni puntos débiles","good":true}} as any)} /></PremiumOverlay> },
  { key: "ov_bulletcascade_705", start: 704.52, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BulletCascade durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Por donde entra el agua de verdad","bullets":[{"pre":"El ","key":"caño de ventilación","post":""},{"pre":"La ","key":"chimenea","post":" y la medianera"},{"pre":"Las ","key":"cabezas de clavos","post":" y tornillos"}]} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_746", start: 746.24, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"El agua parada es tu enemigo número uno. Busca, y busca, hasta que entra."} as any)} /></PremiumOverlay> },
  { key: "ov_splitpanel_791", start: 791.08, dur: 6.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><SplitPanel durationInFrames={d} theme={THEME_EARTH} {...({"image":"img/techo5_c3.png","eyebrow":"El momento del día importa","title":"Aplicá a la mañana temprano","bullets":["Mediodía: el sol reseca la capa por fuera","Tardecita: el rocío te arruina el secado","Mañana: techo seco y temperatura justa","Todo el día por delante para que cure"]} as any)} /></PremiumOverlay> },
  { key: "ov_cutawaycallouts_849", start: 848.52, dur: 6.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><CutawayCallouts durationInFrames={d} theme={THEME_EARTH} {...({"image":"img/techo5_c2.png","eyebrow":"Por qué la gotera engaña","title":"El agua camina antes de caer","callouts":[{"text":"Entra acá","sub":"una grieta cuesta arriba","tx":0.28,"ty":0.3,"side":"left"},{"text":"Camina por la viga","sub":"varios metros, escondida","tx":0.55,"ty":0.46,"side":"right"},{"text":"Cae acá","sub":"lejísimos de la entrada","tx":0.7,"ty":0.8,"side":"right"}]} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_859", start: 858.6, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"Sello el techo justo arriba de la mancha del cielorraso","truth":"La mancha casi nunca está bajo el agujero: la entrada está cuesta arriba"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_879", start: 878.64, dur: 5.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Buscá primero. Sellá después."} as any)} /></PremiumOverlay> },
  { key: "ov_framedphoto_889", start: 889.46, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="full" theme={THEME_EARTH}><FramedPhoto durationInFrames={d} theme={THEME_EARTH} {...({"image":"img/techo5_c6.png","caption":"El techo, sellado y tranquilo","sub":"te olvidás de él por muchísimos años"} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_901", start: 900.69, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Bien hecho, cuánto te dura","value":10,"prefix":"","suffix":" años","support":"una década tranquilo — y después no arrancás de cero, le pasás una mano de refresco"} as any)} /></PremiumOverlay> },
  { key: "ov_beforeafter_906", start: 905.88, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><BeforeAfter durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El mantenimiento, sin drama","beforeLabel":"A los años, apagado","afterLabel":"Una mano de refresco encima","caption":"renovás por otros tantos años, por una fracción del costo"} as any)} /></PremiumOverlay> },
  { key: "ov_duelcolumns_939", start: 939.38, dur: 6.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><DuelColumns durationInFrames={d} theme={THEME_EARTH} {...({"title":"Lo mismo pasa con todo","leftName":"Lo barato que funciona","rightName":"Lo caro que te venden","rows":[{"attr":"Madera: aceite de $2 (50 años) vs barniz que se pela","leftWins":true},{"attr":"Hierro: el óxido convertido en escudo vs antióxido caro","leftWins":true},{"attr":"Plagas: bórax por monedas vs fumigador","leftWins":true},{"attr":"Techo: asfáltico de $5 vs membrana premium","leftWins":true}]} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_987", start: 986.5, dur: 7.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"El Manual, en 4 módulos","items":["Madera y metal que no mueren","Plagas por centavos","Goteras, humedad y moho","Arreglos del hogar y el auto"],"stamp":"40 ARREGLOS EN TOTAL"} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_1026", start: 1026.06, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Los pocos números, el error del 90%, la regla de seguridad","title":"Manual del Constructor Libre","bullet":"40 arreglos probados, con medidas y pasos — para cuando los necesites","price":0,"cta":"PRIMER LINK DE LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
  { key: "ov_mythtruth_1038", start: 1037.53, dur: 6.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><MythTruth durationInFrames={d} theme={THEME_EARTH} {...({"myth":"La única forma de arreglar algo es comprando el producto caro, de marca","truth":"Preguntate cómo lo hacían antes: casi siempre, adentro del frasco caro hay lo mismo que en el barato"} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_1058", start: 1057.96, dur: 5.8, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"La información es lo que te libera. Dejás de ser cliente y pasás a ser el que resuelve."} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_1099", start: 1099.29, dur: 6.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Antes de que te vayas","title":"Dejá tu like y suscribite","bullet":"en el próximo video, otro secreto que la industria preferiría que no sepas","price":0,"cta":"ACTIVÁ LA CAMPANITA"} as any)} /></PremiumOverlay> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":0.99,"role":"popUp","vol":0.32},{"at":10.68,"role":"popUp","vol":0.32},{"at":28.18,"role":"popUp","vol":0.32},{"at":44.32,"role":"popUp","vol":0.32},{"at":86.53,"role":"popUp","vol":0.32},{"at":103.48,"role":"popUp","vol":0.32},{"at":115.36,"role":"popUp","vol":0.32},{"at":141.64,"role":"popUp","vol":0.32},{"at":151.88,"role":"popUp","vol":0.32},{"at":155.92,"role":"popUp","vol":0.32},{"at":187.64,"role":"popUp","vol":0.32},{"at":203.92,"role":"popUp","vol":0.32},{"at":226.03,"role":"popUp","vol":0.32},{"at":263.36,"role":"popUp","vol":0.32},{"at":324.56,"role":"popUp","vol":0.32},{"at":349.57,"role":"popUp","vol":0.32},{"at":386.76,"role":"popUp","vol":0.32},{"at":433.56,"role":"popUp","vol":0.32},{"at":454.84,"role":"popUp","vol":0.32},{"at":477.04,"role":"popUp","vol":0.32},{"at":494.24,"role":"popUp","vol":0.32},{"at":505.84,"role":"popUp","vol":0.32},{"at":519.35,"role":"popUp","vol":0.32},{"at":525.55,"role":"popUp","vol":0.32},{"at":587.93,"role":"popUp","vol":0.32},{"at":605.48,"role":"popUp","vol":0.32},{"at":654.68,"role":"popUp","vol":0.32},{"at":704.52,"role":"popUp","vol":0.32},{"at":746.24,"role":"popUp","vol":0.32},{"at":791.08,"role":"popUp","vol":0.32},{"at":848.52,"role":"popUp","vol":0.32},{"at":858.6,"role":"popUp","vol":0.32},{"at":878.64,"role":"popUp","vol":0.32},{"at":889.46,"role":"popUp","vol":0.32},{"at":900.69,"role":"popUp","vol":0.32},{"at":905.88,"role":"popUp","vol":0.32},{"at":939.38,"role":"popUp","vol":0.32},{"at":986.5,"role":"popUp","vol":0.32},{"at":1026.06,"role":"popUp","vol":0.32},{"at":1037.53,"role":"popUp","vol":0.32},{"at":1057.96,"role":"popUp","vol":0.32},{"at":1099.29,"role":"popUp","vol":0.32}];
