// cues_abono.gen.tsx — GENERADO por beatsheet.mjs desde abono.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/abono.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { MistakeCard } from "./scenes/MistakeCard";
import { LieList } from "./scenes/LieList";
import { NumberCard } from "./scenes/NumberCard";
import { GridReveal } from "./scenes/GridReveal";
import { GrowthTimeline } from "./scenes/GrowthTimeline";
import { KineticLine } from "./scenes/KineticLine";

const D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "b1_abono_hk_kitchen_scraps_bowl", start: 2.2, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_kitchen_scraps_bowl_1.jpg" darken={0} /> },
  { key: "b2_abono_hk_scraps_into_soil", start: 4.16, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_scraps_into_soil_2.jpg" darken={0} /> },
  { key: "b3_abono_hk_trash_bin_food", start: 8.5, dur: 1.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_trash_bin_food_2.jpg" darken={0} /> },
  { key: "b4_abono_hk_rich_black_soil", start: 9.82, dur: 1.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_rich_black_soil_1.jpg" darken={0} /> },
  { key: "b5_abono_hk_tomato_plant_thrive", start: 11.36, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_tomato_plant_thrive_1.jpg" darken={0} /> },
  { key: "b6_abono_hk_eggshells_crushed", start: 13.44, dur: 1.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_eggshells_crushed_1.jpg" darken={0} /> },
  { key: "b7_abono_hk_coffee_grounds_pour", start: 14.76, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_coffee_grounds_pour_1.jpg" darken={0} /> },
  { key: "cmp_hk_nosell", start: 16.56, dur: 1.56, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$0" eyebrow="Cero productos · cero vivero" caption="todo lo que tu tierra necesita ya lo tiras" accent="good" hue="amber" /> },
  { key: "cmp_hk_seven", start: 18.12, dur: 10.84, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="Las 7 basuras que alimentan tu huerta" chips={["Cáscara de huevo","Borra de café","Banana","Agua de cocción","Cebolla y ajo","Té","Recortes"]} hue="amber" /> },
  { key: "b13_abono_hk_compost_pile_turn", start: 28.96, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_compost_pile_turn_1.jpg" darken={0} /> },
  { key: "b14_abono_hk_hands_dirt_work", start: 30.92, dur: 1.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_hands_dirt_work_1.jpg" darken={0} /> },
  { key: "b15_abono_hk_veg_garden_wide", start: 32.36, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_veg_garden_wide_1.jpg" darken={0} /> },
  { key: "b16_abono_hk_seedling_sprout", start: 34.94, dur: 1.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_seedling_sprout_1.jpg" darken={0} /> },
  { key: "cmp_hk_trash", start: 36.48, dur: 5.32, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_hk_trash_bg.png" impact="lo estás tirando hoy." setup="Lo que el vivero te cobra..." impactAccent="danger" hitAt={1} boom={0} darken={0.45} /> },
  { key: "b20_abono_hk_tea_bag_used", start: 41.8, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_tea_bag_used_2.jpg" darken={0} /> },
  { key: "b21_abono_hk_amish_garden_morning", start: 43.4, dur: 1.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_amish_garden_morning_1.jpg" darken={0} /> },
  { key: "b22_abono_hk_grandfather_garden", start: 44.56, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_grandfather_garden_1.png" darken={0} /> },
  { key: "b23_abono_hk_trench_dig_garden", start: 48.6, dur: 7.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_trench_dig_garden_1.png" darken={0} /> },
  { key: "b24_abono_hk_bury_scraps_trench", start: 55.12, dur: 1.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_bury_scraps_trench_1.jpg" darken={0} /> },
  { key: "cmp_hk_tomato", start: 56.58, dur: 7.12, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🍅" eyebrow="La huerta del abuelo" caption="tomates del tamaño de tu puño — gratis" accent="good" hue="amber" /> },
  { key: "b26_abono_hk_hand_drop_eggshell", start: 63.7, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_hk_hand_drop_eggshell.png" darken={0} /> },
  { key: "b27_abono_hk_compost_handful2", start: 66.46, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_compost_handful2_1.jpg" darken={0} /> },
  { key: "b28_abono_hk_kitchen_chopping2", start: 68.9, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_kitchen_chopping2_1.jpg" darken={0} /> },
  { key: "b29_abono_hk_garden_rows2", start: 71.34, dur: 2.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_garden_rows2_1.png" darken={0} /> },
  { key: "cmp_loop", start: 73.32, dur: 6.64, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="4" title="El truco que casi nadie usa" desc="La mayoría ni sabe que sirve — y es el que más cambia tu tierra." eyebrow="EN ESTE VIDEO" image="img/cmp_loop_bg.png" /> },
  { key: "b32_abono_hk_trash_bin_food", start: 79.96, dur: 1.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_trash_bin_food_2.jpg" darken={0} /> },
  { key: "b33_abono_hk_rich_black_soil", start: 81.04, dur: 1.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_rich_black_soil_1.jpg" darken={0} /> },
  { key: "cmp_hk_secret", start: 82.26, dur: 8.76, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="★" title="El secreto de mi abuelo" desc="Una sola cosa que vale más que los 7 trucos juntos." eyebrow="AL FINAL DEL VIDEO" image="img/cmp_hk_secret_bg.png" /> },
  { key: "b37_abono_hk_banana_peel_soil", start: 91.02, dur: 1.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_banana_peel_soil_1.jpg" darken={0} /> },
  { key: "b38_abono_hk_worms_compost", start: 92.06, dur: 1.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_worms_compost_1.jpg" darken={0} /> },
  { key: "b39_abono_hk_watering_can_garden", start: 93.2, dur: 4.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_watering_can_garden_1.jpg" darken={0} /> },
  { key: "b40_abono_hk_garden_store_bag", start: 96.84, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_garden_store_bag_1.jpg" darken={0} /> },
  { key: "b41_abono_hk_money_wallet", start: 98.6, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_hk_money_wallet.png" darken={0} /> },
  { key: "b42_abono_hk_compost_pile_turn", start: 101.1, dur: 4.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_compost_pile_turn_1.jpg" darken={0} /> },
  { key: "b43_abono_hk_hands_dirt_work", start: 104.78, dur: 5.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_hk_hands_dirt_work_1.jpg" darken={0} /> },
  { key: "b44_abono_in_fertilizer_shelf", start: 110.2, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_fertilizer_shelf_1.jpg" darken={0} /> },
  { key: "b45_abono_in_price_tag_bag", start: 113.58, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_price_tag_bag_1.jpg" darken={0} /> },
  { key: "cmp_price", start: 117.96, dur: 6.74, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$$$" eyebrow="Una bolsa de abono" caption="lo que cuesta una semana de comida" accent="danger" hue="amber" /> },
  { key: "cmp_npk", start: 124.7, dur: 7.58, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} image="img/cmp_npk_bg.png" title="Lo único que hay en la bolsa" chips={["Calcio","Potasio","Nitrógeno"]} hue="amber" /> },
  { key: "b52_abono_in_banana_potassium", start: 132.28, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_banana_potassium_1.jpg" darken={0} /> },
  { key: "b53_abono_in_coffee_nitrogen", start: 135, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_coffee_nitrogen_1.jpg" darken={0} /> },
  { key: "b54_abono_in_grandfather_hands_soil", start: 138.6, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_grandfather_hands_soil_1.jpg" darken={0} /> },
  { key: "b55_abono_in_old_homestead_garden", start: 141.88, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_old_homestead_garden_1.jpg" darken={0} /> },
  { key: "b56_abono_in_horse_barn_manure", start: 144.9, dur: 2.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_horse_barn_manure_1.jpg" darken={0} /> },
  { key: "b57_abono_in_feeding_soil_handful", start: 146.6, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_feeding_soil_handful_1.jpg" darken={0} /> },
  { key: "cmp_in_label", start: 151.64, dur: 7.58, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🏷" eyebrow="De restos a producto" caption="etiqueta bonita y un precio — eso es todo" accent="danger" hue="amber" /> },
  { key: "cmp_quote_feed", start: 159.22, dur: 6.36, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_feed_bg.png" words={parseQuote("La tierra no se *compra* de comer. Se le *da* de comer.")} accent="amber" hue="amber" fontSize={84} /> },
  { key: "b63_abono_in_garden_gate_morning", start: 165.58, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_in_garden_gate_morning.png" darken={0} /> },
  { key: "b64_abono_in_store_aisle2", start: 168.4, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_store_aisle2_1.jpg" darken={0} /> },
  { key: "b65_abono_in_hand_soil_pour2", start: 170.12, dur: 2.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_hand_soil_pour2_2.jpg" darken={0} /> },
  { key: "b66_abono_in_compost_bin2", start: 171.82, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_compost_bin2_1.webp" darken={0} /> },
  { key: "b67_abono_in_fertilizer_shelf", start: 174.02, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_in_fertilizer_shelf_1.jpg" darken={0} /> },
  { key: "cmp_item_1", start: 175.78, dur: 3.7, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="1" name="Cáscara de Huevo" eyebrow="Calcio · anti-babosas" total="7" accent="amber" /> },
  { key: "b69_abono_eg_crack_egg", start: 179.48, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_crack_egg_1.jpg" darken={0} /> },
  { key: "b70_abono_eg_dry_shells_sun", start: 181.82, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_dry_shells_sun_1.jpg" darken={0} /> },
  { key: "b71_abono_eg_crush_mortar", start: 185.2, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_crush_mortar_1.jpg" darken={0} /> },
  { key: "b72_abono_eg_powder_close", start: 189.42, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_powder_close_2.jpg" darken={0} /> },
  { key: "b73_abono_eg_sprinkle_plant", start: 191.76, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_sprinkle_plant_2.png" darken={0} /> },
  { key: "cmp_anno_rot", start: 194.2, dur: 9.16, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_rot_bg.png" annotations={[{"kind":"circle","x":0.5,"y":0.7,"w":0.2,"label":"Mancha negra = sin calcio","color":"danger"},{"kind":"arrow","x":0.5,"y":0.4,"fromX":0.85,"fromY":0.15,"label":"No es un bicho","color":"amber"}]} eyebrow="Hambre de calcio" hue="amber" /> },
  { key: "b76_abono_eg_healthy_tomato_bottom", start: 203.36, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_healthy_tomato_bottom_1.jpg" darken={0} /> },
  { key: "b77_abono_eg_pepper_plant", start: 205.96, dur: 7.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_pepper_plant_1.jpg" darken={0} /> },
  { key: "b78_abono_eg_boot_crush_furrow", start: 213.4, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_boot_crush_furrow_1.jpg" darken={0} /> },
  { key: "b79_abono_eg_slug_leaf", start: 215.3, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_slug_leaf_1.jpg" darken={0} /> },
  { key: "b80_abono_eg_lettuce_seedling", start: 217.86, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_lettuce_seedling_1.jpg" darken={0} /> },
  { key: "b81_abono_eg_shell_ring_plant", start: 222.62, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_shell_ring_plant_2.jpg" darken={0} /> },
  { key: "cmp_proc_egg", start: 225.16, dur: 7.62, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Juntar y secar"},{"title":"Triturar bien fino"},{"title":"Al hoyo o alrededor del tallo"}]} eyebrow="Calcio para la tierra" title="La cáscara, paso a paso" accent="good" hue="amber" /> },
  { key: "b85_abono_eg_hands_full_shells", start: 232.78, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_hands_full_shells_1.jpg" darken={0} /> },
  { key: "b86_abono_eg_snail_close_macro", start: 236.02, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_snail_close_macro_1.jpg" darken={0} /> },
  { key: "b87_abono_eg_eggshell_grind2", start: 238.26, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_eggshell_grind2_1.jpg" darken={0} /> },
  { key: "b88_abono_eg_eggs_carton2", start: 241.38, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_eggs_carton2_1.jpg" darken={0} /> },
  { key: "b89_abono_eg_seedling_plant2", start: 245.42, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_seedling_plant2_1.jpg" darken={0} /> },
  { key: "b90_abono_eg_collect_jar", start: 249.5, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_collect_jar_1.jpg" darken={0} /> },
  { key: "b91_abono_eg_crack_egg", start: 251.62, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_crack_egg_1.jpg" darken={0} /> },
  { key: "b92_abono_eg_dry_shells_sun", start: 255.04, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_dry_shells_sun_1.jpg" darken={0} /> },
  { key: "b93_abono_eg_crush_mortar", start: 258, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_crush_mortar_1.jpg" darken={0} /> },
  { key: "b94_abono_eg_powder_close", start: 261.96, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_powder_close_2.jpg" darken={0} /> },
  { key: "cmp_bars_decomp", start: 265.56, dur: 9.42, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Polvo bien fino","value":100,"display":"semanas","winner":true},{"label":"Trozo grande","value":25,"display":"meses","tone":"danger"}]} eyebrow="Por eso se tritura" title="Cuánto tarda en comerlo la tierra" accent="good" hue="amber" /> },
  { key: "b98_abono_eg_healthy_tomato_bottom", start: 274.98, dur: 2.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_healthy_tomato_bottom_1.jpg" darken={0} /> },
  { key: "b99_abono_eg_pepper_plant", start: 276.8, dur: 4.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_pepper_plant_1.jpg" darken={0} /> },
  { key: "b100_abono_eg_boot_crush_furrow", start: 281.08, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_boot_crush_furrow_1.jpg" darken={0} /> },
  { key: "b101_abono_eg_slug_leaf", start: 284.88, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_slug_leaf_1.jpg" darken={0} /> },
  { key: "b102_abono_eg_lettuce_seedling", start: 289.04, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_lettuce_seedling_1.jpg" darken={0} /> },
  { key: "b103_abono_eg_shell_ring_plant", start: 292.12, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_shell_ring_plant_2.jpg" darken={0} /> },
  { key: "b104_abono_eg_bottle_smash", start: 294.74, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_bottle_smash_1.jpg" darken={0} /> },
  { key: "b105_abono_eg_water_in_shells", start: 297.36, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_eg_water_in_shells.png" darken={0} /> },
  { key: "b106_abono_eg_basket_eggs_farm", start: 300.4, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_basket_eggs_farm_2.jpg" darken={0} /> },
  { key: "b107_abono_eg_hands_full_shells", start: 302.74, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_hands_full_shells_1.jpg" darken={0} /> },
  { key: "b108_abono_eg_snail_close_macro", start: 304.84, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_snail_close_macro_1.jpg" darken={0} /> },
  { key: "b109_abono_eg_eggshell_grind2", start: 307.62, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_eggshell_grind2_1.jpg" darken={0} /> },
  { key: "b110_abono_eg_eggs_carton2", start: 309.6, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_eggs_carton2_1.jpg" darken={0} /> },
  { key: "cmp_eg_slug", start: 313.12, dur: 8.6, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="✂" eyebrow="Cáscara rota = cerca" caption="el filo frena a babosas y caracoles" accent="good" hue="amber" /> },
  { key: "b114_abono_eg_dry_shells_sun", start: 321.72, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_dry_shells_sun_1.jpg" darken={0} /> },
  { key: "b115_abono_eg_crush_mortar", start: 325.92, dur: 7.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_crush_mortar_1.jpg" darken={0} /> },
  { key: "b116_abono_eg_powder_close", start: 332.52, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_powder_close_2.jpg" darken={0} /> },
  { key: "cmp_eg_fence", start: 335.96, dur: 6.16, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="✂" eyebrow="Anillo de cáscara rota" caption="una cerca que te regaló el desayuno" accent="good" hue="amber" /> },
  { key: "b119_abono_eg_tomato_blossom_rot", start: 342.12, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_tomato_blossom_rot_1.jpg" darken={0} /> },
  { key: "b120_abono_eg_healthy_tomato_bottom", start: 345.2, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_healthy_tomato_bottom_1.jpg" darken={0} /> },
  { key: "b121_abono_eg_pepper_plant", start: 350.46, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_pepper_plant_1.jpg" darken={0} /> },
  { key: "b122_abono_eg_boot_crush_furrow", start: 353.44, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_eg_boot_crush_furrow_1.jpg" darken={0} /> },
  { key: "cmp_item_2", start: 356.06, dur: 4.9, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="2" name="Borra de Café" eyebrow="Nitrógeno · lombrices" total="7" accent="amber" /> },
  { key: "b125_abono_cf_grounds_macro", start: 360.96, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_grounds_macro_1.jpg" darken={0} /> },
  { key: "b126_abono_cf_sprinkle_thin_soil", start: 364.5, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_sprinkle_thin_soil_1.jpg" darken={0} /> },
  { key: "b127_abono_cf_rake_into_soil", start: 367.96, dur: 4.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_rake_into_soil_1.jpg" darken={0} /> },
  { key: "b128_abono_cf_clumped_mold", start: 372.08, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_clumped_mold_2.jpg" darken={0} /> },
  { key: "b129_abono_cf_leafy_greens_green", start: 375.34, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_leafy_greens_green_1.jpg" darken={0} /> },
  { key: "b130_abono_cf_pale_yellow_leaf", start: 378.32, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_pale_yellow_leaf_1.jpg" darken={0} /> },
  { key: "b131_abono_cf_worms_in_grounds", start: 380.74, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worms_in_grounds_1.jpg" darken={0} /> },
  { key: "b132_abono_cf_worm_tunnels", start: 382.74, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worm_tunnels_2.png" darken={0} /> },
  { key: "b133_abono_cf_worm_castings", start: 386.18, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worm_castings_1.jpg" darken={0} /> },
  { key: "b134_abono_cf_bucket_lid_barn", start: 389.84, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_cf_bucket_lid_barn.png" darken={0} /> },
  { key: "b135_abono_cf_winter_storage", start: 391.74, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_cf_winter_storage.png" darken={0} /> },
  { key: "b136_abono_cf_scatter_like_seed", start: 394.4, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_scatter_like_seed_1.jpg" darken={0} /> },
  { key: "b137_abono_cf_coffee_cup_morning", start: 396.74, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_coffee_cup_morning_1.jpg" darken={0} /> },
  { key: "b138_abono_cf_spoon_grounds_plant", start: 399.54, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_spoon_grounds_plant_1.jpg" darken={0} /> },
  { key: "b139_abono_cf_compost_add_grounds", start: 402.28, dur: 2.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_compost_add_grounds_1.jpg" darken={0} /> },
  { key: "b140_abono_cf_earthworm_macro", start: 404.1, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_earthworm_macro_1.jpg" darken={0} /> },
  { key: "b141_abono_cf_night_garden", start: 406.16, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_night_garden_1.jpg" darken={0} /> },
  { key: "b142_abono_cf_pour_grounds2", start: 409.2, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_pour_grounds2_1.jpg" darken={0} /> },
  { key: "b143_abono_cf_espresso_puck2", start: 412.54, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_espresso_puck2_1.png" darken={0} /> },
  { key: "cmp_coffee_err", start: 414.86, dur: 7.94, kind: "lielist", el: (d) => <LieList durationInFrames={d} title="Por qué la gente lo arruina" items={["La echan fresca y en montón","Se apelmaza y cría moho","Le tapa el aire a la raíz"]} image="img/cmp_coffee_err_bg.png" accent="danger" /> },
  { key: "cmp_proc_coffee", start: 422.8, dur: 9.22, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Capa fina, no en montón"},{"title":"Rascar con el primer dedo de tierra"},{"title":"Una vez por semana"}]} eyebrow="Sin apelmazar" title="La borra, bien puesta" accent="good" hue="amber" /> },
  { key: "b150_abono_cf_clumped_mold", start: 432.02, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_clumped_mold_2.jpg" darken={0} /> },
  { key: "b151_abono_cf_leafy_greens_green", start: 436.86, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_leafy_greens_green_1.jpg" darken={0} /> },
  { key: "b152_abono_cf_pale_yellow_leaf", start: 439.84, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_pale_yellow_leaf_1.jpg" darken={0} /> },
  { key: "b153_abono_cf_worms_in_grounds", start: 442.86, dur: 2.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worms_in_grounds_1.jpg" darken={0} /> },
  { key: "b154_abono_cf_worm_tunnels", start: 444.72, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worm_tunnels_2.png" darken={0} /> },
  { key: "b155_abono_cf_worm_castings", start: 446.76, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worm_castings_1.jpg" darken={0} /> },
  { key: "b156_abono_cf_bucket_lid_barn", start: 448.82, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_cf_bucket_lid_barn.png" darken={0} /> },
  { key: "b157_abono_cf_winter_storage", start: 452.1, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_cf_winter_storage.png" darken={0} /> },
  { key: "b158_abono_cf_scatter_like_seed", start: 454.38, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_scatter_like_seed_1.jpg" darken={0} /> },
  { key: "cmp_worm", start: 456.38, dur: 7.38, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🪱" eyebrow="El verdadero secreto del café" caption="no alimenta la planta — contrata lombrices, gratis" accent="good" hue="amber" /> },
  { key: "b161_abono_cf_compost_add_grounds", start: 463.76, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_compost_add_grounds_1.jpg" darken={0} /> },
  { key: "cmp_cf_best", start: 465.84, dur: 3.2, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="★" eyebrow="Caca de lombriz" caption="el mejor abono que existe — y no se compra" accent="good" hue="amber" /> },
  { key: "cmp_anno_worm", start: 469.04, dur: 13.6, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_worm_bg.png" annotations={[{"kind":"arrow","x":0.45,"y":0.5,"fromX":0.8,"fromY":0.2,"label":"Túneles = aire a la raíz","color":"good"},{"kind":"circle","x":0.35,"y":0.6,"w":0.18,"label":"Humus de lombriz","color":"good"}]} eyebrow="El trabajo invisible" hue="amber" /> },
  { key: "b165_abono_cf_espresso_puck2", start: 482.64, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_espresso_puck2_1.png" darken={0} /> },
  { key: "b166_abono_cf_worm_soil2", start: 486.84, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worm_soil2_2.jpg" darken={0} /> },
  { key: "cmp_cf_night", start: 489.36, dur: 9.2, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🌙" eyebrow="Lombrices contratadas" caption="trabajan de noche, mientras dormís — gratis" accent="good" hue="amber" /> },
  { key: "b169_abono_cf_grounds_macro", start: 498.56, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_grounds_macro_1.jpg" darken={0} /> },
  { key: "b170_abono_cf_sprinkle_thin_soil", start: 500.6, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_sprinkle_thin_soil_1.jpg" darken={0} /> },
  { key: "b171_abono_cf_rake_into_soil", start: 502.9, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_rake_into_soil_1.jpg" darken={0} /> },
  { key: "b172_abono_cf_clumped_mold", start: 505.3, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_clumped_mold_2.jpg" darken={0} /> },
  { key: "b173_abono_cf_leafy_greens_green", start: 509.32, dur: 4.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_leafy_greens_green_1.jpg" darken={0} /> },
  { key: "b174_abono_cf_pale_yellow_leaf", start: 513.16, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_pale_yellow_leaf_1.jpg" darken={0} /> },
  { key: "b175_abono_cf_worms_in_grounds", start: 515.42, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worms_in_grounds_1.jpg" darken={0} /> },
  { key: "b176_abono_cf_worm_tunnels", start: 518.16, dur: 10.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cf_worm_tunnels_2.png" darken={0} /> },
  { key: "cmp_item_3", start: 527.76, dur: 4.12, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="3" name="Cáscara de Banana" eyebrow="Potasio · flor y fruto" total="7" accent="amber" /> },
  { key: "b178_abono_bn_peel_macro", start: 531.88, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_peel_macro_1.jpg" darken={0} /> },
  { key: "b179_abono_bn_cut_peel_scissors", start: 534.18, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_cut_peel_scissors_1.jpg" darken={0} /> },
  { key: "b180_abono_bn_bury_peel_soil", start: 537.88, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_bury_peel_soil_1.jpg" darken={0} /> },
  { key: "cmp_potasio", start: 541.66, dur: 6.18, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="K" eyebrow="Potasio" caption="empuja la flor a volverse fruto" accent="good" hue="amber" /> },
  { key: "b182_abono_bn_pepper_blossom", start: 547.84, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_pepper_blossom_1.png" darken={0} /> },
  { key: "b183_abono_bn_cucumber_flower", start: 549.82, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_cucumber_flower_1.jpg" darken={0} /> },
  { key: "b184_abono_bn_peels_jar_water", start: 551.86, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_peels_jar_water_1.jpg" darken={0} /> },
  { key: "b185_abono_bn_dark_tea_water", start: 556, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_dark_tea_water_2.jpg" darken={0} /> },
  { key: "b186_abono_bn_water_plant_tea", start: 558.28, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_water_plant_tea_1.jpg" darken={0} /> },
  { key: "b187_abono_bn_flowers_to_fruit", start: 560.36, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_flowers_to_fruit_1.jpg" darken={0} /> },
  { key: "cmp_banana_two", start: 562.48, dur: 2.18, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Dos maneras, mismo potasio" items={["Enterrada: se deshace en 2-3 semanas","En té: 3 días en agua, rebajado","Regla: enterrada o tapada, NUNCA al aire"]} accent={D} /> },
  { key: "cmp_bn_crops", start: 564.66, dur: 12.76, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} title="Piden potasio cuando florecen" chips={["Tomate","Pimiento","Pepino","Zapallo"]} hue="amber" /> },
  { key: "b191_abono_bn_ripe_bananas_bunch", start: 577.42, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_ripe_bananas_bunch_1.jpg" darken={0} /> },
  { key: "b192_abono_bn_potted_plant_balcony", start: 579.98, dur: 12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_potted_plant_balcony_1.jpg" darken={0} /> },
  { key: "b193_abono_bn_jar_shade_lid", start: 591.48, dur: 8.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_jar_shade_lid_1.jpg" darken={0} /> },
  { key: "b194_abono_bn_green_tomatoes_vine", start: 599.16, dur: 2.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_green_tomatoes_vine_1.jpg" darken={0} /> },
  { key: "cmp_bn_buried", start: 601.1, dur: 10.72, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🌱" eyebrow="Enterrada" caption="sin olor, sin moscas — trabaja en secreto" accent="good" hue="amber" /> },
  { key: "cmp_proc_banana", start: 611.82, dur: 7.92, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"2-3 cáscaras en un frasco con agua"},{"title":"3 días tapado a la sombra"},{"title":"Colar y rebajar a la mitad"}]} eyebrow="Para macetas con flor" title="El té de banana" accent="good" hue="amber" /> },
  { key: "b200_abono_bn_peel_macro", start: 619.74, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_peel_macro_1.jpg" darken={0} /> },
  { key: "b201_abono_bn_cut_peel_scissors", start: 623.32, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_cut_peel_scissors_1.jpg" darken={0} /> },
  { key: "b202_abono_bn_bury_peel_soil", start: 626.2, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_bury_peel_soil_1.jpg" darken={0} /> },
  { key: "b203_abono_bn_tomato_flower", start: 628.64, dur: 4.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_tomato_flower_1.jpg" darken={0} /> },
  { key: "b204_abono_bn_pepper_blossom", start: 632.92, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_pepper_blossom_1.png" darken={0} /> },
  { key: "b205_abono_bn_cucumber_flower", start: 635.76, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_cucumber_flower_1.jpg" darken={0} /> },
  { key: "b206_abono_bn_peels_jar_water", start: 638.84, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_peels_jar_water_1.jpg" darken={0} /> },
  { key: "b207_abono_bn_dark_tea_water", start: 642.06, dur: 4.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_dark_tea_water_2.jpg" darken={0} /> },
  { key: "b208_abono_bn_water_plant_tea", start: 645.74, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_water_plant_tea_1.jpg" darken={0} /> },
  { key: "b209_abono_bn_flowers_to_fruit", start: 650.36, dur: 5.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_flowers_to_fruit_1.jpg" darken={0} /> },
  { key: "b210_abono_bn_fruit_flies_warning", start: 655.06, dur: 5.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_fruit_flies_warning_1.webp" darken={0} /> },
  { key: "b211_abono_bn_peel_on_soil_bad", start: 659.7, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_peel_on_soil_bad_1.jpg" darken={0} /> },
  { key: "b212_abono_bn_spade_dig_side", start: 664.64, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_spade_dig_side_1.jpg" darken={0} /> },
  { key: "b213_abono_bn_ripe_bananas_bunch", start: 668.04, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_ripe_bananas_bunch_1.jpg" darken={0} /> },
  { key: "b214_abono_bn_potted_plant_balcony", start: 670.64, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_potted_plant_balcony_1.jpg" darken={0} /> },
  { key: "b215_abono_bn_jar_shade_lid", start: 672.52, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_jar_shade_lid_1.jpg" darken={0} /> },
  { key: "b216_abono_bn_green_tomatoes_vine", start: 674.82, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_green_tomatoes_vine_1.jpg" darken={0} /> },
  { key: "b217_abono_bn_hand_mix_water", start: 677, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_hand_mix_water_2.jpg" darken={0} /> },
  { key: "b218_abono_bn_chop_peel2", start: 679.48, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_chop_peel2_1.jpg" darken={0} /> },
  { key: "b219_abono_bn_jar_steep2", start: 683.86, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_jar_steep2_1.jpg" darken={0} /> },
  { key: "b220_abono_bn_flower_macro2", start: 688, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_flower_macro2_1.jpg" darken={0} /> },
  { key: "b221_abono_bn_peel_banana", start: 690.14, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_peel_banana_1.jpg" darken={0} /> },
  { key: "b222_abono_bn_peel_macro", start: 694.36, dur: 9.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_peel_macro_1.jpg" darken={0} /> },
  { key: "b223_abono_bn_cut_peel_scissors", start: 703.1, dur: 4.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_bn_cut_peel_scissors_1.jpg" darken={0} /> },
  { key: "cmp_item_4", start: 707.38, dur: 3.34, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="4" name="Agua de Cocción" eyebrow="El caldo invisible" total="7" accent="amber" /> },
  { key: "b225_abono_wt_colored_water", start: 710.72, dur: 9.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_wt_colored_water.png" darken={0} /> },
  { key: "b226_abono_wt_drain_colander", start: 719.88, dur: 6.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_drain_colander_1.jpg" darken={0} /> },
  { key: "b227_abono_wt_pour_down_drain", start: 725.92, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_wt_pour_down_drain.png" darken={0} /> },
  { key: "b228_abono_wt_save_water_jug", start: 728.36, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_save_water_jug_1.png" darken={0} /> },
  { key: "b229_abono_wt_cool_water_counter", start: 730.54, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_wt_cool_water_counter.png" darken={0} /> },
  { key: "b230_abono_wt_water_potted_plant", start: 733.24, dur: 7.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_water_potted_plant_1.jpg" darken={0} /> },
  { key: "b231_abono_wt_salt_shaker", start: 740.56, dur: 2.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_wt_salt_shaker.png" darken={0} /> },
  { key: "b232_abono_wt_yellowing_houseplant", start: 742.5, dur: 4.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_yellowing_houseplant_1.jpg" darken={0} /> },
  { key: "b233_abono_wt_green_houseplant", start: 746.96, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_green_houseplant_1.jpg" darken={0} /> },
  { key: "b234_abono_wt_broccoli_pot", start: 749.62, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_broccoli_pot_1.jpg" darken={0} /> },
  { key: "b235_abono_wt_carrot_pot", start: 753.24, dur: 7.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_carrot_pot_1.jpg" darken={0} /> },
  { key: "cmp_wt_hot", start: 760.18, dur: 2.4, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🔥" eyebrow="El error que mata la planta" caption="tibia no — FRÍA del todo" accent="danger" hue="amber" /> },
  { key: "cmp_gold_water", start: 762.58, dur: 4.83, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_gold_water_bg.png" impact="Es un caldo de nutrientes." setup="¿Tiras el agua de hervir verduras?" impactAccent="good" hitAt={1.1} boom={0} darken={0.45} /> },
  { key: "cmp_wt_waste", start: 767.41, dur: 11.13, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="💧" eyebrow="Lo que tiras cada día" caption="años de nutrientes directo a la cañería" accent="danger" hue="amber" /> },
  { key: "cmp_proc_water", start: 778.54, dur: 9.74, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Que enfríe del todo"},{"title":"Sin sal (la sal mata la tierra)"},{"title":"Regar como agua normal"}]} eyebrow="Gratis dos veces" title="El agua de cocción, sin error" accent="good" hue="amber" /> },
  { key: "b244_abono_wt_pour_plant2", start: 788.28, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_pour_plant2_1.jpg" darken={0} /> },
  { key: "b245_abono_wt_green_leaves2", start: 792.78, dur: 9.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_green_leaves2_1.jpg" darken={0} /> },
  { key: "b246_abono_wt_boil_vegetables", start: 801.52, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_boil_vegetables_1.webp" darken={0} /> },
  { key: "b247_abono_wt_colored_water", start: 803.92, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_wt_colored_water.png" darken={0} /> },
  { key: "b248_abono_wt_drain_colander", start: 806.06, dur: 6.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_drain_colander_1.jpg" darken={0} /> },
  { key: "b249_abono_wt_pour_down_drain", start: 812, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_wt_pour_down_drain.png" darken={0} /> },
  { key: "b250_abono_wt_save_water_jug", start: 815.88, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_save_water_jug_1.png" darken={0} /> },
  { key: "b251_abono_wt_cool_water_counter", start: 819.34, dur: 7.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_wt_cool_water_counter.png" darken={0} /> },
  { key: "b252_abono_wt_water_potted_plant", start: 826.3, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_water_potted_plant_1.jpg" darken={0} /> },
  { key: "cmp_check_water", start: 830.08, dur: 7.36, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Agua de cocción, bien hecha" items={[{"text":"Hervir SIN sal","state":"done"},{"text":"Dejar enfriar del todo","state":"done"},{"text":"Regar como agua normal","state":"done"},{"text":"Salar recién en el plato","state":"done"}]} eyebrow="Solo cambiar el orden" accent="good" hue="amber" /> },
  { key: "b255_abono_wt_green_houseplant", start: 837.44, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_green_houseplant_1.jpg" darken={0} /> },
  { key: "b256_abono_wt_broccoli_pot", start: 843.04, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_broccoli_pot_1.jpg" darken={0} /> },
  { key: "b257_abono_wt_carrot_pot", start: 847.46, dur: 3.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_carrot_pot_1.jpg" darken={0} /> },
  { key: "b258_abono_wt_steam_pot_stove", start: 850.39, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_steam_pot_stove_2.webp" darken={0} /> },
  { key: "b259_abono_wt_windowsill_plants", start: 852.8, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_windowsill_plants_1.jpg" darken={0} /> },
  { key: "cmp_bars_water", start: 857.2, dur: 6.68, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Con agua de cocción","value":100,"display":"verde lustroso","winner":true},{"label":"Antes","value":45,"display":"amarillenta","tone":"danger"}]} eyebrow="Por agua que tiraba" title="La misma maceta" accent="good" hue="amber" /> },
  { key: "b262_abono_wt_potato_peeling_pot", start: 863.88, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_potato_peeling_pot_1.jpg" darken={0} /> },
  { key: "b263_abono_wt_green_recovery_plant", start: 866.52, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_green_recovery_plant_1.webp" darken={0} /> },
  { key: "b264_abono_wt_kitchen_cooking_wide", start: 869.9, dur: 2.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_kitchen_cooking_wide_1.jpg" darken={0} /> },
  { key: "b265_abono_wt_boil_pot2", start: 872.12, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_boil_pot2_1.webp" darken={0} /> },
  { key: "b266_abono_wt_pour_plant2", start: 876.04, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_pour_plant2_1.jpg" darken={0} /> },
  { key: "b267_abono_wt_green_leaves2", start: 879.28, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_wt_green_leaves2_1.jpg" darken={0} /> },
  { key: "b268_abono_ps_one_eggshell_hand", start: 884.8, dur: 8.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_one_eggshell_hand_2.jpg" darken={0} /> },
  { key: "b269_abono_ps_coffee_one_cup", start: 892.54, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_coffee_one_cup_2.jpg" darken={0} /> },
  { key: "b270_abono_ps_one_seedling_care", start: 895.4, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_one_seedling_care_1.png" darken={0} /> },
  { key: "b271_abono_ps_calendar_routine", start: 899.34, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_ps_calendar_routine.png" darken={0} /> },
  { key: "b272_abono_ps_sweeping_barn", start: 903.48, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_ps_sweeping_barn.png" darken={0} /> },
  { key: "b273_abono_ps_grandfather_thoughtful", start: 906.68, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_grandfather_thoughtful_1.jpg" darken={0} /> },
  { key: "b274_abono_ps_calm_garden_breeze", start: 909.2, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_calm_garden_breeze_1.jpg" darken={0} /> },
  { key: "b275_abono_ps_hands_rest_soil", start: 912.74, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_hands_rest_soil_1.webp" darken={0} /> },
  { key: "b276_abono_ps_single_step_path", start: 915.4, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_single_step_path_1.jpg" darken={0} /> },
  { key: "b277_abono_ps_small_start_pot", start: 919.26, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_small_start_pot_1.jpg" darken={0} /> },
  { key: "b278_abono_ps_quiet_kitchen_window", start: 922.18, dur: 5.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_ps_quiet_kitchen_window.png" darken={0} /> },
  { key: "b279_abono_ps_returning_daily", start: 927.54, dur: 5.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_ps_returning_daily.png" darken={0} /> },
  { key: "b280_abono_ps_one_eggshell_hand", start: 932.06, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_one_eggshell_hand_2.jpg" darken={0} /> },
  { key: "cmp_quote_return", start: 934.89, dur: 8.21, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_return_bg.png" words={parseQuote("La huerta no premia al que sabe mucho. Premia al que *vuelve*.")} accent="amber" hue="amber" fontSize={88} /> },
  { key: "b283_abono_ps_calendar_routine", start: 943.1, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_ps_calendar_routine.png" darken={0} /> },
  { key: "b284_abono_ps_sweeping_barn", start: 948.24, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_ps_sweeping_barn.png" darken={0} /> },
  { key: "b285_abono_ps_grandfather_thoughtful", start: 952.38, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_grandfather_thoughtful_1.jpg" darken={0} /> },
  { key: "b286_abono_ps_calm_garden_breeze", start: 955.84, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_ps_calm_garden_breeze_1.jpg" darken={0} /> },
  { key: "cmp_item_5", start: 957.68, dur: 5.72, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="5" name="Cebolla y Ajo" eyebrow="Alimenta y espanta" total="7" accent="amber" /> },
  { key: "b289_abono_on_skins_handful", start: 963.4, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_skins_handful_1.jpg" darken={0} /> },
  { key: "b290_abono_on_skins_jar_water", start: 967.28, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_skins_jar_water_2.jpg" darken={0} /> },
  { key: "b291_abono_on_golden_tea", start: 970.94, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_on_golden_tea.png" darken={0} /> },
  { key: "b292_abono_on_strain_tea", start: 974.34, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_strain_tea_1.jpg" darken={0} /> },
  { key: "b293_abono_on_spray_bottle_fill", start: 977.14, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_on_spray_bottle_fill.png" darken={0} /> },
  { key: "b294_abono_on_spray_leaves", start: 980.9, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_spray_leaves_1.jpg" darken={0} /> },
  { key: "cmp_onion_double", start: 983.78, dur: 7.38, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Cebolla y ajo: dos trabajos" items={["Alimenta: potasio y azufre","Espanta: el pulgón odia el olor","Té dorado, rociar al atardecer"]} accent={D} /> },
  { key: "cmp_proc_onion", start: 991.16, dur: 11.34, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Cáscaras en un frasco con agua"},{"title":"2-3 días a la sombra"},{"title":"Colar y rociar las hojas"}]} eyebrow="Repele al pulgón" title="El té de cebolla y ajo" accent="good" hue="amber" /> },
  { key: "b300_abono_on_onion_skin_macro", start: 1002.5, dur: 2.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_onion_skin_macro_1.jpg" darken={0} /> },
  { key: "b301_abono_on_garlic_bulb_macro", start: 1004.36, dur: 6.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_garlic_bulb_macro_1.jpg" darken={0} /> },
  { key: "b302_abono_on_rain_washing_leaves", start: 1010.12, dur: 6.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_rain_washing_leaves_1.png" darken={0} /> },
  { key: "b303_abono_on_chopping_onion", start: 1016.28, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_chopping_onion_1.jpg" darken={0} /> },
  { key: "cmp_anno_aphid", start: 1019.28, dur: 8.34, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_aphid_bg.png" annotations={[{"kind":"circle","x":0.5,"y":0.62,"w":0.22,"label":"Pulgón abajo de la hoja","color":"danger"},{"kind":"arrow","x":0.5,"y":0.4,"fromX":0.8,"fromY":0.15,"label":"Rociar por abajo","color":"good"}]} eyebrow="Dónde ataca" hue="amber" /> },
  { key: "b306_abono_on_spray_plant2", start: 1027.62, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_spray_plant2_1.jpg" darken={0} /> },
  { key: "b307_abono_on_aphids_macro2", start: 1029.88, dur: 6.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_aphids_macro2_1.jpg" darken={0} /> },
  { key: "cmp_no_poison", start: 1035.52, dur: 9.28, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="0" eyebrow="Cero químicos" caption="un olor que la naturaleza ya fabricó" accent="good" hue="amber" /> },
  { key: "b310_abono_on_skins_handful", start: 1044.8, dur: 5.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_skins_handful_1.jpg" darken={0} /> },
  { key: "b311_abono_on_skins_jar_water", start: 1049.62, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_skins_jar_water_2.jpg" darken={0} /> },
  { key: "b312_abono_on_golden_tea", start: 1053.56, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_on_golden_tea.png" darken={0} /> },
  { key: "b313_abono_on_strain_tea", start: 1055.72, dur: 5.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_strain_tea_1.jpg" darken={0} /> },
  { key: "b314_abono_on_spray_bottle_fill", start: 1061.1, dur: 7.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_on_spray_bottle_fill.png" darken={0} /> },
  { key: "cmp_on_shield", start: 1067.86, dur: 7.04, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🛡" eyebrow="Rociar al atardecer" caption="es un escudo, no una pared — repetir cada 3-4 días" accent="amber" hue="amber" /> },
  { key: "b317_abono_on_cabbage_clean", start: 1074.9, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_cabbage_clean_1.webp" darken={0} /> },
  { key: "b318_abono_on_kale_plant", start: 1077.48, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_kale_plant_1.jpg" darken={0} /> },
  { key: "cmp_on_proof", start: 1081.06, dur: 6.44, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🥬" eyebrow="Los repollos del abuelo" caption="ni un solo bicho — y olía feo" accent="good" hue="amber" /> },
  { key: "b321_abono_on_onion_skin_macro", start: 1087.5, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_onion_skin_macro_1.jpg" darken={0} /> },
  { key: "b322_abono_on_garlic_bulb_macro", start: 1091.08, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_garlic_bulb_macro_1.jpg" darken={0} /> },
  { key: "b323_abono_on_rain_washing_leaves", start: 1093.18, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_rain_washing_leaves_1.png" darken={0} /> },
  { key: "b324_abono_on_chopping_onion", start: 1096.7, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_chopping_onion_1.jpg" darken={0} /> },
  { key: "b325_abono_on_pest_fly_off", start: 1098.74, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_pest_fly_off_1.jpg" darken={0} /> },
  { key: "b326_abono_on_peel_onion2", start: 1102.36, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_peel_onion2_1.jpg" darken={0} /> },
  { key: "b327_abono_on_spray_plant2", start: 1107.26, dur: 7.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_on_spray_plant2_1.jpg" darken={0} /> },
  { key: "cmp_item_6", start: 1114, dur: 4.62, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="6" name="Bolsita de Té" eyebrow="Nitrógeno · lo chico suma" total="7" accent="amber" /> },
  { key: "b330_abono_te_open_teabag", start: 1118.62, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_open_teabag_2.png" darken={0} /> },
  { key: "b331_abono_te_wet_leaves_hand", start: 1122.44, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_wet_leaves_hand_1.jpg" darken={0} /> },
  { key: "b332_abono_te_plastic_teabag", start: 1125.08, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_plastic_teabag_1.jpg" darken={0} /> },
  { key: "b333_abono_te_paper_teabag", start: 1129.06, dur: 5.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_te_paper_teabag.png" darken={0} /> },
  { key: "b334_abono_te_leaves_on_soil", start: 1133.62, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_leaves_on_soil_1.png" darken={0} /> },
  { key: "b335_abono_te_cover_with_soil", start: 1136.1, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_cover_with_soil_1.jpg" darken={0} /> },
  { key: "b336_abono_te_leaves_compost", start: 1139.12, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_leaves_compost_2.jpg" darken={0} /> },
  { key: "b337_abono_te_microplastic_warn", start: 1141.38, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_microplastic_warn_1.jpg" darken={0} /> },
  { key: "cmp_microplastic", start: 1145.48, dur: 3.56, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_microplastic_bg.png" impact="Usa SOLO las hojas." setup="Muchas bolsitas tienen plástico..." impactAccent="danger" hitAt={1} boom={0} darken={0.5} /> },
  { key: "cmp_tea_cross", start: 1149.04, dur: 8.64, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="La trampa de la bolsita" items={["Papel puro: va entera a la tierra","Con plástico: SOLO las hojas","Si dudas: solo las hojas"]} accent={D} cross /> },
  { key: "b341_abono_te_jar_collecting", start: 1157.68, dur: 5.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_jar_collecting_1.jpg" darken={0} /> },
  { key: "b342_abono_te_small_things_soil", start: 1162.4, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_small_things_soil_1.jpg" darken={0} /> },
  { key: "b343_abono_te_teabag_cup2", start: 1164.42, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_teabag_cup2_2.png" darken={0} /> },
  { key: "b344_abono_te_leaves_soil2", start: 1166.86, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_leaves_soil2_1.png" darken={0} /> },
  { key: "b345_abono_te_used_teabag_plate", start: 1168.78, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_used_teabag_plate_1.jpg" darken={0} /> },
  { key: "b346_abono_te_pour_tea_cup", start: 1171.52, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_pour_tea_cup_1.jpg" darken={0} /> },
  { key: "b347_abono_te_open_teabag", start: 1173.52, dur: 6.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_open_teabag_2.png" darken={0} /> },
  { key: "b348_abono_te_wet_leaves_hand", start: 1179.3, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_wet_leaves_hand_1.jpg" darken={0} /> },
  { key: "b349_abono_te_plastic_teabag", start: 1182.52, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_plastic_teabag_1.jpg" darken={0} /> },
  { key: "b350_abono_te_paper_teabag", start: 1186.06, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_te_paper_teabag.png" darken={0} /> },
  { key: "b351_abono_te_leaves_on_soil", start: 1188.94, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_leaves_on_soil_1.png" darken={0} /> },
  { key: "b352_abono_te_cover_with_soil", start: 1193.34, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_cover_with_soil_1.jpg" darken={0} /> },
  { key: "b353_abono_te_leaves_compost", start: 1196.44, dur: 5.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_leaves_compost_2.jpg" darken={0} /> },
  { key: "b354_abono_te_microplastic_warn", start: 1201.88, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_microplastic_warn_1.jpg" darken={0} /> },
  { key: "b355_abono_te_handful_leaves_month", start: 1204.18, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_handful_leaves_month_1.jpg" darken={0} /> },
  { key: "cmp_te_small", start: 1206.28, dur: 6.44, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="∞" eyebrow="Una bolsita por día" caption="lo chico, repetido mil veces, manda en la huerta" accent="good" hue="amber" /> },
  { key: "b358_abono_te_jar_collecting", start: 1212.72, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_jar_collecting_1.jpg" darken={0} /> },
  { key: "cmp_te_year", start: 1216.2, dur: 11.68, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🪣" eyebrow="Una bolsita por día" caption="al cabo de un año: baldes de nitrógeno" accent="good" hue="amber" /> },
  { key: "b361_abono_te_leaves_soil2", start: 1227.88, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_leaves_soil2_1.png" darken={0} /> },
  { key: "b362_abono_te_used_teabag_plate", start: 1231.4, dur: 7.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_used_teabag_plate_1.jpg" darken={0} /> },
  { key: "b363_abono_te_pour_tea_cup", start: 1238.66, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_te_pour_tea_cup_1.jpg" darken={0} /> },
  { key: "cmp_item_7", start: 1243.92, dur: 3.76, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="7" name="Recortes de Verdura" eyebrow="Tierra negra gratis" total="7" accent="good" /> },
  { key: "b365_abono_sc_potato_peels", start: 1247.68, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_potato_peels_1.jpg" darken={0} /> },
  { key: "b366_abono_sc_broccoli_stalk", start: 1249.54, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_broccoli_stalk_1.png" darken={0} /> },
  { key: "b367_abono_sc_lettuce_outer_leaves", start: 1253.24, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_lettuce_outer_leaves_1.webp" darken={0} /> },
  { key: "b368_abono_sc_scraps_bowl_full", start: 1256.84, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_scraps_bowl_full_1.webp" darken={0} /> },
  { key: "b369_abono_sc_carry_bowl_garden", start: 1260.76, dur: 7.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_carry_bowl_garden_1.jpg" darken={0} /> },
  { key: "b370_abono_sc_dig_hole_between", start: 1267.4, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_dig_hole_between_1.jpg" darken={0} /> },
  { key: "b371_abono_sc_dump_scraps_hole", start: 1270.78, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_dump_scraps_hole_1.jpg" darken={0} /> },
  { key: "cmp_sc_fortune", start: 1274.86, dur: 2.38, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$$$" eyebrow="Tierra negra de vivero" caption="la fabricas con lo que pelas para la cena" accent="good" hue="amber" /> },
  { key: "cmp_sc_smell", start: 1277.24, dur: 5.96, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="🌲" eyebrow="Tierra negra de verdad" caption="huele a bosque después de la lluvia" accent="good" hue="amber" /> },
  { key: "b374_abono_sc_soil_smell_handful", start: 1283.2, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_soil_smell_handful_1.jpg" darken={0} /> },
  { key: "b375_abono_sc_no_bin_needed", start: 1287.52, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_no_bin_needed_1.jpg" darken={0} /> },
  { key: "b376_abono_sc_empty_bed_resting", start: 1292.42, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_empty_bed_resting_1.jpg" darken={0} /> },
  { key: "b377_abono_sc_tomato_cores", start: 1294.42, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_tomato_cores_1.webp" darken={0} /> },
  { key: "b378_abono_sc_cucumber_ends", start: 1296.72, dur: 6.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_cucumber_ends_1.jpg" darken={0} /> },
  { key: "b379_abono_sc_mixed_peels_macro", start: 1303.08, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_mixed_peels_macro_1.jpg" darken={0} /> },
  { key: "b380_abono_sc_garden_fork_soil", start: 1306.16, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_garden_fork_soil_1.jpg" darken={0} /> },
  { key: "b381_abono_sc_peel_potato2", start: 1308.7, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_peel_potato2_1.jpg" darken={0} /> },
  { key: "b382_abono_sc_bowl_scraps2", start: 1310.64, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_bowl_scraps2_1.jpg" darken={0} /> },
  { key: "b383_abono_sc_bury_hole2", start: 1314.38, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_bury_hole2_1.jpg" darken={0} /> },
  { key: "cmp_proc_scraps", start: 1316.56, dur: 6.62, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Bol de recortes al lado de la tabla"},{"title":"Pozo de un palmo entre plantas"},{"title":"Echar y tapar con la tierra"}]} eyebrow="Tierra negra gratis" title="Sin compostera, sin nada" accent="good" hue="amber" /> },
  { key: "b385_abono_sc_potato_peels", start: 1323.18, dur: 6.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_potato_peels_1.jpg" darken={0} /> },
  { key: "b386_abono_sc_broccoli_stalk", start: 1329.04, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_broccoli_stalk_1.png" darken={0} /> },
  { key: "b387_abono_sc_lettuce_outer_leaves", start: 1331.56, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_lettuce_outer_leaves_1.webp" darken={0} /> },
  { key: "b388_abono_sc_scraps_bowl_full", start: 1334.22, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_scraps_bowl_full_1.webp" darken={0} /> },
  { key: "b389_abono_sc_carry_bowl_garden", start: 1336.56, dur: 5.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_carry_bowl_garden_1.jpg" darken={0} /> },
  { key: "b390_abono_sc_dig_hole_between", start: 1342, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_dig_hole_between_1.jpg" darken={0} /> },
  { key: "b391_abono_sc_dump_scraps_hole", start: 1347.04, dur: 6.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_dump_scraps_hole_1.jpg" darken={0} /> },
  { key: "b392_abono_sc_cover_soil_hand", start: 1353.02, dur: 1.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_sc_cover_soil_hand_1.jpg" darken={0} /> },
  { key: "b393_abono_tr_dig_long_trench", start: 1354.5, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_dig_long_trench_1.jpg" darken={0} /> },
  { key: "b394_abono_tr_spade_deep_soil", start: 1356.56, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_spade_deep_soil_1.webp" darken={0} /> },
  { key: "b395_abono_tr_bucket_kitchen_door", start: 1359.86, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_bucket_kitchen_door_1.jpg" darken={0} /> },
  { key: "b396_abono_tr_dump_bucket_trench", start: 1364.4, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_dump_bucket_trench_2.jpg" darken={0} /> },
  { key: "b397_abono_tr_cover_shovel_soil", start: 1368.3, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_cover_shovel_soil_1.jpg" darken={0} /> },
  { key: "b398_abono_tr_all_scraps_mixed", start: 1370.54, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_all_scraps_mixed_1.png" darken={0} /> },
  { key: "b399_abono_tr_winter_field_snow", start: 1372.5, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_winter_field_snow_1.jpg" darken={0} /> },
  { key: "b400_abono_tr_worms_underground", start: 1376.82, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_worms_underground_1.jpg" darken={0} /> },
  { key: "b401_abono_tr_fungi_decompose", start: 1379.42, dur: 5.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_fungi_decompose_1.png" darken={0} /> },
  { key: "b402_abono_tr_richest_black_soil", start: 1384.54, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_richest_black_soil_1.jpg" darken={0} /> },
  { key: "b403_abono_tr_plant_tomato_spring", start: 1387.64, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_plant_tomato_spring_1.jpg" darken={0} /> },
  { key: "cmp_proc_trench", start: 1390.22, dur: 11.9, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Cavar un surco al lado del cantero"},{"title":"Volcar el balde cada noche"},{"title":"Una palada de tierra encima"}]} eyebrow="Todo junto, sin separar" title="La zanja del abuelo" accent="good" hue="amber" /> },
  { key: "cmp_seasons", start: 1402.12, dur: 7.66, kind: "growthtimeline", el: (d) => <GrowthTimeline durationInFrames={d} stages={[{"label":"Otoño","sub":"cavar"},{"label":"Invierno","sub":"enterrar"},{"label":"Primavera","sub":"tierra negra"},{"label":"Cosecha","sub":"tomates"}]} title="La zanja trabaja sola todo el invierno" /> },
  { key: "b408_abono_tr_pail_lid_simple", start: 1409.78, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_pail_lid_simple_1.jpg" darken={0} /> },
  { key: "b409_abono_tr_no_smell_buried", start: 1412.6, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_no_smell_buried_1.jpg" darken={0} /> },
  { key: "b410_abono_tr_seasons_passing", start: 1414.88, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_seasons_passing_1.jpg" darken={0} /> },
  { key: "b411_abono_tr_grandfather_smile_garden", start: 1418.8, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_grandfather_smile_garden_1.jpg" darken={0} /> },
  { key: "b412_abono_tr_strip_planting_tomatoes", start: 1422.2, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_strip_planting_tomatoes_1.jpg" darken={0} /> },
  { key: "b413_abono_tr_spade_dig2", start: 1427.36, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_spade_dig2_1.jpg" darken={0} /> },
  { key: "b414_abono_tr_bucket_scraps2", start: 1429.78, dur: 5.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_bucket_scraps2_1.jpg" darken={0} /> },
  { key: "cmp_tr_30s", start: 1434.34, dur: 9.26, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="30s" eyebrow="Por noche, nada más" caption="la tierra hace el trabajo mientras dormís" accent="good" hue="amber" /> },
  { key: "b417_abono_tr_spade_deep_soil", start: 1443.6, dur: 7.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_spade_deep_soil_1.webp" darken={0} /> },
  { key: "b418_abono_tr_bucket_kitchen_door", start: 1450.48, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_bucket_kitchen_door_1.jpg" darken={0} /> },
  { key: "b419_abono_tr_dump_bucket_trench", start: 1453.62, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_dump_bucket_trench_2.jpg" darken={0} /> },
  { key: "b420_abono_tr_cover_shovel_soil", start: 1459.3, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_cover_shovel_soil_1.jpg" darken={0} /> },
  { key: "b421_abono_tr_all_scraps_mixed", start: 1462.62, dur: 7.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_all_scraps_mixed_1.png" darken={0} /> },
  { key: "b422_abono_tr_winter_field_snow", start: 1469.16, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_winter_field_snow_1.jpg" darken={0} /> },
  { key: "b423_abono_tr_worms_underground", start: 1472.32, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_worms_underground_1.jpg" darken={0} /> },
  { key: "cmp_tr_strip", start: 1474.26, dur: 7.26, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="★" eyebrow="Para la primavera" caption="la tierra más negra, rica y viva de la huerta" accent="good" hue="amber" /> },
  { key: "b426_abono_tr_plant_tomato_spring", start: 1481.52, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_plant_tomato_spring_1.jpg" darken={0} /> },
  { key: "b427_abono_tr_legendary_tomatoes", start: 1484.84, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_legendary_tomatoes_2.jpg" darken={0} /> },
  { key: "b428_abono_tr_neighbors_admire", start: 1487.8, dur: 6.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_neighbors_admire_1.png" darken={0} /> },
  { key: "b429_abono_tr_give_away_basket", start: 1494.28, dur: 7.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_give_away_basket_1.jpg" darken={0} /> },
  { key: "b430_abono_tr_spade_rest_ground", start: 1501.53, dur: 6.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_spade_rest_ground_1.jpg" darken={0} /> },
  { key: "b431_abono_tr_pail_lid_simple", start: 1507.58, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_pail_lid_simple_1.jpg" darken={0} /> },
  { key: "b432_abono_tr_no_smell_buried", start: 1511.44, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_no_smell_buried_1.jpg" darken={0} /> },
  { key: "cmp_quote_winter", start: 1514.34, dur: 9.2, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_winter_bg.png" words={parseQuote("—¿Qué les echas? —*Les echo el invierno.*")} accent="good" hue="amber" fontSize={96} /> },
  { key: "b435_abono_tr_strip_planting_tomatoes", start: 1523.54, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_strip_planting_tomatoes_1.jpg" darken={0} /> },
  { key: "b436_abono_tr_spade_dig2", start: 1526.72, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_spade_dig2_1.jpg" darken={0} /> },
  { key: "b437_abono_tr_bucket_scraps2", start: 1529.82, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_bucket_scraps2_1.jpg" darken={0} /> },
  { key: "b438_abono_tr_tomatoes_harvest2", start: 1532.34, dur: 10.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_tomatoes_harvest2_1.jpg" darken={0} /> },
  { key: "b439_abono_tr_dig_long_trench", start: 1542.02, dur: 5.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_dig_long_trench_1.jpg" darken={0} /> },
  { key: "b440_abono_tr_spade_deep_soil", start: 1547.4, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_spade_deep_soil_1.webp" darken={0} /> },
  { key: "b441_abono_tr_bucket_kitchen_door", start: 1549.66, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_bucket_kitchen_door_1.jpg" darken={0} /> },
  { key: "b442_abono_tr_dump_bucket_trench", start: 1552.36, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_dump_bucket_trench_2.jpg" darken={0} /> },
  { key: "b443_abono_tr_cover_shovel_soil", start: 1555.32, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_tr_cover_shovel_soil_1.jpg" darken={0} /> },
  { key: "cmp_grid", start: 1557.58, dur: 8.14, kind: "gridreveal", el: (d) => <GridReveal durationInFrames={d} tiles={[{"number":"1","name":"Cáscara de Huevo"},{"number":"2","name":"Borra de Café"},{"number":"3","name":"Cáscara de Banana"},{"number":"4","name":"Agua de Cocción"},{"number":"5","name":"Cebolla y Ajo"},{"number":"6","name":"Bolsita de Té"},{"number":"7","name":"Recortes de Verdura"}]} title="7 basuras · 1 zanja · tierra gratis" subtitle="El método del abuelo" /> },
  { key: "b445_abono_rc_coffee_recap", start: 1565.72, dur: 6.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_coffee_recap_1.jpg" darken={0} /> },
  { key: "b446_abono_rc_banana_recap", start: 1571.54, dur: 2.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_banana_recap_1.jpg" darken={0} /> },
  { key: "b447_abono_rc_water_recap", start: 1573.2, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_water_recap_1.jpg" darken={0} /> },
  { key: "b448_abono_rc_onion_recap", start: 1578.52, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_onion_recap_1.jpg" darken={0} /> },
  { key: "b449_abono_rc_tea_recap", start: 1582, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_tea_recap_1.jpg" darken={0} /> },
  { key: "b450_abono_rc_scraps_recap", start: 1586, dur: 7.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_scraps_recap_1.jpg" darken={0} /> },
  { key: "b451_abono_rc_trench_recap", start: 1593.08, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_trench_recap_1.jpg" darken={0} /> },
  { key: "b452_abono_rc_start_one_thing", start: 1596.2, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_start_one_thing_1.jpg" darken={0} /> },
  { key: "b453_abono_rc_no_meat_bones", start: 1599.2, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_no_meat_bones_1.jpg" darken={0} /> },
  { key: "b454_abono_rc_no_dairy_oil", start: 1601.8, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_rc_no_dairy_oil.png" darken={0} /> },
  { key: "b455_abono_rc_rats_warning", start: 1603.56, dur: 2.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_rats_warning_2.jpg" darken={0} /> },
  { key: "b456_abono_rc_grew_from_earth", start: 1605.18, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_grew_from_earth_1.webp" darken={0} /> },
  { key: "b457_abono_rc_seven_scraps_layout", start: 1610.5, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_seven_scraps_layout_2.jpg" darken={0} /> },
  { key: "b458_abono_rc_eggshell_recap", start: 1613.44, dur: 5.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_eggshell_recap_1.webp" darken={0} /> },
  { key: "cmp_check_method", start: 1618.14, dur: 6.38, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="El método completo" items={[{"text":"Cáscara de huevo · calcio","state":"done"},{"text":"Borra de café · nitrógeno","state":"done"},{"text":"Banana · potasio","state":"done"},{"text":"Agua de cocción · sin sal","state":"done"},{"text":"Cebolla y ajo · espanta plagas","state":"done"},{"text":"Bolsita de té · solo hojas","state":"done"},{"text":"Recortes · la zanja","state":"done"}]} eyebrow="Empezá por uno" accent="good" hue="amber" /> },
  { key: "b462_abono_rc_onion_recap", start: 1624.52, dur: 6.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_onion_recap_1.jpg" darken={0} /> },
  { key: "b463_abono_rc_tea_recap", start: 1630.26, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_tea_recap_1.jpg" darken={0} /> },
  { key: "cmp_never", start: 1632.78, dur: 6.28, kind: "lielist", el: (d) => <LieList durationInFrames={d} title="Lo que NUNCA enterrar" items={["Carne y huesos","Lácteos y queso","Aceite y grasa","Atrae ratas y huele mal"]} image="img/cmp_never_bg.png" accent="danger" /> },
  { key: "b467_abono_rc_no_meat_bones", start: 1639.06, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_no_meat_bones_1.jpg" darken={0} /> },
  { key: "b468_abono_rc_no_dairy_oil", start: 1640.86, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/abono_rc_no_dairy_oil.png" darken={0} /> },
  { key: "b469_abono_rc_rats_warning", start: 1643.26, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_rats_warning_2.jpg" darken={0} /> },
  { key: "b470_abono_rc_grew_from_earth", start: 1645.32, dur: 1.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_grew_from_earth_1.webp" darken={0} /> },
  { key: "b471_abono_rc_seven_scraps_layout", start: 1646.86, dur: 1.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_seven_scraps_layout_2.jpg" darken={0} /> },
  { key: "b472_abono_rc_eggshell_recap", start: 1648.4, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_eggshell_recap_1.webp" darken={0} /> },
  { key: "b473_abono_rc_coffee_recap", start: 1650.08, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_coffee_recap_1.jpg" darken={0} /> },
  { key: "b474_abono_rc_banana_recap", start: 1654.42, dur: 6.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_banana_recap_1.jpg" darken={0} /> },
  { key: "cmp_rule", start: 1659.96, dur: 7.28, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_rule_bg.png" words={parseQuote("Si *creció de la tierra*, vuelve a la tierra. Si vino de un animal, no.")} accent="amber" hue="amber" fontSize={86} /> },
  { key: "b478_abono_rc_scraps_recap", start: 1667.24, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_scraps_recap_1.jpg" darken={0} /> },
  { key: "b479_abono_rc_trench_recap", start: 1669.28, dur: 5.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_trench_recap_1.jpg" darken={0} /> },
  { key: "b480_abono_rc_start_one_thing", start: 1673.96, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_start_one_thing_1.jpg" darken={0} /> },
  { key: "b481_abono_rc_no_meat_bones", start: 1676.16, dur: 1.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_rc_no_meat_bones_1.jpg" darken={0} /> },
  { key: "cmp_cl_half", start: 1677.58, dur: 7.96, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_cl_half_bg.png" impact="la mitad del trabajo." setup="Alimentar la tierra es solo..." impactAccent="amber" hitAt={1} boom={0} darken={0.45} /> },
  { key: "b484_abono_cl_pest_eating_leaf", start: 1685.54, dur: 4.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cl_pest_eating_leaf_1.jpg" darken={0} /> },
  { key: "b485_abono_cl_pantry_kitchen_items", start: 1689.38, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cl_pantry_kitchen_items_2.webp" darken={0} /> },
  { key: "b486_abono_cl_spray_protect_plant", start: 1693.2, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/abono_cl_spray_protect_plant_1.png" darken={0} /> },
  { key: "cmp_cl_free", start: 1696.12, dur: 5.64, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$0" eyebrow="Defender la huerta" caption="con lo que ya tienes en la cocina" accent="good" hue="amber" /> },
  { key: "cmp_teaser", start: 1701.76, dur: 11.36, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="→" title="Espanta las plagas, sin veneno" desc="La misma cocina esconde con qué defender tu huerta — gratis." eyebrow="PRÓXIMO VIDEO" image="img/cmp_teaser_bg.png" /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "kl1", start: 2.38, dur: 2.54, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"una","at":0},{"t":"razón","at":0.16},{"t":"muy","at":0.5},{"t":"simple.","at":0.84,"hl":true}]} accent="amber" /> },
  { key: "kl2", start: 101.1, dur: 4.46, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"ese","at":0},{"t":"último","at":0.38},{"t":"es","at":0.54},{"t":"el","at":0.76},{"t":"que","at":0.94},{"t":"de","at":1.04},{"t":"verdad","at":1.42},{"t":"lo","at":1.96},{"t":"cambia","at":2.32,"hl":true},{"t":"todo.","at":2.76}]} accent="amber" /> },
  { key: "kl3", start: 165.58, dur: 3.8, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"Una","at":0},{"t":"huerta","at":0},{"t":"no","at":0.74},{"t":"necesita","at":1.22},{"t":"tu","at":1.88},{"t":"dinero,","at":2.1,"hl":true}]} accent="amber" /> },
  { key: "kl6", start: 215.3, dur: 3.38, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"Eso","at":0},{"t":"es","at":0},{"t":"hambre,","at":0.28},{"t":"hambre","at":1.08},{"t":"de","at":1.38},{"t":"calcio.","at":1.68,"hl":true}]} accent="amber" /> },
  { key: "kl8", start: 672.52, dur: 2.98, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"o","at":0},{"t":"enterrada","at":0.1,"hl":true},{"t":"o","at":0.88},{"t":"en","at":0.98},{"t":"agua","at":1.14},{"t":"tapada,","at":1.28}]} accent="amber" /> },
  { key: "kl9", start: 801.52, dur: 3.38, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":"tiene","at":0},{"t":"que","at":0.08},{"t":"ser","at":0.18},{"t":"agua","at":0.58},{"t":"sin","at":1.22},{"t":"sal,","at":1.68,"hl":true}]} accent="amber" /> },
];
