// cues_evapcooler.gen.tsx — GENERADO por beatsheet.mjs desde evapcooler.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/evapcooler.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { TimelineKit } from "./kit/TimelineKit";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { StatTag } from "./scenes/StatTag";
import { PhraseTag } from "./scenes/PhraseTag";
import { SagaTimeline } from "./scenes/SagaTimeline";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { NextVideoEndcard } from "./scenes/NextVideoEndcard";

const B = COLORS.cold;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "ec_porch_heat_a", start: 5.56, dur: 5.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_porch_heat.png" darken={0} kbPhase={1} /> },
  { key: "ec_porch_heat_b", start: 10.77, dur: 5.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_porch_heat.png" darken={0} kbPhase={2} /> },
  { key: "ec_cool_parlor", start: 15.48, dur: 6.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_cool_parlor.png" darken={0} /> },
  { key: "ec_no_wire", start: 21.8, dur: 8.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_no_wire.png" darken={0} /> },
  { key: "ec_river_wet_a", start: 71.04, dur: 6.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_river_wet.png" darken={0} kbPhase={1} /> },
  { key: "ec_river_wet_b", start: 77.99, dur: 6.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_river_wet.png" darken={0} kbPhase={2} /> },
  { key: "ec_wet_arm_a", start: 84.44, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_wet_arm.png" darken={0} kbPhase={1} /> },
  { key: "ec_wet_arm_b", start: 90.46, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_wet_arm.png" darken={0} kbPhase={2} /> },
  { key: "ec_evaporation", start: 95.98, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_evaporation.png" darken={0} /> },
  { key: "cmp_secret", start: 98.65, dur: 18.47, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_secret_bg.png" impact="Drying water pulls heat out of the air." setup="The whole secret:" impactAccent="cold" hitAt={1.2} boom={0} darken={0.42} /> },
  { key: "ec_sweat", start: 117.12, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_sweat.png" darken={0} /> },
  { key: "ec_clay_jug", start: 120.2, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_clay_jug.png" darken={0} /> },
  { key: "ec_lake_breeze_a", start: 124.08, dur: 5.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_lake_breeze.mp4" darken={0} clipDur={6} kbPhase={1} /> },
  { key: "ec_lake_breeze_b", start: 129.34, dur: 5.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_lake_breeze.mp4" darken={0} clipDur={6} kbPhase={2} /> },
  { key: "cmp_stat20", start: 134.11, dur: 16.65, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={20} prefix="-" suffix="°" label="in a hot dry room, from a bucket of water" eyebrow="The drop" accent="good" hue="cold" /> },
  { key: "ec_thermo_hot", start: 150.76, dur: 6.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thermo_hot.png" darken={0} /> },
  { key: "ec_thermo_cool_a", start: 156.75, dur: 10.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thermo_cool.png" darken={0} kbPhase={1} /> },
  { key: "ec_thermo_cool_b", start: 166.89, dur: 10.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thermo_cool.png" darken={0} kbPhase={2} /> },
  { key: "ec_thermo_cool_c", start: 177.03, dur: 10.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thermo_cool.png" darken={0} kbPhase={3} /> },
  { key: "ec_thermo_cool_undefined", start: 187.17, dur: 10.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thermo_cool.png" darken={0} kbPhase={4} /> },
  { key: "ec_thermo_cool_undefined", start: 197.31, dur: 10.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thermo_cool.png" darken={0} kbPhase={5} /> },
  { key: "ec_well_water", start: 206.97, dur: 6.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_well_water.png" darken={0} /> },
  { key: "ec_sheet_window_a", start: 212.48, dur: 7.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_sheet_window.png" darken={0} kbPhase={1} /> },
  { key: "ec_sheet_window_b", start: 219.99, dur: 7.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_sheet_window.png" darken={0} kbPhase={2} /> },
  { key: "ec_sheet_window_c", start: 227.5, dur: 7.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_sheet_window.png" darken={0} kbPhase={3} /> },
  { key: "ec_cellar_cool_a", start: 234.51, dur: 6.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_cellar_cool.png" darken={0} kbPhase={1} /> },
  { key: "ec_cellar_cool_b", start: 241.38, dur: 6.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_cellar_cool.png" darken={0} kbPhase={2} /> },
  { key: "ec_towel_test_a", start: 247.74, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_towel_test.png" darken={0} kbPhase={1} /> },
  { key: "ec_towel_test_b", start: 254.32, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_towel_test.png" darken={0} kbPhase={2} /> },
  { key: "ec_towel_test_c", start: 260.9, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_towel_test.png" darken={0} kbPhase={3} /> },
  { key: "ec_towel_test_undefined", start: 267.48, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_towel_test.png" darken={0} kbPhase={4} /> },
  { key: "ec_towel_test_undefined", start: 274.06, dur: 6.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_towel_test.png" darken={0} kbPhase={5} /> },
  { key: "cmp_materials", start: 280.15, dur: 38.29, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="The whole cooler" items={[{"text":"A bucket of water (up top)","state":"done"},{"text":"A wet pad — burlap or aspen","state":"done"},{"text":"A frame / old window screen","state":"done"},{"text":"A catch pan below","state":"done"}]} eyebrow="~$12 · any hardware store" accent="good" hue="amber" image="img/cmp_materials_bg.png" /> },
  { key: "ec_bucket", start: 318.44, dur: 9.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_bucket.mp4" darken={0} clipDur={6} /> },
  { key: "ec_pad_hero", start: 327.45, dur: 7.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_pad_hero.png" darken={0} /> },
  { key: "ec_burlap_a", start: 334.65, dur: 5.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_burlap.png" darken={0} kbPhase={1} /> },
  { key: "ec_burlap_b", start: 340.56, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_burlap.png" darken={0} kbPhase={2} /> },
  { key: "ec_honeycomb_pad", start: 345.96, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_honeycomb_pad.png" darken={0} /> },
  { key: "ec_frame", start: 349.07, dur: 8.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_frame.png" darken={0} /> },
  { key: "ec_catch_pan_a", start: 356.92, dur: 8.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_catch_pan.png" darken={0} kbPhase={1} /> },
  { key: "ec_catch_pan_b", start: 365.48, dur: 8.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_catch_pan.png" darken={0} kbPhase={2} /> },
  { key: "ec_catch_pan_c", start: 374.04, dur: 8.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_catch_pan.png" darken={0} kbPhase={3} /> },
  { key: "ec_catch_pan_undefined", start: 382.6, dur: 8.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_catch_pan.png" darken={0} kbPhase={4} /> },
  { key: "ec_catch_pan_undefined", start: 391.16, dur: 8.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_catch_pan.png" darken={0} kbPhase={5} /> },
  { key: "ec_drip_a", start: 399.24, dur: 5.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_drip.png" darken={0} kbPhase={1} /> },
  { key: "ec_drip_b", start: 405.03, dur: 5.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_drip.png" darken={0} kbPhase={2} /> },
  { key: "ec_wick_a", start: 410.31, dur: 7.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_wick.png" darken={0} kbPhase={1} /> },
  { key: "ec_wick_b", start: 418.06, dur: 7.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_wick.png" darken={0} kbPhase={2} /> },
  { key: "ec_window_shade_a", start: 425.31, dur: 6.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_window_shade.png" darken={0} kbPhase={1} /> },
  { key: "ec_window_shade_b", start: 432.27, dur: 6.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_window_shade.png" darken={0} kbPhase={2} /> },
  { key: "ec_window_shade_c", start: 439.23, dur: 6.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_window_shade.png" darken={0} kbPhase={3} /> },
  { key: "ec_window_shade_undefined", start: 446.19, dur: 6.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_window_shade.png" darken={0} kbPhase={4} /> },
  { key: "ec_cooler_box_a", start: 452.67, dur: 5.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_cooler_box.png" darken={0} kbPhase={1} /> },
  { key: "ec_cooler_box_b", start: 458.04, dur: 5.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_cooler_box.png" darken={0} kbPhase={2} /> },
  { key: "ec_three_sides_a", start: 462.9, dur: 8.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_three_sides.png" darken={0} kbPhase={1} /> },
  { key: "ec_three_sides_b", start: 471.64, dur: 8.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_three_sides.png" darken={0} kbPhase={2} /> },
  { key: "ec_three_sides_c", start: 480.38, dur: 8.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_three_sides.png" darken={0} kbPhase={3} /> },
  { key: "ec_three_sides_undefined", start: 489.12, dur: 8.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_three_sides.png" darken={0} kbPhase={4} /> },
  { key: "ec_three_sides_undefined", start: 497.86, dur: 8.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_three_sides.png" darken={0} kbPhase={5} /> },
  { key: "ec_feed_sacks_a", start: 506.12, dur: 7.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feed_sacks.png" darken={0} kbPhase={1} /> },
  { key: "ec_feed_sacks_b", start: 513.76, dur: 7.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feed_sacks.png" darken={0} kbPhase={2} /> },
  { key: "ec_feed_sacks_c", start: 521.4, dur: 7.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feed_sacks.png" darken={0} kbPhase={3} /> },
  { key: "ec_feed_sacks_undefined", start: 529.04, dur: 7.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feed_sacks.png" darken={0} kbPhase={4} /> },
  { key: "ec_lime_scale_a", start: 536.2, dur: 6.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_lime_scale.png" darken={0} kbPhase={1} /> },
  { key: "ec_lime_scale_b", start: 543.08, dur: 6.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_lime_scale.png" darken={0} kbPhase={2} /> },
  { key: "ec_lime_scale_c", start: 549.96, dur: 6.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_lime_scale.png" darken={0} kbPhase={3} /> },
  { key: "ec_lime_scale_undefined", start: 556.84, dur: 6.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_lime_scale.png" darken={0} kbPhase={4} /> },
  { key: "cmp_place", start: 563.21, dur: 16.62, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Where to put it" items={[{"text":"Shady side of the house","state":"done"},{"text":"Open a HIGH window far side","state":"done"},{"text":"Let the house breathe through","state":"done"}]} eyebrow="Get this right or it does nothing" accent="good" hue="cold" image="img/cmp_place_bg.png" /> },
  { key: "ec_airflow_a", start: 579.83, dur: 6.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_airflow.png" darken={0} kbPhase={1} /> },
  { key: "ec_airflow_b", start: 585.91, dur: 6.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_airflow.png" darken={0} kbPhase={2} /> },
  { key: "ec_high_window", start: 591.48, dur: 7.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_high_window.png" darken={0} /> },
  { key: "ec_hot_rises_a", start: 598.26, dur: 7.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_hot_rises.png" darken={0} kbPhase={1} /> },
  { key: "ec_hot_rises_b", start: 605.39, dur: 7.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_hot_rises.png" darken={0} kbPhase={2} /> },
  { key: "ec_hot_rises_c", start: 612.52, dur: 7.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_hot_rises.png" darken={0} kbPhase={3} /> },
  { key: "ec_hot_rises_undefined", start: 619.65, dur: 7.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_hot_rises.png" darken={0} kbPhase={4} /> },
  { key: "cmp_nightflush", start: 626.3, dur: 60.72, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Open wide at night"},{"title":"Flush the heat from the walls"},{"title":"Shut tight by day"}]} eyebrow="Costs nothing" title="Night flush" accent="good" hue="cold" /> },
  { key: "ec_thick_walls_a", start: 687.02, dur: 6.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thick_walls.png" darken={0} kbPhase={1} /> },
  { key: "ec_thick_walls_b", start: 693.36, dur: 6.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thick_walls.png" darken={0} kbPhase={2} /> },
  { key: "ec_thick_walls_c", start: 699.7, dur: 6.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_thick_walls.png" darken={0} kbPhase={3} /> },
  { key: "ec_windows_open_a", start: 705.53, dur: 6.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_windows_open.png" darken={0} kbPhase={1} /> },
  { key: "ec_windows_open_b", start: 712.25, dur: 6.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_windows_open.png" darken={0} kbPhase={2} /> },
  { key: "ec_windows_open_c", start: 718.97, dur: 6.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_windows_open.png" darken={0} kbPhase={3} /> },
  { key: "ec_shut_house_a", start: 725.2, dur: 7.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_shut_house.png" darken={0} kbPhase={1} /> },
  { key: "ec_shut_house_b", start: 733.04, dur: 7.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_shut_house.png" darken={0} kbPhase={2} /> },
  { key: "ec_shut_house_c", start: 740.88, dur: 7.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_shut_house.png" darken={0} kbPhase={3} /> },
  { key: "ec_shut_house_undefined", start: 748.72, dur: 7.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_shut_house.png" darken={0} kbPhase={4} /> },
  { key: "ec_stone_wall_a", start: 756.06, dur: 6.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_stone_wall.png" darken={0} kbPhase={1} /> },
  { key: "ec_stone_wall_b", start: 762.9, dur: 6.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_stone_wall.png" darken={0} kbPhase={2} /> },
  { key: "ec_stone_wall_c", start: 769.74, dur: 6.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_stone_wall.png" darken={0} kbPhase={3} /> },
  { key: "cmp_climate", start: 776.08, dur: 11.67, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Honest limit" items={["DRY heat → drops 15-20° (a wonder)","MUGGY heat → weak by day","Run it at night when air dries"]} accent={B} /> },
  { key: "ec_humid_a", start: 787.75, dur: 7.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_humid.png" darken={0} kbPhase={1} /> },
  { key: "ec_humid_b", start: 795.44, dur: 7.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_humid.png" darken={0} kbPhase={2} /> },
  { key: "ec_humid_c", start: 803.13, dur: 7.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_humid.png" darken={0} kbPhase={3} /> },
  { key: "ec_humid_undefined", start: 810.82, dur: 7.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_humid.png" darken={0} kbPhase={4} /> },
  { key: "ec_finger_test_a", start: 818.01, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_finger_test.png" darken={0} kbPhase={1} /> },
  { key: "ec_finger_test_b", start: 825.01, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_finger_test.png" darken={0} kbPhase={2} /> },
  { key: "ec_finger_test_c", start: 832.01, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_finger_test.png" darken={0} kbPhase={3} /> },
  { key: "ec_finger_test_undefined", start: 839.01, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_finger_test.png" darken={0} kbPhase={4} /> },
  { key: "ec_fan_a", start: 845.51, dur: 5.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_fan.png" darken={0} kbPhase={1} /> },
  { key: "ec_fan_b", start: 851.06, dur: 5.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_fan.png" darken={0} kbPhase={2} /> },
  { key: "ec_solar_fan_a", start: 856.11, dur: 9.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_solar_fan.png" darken={0} kbPhase={1} /> },
  { key: "ec_solar_fan_b", start: 865.92, dur: 9.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_solar_fan.png" darken={0} kbPhase={2} /> },
  { key: "ec_solar_fan_c", start: 875.73, dur: 9.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_solar_fan.png" darken={0} kbPhase={3} /> },
  { key: "ec_solar_fan_undefined", start: 885.54, dur: 9.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_solar_fan.png" darken={0} kbPhase={4} /> },
  { key: "ec_solar_fan_undefined", start: 895.35, dur: 9.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_solar_fan.png" darken={0} kbPhase={5} /> },
  { key: "ec_barrel_a", start: 904.68, dur: 6.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_barrel.png" darken={0} kbPhase={1} /> },
  { key: "ec_barrel_b", start: 910.75, dur: 6.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_barrel.png" darken={0} kbPhase={2} /> },
  { key: "cmp_mistakes", start: 916.32, dur: 26.21, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="4 mistakes to avoid" items={[{"text":"Never let the pad go dry","state":"done"},{"text":"Give the air a way out","state":"done"},{"text":"Keep it out of the sun","state":"done"},{"text":"Ease off on muggy days","state":"done"}]} eyebrow="Then it just works" accent="danger" hue="amber" image="img/cmp_mistakes_bg.png" /> },
  { key: "ec_dry_pad_a", start: 942.53, dur: 8.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_dry_pad.png" darken={0} kbPhase={1} /> },
  { key: "ec_dry_pad_b", start: 951.21, dur: 8.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_dry_pad.png" darken={0} kbPhase={2} /> },
  { key: "ec_dry_pad_c", start: 959.89, dur: 8.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_dry_pad.png" darken={0} kbPhase={3} /> },
  { key: "ec_dry_pad_undefined", start: 968.57, dur: 8.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_dry_pad.png" darken={0} kbPhase={4} /> },
  { key: "ec_dry_pad_undefined", start: 977.25, dur: 8.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_dry_pad.png" darken={0} kbPhase={5} /> },
  { key: "cmp_cost", start: 985.41, dur: 89.59, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Window AC","value":100,"display":"~$1000s","sub":"power + replace","tone":"danger"},{"label":"Wet pad cooler","value":1,"display":"$12 once","sub":"water off the roof","winner":true}]} eyebrow="Staying cool" title="Cost over 10 summers" unit="USD" accent="good" hue="amber" /> },
  { key: "ec_multi_a", start: 1075, dur: 6.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_multi.png" darken={0} kbPhase={1} /> },
  { key: "ec_multi_b", start: 1081.8, dur: 6.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_multi.png" darken={0} kbPhase={2} /> },
  { key: "ec_multi_c", start: 1088.6, dur: 6.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_multi.png" darken={0} kbPhase={3} /> },
  { key: "ec_multi_undefined", start: 1095.4, dur: 6.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_multi.png" darken={0} kbPhase={4} /> },
  { key: "ec_multi_undefined", start: 1102.2, dur: 6.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_multi.png" darken={0} kbPhase={5} /> },
  { key: "ec_wet_neck", start: 1108.52, dur: 6.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_wet_neck.png" darken={0} /> },
  { key: "ec_feet_water_a", start: 1114.3, dur: 6.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feet_water.png" darken={0} kbPhase={1} /> },
  { key: "ec_feet_water_b", start: 1121.22, dur: 6.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feet_water.png" darken={0} kbPhase={2} /> },
  { key: "ec_feet_water_c", start: 1128.14, dur: 6.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feet_water.png" darken={0} kbPhase={3} /> },
  { key: "ec_feet_water_undefined", start: 1135.06, dur: 6.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_feet_water.png" darken={0} kbPhase={4} /> },
  { key: "cmp_history", start: 1177.3, dur: 33.3, kind: "timeline", el: (d) => <SagaTimeline durationInFrames={d} events={[{"year":"1000 BC","label":"Persian wind-catchers & ice houses","accent":"amber"},{"year":"1800s","label":"farmhouse cooler rooms","accent":"amber"},{"year":"1900s","label":"the AC & the meter buried it","accent":"danger"}]} eyebrow="It is not new" title="3,000 years old" /> },
  { key: "ec_yakhchal_a", start: 1210.6, dur: 6.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_yakhchal.png" darken={0} kbPhase={1} /> },
  { key: "ec_yakhchal_b", start: 1216.91, dur: 6.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_yakhchal.png" darken={0} kbPhase={2} /> },
  { key: "ec_yakhchal_c", start: 1223.22, dur: 6.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_yakhchal.png" darken={0} kbPhase={3} /> },
  { key: "ec_cooler_room", start: 1229.04, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_cooler_room.png" darken={0} /> },
  { key: "ec_ac_unit", start: 1235.12, dur: 7.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_ac_unit.png" darken={0} /> },
  { key: "ec_meter_a", start: 1242.21, dur: 6.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_meter.png" darken={0} kbPhase={1} /> },
  { key: "ec_meter_b", start: 1248.25, dur: 6.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_meter.png" darken={0} kbPhase={2} /> },
  { key: "ec_shimmer_road", start: 1253.78, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ec_shimmer_road.png" darken={0} /> },
  { key: "ec_cool_pad2_a", start: 1257.48, dur: 8.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_cool_pad2.mp4" darken={0} clipDur={6} kbPhase={1} /> },
  { key: "ec_cool_pad2_b", start: 1265.65, dur: 8.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_cool_pad2.mp4" darken={0} clipDur={6} kbPhase={2} /> },
  { key: "ec_cool_pad2_c", start: 1273.82, dur: 8.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_cool_pad2.mp4" darken={0} clipDur={6} kbPhase={3} /> },
  { key: "ec_cool_pad2_undefined", start: 1281.99, dur: 8.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_cool_pad2.mp4" darken={0} clipDur={6} kbPhase={4} /> },
  { key: "ec_cool_pad2_undefined", start: 1290.16, dur: 8.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_cool_pad2.mp4" darken={0} clipDur={6} kbPhase={5} /> },
  { key: "cmp_next", start: 1297.82, dur: 29.32, kind: "nextvideo", el: (d) => <NextVideoEndcard durationInFrames={d} title="Keep a whole cellar of food cold all summer" kicker="Next time" sub="No ice, no power — the old way to store a season's food underground." /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ovp_22", start: 21.8, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="No AC · no fan · no power" accent="amber" pos="top" /> },
  { key: "ovp_114", start: 113.69, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Drying water = cooling" accent="cold" pos="bottom" /> },
  { key: "ov_151", start: 150.76, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} value={95} suffix="°" label="outside" corner="TR" accent="cold" /> },
  { key: "ov_157", start: 156.75, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} value={78} suffix="°" label="inside" corner="TL" accent="cold" /> },
  { key: "ovg_382", start: 381.98, dur: 4.2, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="📌 Free build guide — in the comments" accent="amber" pos="bottom" /> },
  { key: "ovp_739", start: 738.68, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Open at night · shut by day" accent="cold" pos="bottom" /> },
  { key: "ovp_776", start: 776.08, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Works best in DRY heat" accent="amber" pos="top" /> },
  { key: "ovg_661", start: 661.16, dur: 4.2, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="📌 Sizing table — in the free guide (comments)" accent="amber" pos="bottom" /> },
  { key: "ovp_943", start: 942.53, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="Keep the pad wet — always" accent="danger" pos="bottom" /> },
  { key: "ovx_1025", start: 1024.65, dur: 3.6, kind: "stattag", el: (d) => <StatTag durationInFrames={d} text="$1000s" label="AC over 10 yrs" corner="TR" accent="amber" /> },
  { key: "ovp_1269", start: 1268.58, dur: 3.4, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="No wire · no motor · no bill" accent="cold" pos="bottom" /> },
  { key: "ovg_1309", start: 1309.38, dur: 4.2, kind: "phrasetag", el: (d) => <PhraseTag durationInFrames={d} text="📌 Free guide + 90 old skills — in the comments" accent="amber" pos="bottom" /> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":21.8,"role":"popUp","vol":0.32},{"at":98.65,"role":"popUp","vol":0.32},{"at":113.69,"role":"popUp","vol":0.32},{"at":134.11,"role":"popUp","vol":0.32},{"at":150.76,"role":"popUp","vol":0.32},{"at":156.75,"role":"popUp","vol":0.32},{"at":280.15,"role":"popUp","vol":0.32},{"at":381.98,"role":"popUp","vol":0.32},{"at":563.21,"role":"popUp","vol":0.32},{"at":626.3,"role":"popUp","vol":0.32},{"at":661.16,"role":"popUp","vol":0.32},{"at":738.68,"role":"popUp","vol":0.32},{"at":776.08,"role":"popUp","vol":0.32},{"at":916.32,"role":"popUp","vol":0.32},{"at":942.53,"role":"popUp","vol":0.32},{"at":985.41,"role":"popUp","vol":0.32},{"at":1024.65,"role":"popUp","vol":0.32},{"at":1177.3,"role":"popUp","vol":0.32},{"at":1268.58,"role":"popUp","vol":0.32},{"at":1297.82,"role":"popUp","vol":0.32},{"at":1309.38,"role":"popUp","vol":0.32}];
