// cues_faros.gen.tsx — GENERADO por beatsheet.mjs desde faros.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/faros.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { DiagramBoard } from "./scenes/DiagramBoard";
import { AgedDoc } from "./scenes/AgedDoc";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { CalloutMark } from "./scenes/CalloutMark";
import { OxStatPop, OxMethodCard, OxRuleStrip, OxMaterialTag, OxBeforeAfter, OxSidePanel, OxPhotoStack, OxQuoteSplit } from "./overlays/OxCards";
import { ManualCard } from "./overlays/ManualCard";

const A = COLORS.accent;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "fa_night_road_driving", start: 0.07, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_night_road_driving.mp4" hue="amber" darken={0} /> },
  { key: "fa_pedestrian_dark_road", start: 2.28, dur: 2.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_pedestrian_dark_road.mp4" hue="red" darken={0} /> },
  { key: "fa_didnt_see_time", start: 4.14, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_didnt_see_time.mp4" hue="blue" darken={0} /> },
  { key: "fa_fill_didnt_see_time", start: 4.14, dur: 1.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_fill_didnt_see_time.png" hue="red" darken={0} /> },
  { key: "fa_slam_brakes", start: 10.2, dur: 1.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_slam_brakes.mp4" hue="amber" darken={0} /> },
  { key: "fa_fill_one_reason", start: 15.98, dur: 1.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_fill_one_reason.png" hue="red" darken={0} /> },
  { key: "fa_yellow_dim_headlight", start: 17.66, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_yellow_dim_headlight.png" hue="red" darken={0} /> },
  { key: "fa_half_light_road", start: 22, dur: 1.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_half_light_road.mp4" hue="blue" darken={0} /> },
  { key: "fa_old_yellow_headlight_day", start: 27.08, dur: 4.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_old_yellow_headlight_day.png" hue="amber" darken={0} /> },
  { key: "fa_driver_eyes_road_night", start: 30.85, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_driver_eyes_road_night.mp4" hue="red" darken={0} /> },
  { key: "fa_mechanic_garage_car", start: 34.42, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_mechanic_garage_car.mp4" hue="amber" darken={0} /> },
  { key: "fa_new_headlight_unit_price", start: 38.69, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_new_headlight_unit_price.mp4" hue="red" darken={0} /> },
  { key: "fa_expensive_quote_paper", start: 40.74, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_expensive_quote_paper.png" hue="blue" darken={0} /> },
  { key: "cmp_bars_st_41", start: 40.74, dur: 6.5, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Cambiar las dos ópticas","value":100,"display":"$$","tone":"danger"},{"label":"Restaurarlas vos mismo","value":3,"display":"café","winner":true}]} title="Lo que pagás de más" hue="red" /> },
  { key: "fa_old_mechanic_portrait", start: 43.32, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_old_mechanic_portrait.mp4" hue="amber" darken={0} /> },
  { key: "fa_mechanic_whisper_aside", start: 46.87, dur: 1.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_mechanic_whisper_aside.mp4" hue="red" darken={0} /> },
  { key: "fa_restore_headlight_curb", start: 51.05, dur: 1.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_restore_headlight_curb.mp4" hue="blue" darken={0} /> },
  { key: "cmp_callout_st_53", start: 52.64, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="20 min" image="real/fa_restore_headlight_curb.png" caption="En la vereda, por el precio de un café." accent="good" hue="blue" /> },
  { key: "fa_coffee_cup_price", start: 53.78, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_coffee_cup_price.mp4" hue="amber" darken={0} /> },
  { key: "fa_show_exactly_how", start: 57.29, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_show_exactly_how.mp4" hue="red" darken={0} /> },
  { key: "fa_yellow_cloudy_headlight2", start: 61.54, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_yellow_cloudy_headlight2.png" hue="blue" darken={0} /> },
  { key: "fa_headlight_cloud_inside", start: 64.56, dur: 1.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_headlight_cloud_inside.png" hue="amber" darken={0} /> },
  { key: "fa_headlight_night_no_see", start: 69.1, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_headlight_night_no_see.mp4" hue="red" darken={0} /> },
  { key: "fa_dealership_counter_quote", start: 73.36, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_dealership_counter_quote.mp4" hue="blue" darken={0} /> },
  { key: "fa_painful_price_estimate", start: 76.34, dur: 2.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_painful_price_estimate.mp4" hue="amber" darken={0} /> },
  { key: "fa_rag_glass_cleaner_rub", start: 78.23, dur: 4.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_rag_glass_cleaner_rub.mp4" hue="red" darken={0} /> },
  { key: "fa_no_change_headlight", start: 82.36, dur: 5.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_no_change_headlight.mp4" hue="blue" darken={0} /> },
  { key: "fa_fake_internet_tricks", start: 99.04, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_fake_internet_tricks.mp4" hue="amber" darken={0} /> },
  { key: "fa_bright_two_weeks", start: 105.12, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_bright_two_weeks.mp4" hue="red" darken={0} /> },
  { key: "fa_step_by_step_demo", start: 106.44, dur: 1.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_step_by_step_demo.mp4" hue="blue" darken={0} /> },
  { key: "fa_why_turns_yellow", start: 107.76, dur: 2.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_why_turns_yellow.mp4" hue="amber" darken={0} /> },
  { key: "fa_real_fix_coins", start: 110.25, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_real_fix_coins.mp4" hue="red" darken={0} /> },
  { key: "fa_toothpaste_bathroom_trick", start: 115.93, dur: 6.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_toothpaste_bathroom_trick.mp4" hue="blue" darken={0} /> },
  { key: "fa_skipped_step_secret", start: 122.09, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_skipped_step_secret.mp4" hue="amber" darken={0} /> },
  { key: "cmp_callout_st_122", start: 122.09, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="90%" image="real/fa_uv_clear_coat_spray.png" caption="Saltea el sellado: por eso el faro se vuelve amarillo." accent="danger" hue="blue" /> },
  { key: "fa_stay_until_end", start: 133.99, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_stay_until_end.mp4" hue="red" darken={0} /> },
  { key: "fa_safety_first_serious", start: 151.6, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_safety_first_serious.mp4" hue="blue" darken={0} /> },
  { key: "cmp_diagram_5_1", start: 155.01, dur: 4.48, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_5_1.mp4" pages={[{"image":"img/dg_fa_half_light.png","eyebrow":"La diferencia entre ver al que cruza y no verlo"}]} /> },
  { key: "cmp_bars_st_155", start: 155.01, dur: 6.5, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Faro amarillo y opaco","value":50,"display":"½","tone":"danger"},{"label":"Faro restaurado","value":100,"display":"100%","winner":true}]} title="Luz a la ruta" hue="red" /> },
  { key: "fa_pedestrian_crossing_night", start: 159.09, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_pedestrian_crossing_night.mp4" hue="red" darken={0} /> },
  { key: "fa_animal_pothole_road_night", start: 161.16, dur: 1.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_animal_pothole_road_night.mp4" hue="blue" darken={0} /> },
  { key: "fa_driving_blind_night", start: 164.4, dur: 6.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_driving_blind_night.mp4" hue="amber" darken={0} /> },
  { key: "fa_failed_inspection_headlight", start: 170.33, dur: 1.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_failed_inspection_headlight.mp4" hue="red" darken={0} /> },
  { key: "fa_expensive_optics_shelf", start: 185, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_expensive_optics_shelf.png" hue="blue" darken={0} /> },
  { key: "fa_shop_pushes_replace", start: 189.24, dur: 1.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_shop_pushes_replace.mp4" hue="amber" darken={0} /> },
  { key: "fa_fill_shop_business", start: 190.2, dur: 2.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_fill_shop_business.png" hue="red" darken={0} /> },
  { key: "fa_selling_new_plastic", start: 192.67, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_selling_new_plastic.png" hue="red" darken={0} /> },
  { key: "fa_fill_thats_business", start: 211, dur: 4.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_fill_thats_business.png" hue="red" darken={0} /> },
  { key: "fa_people_think_dirt", start: 219.29, dur: 1.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_people_think_dirt.mp4" hue="red" darken={0} /> },
  { key: "fa_rubbing_outside_useless", start: 222.64, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_rubbing_outside_useless.mp4" hue="blue" darken={0} /> },
  { key: "cmp_diagram_6_3", start: 227.44, dur: 2.12, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_6_3.mp4" pages={[{"image":"img/dg_fa_uv_layer.png","eyebrow":"El sol quema el barniz y el plástico se oxida"}]} /> },
  { key: "fa_polycarbonate_headlight", start: 229.16, dur: 2.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_polycarbonate_headlight.png" hue="red" darken={0} /> },
  { key: "fa_uv_clear_coat_factory", start: 233.6, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_uv_clear_coat_factory.mp4" hue="blue" darken={0} /> },
  { key: "fa_sun_uv_burning_coat", start: 237.68, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_sun_uv_burning_coat.mp4" hue="amber" darken={0} /> },
  { key: "fa_bare_plastic_oxidized", start: 247.89, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_bare_plastic_oxidized.png" hue="red" darken={0} /> },
  { key: "cmp_callout_st_248", start: 247.89, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="El sol" image="real/fa_bare_plastic_oxidized.png" caption="Quema la capa UV y el plástico queda desnudo y amarillo." accent="danger" hue="blue" /> },
  { key: "fa_micro_scratches_yellow", start: 254.04, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_micro_scratches_yellow.mp4" hue="blue" darken={0} /> },
  { key: "fa_problem_in_dead_layer", start: 266, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_problem_in_dead_layer.png" hue="amber" darken={0} /> },
  { key: "cmp_diagram_7_0", start: 271.88, dur: 4.81, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_7_0.mp4" pages={[{"image":"img/dg_fa_two_keys.png","eyebrow":"1. Sacar lo muerto · 2. Volver a sellar"}]} /> },
  { key: "cmp_aged_st_275", start: 274.95, dur: 6.5, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="LAS DOS CLAVES" lines={[{"text":"Sacar la capa muerta, lijándola"},{"text":"Volver a proteger, sellándolo"},{"text":"Sacar lo muerto y volver a proteger","mark":true}]} eyebrow="Si te falta una mitad, fallaste" hue="amber" /> },
  { key: "fa_sanding_off_dead_layer", start: 276.29, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_sanding_off_dead_layer.mp4" hue="blue" darken={0} /> },
  { key: "fa_most_forget_seal", start: 282.77, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_most_forget_seal.mp4" hue="amber" darken={0} /> },
  { key: "fa_new_protective_coat", start: 287.76, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_new_protective_coat.mp4" hue="red" darken={0} /> },
  { key: "fa_yellow_again_two_weeks", start: 294.05, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_yellow_again_two_weeks.mp4" hue="blue" darken={0} /> },
  { key: "fa_remove_protect_summary", start: 297.72, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_remove_protect_summary.mp4" hue="amber" darken={0} /> },
  { key: "fa_not_clean_restore", start: 314.48, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_not_clean_restore.mp4" hue="blue" darken={0} /> },
  { key: "cmp_bars_st_314", start: 314.48, dur: 6.5, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Frotar por afuera: no pasa nada","value":100,"display":"✗","tone":"danger"},{"label":"Sacar lo muerto y sellar","value":6,"display":"✓","winner":true}]} title="Limpiar vs restaurar" hue="amber" /> },
  { key: "fa_old_coat_new_coat", start: 318.52, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_old_coat_new_coat.mp4" hue="amber" darken={0} /> },
  { key: "cmp_process_st_325", start: 325.2, dur: 6.5, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Pasta de dientes","desc":"una buena cantidad en un trapo o cepillo"},{"title":"Frotá en círculos","desc":"con fuerza, mojando de vez en cuando"},{"title":"Enjuagá","desc":"se ve mejor, pero es solo un parche"}]} eyebrow="Algo que tenés en el baño" title="El parche de urgencia" hue="amber" /> },
  { key: "fa_toothpaste_white_tube", start: 330.55, dur: 1.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/fa_toothpaste_white_tube.png" hue="amber" darken={0} /> },
  { key: "cmp_diagram_9_1", start: 338.19, dur: 6.48, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_9_1.mp4" pages={[{"image":"img/dg_fa_toothpaste.png","eyebrow":"Un abrasivo finito que lija suave la capa de arriba"}]} /> },
  { key: "fa_abrasive_particles_polish", start: 344.27, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_abrasive_particles_polish.mp4" hue="blue" darken={0} /> },
  { key: "fa_rag_toothpaste_headlight", start: 352.59, dur: 2.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_rag_toothpaste_headlight.mp4" hue="amber" darken={0} /> },
  { key: "fa_old_toothbrush_scrub", start: 360.72, dur: 2.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_old_toothbrush_scrub.mp4" hue="red" darken={0} /> },
  { key: "fa_rag_turning_yellow", start: 371.21, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_rag_turning_yellow.mp4" hue="blue" darken={0} /> },
  { key: "fa_rinse_dry_better", start: 378.92, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_rinse_dry_better.mp4" hue="amber" darken={0} /> },
  { key: "fa_toothpaste_just_patch", start: 385.87, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_toothpaste_just_patch.mp4" hue="red" darken={0} /> },
  { key: "fa_pass_inspection_tomorrow", start: 388.95, dur: 2.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_pass_inspection_tomorrow.mp4" hue="blue" darken={0} /> },
  { key: "fa_opaque_again_weeks", start: 401.08, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_opaque_again_weeks.mp4" hue="amber" darken={0} /> },
  { key: "fa_real_fix_coming", start: 408.28, dur: 5.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_real_fix_coming.mp4" hue="red" darken={0} /> },
  { key: "cmp_process_st_413", start: 413.33, dur: 6.5, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Tapá y lijá al agua","desc":"400, 600, 1000 y 2000, siempre mojado"},{"title":"Pulí","desc":"con pasta pulidora hasta dejarlo transparente"},{"title":"Sellá","desc":"barniz UV: el paso que el 90% saltea"}]} eyebrow="Tres pasos, por monedas" title="El arreglo que dura años" hue="blue" /> },
  { key: "cmp_oxstack_11_0", start: 418.29, dur: 2.15, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/fa_wet_sandpaper_grits.png","real/fa_polish_compound_tube.png","real/fa_uv_clear_coat_spray.png"]} captions={["Lijas al agua","Pasta pulidora","Barniz UV"]} accent="blue" /> },
  { key: "fa_masking_tape_around", start: 428.49, dur: 3.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_masking_tape_around.mp4" hue="red" darken={0} /> },
  { key: "fa_protect_car_paint", start: 435.39, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_protect_car_paint.mp4" hue="blue" darken={0} /> },
  { key: "fa_tape_whole_edge", start: 438, dur: 4.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_tape_whole_edge.mp4" hue="amber" darken={0} /> },
  { key: "cmp_diagram_12_0", start: 442.11, dur: 4.38, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_12_0.mp4" pages={[{"image":"img/dg_fa_grits.png","eyebrow":"400 · 600 · 1000 · 2000 — siempre con agua"}]} /> },
  { key: "fa_always_wet_never_dry", start: 446.09, dur: 3.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_always_wet_never_dry.mp4" hue="red" darken={0} /> },
  { key: "fa_sand_400_grit", start: 455.26, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_sand_400_grit.mp4" hue="blue" darken={0} /> },
  { key: "fa_headlight_white_milky", start: 459.72, dur: 4.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_headlight_white_milky.mp4" hue="amber" darken={0} /> },
  { key: "fa_dead_layer_coming_off", start: 472.57, dur: 4.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_dead_layer_coming_off.mp4" hue="red" darken={0} /> },
  { key: "fa_sand_600_grit", start: 477.1, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_sand_600_grit.mp4" hue="blue" darken={0} /> },
  { key: "fa_finer_grit_1000", start: 483.86, dur: 2.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_finer_grit_1000.mp4" hue="amber" darken={0} /> },
  { key: "fa_finest_grit_2000", start: 486.15, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_finest_grit_2000.mp4" hue="red" darken={0} /> },
  { key: "fa_smooth_even_no_scratch", start: 497.48, dur: 5.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_smooth_even_no_scratch.mp4" hue="blue" darken={0} /> },
  { key: "fa_polishing_headlight_cloth", start: 513.43, dur: 5.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_polishing_headlight_cloth.mp4" hue="blue" darken={0} /> },
  { key: "fa_plastic_turns_clear", start: 518.68, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_plastic_turns_clear.mp4" hue="amber" darken={0} /> },
  { key: "fa_healthy_plastic_appears", start: 529.46, dur: 5.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_healthy_plastic_appears.mp4" hue="red" darken={0} /> },
  { key: "fa_headlight_looks_perfect", start: 534.65, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_headlight_looks_perfect.mp4" hue="blue" darken={0} /> },
  { key: "fa_drill_polish_disc", start: 544.8, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_drill_polish_disc.mp4" hue="amber" darken={0} /> },
  { key: "fa_drill_faster_even", start: 549.42, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_drill_faster_even.mp4" hue="red" darken={0} /> },
  { key: "fa_drill_overheat_warning", start: 567.26, dur: 3.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_drill_overheat_warning.mp4" hue="blue" darken={0} /> },
  { key: "fa_slow_wet_always", start: 570.91, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_slow_wet_always.mp4" hue="amber" darken={0} /> },
  { key: "fa_celebrate_too_soon", start: 573.93, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_celebrate_too_soon.mp4" hue="amber" darken={0} /> },
  { key: "fa_biggest_mistake_teaser", start: 578.46, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_biggest_mistake_teaser.mp4" hue="red" darken={0} /> },
  { key: "cmp_diagram_16_0", start: 595.89, dur: 5.14, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_16_0.mp4" pages={[{"image":"img/dg_fa_manual.png","eyebrow":"El Manual de Reparaciones Caseras"}]} /> },
  { key: "fa_first_time_missed_grit", start: 600.63, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_first_time_missed_grit.mp4" hue="blue" darken={0} /> },
  { key: "fa_seal_secret_next", start: 624.05, dur: 6.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_seal_secret_next.mp4" hue="amber" darken={0} /> },
  { key: "fa_bare_plastic_oxidizes_fast", start: 647.99, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_bare_plastic_oxidizes_fast.mp4" hue="amber" darken={0} /> },
  { key: "fa_worse_than_start", start: 659.44, dur: 6.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_worse_than_start.mp4" hue="red" darken={0} /> },
  { key: "fa_what_failed_no_seal", start: 668.88, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_what_failed_no_seal.mp4" hue="blue" darken={0} /> },
  { key: "cmp_diagram_17_4", start: 671.88, dur: 7.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_17_4.mp4" pages={[{"image":"img/dg_fa_seal_options.png","eyebrow":"Barniz UV en aerosol · barniz auto · cera"}]} /> },
  { key: "fa_spray_thin_coats", start: 688.16, dur: 4.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_spray_thin_coats.mp4" hue="blue" darken={0} /> },
  { key: "cmp_callout_st_692", start: 692.47, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Años" image="real/fa_uv_clear_coat_spray.png" caption="El barniz UV es el protector solar del faro: dura años." accent="cold" hue="blue" /> },
  { key: "fa_lasts_years_recommend", start: 694.87, dur: 3.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_lasts_years_recommend.mp4" hue="amber" darken={0} /> },
  { key: "fa_car_wax_homemade", start: 705.34, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_car_wax_homemade.mp4" hue="red" darken={0} /> },
  { key: "fa_never_leave_bare", start: 719.08, dur: 5.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_never_leave_bare.mp4" hue="blue" darken={0} /> },
  { key: "cmp_aged_st_724", start: 724.16, dur: 6.5, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="EL ERROR FATAL" lines={[{"text":"Lijar, pulir y dejarlo brillante"},{"text":"Y guardar todo SIN sellar"},{"text":"El sol lo quema de nuevo en dos semanas","mark":true}]} eyebrow="Por qué a la gente no le dura" hue="red" /> },
  { key: "cmp_diagram_18_0", start: 734.08, dur: 7.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_18_0.mp4" pages={[{"image":"img/dg_fa_mistake.png","eyebrow":"El sol lo quema de nuevo en dos semanas"}]} /> },
  { key: "fa_first_sunny_weekend", start: 748.06, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_first_sunny_weekend.mp4" hue="blue" darken={0} /> },
  { key: "fa_stripped_last_defense", start: 755.21, dur: 5.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_stripped_last_defense.mp4" hue="amber" darken={0} /> },
  { key: "fa_skipped_important_half", start: 764.13, dur: 1.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_skipped_important_half.mp4" hue="red" darken={0} /> },
  { key: "cmp_callout_st_765", start: 764.85, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="La mitad" image="real/fa_skipped_important_half.png" caption="Sin sellar, te salteás la mitad más importante." accent="danger" hue="blue" /> },
  { key: "fa_repellent_instant_clear", start: 778.2, dur: 4.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_repellent_instant_clear.mp4" hue="blue" darken={0} /> },
  { key: "fa_repellent_melts_plastic", start: 785.05, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_repellent_melts_plastic.mp4" hue="amber" darken={0} /> },
  { key: "cmp_callout_st_785", start: 785.05, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Veneno" image="real/fa_insect_repellent_can.png" caption="El repelente derrite y deforma el plástico del faro." accent="danger" hue="blue" /> },
  { key: "fa_sticky_deformed_worse", start: 791.3, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_sticky_deformed_worse.mp4" hue="red" darken={0} /> },
  { key: "fa_oil_shine_one_day", start: 801.98, dur: 2.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_oil_shine_one_day.mp4" hue="amber" darken={0} /> },
  { key: "fa_only_real_way", start: 810.06, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_only_real_way.mp4" hue="red" darken={0} /> },
  { key: "fa_cracked_headlight_real", start: 814.4, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_cracked_headlight_real.mp4" hue="blue" darken={0} /> },
  { key: "fa_moisture_inside_fog", start: 816.62, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_moisture_inside_fog.mp4" hue="amber" darken={0} /> },
  { key: "fa_water_inside_not_sanding", start: 822.16, dur: 4.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_water_inside_not_sanding.mp4" hue="red" darken={0} /> },
  { key: "fa_deep_pitted_plastic", start: 831.48, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_deep_pitted_plastic.mp4" hue="blue" darken={0} /> },
  { key: "cmp_diagram_20_4", start: 841.44, dur: 1.72, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_20_4.mp4" pages={[{"image":"img/dg_fa_99.png","eyebrow":"Esos se arreglan perfecto con lo de hoy"}]} /> },
  { key: "fa_most_just_surface", start: 842.76, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_most_just_surface.mp4" hue="red" darken={0} /> },
  { key: "fa_trim_bumper_mirrors", start: 854.82, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_trim_bumper_mirrors.mp4" hue="red" darken={0} /> },
  { key: "fa_same_sun_burned", start: 866.28, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_same_sun_burned.mp4" hue="blue" darken={0} /> },
  { key: "cmp_callout_st_870", start: 869.62, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Mismo arreglo" image="real/fa_deep_black_returns.png" caption="Los plásticos negros se reviven con el mismo principio." accent="good" hue="blue" /> },
  { key: "fa_oil_rag_black_back", start: 873.34, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_oil_rag_black_back.mp4" hue="amber" darken={0} /> },
  { key: "fa_deep_black_returns", start: 898.1, dur: 2.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_deep_black_returns.mp4" hue="blue" darken={0} /> },
  { key: "cmp_chips_22_1", start: 920.9, dur: 7.2, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} image="real/fa_shop_upsell_bg.png" title="Por qué no te lo cuentan" chips={["Al taller le conviene","venderte las ópticas nuevas","no restaurarte las que tenés"]} hue="red" /> },
  { key: "cmp_splitlist_22_2", start: 928.29, dur: 7.2, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Los 40 arreglos, divididos así" items={["Madera y metal que no mueren","Plagas por centavos","Goteras, humedad y moho","Arreglos del hogar y el auto"]} accent={A} /> },
  { key: "cmp_checklist_23_0", start: 947.08, dur: 7.2, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="El plan contra el faro amarillo" items={[{"text":"No es mugre: es plástico oxidado por el sol","state":"done"},{"text":"Urgencia: pasta de dientes (parche)","state":"done"},{"text":"Tapá, lijá con agua 400 → 600 → 1000 → 2000","state":"done"},{"text":"Pulí hasta dejarlo transparente","state":"done"},{"text":"Sellá con barniz UV. Nunca repelente","state":"done"}]} hue="blue" /> },
  { key: "cmp_checklist_st_959", start: 958.9, dur: 6.5, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="El plan completo" items={[{"text":"No es mugre: es plástico oxidado por el sol","state":"done"},{"text":"Urgencia: pasta de dientes (parche)","state":"done"},{"text":"Tapá y lijá al agua 400 → 2000","state":"done"},{"text":"Pulí hasta dejarlo transparente","state":"done"},{"text":"Sellá con barniz UV. Nunca repelente","state":"done"}]} hue="blue" /> },
  { key: "fa_two_clear_headlights", start: 986.4, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_two_clear_headlights.mp4" hue="amber" darken={0} /> },
  { key: "cmp_diagram_24_0", start: 1024.84, dur: 7.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_24_0.mp4" pages={[{"image":"img/dg_fa_stack.png","eyebrow":"Con los planos y las medidas exactas"}]} /> },
  { key: "fa_cheaper_than_one_optic", start: 1035.44, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_cheaper_than_one_optic.mp4" hue="red" darken={0} /> },
  { key: "cmp_callout_st_1035", start: 1035.44, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="< 1 óptica" image="real/fa_expensive_optics_shelf.png" caption="El manual cuesta menos que una sola óptica nueva." accent="good" hue="blue" /> },
  { key: "fa_look_headlights_today", start: 1048.05, dur: 6.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_look_headlights_today.mp4" hue="blue" darken={0} /> },
  { key: "fa_give_back_sight", start: 1054.68, dur: 1.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_give_back_sight.mp4" hue="amber" darken={0} /> },
  { key: "fa_paint_scratches_car", start: 1069.36, dur: 6.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_paint_scratches_car.mp4" hue="red" darken={0} /> },
  { key: "fa_scratch_removed_clear", start: 1075.54, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/fa_scratch_removed_clear.mp4" hue="blue" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_oxquote_50", start: 49.92, dur: 5.2, kind: "oxquote", el: (d) => <OxQuoteSplit durationInFrames={d} quote="No cambies nada. Eso se arregla en la vereda, *en veinte minutos, por el precio de un café*." image="real/fa_old_mechanic_portrait.png" attribution="Un mecánico viejo" side="right" accent="amber" /> },
  { key: "ov_oxbefore_62", start: 61.54, dur: 4.4, kind: "oxbefore", el: (d) => <OxBeforeAfter durationInFrames={d} before="real/fa_yellow_cloudy_headlight2.png" after="real/fa_two_clear_headlights.png" accent="green" /> },
  { key: "burst_62", start: 61.54, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/fa_yellow_cloudy_headlight2.png","real/fa_headlight_cloud_inside.png","real/fa_old_yellow_headlight_day.png"]} captions={["Amarillos","Opacos","Como con nube"]} accent="red" /> },
  { key: "ov_oxstat_122", start: 122.09, dur: 4.2, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={90} label="saltea el sellado: por eso el faro se vuelve amarillo" suffix=" %" glyph="🛡️" accent="red" /> },
  { key: "ov_oxstat_155", start: 155.01, dur: 4.2, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={50} label="menos de luz a la ruta: manejás con los ojos tapados" suffix=" %" glyph="🚗" accent="red" /> },
  { key: "ov_oxside_170", start: 170.33, dur: 5, kind: "oxside", el: (d) => <OxSidePanel durationInFrames={d} image="real/fa_failed_inspection_headlight.png" title="Lo que te cuesta" lines={["Seguridad: ves la mitad de la ruta","Verificación: te frenan el auto","Bolsillo: una óptica nueva es una fortuna"]} side="right" accent="red" /> },
  { key: "ov_oxrule_226", start: 225.72, dur: 4.4, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="No es mugre. Es la *capa de plástico oxidada por el sol*." accent="amber" /> },
  { key: "ov_oxstat_242", start: 242.4, dur: 4, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={100} label="el sol come la capa UV y el plástico queda desnudo" suffix=" %" glyph="☀️" accent="red" /> },
  { key: "ov_oxside_276", start: 276.29, dur: 5.2, kind: "oxside", el: (d) => <OxSidePanel durationInFrames={d} image="real/fa_sanding_off_dead_layer.png" title="Las dos claves" lines={["Sacar la capa muerta, lijándola","Volver a sellar con una capa nueva","Si te falta una mitad, fallaste"]} side="right" accent="amber" /> },
  { key: "ov_oxrule_314", start: 314.48, dur: 4.6, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="El faro amarillo no se *limpia*. Se *restaura*." accent="amber" /> },
  { key: "ov_oxmethod_325", start: 325.2, dur: 4.6, kind: "oxmethod", el: (d) => <OxMethodCard durationInFrames={d} num="01" title="Pasta de dientes" chips={["Trapo o cepillo","Frotar en círculos","Es un parche"]} cost="lo del baño" accent="blue" /> },
  { key: "ov_oxmethod_413", start: 413.33, dur: 4.8, kind: "oxmethod", el: (d) => <OxMethodCard durationInFrames={d} num="02" title="Lijar al agua y sellar" chips={["Tapar alrededor","Lijar 400→2000","Pulir y sellar"]} cost="monedas" accent="amber" /> },
  { key: "burst_413", start: 413.33, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/fa_toothpaste_white_tube.png","real/fa_wet_sandpaper_grits.png","real/fa_uv_clear_coat_spray.png"]} captions={["Pasta (parche)","Lijas al agua","Barniz UV"]} accent="blue" /> },
  { key: "ov_oxrule_446", start: 446.09, dur: 4.4, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="Siempre con *agua*, nunca en *seco*. De gruesa a fina." accent="blue" /> },
  { key: "ov_oxstat_455", start: 455.26, dur: 4, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={400} label="se arranca con 400, después 600, 1000 y 2000" glyph="🧽" accent="amber" /> },
  { key: "ov_oxtag_505", start: 505.37, dur: 4, kind: "oxtag", el: (d) => <OxMaterialTag durationInFrames={d} name="La pasta pulidora" what="Saca lo opaco y aparece el plástico cristalino" side="left" accent="blue" /> },
  { key: "ov_oxtag_538", start: 538.24, dur: 4, kind: "oxtag", el: (d) => <OxMaterialTag durationInFrames={d} name="El taladro" what="Cinco minutos en vez de veinte, pero despacio y mojado" side="right" accent="amber" /> },
  { key: "ov_manualcard_611", start: 611.22, dur: 6, kind: "manualcard", el: (d) => <ManualCard durationInFrames={d} image="real/manual_cover.png" title="Manual de Reparaciones Caseras" desc="Los 40 arreglos de $1 a $5 del hogar, con los planos y las medidas exactas." accent="amber" /> },
  { key: "ov_oxmethod_680", start: 679.71, dur: 4.8, kind: "oxmethod", el: (d) => <OxMethodCard durationInFrames={d} num="03" title="El sellado UV" chips={["Aerosol UV","Barniz de auto","Cera (parche)"]} cost="el secreto" accent="amber" /> },
  { key: "ov_oxrule_734", start: 734.08, dur: 4.6, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="El error: dejarlo brillante y *no sellarlo*. El sol lo quema de nuevo." accent="red" /> },
  { key: "ov_oxrule_785", start: 785.05, dur: 4.4, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="Repelente, *nunca*: derrite y deforma el plástico." accent="red" /> },
  { key: "burst_855", start: 854.82, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/fa_faded_black_trim.png","real/fa_trim_bumper_mirrors.png","real/fa_deep_black_returns.png"]} captions={["Plásticos grises","Molduras, espejos","Negro de vuelta"]} accent="amber" /> },
  { key: "burst_962", start: 962.23, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/fa_sand_400_grit.png","real/fa_sand_600_grit.png","real/fa_finest_grit_2000.png"]} captions={["400 grueso","600 y 1000","2000 fino"]} accent="amber" /> },
  { key: "ov_manualcard_1038", start: 1038.12, dur: 6, kind: "manualcard", el: (d) => <ManualCard durationInFrames={d} image="real/manual_cover.png" title="Manual de Reparaciones Caseras" desc="Los 40 arreglos, incluido el sellado de los faros." chip="Accedé en la descripción" accent="amber" /> },
];
