// cues_meriendas.gen.tsx — GENERADO por beatsheet.mjs desde meriendas.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/meriendas.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { JourneyCanvas } from "./scenes/JourneyCanvas";
import { FloatingInsert } from "./scenes/FloatingInsert";
import { KineticHeadline } from "./scenes/KineticHeadline";
import { AgedDoc } from "./scenes/AgedDoc";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { RuleNumberScene } from "./scenes/RuleNumberScene";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { InfiniteZoom } from "./scenes/InfiniteZoom";
import { FoodTeaseCards } from "./scenes/FoodTeaseCards";

const G = COLORS.good, B = COLORS.cold, A = COLORS.accent, D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "intro_0", start: 0.1, dur: 8.46, kind: "teasecards", el: (d) => <FoodTeaseCards durationInFrames={d} cards={[{"src":"broll/rc_tortas_fritas.mp4","label":"Tortas fritas"},{"src":"broll/mer_arroz_leche.mp4","label":"Arroz con leche"},{"src":"broll/rc_alfajores.mp4","label":"Alfajores de maicena"},{"src":"broll/rc_flan.mp4","label":"Flan casero"},{"src":"broll/mer_chocolate_caliente.mp4","label":"Chocolate espeso"},{"src":"broll/rc_mazamorra.mp4","label":"Mazamorra"},{"src":"broll/mer_dulce_leche_olla.mp4","label":"Dulce de leche"}]} eyebrow="Algunas merecen volver…" title="¿Cuántas te acordás?" /> },
  { key: "intro_1", start: 8.56, dur: 4.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_harina_manos.mp4" hue="red" kicker="Un sábado a la tarde" /> },
  { key: "intro_2", start: 12.77, dur: 3.09, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_cuchara_madera.mp4" side="right" hue="blue" /> },
  { key: "intro_3", start: 15.86, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_abuela_cocina.mp4" hue="amber" /> },
  { key: "intro_4", start: 20.38, dur: 5.27, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_abuela_manos.mp4" words={parseQuote("Estas manos ya no son las de antes, pero todavía se *acuerdan*.")} hue="red" /> },
  { key: "intro_5", start: 25.65, dur: 3.31, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_horno_abrir.mp4" side="left" hue="blue" /> },
  { key: "intro_6", start: 28.96, dur: 4.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_amasar_pan.mp4" hue="amber" /> },
  { key: "intro_7", start: 33.17, dur: 6.69, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={82} label="años — y me acuerdo de todo" eyebrow="La que te habla" hue="red" /> },
  { key: "intro_8", start: 39.86, dur: 7.36, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="img/ai_abuela_retrato.png" side="right" hue="blue" /> },
  { key: "intro_9", start: 47.22, dur: 8.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_cocina_vintage.mp4" hue="amber" /> },
  { key: "intro_10", start: 55.25, dur: 6.69, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"Algo"},{"t":"se"},{"t":"está"},{"t":"perdiendo","hl":true}]} eyebrow="Hoy quiero contarte" hue="red" bg="image" image="img/ai_abuela_cocina2.png" /> },
  { key: "intro_11", start: 61.94, dur: 7.36, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_pan_recien.mp4" side="left" hue="blue" /> },
  { key: "intro_12", start: 69.3, dur: 8.7, kind: "infzoom", el: (d) => <InfiniteZoom durationInFrames={d} images={[{"src":"broll/mer_cocina_vintage.mp4"},{"src":"img/ai_mesa_70s.png"},{"src":"broll/mer_abuela_cocina.mp4"}]} /> },
  { key: "intro_13", start: 78, dur: 10.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_abuela_sonrie.mp4" hue="red" /> },
  { key: "riqueza_0", start: 88.04, dur: 12.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_mesa_70s.png" hue="red" /> },
  { key: "riqueza_1", start: 100.45, dur: 5.84, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="En casa no sobraba la plata" lines={[{"text":"Éramos muchos. Cada peso se cuidaba."},{"text":"Pero nunca faltó algo rico a media tarde."}]} hue="blue" /> },
  { key: "riqueza_2", start: 106.29, dur: 7.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_familia_70s.mp4" hue="amber" /> },
  { key: "riqueza_3", start: 113.59, dur: 5.35, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Con esto alcanzaba" items={["Harina","Azúcar","Un poco de leche","Manos que sabían"]} accent={G} /> },
  { key: "riqueza_4", start: 118.94, dur: 7.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_abuela_delantal.mp4" hue="blue" /> },
  { key: "riqueza_5", start: 126.24, dur: 12.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_manos_viejas2.mp4" hue="amber" /> },
  { key: "riqueza_6", start: 138.65, dur: 6.08, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"El bolsillo","value":2},{"label":"Las manos","value":10}]} title="Dónde estaba la riqueza" hue="red" /> },
  { key: "riqueza_7", start: 144.73, dur: 5.11, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_ventana_luz.mp4" words={parseQuote("Comida que alimentaba el cuerpo y el *alma*.")} hue="blue" /> },
  { key: "riqueza_8", start: 149.84, dur: 7.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_ventana_luz.mp4" hue="amber" /> },
  { key: "s01_0", start: 157.16, dur: 5.28, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="01" title="Pan con manteca y azúcar" hue="blue" /> },
  { key: "s01_1", start: 162.44, dur: 5.53, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_pan_rebanada.mp4" side="right" hue="amber" /> },
  { key: "s01_2", start: 167.97, dur: 12.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_manteca_pan.mp4" hue="red" /> },
  { key: "s01_3", start: 180.8, dur: 7.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_pan_manteca_azucar2.png" hue="blue" kicker="Azúcar, la que había" /> },
  { key: "s01_4", start: 188.35, dur: 12.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_azucar_cae.mp4" hue="amber" /> },
  { key: "s01_5", start: 201.18, dur: 6.04, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Pan con azúcar" items={[{"text":"Pan del día","state":"done"},{"text":"Manteca","state":"done"},{"text":"Azúcar","state":"done"},{"text":"Una gota de canela","state":"done"}]} hue="red" /> },
  { key: "s01_6", start: 207.22, dur: 7.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_pan_azucar.png" hue="blue" /> },
  { key: "s01_7", start: 214.77, dur: 5.27, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_canela.mp4" words={parseQuote("No se perdió el pan con azúcar. Se perdió que lo hicieran *para vos*.")} hue="amber" /> },
  { key: "s02_0", start: 220.04, dur: 4.43, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="02" title="Tortas fritas" hue="amber" /> },
  { key: "s02_1", start: 224.47, dur: 10.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_lluvia_ventana.mp4" hue="red" kicker="Día de lluvia" /> },
  { key: "s02_2", start: 235.23, dur: 6.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_masa_amasar.mp4" hue="blue" /> },
  { key: "s02_3", start: 241.56, dur: 6.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_masa_estirar.mp4" hue="amber" /> },
  { key: "s02_4", start: 247.89, dur: 10.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_fry_pan.mp4" hue="red" /> },
  { key: "s02_5", start: 258.65, dur: 6.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_freir_masa.mp4" hue="blue" /> },
  { key: "s02_6", start: 264.98, dur: 10.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_tortas_fritas.mp4" hue="amber" kicker="Con azúcar arriba" /> },
  { key: "s02_7", start: 275.74, dur: 6.12, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Amasar","image":"broll/mer_masa_amasar.mp4"},{"title":"Estirar y tajear","image":"broll/mer_masa_estirar.mp4"},{"title":"A la grasa","image":"broll/mer_freir_masa.mp4"},{"title":"Azúcar arriba","image":"broll/rc_tortas_fritas.mp4"}]} title="Cómo salían" hue="red" /> },
  { key: "s02_8", start: 281.86, dur: 5.06, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Lo que pedía la torta frita" items={[{"text":"Harina y grasa","state":"done"},{"text":"Agua tibia, sal","state":"done"},{"text":"La lluvia","state":"done"},{"text":"La abuela","state":"done"},{"text":"Paciencia","state":"done"}]} hue="blue" /> },
  { key: "s02_9", start: 286.92, dur: 4.44, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ai_tortas_lluvia.png" words={parseQuote("*Estilo casero*, dice la caja. Como si el estilo se metiera en una bolsa.")} hue="amber" /> },
  { key: "s03_0", start: 291.36, dur: 4.67, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="03" title="Pan casero" hue="red" /> },
  { key: "s03_1", start: 296.03, dur: 6.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_amasar_pan.mp4" hue="blue" /> },
  { key: "s03_2", start: 302.7, dur: 11.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_masa_bowl.mp4" hue="amber" /> },
  { key: "s03_3", start: 314.05, dur: 6.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_pan_horneado.mp4" hue="red" /> },
  { key: "s03_4", start: 320.72, dur: 11.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_pan_recien.mp4" hue="blue" kicker="Ese olor no se olvida" /> },
  { key: "s03_5", start: 332.07, dur: 4.67, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_pan_cortar2.mp4" words={parseQuote("Un olor que si lo sentís una vez, no te lo olvidás *nunca*.")} hue="amber" /> },
  { key: "s03_6", start: 336.74, dur: 4.89, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_pan_cortar2.mp4" side="left" hue="red" /> },
  { key: "s03_7", start: 341.63, dur: 5.57, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Antes","value":180},{"label":"Hoy","value":5}]} title="Una mañana entera en la cocina" unit="min" hue="blue" /> },
  { key: "s04_0", start: 347.2, dur: 5.65, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="04" title="Alfajores de maicena" hue="blue" /> },
  { key: "s04_1", start: 352.85, dur: 8.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_galletas_bandeja.mp4" hue="amber" /> },
  { key: "s04_2", start: 360.93, dur: 7, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="broll/rc_alfajores.mp4" annotations={[{"kind":"circle","x":50,"y":30,"label":"Tapita de maicena"},{"kind":"circle","x":50,"y":60,"label":"Dulce de leche"},{"kind":"circle","x":18,"y":55,"label":"Coco rallado"}]} caption="Tratar la masa con respeto" hue="red" /> },
  { key: "s04_3", start: 367.93, dur: 8.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_coco_rallado.jpg" hue="blue" kicker="Bordes de coco" /> },
  { key: "s04_4", start: 376.01, dur: 13.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_alfajor_corte.png" hue="amber" /> },
  { key: "s04_5", start: 389.74, dur: 8.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_dulce_leche_cuch.mp4" hue="red" /> },
  { key: "s04_6", start: 397.82, dur: 5.64, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ai_alfajor_corte.png" words={parseQuote("El de la fábrica nunca va a tener lo que tenía el de mi tía: sus *manos*.")} hue="blue" /> },
  { key: "s05_0", start: 403.46, dur: 7.61, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="05" title="Arroz con leche" hue="amber" /> },
  { key: "s05_1", start: 411.07, dur: 7.97, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_leche_verter.mp4" side="right" hue="red" /> },
  { key: "s05_2", start: 419.04, dur: 18.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_arroz_leche.mp4" hue="blue" /> },
  { key: "s05_3", start: 437.52, dur: 10.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_olla_revolver.mp4" hue="amber" kicker="Revolver y revolver" /> },
  { key: "s05_4", start: 448.39, dur: 10.51, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Al fuego","image":"broll/mer_olla_vieja.mp4"},{"title":"Revolver","image":"broll/mer_cuchara_revolver2.mp4"},{"title":"Canela","image":"broll/mer_canela_rama.jpg"},{"title":"Enfriar","image":"broll/rc_arroz_leche.mp4"}]} title="Arroz con leche" hue="red" /> },
  { key: "s05_5", start: 458.9, dur: 18.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_arroz_leche.mp4" hue="blue" /> },
  { key: "s05_6", start: 477.38, dur: 7.62, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_cuchara_revolver2.mp4" words={parseQuote("Revolver era la excusa para que alguien se quedara en la cocina *con vos*.")} hue="amber" /> },
  { key: "s06_0", start: 485, dur: 2.53, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="06" title="Las galletitas de la abuela" hue="red" /> },
  { key: "s06_1", start: 487.53, dur: 6.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_nina_abuela.mp4" hue="blue" /> },
  { key: "s06_2", start: 493.67, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_cortar_galletas.mp4" hue="amber" kicker="Con un vaso dado vuelta" /> },
  { key: "s06_3", start: 497.28, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_nino_cocina.mp4" hue="red" /> },
  { key: "s06_4", start: 500.89, dur: 6.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_horno_vidrio.mp4" hue="blue" /> },
  { key: "s06_5", start: 507.03, dur: 2.51, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_horno_vidrio.mp4" words={parseQuote("Se perdieron porque ya nadie le enseña a un chico a cocinar *a su lado*.")} hue="amber" /> },
  { key: "s07_0", start: 509.54, dur: 4.59, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="07" title="Mate cocido y tostadas" hue="blue" /> },
  { key: "s07_1", start: 514.13, dur: 11.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_mate.mp4" hue="amber" /> },
  { key: "s07_2", start: 525.27, dur: 4.81, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_te_servir.mp4" side="left" hue="red" /> },
  { key: "s07_3", start: 530.08, dur: 6.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_tostada_manteca.mp4" hue="blue" /> },
  { key: "s07_4", start: 536.64, dur: 11.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_mesa_familia.mp4" hue="amber" kicker="Todos alrededor" /> },
  { key: "s07_5", start: 547.78, dur: 4.81, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Lo que de verdad se murió" items={["El ritual","La mesa compartida","Mirarse a la cara"]} accent={B} cross /> },
  { key: "s07_6", start: 552.59, dur: 6.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_mate_bizcochos.png" hue="blue" /> },
  { key: "s08_0", start: 559.14, dur: 4.76, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="08" title="Budín de pan" hue="amber" /> },
  { key: "s08_1", start: 563.9, dur: 6.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_pan_duro.jpg" hue="red" kicker="Nada se tiraba" /> },
  { key: "s08_2", start: 570.71, dur: 6.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_caramelo_dorado.mp4" hue="blue" /> },
  { key: "s08_3", start: 577.52, dur: 6.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_pasas_uva.jpg" hue="amber" /> },
  { key: "s08_4", start: 584.33, dur: 11.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_budin_molde.png" hue="red" /> },
  { key: "s08_5", start: 595.9, dur: 11.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_budin_pan.mp4" hue="blue" /> },
  { key: "s08_6", start: 607.47, dur: 5.44, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Nada se desperdicia" lines={[{"text":"El pan duro no se tiraba jamás."},{"text":"El domingo era budín de pan."}]} image="broll/mer_budin_pan.mp4" hue="amber" /> },
  { key: "s08_7", start: 612.91, dur: 4.76, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_budin_pan.mp4" words={parseQuote("Todo se transforma en algo bueno si le ponés *cariño*.")} hue="red" /> },
  { key: "s09_0", start: 617.67, dur: 7.47, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="09" title="Bizcochitos de grasa" hue="red" /> },
  { key: "s09_1", start: 625.14, dur: 18.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_bizcochitos.mp4" hue="blue" /> },
  { key: "s09_2", start: 643.29, dur: 10.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_bizcochos.mp4" hue="amber" /> },
  { key: "s09_3", start: 653.97, dur: 7.83, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_miel.mp4" side="right" hue="red" /> },
  { key: "s09_4", start: 661.8, dur: 7.48, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_bizcochos.mp4" words={parseQuote("Hacerlos era el punto. No el comerlos. El *hacerlos*.")} hue="blue" /> },
  { key: "s10_0", start: 669.28, dur: 5.34, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="10" title="Leche con vainilla" hue="blue" /> },
  { key: "s10_1", start: 674.62, dur: 12.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_leche_tibia.mp4" hue="amber" /> },
  { key: "s10_2", start: 687.6, dur: 7.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_azucar_quemada.mp4" hue="red" kicker="Azúcar quemada arriba" /> },
  { key: "s10_3", start: 695.24, dur: 12.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_leche_vainilla.png" hue="blue" /> },
  { key: "s10_4", start: 708.22, dur: 7.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_manos_taza.mp4" hue="amber" /> },
  { key: "s10_5", start: 715.86, dur: 5.34, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_manos_taza.mp4" words={parseQuote("Antes le dábamos una taza tibia y la falda de la madre. ¿Qué cura *más*?")} hue="red" /> },
  { key: "s11_0", start: 721.2, dur: 5.01, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="11" title="La torta de la abuela" hue="amber" /> },
  { key: "s11_1", start: 726.21, dur: 12.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_torta_amarilla.mp4" hue="red" /> },
  { key: "s11_2", start: 738.39, dur: 7.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_huevos_batir.mp4" hue="blue" /> },
  { key: "s11_3", start: 745.55, dur: 7.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_limon_rallar.mp4" hue="amber" kicker="Ralladura de limón" /> },
  { key: "s11_4", start: 752.71, dur: 12.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_torta_abuela.png" hue="red" /> },
  { key: "s11_5", start: 764.89, dur: 4.78, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="«Lo que la masa pida»" image="broll/mer_torta_porcion.mp4" caption="Sin balanza. Sin números. Solo sus manos." hue="blue" /> },
  { key: "s11_6", start: 769.67, dur: 7.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_torta_porcion.mp4" hue="amber" /> },
  { key: "s11_7", start: 776.83, dur: 5.73, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Recetas que nunca se escribieron" lines={[{"text":"Vivían solo en la memoria de las manos."},{"text":"Murieron con sus dueñas, en silencio."}]} hue="red" /> },
  { key: "s12_0", start: 782.56, dur: 5.67, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="12" title="Pan con tomate" hue="red" /> },
  { key: "s12_1", start: 788.23, dur: 13.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_tomate_huerta.mp4" hue="blue" /> },
  { key: "s12_2", start: 802.01, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_pan_tomate.mp4" hue="amber" /> },
  { key: "s12_3", start: 810.11, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_pan_tomate.mp4" hue="red" kicker="Aceite y sal gruesa" /> },
  { key: "s12_4", start: 818.21, dur: 5.67, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_fruta_canasta.mp4" words={parseQuote("Todo se ve más lindo ahora y sabe a *menos*.")} hue="blue" /> },
  { key: "s12_5", start: 823.88, dur: 8.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_fruta_canasta.mp4" hue="amber" /> },
  { key: "s13_0", start: 832, dur: 5.46, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="13" title="Masitas secas" hue="blue" /> },
  { key: "s13_1", start: 837.46, dur: 13.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_masitas.mp4" hue="amber" /> },
  { key: "s13_2", start: 850.72, dur: 7.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_masitas_surtido.mp4" hue="red" /> },
  { key: "s13_3", start: 858.52, dur: 7.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_nuez.jpg" hue="blue" /> },
  { key: "s13_4", start: 866.32, dur: 7.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_azucar_impalpable.jpg" hue="amber" kicker="Azúcar impalpable" /> },
  { key: "s13_5", start: 874.12, dur: 5.72, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Recibir con la bandeja" items={["Con dulce","Con nuez","Con azúcar"]} accent={A} /> },
  { key: "s13_6", start: 879.84, dur: 5.45, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_mesa_mantel.mp4" words={parseQuote("Recibir con algo hecho por vos era decir: *valés* mis manos.")} hue="blue" /> },
  { key: "s14_0", start: 885.29, dur: 4.75, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="14" title="Dulce de leche casero" hue="amber" /> },
  { key: "s14_1", start: 890.04, dur: 6.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_leche_jarra.mp4" hue="red" /> },
  { key: "s14_2", start: 896.83, dur: 11.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_dulce_leche.mp4" hue="blue" /> },
  { key: "s14_3", start: 908.38, dur: 6.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_dulce_leche_olla.mp4" hue="amber" kicker="Una hora revolviendo" /> },
  { key: "s14_4", start: 915.17, dur: 5.43, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Dulce de leche casero" items={[{"text":"Leche","state":"done"},{"text":"Azúcar","state":"done"},{"text":"Una hora de brazo","state":"done"},{"text":"El fondo tostado de la olla","state":"done"}]} hue="red" /> },
  { key: "s14_5", start: 920.6, dur: 11.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_frasco_dulce.jpg" hue="blue" /> },
  { key: "s14_6", start: 932.15, dur: 4.76, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_dulce_leche_olla.mp4" words={parseQuote("La pelea por el fondo de la olla: uno de mis recuerdos más *felices*.")} hue="amber" /> },
  { key: "s15_0", start: 936.91, dur: 6.26, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="15" title="Sándwich de miga tostado" hue="red" /> },
  { key: "s15_1", start: 943.17, dur: 15.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_sandwich_miga.png" hue="blue" /> },
  { key: "s15_2", start: 958.37, dur: 8.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_sandwich_plancha.mp4" hue="amber" /> },
  { key: "s15_3", start: 967.31, dur: 5.96, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} bg="image" image="broll/mer_sandwich_plancha.mp4" title="Casi todo lo rico nacía de…" chips={["no tirar nada","aprovechar","estirar"]} hue="amber" /> },
  { key: "s15_4", start: 973.27, dur: 7.45, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Antes","value":1},{"label":"Hoy","value":9}]} title="Comida que se tira por semana" hue="blue" /> },
  { key: "s15_5", start: 980.72, dur: 6.27, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ai_sandwich_miga.png" words={parseQuote("La abundancia nos volvió *perezosos* en la cocina.")} hue="amber" /> },
  { key: "s16_0", start: 986.99, dur: 6.39, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="16" title="Manzana asada" hue="blue" /> },
  { key: "s16_1", start: 993.38, dur: 9.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_manzana_horno.mp4" hue="amber" /> },
  { key: "s16_2", start: 1002.5, dur: 15.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_manzana_asada.mp4" hue="red" /> },
  { key: "s16_3", start: 1018.01, dur: 9.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_manzana_asada.mp4" hue="blue" kicker="Un juguito en el fondo" /> },
  { key: "s16_4", start: 1027.13, dur: 6.69, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Por qué se perdió" items={["Demasiado trabajo, dicen","El postre tiene que ser de chocolate","La fruta quedó relegada"]} accent={D} cross /> },
  { key: "s16_5", start: 1033.82, dur: 6.38, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_canela_rama.jpg" words={parseQuote("Dejamos de mirar la fruta como un *postre*.")} hue="red" /> },
  { key: "s17_0", start: 1040.2, dur: 5.9, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="17" title="Panqueques con dulce de leche" hue="amber" /> },
  { key: "s17_1", start: 1046.1, dur: 6.18, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_panqueque_sarten.mp4" side="left" hue="red" /> },
  { key: "s17_2", start: 1052.28, dur: 14.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_panqueque_voltear.mp4" hue="blue" kicker="Dada vuelta por el aire" /> },
  { key: "s17_3", start: 1066.62, dur: 14.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_panqueques.mp4" hue="amber" /> },
  { key: "s17_4", start: 1080.96, dur: 5.62, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="«La del perro»" image="broll/mer_panqueque_sarten.mp4" caption="La primera siempre salía fea. Era parte del rito." hue="red" /> },
  { key: "s17_5", start: 1086.58, dur: 5.91, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/rc_panqueques.mp4" words={parseQuote("Sin esa primera fea, no es lo *mismo*.")} hue="blue" /> },
  { key: "s18_0", start: 1092.49, dur: 7, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="18" title="El vigilante" hue="red" /> },
  { key: "s18_1", start: 1099.49, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_queso_fresco.jpg" hue="blue" /> },
  { key: "s18_2", start: 1109.49, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_queso_cortar.mp4" hue="amber" /> },
  { key: "s18_3", start: 1119.49, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_membrillo.jpg" hue="red" kicker="Queso y dulce" /> },
  { key: "s18_4", start: 1129.49, dur: 8.66, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="broll/rc_vigilante.mp4" annotations={[{"kind":"circle","x":32,"y":45,"label":"Queso fresco del tambo"},{"kind":"circle","x":68,"y":50,"label":"Dulce de membrillo"}]} caption="El postre de los días de calor" hue="blue" /> },
  { key: "s18_5", start: 1138.15, dur: 6.99, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/rc_vigilante.mp4" words={parseQuote("Cuando se apaga un ingrediente, se va todo un *cuarto* de recuerdos.")} hue="amber" /> },
  { key: "s19_0", start: 1145.14, dur: 5.24, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="19" title="Gelatina con frutas" hue="blue" /> },
  { key: "s19_1", start: 1150.38, dur: 12.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_gelatina.mp4" hue="amber" /> },
  { key: "s19_2", start: 1163.09, dur: 12.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_gelatina.mp4" hue="red" /> },
  { key: "s19_3", start: 1175.8, dur: 7.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_gelatina_fruta.jpg" hue="blue" /> },
  { key: "s19_4", start: 1183.28, dur: 7.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_durazno.jpg" hue="amber" /> },
  { key: "s19_5", start: 1190.76, dur: 5.24, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/rc_gelatina.mp4" words={parseQuote("Antes una gelatina que temblaba alcanzaba para una *fiesta*.")} hue="red" /> },
  { key: "s20_0", start: 1196, dur: 5, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="20" title="Chocolate caliente espeso" hue="amber" /> },
  { key: "s20_1", start: 1201, dur: 12.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_chocolate_caliente.mp4" hue="red" /> },
  { key: "s20_2", start: 1213.14, dur: 7.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_chocolate_taza2.png" hue="blue" kicker="Casi le parabas la cuchara" /> },
  { key: "s20_3", start: 1220.28, dur: 7.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_mojar_pan_choco.mp4" hue="amber" /> },
  { key: "s20_4", start: 1227.42, dur: 12.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_chocolate.mp4" hue="red" /> },
  { key: "s20_5", start: 1239.56, dur: 5.71, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Chocolate de verdad" items={[{"text":"Chocolate o cacao","state":"done"},{"text":"Leche, no agua","state":"done"},{"text":"Una punta de almidón","state":"done"},{"text":"Pan duro para mojar","state":"done"}]} hue="blue" /> },
  { key: "s20_6", start: 1245.27, dur: 5.73, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Ese pan duro era oro" lines={[{"text":"Lo mojabas y chorreaba chocolate."},{"text":"Y hoy lo tiramos."}]} image="broll/mer_pan_partir_mano.mp4" hue="amber" /> },
  { key: "s21_0", start: 1251, dur: 5.61, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="21" title="Mazamorra" hue="red" /> },
  { key: "s21_1", start: 1256.61, dur: 8.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_maiz_blanco.jpg" hue="blue" /> },
  { key: "s21_2", start: 1264.63, dur: 13.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_olla_hervir.mp4" hue="amber" /> },
  { key: "s21_3", start: 1278.26, dur: 8.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_mazamorra2.png" hue="red" kicker="Maíz blanco, horas al fuego" /> },
  { key: "s21_4", start: 1286.28, dur: 13.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_mazamorra.mp4" hue="blue" /> },
  { key: "s21_5", start: 1299.91, dur: 6.41, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Cruzó siglos" lines={[{"text":"Mi bisabuela, mi abuela, mi madre…"},{"text":"Mis nietos ni saben qué es."}]} image="broll/mer_campo_casa.mp4" hue="amber" /> },
  { key: "s21_6", start: 1306.32, dur: 5.62, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_humo_chimenea.mp4" words={parseQuote("Se pierde un pedazo de *quiénes somos*. Si no la cuento, se va conmigo.")} hue="red" /> },
  { key: "s22_0", start: 1311.94, dur: 7.42, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="22" title="Buñuelos de manzana" hue="blue" /> },
  { key: "s22_1", start: 1319.36, dur: 10.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_fruta_canasta.mp4" hue="amber" /> },
  { key: "s22_2", start: 1329.96, dur: 18.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_bunuelos.mp4" hue="red" /> },
  { key: "s22_3", start: 1347.98, dur: 10.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_bunuelos.mp4" hue="blue" kicker="Chisporroteo del domingo" /> },
  { key: "s22_4", start: 1358.58, dur: 7.77, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Aprovechar lo que sobraba" items={["Manzanas muy blandas","Masa liviana","A la sartén"]} accent={A} /> },
  { key: "s22_5", start: 1366.35, dur: 7.42, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_bunuelos.mp4" words={parseQuote("Se llevó una música que toda la casa *reconocía*.")} hue="red" /> },
  { key: "s22_6", start: 1373.77, dur: 10.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_cocina_humo.mp4" hue="blue" /> },
  { key: "s23_0", start: 1384.36, dur: 7.34, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="23" title="Pan con ajo y aceite" hue="amber" /> },
  { key: "s23_1", start: 1391.7, dur: 17.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_pan_ajo.mp4" hue="red" /> },
  { key: "s23_2", start: 1409.53, dur: 10.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_pan_ajo.mp4" hue="blue" /> },
  { key: "s23_3", start: 1420.02, dur: 10.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_aceite_verter2.mp4" hue="amber" kicker="Un hilo de aceite" /> },
  { key: "s23_4", start: 1430.51, dur: 7.34, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_pan_ajo.mp4" words={parseQuote("Antes comíamos con el cuerpo, no con la *cabeza*.")} hue="red" /> },
  { key: "s23_5", start: 1437.85, dur: 7.7, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_aceite_oliva.mp4" side="right" hue="blue" /> },
  { key: "s24_0", start: 1445.55, dur: 6.48, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="24" title="Flan casero" hue="red" /> },
  { key: "s24_1", start: 1452.03, dur: 9.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_huevos_batir.mp4" hue="blue" /> },
  { key: "s24_2", start: 1461.28, dur: 15.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_flan_caramelo.mp4" hue="amber" /> },
  { key: "s24_3", start: 1477.01, dur: 9.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_flan.mp4" hue="red" kicker="Caramelo chorreando" /> },
  { key: "s24_4", start: 1486.26, dur: 15.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_flan_temblar.mp4" hue="blue" /> },
  { key: "s24_5", start: 1501.99, dur: 6.49, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/rc_flan.mp4" words={parseQuote("Lo bueno casi siempre lleva tiempo. Y el tiempo es lo que ya no *damos*.")} hue="amber" /> },
  { key: "s25_0", start: 1508.48, dur: 8.46, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="25" title="El polvorón" hue="blue" /> },
  { key: "s25_1", start: 1516.94, dur: 20.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rc_polvoron.mp4" hue="amber" /> },
  { key: "s25_2", start: 1537.49, dur: 8.86, kind: "float", el: (d) => <FloatingInsert durationInFrames={d} src="broll/mer_polvoron.mp4" side="left" hue="red" /> },
  { key: "s25_3", start: 1546.35, dur: 12.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_galleta_morder.mp4" hue="blue" kicker="Se deshacía en la boca" /> },
  { key: "s25_4", start: 1558.44, dur: 12.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_lata_galletas.jpg" hue="amber" /> },
  { key: "s25_5", start: 1570.53, dur: 8.45, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_lata_galletas.jpg" words={parseQuote("Lo descartable nos cambió hasta la forma de *querer* las cosas.")} hue="red" /> },
  { key: "s26_0", start: 1578.98, dur: 5.1, kind: "headline", el: (d) => <KineticHeadline durationInFrames={d} tokens={[{"t":"La"},{"t":"merienda"},{"t":"compartida","hl":true}]} eyebrow="Y la más importante" hue="amber" bg="image" image="broll/mer_mesa_compartir.mp4" /> },
  { key: "s26_1", start: 1584.08, dur: 12.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ai_mesa_compartida2.png" hue="red" /> },
  { key: "s26_2", start: 1597.07, dur: 7.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_mesa_compartir.mp4" hue="blue" /> },
  { key: "s26_3", start: 1604.71, dur: 12.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_nieta_reir.mp4" hue="amber" /> },
  { key: "s26_4", start: 1617.7, dur: 7.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_velas_torta.mp4" hue="red" /> },
  { key: "s26_5", start: 1625.34, dur: 5.35, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_abuela_nietos.mp4" words={parseQuote("La comida era la excusa. Lo importante era la mesa *llena*.")} hue="blue" /> },
  { key: "s26_6", start: 1630.69, dur: 13.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_abuela_nietos.mp4" hue="amber" /> },
  { key: "cierre_0", start: 1643.7, dur: 5.45, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_ventana_luz.mp4" words={parseQuote("No te cuento esto para que sientas pena. Todavía estás a *tiempo*.")} hue="red" /> },
  { key: "cierre_1", start: 1649.15, dur: 13.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_mesa_atardecer.mp4" hue="blue" /> },
  { key: "cierre_2", start: 1662.39, dur: 12.46, kind: "journey", el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="Esta tarde, o el domingo" title="Andá a la cocina" waypoints={[{"x":0,"y":0,"z":0,"image":"broll/mer_abuela_delantal.mp4","label":"Aunque salga fea","num":"1","dwell":2.6,"travel":1.6},{"x":1.2,"y":-0.4,"z":0.3,"image":"broll/mer_olla_revolver.mp4","label":"Revolvé un arroz","num":"2","dwell":2.6,"travel":1.6},{"x":2.4,"y":0.3,"z":-0.2,"image":"broll/mer_mesa_compartir.mp4","label":"Sentate con alguien","num":"3","dwell":2.6,"travel":1.6},{"x":3.6,"y":-0.2,"z":0.2,"image":"broll/mer_manos_taza.mp4","label":"Sin teléfono","num":"4","dwell":2.8,"travel":1.6},{"x":4.8,"y":0.1,"z":0,"image":"img/ai_mesa_compartida2.png","label":"Mirándola a los ojos","num":"5","dwell":3,"travel":1.4}]} /> },
  { key: "cierre_3", start: 1674.85, dur: 6.23, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="Cociná algo para alguien hoy" lines={[{"text":"El cariño se pasa de mano en mano,"},{"text":"mientras todavía estamos."}]} hue="red" /> },
  { key: "cierre_4", start: 1681.08, dur: 13.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_manos_rezar.mp4" hue="blue" /> },
  { key: "cierre_5", start: 1694.32, dur: 5.45, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="broll/mer_abuela_sonrie.mp4" words={parseQuote("Comé algo hecho en casa, por favor. Hacelo *por mí*.")} hue="amber" /> },
  { key: "cierre_6", start: 1699.77, dur: 13.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/mer_abuela_sonrie.mp4" hue="red" /> },
];

export const REFRAME: { start: number; end: number }[] = [];
