// cues_replantar.gen.tsx — GENERADO por beatsheet.mjs desde replantar.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/replantar.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { MistakeCard } from "./scenes/MistakeCard";
import { RegrowSplit } from "./scenes/RegrowSplit";
import { LieList } from "./scenes/LieList";
import { NumberCard } from "./scenes/NumberCard";
import { GridReveal } from "./scenes/GridReveal";
import { GrowthTimeline } from "./scenes/GrowthTimeline";
import { KineticLine } from "./scenes/KineticLine";
import { FloatCards } from "./scenes/FloatCards";

const D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "bh1_rpl_cl_scraps_returned_soil", start: 2.05, dur: 6.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_scraps_returned_soil.mp4" darken={0} /> },
  { key: "bh2_rpl_tr_scraps_lined_up", start: 8.43, dur: 6.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_scraps_lined_up.mp4" darken={0} /> },
  { key: "bh3_rpl_h1_harvest_hands_tomatoes", start: 14.9, dur: 2.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_harvest_hands_tomatoes.mp4" darken={0} /> },
  { key: "bh4_rpl_i2_chopping_lettuce_board", start: 17.13, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "bh5_rpl_h1_green_onion_roots_macro", start: 20.55, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_green_onion_roots_macro.mp4" darken={0} /> },
  { key: "bh6_rpl_i1_scallion_root_ends", start: 22.55, dur: 3.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_root_ends.mp4" darken={0} /> },
  { key: "bh7_rpl_i9_planting_clove_soil", start: 25.64, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "bh8_rpl_i9_garlic_rows_field", start: 28.55, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "bh9_rpl_h1_pineapple_crown_top", start: 31.55, dur: 1.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_pineapple_crown_top.mp4" darken={0} /> },
  { key: "bh10_rpl_tr_money_saved_jar", start: 33.05, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_money_saved_jar.mp4" darken={0} /> },
  { key: "bh11_rpl_tr_scraps_lined_up", start: 35.55, dur: 4.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_scraps_lined_up.mp4" darken={0} /> },
  { key: "bh12_rpl_cl_scraps_returned_soil", start: 39.5, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_scraps_returned_soil.mp4" darken={0} /> },
  { key: "cmp_alive", start: 43.55, dur: 6.79, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/cmp_alive_bg.png" impact="sigue VIVA." setup="Eso que llamas basura..." impactAccent="good" hitAt={1.2} boom={0} darken={0.4} /> },
  { key: "cmp_tally", start: 50.34, dur: 10.48, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={16} suffix=" plantas · 0€" label="comida nueva, gratis, desde tu basura" eyebrow="Lo que vas a sacar hoy" accent="good" hue="amber" /> },
  { key: "bh16_rpl_i1_scallion_regrow_timelapse", start: 60.82, dur: 11.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "bh17_rpl_h1_hands_planting_soil", start: 71.4, dur: 2.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_hands_planting_soil.mp4" darken={0} /> },
  { key: "b1_rpl_h2_wilting_plant_cloudy", start: 73.59, dur: 4.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "cmp_teaser11", start: 77.14, dur: 7.86, kind: "regrow", el: (d) => <RegrowSplit durationInFrames={d} leftImage="img/cmp_teaser11_l.png" rightImage="img/cmp_teaser11_r.png" number="11" title="Una sola te da una bolsa de comida" leftLabel="Basura" rightLabel="Cosecha" hue="amber" /> },
  { key: "b3_rpl_h2_wilting_plant_cloudy", start: 85, dur: 1.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b4_rpl_h2_seedling_emerging", start: 86, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b5_rpl_h2_pepper_plant_fruit", start: 87.9, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b6_rpl_h2_pepper_seedlings", start: 91.5, dur: 1.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "cmp_loop_error", start: 92.48, dur: 7.16, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="!" title="El error que mata la mitad de tus plantas" desc="Casi todos lo cometen, y creen que no funcionó." eyebrow="EN ESTE VIDEO" image="img/cmp_loop_error_bg.png" /> },
  { key: "b8_rpl_h2_pepper_plant_fruit", start: 99.64, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b9_rpl_h2_wilting_plant_cloudy", start: 103.5, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b10_rpl_h2_pepper_seedlings", start: 106.96, dur: 1.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "b11_rpl_h2_pepper_plant_fruit", start: 108.5, dur: 1.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "b12_rpl_h2_seedling_emerging", start: 109.54, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b13_rpl_h2_wilting_plant_cloudy", start: 113.5, dur: 2.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_wilting_plant_cloudy.mp4" darken={0} /> },
  { key: "b14_rpl_h2_pepper_seedlings", start: 115.71, dur: 2.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_seedlings.mp4" darken={0} /> },
  { key: "b15_rpl_h2_seedling_emerging", start: 117.5, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_seedling_emerging.mp4" darken={0} /> },
  { key: "b16_rpl_h2_pepper_plant_fruit", start: 120.09, dur: 0.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h2_pepper_plant_fruit.mp4" darken={0} /> },
  { key: "bh19_rpl_h1_fresh_veg_spread_table", start: 120.14, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_h1_fresh_veg_spread_table.mp4" darken={0} /> },
  { key: "b17_rpl_tr_greenhouse_interior", start: 154.5, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_greenhouse_interior.mp4" darken={0} /> },
  { key: "b18_rpl_tr_sun_kitchen_window", start: 159.5, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_sun_kitchen_window.mp4" darken={0} /> },
  { key: "cmp_savings_bars", start: 162.08, dur: 3.42, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Comprándolas todo el año","value":160,"display":"~160€","tone":"danger"},{"label":"Replantando los restos","value":0,"display":"0€","winner":true}]} eyebrow="Lo que se va al año" title="Hierbas y verduras de hoja" unit="EUR" accent="good" hue="amber" /> },
  { key: "cmp_growth", start: 165.5, dur: 8.71, kind: "growthtimeline", el: (d) => <GrowthTimeline durationInFrames={d} stages={[{"label":"Un resto"},{"label":"En agua","sub":"días"},{"label":"Raíces"},{"label":"A la tierra"},{"label":"Cosecha"}]} title="De un resto a una planta" bg="broll/rpl_err_pale_wilting_cutting.mp4" /> },
  { key: "b23_rpl_tr_sun_kitchen_window", start: 174.21, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_sun_kitchen_window.mp4" darken={0} /> },
  { key: "b24_rpl_tr_scraps_lined_up", start: 176.59, dur: 5.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_scraps_lined_up.mp4" darken={0} /> },
  { key: "b25_rpl_tr_roots_timelapse", start: 181.5, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_roots_timelapse.mp4" darken={0} /> },
  { key: "cmp_nonecesitas", start: 183.5, dur: 8, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="No necesitas nada de esto" items={["Semillas caras","Luces de cultivo","Invernadero"]} accent={D} cross /> },
  { key: "cmp_solo", start: 191.5, dur: 7.14, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Solo necesitas" items={[{"text":"Un vaso de agua","state":"done"},{"text":"Un puñado de tierra","state":"done"},{"text":"Una ventana con luz","state":"done"}]} eyebrow="En tu cocina" accent="good" hue="amber" image="img/cmp_solo_bg.png" /> },
  { key: "b31_rpl_tr_money_saved_jar", start: 198.64, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_money_saved_jar.mp4" darken={0} /> },
  { key: "b32_rpl_tr_greenhouse_interior", start: 201.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_greenhouse_interior.mp4" darken={0} /> },
  { key: "b33_rpl_tr_sun_kitchen_window", start: 205.5, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_tr_sun_kitchen_window.mp4" darken={0} /> },
  { key: "cmp_num_1", start: 209.15, dur: 3.35, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="1" name="Cebolla de verdeo" bg="broll/rpl_i1_scallion_root_ends.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_cebolla", start: 212.5, dur: 9.14, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_cebolla_bg.png" annotations={[{"kind":"circle","x":0.5,"y":0.78,"w":0.18,"label":"Raíces al agua","color":"good"},{"kind":"arrow","x":0.5,"y":0.32,"fromX":0.78,"fromY":0.12,"label":"Dejá 3 dedos de tallo","color":"amber"},{"kind":"circle","x":0.5,"y":0.9,"w":0.4,"label":"1 dedo de agua","color":"accent"}]} eyebrow="Cómo se hace" hue="amber" /> },
  { key: "b38_rpl_i1_chopped_over_food", start: 221.64, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_chopped_over_food.mp4" darken={0} /> },
  { key: "b39_rpl_i1_slicing_scallions_macro", start: 224.08, dur: 4.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_slicing_scallions_macro.mp4" darken={0} /> },
  { key: "b40_rpl_i1_chopped_over_food", start: 228.56, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_chopped_over_food.mp4" darken={0} /> },
  { key: "b41_rpl_i1_scallion_root_ends", start: 233.5, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_root_ends.mp4" darken={0} /> },
  { key: "b42_rpl_i1_scallion_regrow_timelapse", start: 235.6, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "b43_rpl_i1_snipping_scissors", start: 238.5, dur: 2.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_snipping_scissors.mp4" darken={0} /> },
  { key: "b44_rpl_i1_slicing_scallions_macro", start: 240.58, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_slicing_scallions_macro.mp4" darken={0} /> },
  { key: "b45_rpl_i1_scallion_root_ends", start: 243.59, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_root_ends.mp4" darken={0} /> },
  { key: "b46_rpl_i1_scallion_regrow_timelapse", start: 246.37, dur: 6.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "b47_rpl_i1_snipping_scissors", start: 252.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_snipping_scissors.mp4" darken={0} /> },
  { key: "b48_rpl_i1_chopped_over_food", start: 256.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_chopped_over_food.mp4" darken={0} /> },
  { key: "b49_rpl_i1_slicing_scallions_macro", start: 259.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_slicing_scallions_macro.mp4" darken={0} /> },
  { key: "b50_rpl_i1_scallion_root_ends", start: 263.5, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_root_ends.mp4" darken={0} /> },
  { key: "b51_rpl_i1_scallion_regrow_timelapse", start: 266.96, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_scallion_regrow_timelapse.mp4" darken={0} /> },
  { key: "b52_rpl_i1_snipping_scissors", start: 269.64, dur: 4.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_snipping_scissors.mp4" darken={0} /> },
  { key: "b53_rpl_i1_chopped_over_food", start: 273.17, dur: 2.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i1_chopped_over_food.mp4" darken={0} /> },
  { key: "cmp_num_2", start: 275.5, dur: 3.52, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="2" name="Lechuga" bg="broll/rpl_i2_lettuce_dish_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_s2_bars", start: 279.02, dur: 9.48, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Comprada","value":140,"display":"~140€/año","tone":"danger"},{"label":"Replantada","value":0,"display":"0€","winner":true}]} eyebrow="Comprarla todo el año vs replantarla" title="Verdura de hoja" unit="EUR" accent="good" hue="amber" /> },
  { key: "b57_rpl_i2_chopping_lettuce_board", start: 288.5, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b58_rpl_i2_lettuce_dish_water", start: 291.17, dur: 2.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b59_rpl_i2_lettuce_water_window", start: 293.5, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "b60_rpl_i2_harvest_lettuce_hand", start: 297.64, dur: 6.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_harvest_lettuce_hand.mp4" darken={0} /> },
  { key: "b61_rpl_i2_chopping_lettuce_board", start: 303.5, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b62_rpl_i2_lettuce_dish_water", start: 306.08, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b63_rpl_i2_lettuce_water_window", start: 308.5, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "b64_rpl_i2_harvest_lettuce_hand", start: 311.77, dur: 2.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_harvest_lettuce_hand.mp4" darken={0} /> },
  { key: "b65_rpl_i2_chopping_lettuce_board", start: 313.82, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b66_rpl_i2_lettuce_dish_water", start: 315.92, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b67_rpl_i2_lettuce_water_window", start: 321.82, dur: 3.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "b68_rpl_i2_harvest_lettuce_hand", start: 324.33, dur: 3.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_harvest_lettuce_hand.mp4" darken={0} /> },
  { key: "b69_rpl_i2_chopping_lettuce_board", start: 327.51, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_chopping_lettuce_board.mp4" darken={0} /> },
  { key: "b70_rpl_i2_lettuce_dish_water", start: 330.49, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_dish_water.mp4" darken={0} /> },
  { key: "b71_rpl_i2_lettuce_water_window", start: 334.39, dur: 5.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i2_lettuce_water_window.mp4" darken={0} /> },
  { key: "cmp_num_3", start: 339.64, dur: 3.94, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="3" name="Apio" bg="broll/rpl_i3_celery_base_glass.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_s3_proc", start: 343.58, dur: 8.46, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"El resto, en un dedo de agua"},{"title":"Cambiá el agua cada 2-3 días"},{"title":"Con raíces, pasalo a la tierra"}]} eyebrow="Sirve para casi todas" title="El método base" accent="good" hue="amber" /> },
  { key: "b75_rpl_i3_celery_base_glass", start: 352.04, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "b76_rpl_i3_celery_regrow_timelapse", start: 354.57, dur: 8.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_regrow_timelapse.mp4" darken={0} /> },
  { key: "b77_rpl_i3_celery_water_window", start: 362.58, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_water_window.mp4" darken={0} /> },
  { key: "b78_rpl_i3_celery_base_glass", start: 365.58, dur: 3.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "b79_rpl_i3_celery_water_window", start: 368.29, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_water_window.mp4" darken={0} /> },
  { key: "b80_rpl_i3_celery_regrow_timelapse", start: 371.5, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_regrow_timelapse.mp4" darken={0} /> },
  { key: "b81_rpl_i3_celery_base_glass", start: 374.4, dur: 7.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i3_celery_base_glass.mp4" darken={0} /> },
  { key: "cmp_s4_call", start: 381.19, dur: 3.45, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="semanas" eyebrow="De un solo resto" caption="cosechás hoja por hoja, sin arrancar la planta" accent="good" hue="amber" /> },
  { key: "cmp_num_4", start: 384.64, dur: 6.2, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="4" name="Bok choy" bg="broll/rpl_i4_bokchoy_base_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b85_rpl_i4_bokchoy_window_jar", start: 390.84, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_window_jar.mp4" darken={0} /> },
  { key: "b86_rpl_i4_bokchoy_base_water", start: 393.14, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_base_water.mp4" darken={0} /> },
  { key: "b87_rpl_i4_asian_leafy_greens", start: 396.5, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_asian_leafy_greens.mp4" darken={0} /> },
  { key: "b88_rpl_i4_bokchoy_base_water", start: 399.34, dur: 2.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_base_water.mp4" darken={0} /> },
  { key: "b89_rpl_i4_bokchoy_window_jar", start: 401.14, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_window_jar.mp4" darken={0} /> },
  { key: "b90_rpl_i4_asian_leafy_greens", start: 407.64, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_asian_leafy_greens.mp4" darken={0} /> },
  { key: "b91_rpl_i4_bokchoy_window_jar", start: 410.31, dur: 4.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i4_bokchoy_window_jar.mp4" darken={0} /> },
  { key: "cmp_num_5", start: 414.5, dur: 5, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="5" name="Puerro" bg="broll/rpl_i5_leek_regrow_upward.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_s5_split", start: 419.5, dur: 6.55, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Lo que NO necesitás" items={["Comprar semillas","Fertilizante químico","Luz especial"]} accent={D} cross /> },
  { key: "b95_rpl_i5_leeks_rustic_kitchen", start: 426.05, dur: 5.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leeks_rustic_kitchen.mp4" darken={0} /> },
  { key: "b96_rpl_i5_leek_root_macro", start: 430.64, dur: 3.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leek_root_macro.mp4" darken={0} /> },
  { key: "b97_rpl_i5_chopping_leek_macro", start: 433.77, dur: 4.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_chopping_leek_macro.mp4" darken={0} /> },
  { key: "b98_rpl_i5_leek_soup_pot", start: 437.5, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_leek_soup_pot.mp4" darken={0} /> },
  { key: "b99_rpl_i5_washing_leek_water", start: 441.24, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_washing_leek_water.mp4" darken={0} /> },
  { key: "cmp_herbs", start: 443.5, dur: 9.07, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} image="img/cmp_herbs_bg.png" title="Las hierbas: donde más ahorrás" chips={["Albahaca","Menta","Cilantro"]} hue="amber" /> },
  { key: "cmp_basil_bars", start: 452.57, dur: 6.37, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Comprada cada semana","value":60,"display":"60€/año","tone":"danger"},{"label":"De 1 manojo replantado","value":0,"display":"0€","winner":true}]} eyebrow="Comprarla vs replantarla" title="Albahaca fresca" unit="EUR" accent="good" hue="amber" /> },
  { key: "b103_rpl_i5_washing_leek_water", start: 458.94, dur: 4.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i5_washing_leek_water.mp4" darken={0} /> },
  { key: "cmp_num_6", start: 462.5, dur: 2.99, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="6" name="Albahaca" bg="broll/rpl_i6_basil_cuttings_glass.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_s6_bars", start: 465.49, dur: 6.19, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Comprando","value":220,"display":"~220€","tone":"danger"},{"label":"Replantando","value":0,"display":"0€","winner":true}]} eyebrow="Lo que se va al año en lo replantable" title="Tu factura de verdura" unit="EUR" accent="good" hue="amber" /> },
  { key: "b107_rpl_i6_picking_basil_hand", start: 471.68, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_picking_basil_hand.mp4" darken={0} /> },
  { key: "b108_rpl_i6_basil_timelapse_root", start: 474.93, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_timelapse_root.mp4" darken={0} /> },
  { key: "b109_rpl_i6_basil_windowsill_plants", start: 477.73, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_windowsill_plants.mp4" darken={0} /> },
  { key: "b110_rpl_i6_basil_cuttings_glass", start: 481.01, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_cuttings_glass.mp4" darken={0} /> },
  { key: "b111_rpl_i6_picking_basil_hand", start: 484.28, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_picking_basil_hand.mp4" darken={0} /> },
  { key: "b112_rpl_i6_basil_timelapse_root", start: 487.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_timelapse_root.mp4" darken={0} /> },
  { key: "b113_rpl_i6_basil_cuttings_glass", start: 490.5, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_cuttings_glass.mp4" darken={0} /> },
  { key: "b114_rpl_i6_basil_windowsill_plants", start: 493.64, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_basil_windowsill_plants.mp4" darken={0} /> },
  { key: "b115_rpl_i6_picking_basil_hand", start: 497.08, dur: 5.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i6_picking_basil_hand.mp4" darken={0} /> },
  { key: "cmp_s7_proc", start: 502.5, dur: 3, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Esperá raíces de 2-3 cm"},{"title":"Maceta con tierra y buen sol"},{"title":"Regá y dejá que se haga fuerte"}]} eyebrow="La señal exacta" title="Cuándo pasarla a la tierra" accent="good" hue="amber" /> },
  { key: "cmp_num_7", start: 505.5, dur: 5.88, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="7" name="Menta" bg="broll/rpl_i7_mint_cuttings_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b119_rpl_i7_mint_timelapse_grow", start: 511.38, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b120_rpl_i7_mint_cuttings_water", start: 513.5, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b121_rpl_i7_mint_roots_macro", start: 515.64, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b122_rpl_i7_mint_timelapse_grow", start: 519.24, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b123_rpl_i7_mint_cuttings_water", start: 524.5, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b124_rpl_i7_mint_roots_macro", start: 527.08, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b125_rpl_i7_mint_timelapse_grow", start: 529.5, dur: 4.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b126_rpl_i7_mint_cuttings_water", start: 533.17, dur: 4.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b127_rpl_i7_mint_roots_macro", start: 536.8, dur: 6.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b128_rpl_i7_mint_timelapse_grow", start: 542.49, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b129_rpl_i7_mint_cuttings_water", start: 546.29, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_cuttings_water.mp4" darken={0} /> },
  { key: "b130_rpl_i7_mint_roots_macro", start: 548.95, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_roots_macro.mp4" darken={0} /> },
  { key: "b131_rpl_i7_mint_timelapse_grow", start: 551.27, dur: 5.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i7_mint_timelapse_grow.mp4" darken={0} /> },
  { key: "b132_rpl_err_pale_wilting_cutting", start: 556.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b133_rpl_err_cloudy_stagnant_water", start: 560.5, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b134_rpl_err_slimy_rotting_roots", start: 565.64, dur: 4.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b135_rpl_err_pouring_old_water", start: 570.09, dur: 4.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b136_rpl_err_transplant_rich_soil", start: 574.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b137_rpl_err_pale_wilting_cutting", start: 578.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b138_rpl_err_transplant_rich_soil", start: 582.5, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b139_rpl_err_cloudy_stagnant_water", start: 585.64, dur: 2.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b140_rpl_err_slimy_rotting_roots", start: 587.91, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b141_rpl_err_pouring_old_water", start: 589.89, dur: 6.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b142_rpl_err_pale_wilting_cutting", start: 595.51, dur: 2.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b143_rpl_err_cloudy_stagnant_water", start: 597.5, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b144_rpl_err_slimy_rotting_roots", start: 599.5, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b145_rpl_err_pouring_old_water", start: 602.64, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "cmp_error_fix", start: 605.51, dur: 6.2, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Cambia el agua cada 2-3 días"},{"title":"En cuanto veas raíces, pásala a la tierra"}]} eyebrow="Las 2 reglas" title="Cómo evitar que mueran" accent="good" hue="amber" /> },
  { key: "b148_rpl_err_cloudy_stagnant_water", start: 611.71, dur: 6.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b149_rpl_err_slimy_rotting_roots", start: 617.59, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b150_rpl_err_pouring_old_water", start: 620.95, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "b151_rpl_err_transplant_rich_soil", start: 623.54, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_transplant_rich_soil.mp4" darken={0} /> },
  { key: "b152_rpl_err_pale_wilting_cutting", start: 625.88, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pale_wilting_cutting.mp4" darken={0} /> },
  { key: "b153_rpl_err_cloudy_stagnant_water", start: 628.22, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "b154_rpl_err_slimy_rotting_roots", start: 632.64, dur: 6.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_slimy_rotting_roots.mp4" darken={0} /> },
  { key: "b155_rpl_err_pouring_old_water", start: 638.9, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_pouring_old_water.mp4" darken={0} /> },
  { key: "cmp_water_crew", start: 641.5, dur: 6, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Solo agua y ventana" items={[{"text":"Cebolla de verdeo","state":"done"},{"text":"Lechuga","state":"done"},{"text":"Apio","state":"done"},{"text":"Bok choy","state":"done"},{"text":"Puerro","state":"done"}]} eyebrow="Los 5 más fáciles" accent="good" hue="amber" image="img/cmp_water_crew_bg.png" /> },
  { key: "b158_rpl_err_cloudy_stagnant_water", start: 647.5, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_err_cloudy_stagnant_water.mp4" darken={0} /> },
  { key: "cmp_num_8", start: 649.64, dur: 4.81, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="8" name="Cilantro" bg="broll/rpl_i8_cilantro_stems_water.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_s8_split", start: 654.45, dur: 8.03, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Mitos que te frenan" items={["\"Hace falta jardín\"","\"Es muy difícil\"","\"Tarda años\""]} accent={D} cross /> },
  { key: "b163_rpl_i8_chopping_cilantro", start: 662.48, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_chopping_cilantro.mp4" darken={0} /> },
  { key: "b164_rpl_i8_cilantro_window_jar", start: 664.5, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_window_jar.mp4" darken={0} /> },
  { key: "b165_rpl_i8_chopping_cilantro", start: 667.64, dur: 5.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_chopping_cilantro.mp4" darken={0} /> },
  { key: "b166_rpl_i8_cilantro_window_jar", start: 672.37, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_window_jar.mp4" darken={0} /> },
  { key: "b167_rpl_i8_cilantro_roots_macro", start: 674.63, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_roots_macro.mp4" darken={0} /> },
  { key: "b168_rpl_i8_cilantro_garden_bed", start: 677.64, dur: 2.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_garden_bed.mp4" darken={0} /> },
  { key: "b169_rpl_i8_cilantro_stems_water", start: 679.57, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_stems_water.mp4" darken={0} /> },
  { key: "b170_rpl_i8_cilantro_regrow_fresh", start: 682.2, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_regrow_fresh.mp4" darken={0} /> },
  { key: "b171_rpl_i8_cilantro_flowering", start: 686.5, dur: 4.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_flowering.mp4" darken={0} /> },
  { key: "b172_rpl_i8_coriander_seeds_macro", start: 690.33, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_coriander_seeds_macro.mp4" darken={0} /> },
  { key: "b173_rpl_i8_cilantro_roots_macro", start: 694.93, dur: 4.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i8_cilantro_roots_macro.mp4" darken={0} /> },
  { key: "cmp_num_9", start: 698.64, dur: 5.35, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="9" name="Ajo" bg="broll/rpl_i9_planting_clove_soil.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b175_rpl_i9_garlic_rows_field", start: 703.99, dur: 4.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b176_rpl_i9_planting_clove_soil", start: 707.68, dur: 3.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b177_rpl_i9_garlic_rows_field", start: 711.08, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b178_rpl_i9_planting_clove_soil", start: 713.5, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b179_rpl_i9_garlic_rows_field", start: 716.58, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b180_rpl_i9_planting_clove_soil", start: 719.08, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b181_rpl_i9_garlic_rows_field", start: 721.42, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b182_rpl_i9_planting_clove_soil", start: 724.18, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b183_rpl_i9_garlic_rows_field", start: 728.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b184_rpl_i9_planting_clove_soil", start: 731.5, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b185_rpl_i9_garlic_rows_field", start: 733.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b186_rpl_i9_planting_clove_soil", start: 739, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "b187_rpl_i9_garlic_rows_field", start: 741.69, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_garlic_rows_field.mp4" darken={0} /> },
  { key: "b188_rpl_i9_planting_clove_soil", start: 745.08, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i9_planting_clove_soil.mp4" darken={0} /> },
  { key: "cmp_num_10", start: 747.49, dur: 3.15, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="10" name="Jengibre" bg="broll/rpl_i10_ginger_buds_macro.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_jengibre", start: 750.64, dur: 7.42, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_jengibre_bg.png" annotations={[{"kind":"circle","x":0.42,"y":0.4,"w":0.16,"label":"Yema (como un ojo)","color":"good"},{"kind":"arrow","x":0.6,"y":0.6,"fromX":0.85,"fromY":0.85,"label":"Cortá con una yema","color":"amber"}]} eyebrow="Buscá la yema" hue="amber" /> },
  { key: "b193_rpl_i10_planting_ginger_soil", start: 758.06, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_planting_ginger_soil.mp4" darken={0} /> },
  { key: "b194_rpl_i10_ginger_shoot_green", start: 761.36, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_shoot_green.mp4" darken={0} /> },
  { key: "b195_rpl_i10_turmeric_root_orange", start: 764.5, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_turmeric_root_orange.mp4" darken={0} /> },
  { key: "b196_rpl_i10_ginger_pot_plant", start: 768.84, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_pot_plant.mp4" darken={0} /> },
  { key: "b197_rpl_i10_ginger_tea_water", start: 772.92, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_tea_water.mp4" darken={0} /> },
  { key: "b198_rpl_i10_ginger_pot_plant", start: 776.88, dur: 3.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_pot_plant.mp4" darken={0} /> },
  { key: "b199_rpl_i10_ginger_tea_water", start: 780.2, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_tea_water.mp4" darken={0} /> },
  { key: "b200_rpl_i10_ginger_market_pile", start: 783.58, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_market_pile.mp4" darken={0} /> },
  { key: "b201_rpl_i10_ginger_buds_macro", start: 786.19, dur: 2.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_buds_macro.mp4" darken={0} /> },
  { key: "b202_rpl_i10_turmeric_root_orange", start: 788.43, dur: 3.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_turmeric_root_orange.mp4" darken={0} /> },
  { key: "b203_rpl_i10_ginger_market_pile", start: 790.96, dur: 2.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_market_pile.mp4" darken={0} /> },
  { key: "b204_rpl_i10_ginger_buds_macro", start: 793.33, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_buds_macro.mp4" darken={0} /> },
  { key: "b205_rpl_i10_planting_ginger_soil", start: 796.53, dur: 4.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_planting_ginger_soil.mp4" darken={0} /> },
  { key: "b206_rpl_i10_ginger_shoot_green", start: 800.64, dur: 7.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_shoot_green.mp4" darken={0} /> },
  { key: "b207_rpl_i10_turmeric_root_orange", start: 807.66, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_turmeric_root_orange.mp4" darken={0} /> },
  { key: "b208_rpl_i10_ginger_pot_plant", start: 811.24, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i10_ginger_pot_plant.mp4" darken={0} /> },
  { key: "cmp_num_11", start: 813.58, dur: 0.86, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="11" name="Papa" bg="broll/rpl_i11_sprouting_potato_pantry.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_papa", start: 814.44, dur: 7.05, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_papa_bg.png" annotations={[{"kind":"circle","x":0.35,"y":0.4,"w":0.14,"label":"Los ojos / brotes","color":"good"},{"kind":"circle","x":0.66,"y":0.55,"w":0.14,"label":"","color":"good"},{"kind":"arrow","x":0.5,"y":0.82,"fromX":0.8,"fromY":0.95,"label":"Cortá en trozos y dejá secar","color":"amber"}]} eyebrow="Cada trozo, un ojo" hue="amber" /> },
  { key: "b212_rpl_i11_potato_pieces_drying", start: 821.49, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_pieces_drying.mp4" darken={0} /> },
  { key: "b213_rpl_i11_planting_trench_soil", start: 827.17, dur: 3.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_planting_trench_soil.mp4" darken={0} /> },
  { key: "b214_rpl_i11_potato_plants_rows", start: 830.5, dur: 6.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plants_rows.mp4" darken={0} /> },
  { key: "b215_rpl_i11_potato_sprout_macro", start: 836.64, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_sprout_macro.mp4" darken={0} /> },
  { key: "b216_rpl_i11_potato_plant_timelapse", start: 839.25, dur: 5.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plant_timelapse.mp4" darken={0} /> },
  { key: "b217_rpl_i11_washing_potatoes_water", start: 844.5, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_washing_potatoes_water.mp4" darken={0} /> },
  { key: "b218_rpl_i11_sprouting_potato_pantry", start: 847.64, dur: 2.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_sprouting_potato_pantry.mp4" darken={0} /> },
  { key: "b219_rpl_i11_cutting_potato_pieces", start: 850.09, dur: 8.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_cutting_potato_pieces.mp4" darken={0} /> },
  { key: "b220_rpl_i11_potato_pieces_drying", start: 858.29, dur: 9.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_pieces_drying.mp4" darken={0} /> },
  { key: "cmp_potato_yield", start: 867.5, dur: 6.8, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="10–15" eyebrow="De una sola papa" caption="papas nuevas, de una que ibas a tirar" accent="good" hue="amber" /> },
  { key: "b222_rpl_i11_planting_trench_soil", start: 874.3, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_planting_trench_soil.mp4" darken={0} /> },
  { key: "b223_rpl_i11_potato_plant_timelapse", start: 877.5, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plant_timelapse.mp4" darken={0} /> },
  { key: "b224_rpl_i11_washing_potatoes_water", start: 882.64, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_washing_potatoes_water.mp4" darken={0} /> },
  { key: "b225_rpl_i11_potato_plants_rows", start: 885.1, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i11_potato_plants_rows.mp4" darken={0} /> },
  { key: "cmp_num_12", start: 887.36, dur: 3.99, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="12" name="Batata" bg="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_batata", start: 891.35, dur: 8.22, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_batata_bg.png" annotations={[{"kind":"arrow","x":0.5,"y":0.45,"fromX":0.8,"fromY":0.2,"label":"Palillos: mitad en agua","color":"amber"},{"kind":"circle","x":0.5,"y":0.2,"w":0.3,"label":"Salen los esquejes","color":"good"}]} eyebrow="El truco de los palillos" hue="amber" /> },
  { key: "b229_rpl_i12_rooting_slips_water", start: 899.57, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_rooting_slips_water.mp4" darken={0} /> },
  { key: "b230_rpl_i12_pulling_a_slip", start: 903.49, dur: 8.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_pulling_a_slip.mp4" darken={0} /> },
  { key: "b231_rpl_i12_rooting_slips_water", start: 911.18, dur: 4.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_rooting_slips_water.mp4" darken={0} /> },
  { key: "b232_rpl_i12_slips_macro_roots", start: 915.64, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_slips_macro_roots.mp4" darken={0} /> },
  { key: "b233_rpl_i12_sweetpotato_toothpicks_glass", start: 918.02, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" darken={0} /> },
  { key: "b234_rpl_i12_slips_macro_roots", start: 921.17, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_slips_macro_roots.mp4" darken={0} /> },
  { key: "b235_rpl_i12_sweetpotato_toothpicks_glass", start: 924.14, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" darken={0} /> },
  { key: "b236_rpl_i12_pulling_a_slip", start: 927.38, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_pulling_a_slip.mp4" darken={0} /> },
  { key: "b237_rpl_i12_rooting_slips_water", start: 929.64, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_rooting_slips_water.mp4" darken={0} /> },
  { key: "b238_rpl_i12_slips_macro_roots", start: 932.5, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_slips_macro_roots.mp4" darken={0} /> },
  { key: "b239_rpl_i12_sweetpotato_toothpicks_glass", start: 934.9, dur: 5.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_sweetpotato_toothpicks_glass.mp4" darken={0} /> },
  { key: "b240_rpl_i12_pulling_a_slip", start: 940.11, dur: 5.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i12_pulling_a_slip.mp4" darken={0} /> },
  { key: "cmp_s13_call", start: 945.52, dur: 4.12, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="1 → ∞" eyebrow="Un resto que no para" caption="vuelve a darte comida una y otra vez" accent="good" hue="amber" /> },
  { key: "cmp_num_13", start: 949.64, dur: 5.22, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="13" name="Zanahoria" bg="broll/rpl_i13_cutting_carrot_tops.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_business", start: 954.86, dur: 7.78, kind: "lielist", el: (d) => <LieList durationInFrames={d} title="Por qué te lo vende suelto" items={["Para que vuelvas cada semana","Lo usás una vez y lo tirás","El negocio es la dependencia"]} image="img/cmp_business_bg.png" accent="danger" /> },
  { key: "b246_rpl_i13_washing_carrots_water", start: 962.64, dur: 3.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_washing_carrots_water.mp4" darken={0} /> },
  { key: "b247_rpl_i13_carrot_seeds_hand", start: 965.2, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seeds_hand.mp4" darken={0} /> },
  { key: "b248_rpl_i13_carrots_market_bunch", start: 968.3, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrots_market_bunch.mp4" darken={0} /> },
  { key: "b249_rpl_i13_carrot_seedling_soil", start: 971.14, dur: 3.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seedling_soil.mp4" darken={0} /> },
  { key: "b250_rpl_i13_pulling_carrots_soil", start: 974.2, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_pulling_carrots_soil.mp4" darken={0} /> },
  { key: "b251_rpl_i13_cutting_carrot_tops", start: 977.2, dur: 5.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_cutting_carrot_tops.mp4" darken={0} /> },
  { key: "b252_rpl_i13_washing_carrots_water", start: 982.64, dur: 5.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_washing_carrots_water.mp4" darken={0} /> },
  { key: "b253_rpl_i13_carrot_tops_dish_water", start: 988.13, dur: 4.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_tops_dish_water.mp4" darken={0} /> },
  { key: "b254_rpl_i13_carrots_market_bunch", start: 991.68, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrots_market_bunch.mp4" darken={0} /> },
  { key: "b255_rpl_i13_carrot_seedling_soil", start: 994.1, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seedling_soil.mp4" darken={0} /> },
  { key: "b256_rpl_i13_carrots_market_bunch", start: 996.5, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrots_market_bunch.mp4" darken={0} /> },
  { key: "b257_rpl_i13_carrot_seedling_soil", start: 998.64, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seedling_soil.mp4" darken={0} /> },
  { key: "b258_rpl_i13_cutting_carrot_tops", start: 1002.78, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_cutting_carrot_tops.mp4" darken={0} /> },
  { key: "b259_rpl_i13_carrot_tops_dish_water", start: 1006.56, dur: 5.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_tops_dish_water.mp4" darken={0} /> },
  { key: "b260_rpl_i13_carrot_seeds_hand", start: 1012.05, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i13_carrot_seeds_hand.mp4" darken={0} /> },
  { key: "cmp_s14_bars", start: 1015.28, dur: 4.36, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Si lo comprás","value":90,"display":"~90€/año","tone":"danger"},{"label":"Si lo replantás","value":0,"display":"0€","winner":true}]} eyebrow="Cada resto que replantás" title="El ahorro que se acumula" unit="EUR" accent="good" hue="amber" /> },
  { key: "cmp_num_14", start: 1019.64, dur: 10.37, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="14" name="Tomate" bg="broll/rpl_i14_slicing_tomato_rounds.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "b264_rpl_i14_tomato_seedlings_row", start: 1030.01, dur: 3.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seedlings_row.mp4" darken={0} /> },
  { key: "b265_rpl_i14_covering_slices_soil", start: 1033.5, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_covering_slices_soil.mp4" darken={0} /> },
  { key: "b266_rpl_i14_tomato_seedlings_row", start: 1037.64, dur: 2.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seedlings_row.mp4" darken={0} /> },
  { key: "b267_rpl_i14_seedlings_tray_dozens", start: 1040.08, dur: 7.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_seedlings_tray_dozens.mp4" darken={0} /> },
  { key: "b268_rpl_i14_tomato_seeds_macro", start: 1047.16, dur: 8.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seeds_macro.mp4" darken={0} /> },
  { key: "b269_rpl_i14_tomato_timelapse_grow", start: 1054.8, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_timelapse_grow.mp4" darken={0} /> },
  { key: "b270_rpl_i14_slicing_tomato_rounds", start: 1059.64, dur: 5.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_slicing_tomato_rounds.mp4" darken={0} /> },
  { key: "b271_rpl_i14_seedlings_tray_dozens", start: 1064.35, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_seedlings_tray_dozens.mp4" darken={0} /> },
  { key: "b272_rpl_i14_tomato_timelapse_grow", start: 1067.5, dur: 3.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_timelapse_grow.mp4" darken={0} /> },
  { key: "b273_rpl_i14_tomato_seeds_macro", start: 1070.13, dur: 7.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_tomato_seeds_macro.mp4" darken={0} /> },
  { key: "b274_rpl_i14_slicing_tomato_rounds", start: 1076.64, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i14_slicing_tomato_rounds.mp4" darken={0} /> },
  { key: "cmp_num_15", start: 1079.46, dur: 4.64, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="15" name="Piña" bg="broll/rpl_i15_pineapple_crown_leafy.mp4" eyebrow="Replántalo gratis" accent="amber" /> },
  { key: "cmp_anno_pina", start: 1084.1, dur: 7.1, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/cmp_anno_pina_bg.png" annotations={[{"kind":"arrow","x":0.5,"y":0.7,"fromX":0.82,"fromY":0.9,"label":"Sacá las hojas de abajo","color":"amber"},{"kind":"circle","x":0.5,"y":0.66,"w":0.16,"label":"Raíces dormidas","color":"good"}]} eyebrow="La corona = una planta" hue="amber" /> },
  { key: "b279_rpl_i15_pineapple_crown_drying", start: 1091.2, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_crown_drying.mp4" darken={0} /> },
  { key: "b280_rpl_i15_crown_rooting_water", start: 1094.64, dur: 10.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_crown_rooting_water.mp4" darken={0} /> },
  { key: "b281_rpl_i15_mature_pineapple_fruit", start: 1104.77, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_mature_pineapple_fruit.mp4" darken={0} /> },
  { key: "b282_rpl_i15_pineapple_root_bumps_macro", start: 1107.64, dur: 5.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_root_bumps_macro.mp4" darken={0} /> },
  { key: "b283_rpl_i15_mature_pineapple_fruit", start: 1112.22, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_mature_pineapple_fruit.mp4" darken={0} /> },
  { key: "b284_rpl_i15_pineapple_root_bumps_macro", start: 1116.14, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_root_bumps_macro.mp4" darken={0} /> },
  { key: "b285_rpl_i15_pineapple_field_rows", start: 1119.4, dur: 5.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_field_rows.mp4" darken={0} /> },
  { key: "b286_rpl_i15_planting_crown_soil", start: 1124.5, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_planting_crown_soil.mp4" darken={0} /> },
  { key: "b287_rpl_i15_pineapple_crown_window", start: 1128.64, dur: 6.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_crown_window.mp4" darken={0} /> },
  { key: "b288_rpl_i15_pineapple_leaves_macro", start: 1135.07, dur: 2.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_leaves_macro.mp4" darken={0} /> },
  { key: "b289_rpl_i15_cutting_pineapple_top", start: 1137.14, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_cutting_pineapple_top.mp4" darken={0} /> },
  { key: "b290_rpl_i15_pineapple_timelapse_root", start: 1139.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_timelapse_root.mp4" darken={0} /> },
  { key: "b291_rpl_i15_pineapple_crown_leafy", start: 1142.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_crown_leafy.mp4" darken={0} /> },
  { key: "b292_rpl_i15_pineapple_timelapse_root", start: 1146.5, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i15_pineapple_timelapse_root.mp4" darken={0} /> },
  { key: "cmp_quote", start: 1150.64, dur: 7.86, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/cmp_quote_bg.png" words={parseQuote("La naturaleza no conoce la palabra *basura*.")} accent="amber" hue="amber" fontSize={96} /> },
  { key: "cmp_num_16", start: 1158.5, dur: 6.17, kind: "numcard", el: (d) => <NumberCard durationInFrames={d} number="16" name="Pimiento" bg="broll/rpl_i16_cutting_open_pepper.mp4" eyebrow="Bonus de regalo" accent="good" /> },
  { key: "b297_rpl_i16_pepper_seedlings_germinate", start: 1164.67, dur: 4.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedlings_germinate.mp4" darken={0} /> },
  { key: "b298_rpl_i16_colorful_peppers_market", start: 1168.5, dur: 2.81, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_colorful_peppers_market.mp4" darken={0} /> },
  { key: "b299_rpl_i16_pepper_seedling_macro", start: 1170.81, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedling_macro.mp4" darken={0} /> },
  { key: "b300_rpl_i16_watering_pepper_pot", start: 1173.64, dur: 2.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_watering_pepper_pot.mp4" darken={0} /> },
  { key: "b301_rpl_i16_colorful_peppers_market", start: 1175.75, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_colorful_peppers_market.mp4" darken={0} /> },
  { key: "b302_rpl_i16_pepper_seedling_macro", start: 1180.59, dur: 4.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedling_macro.mp4" darken={0} /> },
  { key: "b303_rpl_i16_watering_pepper_pot", start: 1184.36, dur: 3.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_watering_pepper_pot.mp4" darken={0} /> },
  { key: "b304_rpl_i16_picking_pepper_plant", start: 1187.61, dur: 2.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_picking_pepper_plant.mp4" darken={0} /> },
  { key: "b305_rpl_i16_cutting_open_pepper", start: 1189.64, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_cutting_open_pepper.mp4" darken={0} /> },
  { key: "b306_rpl_i16_pressing_seeds_soil", start: 1192.18, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pressing_seeds_soil.mp4" darken={0} /> },
  { key: "b307_rpl_i16_pepper_seedlings_germinate", start: 1196.32, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_pepper_seedlings_germinate.mp4" darken={0} /> },
  { key: "b308_rpl_i16_picking_pepper_plant", start: 1201.52, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_i16_picking_pepper_plant.mp4" darken={0} /> },
  { key: "cmp_close_proc", start: 1204.27, dur: 3.37, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Usás la verdura en la cocina"},{"title":"El resto vuelve al agua"},{"title":"Crece y cosechás otra vez"}]} eyebrow="Y vuelve a empezar" title="El ciclo que no termina" accent="good" hue="amber" /> },
  { key: "cmp_grid", start: 1207.64, dur: 8.09, kind: "gridreveal", el: (d) => <GridReveal durationInFrames={d} tiles={[{"number":"1","name":"Cebolla de verdeo"},{"number":"2","name":"Lechuga"},{"number":"3","name":"Apio"},{"number":"4","name":"Bok choy"},{"number":"5","name":"Puerro"},{"number":"6","name":"Albahaca"},{"number":"7","name":"Menta"},{"number":"8","name":"Cilantro"},{"number":"9","name":"Ajo"},{"number":"10","name":"Jengibre"},{"number":"11","name":"Papa"},{"number":"12","name":"Batata"},{"number":"13","name":"Zanahoria"},{"number":"14","name":"Tomate"},{"number":"15","name":"Piña"},{"number":"16","name":"Pimiento"}]} title="16 restos = 16 plantas" subtitle="Gratis · desde tu basura" /> },
  { key: "cmp_zero", start: 1215.73, dur: 6.71, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="0€" eyebrow="16 plantas" caption="comida que se siembra a sí misma, desde tu basura" accent="good" hue="amber" /> },
  { key: "b315_rpl_cl_seedlings_windowsill_row", start: 1222.44, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_seedlings_windowsill_row.mp4" darken={0} /> },
  { key: "b316_rpl_cl_child_hands_seedling", start: 1225.65, dur: 2.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_child_hands_seedling.mp4" darken={0} /> },
  { key: "b317_rpl_cl_seedlings_windowsill_row", start: 1227.5, dur: 6.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_seedlings_windowsill_row.mp4" darken={0} /> },
  { key: "b318_rpl_cl_farmer_teaching_child", start: 1233.64, dur: 2.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_farmer_teaching_child.mp4" darken={0} /> },
  { key: "b319_rpl_cl_scraps_returned_soil", start: 1235.47, dur: 2.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_scraps_returned_soil.mp4" darken={0} /> },
  { key: "b320_rpl_cl_child_hands_seedling", start: 1237.46, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_child_hands_seedling.mp4" darken={0} /> },
  { key: "b321_rpl_cl_seedlings_windowsill_row", start: 1242.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_seedlings_windowsill_row.mp4" darken={0} /> },
  { key: "b322_rpl_cl_farmer_teaching_child", start: 1245.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_farmer_teaching_child.mp4" darken={0} /> },
  { key: "b323_rpl_cl_scraps_returned_soil", start: 1248.5, dur: 3.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_cl_scraps_returned_soil.mp4" darken={0} /> },
  { key: "b324_rpl_ac_scallion_into_glass", start: 1251.53, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
  { key: "b325_rpl_ac_writing_garden_journal", start: 1254.64, dur: 2.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_writing_garden_journal.mp4" darken={0} /> },
  { key: "b326_rpl_ac_fresh_start_seedlings", start: 1256.81, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_fresh_start_seedlings.mp4" darken={0} /> },
  { key: "b327_rpl_ac_scallion_into_glass", start: 1259.35, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
  { key: "b328_rpl_ac_writing_garden_journal", start: 1262.29, dur: 3.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_writing_garden_journal.mp4" darken={0} /> },
  { key: "b329_rpl_ac_fresh_start_seedlings", start: 1265.5, dur: 4.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_fresh_start_seedlings.mp4" darken={0} /> },
  { key: "b330_rpl_ac_scallion_into_glass", start: 1269.29, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
  { key: "b331_rpl_ac_writing_garden_journal", start: 1272.64, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_writing_garden_journal.mp4" darken={0} /> },
  { key: "b332_rpl_ac_fresh_start_seedlings", start: 1276.5, dur: 6.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_fresh_start_seedlings.mp4" darken={0} /> },
  { key: "b333_rpl_ac_scallion_into_glass", start: 1282.63, dur: 5.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/rpl_ac_scallion_into_glass.mp4" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "kl1", start: 43.5, dur: 4.84, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" Esa","at":0},{"t":" parte","at":0.22},{"t":" que","at":0.6},{"t":" tú","at":0.83},{"t":" llamas","at":1.06},{"t":" basura","at":1.51},{"t":" todavía","at":2},{"t":" está","at":2.72},{"t":" viva.","at":3.14,"hl":true}]} accent="amber" /> },
  { key: "kl2", start: 50.29, dur: 3.05, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" vuelve","at":0},{"t":" a","at":0.53},{"t":" crecer.","at":0.62},{"t":" Gratis.","at":1.35,"hl":true}]} accent="amber" /> },
  { key: "kl3", start: 1214.1, dur: 2.56, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" cero","at":0,"hl":true},{"t":" euros","at":0.33,"hl":true},{"t":" gastados.","at":0.86}]} accent="amber" /> },
  { key: "kl4", start: 593.18, dur: 2.09, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" para","at":0},{"t":" siempre","at":0.39,"hl":true}]} accent="amber" /> },
  { key: "kl5", start: 1323.93, dur: 3.43, kind: "kineticline", el: (d) => <KineticLine durationInFrames={d} words={[{"t":" tires","at":0},{"t":" lo","at":0.44},{"t":" que","at":0.48},{"t":" todavía","at":0.71},{"t":" está","at":1.33},{"t":" vivo.","at":1.73,"hl":true}]} accent="amber" /> },
  { key: "cmp_floatscraps", start: 18.04, dur: 16.95, kind: "floatcards", el: (d) => <FloatCards durationInFrames={d} cards={[{"label":"Lechuga","src":"broll/rpl_i2_lettuce_dish_water.mp4","at":0},{"label":"Cebolla","src":"broll/rpl_i1_scallion_root_ends.mp4","at":3.66},{"label":"Ajo","src":"broll/rpl_i9_planting_clove_soil.mp4","at":8.41},{"label":"Piña","src":"broll/rpl_i15_pineapple_crown_leafy.mp4","at":14.35}]} /> },
];
