// cues_ovejas.gen.tsx — GENERADO por beatsheet.mjs desde ovejas.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/ovejas.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { KineticQuote, parseQuote } from "./scenes/KineticQuote";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { IngredientEquation } from "./scenes/IngredientEquation";
import { StatBig } from "./scenes/StatBig";
import { SagaTimeline } from "./scenes/SagaTimeline";
import { AgedDoc } from "./scenes/AgedDoc";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { MistakeCard } from "./scenes/MistakeCard";
import { GoldVault } from "./scenes/GoldVault";
import { NextVideoEndcard } from "./scenes/NextVideoEndcard";
import { StatPills } from "./scenes/StatPills";
import { RegrowSplit } from "./scenes/RegrowSplit";
import { LieList } from "./scenes/LieList";
import { GridReveal } from "./scenes/GridReveal";
import { GrowthTimeline } from "./scenes/GrowthTimeline";
import { SplitExplain } from "./setpieces/SplitExplain";

const D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "b1", start: 6.3, dur: 0.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov001.jpg" hue="amber" /> },
  { key: "sp1", start: 7, dur: 16.1, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$225.000" image="img/ov006.jpg" eyebrow="DE $2.500 A" caption="en unos pocos años" hue="amber" /> },
  { key: "b2", start: 23.1, dur: 6.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov002.jpg" hue="amber" /> },
  { key: "b3", start: 29.3, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os001.mp4" hue="amber" /> },
  { key: "b4", start: 33, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov003.jpg" hue="amber" /> },
  { key: "b5", start: 36.4, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov004.jpg" hue="amber" /> },
  { key: "b6", start: 38, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os002.mp4" hue="amber" /> },
  { key: "b7", start: 46.1, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov005.jpg" hue="amber" /> },
  { key: "b8", start: 50.4, dur: 9.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov006.jpg" hue="amber" /> },
  { key: "b9", start: 60, dur: 14.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os003.mp4" hue="amber" /> },
  { key: "b10", start: 74.6, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov007.jpg" hue="amber" /> },
  { key: "b11", start: 78.3, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov008.jpg" hue="amber" /> },
  { key: "b12", start: 83.4, dur: 7.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os004.mp4" hue="amber" /> },
  { key: "sp2", start: 90.6, dur: 9.4, kind: "lielist", el: (d) => <LieList durationInFrames={d} title="Te dicen que necesitás:" items={["Millones de dólares","Mil hectáreas","Un tractor gigante"]} image="img/ov035.jpg" hue="cold" /> },
  { key: "b13", start: 100, dur: 1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov009.jpg" hue="amber" /> },
  { key: "b14", start: 101, dur: 7.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov010.jpg" hue="amber" /> },
  { key: "b15", start: 108.3, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os005.mp4" hue="amber" /> },
  { key: "b16", start: 111.3, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov011.jpg" hue="amber" /> },
  { key: "sp3", start: 114.5, dur: 7.5, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} bg="image" image="img/ov006.jpg" title="Hoy vas a ver" chips={["La cuenta real","El animal exacto","El método"]} hue="amber" /> },
  { key: "b17", start: 122, dur: 6.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov012.jpg" hue="amber" /> },
  { key: "b18", start: 128.2, dur: 8.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os006.mp4" hue="amber" /> },
  { key: "b19", start: 136.6, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov013.jpg" hue="amber" /> },
  { key: "b20", start: 138.8, dur: 8.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov014.jpg" hue="amber" /> },
  { key: "b21", start: 147.2, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os007.mp4" hue="amber" /> },
  { key: "b22", start: 151.6, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov015.jpg" hue="amber" /> },
  { key: "b23", start: 153.9, dur: 0.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov016.jpg" hue="amber" /> },
  { key: "sp4", start: 154.6, dur: 10.7, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Vaca","value":1,"display":"1 cría/año"},{"label":"Oveja","value":3,"display":"2 cada 8 meses"}]} eyebrow="VACA vs OVEJA" title="¿Cuál se multiplica?" hue="amber" /> },
  { key: "b24", start: 165.3, dur: 6.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os008.mp4" hue="amber" /> },
  { key: "b25", start: 172.2, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov017.jpg" hue="amber" /> },
  { key: "b26", start: 177.6, dur: 5.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov018.jpg" hue="amber" /> },
  { key: "b27", start: 182.8, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os011.mp4" hue="amber" /> },
  { key: "b28", start: 186.8, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov019.jpg" hue="amber" /> },
  { key: "b29", start: 188.4, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov020.jpg" hue="amber" /> },
  { key: "sp5", start: 193.7, dur: 7.7, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} bg="image" image="img/ov017.jpg" title="Oveja de pelo · Dorper" chips={["No se esquila","Suelta el pelo sola","Solo carne, bien pagada"]} hue="amber" /> },
  { key: "b30", start: 201.4, dur: 7.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os012.mp4" hue="amber" /> },
  { key: "b31", start: 209, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov021.jpg" hue="amber" /> },
  { key: "b32", start: 211.2, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov022.jpg" hue="amber" /> },
  { key: "sp26", start: 215, dur: 8, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/ov017.jpg" annotations={[{"kind":"circle","x":0.52,"y":0.5,"w":0.2,"label":"Pelo, no lana"}]} eyebrow="OVEJA DE PELO" caption="No se esquila — suelta el pelo sola" hue="amber" /> },
  { key: "b33", start: 223, dur: 6.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os013.mp4" hue="amber" /> },
  { key: "b34", start: 229.6, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov023.jpg" hue="amber" /> },
  { key: "b35", start: 232.7, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov024.jpg" hue="amber" /> },
  { key: "b36", start: 237.4, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os014.mp4" hue="amber" /> },
  { key: "sp6", start: 240, dur: 6.5, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={2} suffix=" CRÍAS" label="cada 8 meses" eyebrow="LA DORPER" hue="amber" /> },
  { key: "b37", start: 246.5, dur: 6.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov025.jpg" hue="amber" /> },
  { key: "b38", start: 252.7, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov026.jpg" hue="amber" /> },
  { key: "b39", start: 256.4, dur: 1.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os015.mp4" hue="amber" /> },
  { key: "sp7", start: 258.1, dur: 9.8, kind: "gridreveal", el: (d) => <GridReveal durationInFrames={d} tiles={[{"number":"10","name":"hoy"},{"number":"20","name":"año 1"},{"number":"40","name":"año 2"},{"number":"80","name":"año 3"}]} title="Interés compuesto... con patas" subtitle="el rebaño se duplica solo" /> },
  { key: "b40", start: 267.9, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov027.jpg" hue="amber" /> },
  { key: "b41", start: 274, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov028.jpg" hue="amber" /> },
  { key: "b42", start: 282.5, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os016.mp4" hue="amber" /> },
  { key: "b43", start: 288.6, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov029.jpg" hue="amber" /> },
  { key: "b44", start: 291.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov030.jpg" hue="amber" /> },
  { key: "sp27", start: 295, dur: 13.5, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/ov066.jpg" annotations={[{"kind":"circle","x":0.5,"y":0.55,"w":0.22,"label":"El rebaño crece"}]} eyebrow="SE MULTIPLICA SOLO" caption="2 crías cada 8 meses, casi siempre mellizos" hue="amber" /> },
  { key: "b45", start: 308.5, dur: 6.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os017.mp4" hue="amber" /> },
  { key: "b46", start: 314.7, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov031.jpg" hue="amber" /> },
  { key: "b47", start: 327.6, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov032.jpg" hue="amber" /> },
  { key: "b48", start: 331, dur: 1.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os018.mp4" hue="amber" /> },
  { key: "b49", start: 332.4, dur: 0.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov033.jpg" hue="amber" /> },
  { key: "sp8", start: 349, dur: 18.4, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="La guía del micro-rancho" lines={[{"text":"Cuántos animales por parcela","mark":true},{"text":"Los tiempos exactos"},{"text":"Los números reales, paso a paso"}]} eyebrow="¿La publico o me la guardo?" hue="amber" /> },
  { key: "b50", start: 367.4, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov034.jpg" hue="amber" /> },
  { key: "b51", start: 372, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os019.mp4" hue="amber" /> },
  { key: "b52", start: 382, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov035.jpg" hue="amber" /> },
  { key: "b53", start: 386.1, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov036.jpg" hue="amber" /> },
  { key: "sp9", start: 389.1, dur: 10.5, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Parcela chica","desc":"con alambre eléctrico"},{"title":"Comen y abonan","desc":"1 o 2 días"},{"title":"Mover al lado","desc":"tira fresca"},{"title":"Descansar 30-40 días","desc":"el pasto resucita"}]} eyebrow="PASTOREO ROTATIVO" /> },
  { key: "b54", start: 399.6, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os020.mp4" hue="amber" /> },
  { key: "b55", start: 402.2, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov037.jpg" hue="amber" /> },
  { key: "b56", start: 405, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov038.jpg" hue="amber" /> },
  { key: "b57", start: 408.2, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os021.mp4" hue="amber" /> },
  { key: "b58", start: 412.4, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov039.jpg" hue="amber" /> },
  { key: "b59", start: 417, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov040.jpg" hue="amber" /> },
  { key: "b60", start: 420.5, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os022.mp4" hue="amber" /> },
  { key: "b61", start: 422.6, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov041.jpg" hue="amber" /> },
  { key: "sp28", start: 425, dur: 6.4, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/ov087.jpg" annotations={[{"kind":"arrow","x":0.45,"y":0.5,"fromX":0.82,"fromY":0.72,"label":"Tira fresca"}]} eyebrow="PASTOREO ROTATIVO" caption="Comen una tira, la dejás descansar 30 días" hue="amber" /> },
  { key: "b62", start: 431.4, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov042.jpg" hue="amber" /> },
  { key: "b63", start: 436.2, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os023.mp4" hue="amber" /> },
  { key: "b64", start: 439.4, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov043.jpg" hue="amber" /> },
  { key: "b65", start: 442.9, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov044.jpg" hue="amber" /> },
  { key: "b66", start: 444.9, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os024.mp4" hue="amber" /> },
  { key: "b67", start: 448.2, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov045.jpg" hue="amber" /> },
  { key: "b68", start: 452.7, dur: 1.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov046.jpg" hue="amber" /> },
  { key: "sp10", start: 454.6, dur: 12.1, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Suelto","value":1,"display":"1"},{"label":"Rotativo","value":5,"display":"5"}]} eyebrow="MISMA HECTÁREA" title="Animales por hectárea" unit=" ovejas" hue="amber" /> },
  { key: "b69", start: 466.7, dur: 0.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os025.mp4" hue="amber" /> },
  { key: "sp11", start: 467.2, dur: 12.9, kind: "regrow", el: (d) => <RegrowSplit durationInFrames={d} leftImage="img/ov087.jpg" rightImage="img/ov090.jpg" title="El pasto vuelve más fuerte" leftLabel="Comido" rightLabel="Resucitado" hue="amber" /> },
  { key: "b70", start: 480.1, dur: 7.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov047.jpg" hue="amber" /> },
  { key: "b71", start: 488, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov048.jpg" hue="amber" /> },
  { key: "b72", start: 491.8, dur: 0.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os026.mp4" hue="amber" /> },
  { key: "sp12", start: 492.7, dur: 10.1, kind: "ingredients", el: (d) => <IngredientEquation durationInFrames={d} items={[{"image":"img/ov066.jpg","label":"12 ovejas madre"},{"image":"img/ov097.jpg","label":"1 buen carnero"}]} resultLabel="Tu fábrica viva" /> },
  { key: "b73", start: 502.8, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov049.jpg" hue="amber" /> },
  { key: "b74", start: 506.6, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov050.jpg" hue="amber" /> },
  { key: "b75", start: 511.3, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os027.mp4" hue="amber" /> },
  { key: "b76", start: 514.9, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov051.jpg" hue="amber" /> },
  { key: "b77", start: 519.3, dur: 8.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov052.jpg" hue="amber" /> },
  { key: "b78", start: 527.7, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os030.mp4" hue="amber" /> },
  { key: "b79", start: 530.8, dur: 9.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov053.jpg" hue="amber" /> },
  { key: "sp13", start: 540, dur: 7.5, kind: "timeline", el: (d) => <SagaTimeline durationInFrames={d} events={[{"year":"Año 1","label":"20 corderos"},{"year":"Año 3","label":"40 madres"},{"year":"Año 4","label":"80 animales"},{"year":"Año 6","label":"$200.000","accent":"amber"}]} eyebrow="LA BOLA DE NIEVE" title="De $2.500 a un patrimonio" /> },
  { key: "b80", start: 547.5, dur: 7.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov054.jpg" hue="amber" /> },
  { key: "sp14", start: 554.9, dur: 6.8, kind: "goldvault", el: (d) => <GoldVault durationInFrames={d} label="$200.000" caption="un capital que se reproduce solo" /> },
  { key: "b81", start: 561.7, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os031.mp4" hue="amber" /> },
  { key: "b82", start: 567, dur: 1.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov055.jpg" hue="amber" /> },
  { key: "b83", start: 568.9, dur: 6.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov056.jpg" hue="amber" /> },
  { key: "b84", start: 575.1, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os032.mp4" hue="amber" /> },
  { key: "b85", start: 580.1, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov057.jpg" hue="amber" /> },
  { key: "sp15", start: 583.8, dur: 9.3, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="!" title="El apuro" desc="Vender antes de tiempo y comerte las hembras jóvenes que iban a multiplicar el rebaño" eyebrow="EL ERROR QUE FUNDE AL 90%" image="img/ov111.jpg" /> },
  { key: "b86", start: 593.1, dur: 8.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov058.jpg" hue="amber" /> },
  { key: "b87", start: 601.4, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os035.mp4" hue="amber" /> },
  { key: "b88", start: 610, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov059.jpg" hue="amber" /> },
  { key: "b89", start: 615, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov060.jpg" hue="amber" /> },
  { key: "b90", start: 618.3, dur: 1.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os036.mp4" hue="amber" /> },
  { key: "sp29", start: 620, dur: 7.2, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/ov097.jpg" annotations={[{"kind":"circle","x":0.5,"y":0.48,"w":0.2,"label":"El mejor"}]} eyebrow="EL CARNERO" caption="Es la mitad de la sangre del rebaño" hue="amber" /> },
  { key: "b91", start: 627.2, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov061.jpg" hue="amber" /> },
  { key: "b92", start: 630.5, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov062.jpg" hue="amber" /> },
  { key: "b93", start: 634.3, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os037.mp4" hue="amber" /> },
  { key: "b94", start: 636.3, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov063.jpg" hue="amber" /> },
  { key: "b95", start: 640, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov064.jpg" hue="amber" /> },
  { key: "sp16", start: 647, dur: 8.8, kind: "splitexplain", el: (d) => <SplitExplain durationInFrames={d} bg="img/ov123.jpg" image="img/ov124.jpg" title="Dos productos, una tierra" points={["La vaca come lo alto","La oveja limpia lo bajo","Nada se desperdicia","Se enferman menos"]} eyebrow="PASTOREO MIXTO" accent="amber" /> },
  { key: "b96", start: 655.8, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os039.mp4" hue="amber" /> },
  { key: "b97", start: 663.3, dur: 9.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov065.jpg" hue="amber" /> },
  { key: "b98", start: 673, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov066.jpg" hue="amber" /> },
  { key: "b99", start: 678.5, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os040.mp4" hue="amber" /> },
  { key: "b100", start: 681.8, dur: 10.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov067.jpg" hue="amber" /> },
  { key: "b101", start: 692.3, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov068.jpg" hue="amber" /> },
  { key: "b102", start: 698, dur: 1.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os041.mp4" hue="amber" /> },
  { key: "sp17", start: 699.4, dur: 15.3, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} bg="image" image="img/ov129.jpg" title="«No tengo tierra»" chips={["Alquilá barato","Trabajá a porcentaje","Campos abandonados de sobra"]} hue="amber" /> },
  { key: "b103", start: 714.7, dur: 8.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov069.jpg" hue="amber" /> },
  { key: "b104", start: 722.8, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov070.jpg" hue="amber" /> },
  { key: "b105", start: 729.3, dur: 0.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os042.mp4" hue="amber" /> },
  { key: "sp30", start: 730, dur: 6.8, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/ov129.jpg" annotations={[{"kind":"circle","x":0.5,"y":0.55,"w":0.24,"label":"Tierra de sobra"}]} eyebrow="«NO TENGO TIERRA»" caption="Campos abandonados hay de sobra" hue="amber" /> },
  { key: "b106", start: 736.8, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov071.jpg" hue="amber" /> },
  { key: "b107", start: 741.4, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov072.jpg" hue="amber" /> },
  { key: "b108", start: 745.7, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os043.mp4" hue="amber" /> },
  { key: "b109", start: 747.7, dur: 7.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov073.jpg" hue="amber" /> },
  { key: "b110", start: 755.3, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov074.jpg" hue="amber" /> },
  { key: "b111", start: 758.8, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os044.mp4" hue="amber" /> },
  { key: "b112", start: 763.7, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov075.jpg" hue="amber" /> },
  { key: "b113", start: 768.6, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov076.jpg" hue="amber" /> },
  { key: "b114", start: 770.9, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os045.mp4" hue="amber" /> },
  { key: "b115", start: 774.9, dur: 1.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov077.jpg" hue="amber" /> },
  { key: "sp18", start: 776.8, dur: 8.7, kind: "statpills", el: (d) => <StatPills durationInFrames={d} pills={["No se esquila","Aguanta frío y calor","Pare sola en el campo","Casi no se enferma"]} /> },
  { key: "b116", start: 785.5, dur: 2.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov078.jpg" hue="amber" /> },
  { key: "b117", start: 788.1, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os046.mp4" hue="amber" /> },
  { key: "b118", start: 791.8, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov079.jpg" hue="amber" /> },
  { key: "b119", start: 796.7, dur: 8.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov080.jpg" hue="amber" /> },
  { key: "b120", start: 805, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os047.mp4" hue="amber" /> },
  { key: "b121", start: 810.5, dur: 6.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov081.jpg" hue="amber" /> },
  { key: "b122", start: 817.4, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov082.jpg" hue="amber" /> },
  { key: "b123", start: 821.1, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os048.mp4" hue="amber" /> },
  { key: "b124", start: 829.7, dur: 4.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov083.jpg" hue="amber" /> },
  { key: "b125", start: 834, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov084.jpg" hue="amber" /> },
  { key: "b126", start: 836.8, dur: 6.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os049.mp4" hue="amber" /> },
  { key: "b127", start: 843.6, dur: 10.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov085.jpg" hue="amber" /> },
  { key: "b128", start: 853.9, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov086.jpg" hue="amber" /> },
  { key: "sp19", start: 856.3, dur: 7.1, kind: "growthtimeline", el: (d) => <GrowthTimeline durationInFrames={d} stages={[{"label":"8 ovejas","sub":"el arranque"},{"label":"25","sub":"2do año"},{"label":"+100","sub":"4to año"}]} title="De 8 a más de 100" /> },
  { key: "b129", start: 863.4, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/os050.mp4" hue="amber" /> },
  { key: "b130", start: 866.8, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov087.jpg" hue="amber" /> },
  { key: "b131", start: 871.6, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov088.jpg" hue="amber" /> },
  { key: "b132", start: 881.1, dur: 8.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov089.jpg" hue="amber" /> },
  { key: "b133", start: 889.7, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov090.jpg" hue="amber" /> },
  { key: "b134", start: 892.5, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov091.jpg" hue="amber" /> },
  { key: "sp20", start: 898, dur: 10.4, kind: "quote", el: (d) => <KineticQuote durationInFrames={d} image="img/ov130.jpg" eyebrow="EL MUCHACHO DEL CAMPITO" words={parseQuote("El campo que nadie quería hoy me da *más que el sueldo* que tenía")} /> },
  { key: "b135", start: 908.4, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov092.jpg" hue="amber" /> },
  { key: "b136", start: 911.7, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov093.jpg" hue="amber" /> },
  { key: "b137", start: 914.5, dur: 18.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov094.jpg" hue="amber" /> },
  { key: "b138", start: 932.8, dur: 5.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov095.jpg" hue="amber" /> },
  { key: "b139", start: 938, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov096.jpg" hue="amber" /> },
  { key: "sp31", start: 940, dur: 5.3, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/ov130.jpg" annotations={[{"kind":"circle","x":0.5,"y":0.5,"w":0.22,"label":"Transformado"}]} eyebrow="EL CAMPO QUE NADIE QUERÍA" caption="Hoy le da más que el sueldo que tenía" hue="amber" /> },
  { key: "b140", start: 945.3, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov097.jpg" hue="amber" /> },
  { key: "b141", start: 958.2, dur: 7.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov098.jpg" hue="amber" /> },
  { key: "b142", start: 965.3, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov099.jpg" hue="amber" /> },
  { key: "b143", start: 969.3, dur: 5.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov100.jpg" hue="amber" /> },
  { key: "sp21", start: 975.1, dur: 15.8, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Te quieren cliente de:" items={["el banco","el supermercado","el patrón"]} accent={D} cross /> },
  { key: "b144", start: 990.9, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov101.jpg" hue="amber" /> },
  { key: "b145", start: 1003.8, dur: 9.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov102.jpg" hue="amber" /> },
  { key: "b146", start: 1013.2, dur: 13.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov103.jpg" hue="amber" /> },
  { key: "b147", start: 1027.1, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov104.jpg" hue="amber" /> },
  { key: "sp22", start: 1031.8, dur: 10.4, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Tierra prestada o alquilada"},{"title":"Hembras de mellizos"},{"title":"Un buen carnero"},{"title":"Cerco eléctrico portátil"},{"title":"Aguantá dos años"}]} eyebrow="PRIMEROS PASOS" /> },
  { key: "b148", start: 1042.2, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov105.jpg" hue="amber" /> },
  { key: "b149", start: 1047.6, dur: 6.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov106.jpg" hue="amber" /> },
  { key: "b150", start: 1053.9, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov107.jpg" hue="amber" /> },
  { key: "b151", start: 1063.4, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov108.jpg" hue="amber" /> },
  { key: "b152", start: 1068.1, dur: 6.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov109.jpg" hue="amber" /> },
  { key: "b153", start: 1074.7, dur: 2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov110.jpg" hue="amber" /> },
  { key: "sp23", start: 1076.7, dur: 8.9, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={50} suffix="%" label="de la sangre del rebaño" eyebrow="EL CARNERO" hue="amber" /> },
  { key: "b154", start: 1085.6, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov111.jpg" hue="amber" /> },
  { key: "b155", start: 1093.6, dur: 7.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov112.jpg" hue="amber" /> },
  { key: "b156", start: 1101.5, dur: 9.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov113.jpg" hue="amber" /> },
  { key: "b157", start: 1110.8, dur: 2.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov114.jpg" hue="amber" /> },
  { key: "b158", start: 1113.5, dur: 6.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov115.jpg" hue="amber" /> },
  { key: "b159", start: 1119.8, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov116.jpg" hue="amber" /> },
  { key: "b160", start: 1121.4, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov117.jpg" hue="amber" /> },
  { key: "b161", start: 1124.3, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov118.jpg" hue="amber" /> },
  { key: "b162", start: 1129.7, dur: 4.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov119.jpg" hue="amber" /> },
  { key: "b163", start: 1134.5, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov120.jpg" hue="amber" /> },
  { key: "b164", start: 1138, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov121.jpg" hue="amber" /> },
  { key: "sp24", start: 1140.5, dur: 13.5, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="LA RECETA DEL MICRO-RANCHO" items={[{"text":"Pedazo chico, bien manejado"},{"text":"Un animal que se multiplica"},{"text":"Aguantar dos años"},{"text":"Mover el pasto"},{"text":"Sumar unas vacas"}]} eyebrow="RESUMEN" hue="amber" /> },
  { key: "b165", start: 1154, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov122.jpg" hue="amber" /> },
  { key: "b166", start: 1161, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov123.jpg" hue="amber" /> },
  { key: "b167", start: 1169.5, dur: 11.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov124.jpg" hue="amber" /> },
  { key: "b168", start: 1180.8, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov125.jpg" hue="amber" /> },
  { key: "b169", start: 1185.5, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov126.jpg" hue="amber" /> },
  { key: "b170", start: 1190.6, dur: 7.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov127.jpg" hue="amber" /> },
  { key: "b171", start: 1198.4, dur: 11.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov128.jpg" hue="amber" /> },
  { key: "b172", start: 1210.1, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov129.jpg" hue="amber" /> },
  { key: "b173", start: 1214.1, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov130.jpg" hue="amber" /> },
  { key: "b174", start: 1219.5, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov131.jpg" hue="amber" /> },
  { key: "b175", start: 1225.9, dur: 7.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov132.jpg" hue="amber" /> },
  { key: "b176", start: 1233.7, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov133.jpg" hue="amber" /> },
  { key: "b177", start: 1235.8, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov134.jpg" hue="amber" /> },
  { key: "b178", start: 1240, dur: 13.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov135.jpg" hue="amber" /> },
  { key: "b179", start: 1253.9, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov136.jpg" hue="amber" /> },
  { key: "sp25", start: 1258, dur: 12.2, kind: "nextvideo", el: (d) => <NextVideoEndcard durationInFrames={d} title="Codornices: $1.000 al mes en el patio" kicker="Próximo video" sub="el animal chiquito que rinde como uno grande" /> },
  { key: "b180", start: 1270.2, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov137.jpg" hue="amber" /> },
  { key: "b181", start: 1276.3, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/ov138.jpg" hue="amber" /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [

];
