// cues_dulcesv2.gen.tsx — GENERADO por beatsheet.mjs desde dulcesv2.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/dulcesv2.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { FoodTeaseCards } from "./scenes/FoodTeaseCards";
import { FichaDulce, AntesAhora, CitaAbuela, IngredientesFlotan, TopDulce, NumeroDulce } from "./components/DulcesCards";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "intro_1", start: 0.13, dur: 6.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_1.mp4" hue="amber" fit="blur" /> },
  { key: "intro_2", start: 7.09, dur: 10.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_cocina1_1.jpg" hue="amber" /> },
  { key: "intro_3", start: 17.58, dur: 6.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "intro_4", start: 24.34, dur: 2.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_cocina2_1.jpg" hue="amber" /> },
  { key: "intro_5", start: 26.65, dur: 2.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_5.mp4" hue="amber" fit="blur" /> },
  { key: "intro_15", start: 29.48, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_15.mp4" hue="amber" fit="blur" /> },
  { key: "intro_6", start: 36.06, dur: 1.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_abuela_cocina1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "intro_16", start: 37.48, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_abuela_1.jpg" hue="amber" /> },
  { key: "intro_7", start: 41.76, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_abuela_cocina2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "intro_8", start: 46.24, dur: 2.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_familia1_1.jpg" hue="amber" /> },
  { key: "intro_9", start: 48.93, dur: 0.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_9.mp4" hue="amber" fit="blur" /> },
  { key: "intro_10", start: 49.85, dur: 6.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_10.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "intro_11", start: 55.96, dur: 1.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_almibar.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "intro_12", start: 57.14, dur: 6.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_12.mp4" hue="amber" fit="blur" /> },
  { key: "intro_13", start: 63.76, dur: 3.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_azucar_caramelo1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "intro_17", start: 67.73, dur: 5.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_17.mp4" hue="amber" fit="blur" /> },
  { key: "intro_14", start: 73.46, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_14.mp4" hue="amber" fit="blur" /> },
  { key: "intro_18", start: 75.09, dur: 9.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_manos_1.jpg" hue="amber" /> },
  { key: "d01_alfajor_1", start: 84.31, dur: 6.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajor_1.mp4" hue="amber" fit="blur" /> },
  { key: "d01_alfajor_2", start: 90.64, dur: 1.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_3", start: 91.82, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajor_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_4", start: 94.98, dur: 1.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajor_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_5", start: 96.52, dur: 4.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_6", start: 100.59, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajor_6.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_7", start: 104.48, dur: 7.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajor_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_8", start: 112.05, dur: 3.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_9", start: 115.56, dur: 5.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_10", start: 120.96, dur: 8.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_11", start: 129.7, dur: 6.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajor_11.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_12", start: 136.53, dur: 3.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d01_alfajor_13", start: 140.46, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_1", start: 144.82, dur: 5.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_2", start: 150.56, dur: 2.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_3", start: 152.86, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dulceleche.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_4", start: 155.66, dur: 3.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_5", start: 159.43, dur: 6.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_5.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_6", start: 166.16, dur: 2.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_6.mp4" hue="amber" fit="blur" /> },
  { key: "d02_dl_13", start: 168.84, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_13.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_7", start: 172.68, dur: 5.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_8", start: 178.21, dur: 4.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d01_alfajores.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_12", start: 182.92, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_12.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_9", start: 185.37, dur: 7.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_9.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_10", start: 193.09, dur: 16.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dl_10.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d02_dl_11", start: 209.72, dur: 14.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dulceleche_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_1", start: 224.64, dur: 5.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arrozleche.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_2", start: 229.93, dur: 2.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_2.mp4" hue="amber" fit="blur" /> },
  { key: "d03_arroz_3", start: 232.54, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_4", start: 237, dur: 2.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_5", start: 239.1, dur: 6.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_5.mp4" hue="amber" fit="blur" /> },
  { key: "d03_arroz_6", start: 245.41, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d02_dulceleche.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_7", start: 247.86, dur: 2.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_11", start: 249.97, dur: 8.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_11.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_8", start: 258.61, dur: 5.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_8.mp4" hue="amber" fit="blur" /> },
  { key: "d03_arroz_9", start: 264.03, dur: 8.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arroz_9.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d03_arroz_10", start: 272.18, dur: 8.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arrozleche_beauty.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_1", start: 280.43, dur: 6.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_maza_1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_2", start: 287, dur: 4.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_mazamorra.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_3", start: 291.33, dur: 5.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_maza_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_4", start: 296.96, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_maza_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_5", start: 301, dur: 5.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_maza_5.mp4" hue="amber" fit="blur" /> },
  { key: "d04_maza_6", start: 306.72, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d03_arrozleche_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_11", start: 309.68, dur: 1.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_mazamorra_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_7", start: 311.42, dur: 8.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_mazamorra_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_8", start: 319.44, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_mazamorra_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_9", start: 323.1, dur: 8.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_maza_9.mp4" hue="amber" fit="blur" /> },
  { key: "d04_maza_12", start: 331.77, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_mazamorra_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d04_maza_10", start: 334.12, dur: 7.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d04_maza_10.mp4" hue="amber" fit="blur" /> },
  { key: "d05_coco_1", start: 341.56, dur: 6.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_1.mp4" hue="amber" fit="blur" /> },
  { key: "d05_coco_2", start: 347.64, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_3", start: 350.16, dur: 2.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_4", start: 352.91, dur: 6.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_5", start: 359.89, dur: 4.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_5.mp4" hue="amber" fit="blur" /> },
  { key: "d05_coco_10", start: 364.02, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_6", start: 368.68, dur: 3.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_6.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_7", start: 372.64, dur: 2.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_8", start: 374.68, dur: 4.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_9", start: 379.53, dur: 14.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d05_coco_11", start: 394.23, dur: 6.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_1", start: 400.3, dur: 6.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_turronquaker.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_2", start: 406.33, dur: 4.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_quaker_2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_3", start: 410.6, dur: 2.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_quaker_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_4", start: 412.69, dur: 5.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_5", start: 418.28, dur: 4.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_quaker_5.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_7", start: 422.59, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_turronquaker_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_6", start: 426.01, dur: 7.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_quaker_6.mp4" hue="amber" fit="blur" /> },
  { key: "d06_quaker_8", start: 433.87, dur: 12.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_quaker_8.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_9", start: 446.77, dur: 12.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d06_turronquaker.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d06_quaker_10", start: 459.51, dur: 6.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d05_coco_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_1", start: 466.21, dur: 5.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_2", start: 472.16, dur: 1.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_3", start: 473.41, dur: 4.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_4", start: 478.04, dur: 8.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_5", start: 486.52, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_5.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_9", start: 489.42, dur: 6.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_9.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_7", start: 495.96, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_serve.mp4" hue="amber" fit="blur" /> },
  { key: "d07_mantecol_6", start: 500.04, dur: 11.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_8", start: 511.53, dur: 6.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d07_mantecol_10", start: 518.36, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d07_mantecol_serve.mp4" hue="amber" fit="blur" /> },
  { key: "d08_casca_1", start: 522.74, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_casca_1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_2", start: 529.24, dur: 4.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_cascaritas.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_3", start: 533.31, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_casca_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_4", start: 536.78, dur: 5.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_casca_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_5", start: 542.5, dur: 1.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_casca_5.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_6", start: 544.42, dur: 1.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_cascaritas_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_10", start: 546.07, dur: 5.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_cascaritas_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_7", start: 551.16, dur: 10.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_casca_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d08_casca_8", start: 561.19, dur: 15.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_cascaritas_serve.mp4" hue="amber" fit="blur" /> },
  { key: "d08_casca_9", start: 577.04, dur: 7.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_cascaritas.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d09_colacion_1", start: 584.94, dur: 6.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_1.mp4" hue="amber" fit="blur" /> },
  { key: "d09_colacion_2", start: 591.76, dur: 2.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_2.mp4" hue="amber" fit="blur" /> },
  { key: "d09_colacion_3", start: 594.16, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d09_colacion_4", start: 598.26, dur: 11.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_4.mp4" hue="amber" fit="blur" /> },
  { key: "d09_colacion_5", start: 609.28, dur: 8.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d09_colacion_6", start: 617.41, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d08_cascaritas_serve.mp4" hue="amber" fit="blur" /> },
  { key: "d09_colacion_7", start: 622.09, dur: 10.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d09_colacion_8", start: 632.14, dur: 6.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_8.mp4" hue="amber" fit="blur" /> },
  { key: "d09_colacion_9", start: 639.05, dur: 8.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d09_colacion_9.mp4" hue="amber" fit="blur" /> },
  { key: "d10_alfe_1", start: 647.12, dur: 8.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d10_alfe_2", start: 655.76, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfe_2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d10_alfe_3", start: 658.96, dur: 5.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques_close.mp4" hue="amber" fit="blur" /> },
  { key: "d10_alfe_4", start: 664.1, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfe_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d10_alfe_5", start: 667.24, dur: 6.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques_ingr.mp4" hue="amber" fit="blur" /> },
  { key: "d10_alfe_6", start: 673.9, dur: 3.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d10_alfe_7", start: 677.81, dur: 10.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques_serve.mp4" hue="amber" fit="blur" /> },
  { key: "d10_alfe_10", start: 687.91, dur: 6.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d10_alfe_8", start: 693.94, dur: 7.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfe_8.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d10_alfe_11", start: 701.61, dur: 3.17, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques_close.mp4" hue="amber" fit="blur" /> },
  { key: "d10_alfe_9", start: 704.78, dur: 6.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques_ingr.mp4" hue="amber" fit="blur" /> },
  { key: "d11_memb_1", start: 711.04, dur: 7.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_memb_1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_2", start: 718.52, dur: 2.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_membrillo.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_3", start: 721.25, dur: 5.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_memb_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_4", start: 727.01, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_memb_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_5", start: 732.83, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d10_alfeniques_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_6", start: 736.98, dur: 2.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_memb_6.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_7", start: 739.12, dur: 8.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_memb_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_8", start: 747.89, dur: 5.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_membrillo_beauty.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_9", start: 753.38, dur: 4.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_memb_9.mp4" hue="amber" fit="blur" /> },
  { key: "d11_memb_12", start: 758.36, dur: 8.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_membrillo_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_10", start: 766.83, dur: 12.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_membrillo_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d11_memb_11", start: 779.12, dur: 10.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d11_memb_11.mp4" hue="amber" fit="blur" /> },
  { key: "d12_arrope_1", start: 790, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_1.mp4" hue="amber" fit="blur" /> },
  { key: "d12_arrope_2", start: 797, dur: 6.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_2.mp4" hue="amber" fit="blur" /> },
  { key: "d12_arrope_3", start: 803.15, dur: 1.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d12_arrope_4", start: 804.74, dur: 2.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_4.mp4" hue="amber" fit="blur" /> },
  { key: "d12_arrope_5", start: 807.35, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_5.mp4" hue="amber" fit="blur" /> },
  { key: "d12_arrope_6", start: 811.5, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_6.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d12_arrope_9", start: 814.5, dur: 14.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d12_arrope_7", start: 829.03, dur: 8.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d12_arrope_8", start: 837.26, dur: 8.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_1", start: 845.61, dur: 6.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_2", start: 851.88, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_3", start: 855.12, dur: 7.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_4", start: 862.74, dur: 5.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_5", start: 867.84, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_6", start: 871.21, dur: 7.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_7", start: 878.97, dur: 11.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d12_arrope_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_9", start: 890.8, dur: 11.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d13_melco_8", start: 902.42, dur: 5.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d14_caram_1", start: 908.05, dur: 4.87, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d14_caramelosleche.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d14_caram_2", start: 912.92, dur: 7.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d14_caram_3", start: 920.49, dur: 2.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d14_caramelosleche_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d14_caram_4", start: 922.97, dur: 6.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d14_caram_4.mp4" hue="amber" fit="blur" /> },
  { key: "d14_caram_5", start: 929.9, dur: 2.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d14_caram_5.mp4" hue="amber" fit="blur" /> },
  { key: "d14_caram_6", start: 932.54, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d14_caramelosleche_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d14_caram_9", start: 935.56, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d14_caramelosleche.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d14_caram_7", start: 942.56, dur: 23.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d13_melcocha_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d14_caram_8", start: 965.87, dur: 5.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d14_caramelosleche_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_1", start: 971.49, dur: 4.77, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_2", start: 976.26, dur: 5.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_3", start: 982.12, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_4", start: 985.96, dur: 8.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_5", start: 994.23, dur: 5.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_6", start: 999.25, dur: 7.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_8", start: 1006.84, dur: 19.43, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia_close.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d15_ambr_7", start: 1026.27, dur: 8.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_1", start: 1034.81, dur: 8.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bomb_1.mp4" hue="amber" fit="blur" /> },
  { key: "d16_bomb_2", start: 1042.92, dur: 2.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bombones.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_3", start: 1044.94, dur: 1.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bomb_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_4", start: 1046.2, dur: 3.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bomb_4.mp4" hue="amber" fit="blur" /> },
  { key: "d16_bomb_5", start: 1050.19, dur: 9.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d15_ambrosia_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_6", start: 1059.39, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bomb_6.mp4" hue="amber" fit="blur" /> },
  { key: "d16_bomb_10", start: 1063.87, dur: 4.71, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bombones_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_7", start: 1068.58, dur: 13.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bomb_7.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_8", start: 1081.86, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bombones_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_11", start: 1086.58, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bomb_11.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d16_bomb_9", start: 1090.22, dur: 8.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bomb_9.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d17_chup_1", start: 1098.9, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chup_1.mp4" hue="amber" fit="blur" /> },
  { key: "d17_chup_2", start: 1106.4, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chupetines.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d17_chup_3", start: 1110.18, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chup_3.mp4" hue="amber" fit="blur" /> },
  { key: "d17_chup_4", start: 1113.75, dur: 7.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chup_4.mp4" hue="amber" fit="blur" /> },
  { key: "d17_chup_5", start: 1121.41, dur: 4.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d16_bombones_serve.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d17_chup_6", start: 1125.57, dur: 13.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chup_6.mp4" hue="amber" fit="blur" /> },
  { key: "d17_chup_7", start: 1138.71, dur: 7.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chup_7.mp4" hue="amber" fit="blur" /> },
  { key: "d17_chup_9", start: 1146.55, dur: 8.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chupetines_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d17_chup_8", start: 1155.06, dur: 7.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d17_chup_8.mp4" hue="amber" fit="blur" /> },
  { key: "d18_fruta_1", start: 1162.58, dur: 8.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_1.mp4" hue="amber" fit="blur" /> },
  { key: "d18_fruta_2", start: 1171.19, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d18_fruta_3", start: 1173.75, dur: 8.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_3.mp4" hue="amber" fit="blur" /> },
  { key: "d18_fruta_4", start: 1182.69, dur: 5.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_4.mp4" hue="amber" fit="blur" /> },
  { key: "d18_fruta_5", start: 1188, dur: 6.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_5.mp4" hue="amber" fit="blur" /> },
  { key: "d18_fruta_6", start: 1194.86, dur: 6.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_frutasabrillantadas_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d18_fruta_9", start: 1201.84, dur: 7.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_9.mp4" hue="amber" fit="blur" /> },
  { key: "d18_fruta_7", start: 1209.62, dur: 10.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_7.mp4" hue="amber" fit="blur" /> },
  { key: "d18_fruta_8", start: 1220.46, dur: 8.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_fruta_8.mp4" hue="amber" fit="blur" /> },
  { key: "d19_coni_1", start: 1229.01, dur: 6.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d19_coni_1.mp4" hue="amber" fit="blur" /> },
  { key: "d19_coni_2", start: 1235.94, dur: 7.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d19_coni_2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d19_coni_3", start: 1243.26, dur: 4.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d19_conitos_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d19_coni_4", start: 1247.77, dur: 4.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d19_coni_4.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d19_coni_9", start: 1251.88, dur: 5.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d19_coni_9.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d19_coni_5", start: 1257.6, dur: 12.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d19_coni_5.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d19_coni_6", start: 1269.84, dur: 5.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_frutasabrillantadas_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d19_coni_7", start: 1275.02, dur: 10.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d19_conitos_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d19_coni_8", start: 1285.72, dur: 6.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d18_frutasabrillantadas_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d20_ques_1", start: 1292.6, dur: 10.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d20_ques_2", start: 1302.82, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo_close.mp4" hue="amber" fit="blur" /> },
  { key: "d20_ques_3", start: 1305.27, dur: 5.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d20_ques_4", start: 1310.52, dur: 5.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d20_ques_5", start: 1316.24, dur: 6.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo_serve.mp4" hue="amber" fit="blur" /> },
  { key: "d20_ques_6", start: 1323.02, dur: 15.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d20_ques_7", start: 1338.74, dur: 5.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo_close.mp4" hue="amber" fit="blur" /> },
  { key: "d20_ques_9", start: 1344.49, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo_ingr.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "d20_ques_8", start: 1347.15, dur: 9.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/d20_quesillo_proc.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "ex_intro", start: 1357.11, dur: 7.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_cuchara_madera.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "ex_menta_1", start: 1364.38, dur: 7.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_cocina1_3.jpg" hue="amber" /> },
  { key: "ex_menta_2", start: 1371.76, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_cocina_vieja1.mp4" hue="amber" fit="blur" /> },
  { key: "ex_menta_3", start: 1376.76, dur: 5.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_abuela_2.jpg" hue="amber" /> },
  { key: "ex_menta_4", start: 1381.89, dur: 15.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_manos_viejas1.mp4" hue="amber" fit="blur" /> },
  { key: "ex_cayote_1", start: 1397.3, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_familia1_2.jpg" hue="amber" /> },
  { key: "ex_cayote_2", start: 1401.76, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_manos_viejas2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "ex_cayote_3", start: 1405.06, dur: 2.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_manos_2.jpg" hue="amber" /> },
  { key: "ex_cayote_4", start: 1407.68, dur: 13.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/intro_caramelo.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "ex_rapa_1", start: 1420.99, dur: 5.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_cocina2_2.jpg" hue="amber" /> },
  { key: "ex_rapa_2", start: 1426.5, dur: 6.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_campo_fruta.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "ex_rapa_3", start: 1433.26, dur: 11.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ex_rapa_3.mp4" hue="amber" fit="blur" /> },
  { key: "ex_rapa_4", start: 1444.94, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ex_rapa_4.mp4" hue="amber" fit="blur" /> },
  { key: "ex_miel_1", start: 1451.04, dur: 2.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ex_miel_1.mp4" hue="amber" fit="blur" /> },
  { key: "ex_miel_2", start: 1453.67, dur: 11.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ex_miel_2.mp4" hue="amber" fit="blur" /> },
  { key: "ex_miel_3", start: 1465.51, dur: 7.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_cocina1_1.jpg" hue="amber" /> },
  { key: "ex_miel_4", start: 1472.65, dur: 13.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_abuela_cocina1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "cierre_1", start: 1486.35, dur: 4.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cierre_1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "cierre_2", start: 1490.68, dur: 13.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_abuela_cocina2.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "cierre_11", start: 1504.46, dur: 2.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_cocina2_1.jpg" hue="amber" /> },
  { key: "cierre_3", start: 1507.15, dur: 2.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cierre_3.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "cierre_4", start: 1509.28, dur: 2.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_abuela_1.jpg" hue="amber" /> },
  { key: "cierre_5", start: 1511.48, dur: 11.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_almibar.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "cierre_6", start: 1522.98, dur: 11.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_familia1_1.jpg" hue="amber" /> },
  { key: "cierre_7", start: 1534.34, dur: 6.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_azucar_caramelo1.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "cierre_12", start: 1540.42, dur: 11.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_manos_1.jpg" hue="amber" /> },
  { key: "cierre_8", start: 1552.06, dur: 37.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_cuchara_madera.mp4" hue="amber" zoom={[1.04,1.06]} /> },
  { key: "cierre_9", start: 1589.56, dur: 3.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_cocina1_3.jpg" hue="amber" /> },
  { key: "cierre_13", start: 1593.51, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/amb_cocina_vieja1.mp4" hue="amber" fit="blur" /> },
  { key: "cierre_10", start: 1596.48, dur: 8.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/vintage_abuela_2.jpg" hue="amber" /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "teasecards_v2_cmp_tease", start: 17.24, dur: 8.6, kind: "teasecards", el: (d) => <FoodTeaseCards durationInFrames={d} cards={[{"src":"real/card_d01.jpg","label":"Alfajor de maicena"},{"src":"real/card_d02.jpg","label":"Dulce de leche"},{"src":"real/card_d03.jpg","label":"Arroz con leche"},{"src":"real/card_d05.jpg","label":"Bocaditos de coco"},{"src":"real/card_d11.jpg","label":"Dulce de membrillo"},{"src":"real/card_d10.jpg","label":"Alfeñiques"},{"src":"real/card_d16.jpg","label":"Bombones caseros"}]} eyebrow="Algunos merecen volver…" title="¿Cuántos probaste?" /> },
  { key: "numerodulce_v2_cmp_aroma", start: 44.04, dur: 3.2, kind: "numerodulce", el: (d) => <NumeroDulce durationInFrames={d} number="20" name="dulces que se perdieron" total="recetas" image="broll/intro_caramelo.mp4" eyebrow="¿Sentís ese olor?" /> },
  { key: "numerodulce_v2_cmp_stat20", start: 63.24, dur: 3.8, kind: "numerodulce", el: (d) => <NumeroDulce durationInFrames={d} number="20" name="hechos con las manos" total="20" image="broll/intro_caramelo.mp4" eyebrow="Hoy te cuento" /> },
  { key: "top_v2_1", start: 83.11, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={1} title="Alfajores de maicena" total={20} image="broll/d01_alfajor_1.mp4" /> },
  { key: "fichadulce_v2_1_6", start: 90.31, dur: 5.2, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d01.jpg" title="Alfajor de maicena" notes={["Maicena y muy poca harina","Dulce de leche generoso","Todo el borde en coco"]} bg="broll/d01_alfajor_1.mp4" side="left" eyebrow="El rey de la merienda" /> },
  { key: "citaabuela_v2_1_19.2", start: 103.51, dur: 4.27, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="y eso mi amor no se compra en ningun quiosco" image="real/alfajores_maicena_1.jpg" words={[{"t":"y","at":0},{"t":"eso","at":0.04},{"t":"mi","at":0.25},{"t":"amor,","at":0.45},{"t":"no","at":0.89},{"t":"se","at":0.95},{"t":"compra","at":1.09},{"t":"en","at":1.59},{"t":"ningún","at":1.93},{"t":"quiosco.","at":2.85}]} fontSize={74} /> },
  { key: "top_v2_2", start: 143.62, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={2} title="Dulce de leche" total={20} image="broll/d02_dl_1.mp4" /> },
  { key: "ingredientesflotan_v2_2_6", start: 150.82, dur: 6.1, kind: "ingredientesflotan", el: (d) => <IngredientesFlotan durationInFrames={d} items={["Leche","Azúcar","Bicarbonato"]} image="broll/d02_dulceleche.mp4" title="El dulce de leche casero" ats={[0,0.7,2.7]} /> },
  { key: "antesahora_v2_2_20.1", start: 164.92, dur: 4.81, kind: "antesahora", el: (d) => <AntesAhora durationInFrames={d} beforeImage="real/dulce_de_leche_1.jpg" afterImage="real/dulce_de_leche_2.jpg" beforeLabel="Casero" afterLabel="En pote" /> },
  { key: "top_v2_3", start: 223.44, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={3} title="Arroz con leche" total={20} image="broll/d03_arroz_2.mp4" /> },
  { key: "fichadulce_v2_3_6", start: 230.64, dur: 4.6, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d03.jpg" title="Arroz con leche" notes={["Canela y cáscara de limón","Revolver sin que se pegue","Cremoso, en su punto"]} bg="broll/d03_arroz_2.mp4" side="right" eyebrow="El consuelo del invierno" /> },
  { key: "citaabuela_v2_3_18.6", start: 243.24, dur: 4.13, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="era un abrazo en un plato" image="real/arroz_con_leche_1.jpg" words={[{"t":"era","at":0},{"t":"un","at":0.24},{"t":"abrazo","at":0.36},{"t":"en","at":0.99},{"t":"un","at":1.15},{"t":"plato.","at":1.33}]} fontSize={92} /> },
  { key: "top_v2_4", start: 279.23, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={4} title="Mazamorra" total={20} image="broll/d04_maza_1.mp4" /> },
  { key: "ingredientesflotan_v2_4_6", start: 286.43, dur: 4.25, kind: "ingredientesflotan", el: (d) => <IngredientesFlotan durationInFrames={d} items={["Maíz blanco","Remojado"]} image="broll/d04_mazamorra.mp4" title="El dulce de la tierra" ats={[0,1.45]} /> },
  { key: "citaabuela_v2_4_18.25", start: 298.68, dur: 4.23, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="perdimos un pedacito de quienes eramos" image="real/mazamorra_1.jpg" words={[{"t":"Perdimos","at":0},{"t":"un","at":0.52},{"t":"pedacito","at":0.62},{"t":"de","at":1.13},{"t":"quiénes","at":1.22},{"t":"éramos,","at":1.83}]} fontSize={78} /> },
  { key: "top_v2_5", start: 340.36, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={5} title="Bocaditos de coco" total={20} image="broll/d05_coco_1.mp4" /> },
  { key: "fichadulce_v2_5_6", start: 347.56, dur: 4.6, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d05.jpg" title="Bocaditos de coco" notes={["Coco y dulce de leche","Bolitas con las manos","Algunos con chocolate"]} bg="broll/d05_coco_1.mp4" side="left" eyebrow="Se hacían con los nietos" /> },
  { key: "citaabuela_v2_5_18.6", start: 360.16, dur: 7.17, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="eran feos disparejos cada uno de un tamano distinto y eran perfectos" image="real/bocaditos_coco_1.jpg" words={[{"t":"Eran","at":0},{"t":"feos,","at":0.36},{"t":"disparejos,","at":0.9},{"t":"cada","at":2.02},{"t":"uno","at":2.34},{"t":"de","at":2.61},{"t":"un","at":2.82},{"t":"tamaño","at":2.97},{"t":"distinto","at":3.59},{"t":"y","at":4.32},{"t":"eran","at":4.41},{"t":"perfectos.","at":4.77}]} fontSize={70} /> },
  { key: "top_v2_6", start: 399.1, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={6} title="Turrón de quaker" total={20} image="broll/d06_quaker_2.mp4" /> },
  { key: "ingredientesflotan_v2_6_6", start: 406.3, dur: 7.91, kind: "ingredientesflotan", el: (d) => <IngredientesFlotan durationInFrames={d} items={["Avena","Azúcar quemada","Manteca"]} image="broll/d06_turronquaker.mp4" title="Con lo de la alacena" ats={[0,0.94,5.11]} /> },
  { key: "top_v2_7", start: 465.01, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={7} title="Mantecol" total={20} image="broll/d07_mantecol_2.mp4" /> },
  { key: "fichadulce_v2_7_6", start: 472.21, dur: 4.6, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d07.jpg" title="Mantecol casero" notes={["Maní tostado y molido","Azúcar y clara batida","Cortado en barritas"]} bg="broll/d07_mantecol_2.mp4" side="right" eyebrow="Un lujo de monedas" /> },
  { key: "citaabuela_v2_7_18.6", start: 484.81, dur: 5.51, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="de tanto ganar ratos nos quedamos sin sabores" image="real/mantecol_1.jpg" words={[{"t":"de","at":0},{"t":"tanto","at":0.27},{"t":"ganar","at":0.61},{"t":"ratos","at":1.32},{"t":"nos","at":2.03},{"t":"quedamos","at":2.63},{"t":"sin","at":3.6},{"t":"sabores.","at":4.03}]} fontSize={80} /> },
  { key: "top_v2_8", start: 521.54, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={8} title="Cascaritas de naranja" total={20} image="broll/d08_casca_1.mp4" /> },
  { key: "antesahora_v2_8_6", start: 528.74, dur: 5, kind: "antesahora", el: (d) => <AntesAhora durationInFrames={d} beforeImage="real/cascaritas_naranja_1.jpg" afterImage="real/cascaritas_naranja_2.png" beforeLabel="Se aprovechaba" afterLabel="A la basura" /> },
  { key: "top_v2_9", start: 583.74, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={9} title="Colación" total={20} image="broll/d09_colacion_1.mp4" /> },
  { key: "fichadulce_v2_9_6", start: 590.94, dur: 4.6, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d09.jpg" title="Colación" notes={["Cascarita dura de azúcar","Relleno de dulce de leche","Bañadas en glasé"]} bg="broll/d09_colacion_1.mp4" side="left" eyebrow="De casamientos y fiestas" /> },
  { key: "citaabuela_v2_9_18.6", start: 603.54, dur: 3.82, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="era una forma callada de amor" image="real/colacion_1.jpg" words={[{"t":"era","at":0},{"t":"una","at":0.18},{"t":"forma","at":0.4},{"t":"callada","at":0.89},{"t":"de","at":1.28},{"t":"amor.","at":1.42}]} fontSize={82} /> },
  { key: "top_v2_10", start: 645.92, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={10} title="Alfeñiques" total={20} image="broll/d10_alfe_2.mp4" /> },
  { key: "citaabuela_v2_10_6", start: 653.12, dur: 4.66, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="y ver nacer la magia era la mitad de la felicidad" image="real/alfeniques_1.jpg" words={[{"t":"y","at":0},{"t":"ver","at":0.04},{"t":"nacer","at":0.33},{"t":"la","at":0.88},{"t":"magia","at":1.1},{"t":"era","at":1.66},{"t":"la","at":1.98},{"t":"mitad","at":2.3},{"t":"de","at":2.76},{"t":"la","at":2.98},{"t":"felicidad.","at":3.2}]} fontSize={78} /> },
  { key: "top_v2_11", start: 709.84, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={11} title="Dulce de membrillo" total={20} image="broll/d11_memb_1.mp4" /> },
  { key: "fichadulce_v2_11_6", start: 717.04, dur: 4.97, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d11.jpg" title="Dulce de membrillo" notes={["Membrillos hervidos","Horas revolviendo","En cajones de madera"]} bg="broll/d11_memb_1.mp4" side="right" eyebrow="El del vigilante" /> },
  { key: "top_v2_12", start: 788.8, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={12} title="Arrope" total={20} image="broll/d12_arrope_1.mp4" /> },
  { key: "citaabuela_v2_12_6", start: 796, dur: 5.41, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="perder el arrope es perder la memoria mas vieja del dulce" image="real/arrope_1.jpg" words={[{"t":"Perder","at":0},{"t":"el","at":0.42},{"t":"arrope","at":0.56},{"t":"es","at":0.98},{"t":"perder","at":1.13},{"t":"la","at":1.54},{"t":"memoria","at":1.89},{"t":"más","at":2.17},{"t":"vieja","at":2.45},{"t":"del","at":2.82},{"t":"dulce,","at":3.01}]} fontSize={74} /> },
  { key: "top_v2_13", start: 844.41, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={13} title="Melcocha" total={20} image="broll/d13_melcocha_close.mp4" /> },
  { key: "fichadulce_v2_13_6", start: 851.61, dur: 4.6, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d13.jpg" title="Melcocha" notes={["Miel o azúcar","Estirada a mano","El dulce de las ferias"]} bg="broll/d13_melcocha_close.mp4" side="left" eyebrow="Un arte de circo" /> },
  { key: "top_v2_14", start: 906.85, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={14} title="Caramelos de leche" total={20} image="broll/d14_caram_4.mp4" /> },
  { key: "ingredientesflotan_v2_14_6", start: 914.05, dur: 4.45, kind: "ingredientesflotan", el: (d) => <IngredientesFlotan durationInFrames={d} items={["Leche","Azúcar","Manteca"]} image="broll/d14_caramelosleche.mp4" title="Los del delantal" ats={[0,0.77,1.65]} /> },
  { key: "citaabuela_v2_14_18.45", start: 926.5, dur: 4.49, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="era amor puro escondido en un papelito" image="real/caramelos_leche_1.jpg" words={[{"t":"era","at":0},{"t":"amor","at":0.3},{"t":"puro","at":0.51},{"t":"escondido","at":0.93},{"t":"en","at":2.25},{"t":"un","at":2.54},{"t":"papelito.","at":2.95}]} fontSize={82} /> },
  { key: "top_v2_15", start: 970.29, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={15} title="Ambrosía" total={20} image="broll/d15_ambrosia.mp4" /> },
  { key: "ingredientesflotan_v2_15_6", start: 977.49, dur: 6.38, kind: "ingredientesflotan", el: (d) => <IngredientesFlotan durationInFrames={d} items={["Yemas de huevo","Almíbar"]} image="broll/d15_ambrosia.mp4" title="Con lo que sobraba" ats={[0,3.58]} /> },
  { key: "top_v2_16", start: 1033.61, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={16} title="Bombones caseros" total={20} image="broll/d16_bomb_1.mp4" /> },
  { key: "antesahora_v2_16_6", start: 1040.81, dur: 4.64, kind: "antesahora", el: (d) => <AntesAhora durationInFrames={d} beforeImage="real/bombones_caseros_1.jpg" afterImage="real/bombones_caseros_2.jpg" beforeLabel="Caseros" afterLabel="Comprados" /> },
  { key: "citaabuela_v2_16_18.64", start: 1053.45, dur: 3.67, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="la pascua es un poco menos pascua" image="real/bombones_caseros_1.jpg" words={[{"t":"la","at":0},{"t":"pascua","at":0.21},{"t":"es","at":0.93},{"t":"un","at":1.17},{"t":"poco","at":1.41},{"t":"menos","at":1.9},{"t":"pascua.","at":2.51}]} fontSize={84} /> },
  { key: "top_v2_17", start: 1097.7, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={17} title="Chupetines" total={20} image="broll/d17_chup_1.mp4" /> },
  { key: "fichadulce_v2_17_6", start: 1104.9, dur: 4.6, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d17.jpg" title="Chupetines caseros" notes={["Caramelo con colorante","Sobre papel manteca","Un palito en el borde"]} bg="broll/d17_chup_1.mp4" side="right" eyebrow="Las tardes de lluvia" /> },
  { key: "top_v2_18", start: 1161.38, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={18} title="Frutas abrillantadas" total={20} image="broll/d18_fruta_1.mp4" /> },
  { key: "citaabuela_v2_18_6", start: 1168.58, dur: 1.6, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="se podia volver joya" image="real/frutas_abrillantadas_1.jpg" words={[{"t":"se","at":0},{"t":"podía","at":0.15},{"t":"volver","at":0.64},{"t":"joya,","at":1.12}]} fontSize={84} /> },
  { key: "top_v2_19", start: 1227.81, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={19} title="Conitos de dulce de leche" total={20} image="broll/d19_coni_1.mp4" /> },
  { key: "fichadulce_v2_19_6", start: 1235.01, dur: 4.6, kind: "fichadulce", el: (d) => <FichaDulce durationInFrames={d} image="real/card_d19.jpg" title="Conitos de dulce de leche" notes={["Cucurucho de merengue","Relleno bien firme","Puntita en chocolate"]} bg="broll/d19_coni_1.mp4" side="left" eyebrow="El mimo de los cumpleaños" /> },
  { key: "citaabuela_v2_19_18.6", start: 1247.61, dur: 1.94, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="es de lo que mas extrano" image="real/conitos_ddl_1.jpg" words={[{"t":"es","at":0},{"t":"de","at":0.14},{"t":"lo","at":0.29},{"t":"que","at":0.42},{"t":"más","at":0.64},{"t":"extraño.","at":0.93}]} fontSize={80} /> },
  { key: "top_v2_20", start: 1291.4, dur: 4, kind: "topdulce", el: (d) => <TopDulce durationInFrames={d} index={20} title="Quesillo con arrope" total={20} image="broll/d20_quesillo.mp4" /> },
  { key: "antesahora_v2_20_6", start: 1298.6, dur: 4.4, kind: "antesahora", el: (d) => <AntesAhora durationInFrames={d} beforeImage="real/quesillo_arrope_1.jpg" afterImage="real/quesillo_arrope_2.jpg" beforeLabel="Del patio" afterLabel="De fábrica" /> },
  { key: "citaabuela_v2_20_18.4", start: 1311, dur: 4.26, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="sino del propio patio" image="real/quesillo_arrope_1.jpg" words={[{"t":"sino","at":0},{"t":"del","at":0.88},{"t":"propio","at":1},{"t":"patio,","at":1.86}]} fontSize={80} /> },
  { key: "cita_v2_cierre", start: 1526.35, dur: 4.42, kind: "citaabuela", el: (d) => <CitaAbuela durationInFrames={d} text="lo dificil de recuperar es el gesto" image="real/vintage_familia1_1.jpg" words={[{"t":"lo","at":0},{"t":"difícil","at":0.16},{"t":"de","at":0.79},{"t":"recuperar","at":0.98},{"t":"es","at":1.65},{"t":"el","at":1.97},{"t":"gesto.","at":2.02}]} fontSize={88} /> },
];
