// cues_plomeria.gen.tsx — GENERADO por beatsheet.mjs desde plomeria.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/plomeria.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { DiagramBoard } from "./scenes/DiagramBoard";
import { AgedDoc } from "./scenes/AgedDoc";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { CalloutMark } from "./scenes/CalloutMark";
import { OxStatPop, OxMethodCard, OxRuleStrip, OxMaterialTag, OxSidePanel, OxPhotoStack, OxQuoteSplit } from "./overlays/OxCards";

const A = COLORS.accent;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "pl_fill_invoice2", start: 0.09, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_invoice2.png" hue="amber" darken={0} /> },
  { key: "pl_plumber_invoice", start: 2.16, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_plumber_invoice.mp4" hue="amber" darken={0} /> },
  { key: "pl_clog_unclog_quick", start: 3.48, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_clog_unclog_quick.mp4" hue="red" darken={0} /> },
  { key: "pl_watch_clock", start: 6.64, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_watch_clock.mp4" hue="blue" darken={0} /> },
  { key: "cmp_callout_st_7", start: 6.64, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="10 min" image="real/pl_fill_invoice2.png" caption="Lo que tarda el plomero, y te cobra una fortuna." accent="danger" hue="blue" /> },
  { key: "pl_man_watching_plumber", start: 8.54, dur: 4.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_man_watching_plumber.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_shame_face", start: 12.92, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_shame_face.png" hue="red" darken={0} /> },
  { key: "pl_kitchen_cupboard", start: 22.78, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_kitchen_cupboard.png" hue="red" darken={0} /> },
  { key: "pl_old_plumber_mate", start: 32.44, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_old_plumber_mate.png" hue="blue" darken={0} /> },
  { key: "pl_money_handed", start: 35.88, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_money_handed.mp4" hue="amber" darken={0} /> },
  { key: "cmp_bars_st_36", start: 35.88, dur: 6.5, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"El plomero por 10 minutos","value":100,"display":"$$$","tone":"danger"},{"label":"Hacerlo vos mismo","value":3,"display":"$2","winner":true}]} title="Lo que pagás de más" hue="red" /> },
  { key: "pl_plumber_knows", start: 40.69, dur: 1.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_plumber_knows.mp4" hue="red" darken={0} /> },
  { key: "pl_cheap_tricks_tools", start: 42.98, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_cheap_tricks_tools.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_pass_all", start: 45.93, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_pass_all.png" hue="red" darken={0} /> },
  { key: "pl_sink_full_water", start: 52.88, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_sink_full_water.png" hue="red" darken={0} /> },
  { key: "pl_faucet_drip_night", start: 55.68, dur: 4.13, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_faucet_drip_night.png" hue="blue" darken={0} /> },
  { key: "pl_toilet_running", start: 59.51, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_toilet_running.png" hue="amber" darken={0} /> },
  { key: "pl_water_bill_high", start: 61.77, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_water_bill_high.png" hue="red" darken={0} /> },
  { key: "cmp_bars_st_62", start: 61.77, dur: 6.5, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Con la pérdida escondida","value":100,"display":"×2","tone":"danger"},{"label":"Después de arreglarla","value":50,"display":"normal","winner":true}]} title="La factura del agua" hue="red" /> },
  { key: "pl_fill_same_story", start: 66.26, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_same_story.png" hue="amber" darken={0} /> },
  { key: "pl_calling_plumber", start: 69.62, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_calling_plumber.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_fortune_10min", start: 72.94, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_fortune_10min.png" hue="red" darken={0} /> },
  { key: "pl_fill_internet_scams", start: 76.3, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_internet_scams.png" hue="red" darken={0} /> },
  { key: "pl_drain_cleaner_warning", start: 83.7, dur: 2.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_drain_cleaner_warning.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_show_real", start: 85.96, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_show_real.png" hue="blue" darken={0} /> },
  { key: "pl_fill_teach_unclog", start: 89.94, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_teach_unclog.png" hue="amber" darken={0} /> },
  { key: "pl_clearing_drain_no_chem", start: 92.72, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_clearing_drain_no_chem.mp4" hue="blue" darken={0} /> },
  { key: "pl_dye_drop_tank", start: 96.57, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_dye_drop_tank.mp4" hue="amber" darken={0} /> },
  { key: "pl_hidden_leak_meter", start: 99.58, dur: 6.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_hidden_leak_meter.png" hue="red" darken={0} /> },
  { key: "pl_faucet_washer_change", start: 105.32, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_faucet_washer_change.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_cheap_parts", start: 108.26, dur: 1.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_cheap_parts.png" hue="amber" darken={0} /> },
  { key: "pl_fill_whole_visit", start: 109.87, dur: 2.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_whole_visit.png" hue="blue" darken={0} /> },
  { key: "pl_fill_stay_end", start: 112.1, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_stay_end.png" hue="red" darken={0} /> },
  { key: "pl_fill_everyone_mistake", start: 115.72, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_everyone_mistake.png" hue="blue" darken={0} /> },
  { key: "pl_fill_seems_help", start: 119.26, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_seems_help.png" hue="blue" darken={0} /> },
  { key: "pl_fill_destroying_pipes", start: 119.45, dur: 5.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_destroying_pipes.png" hue="blue" darken={0} /> },
  { key: "pl_pipe_splits", start: 125, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pipe_splits.mp4" hue="amber" darken={0} /> },
  { key: "pl_chemical_eating_pipe", start: 126.32, dur: 1.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_chemical_eating_pipe.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_else_useless", start: 127.24, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_else_useless.png" hue="red" darken={0} /> },
  { key: "pl_fill_plumber_secret", start: 131.22, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_plumber_secret.png" hue="blue" darken={0} /> },
  { key: "pl_fill_plumber_account", start: 139.06, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_plumber_account.png" hue="red" darken={0} /> },
  { key: "pl_bill_doubled", start: 143.24, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_bill_doubled.png" hue="red" darken={0} /> },
  { key: "pl_fill_toilet_months", start: 146.3, dur: 2.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_toilet_months.png" hue="blue" darken={0} /> },
  { key: "pl_toilet_silent_leak", start: 148.07, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_toilet_silent_leak.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_liters_drain", start: 151.19, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_liters_drain.png" hue="red" darken={0} /> },
  { key: "cmp_callout_st_151", start: 151.19, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Miles de litros" image="real/pl_fill_toilet_months.png" caption="Lo que tira el inodoro que pierde en silencio." accent="danger" hue="blue" /> },
  { key: "pl_drip_bucket_summer", start: 156.86, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_drip_bucket_summer.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_buckets_wasted", start: 159.94, dur: 6.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_buckets_wasted.png" hue="red" darken={0} /> },
  { key: "pl_fill_water_rising_sink", start: 165.88, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_water_rising_sink.png" hue="red" darken={0} /> },
  { key: "pl_emergency_plumber_triple", start: 168.82, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_emergency_plumber_triple.mp4" hue="red" darken={0} /> },
  { key: "pl_sink_overflow_night", start: 170.14, dur: 0.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_sink_overflow_night.mp4" hue="blue" darken={0} /> },
  { key: "pl_damp_wall_stain", start: 170.72, dur: 4.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_damp_wall_stain.mp4" hue="amber" darken={0} /> },
  { key: "pl_pipe_leak_inside_wall", start: 174.63, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pipe_leak_inside_wall.mp4" hue="red" darken={0} /> },
  { key: "pl_rotted_wall", start: 177.52, dur: 5.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_rotted_wall.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_grabbed_neck", start: 183.15, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_grabbed_neck.png" hue="amber" darken={0} /> },
  { key: "pl_fill_changes_all", start: 193.86, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_changes_all.png" hue="blue" darken={0} /> },
  { key: "pl_fill_not_broken", start: 198.39, dur: 6.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_not_broken.png" hue="amber" darken={0} /> },
  { key: "cmp_diagram_5_1", start: 204.67, dur: 3.43, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_5_1.mp4" pages={[{"image":"img/dg_pl_causas.png","eyebrow":"Grasa y pelo, una goma, una unión floja"}]} /> },
  { key: "pl_grease_hair_elbow", start: 207.7, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_grease_hair_elbow.png" hue="red" darken={0} /> },
  { key: "pl_worn_washer", start: 211.78, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_worn_washer.png" hue="blue" darken={0} /> },
  { key: "cmp_callout_st_212", start: 211.78, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$2" image="real/pl_faucet_washer_small.png" caption="La gomita que arregla el problema entero." accent="good" hue="blue" /> },
  { key: "pl_loose_joint_drip", start: 213.94, dur: 2.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_loose_joint_drip.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_plumber_knows2", start: 216.09, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_plumber_knows2.png" hue="amber" darken={0} /> },
  { key: "pl_plumber_quick_fix", start: 220.34, dur: 6.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_plumber_quick_fix.mp4" hue="red" darken={0} /> },
  { key: "pl_knowing_what_to_touch", start: 226.79, dur: 2.49, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_knowing_what_to_touch.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_free_knowledge", start: 228.98, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_free_knowledge.png" hue="red" darken={0} /> },
  { key: "pl_fill_rule_one_note", start: 232.1, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_rule_one_note.png" hue="red" darken={0} /> },
  { key: "pl_fill_before_calling", start: 237.3, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_before_calling.png" hue="amber" darken={0} /> },
  { key: "cmp_aged_st_237", start: 237.3, dur: 6.5, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="REGLA NÚMERO UNO" lines={[{"text":"Lo mecánico y lo barato, primero"},{"text":"Casi siempre, con eso alcanza"},{"text":"El 80% lo resolvés solo en 10 minutos","mark":true}]} eyebrow="Aunque te olvides de todo lo demás" hue="amber" /> },
  { key: "pl_mechanical_first", start: 241.04, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_mechanical_first.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_usually_enough", start: 244.98, dur: 2.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_usually_enough.png" hue="blue" darken={0} /> },
  { key: "pl_methods_intro", start: 247.61, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_methods_intro.mp4" hue="red" darken={0} /> },
  { key: "pl_clogged_sink_slow", start: 254.67, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_clogged_sink_slow.mp4" hue="red" darken={0} /> },
  { key: "cmp_process_st_255", start: 254.67, dur: 6.5, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"La sopapa","desc":"tapá el rebosadero, agua que cubra, tirones secos"},{"title":"Bicarbonato + vinagre","desc":"y una pava de agua hirviendo"},{"title":"El sifón","desc":"desarmalo: ahí está el 80% del tapón"}]} eyebrow="Tres pasos, sin químicos" title="Destapar la pileta" hue="blue" /> },
  { key: "pl_fill_clog_near", start: 261.94, dur: 3.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_clog_near.png" hue="red" darken={0} /> },
  { key: "cmp_diagram_7_1", start: 265.24, dur: 7.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_7_1.mp4" pages={[{"image":"img/dg_pl_tapon.png","eyebrow":"El 90% de las veces, en el primer codo"}]} /> },
  { key: "pl_fill_you_remove", start: 268.02, dur: 5.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_you_remove.png" hue="red" darken={0} /> },
  { key: "pl_plunger_corner", start: 273.19, dur: 4.21, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_plunger_corner.png" hue="amber" darken={0} /> },
  { key: "pl_fill_used_wrong", start: 277.1, dur: 4.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_used_wrong.png" hue="red" darken={0} /> },
  { key: "pl_fill_overflow_hole", start: 280.87, dur: 3.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_overflow_hole.png" hue="blue" darken={0} /> },
  { key: "pl_fill_rag_overflow", start: 284.18, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_rag_overflow.png" hue="blue" darken={0} /> },
  { key: "pl_seal_overflow_rag", start: 287.14, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_seal_overflow_rag.mp4" hue="red" darken={0} /> },
  { key: "pl_water_covers_plunger", start: 294.2, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_water_covers_plunger.mp4" hue="blue" darken={0} /> },
  { key: "pl_plunger_seal_drain", start: 301.55, dur: 2.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_plunger_seal_drain.mp4" hue="amber" darken={0} /> },
  { key: "pl_plunging_hard", start: 303.88, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_plunging_hard.png" hue="red" darken={0} /> },
  { key: "pl_sink_draining_clear", start: 311.99, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_sink_draining_clear.mp4" hue="blue" darken={0} /> },
  { key: "cmp_oxstack_8_0", start: 324.92, dur: 2.47, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/pl_baking_soda_box.png","real/pl_vinegar_bottle.png","real/pl_kettle_boiling.png"]} captions={["Bicarbonato","Vinagre blanco","Agua hirviendo"]} accent="cold" /> },
  { key: "pl_baking_soda_box", start: 326.99, dur: 2.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_baking_soda_box.png" hue="amber" darken={0} /> },
  { key: "pl_vinegar_bottle", start: 329.23, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_vinegar_bottle.png" hue="red" darken={0} /> },
  { key: "pl_kettle_boiling", start: 339.84, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_kettle_boiling.png" hue="blue" darken={0} /> },
  { key: "pl_baking_soda_drain", start: 341.16, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_baking_soda_drain.mp4" hue="amber" darken={0} /> },
  { key: "pl_vinegar_pour_drain", start: 342.48, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_vinegar_pour_drain.mp4" hue="red" darken={0} /> },
  { key: "pl_foam_fizz_drain", start: 343.8, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_foam_fizz_drain.mp4" hue="blue" darken={0} /> },
  { key: "pl_reaction_soften_grease", start: 345.12, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_reaction_soften_grease.mp4" hue="amber" darken={0} /> },
  { key: "pl_boiling_water_kettle", start: 346.44, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_boiling_water_kettle.mp4" hue="red" darken={0} /> },
  { key: "pl_hot_water_melts_grease", start: 347.76, dur: 2.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_hot_water_melts_grease.mp4" hue="blue" darken={0} /> },
  { key: "pl_grease_soap_clog", start: 349.49, dur: 4.93, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_grease_soap_clog.png" hue="amber" darken={0} /> },
  { key: "pl_fill_hair_clog_bath", start: 354.12, dur: 3.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_hair_clog_bath.png" hue="amber" darken={0} /> },
  { key: "pl_fill_plunger_no_hair", start: 357.24, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_plunger_no_hair.png" hue="amber" darken={0} /> },
  { key: "pl_hair_clog_ball", start: 360.56, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_hair_clog_ball.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_hook_grab", start: 363.06, dur: 3.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_hook_grab.png" hue="amber" darken={0} /> },
  { key: "pl_drain_snake_tool", start: 366.67, dur: 3.95, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_drain_snake_tool.png" hue="red" darken={0} /> },
  { key: "pl_wire_hook_hanger", start: 370.32, dur: 6.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_wire_hook_hanger.mp4" hue="blue" darken={0} /> },
  { key: "pl_pull_hair_out", start: 376.78, dur: 2.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pull_hair_out.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_gross_but_works", start: 379.14, dur: 1.63, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_gross_but_works.png" hue="red" darken={0} /> },
  { key: "cmp_callout_st_380", start: 380.47, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Gratis" image="real/pl_clogged_sink_slow.png" caption="Sacar la maraña de pelo con un alambre." accent="good" hue="blue" /> },
  { key: "pl_fill_plumber_hides", start: 383.91, dur: 6.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_plumber_hides.png" hue="amber" darken={0} /> },
  { key: "cmp_diagram_10_0", start: 390.27, dur: 1.72, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_10_0.mp4" pages={[{"image":"img/dg_pl_sifon.png","eyebrow":"Se desenrosca con la mano y ahí está el tapón"}]} /> },
  { key: "pl_p_trap_under_sink", start: 391.59, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_p_trap_under_sink.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_trap_water_seal", start: 394.15, dur: 5.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_trap_water_seal.png" hue="red" darken={0} /> },
  { key: "pl_fill_lowest_point", start: 399.04, dur: 6.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_lowest_point.png" hue="amber" darken={0} /> },
  { key: "pl_fill_trap_unscrews", start: 405.26, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_trap_unscrews.png" hue="amber" darken={0} /> },
  { key: "pl_fill_unscrew_hand", start: 408.05, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_unscrew_hand.png" hue="amber" darken={0} /> },
  { key: "pl_bucket_under_trap", start: 411.3, dur: 1.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_bucket_under_trap.mp4" hue="amber" darken={0} /> },
  { key: "pl_unscrew_trap", start: 412.7, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_unscrew_trap.mp4" hue="red" darken={0} /> },
  { key: "pl_pliers_loosen_trap", start: 414.02, dur: 1.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pliers_loosen_trap.mp4" hue="blue" darken={0} /> },
  { key: "pl_gunk_in_trap", start: 415.54, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_gunk_in_trap.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_food_scraps", start: 418.33, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_food_scraps.png" hue="red" darken={0} /> },
  { key: "pl_clean_reattach_trap", start: 422.15, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_clean_reattach_trap.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_ten_min_fortune", start: 425.19, dur: 5.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_ten_min_fortune.png" hue="blue" darken={0} /> },
  { key: "pl_fill_exact_amounts", start: 430.18, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_exact_amounts.png" hue="red" darken={0} /> },
  { key: "pl_fill_which_snake", start: 433, dur: 5.45, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_which_snake.png" hue="red" darken={0} /> },
  { key: "cmp_callout_st_438", start: 438.15, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="10 min" image="real/pl_clogged_sink_slow.png" caption="Desarmar el sifón: por esto el plomero te cobra fortunas." accent="cold" hue="blue" /> },
  { key: "cmp_diagram_11_0", start: 440.46, dur: 4.6, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_11_0.mp4" pages={[{"image":"img/dg_pl_manual.png","eyebrow":"El Manual de Reparaciones Caseras"}]} /> },
  { key: "pl_cracked_nut_trap", start: 444.66, dur: 6.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_cracked_nut_trap.mp4" hue="amber" darken={0} /> },
  { key: "pl_manual_phone_steps", start: 451.15, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_manual_phone_steps.png" hue="red" darken={0} /> },
  { key: "pl_fill_keep_watching", start: 458.94, dur: 3.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_keep_watching.png" hue="amber" darken={0} /> },
  { key: "pl_fill_saves_money", start: 462.03, dur: 5.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_saves_money.png" hue="amber" darken={0} /> },
  { key: "pl_fill_taught_unclog", start: 466.95, dur: 3.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_taught_unclog.png" hue="blue" darken={0} /> },
  { key: "pl_fill_more_costly", start: 470.02, dur: 5.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_more_costly.png" hue="blue" darken={0} /> },
  { key: "pl_no_visible_leak", start: 475.2, dur: 5.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_no_visible_leak.png" hue="amber" darken={0} /> },
  { key: "pl_bill_doubled_zoom", start: 479.96, dur: 2.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_bill_doubled_zoom.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_wall_stain_norain", start: 482.04, dur: 2.37, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_wall_stain_norain.png" hue="blue" darken={0} /> },
  { key: "pl_wall_damp_no_rain", start: 484.11, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_wall_damp_no_rain.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_how_to_know", start: 493.06, dur: 6.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_how_to_know.png" hue="red" darken={0} /> },
  { key: "pl_water_meter_dial", start: 499.32, dur: 2.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_water_meter_dial.mp4" hue="red" darken={0} /> },
  { key: "pl_close_all_taps", start: 501.54, dur: 6.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_close_all_taps.mp4" hue="blue" darken={0} /> },
  { key: "pl_look_at_meter", start: 507.39, dur: 4.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_look_at_meter.mp4" hue="amber" darken={0} /> },
  { key: "pl_meter_still_spinning", start: 512, dur: 2.35, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_meter_still_spinning.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_leak_somewhere", start: 514.05, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_leak_somewhere.png" hue="red" darken={0} /> },
  { key: "pl_fill_water_leaving", start: 517.15, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_water_leaving.png" hue="red" darken={0} /> },
  { key: "pl_fill_free_test", start: 520.35, dur: 4.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_free_test.png" hue="red" darken={0} /> },
  { key: "pl_fill_most_common_leak", start: 524.3, dur: 2.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_most_common_leak.png" hue="blue" darken={0} /> },
  { key: "pl_fill_inflates_bill", start: 526.89, dur: 4.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_inflates_bill.png" hue="blue" darken={0} /> },
  { key: "pl_toilet_silent", start: 531.24, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_toilet_silent.png" hue="blue" darken={0} /> },
  { key: "cmp_process_st_531", start: 531.24, dur: 6.5, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"El medidor","desc":"cerrá todo: ¿sigue girando?"},{"title":"La gota de tinta","desc":"en la mochila, esperá 20 min"},{"title":"Cambiá la goma","desc":"cuesta $2 y se hace con la mano"}]} eyebrow="Donde se va tu factura" title="Cazar la pérdida escondida" hue="blue" /> },
  { key: "cmp_diagram_14_1", start: 534.35, dur: 7.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_14_1.mp4" pages={[{"image":"img/dg_pl_sapito.png","eyebrow":"Endurecida, deja pasar agua día y noche"}]} /> },
  { key: "pl_fill_seal_hardens", start: 540.91, dur: 6.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_seal_hardens.png" hue="red" darken={0} /> },
  { key: "pl_fill_day_and_night", start: 546.93, dur: 1.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_day_and_night.png" hue="red" darken={0} /> },
  { key: "cmp_callout_st_548", start: 547.86, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Día y noche" image="real/pl_fill_toilet_months.png" caption="El inodoro pierde en silencio, sin parar." accent="danger" hue="blue" /> },
  { key: "pl_thousands_liters", start: 550.87, dur: 3.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_thousands_liters.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_magic_trick", start: 553.88, dur: 3.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_magic_trick.png" hue="blue" darken={0} /> },
  { key: "pl_fill_dye_no_flush", start: 557.31, dur: 2.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_dye_no_flush.png" hue="blue" darken={0} /> },
  { key: "pl_dye_into_tank", start: 559.92, dur: 2.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_dye_into_tank.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_dye_colors_water", start: 562.27, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_dye_colors_water.png" hue="red" darken={0} /> },
  { key: "pl_wait_no_touch", start: 566.39, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_wait_no_touch.mp4" hue="amber" darken={0} /> },
  { key: "pl_colored_water_bowl", start: 570.29, dur: 6.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_colored_water_bowl.mp4" hue="red" darken={0} /> },
  { key: "pl_replace_flapper", start: 576.11, dur: 4.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_replace_flapper.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_five_min_fix", start: 579.96, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_five_min_fix.png" hue="red" darken={0} /> },
  { key: "cmp_callout_st_584", start: 584.1, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="½ factura" image="real/pl_fill_toilet_months.png" caption="Una sola goma del inodoro puede ser la mitad de tu cuenta." accent="amber" hue="blue" /> },
  { key: "pl_fill_faucet_drips2", start: 586.3, dur: 2.51, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_faucet_drips2.png" hue="red" darken={0} /> },
  { key: "pl_dripping_faucet_close", start: 588.51, dur: 6.01, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_dripping_faucet_close.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_one_thing", start: 594.22, dur: 3.09, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_one_thing.png" hue="amber" darken={0} /> },
  { key: "pl_faucet_washer_small", start: 597.01, dur: 3.29, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_faucet_washer_small.png" hue="red" darken={0} /> },
  { key: "pl_fill_worn_years", start: 600, dur: 2.79, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_worn_years.png" hue="amber" darken={0} /> },
  { key: "pl_shutoff_disassemble", start: 602.49, dur: 3.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_shutoff_disassemble.mp4" hue="blue" darken={0} /> },
  { key: "pl_old_washer_out", start: 605.44, dur: 1.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_old_washer_out.mp4" hue="amber" darken={0} /> },
  { key: "pl_new_washer_in", start: 607.05, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_new_washer_in.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_another_problem", start: 615.86, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_another_problem.png" hue="red" darken={0} /> },
  { key: "pl_fill_two_min_fix", start: 619, dur: 5.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_two_min_fix.png" hue="red" darken={0} /> },
  { key: "pl_weak_water_flow", start: 624.32, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_weak_water_flow.mp4" hue="red" darken={0} /> },
  { key: "pl_aerator_tip", start: 631.02, dur: 5.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_aerator_tip.png" hue="blue" darken={0} /> },
  { key: "pl_fill_scale_buildup", start: 636.05, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_scale_buildup.png" hue="amber" darken={0} /> },
  { key: "pl_unscrew_aerator", start: 644.59, dur: 3.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_unscrew_aerator.mp4" hue="amber" darken={0} /> },
  { key: "pl_aerator_soak_vinegar", start: 648.14, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_aerator_soak_vinegar.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_brush_rescrew", start: 651.2, dur: 6.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_brush_rescrew.png" hue="amber" darken={0} /> },
  { key: "pl_fill_showerhead", start: 657.26, dur: 5.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_showerhead.png" hue="amber" darken={0} /> },
  { key: "pl_fill_scale_holes", start: 662.27, dur: 2.73, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_scale_holes.png" hue="blue" darken={0} /> },
  { key: "pl_showerhead_soak", start: 664.7, dur: 2.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_showerhead_soak.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_holes_clear", start: 667.37, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_holes_clear.png" hue="red" darken={0} /> },
  { key: "pl_fill_joint_leaks", start: 671.93, dur: 5.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_joint_leaks.png" hue="amber" darken={0} /> },
  { key: "pl_fill_teflon_wrap", start: 676.95, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_teflon_wrap.png" hue="blue" darken={0} /> },
  { key: "pl_teflon_tape_thread", start: 681.39, dur: 6.25, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_teflon_tape_thread.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_pinhole_pipe", start: 687.34, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_pinhole_pipe.png" hue="amber" darken={0} /> },
  { key: "pl_fill_temp_fix", start: 691.92, dur: 5.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_temp_fix.png" hue="blue" darken={0} /> },
  { key: "pl_epoxy_putty_pipe", start: 697.09, dur: 4.53, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_epoxy_putty_pipe.png" hue="amber" darken={0} /> },
  { key: "pl_pipe_clamp_rubber", start: 701.32, dur: 5.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pipe_clamp_rubber.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_minutes_solution", start: 706.5, dur: 3.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_minutes_solution.png" hue="blue" darken={0} /> },
  { key: "pl_fill_golden_rule", start: 709.86, dur: 3.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_golden_rule.png" hue="blue" darken={0} /> },
  { key: "pl_fill_number_one_cause", start: 712.97, dur: 3.19, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_number_one_cause.png" hue="blue" darken={0} /> },
  { key: "cmp_callout_st_716", start: 715.86, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="La grasa" image="real/pl_grease_hair_elbow.png" caption="La causa #1 de las cañerías tapadas en la cocina." accent="danger" hue="blue" /> },
  { key: "pl_fill_pour_grease", start: 720.92, dur: 2.85, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_pour_grease.png" hue="red" darken={0} /> },
  { key: "pl_pouring_grease_sink", start: 723.47, dur: 4.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pouring_grease_sink.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_grease_sticks", start: 727.22, dur: 4.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_grease_sticks.png" hue="red" darken={0} /> },
  { key: "cmp_diagram_18_1", start: 731.39, dur: 7.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_18_1.mp4" pages={[{"image":"img/dg_pl_grasa.png","eyebrow":"Se enfría y se pega como sebo"}]} /> },
  { key: "pl_grease_jar_trash", start: 739.5, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_grease_jar_trash.mp4" hue="blue" darken={0} /> },
  { key: "pl_drain_strainer", start: 744.5, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_drain_strainer.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_strainer_catches", start: 747, dur: 5.27, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_strainer_catches.png" hue="amber" darken={0} /> },
  { key: "pl_clean_drain_prevent", start: 751.97, dur: 3.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_clean_drain_prevent.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_two_things", start: 755.34, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_two_things.png" hue="blue" darken={0} /> },
  { key: "pl_fill_even_if_never", start: 757.88, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_even_if_never.png" hue="blue" darken={0} /> },
  { key: "pl_fill_most_important", start: 762.4, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_most_important.png" hue="amber" darken={0} /> },
  { key: "pl_fill_go_now", start: 765.21, dur: 5.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_go_now.png" hue="amber" darken={0} /> },
  { key: "pl_main_shutoff_valve", start: 770.47, dur: 3.89, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_main_shutoff_valve.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_cuts_all_water", start: 774.06, dur: 3.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_cuts_all_water.png" hue="amber" darken={0} /> },
  { key: "pl_fill_burst_sunday", start: 776.94, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_burst_sunday.png" hue="amber" darken={0} /> },
  { key: "pl_burst_pipe_flood", start: 781.98, dur: 4.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_burst_pipe_flood.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_house_flooding", start: 786.35, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_house_flooding.png" hue="amber" darken={0} /> },
  { key: "pl_fill_sewer_smell", start: 797.41, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_sewer_smell.png" hue="blue" darken={0} /> },
  { key: "pl_fill_trap_dried", start: 806.91, dur: 3.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_trap_dried.png" hue="amber" darken={0} /> },
  { key: "pl_pour_water_drain", start: 810.18, dur: 5.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pour_water_drain.mp4" hue="amber" darken={0} /> },
  { key: "pl_oil_drain_seal", start: 815.26, dur: 4.97, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_oil_drain_seal.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_promised_start", start: 819.93, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_promised_start.png" hue="red" darken={0} /> },
  { key: "pl_fill_caustic_bottle2", start: 834.9, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_caustic_bottle2.png" hue="red" darken={0} /> },
  { key: "pl_caustic_soda_bottle", start: 843.86, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_caustic_soda_bottle.png" hue="blue" darken={0} /> },
  { key: "cmp_callout_st_844", start: 843.86, dur: 6.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Veneno" image="real/pl_caustic_soda_bottle.png" caption="Te come los caños desde adentro y te quema." accent="danger" hue="blue" /> },
  { key: "pl_fill_burns_everything", start: 846.26, dur: 4.99, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_burns_everything.png" hue="amber" darken={0} /> },
  { key: "pl_fill_eats_metal", start: 850.95, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_eats_metal.png" hue="blue" darken={0} /> },
  { key: "pl_pipe_eaten_inside", start: 855.17, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pipe_eaten_inside.mp4" hue="amber" darken={0} /> },
  { key: "pl_plastic_pipe_warp", start: 862.75, dur: 3.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_plastic_pipe_warp.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_today_tomorrow", start: 866.1, dur: 4.59, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_today_tomorrow.png" hue="blue" darken={0} /> },
  { key: "pl_fill_dangerous_you", start: 870.39, dur: 2.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_dangerous_you.png" hue="amber" darken={0} /> },
  { key: "pl_chemical_skin_burn", start: 872.89, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_chemical_skin_burn.mp4" hue="blue" darken={0} /> },
  { key: "pl_toxic_vapors", start: 875.09, dur: 3.11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_toxic_vapors.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_doesnt_unclog", start: 877.9, dur: 5.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_doesnt_unclog.png" hue="blue" darken={0} /> },
  { key: "pl_fill_caustic_bomb", start: 883.18, dur: 4.67, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_caustic_bomb.png" hue="red" darken={0} /> },
  { key: "pl_clogged_caustic_pool", start: 887.55, dur: 6.83, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_clogged_caustic_pool.mp4" hue="red" darken={0} /> },
  { key: "cmp_aged_st_894", start: 894.08, dur: 6.5, kind: "aged", el: (d) => <AgedDoc durationInFrames={d} heading="REGLA FINAL" lines={[{"text":"Nunca soda cáustica"},{"text":"Te come el caño desde adentro"},{"text":"Lo mecánico antes que lo químico","mark":true}]} eyebrow="El error que destruye los caños" hue="red" /> },
  { key: "pl_fill_most_important_video", start: 895.15, dur: 2.39, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_most_important_video.png" hue="red" darken={0} /> },
  { key: "pl_mechanical_tools_row", start: 897.24, dur: 0.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_mechanical_tools_row.mp4" hue="amber" darken={0} /> },
  { key: "cmp_bars_st_897", start: 897.24, dur: 6.5, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Soda cáustica: arruina el caño","value":100,"display":"✗","tone":"danger"},{"label":"Sopapa, sifón, bicarbonato","value":5,"display":"✓","winner":true}]} title="Mecánico vs químico" hue="amber" /> },
  { key: "pl_fill_tools_lineup", start: 900.35, dur: 6.05, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_tools_lineup.png" hue="amber" darken={0} /> },
  { key: "pl_fill_no_damage", start: 906.1, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_no_damage.png" hue="amber" darken={0} /> },
  { key: "pl_fill_collapsed_real", start: 920.93, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_collapsed_real.png" hue="amber" darken={0} /> },
  { key: "pl_pro_machine_plumber", start: 929.42, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_pro_machine_plumber.mp4" hue="red" darken={0} /> },
  { key: "pl_collapsed_pipe_roots", start: 930.74, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_collapsed_pipe_roots.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_toilet_still_leaks", start: 934.38, dur: 5.23, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_toilet_still_leaks.png" hue="red" darken={0} /> },
  { key: "pl_toilet_mechanism", start: 939.31, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_toilet_mechanism.mp4" hue="amber" darken={0} /> },
  { key: "pl_hot_water_old_pipe", start: 946.04, dur: 6.65, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_hot_water_old_pipe.mp4" hue="red" darken={0} /> },
  { key: "pl_fill_hot_not_boiling", start: 952.39, dur: 3.91, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_hot_not_boiling.png" hue="red" darken={0} /> },
  { key: "pl_fill_same_as_always", start: 956, dur: 4.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_same_as_always.png" hue="blue" darken={0} /> },
  { key: "pl_fill_none_expensive", start: 960.27, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_none_expensive.png" hue="amber" darken={0} /> },
  { key: "pl_fill_built_manual", start: 975.87, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_built_manual.png" hue="red" darken={0} /> },
  { key: "cmp_chips_23_1", start: 984.43, dur: 1.72, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} image="real/pl_phone_calling_bg.png" title="Por qué nadie te lo enseña" chips={["Al plomero no le conviene","que sepas que el 80% lo hacés solo","que sigas levantando el teléfono"]} hue="red" /> },
  { key: "pl_fill_leaks_section", start: 984.43, dur: 1.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_leaks_section.png" hue="amber" darken={0} /> },
  { key: "cmp_splitlist_23_2", start: 985.75, dur: 7.2, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Los 40 arreglos, divididos así" items={["Madera y metal que no mueren","Plagas por centavos","Goteras, humedad y moho","Arreglos del hogar y el auto"]} accent={A} /> },
  { key: "pl_fill_same_criterion", start: 991.58, dur: 6.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_same_criterion.png" hue="blue" darken={0} /> },
  { key: "cmp_checklist_24_0", start: 997.58, dur: 7.2, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="El plan contra la plomería" items={[{"text":"Sopapa bien usada primero","state":"done"},{"text":"Bicarbonato, vinagre y agua hirviendo","state":"done"},{"text":"Desarmar el sifón: ahí está el tapón","state":"done"},{"text":"Medidor + colorante para la pérdida","state":"done"},{"text":"Grasa nunca a la pileta, nada de soda cáustica","state":"done"}]} hue="amber" /> },
  { key: "cmp_checklist_st_998", start: 998.32, dur: 6.5, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="El plan completo" items={[{"text":"Destapar: sopapa, bicarbonato, el sifón","state":"done"},{"text":"Pérdida: medidor + gota de tinta","state":"done"},{"text":"Cambiar la goma y el cuerito ($2)","state":"done"},{"text":"Grasa nunca a la pileta","state":"done"},{"text":"Nada de soda cáustica","state":"done"}]} hue="blue" /> },
  { key: "pl_fill_disassemble_trap", start: 1004.86, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_disassemble_trap.png" hue="amber" darken={0} /> },
  { key: "pl_fill_meter_detect", start: 1008.98, dur: 4.41, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_meter_detect.png" hue="red" darken={0} /> },
  { key: "pl_fill_dye_recap", start: 1013.09, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_dye_recap.png" hue="blue" darken={0} /> },
  { key: "pl_fill_grease_never_sink", start: 1022.18, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_grease_never_sink.png" hue="blue" darken={0} /> },
  { key: "pl_fill_mechanical_chemical", start: 1028.91, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_mechanical_chemical.png" hue="amber" darken={0} /> },
  { key: "pl_fill_solve_eighty", start: 1032.25, dur: 2.15, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_solve_eighty.png" hue="amber" darken={0} /> },
  { key: "pl_fixed_sink_clean", start: 1034.1, dur: 6.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fixed_sink_clean.png" hue="red" darken={0} /> },
  { key: "pl_fill_honest_always", start: 1040.32, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_honest_always.png" hue="blue" darken={0} /> },
  { key: "pl_fill_one_front", start: 1043.46, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_one_front.png" hue="blue" darken={0} /> },
  { key: "pl_fill_rotting_wood", start: 1050.93, dur: 4.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_rotting_wood.png" hue="red" darken={0} /> },
  { key: "pl_fill_rust_pests", start: 1055.18, dur: 3.55, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_rust_pests.png" hue="blue" darken={0} /> },
  { key: "pl_fill_leak_forever", start: 1058.43, dur: 6.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_leak_forever.png" hue="blue" darken={0} /> },
  { key: "cmp_diagram_25_0", start: 1064.88, dur: 7.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/cmp_diagram_25_0.mp4" pages={[{"image":"img/dg_pl_stack.png","eyebrow":"Con los planos y las medidas exactas"}]} /> },
  { key: "pl_fill_manual_steps", start: 1070.96, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_manual_steps.png" hue="amber" darken={0} /> },
  { key: "pl_plumber_again", start: 1077.76, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_plumber_again.mp4" hue="blue" darken={0} /> },
  { key: "pl_fill_even_if_never2", start: 1085.47, dur: 4.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_even_if_never2.png" hue="blue" darken={0} /> },
  { key: "pl_fill_next_clog", start: 1089.29, dur: 3.33, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_next_clog.png" hue="amber" darken={0} /> },
  { key: "pl_grab_plunger_today", start: 1092.32, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_grab_plunger_today.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_next_car", start: 1099.87, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_next_car.png" hue="blue" darken={0} /> },
  { key: "pl_fill_headlight_trick", start: 1105.01, dur: 3.07, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_headlight_trick.png" hue="red" darken={0} /> },
  { key: "pl_yellow_headlights", start: 1107.78, dur: 2.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_yellow_headlights.mp4" hue="blue" darken={0} /> },
  { key: "pl_restored_headlight", start: 1109.98, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/pl_restored_headlight.mp4" hue="amber" darken={0} /> },
  { key: "pl_fill_if_helped", start: 1118.39, dur: 5.75, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_if_helped.png" hue="blue" darken={0} /> },
  { key: "pl_fill_one_repair_time", start: 1123.84, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/pl_fill_one_repair_time.png" hue="blue" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_oxquote_36", start: 35.88, dur: 5, kind: "oxquote", el: (d) => <OxQuoteSplit durationInFrames={d} quote="La mitad de lo que te cobra el plomero no es por el trabajo. *Es porque vos no sabés lo que él sabe*." image="real/pl_old_plumber_mate.png" attribution="Un plomero de 65 años" side="right" accent="cold" /> },
  { key: "ov_oxstack_53", start: 52.88, dur: 4.4, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/pl_sink_full_water.png","real/pl_faucet_drip_night.png","real/pl_toilet_running.png"]} captions={["La pileta tapada","La canilla que gotea","El inodoro que pierde"]} accent="cold" /> },
  { key: "burst_53", start: 52.88, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/pl_sink_full_water.png","real/pl_faucet_drip_night.png","real/pl_toilet_running.png"]} captions={["Pileta tapada","Canilla que gotea","Inodoro que pierde"]} accent="cold" /> },
  { key: "ov_oxstat_188", start: 188.44, dur: 4, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={90} label="de los problemas son los mismos cinco, una y otra vez" suffix=" %" glyph="💧" accent="danger" /> },
  { key: "ov_oxside_208", start: 207.7, dur: 5.2, kind: "oxside", el: (d) => <OxSidePanel durationInFrames={d} image="real/pl_grease_hair_elbow.png" title="Lo que tapa de verdad" lines={["Grasa y pelo en un codo del caño","Una goma de dos pesos gastada","O una unión floja que gotea"]} side="right" accent="danger" /> },
  { key: "ov_oxrule_241", start: 241.04, dur: 4.6, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="Antes de ningún químico: lo *mecánico* y lo *barato* primero." accent="amber" /> },
  { key: "ov_oxmethod_271", start: 270.98, dur: 4.6, kind: "oxmethod", el: (d) => <OxMethodCard durationInFrames={d} num="01" title="La sopapa, bien usada" chips={["Tapar rebosadero","Cubrir con agua","Tirones secos"]} cost="gratis" accent="amber" /> },
  { key: "ov_oxrule_298", start: 297.98, dur: 4.4, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="Lo que empuja el tapón no es el *aire*, es el *agua*." accent="amber" /> },
  { key: "ov_oxmethod_318", start: 318.16, dur: 4.6, kind: "oxmethod", el: (d) => <OxMethodCard durationInFrames={d} num="02" title="Bicarbonato y vinagre" chips={["½ taza bicarbonato","1 taza vinagre","Agua hirviendo"]} cost="centavos" accent="cold" /> },
  { key: "burst_363", start: 363.06, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/pl_fill_plunger_no_hair.png","real/pl_drain_snake_tool.png","real/pl_fill_hook_grab.png"]} captions={["Ni sopapa","Una sonda","O un alambre"]} accent="amber" /> },
  { key: "ov_oxmethod_382", start: 381.9, dur: 4.8, kind: "oxmethod", el: (d) => <OxMethodCard durationInFrames={d} num="03" title="El sifón: el secreto" chips={["Balde abajo","Desenroscar","Limpiar"]} cost="gratis" accent="amber" /> },
  { key: "ov_oxstat_403", start: 402.84, dur: 4, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={80} label="de los tapones se juntan en el sifón, el punto más bajo" suffix=" %" glyph="🪣" accent="amber" /> },
  { key: "ov_oxmethod_498", start: 497.88, dur: 4.6, kind: "oxmethod", el: (d) => <OxMethodCard durationInFrames={d} num="04" title="El truco del medidor" chips={["Cerrar todo","Mirar el medidor","¿Sigue girando?"]} cost="gratis" accent="cold" /> },
  { key: "ov_oxside_531", start: 531.24, dur: 5.2, kind: "oxside", el: (d) => <OxSidePanel durationInFrames={d} image="real/pl_toilet_silent.png" title="La pérdida más cara" lines={["La goma del fondo del tanque, gastada","Pierde día y noche, sin ruido","Miles de litros al mes al desagüe"]} side="right" accent="danger" /> },
  { key: "ov_oxstat_583", start: 583.46, dur: 4.2, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={50} label="una sola goma de dos pesos puede ser media factura" suffix=" %" glyph="🚽" accent="danger" /> },
  { key: "burst_619", start: 619, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/pl_faucet_washer_small.png","real/pl_aerator_tip.png","real/pl_fill_scale_holes.png"]} captions={["El cuerito","El aireador","Sarro y agujeritos"]} accent="cold" /> },
  { key: "ov_oxtag_631", start: 631.02, dur: 4, kind: "oxtag", el: (d) => <OxMaterialTag durationInFrames={d} name="El aireador" what="Tapado de sarro: por eso tira poca agua" side="left" accent="cold" /> },
  { key: "ov_oxrule_737", start: 737.12, dur: 4.4, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="La grasa *nunca* va a la pileta. Al frasco y a la basura." accent="amber" /> },
  { key: "burst_870", start: 870.39, dur: 4.2, kind: "oxstack", el: (d) => <OxPhotoStack durationInFrames={d} images={["real/pl_caustic_soda_bottle.png","real/pl_fill_dangerous_you.png","real/pl_fill_eats_metal.png"]} captions={["Quema el caño","Quema la piel","Come el metal"]} accent="danger" /> },
  { key: "ov_oxstat_891", start: 891.26, dur: 4.2, kind: "oxstat", el: (d) => <OxStatPop durationInFrames={d} value={0} label="la soda cáustica: arreglás hoy y arruinás el caño mañana" glyph="☠️" accent="danger" /> },
  { key: "ov_oxrule_908", start: 908.07, dur: 4.6, kind: "oxrule", el: (d) => <OxRuleStrip durationInFrames={d} text="La soda cáustica, *nunca*. Lo mecánico antes que lo químico." accent="danger" /> },
  { key: "ov_oxquote_1081", start: 1080.68, dur: 5.2, kind: "oxquote", el: (d) => <OxQuoteSplit durationInFrames={d} quote="Cuesta menos que una sola visita del plomero. El link está *abajo*." image="real/pl_manual_phone_steps.png" attribution="Igual, hacé lo de hoy" side="right" accent="green" /> },
];
