// cues_estafas.gen.tsx — GENERADO por beatsheet.mjs desde estafas.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/estafas.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { SplitList } from "./scenes/SplitList";
import { DiagramBoard } from "./scenes/DiagramBoard";
import { JourneyCanvas } from "./scenes/JourneyCanvas";
import { BarCompare } from "./scenes/BarCompare";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { RuleNumberScene } from "./scenes/RuleNumberScene";
import { AnnotatedImage } from "./scenes/AnnotatedImage";
import { CalloutMark } from "./scenes/CalloutMark";
import { InfiniteZoom } from "./scenes/InfiniteZoom";
import { MistakeCard } from "./scenes/MistakeCard";
import { GoldVault } from "./scenes/GoldVault";
import { ProtectionTool } from "./scenes/ProtectionTool";
import { SignaturePhrase } from "./scenes/SignaturePhrase";
import { ActionStepCard } from "./scenes/ActionStepCard";
import { NextVideoEndcard } from "./scenes/NextVideoEndcard";
import { KeyPhrase } from "./scenes/KeyPhrase";
import { StatPills } from "./scenes/StatPills";
import { FloatingProp } from "./scenes/FloatingProp";

const D = COLORS.danger;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "hook_1", start: 12.09, dur: 6.09, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Una *llamada* te puede vaciar la cuenta" /> },
  { key: "hook_2", start: 18.18, dur: 6.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="blue" /> },
  { key: "hook_3", start: 24.46, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No es un loco. Es un *negocio*." src="broll/ec_call_center.mp4" /> },
  { key: "hook_3_f0", start: 32.96, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="red" /> },
  { key: "hook_4", start: 37, dur: 4.77, kind: "statpills", el: (d) => <StatPills durationInFrames={d} pills={["MIEDO","APURO"]} slider={false} /> },
  { key: "hook_5", start: 41.77, dur: 6.75, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/dg_es_callid.png" annotations={[{"kind":"circle","x":0.5,"y":0.3,"w":0.22,"label":"DESCONOCIDO"}]} eyebrow="Suena el teléfono" caption="Así empieza, siempre" hue="blue" /> },
  { key: "hook_6", start: 48.52, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No con un arma: con una *llamada amable*" src="broll/ec_anciano_tel.mp4" /> },
  { key: "hook_6_f0", start: 57.02, dur: 2.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="red" /> },
  { key: "hook_7", start: 59.36, dur: 10.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="amber" /> },
  { key: "hook_8", start: 69.96, dur: 10.02, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No le pasa a los *tontos*. Le pasa a *cualquiera*." src="img/es_medico_jub.png" /> },
  { key: "hook_9", start: 79.98, dur: 9.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_medico_jub.png" hue="red" /> },
  { key: "hook_10", start: 89.88, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No ataca tu *cabeza*. Ataca tu *corazón*." src="img/es_corazon.png" /> },
  { key: "hook_10_f0", start: 98.38, dur: 2.31, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="amber" /> },
  { key: "hook_11", start: 100.69, dur: 10.69, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_corazon.png" hue="blue" /> },
  { key: "hook_12", start: 111.38, dur: 8.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="TODOS los países" image="img/es_mapa_hispano.png" caption="México, Argentina, Colombia, España…" accent="amber" hue="red" /> },
  { key: "hook_12_f0", start: 119.88, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="red" /> },
  { key: "hook_12_f1", start: 127.38, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="red" /> },
  { key: "hook_12_f2", start: 134.88, dur: 1.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="red" /> },
  { key: "hook_13", start: 136.34, dur: 8.5, kind: "goldvault", el: (d) => <GoldVault durationInFrames={d} state="locked" label="UNA REGLA" caption="Una sola frase las detiene a todas — al final" /> },
  { key: "hook_13_f0", start: 144.84, dur: 5.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="amber" /> },
  { key: "hook_14", start: 150.58, dur: 6.98, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Quédate hasta el *final*" src="broll/ec_dinero.mp4" /> },
  { key: "benintro_0", start: 157.56, dur: 6.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_camara.png" hue="amber" kicker="Soy Ben, también jubilado" /> },
  { key: "benintro_1", start: 163.66, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Lo vi de cerca, con gente que *quiero*" src="img/es_ben_camara.png" /> },
  { key: "benintro_1_f0", start: 172.16, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="blue" /> },
  { key: "aldo_0", start: 176.62, dur: 2.89, kind: "rule", el: (d) => <RuleNumberScene durationInFrames={d} number="01" title="La tarde que llamó “el nieto”" hue="blue" /> },
  { key: "aldo_1", start: 179.51, dur: 5.57, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_aldo.png" hue="red" kicker="Don Aldo, 74" /> },
  { key: "aldo_2", start: 185.08, dur: 6.82, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="“A mí no me la *cuentan*”" src="img/es_aldo.png" times={[0,5,9,16,20,27]} /> },
  { key: "aldo_3", start: 191.9, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="blue" /> },
  { key: "aldo_3_f0", start: 200.9, dur: 2.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="blue" /> },
  { key: "aldo_4", start: 203.32, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="“Abuelo… tuve un *accidente*”" src="broll/ec_anciano_tel.mp4" /> },
  { key: "aldo_4_f0", start: 211.82, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="red" /> },
  { key: "aldo_5", start: 217.48, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Era la voz de su *nieto*. Idéntica." src="img/es_aldo.png" /> },
  { key: "aldo_5_f0", start: 225.98, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="amber" /> },
  { key: "aldo_5_f1", start: 233.48, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="amber" /> },
  { key: "aldo_6", start: 237.42, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_abogado.png" hue="blue" /> },
  { key: "aldo_6_f0", start: 246.42, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="blue" /> },
  { key: "aldo_6_f1", start: 253.92, dur: 1.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="blue" /> },
  { key: "aldo_7", start: 255.52, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="“Hay que pagar. *Rápido*. En efectivo.”" src="img/es_abogado.png" /> },
  { key: "aldo_7_f0", start: 264.02, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="red" /> },
  { key: "aldo_7_f1", start: 271.52, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="red" /> },
  { key: "aldo_8", start: 275.98, dur: 7.03, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="amber" /> },
  { key: "aldo_9", start: 283.01, dur: 14, kind: "journey", el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="Cómo se desarmó, paso a paso" accent="accent" dark waypoints={[{"x":0,"y":0,"image":"img/es_j_telefono.png","label":"Suena el teléfono","num":"1","dwell":2.4,"travel":1.3},{"x":1.3,"y":-0.3,"image":"img/es_j_llanto.png","label":"“Soy yo, tuve un accidente”","num":"2","dwell":2.5,"travel":1.4},{"x":2.6,"y":0.3,"image":"img/es_j_pago.png","label":"Pagó todo en una hora","num":"3","dwell":2.5,"travel":1.4},{"x":3.9,"y":-0.2,"image":"img/es_j_sano.png","label":"El nieto estaba sano","num":"4","dwell":2.7,"travel":1.3}]} /> },
  { key: "aldo_9_f0", start: 297.01, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="red" /> },
  { key: "aldo_9_f1", start: 304.51, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="red" /> },
  { key: "aldo_9_f2", start: 312.01, dur: 3.47, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="red" /> },
  { key: "aldo_10", start: 315.48, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Habló con un *estafador*. La voz era *idéntica*." src="img/es_aldo.png" /> },
  { key: "aldo_10_f0", start: 323.98, dur: 2.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="red" /> },
  { key: "voz_0", start: 326.74, dur: 2.18, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/voz_0.mp4" pages={[{"image":"img/dg_es_voz.png","eyebrow":"La voz copiada"}]} /> },
  { key: "voz_1", start: 328.92, dur: 8.54, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Unos *segundos* de audio bastan" src="broll/ec_compu.mp4" /> },
  { key: "voz_2", start: 337.46, dur: 5.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="blue" /> },
  { key: "voz_3", start: 342.88, dur: 9.52, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Ya no alcanza con *reconocer la voz*" src="broll/ec_compu.mp4" times={[9,14,20,34,41,59,64]} /> },
  { key: "voz_4", start: 352.4, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_aldo_triste.png" hue="amber" /> },
  { key: "voz_4_f0", start: 361.4, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="amber" /> },
  { key: "voz_5", start: 366.44, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="“No fuiste un *tonto*. Te tendieron una *trampa*.”" src="img/es_aldo_triste.png" /> },
  { key: "voz_5_f0", start: 374.94, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="blue" /> },
  { key: "voz_5_f1", start: 382.44, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="blue" /> },
  { key: "voz_5_f2", start: 389.94, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="blue" /> },
  { key: "voz_5_f3", start: 397.44, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="blue" /> },
  { key: "rosa_0", start: 400.8, dur: 8.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_rosa.png" hue="amber" kicker="Doña Rosa, viuda" /> },
  { key: "rosa_1", start: 409.24, dur: 2.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="blue" /> },
  { key: "rosa_2", start: 412.1, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Las tardes *largas*. La casa en *silencio*." src="broll/ec_anciana_sola.mp4" times={[0,0,0,9,14,21,31]} /> },
  { key: "rosa_2_f0", start: 420.6, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="red" /> },
  { key: "rosa_2_f1", start: 428.1, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="red" /> },
  { key: "rosa_3", start: 431.26, dur: 3.78, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Por fin alguien la *escuchaba*" src="img/es_rosa.png" /> },
  { key: "rosa_4", start: 435.04, dur: 15.52, kind: "journey", el: (d) => <JourneyCanvas durationInFrames={d} eyebrow="El “amor” de Doña Rosa, paso a paso" accent="accent" dark waypoints={[{"x":0,"y":0,"image":"img/es_jr_chat.png","label":"“Buenos días” todas las mañanas","num":"1","dwell":2.4,"travel":1.3},{"x":1.3,"y":-0.3,"image":"img/es_jr_meses.png","label":"Meses de cariño","num":"2","dwell":2.4,"travel":1.4},{"x":2.6,"y":0.3,"image":"img/es_jr_pedido.png","label":"“Necesito que me mandes dinero”","num":"3","dwell":2.5,"travel":1.4},{"x":3.9,"y":-0.2,"image":"img/es_jr_borrado.png","label":"Desapareció. Nunca existió.","num":"4","dwell":2.6,"travel":1.3}]} /> },
  { key: "rosa_5", start: 450.56, dur: 8.5, kind: "floatprop", el: (d) => <FloatingProp durationInFrames={d} src="img/es_corazon_roto.png" bg="broll/ec_telefono.mp4" caption="El amor que *no existía*" accent="accent" scale={0.6} /> },
  { key: "rosa_5_f0", start: 459.06, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="red" /> },
  { key: "rosa_5_f1", start: 466.56, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="red" /> },
  { key: "rosa_5_f2", start: 474.06, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="red" /> },
  { key: "rosa_5_f3", start: 481.56, dur: 4.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="red" /> },
  { key: "rosa_6", start: 486.34, dur: 8.76, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Un *libreto*. Para una mujer *sola*." src="img/es_rosa.png" /> },
  { key: "bridge_0", start: 495.1, dur: 5.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_puertas.png" hue="blue" kicker="Por ahí entra el estafador" /> },
  { key: "bridge_1", start: 500.7, dur: 8.5, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Las dos puertas" items={["El miedo (una emergencia)","La soledad (un cariño falso)"]} accent={D} /> },
  { key: "bridge_1_f0", start: 509.2, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="red" /> },
  { key: "bridge_1_f1", start: 516.7, dur: 4.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="red" /> },
  { key: "bridge_2", start: 521.34, dur: 4.74, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Conocer la trampa = *media defensa*" src="img/es_ben_puertas.png" /> },
  { key: "estafa1_0", start: 526.08, dur: 8.5, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="1" title="El falso familiar en problemas" desc="Emergencia + apuro + “no le digas a nadie”. Ahora con la voz copiada." eyebrow="ESTAFA" /> },
  { key: "estafa1_0_f0", start: 534.58, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="red" /> },
  { key: "estafa1_0_f1", start: 542.08, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="red" /> },
  { key: "estafa1_1", start: 546.84, dur: 8.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Emoción + Apuro + Secreto" image="img/es_call_panic.png" caption="“No le digas a nadie” = trampa" accent="accent" hue="amber" /> },
  { key: "estafa1_1_f0", start: 555.34, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="amber" /> },
  { key: "estafa1_1_f1", start: 562.84, dur: 4.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="amber" /> },
  { key: "estafa1_2", start: 567.3, dur: 9.1, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Dinero *urgente* y en *secreto*" src="broll/ec_anciano_tel.mp4" times={[22,53,78,82,90]} /> },
  { key: "estafa2_0", start: 576.4, dur: 8.5, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="2" title="El falso banco" desc="“Confirme su clave / pase su dinero a una cuenta segura.” El banco NUNCA pide eso." eyebrow="ESTAFA" /> },
  { key: "estafa2_0_f0", start: 584.9, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="amber" /> },
  { key: "estafa2_1", start: 591.9, dur: 8.5, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/dg_es_banco.png" annotations={[{"kind":"circle","x":0.5,"y":0.38,"w":0.16,"label":"Pide tu CLAVE"},{"kind":"arrow","x":0.5,"y":0.66,"fromX":0.18,"fromY":0.85,"label":"“Cuenta segura” = la de ELLOS"}]} eyebrow="El mensaje del “banco”" caption="Todo esto lo delata" hue="blue" /> },
  { key: "estafa2_1_f0", start: 600.4, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="blue" /> },
  { key: "estafa2_2", start: 605.56, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Ningún banco te pide la *clave* por teléfono" src="broll/ec_tarjeta.mp4" /> },
  { key: "estafa2_2_f0", start: 614.06, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="red" /> },
  { key: "estafa2_3", start: 618.54, dur: 3.32, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Quien la pide es el *ladrón*" src="broll/ec_tarjeta.mp4" /> },
  { key: "estafa2_4", start: 621.86, dur: 1.68, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="El banco de verdad…" items={["NUNCA pide tu clave completa","NUNCA te pasa a “otra cuenta”","Vos llamás al dorso de la tarjeta"]} accent={D} cross /> },
  { key: "estafa3_0", start: 623.54, dur: 8.5, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="3" title="El premio o la herencia" desc="“Ganó un sorteo / apareció una herencia. Pague un pequeño impuesto para recibirlo.”" eyebrow="ESTAFA" /> },
  { key: "estafa3_0_f0", start: 632.04, dur: 7.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="blue" /> },
  { key: "estafa3_1", start: 639.22, dur: 8.5, kind: "floatprop", el: (d) => <FloatingProp durationInFrames={d} src="img/es_trofeo.png" bg="broll/ec_compu.mp4" caption="Siempre hay una *condición*" accent="amber" scale={0.6} /> },
  { key: "estafa3_1_f0", start: 647.72, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="red" /> },
  { key: "estafa3_1_f1", start: 655.22, dur: 0.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="red" /> },
  { key: "estafa3_2", start: 656.12, dur: 8.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="¿Pagar para COBRAR?" image="img/es_premio.png" caption="Jamás se paga para recibir dinero" accent="accent" hue="amber" /> },
  { key: "estafa3_2_f0", start: 664.62, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="amber" /> },
  { key: "estafa3_2_f1", start: 672.12, dur: 1.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="amber" /> },
  { key: "estafa4_0", start: 673.94, dur: 4.6, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="4" title="El falso soporte técnico" desc="“Su equipo tiene un virus, deme acceso / instale esto.” → entran a tu banco." eyebrow="ESTAFA" /> },
  { key: "estafa4_1", start: 678.54, dur: 8.5, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/dg_es_virus.png" annotations={[{"kind":"circle","x":0.5,"y":0.42,"w":0.22,"label":"FALSO"},{"kind":"underline","x":0.5,"y":0.7,"w":0.28,"label":"“llame ya”"}]} eyebrow="El cartel falso" caption="Todo es para asustarte" hue="amber" /> },
  { key: "estafa4_1_f0", start: 687.04, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="amber" /> },
  { key: "estafa4_1_f1", start: 694.54, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="amber" /> },
  { key: "estafa4_2", start: 697.74, dur: 8.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="DAME ACCESO" image="img/es_acceso.png" caption="Si entran, te vacían el banco" accent="accent" hue="blue" /> },
  { key: "estafa4_2_f0", start: 706.24, dur: 6.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="blue" /> },
  { key: "estafa4_3", start: 712.38, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Nadie te llama por un *virus*" src="broll/ec_compu.mp4" /> },
  { key: "estafa4_3_f0", start: 720.88, dur: 3.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="red" /> },
  { key: "estafa5_0", start: 723.92, dur: 9.86, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="5" title="El amor por internet" desc="Compañía durante meses → una emergencia → pide dinero. Nunca se vieron en persona." eyebrow="ESTAFA" /> },
  { key: "estafa5_1", start: 733.78, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="blue" /> },
  { key: "estafa5_1_f0", start: 742.78, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="blue" /> },
  { key: "estafa5_1_f1", start: 750.28, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="blue" /> },
  { key: "estafa5_2", start: 754.3, dur: 5.71, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="NUNCA en persona" image="img/es_romance.png" caption="Gana tu confianza… y pide dinero" accent="accent" hue="red" /> },
  { key: "estafa5_3", start: 760.01, dur: 4.99, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="La señal del amor falso" items={["Lo conociste por una pantalla","Nunca se vieron en persona","En algún momento pide dinero"]} accent={D} cross /> },
  { key: "estafa6_0", start: 765, dur: 8.5, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="6" title="El falso funcionario" desc="“Tiene una deuda/multa, pague YA o lo detienen.” Pura amenaza para asustar." eyebrow="ESTAFA" /> },
  { key: "estafa6_0_f0", start: 773.5, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="blue" /> },
  { key: "estafa6_0_f1", start: 781, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="blue" /> },
  { key: "estafa6_1", start: 784.94, dur: 8.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="“PAGUE YA O…”" image="img/es_amenaza.png" caption="Ninguna autoridad amenaza por teléfono" accent="accent" hue="red" /> },
  { key: "estafa6_1_f0", start: 793.44, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="red" /> },
  { key: "estafa6_1_f1", start: 800.94, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="red" /> },
  { key: "estafa6_2", start: 804.64, dur: 9.96, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="La autoridad real…" items={["Avisa por escrito, con tiempo","No te amenaza con la cárcel","Nunca exige pago inmediato"]} accent={D} cross /> },
  { key: "estafa7_0", start: 814.6, dur: 8.5, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="7" title="“Hola mamá, cambié de número”" desc="Mensaje de un número nuevo desconocido → enseguida pide una transferencia." eyebrow="ESTAFA" /> },
  { key: "estafa7_0_f0", start: 823.1, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="red" /> },
  { key: "estafa7_1", start: 826.3, dur: 8.5, kind: "annotated", el: (d) => <AnnotatedImage durationInFrames={d} image="img/dg_es_whatsapp.png" annotations={[{"kind":"circle","x":0.5,"y":0.18,"w":0.2,"label":"Número DESCONOCIDO"},{"kind":"underline","x":0.5,"y":0.74,"w":0.3,"label":"“transferencia urgente”"}]} eyebrow="El mensaje del “hijo”" caption="Número nuevo + apuro = alerta" hue="amber" /> },
  { key: "estafa7_1_f0", start: 834.8, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="amber" /> },
  { key: "estafa7_1_f1", start: 842.3, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="amber" /> },
  { key: "estafa7_1_f2", start: 849.8, dur: 6.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="amber" /> },
  { key: "estafa7_2", start: 856.56, dur: 2.1, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Número nuevo → enseguida pide *plata*" src="broll/ec_whatsapp.mp4" /> },
  { key: "estafa8_0", start: 858.66, dur: 2.84, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="8" title="La inversión milagrosa" desc="“Duplicá tu jubilación.” Mucho, rápido y sin riesgo = mentira." eyebrow="ESTAFA" /> },
  { key: "estafa8_1", start: 861.5, dur: 8.5, kind: "floatprop", el: (d) => <FloatingProp durationInFrames={d} src="img/es_grafico_falso.png" bg="broll/ec_dinero.mp4" caption="“Duplicá tu *jubilación*”" accent="amber" scale={0.7} /> },
  { key: "estafa8_1_f0", start: 870, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="blue" /> },
  { key: "estafa8_1_f1", start: 877.5, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="blue" /> },
  { key: "estafa8_1_f2", start: 885, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="blue" /> },
  { key: "estafa8_2", start: 892.62, dur: 0.6, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Inversión honesta","value":6,"sub":"al año, despacio","display":"~6%","tone":"good"},{"label":"La “milagrosa”","value":300,"sub":"que te promete","display":"300%","winner":true}]} eyebrow="La promesa vs la realidad" title="Si promete eso, es mentira" unit="%" hue="red" /> },
  { key: "estafa8_3", start: 893.22, dur: 0.6, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Y un día… DESAPARECE" image="img/es_plataforma.png" caption="La plataforma y tu dinero, juntos" accent="accent" hue="amber" /> },
  { key: "estafa8_4", start: 893.82, dur: 8.2, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="El dinero honesto crece *despacio*" src="broll/ec_dinero.mp4" times={[9,13,22,50,61]} /> },
  { key: "patron_0", start: 902.02, dur: 10.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_patron.png" hue="blue" kicker="El patrón de TODAS" /> },
  { key: "patron_1", start: 912.18, dur: 3.2, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/patron_1.mp4" pages={[{"image":"img/dg_es_patron.png","eyebrow":"Las 3 señales"}]} /> },
  { key: "patron_2", start: 915.38, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="1. Te despiertan una *emoción* fuerte" src="broll/ec_anciano_tel.mp4" /> },
  { key: "patron_2_f0", start: 923.88, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="amber" /> },
  { key: "patron_3", start: 927.22, dur: 7.14, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="2. Te *apuran*: tiene que ser YA" src="broll/ec_telefono.mp4" /> },
  { key: "patron_4", start: 934.36, dur: 1.4, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="3. Te *aíslan*: no le digas a nadie" src="broll/ec_anciana_sola.mp4" /> },
  { key: "patron_5", start: 935.76, dur: 4.4, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Emoción","desc":"miedo o ilusión"},{"title":"Apuro","desc":"tiene que ser YA"},{"title":"Silencio","desc":"no le digas a nadie"}]} eyebrow="Cómo entra, siempre" title="Los 3 ingredientes" hue="amber" /> },
  { key: "patron_6", start: 940.16, dur: 8.5, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Las 3 juntas = estafa" items={["Emoción (miedo o ilusión)","Apuro (tiene que ser YA)","Silencio (no le digas a nadie)"]} accent={D} cross /> },
  { key: "patron_6_f0", start: 948.66, dur: 2.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="blue" /> },
  { key: "patron_7", start: 950.9, dur: 2.62, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No importa quién diga que es. Es *estafa*." src="img/es_ben_patron.png" /> },
  { key: "cta_share_0", start: 953.52, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_share.png" hue="red" kicker="Mandáselo a quien lo necesite" /> },
  { key: "cta_share_0_f0", start: 962.52, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="red" /> },
  { key: "cta_share_0_f1", start: 970.02, dur: 2.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="red" /> },
  { key: "cta_share_1", start: 972.36, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Reenvíalo. Puede evitar el *peor día*" src="img/es_ben_share.png" /> },
  { key: "cta_share_1_f0", start: 980.86, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="amber" /> },
  { key: "cta_share_1_f1", start: 988.36, dur: 0.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="amber" /> },
  { key: "cta_sub_0", start: 989.12, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_sub.png" hue="amber" kicker="De jubilado a jubilado" /> },
  { key: "cta_sub_0_f0", start: 998.12, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="amber" /> },
  { key: "cta_sub_0_f1", start: 1005.62, dur: 3.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="amber" /> },
  { key: "cta_sub_1", start: 1009.1, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Lo más *importante* viene ahora" src="img/es_ben_sub.png" /> },
  { key: "cta_sub_1_f0", start: 1017.6, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="blue" /> },
  { key: "cta_sub_1_f1", start: 1025.1, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="blue" /> },
  { key: "cta_sub_1_f2", start: 1032.6, dur: 0.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="blue" /> },
  { key: "regla_0", start: 1033.5, dur: 1.24, kind: "goldvault", el: (d) => <GoldVault durationInFrames={d} state="open" label="LA REGLA" caption="Cuando algo te apura, vos FRENÁS" /> },
  { key: "regla_1", start: 1034.74, dur: 8.14, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Cuando algo te *apura*, vos *frenás*" src="img/es_ben_camara.png" /> },
  { key: "regla_2", start: 1042.88, dur: 7.2, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Él necesita tu *miedo*. Vos, tu *calma*." src="img/es_ben_camara.png" /> },
  { key: "regla_3", start: 1050.08, dur: 5.86, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Frená y colgá","desc":"ante cualquier pedido"},{"title":"Verificá por otro camino","desc":"vos llamás"},{"title":"Palabra clave familiar","desc":"le gana a la voz copiada"}]} eyebrow="Tu defensa, en pasos" title="Fácil de recordar" hue="blue" /> },
  { key: "regla_4", start: 1055.94, dur: 4.56, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Solo necesitás un minuto" items={["Él trabaja con tu apuro","Vos ganás con tu calma","Un minuto frena cualquier estafa"]} accent={D} /> },
  { key: "def1_0", start: 1060.5, dur: 1.62, kind: "tool", el: (d) => <ProtectionTool durationInFrames={d} nameEs="Cortá. Colgá." how="Ante cualquier pedido de dinero o datos, cortá. No es mala educación, es defensa propia." number="1" eyebrow="Defensa" /> },
  { key: "def1_1", start: 1062.12, dur: 10.16, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Colgar NO es *mala educación*" src="broll/ec_telefono.mp4" /> },
  { key: "def1_2", start: 1072.28, dur: 7.3, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="El que se *enoja* porque colgás… es el *ladrón*" src="broll/ec_anciano_tel.mp4" /> },
  { key: "def2_0", start: 1079.58, dur: 3.8, kind: "tool", el: (d) => <ProtectionTool durationInFrames={d} nameEs="Verificá por otro camino" how="Colgá y llamá VOS al número que ya tenés: tu nieto, tu banco. Nunca al que te dieron." number="2" eyebrow="Defensa" /> },
  { key: "def2_1", start: 1083.38, dur: 10.68, kind: "diagram", el: (d) => <DiagramBoard durationInFrames={d} clip="avatar_clips/def2_1.mp4" pages={[{"image":"img/dg_es_verificar.png","eyebrow":"Verificá vos"}]} /> },
  { key: "def2_2", start: 1094.06, dur: 3.36, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Llamá VOS al número del *dorso de la tarjeta*" src="broll/ec_tarjeta.mp4" /> },
  { key: "def2_3", start: 1097.42, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Nunca al número que *ellos* te dieron" src="broll/ec_telefono.mp4" /> },
  { key: "def2_3_f0", start: 1105.92, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="amber" /> },
  { key: "def2_3_f1", start: 1113.42, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="amber" /> },
  { key: "def3_0", start: 1116.34, dur: 3.72, kind: "tool", el: (d) => <ProtectionTool durationInFrames={d} nameEs="Palabra clave familiar" how="Acuerden una palabra secreta. Si un familiar pide dinero, preguntá la palabra. El estafador no la sabe." number="3" nameEn="Le gana a la voz copiada" eyebrow="Defensa" /> },
  { key: "def3_1", start: 1120.06, dur: 3.24, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Junten a hijos y nietos *hoy mismo*" src="broll/ec_pareja.mp4" /> },
  { key: "def3_2", start: 1123.3, dur: 8.5, kind: "floatprop", el: (d) => <FloatingProp durationInFrames={d} src="img/es_llave.png" bg="broll/ec_anciano_tel.mp4" caption="Girasol, el mate, el primer perro…" accent="good" scale={0.6} /> },
  { key: "def3_2_f0", start: 1131.8, dur: 6.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="amber" /> },
  { key: "def3_3", start: 1138.4, dur: 7.32, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Le preguntás, tranquilo, *la palabra*" src="img/es_llave.png" /> },
  { key: "def3_4", start: 1145.72, dur: 3.8, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Aunque tenga la voz *idéntica*, no la sabe" src="broll/ec_telefono.mp4" /> },
  { key: "def3_5", start: 1149.52, dur: 9.28, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Una palabra y se cae *todo*" src="img/es_llave.png" /> },
  { key: "def4_0", start: 1158.8, dur: 3.78, kind: "tool", el: (d) => <ProtectionTool durationInFrames={d} nameEs="Nunca des clave ni acceso" how="Ni al banco, ni a la policía, ni a soporte. La gente honesta no te lo pide jamás." number="4" eyebrow="Defensa" /> },
  { key: "def4_1", start: 1162.58, dur: 10.24, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Ni *clave*, ni *contraseña*, ni *acceso*" src="broll/ec_compu.mp4" /> },
  { key: "def4_2", start: 1172.82, dur: 4.88, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="La gente *honesta* no te lo pide jamás" src="broll/ec_pareja.mp4" /> },
  { key: "def5_0", start: 1177.7, dur: 1.52, kind: "tool", el: (d) => <ProtectionTool durationInFrames={d} nameEs="Nunca pagues para recibir" how="Premio, herencia, préstamo o trabajo: si hay que poner plata para cobrar, es mentira." number="5" eyebrow="Defensa" /> },
  { key: "def5_1", start: 1179.22, dur: 4.62, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Ni premios, ni herencias, ni *préstamos*" src="broll/ec_dinero.mp4" times={[9,14,37,42,74,80]} /> },
  { key: "def5_2", start: 1183.84, dur: 9.22, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="¿Poner plata para *cobrar* plata? *Mentira*" src="broll/ec_dinero.mp4" /> },
  { key: "def6_0", start: 1193.06, dur: 2.04, kind: "tool", el: (d) => <ProtectionTool durationInFrames={d} nameEs="Si te piden secreto, es estafa" how="“No le digas a nadie” es la frase del ladrón. Hacé lo contrario: hablá, consultá, llamá." number="6" eyebrow="Defensa" /> },
  { key: "def6_1", start: 1195.1, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="“No le digas a nadie” = la frase del *ladrón*" src="broll/ec_anciano_tel.mp4" /> },
  { key: "def6_1_f0", start: 1203.6, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="red" /> },
  { key: "def6_2", start: 1206.38, dur: 9.98, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Te exigen silencio → hacé lo *contrario*" src="broll/ec_pareja.mp4" /> },
  { key: "def6_3", start: 1216.36, dur: 2.3, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="La estafa se muere a la *luz del día*" src="broll/ec_pareja.mp4" times={[9,14,23,30,36,40,44,48,55]} /> },
  { key: "def6_4", start: 1218.66, dur: 5.7, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Tu defensa, en 6" items={[{"text":"1. Cortá y colgá","state":"done"},{"text":"2. Verificá por otro camino","state":"done"},{"text":"3. Palabra clave familiar","state":"done"},{"text":"4. Nunca clave ni acceso","state":"done"},{"text":"5. Nunca pagues para recibir","state":"done"},{"text":"6. Si piden secreto, es estafa","state":"done"}]} hue="red" /> },
  { key: "yacaiste_0", start: 1224.36, dur: 10.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_apoyo.png" hue="red" kicker="¿Ya te pasó? No es tu culpa." /> },
  { key: "yacaiste_1", start: 1235.22, dur: 3.98, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No es tu *culpa*. No te *avergüences*." src="img/es_ben_apoyo.png" /> },
  { key: "yacaiste_2", start: 1239.2, dur: 6.82, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Le pasó a *Don Aldo*. A *Doña Rosa*. A *millones*." src="img/es_aldo_triste.png" /> },
  { key: "yacaiste_3", start: 1246.02, dur: 10.7, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="La *vergüenza* es lo que usan para que calles" src="broll/ec_anciana_sola.mp4" /> },
  { key: "yacaiste_4", start: 1256.72, dur: 8.5, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Llamá a tu banco","desc":"frenar / reportar"},{"title":"Cambiá tus claves","desc":"todas"},{"title":"Contalo","desc":"familia + denuncia"}]} eyebrow="Si acaba de pasar, rápido" title="Actuá ya" hue="amber" /> },
  { key: "yacaiste_4_f0", start: 1265.22, dur: 5.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="amber" /> },
  { key: "yacaiste_5", start: 1270.78, dur: 2.4, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Si caíste, hoy" items={[{"text":"No te avergüences: te tendieron una trampa","state":"done"},{"text":"Banco + claves, ya","state":"done"},{"text":"Contalo: tu voz salva a otro","state":"done"}]} hue="blue" /> },
  { key: "yacaiste_6", start: 1273.18, dur: 4.92, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="El silencio protege al *ladrón*. Tu voz, a *los demás*." src="broll/ec_pareja.mp4" /> },
  { key: "paso_0", start: 1278.1, dur: 7.38, kind: "action", el: (d) => <ActionStepCard durationInFrames={d} step="Acordá la palabra clave familiar" question="Si les llega un mensaje mío de un número nuevo pidiendo plata, llámenme antes de hacer nada." eyebrow="Hoy mismo" /> },
  { key: "paso_1", start: 1285.48, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="blue" /> },
  { key: "paso_1_f0", start: 1294.48, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="blue" /> },
  { key: "paso_2", start: 1298.18, dur: 5.94, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="“Llámenme *antes* de hacer nada”" src="broll/ec_pareja.mp4" times={[9,24,33,41,48]} /> },
  { key: "paso_3", start: 1304.12, dur: 2.18, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Esa charla de 5 min vale más que una *cerradura*" src="broll/ec_pareja.mp4" /> },
  { key: "paso_4", start: 1306.3, dur: 4.22, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No lo dejes para *mañana*. La estafa *no avisa*." src="broll/ec_telefono.mp4" /> },
  { key: "paso_5", start: 1310.52, dur: 6.98, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Llega un *martes cualquiera*, a la siesta" src="broll/ec_anciano_tel.mp4" /> },
  { key: "paso_6", start: 1317.5, dur: 8.5, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="El preparado *cuelga y se ríe*. El otro, *pierde todo*." src="broll/ec_dinero.mp4" /> },
  { key: "paso_6_f0", start: 1326, dur: 3.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciana_sola.mp4" hue="amber" /> },
  { key: "paso_7", start: 1329.88, dur: 5.64, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="La diferencia es haberlo *pensado antes*" src="img/es_ben_camara.png" times={[9,14,31,39,53,64]} /> },
  { key: "recap_0", start: 1335.52, dur: 8.5, kind: "infzoom", el: (d) => <InfiniteZoom durationInFrames={d} images={[{"src":"img/es_call_panic.png","label":"Falso nieto"},{"src":"img/dg_es_banco.png","label":"Falso banco"},{"src":"img/es_premio.png","label":"Premio / herencia"},{"src":"img/es_acceso.png","label":"Soporte técnico"},{"src":"img/es_romance.png","label":"Amor online"},{"src":"img/es_amenaza.png","label":"Falso funcionario"},{"src":"img/dg_es_whatsapp.png","label":"“Cambié de número”"},{"src":"img/es_plataforma.png","label":"Inversión milagrosa"}]} accent="accent" /> },
  { key: "recap_0_f0", start: 1344.02, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_call_center.mp4" hue="blue" /> },
  { key: "recap_1", start: 1346.84, dur: 8.5, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Las 8, una por una" items={["Falso nieto","Falso banco","Premio / herencia","Soporte técnico","Amor online","Falso funcionario","“Cambié de número”","Inversión milagrosa"]} accent={D} /> },
  { key: "recap_1_f0", start: 1355.34, dur: 4.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_anciano_tel.mp4" hue="red" /> },
  { key: "recap_2", start: 1360.12, dur: 2.98, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Para no olvidar" items={[{"text":"Toda estafa: emoción + apuro + secreto","state":"done"},{"text":"Frená, colgá, verificá por tu cuenta","state":"done"},{"text":"Palabra clave: le gana a la voz copiada","state":"done"},{"text":"Nunca clave, acceso, ni pagar para recibir","state":"done"}]} hue="amber" /> },
  { key: "recap_3", start: 1363.1, dur: 1.83, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Frená, colgá y verificá por tu *propia cuenta*" src="broll/ec_telefono.mp4" /> },
  { key: "recap_4", start: 1364.93, dur: 4.63, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Calma que te salva","value":1,"sub":"un minuto","display":"1 min","tone":"good"},{"label":"Perder todo","value":10,"sub":"si te apuran","display":"10 min","winner":true}]} eyebrow="La diferencia no es ser más vivo" title="Es haberlo pensado antes" unit="min" hue="red" /> },
  { key: "recap_5", start: 1369.56, dur: 7.48, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="La palabra clave le gana hasta a la *voz copiada*" src="broll/ec_telefono.mp4" /> },
  { key: "firma_0", start: 1377.04, dur: 8.46, kind: "signature", el: (d) => <SignaturePhrase durationInFrames={d} lines={[{"text":"El estafador trabaja con tu apuro."},{"text":"Vos defendete"},{"text":"con tu calma.","gold":true}]} eyebrow="Para llevarte" /> },
  { key: "firma_1", start: 1385.5, dur: 4.52, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Nadie honesto te exige decidir *en este segundo*" src="img/es_ben_camara.png" /> },
  { key: "firma_2", start: 1390.02, dur: 3.26, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="El *apuro* es la huella de la *mentira*" src="img/es_ben_camara.png" /> },
  { key: "epi_0", start: 1393.28, dur: 9.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_aldo_avisa.png" hue="amber" kicker="Hoy Don Aldo avisa a todos" /> },
  { key: "epi_1", start: 1402.74, dur: 7.04, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="Hoy él es el *primero* que avisa a todos" src="img/es_aldo_avisa.png" /> },
  { key: "epi_2", start: 1409.78, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_rosa_bien.png" hue="red" /> },
  { key: "epi_2_f0", start: 1418.78, dur: 7.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_compu.mp4" hue="red" /> },
  { key: "epi_3", start: 1425.94, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_final.png" hue="amber" kicker="¿Ya tienen su palabra clave?" /> },
  { key: "epi_3_f0", start: 1434.94, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_dinero.mp4" hue="amber" /> },
  { key: "tease_0", start: 1437.82, dur: 8.5, kind: "nextvideo", el: (d) => <NextVideoEndcard durationInFrames={d} title="Los gastos hormiga" kicker="Próximo video" sub="Lo que te saca dinero todos los meses, en silencio — y cómo cortarlo en una sola tarde." /> },
  { key: "tease_0_f0", start: 1446.32, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_pareja.mp4" hue="blue" /> },
  { key: "tease_0_f1", start: 1453.82, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_telefono.mp4" hue="blue" /> },
  { key: "tease_0_f2", start: 1461.32, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_tarjeta.mp4" hue="blue" /> },
  { key: "outro_0", start: 1466.14, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/es_ben_outro.png" hue="red" kicker="Soy Ben, de Ben retirado" /> },
  { key: "outro_0_f0", start: 1475.14, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/ec_whatsapp.mp4" hue="red" /> },
];

export const REFRAME: { start: number; end: number }[] = [];
