// cues_carne.gen.tsx — GENERADO por beatsheet.mjs desde carne.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/carne.json
import { ReactNode } from "react";
import { COLORS } from "./theme";
import { RawShot } from "./scenes/RawShot";
import { ChipsCluster } from "./scenes/ReframeContent";
import { SplitList } from "./scenes/SplitList";
import { StatBig } from "./scenes/StatBig";
import { ImpactReveal } from "./scenes/ImpactReveal";
import { BarCompare } from "./scenes/BarCompare";
import { CrossSection } from "./scenes/CrossSection";
import { ProcessSteps } from "./scenes/ProcessSteps";
import { Checklist } from "./scenes/Checklist";
import { CureDiagram } from "./scenes/CureDiagram";
import { CalloutMark } from "./scenes/CalloutMark";
import { MistakeCard } from "./scenes/MistakeCard";
import { NextVideoEndcard } from "./scenes/NextVideoEndcard";
import { KeyPhrase } from "./scenes/KeyPhrase";

const B = COLORS.cold, D = COLORS.danger, G = COLORS.good;

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "k_h_ham", start: 1.8, dur: 4.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_ham.png" darken={0} /> },
  { key: "k_h_smokehouse", start: 5.4, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_smokehouse.png" darken={0} /> },
  { key: "k_h_impact1", start: 8.6, dur: 5.2, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/k_h_slice.png" impact="Kept a whole year." setup="No fridge. No freezer." impactAccent="good" hitAt={2} boom={0} darken={0.46} /> },
  { key: "k_h_slice", start: 13.8, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_slice.png" darken={0} /> },
  { key: "k_h_keyphrase", start: 17.9, dur: 4.7, kind: "keyphrase", el: (d) => <KeyPhrase durationInFrames={d} text="No machine. Just salt and smoke." src="img/k_h_nomachine.png" accent="good" fontSize={92} /> },
  { key: "k_h_salt", start: 22.6, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_salt.png" darken={0} /> },
  { key: "k_h_supper", start: 26.6, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_supper.png" darken={0} /> },
  { key: "k_h_winterfarm", start: 30.8, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_winterfarm.png" darken={0} /> },
  { key: "k_h_impact2", start: 34.8, dur: 5, kind: "impact", el: (d) => <ImpactReveal durationInFrames={d} image="img/k_h_cellar.png" impact="Your meat stays safe." setup="The grid goes dark." impactAccent="good" hitAt={1.9} boom={0} darken={0.46} /> },
  { key: "k_h_cellar", start: 39.8, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_cellar.png" darken={0} /> },
  { key: "k_h_hands", start: 44, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_hands.png" darken={0} /> },
  { key: "k_h_meats", start: 48, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_h_meats.png" darken={0} /> },
  { key: "k_salt_smoke_cellar", start: 52.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_salt_smoke_cellar_1.webp" darken={0} /> },
  { key: "k_f_smoke_wisp", start: 57, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_smoke_wisp_1.jpg" darken={0} /> },
  { key: "k_old_hands_ham", start: 60.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_old_hands_ham_1.jpg" darken={0} /> },
  { key: "k_side_pork_hanging", start: 64.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_side_pork_hanging.mp4" darken={0} /> },
  { key: "k_f_bacon_hang", start: 68, dur: 11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_bacon_hang.mp4" darken={0} /> },
  { key: "k_chest_freezer", start: 78.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_chest_freezer.mp4" darken={0} /> },
  { key: "k_f_freezer_meat2", start: 82.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_freezer_meat2.mp4" darken={0} /> },
  { key: "k_f_garage_freezer2", start: 88, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_garage_freezer2.mp4" darken={0} /> },
  { key: "cmp_methods", start: 95.5, dur: 9.5, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Five ways to keep meat — no power" items={["Salt curing (the $5 box of salt)","The smokehouse","The cool cellar","Potting in fat (confit)","Drying (jerky)"]} accent={B} /> },
  { key: "k_f_salt_scoop", start: 105, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_salt_scoop.mp4" darken={0} /> },
  { key: "k_potted_meat_crock", start: 110, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_potted_meat_crock.mp4" darken={0} /> },
  { key: "k_f_cured_board", start: 115, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_cured_board.mp4" darken={0} /> },
  { key: "k_butcher_meat_block", start: 120, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_butcher_meat_block.mp4" darken={0} /> },
  { key: "k_f_butcher_hands", start: 125, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_butcher_hands.mp4" darken={0} /> },
  { key: "k_warning_hand", start: 130, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_warning_hand_1.jpg" darken={0} /> },
  { key: "k_grandfather_smokehouse", start: 138.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_grandfather_smokehouse_1.jpg" darken={0} /> },
  { key: "k_f_old_barn_meat", start: 143, dur: 5.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_old_barn_meat.mp4" darken={0} /> },
  { key: "cmp_freezertrap", start: 156, dur: 9, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Pauses the rot" image="img/cmp_freezertrap_bg.png" eyebrow="A freezer doesn't preserve" caption="every cut is still spoilable — only a steady feed of electricity holds it at the edge of the cliff" accent="danger" hue="red" /> },
  { key: "k_freezer_open_frost", start: 165, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_freezer_open_frost_1.webp" darken={0} /> },
  { key: "k_power_cord_meter", start: 172, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_power_cord_meter.mp4" darken={0} /> },
  { key: "k_thawing_meat", start: 177, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_thawing_meat.mp4" darken={0} /> },
  { key: "k_f_thaw_drip", start: 181, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_thaw_drip_1.jpg" darken={0} /> },
  { key: "k_side_beef_freezer", start: 186.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_side_beef_freezer.mp4" darken={0} /> },
  { key: "cmp_blackout", start: 191, dur: 8, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="$1–2k gone" image="img/cmp_blackout_bg.png" eyebrow="One winter storm" caption="the grid blinks, the freezer thaws, and a weekend wipes out a whole side of beef and a hog" accent="danger" hue="red" /> },
  { key: "k_ice_powerline_down", start: 199, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_ice_powerline_down_1.jpg" darken={0} /> },
  { key: "k_f_storm_dark_house", start: 203, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_storm_dark_house_1.jpg" darken={0} /> },
  { key: "k_spoiled_freezer_loss", start: 208, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_spoiled_freezer_loss.mp4" darken={0} /> },
  { key: "k_freezer_bill", start: 216, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_freezer_bill_1.png" darken={0} /> },
  { key: "k_f_meter_spin2", start: 220, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_meter_spin2.mp4" darken={0} /> },
  { key: "cmp_freezercost", start: 225, dur: 6.5, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Salt + smokehouse","value":1,"display":"~$5 + a build","sub":"no bill, ever","winner":true},{"label":"Chest freezer","value":60,"display":"$500+ & power","sub":"humming all year"}]} eyebrow="Same job" title="Keeping a year of meat" unit="USD" accent="good" hue="amber" /> },
  { key: "k_thinking_old_man", start: 231.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_thinking_old_man_1.png" darken={0} /> },
  { key: "k_store_freezers_row", start: 236, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_store_freezers_row_1.jpg" darken={0} /> },
  { key: "k_f_appliance_aisle", start: 241, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_appliance_aisle.mp4" darken={0} /> },
  { key: "k_cash_register2", start: 248, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_cash_register2.mp4" darken={0} /> },
  { key: "k_appliance_store", start: 253.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_appliance_store.mp4" darken={0} /> },
  { key: "k_f_money_count", start: 257, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_money_count.mp4" darken={0} /> },
  { key: "k_salt_sack", start: 261.5, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_salt_sack_1.jpg" darken={0} /> },
  { key: "k_ham_rafter", start: 266.5, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_ham_rafter.mp4" darken={0} /> },
  { key: "k_humming_box", start: 271.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_humming_box.mp4" darken={0} /> },
  { key: "k_f_lone_freezer", start: 275, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_lone_freezer.mp4" darken={0} /> },
  { key: "k_leash_chain", start: 279.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_leash_chain.mp4" darken={0} /> },
  { key: "k_f_old_pantry_full", start: 285, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_old_pantry_full.mp4" darken={0} /> },
  { key: "k_f_smoked_variety", start: 292, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_smoked_variety_1.jpg" darken={0} /> },
  { key: "cmp_secret", start: 297.5, dur: 12, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="The whole secret" items={["Rot needs tiny living things — bacteria","Bacteria must have water to live","Cold only slows them (never kills)","The old ways take the water away"]} accent={D} cross /> },
  { key: "k_water_droplet_macro", start: 309.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_water_droplet_macro.mp4" darken={0} /> },
  { key: "k_f_ice_crystal", start: 313, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_ice_crystal.mp4" darken={0} /> },
  { key: "k_f_meat_turning", start: 320, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_meat_turning.mp4" darken={0} /> },
  { key: "k_salt_on_meat", start: 325, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_salt_on_meat_1.jpg" darken={0} /> },
  { key: "k_salt_draw_water", start: 329.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_salt_draw_water.mp4" darken={0} /> },
  { key: "k_smoke_meat_seal", start: 335, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_smoke_meat_seal_1.jpg" darken={0} /> },
  { key: "k_fat_sealed_crock", start: 340.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_fat_sealed_crock_1.jpg" darken={0} /> },
  { key: "k_f_fat_seal2", start: 344, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_fat_seal2_1.jpg" darken={0} /> },
  { key: "k_pantry_shelf_meat", start: 348, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_pantry_shelf_meat_1.png" darken={0} /> },
  { key: "k_dark_cellar_meat", start: 354, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_dark_cellar_meat_1.jpg" darken={0} /> },
  { key: "k_box_plain_salt", start: 361.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_box_plain_salt_1.jpg" darken={0} /> },
  { key: "cmp_cure", start: 366, dur: 10.5, kind: "curediagram", el: (d) => <CureDiagram durationInFrames={d} eyebrow="How the salt cure works" title="Salt is thirsty" saltTag="salt pulls the water out" waterTag="bacteria can't live" keepTag="keeps a year" /> },
  { key: "k_salt_pour_hand", start: 376.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_salt_pour_hand.mp4" darken={0} /> },
  { key: "k_salt_crystals_macro", start: 380, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_salt_crystals_macro.mp4" darken={0} /> },
  { key: "k_meat_in_brine", start: 388, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_meat_in_brine_1.jpg" darken={0} /> },
  { key: "k_f_meat_brine2", start: 393, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_meat_brine2.mp4" darken={0} /> },
  { key: "cmp_meatcross", start: 398, dur: 8, kind: "cross", el: (d) => <CrossSection durationInFrames={d} layers={[{"label":"Salty dry rind — no water left","color":"#e8e2d2","weight":0.6},{"label":"Smoke-sealed skin — flies can't pass","color":"#6b4f2e","weight":0.5},{"label":"Rosy cured meat — good for a year","color":"#b8434a","weight":1.6}]} eyebrow="Why it keeps" title="Inside a cured ham" marker={{"label":"cured to the bone","atDepth":0.5,"color":"good"}} hue="amber" /> },
  { key: "k_f_salt_pork2", start: 406, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_salt_pork2.mp4" darken={0} /> },
  { key: "k_two_methods_meat", start: 411, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_two_methods_meat_1.jpg" darken={0} /> },
  { key: "cmp_twoways", start: 415, dur: 7, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Two ways to salt" items={["DRY: bury the cut in a salt box","Re-salt partway, pour off the water","BRINE: salt water that floats an egg","Sugar + spices = corned beef, hams"]} accent={G} /> },
  { key: "k_f_rub_salt2", start: 422, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_rub_salt2.mp4" darken={0} /> },
  { key: "k_rub_salt_meat", start: 428.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_rub_salt_meat.mp4" darken={0} /> },
  { key: "k_f_bury_salt2", start: 432, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_bury_salt2_1.jpg" darken={0} /> },
  { key: "k_brine_drip_off", start: 440.5, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_brine_drip_off.mp4" darken={0} /> },
  { key: "cmp_curetime", start: 446.5, dur: 10.5, kind: "stat", el: (d) => <StatBig durationInFrames={d} value={2} prefix="1½–" suffix=" days / lb" label="of curing — kept cold, just above freezing, the old butcher's rule" eyebrow="How long to cure" accent="good" hue="amber" /> },
  { key: "k_bacon_slab_cure", start: 457, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_bacon_slab_cure.mp4" darken={0} /> },
  { key: "k_f_bacon_curing2", start: 462, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_bacon_curing2.mp4" darken={0} /> },
  { key: "k_ham_leg_salt", start: 466.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_ham_leg_salt.mp4" darken={0} /> },
  { key: "k_f_ham_salt2", start: 471, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_ham_salt2.mp4" darken={0} /> },
  { key: "k_resalt_meat", start: 477, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_resalt_meat.mp4" darken={0} /> },
  { key: "k_f_resalt2", start: 482, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_resalt2.mp4" darken={0} /> },
  { key: "k_brine_barrel", start: 488, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_brine_barrel.mp4" darken={0} /> },
  { key: "k_f_barrel_brine2", start: 493, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_barrel_brine2.mp4" darken={0} /> },
  { key: "k_egg_float_brine", start: 497, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_egg_float_brine_1.jpg" darken={0} /> },
  { key: "k_plate_stone_brine", start: 501.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_plate_stone_brine.mp4" darken={0} /> },
  { key: "k_sugar_spices_cure", start: 506, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_sugar_spices_cure.mp4" darken={0} /> },
  { key: "k_f_spices_cure", start: 511, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_spices_cure.mp4" darken={0} /> },
  { key: "k_corned_beef", start: 516.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_corned_beef.mp4" darken={0} /> },
  { key: "k_f_corned_beef2", start: 521, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_corned_beef2.mp4" darken={0} /> },
  { key: "k_brine_soak_crock", start: 525.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_brine_soak_crock_1.jpg" darken={0} /> },
  { key: "k_f_brine_crock2", start: 531, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_brine_crock2.mp4" darken={0} /> },
  { key: "k_cold_smoke_meat", start: 550, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_cold_smoke_meat_1.jpg" darken={0} /> },
  { key: "cmp_curesalt", start: 557.5, dur: 7, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="⚠" title="Use real curing salt (pink, nitrite)" desc="For anything smoked or aged, plain salt is NOT enough. The nitrite guards against botulism — invisible, no smell, no taste. Follow the package." eyebrow="SAFETY — DO NOT SKIP" image="img/cmp_curesalt_bg.png" /> },
  { key: "k_curing_salt_pink", start: 564.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_curing_salt_pink.mp4" darken={0} /> },
  { key: "k_f_pink_salt2", start: 571, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_pink_salt2.mp4" darken={0} /> },
  { key: "k_safety_warning_meat", start: 579, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_safety_warning_meat_1.jpg" darken={0} /> },
  { key: "k_f_measure_scale", start: 587, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_measure_scale.mp4" darken={0} /> },
  { key: "k_measure_cure_salt", start: 595.5, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_measure_cure_salt_1.png" darken={0} /> },
  { key: "k_f_safe_meat2", start: 604, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_safe_meat2.mp4" darken={0} /> },
  { key: "k_dont_guess_salt", start: 611.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_dont_guess_salt_1.jpg" darken={0} /> },
  { key: "k_safe_cured_meats", start: 616, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_safe_cured_meats.mp4" darken={0} /> },
  { key: "k_f_respect_hands", start: 623, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_respect_hands.mp4" darken={0} /> },
  { key: "k_respect_meat", start: 629.5, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_respect_meat_1.jpg" darken={0} /> },
  { key: "k_smoked_ham_glisten", start: 636.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_smoked_ham_glisten_1.webp" darken={0} /> },
  { key: "k_f_smoked_ham2", start: 641, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_smoked_ham2.mp4" darken={0} /> },
  { key: "k_wood_smoke_rising", start: 645.5, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_wood_smoke_rising_1.jpg" darken={0} /> },
  { key: "k_smokehouse_exterior", start: 650.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_smokehouse_exterior.mp4" darken={0} /> },
  { key: "k_f_smokehouse_door", start: 654, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_smokehouse_door.mp4" darken={0} /> },
  { key: "k_barrel_smoker", start: 658, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_barrel_smoker.mp4" darken={0} /> },
  { key: "k_hang_meat_smoke", start: 665.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_hang_meat_smoke_1.jpg" darken={0} /> },
  { key: "k_f_hang_smoke2", start: 669, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_hang_smoke2.mp4" darken={0} /> },
  { key: "k_hardwood_fire_low", start: 674, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_hardwood_fire_low.mp4" darken={0} /> },
  { key: "cmp_woods", start: 681, dur: 11, kind: "chips", el: (d) => <ChipsCluster durationInFrames={d} image="img/cmp_woods_bg.png" title="Best woods to smoke with" chips={["hickory","oak","apple","maple","cherry"]} hue="amber" /> },
  { key: "k_smoke_curl_meat", start: 692, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_smoke_curl_meat_1.jpg" darken={0} /> },
  { key: "k_meat_skin_sealed", start: 699, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_meat_skin_sealed_1.jpg" darken={0} /> },
  { key: "k_f_sealed_skin2", start: 703, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_sealed_skin2.mp4" darken={0} /> },
  { key: "cmp_keeps", start: 708, dur: 4, kind: "bars", el: (d) => <BarCompare durationInFrames={d} bars={[{"label":"Smoked ham / bacon","value":12,"display":"~1 year","winner":true},{"label":"Potted in fat","value":8,"display":"~months","tone":"amber"},{"label":"Dried jerky","value":8,"display":"~months","tone":"amber"}]} eyebrow="Cured & stored cool" title="How long it keeps (no power)" unit="months" accent="good" hue="amber" /> },
  { key: "cmp_smoke", start: 712, dur: 9, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Nature's preservative" image="img/cmp_smoke_bg.png" eyebrow="Why smoke works" caption="it seals the surface into a tough skin AND its natural substances kill what causes spoiling" accent="good" hue="amber" /> },
  { key: "k_smoked_bacon_side", start: 721, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_smoked_bacon_side_1.jpg" darken={0} /> },
  { key: "k_f_smoked_side", start: 727, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_smoked_side.mp4" darken={0} /> },
  { key: "k_two_smoke_types", start: 733, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_two_smoke_types.mp4" darken={0} /> },
  { key: "cmp_smoketypes", start: 739, dur: 9, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="Cold smoke vs hot smoke" items={["COLD: cool, preserves, does NOT cook","→ needs the cure + curing salt first","HOT: warm, cooks as it smokes","→ for sausage & fish you eat soon"]} accent={B} /> },
  { key: "k_cure_then_smoke", start: 748, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_cure_then_smoke_1.jpg" darken={0} /> },
  { key: "k_f_cure_to_smoke", start: 755, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_cure_to_smoke.mp4" darken={0} /> },
  { key: "k_hot_smoke_sausage", start: 760.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_hot_smoke_sausage.mp4" darken={0} /> },
  { key: "k_f_hot_smoke2", start: 766, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_hot_smoke2.mp4" darken={0} /> },
  { key: "k_cold_smoke_year", start: 772.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_cold_smoke_year_1.jpg" darken={0} /> },
  { key: "k_f_cold_smoke_ham", start: 777, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_cold_smoke_ham_1.webp" darken={0} /> },
  { key: "k_salt_smoke_hang", start: 781, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_salt_smoke_hang.mp4" darken={0} /> },
  { key: "k_f_hang_age", start: 786, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_hang_age_1.jpg" darken={0} /> },
  { key: "k_cellar_steps_meat", start: 791.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_cellar_steps_meat.mp4" darken={0} /> },
  { key: "k_f_cellar_steps2", start: 798, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_cellar_steps2.mp4" darken={0} /> },
  { key: "k_rootcellar_apples_meat", start: 803.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_rootcellar_apples_meat_1.jpg" darken={0} /> },
  { key: "k_f_cellar_apples_meat", start: 808, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_cellar_apples_meat.mp4" darken={0} /> },
  { key: "k_sausage_coil_hang", start: 813.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_sausage_coil_hang.mp4" darken={0} /> },
  { key: "k_f_sausage_hang", start: 818, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_sausage_hang.mp4" darken={0} /> },
  { key: "k_wrapped_ham_cloth", start: 822, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_wrapped_ham_cloth.mp4" darken={0} /> },
  { key: "k_f_wrapped_meat", start: 826, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_wrapped_meat.mp4" darken={0} /> },
  { key: "k_airy_cellar_meat", start: 835, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_airy_cellar_meat_1.jpg" darken={0} /> },
  { key: "cmp_cellar", start: 843, dur: 13.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="The pantry" image="img/cmp_cellar_bg.png" eyebrow="The cool cellar" caption="the cellar isn't preserving — the salt and smoke already did. It's just where a year of meat hangs and waits" accent="good" hue="cold" /> },
  { key: "k_cut_ham_slice", start: 856.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_cut_ham_slice.mp4" darken={0} /> },
  { key: "k_f_ham_slice2", start: 861, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_ham_slice2.mp4" darken={0} /> },
  { key: "k_potted_meat_jar", start: 870.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_potted_meat_jar_1.jpg" darken={0} /> },
  { key: "cmp_confit", start: 877, dur: 8, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Sealed in fat" image="img/cmp_confit_bg.png" eyebrow="Potting / confit" caption="cook the meat in fat, then bury it under a solid cap of fat — no air, no rot. Keeps cooked meat months on a shelf" accent="good" hue="amber" /> },
  { key: "k_confit_duck_fat", start: 885, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_confit_duck_fat_1.jpg" darken={0} /> },
  { key: "k_lard_fat_white", start: 892.5, dur: 9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_lard_fat_white_1.jpg" darken={0} /> },
  { key: "k_meat_in_fat_pot", start: 901, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_meat_in_fat_pot.mp4" darken={0} /> },
  { key: "k_f_meat_in_fat2", start: 905, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_meat_in_fat2.mp4" darken={0} /> },
  { key: "k_pork_shoulder_confit", start: 910, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_pork_shoulder_confit_1.jpg" darken={0} /> },
  { key: "k_f_shoulder_fork", start: 916, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_shoulder_fork.mp4" darken={0} /> },
  { key: "k_pack_crock_meat", start: 921.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_pack_crock_meat.mp4" darken={0} /> },
  { key: "k_f_pack_crock2", start: 926, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_pack_crock2_1.jpg" darken={0} /> },
  { key: "k_pour_fat_over", start: 930.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_pour_fat_over_1.jpg" darken={0} /> },
  { key: "k_f_pour_fat2", start: 934, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_pour_fat2_1.jpg" darken={0} /> },
  { key: "k_sealed_fat_cap", start: 938.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_sealed_fat_cap_1.jpg" darken={0} /> },
  { key: "k_f_fat_cap2", start: 945, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_fat_cap2_1.jpg" darken={0} /> },
  { key: "k_potted_cellar_shelf", start: 950, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_potted_cellar_shelf_1.jpg" darken={0} /> },
  { key: "k_crock_fat_dark", start: 957.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_crock_fat_dark_1.jpg" darken={0} /> },
  { key: "k_rich_potted_dish", start: 964, dur: 11, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_rich_potted_dish.mp4" darken={0} /> },
  { key: "k_drying_strips_air", start: 974.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_drying_strips_air.mp4" darken={0} /> },
  { key: "cmp_drying", start: 979, dur: 9, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Just moving air" image="img/cmp_drying_bg.png" eyebrow="Drying / jerky" caption="thin strips, salted, hung in dry breezy air — the lightest, longest-keeping meat there is" accent="good" hue="amber" /> },
  { key: "k_f_cut_strips2", start: 988, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_cut_strips2.mp4" darken={0} /> },
  { key: "k_hang_strips_dry", start: 992, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_hang_strips_dry_1.jpg" darken={0} /> },
  { key: "k_f_hang_dry2", start: 996, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_hang_dry2_1.jpg" darken={0} /> },
  { key: "k_dried_jerky_hard", start: 999.5, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_dried_jerky_hard.mp4" darken={0} /> },
  { key: "k_jerky_biltong", start: 1006.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_jerky_biltong_1.jpg" darken={0} /> },
  { key: "k_f_jerky_dark", start: 1010, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_jerky_dark.mp4" darken={0} /> },
  { key: "k_jerky_sack", start: 1014, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_jerky_sack_1.jpg" darken={0} /> },
  { key: "k_f_jerky_sack2", start: 1018, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_jerky_sack2_1.jpg" darken={0} /> },
  { key: "k_jerky_pocket_travel", start: 1023, dur: 14.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_jerky_pocket_travel.mp4" darken={0} /> },
  { key: "k_butchering_day", start: 1037, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_butchering_day.mp4" darken={0} /> },
  { key: "k_late_fall_cold_farm", start: 1043.5, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_late_fall_cold_farm.mp4" darken={0} /> },
  { key: "k_cold_butcher_work", start: 1051, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_cold_butcher_work.mp4" darken={0} /> },
  { key: "k_f_cold_barn2", start: 1055, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_cold_barn2.mp4" darken={0} /> },
  { key: "k_f_salt_fresh2", start: 1062, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_salt_fresh2_1.jpg" darken={0} /> },
  { key: "k_nothing_wasted_hog", start: 1068.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_nothing_wasted_hog_1.jpg" darken={0} /> },
  { key: "cmp_butchering", start: 1072, dur: 8, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="Nothing wasted" image="img/cmp_butchering_bg.png" eyebrow="Butchering day, late fall" caption="hams & bacon cured, trimmings to sausage, fat to lard — one hog became a whole year of suppers" accent="good" hue="amber" /> },
  { key: "k_f_lard_render2", start: 1080, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_lard_render2.mp4" darken={0} /> },
  { key: "k_f_full_pantry2", start: 1086, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_full_pantry2_1.webp" darken={0} /> },
  { key: "k_year_of_food", start: 1090, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_year_of_food_1.jpg" darken={0} /> },
  { key: "cmp_numbers", start: 1099.5, dur: 12, kind: "process", el: (d) => <ProcessSteps durationInFrames={d} steps={[{"title":"Use plenty of salt"},{"title":"1½–2 days per pound"},{"title":"Cure cold, above freezing"},{"title":"Curing salt for smoked/aged"},{"title":"Hang in cool, dark, dry"}]} eyebrow="Get these right" title="The numbers to remember" accent="amber" hue="amber" /> },
  { key: "k_salt_heap", start: 1111.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_salt_heap.mp4" darken={0} /> },
  { key: "k_cure_cold_cellar", start: 1116, dur: 12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_cure_cold_cellar_1.jpg" darken={0} /> },
  { key: "k_pink_cure_salt2", start: 1127.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_pink_cure_salt2_1.webp" darken={0} /> },
  { key: "k_f_pink_measure", start: 1131, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_pink_measure_1.jpg" darken={0} /> },
  { key: "k_cold_vs_hot_smoke2", start: 1135.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_cold_vs_hot_smoke2_1.jpg" darken={0} /> },
  { key: "k_f_two_smokers", start: 1139, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_two_smokers_1.jpg" darken={0} /> },
  { key: "cmp_system", start: 1142.5, dur: 7, kind: "splitlist", el: (d) => <SplitList durationInFrames={d} title="A whole plain system" items={["Salt — pulls the water, stops the rot","Smoke — seals the surface","Cellar — where it hangs & waits","Fat & dry air — the rest"]} accent={G} /> },
  { key: "k_whole_meat_system", start: 1149.5, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_whole_meat_system_1.jpg" darken={0} /> },
  { key: "k_f_pantry_system", start: 1156, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_pantry_system_1.jpg" darken={0} /> },
  { key: "k_salt_work2", start: 1160.5, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_salt_work2_1.jpg" darken={0} /> },
  { key: "k_smoke_seal2", start: 1166.5, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_smoke_seal2_1.jpg" darken={0} /> },
  { key: "k_cellar_hangs", start: 1170.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_cellar_hangs_1.jpg" darken={0} /> },
  { key: "k_fat_and_dry", start: 1175, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_fat_and_dry_1.jpg" darken={0} /> },
  { key: "k_no_wire_meat", start: 1181.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_no_wire_meat.mp4" darken={0} /> },
  { key: "k_f_no_wire2", start: 1185, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_no_wire2.mp4" darken={0} /> },
  { key: "k_blackout_neighbor_meat", start: 1189.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_blackout_neighbor_meat.png" darken={0} /> },
  { key: "k_f_dark_freezer2", start: 1195, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="img/k_f_dark_freezer2.png" darken={0} /> },
  { key: "cmp_safety", start: 1201, dur: 9.86, kind: "checklist", el: (d) => <Checklist durationInFrames={d} title="Do it safe" items={[{"text":"Curing salt for smoked/aged — follow the package","state":"done"},{"text":"Cure cold, just above freezing","state":"done"},{"text":"Plenty of salt — under-salting is the #1 failure","state":"done"},{"text":"Smells foul or slimy? Throw it out","state":"done"}]} eyebrow="Respect the meat" accent="good" hue="red" image="img/cmp_safety_bg.png" /> },
  { key: "k_cure_salt_hams", start: 1230, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_cure_salt_hams.mp4" darken={0} /> },
  { key: "k_f_cure_salt3", start: 1235, dur: 9.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_cure_salt3_1.jpg" darken={0} /> },
  { key: "k_meat_cold_cure2", start: 1244, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_meat_cold_cure2.mp4" darken={0} /> },
  { key: "k_cold_months_cure", start: 1251, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_cold_months_cure_1.jpg" darken={0} /> },
  { key: "k_f_winter_cure", start: 1255, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_winter_cure_1.jpg" darken={0} /> },
  { key: "k_plenty_salt2", start: 1260, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_plenty_salt2_1.webp" darken={0} /> },
  { key: "k_f_salt_plenty", start: 1264, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_salt_plenty.mp4" darken={0} /> },
  { key: "k_clean_tools_meat", start: 1269.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_clean_tools_meat.mp4" darken={0} /> },
  { key: "k_smell_check_meat", start: 1273, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_smell_check_meat.mp4" darken={0} /> },
  { key: "k_f_smell_meat", start: 1278, dur: 11.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_smell_meat_1.jpg" darken={0} /> },
  { key: "k_discard_bad_meat", start: 1289, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_discard_bad_meat_1.jpg" darken={0} /> },
  { key: "k_world_fed_safely", start: 1295.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_world_fed_safely_1.png" darken={0} /> },
  { key: "k_f_safe_cured3", start: 1300, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_safe_cured3_1.jpg" darken={0} /> },
  { key: "k_one_mistake_meat", start: 1309.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_one_mistake_meat_1.jpg" darken={0} /> },
  { key: "cmp_mistake", start: 1314, dur: 6.5, kind: "mistake", el: (d) => <MistakeCard durationInFrames={d} number="1" title="Too little salt, or too much warmth" desc="Both leave water for the rot to take hold. Use the full salt the old recipes call for, and cure in the cold. That's the whole of it." eyebrow="THE ONE MISTAKE" image="img/cmp_mistake_bg.png" /> },
  { key: "k_not_enough_salt", start: 1320.5, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_not_enough_salt_1.jpg" darken={0} /> },
  { key: "k_timid_salt", start: 1326.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_timid_salt_1.jpg" darken={0} /> },
  { key: "k_f_timid_salt2", start: 1331, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_timid_salt2_1.jpg" darken={0} /> },
  { key: "k_warm_room_spoil", start: 1337, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_warm_room_spoil.mp4" darken={0} /> },
  { key: "k_f_warm_spoil2", start: 1341, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_warm_spoil2_1.webp" darken={0} /> },
  { key: "k_full_salt_cold", start: 1346.5, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_full_salt_cold.mp4" darken={0} /> },
  { key: "k_f_full_salt2", start: 1351, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_full_salt2_1.webp" darken={0} /> },
  { key: "k_one_true_idea", start: 1356, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_one_true_idea_1.jpg" darken={0} /> },
  { key: "k_take_water_air", start: 1362.5, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_take_water_air_1.jpg" darken={0} /> },
  { key: "k_f_water_leaving", start: 1366, dur: 5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_water_leaving.mp4" darken={0} /> },
  { key: "k_salt_well_cure_cold", start: 1370.5, dur: 8.61, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_salt_well_cure_cold_1.jpg" darken={0} /> },
  { key: "k_fry_bacon_pan", start: 1398.5, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_fry_bacon_pan.mp4" darken={0} /> },
  { key: "k_f_fry_bacon2", start: 1404, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_fry_bacon2_1.jpg" darken={0} /> },
  { key: "k_home_cured_pride", start: 1410, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_home_cured_pride_1.jpg" darken={0} /> },
  { key: "k_f_proud_meat", start: 1416, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_proud_meat.mp4" darken={0} /> },
  { key: "cmp_almanac", start: 1421.5, dur: 10.5, kind: "callout", el: (d) => <CalloutMark durationInFrames={d} figure="The Plain Almanac" image="img/cmp_almanac_bg.png" eyebrow="Below this video" caption="the salt & brine recipes by weight, a barrel smokehouse, potting, drying, sausage — exactly how much & how long, safe" accent="good" hue="amber" /> },
  { key: "k_f_recipes2", start: 1432, dur: 4.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_f_recipes2.mp4" darken={0} /> },
  { key: "k_recipes_plans", start: 1436, dur: 8.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/k_recipes_plans.mp4" darken={0} /> },
  { key: "k_f_offgrid_family2", start: 1444, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_f_offgrid_family2_1.jpg" darken={0} /> },
  { key: "k_gathered_guide", start: 1449.5, dur: 10, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_gathered_guide_1.png" darken={0} /> },
  { key: "cmp_next", start: 1459, dur: 8, kind: "nextvideo", el: (d) => <NextVideoEndcard durationInFrames={d} title="Keep milk, butter & cream fresh all summer — no ice" kicker="Next time" sub="Fresh every single day, no cold box of any kind. Meat today, milk next time." /> },
  { key: "k_springhouse_milk", start: 1467, dur: 7.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="real/k_springhouse_milk_1.jpg" darken={0} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [

];
